apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gramps-data
  namespace: gramps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
