apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gramps

resources:
  - 00-namespace.yaml
  - 10-pvc.yaml
  - 14-pv-media.yaml
  - 15-pvc-media.yaml
  - 20-redis-deployment.yaml
  - 21-redis-service.yaml
  - 30-deployment.yaml
  - 40-service.yaml
  - 52-httproute-public.yaml
  - 53-httproute-internal.yaml

images:
  - name: ghcr.io/gramps-project/grampsweb
    newTag: "26.9.1"
  - name: redis
    newTag: "8.10-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0"
