apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: repeaterbook-token
  namespace: sdr-research
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared
  target:
    name: repeaterbook-token
    creationPolicy: Owner
  data:
    - secretKey: repeaterbook-password
      remoteRef:
        key: "fnjtfv3sscwtlfrl5szdac7rna/password"
