apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sdr-viewer-internal
  namespace: sdr-research
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - sdr.internal.white.fm
    secretName: sdr-internal-white-fm-tls
  - hosts:
    - sdr.internal.w3rdw.radio
    secretName: sdr-internal-w3rdw-radio-tls
  rules:
  - host: sdr.internal.white.fm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdr-viewer-ui
            port:
              number: 80
  - host: sdr.internal.w3rdw.radio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sdr-viewer-ui
            port:
              number: 80
