apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intelowl

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - 00-namespace.yaml
  - 10-configmap-env.yaml
  - 10-configmap-nginx.yaml
  - 10-configmap-uwsgi.yaml
  - 20-postgres-statefulset.yaml
  - 21-redis-deployment.yaml
  - 22-rabbitmq-deployment.yaml
  - 30-deployment-web.yaml
  - 31-deployment-daphne.yaml
  - 33-deployment-celery.yaml
  - 40-services.yaml

images:
  - name: intelowlproject/intelowl
    newTag: "v6.8.0"
  - name: intelowlproject/intelowl_nginx
    newTag: "v6.8.0"
  - name: postgres
    newTag: "16-alpine@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea"
  - name: redis
    newTag: "8.10.2-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0"
  - name: rabbitmq
    newTag: "4.3-alpine"
  - name: busybox
    newTag: "1.38"
