apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:iAPNd5zapi/0M6ka8vx5BSKdQQB8LhnSbsaR827D41LRJmsktQqKP0yzPC3bo/Cb39QO/X6roTFrHVprlrAZk9mztvqx9un6WCozbv5JjYnZgouBKW3sMBLwSpp6etbI/xVr0LwoxC2P55Ko02oPT4Dk0zCSbXWzYAnNjIs6oo+2ON75I/RsVJ9kp+ROG1VVyKEMpxK83P2wlPmGhbEHiwGR6Li7+lc9HNh6bpxNrs8lUffIBOJ5a3wgR+rXaH5Q4IkfQxdnfgb4WN2jWfMk4a59W1pNjYzO,iv:CVELAaXDl3CVQQHo2mJSd0/TeobZoFGE4HFTpFvmXyg=,tag:1FqSBizq9KWVINLdMA3qJA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: cloudflared-secret
    namespace: cloudflared
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTlNzSnVPZEEyOUVFWFBw
            ZnpFOFVNSk4rbzZzM0d1aS9YR2dac05qdzFRCnAxM3JVNGJ2dWFOM3pkQkw5ZERI
            b0hjVnBpakd6MU8yRFdlUkdnMjNZancKLS0tIGpSaHV6b29JQzJzRzliaUJSamVC
            aWFwdzJjMXM2TnhtTDNQZkpSTGdGdlUKx+G3EbWx45MkEiDRrX8B3brBx8YjzMnx
            5PV0tq1y69+uw6L5ZxHpsNax9zlkLXVaari+3zFBV/Au3MVNX8sFAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T21:34:21Z"
    mac: ENC[AES256_GCM,data:wu8u9yJpD/luL6r0rKVEBReyLfw3j0do/3Gtw5pgY10XzKnBDlC2reVPCHacu8nO0rZHYyUzIDYkkVhy5srRrvTLXmAoe0ZP6NKzIyD2FiDjOKRFn1uEYT4mc627L/f9VqEUDVpm6A6Rf3o8T+lbLmHzMAE9aEGSvHaN4HEjzCg=,iv:vp+X+9JqGVEEDlIU/5Odfa/zRK8GkiL3kCOV6HdAVN8=,tag:5AhYcoU3McrdB+ju/cCZiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
