apiVersion: v1
kind: Service
metadata:
  name: astronomy-api
  namespace: astronomy
spec:
  selector:
    app: astronomy-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
