apiVersion: v1
kind: Service
metadata:
  name: astronomy-ui
  namespace: astronomy
spec:
  selector:
    app: astronomy-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  type: ClusterIP
