apiVersion: v1
kind: Secret
metadata:
    name: monica-mcp-env
    namespace: monica-mcp
type: Opaque
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:sP2uhpWwf3CTgOOsTC5u0Mjo1nyip1JCssjIFcuqKzGhELgGRkelum/vPQdukWjxh+IWZhRUYKIC82ldI6GcXQ==,iv:Uyt8dzUxsByIFIpxfMDAu1Db2tuhA8P4VVoJw9P3SRE=,tag:zKnC/A3plgcbelk9S+qZ6A==,type:str]
    MONICA_EMAIL: ENC[AES256_GCM,data:gCK3aqKHzLWqTyrZCZSt1nai8PbRxDk=,iv:Qp7jnEy+q+rVCyk8OEycehkINwCeuk32FOlgTundLew=,tag:LlPKPY4a/mjgc/LjlEapow==,type:str]
    MONICA_DAV_TOKEN: ENC[AES256_GCM,data:eyB9TXZmsNdbdhwIngO2jpjSbgQUZgrom1sUKpY=,iv:+2Fo9QnO2RL+jiCFYMlTcu1ht5A0jT3at3NgU51FWN8=,tag:XDfZ5ueRjUIp4Dx//LCR6g==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnhXcVppbkFqdFdUR0Q3
            OG5jcTlzMzV0ekU2TTFvd09jUi9IbDZKR2pVCjREejM3MHZIK09EYnp1ek9tUVBt
            L2Y4MWM0ZkFRQmdjOTA0bmpQWnk1VVUKLS0tIDh0djkzaTVPL2t4MFFQMnNYeS9B
            VS9xWmU1UkhxOXBqdnRXUUNuZXBLT1kK2i1iaLJGGvfLTfePJtNWW/mG/KHXzDMV
            mWnL7OIyg2ZRHhoturJDXvx6D6Re07esG2x7L6ZcRkbC3UfPqqOJlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T05:51:16Z"
    mac: ENC[AES256_GCM,data:/lyCte0E8G7CNvuZsQufcjG/HOfoLcDBb1pdhYAOp+3+EYyiD28ZcjMUAC77QilX3o3J2RBIhuFu4gnxy29K0B0L5Trh3cjdHl3KqMooCdpaYNqx73uxaLc+rVpIo01aEMgb4s5DC7s6UuTvUEpunZUDL0bXL9a54Bbmp7OYrIw=,iv:PB9PC+d1FRn+5EtIJnNXrj40ymr0GgyHrmET7sBUOL0=,tag:oqeqPqsIisVBPkvTz2DHTw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
