apiVersion: ENC[AES256_GCM,data:DY0=,iv:tT+WzqjVl0xq5El0rOH46z9386bbjkOrRqlyJ93SUg4=,tag:ffdy9cam/Ea3r9OJUEAdpQ==,type:str]
kind: ENC[AES256_GCM,data:41ZKTWZ0,iv:q+HHDDgiL1Avc/rPifHWUbU5FpTR1Sf+b4XAof2x4lE=,tag:kfG9w79RO/cmZgNf1Jv0Tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TZED7YpF52KykPHJwimlLg==,iv:prt8KaIg7V1BlfNDDZre1pbNV4S6FVvIAU0EJpHEpfo=,tag:/qffN6u2n53S4f4hDhIaJA==,type:str]
    namespace: ENC[AES256_GCM,data:/r9ifJ+ycNcWu1qU,iv:WcgEaz+34j30feOycblwqJ6ohU7pAGwR8/2Bzst9xGQ=,tag:SqZLhK7ShcgoOjwPFTKZbA==,type:str]
type: ENC[AES256_GCM,data:OPWIJmVy,iv:9Qr28+AMUdk9CbAr8ucbVnYfUOifXPyI7+xa7Xa0UWI=,tag:+fCORyWMYlSQ0x8NCRNBYA==,type:str]
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:e9prS8t1KhdHzcuRRhgzbxFRebfFdbar0L3CHun4CvydGIiWM0qqUjoa+VU1qdyCYuW8PrqK8P6uyWkk5PlLTw==,iv:O28TFzsxp1znLSYoXI2kioRqDZF7tD6k6VLiSa3XxU8=,tag:60z9UIiNiMGEvlCcafKHTQ==,type:str]
    FRESHRSS_USER: ENC[AES256_GCM,data:FfWV4czp,iv:hzypk257v6ovXKcGNrbA00CigZCYUiHl3qhi/U6S6QY=,tag:3MewlZsQWPAlmuthiK1vjQ==,type:str]
    FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:AJ0SOtbRB3SQ+hN7a2+u3d1C2fN24w0KEd6o0zIcWLh0h8PmbMTWcOQ4YtFxZMoV,iv:xrpP9+H4zZcwpNxOl+86wV/IeZH2/h/WvomZi+YoGlg=,tag:7wCosrUSPssEV0RI8nzIZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UjcvT0k5cFdUZEVDN0RQ
            SFVTMzFqZnRUNXBGVDMvQ29VMWp0Mzk4YkRBCklqWnUrVVVDYUNxVUlzVHkwdDIx
            QkNGaVhHVGcwSFVjeGFDbXA3cnVUZTgKLS0tIDBxck9oMTFlWnkvZzZuT0FvY3RI
            dlQ0M3VwbzVBdC9vb3E1Sy9xaGRsZEkKpbc7Jm41iddyH/CUnNs6O4zmxwC9y6mn
            0u1ntqNvL0+EDXqpwTBy4TlImQ74oXa4SaArZQ4zX8i5xoG2kEIvdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    lastmodified: "2026-06-29T16:45:34Z"
    mac: ENC[AES256_GCM,data:Yix3DSCFyxQJiyKE4ZZGnaajBDrbfIRapcaGlaEzLPcaD1q3mo1P0faYlKyd5IWqBbb/j5nnX5yTg9wy2BWbvxgQOvwjIwJncTCFec1qWZplJ3L18U55RpOl6UJB53lrUhVLi8GEYLJe9IB2s9YF/4PuoU4+pS4b8bfIxEpkGl8=,iv:WrpLCePhcw/eeBmPasu+TAzIrN9AIJoohI3Oa8Nf4Tw=,tag:MLgC9NDeJgEN/Dni0uRpaw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
