apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:SQuoBi98Q152JYfK5LVLWcjiQdcvIDMZtfvvRu0YzpO/zt9DUKXpIucd6AXNpvatDwOj21rLzBcxoshuDzLf1IJzEAVidUDkBCWlpXUJozvRf2dqYpdtqQ4OcoMmyvnANBKFXI8UcSGjaIksFUipTl9EBt2GasVB+lIvpvG2RewEK/28mIK3ruBHONrqtRHNythet0Ry2GkJiIX/Ucu+M/3h3JbyyZ0Tay0OlKmd1OsbPx5E8TgVdccIXpLdKOqrgYhJo0l1ERVk6nwpf2Ovwn1eS0EZyXfHlGz9yCsmtahhfMufBQl+XkF5lvrbIZYi4bD2BB3DZok5uMJz,iv:98aEi3Noy324S5sm7QbFsPAk3AhKzJLujyiQkoTlVc4=,tag:pyAHdC7soQXTcEA0/BFltw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWXA2OEVBb2tuTS9XVmlH
            SFBBYXVDcEt3WTIwemtLZ0VrUmJ3YXlxb0NFClN4TTZSSmNwZFJxVEZSQUVsOWpu
            Sm1sRVZsbVZQSVc2RDZiTndrd2oxYmMKLS0tIFcvUW5QTlVzVnZYNGFnSEN2Q0wz
            cGNRb0pJWGdJRE5RS00zZnprQ1BWVkkKiUjqXSMdgC4G2EwfadaYiXbWLvLxlkx9
            lHhDDCtyHp09HzslHmiyrwbdJ+y0eVKvrGT/ZvlcuFLTd74l+3WwVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T05:09:43Z"
    mac: ENC[AES256_GCM,data:ase8xWKU0hQHmedgtCbGEUGI6YhnzVRGE6lFpHTbOuT1AVZtTOlNArJdXINZBISdmnB1pXMtI9qyi8JDGDEaC9t35sZ9qIbLjUa6t9BmNP/4wMdJ/HCuS5W1EU7BZ33wNlsdeucnDduDhOYD+JCLeBNSkcFRauYXblS/DsGeD1M=,iv:iunByUVownTb6+2YRbMXww8/RtKwD3OAsANw9AFzAB0=,tag:ob0KJW2MS8ZvtCTFuVzfuQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
