apiVersion: v1
kind: Secret
metadata:
    name: freshrss-digest-secrets
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_USERNAME: ENC[AES256_GCM,data:nJHAMrb9,iv:HOmmOVfIkgZXXG4EAacqyotYHwoHiBK7I17zr3euP9I=,tag:kIpN+4PEONhXuBI6s2DFCQ==,type:str]
    FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:i/He1RETpkexHQ7tUCMsattZiQ==,iv:LCvYsWsMUibhV63ABesj4g3BzOmP+ECLc7okmruCamU=,tag:zuKB3BJ/9I+vuJejOu2XVw==,type:str]
    AI_API_KEY: ENC[AES256_GCM,data:Xib+DwQ=,iv:2z/4nPKC4LS2H7MTzfxKL6OGpE1a6zJNa9ElTcnmgCE=,tag:rP41R5cTTYBl0TzcFrxWDw==,type:str]
    MATRIX_WEBHOOK_UUID: ENC[AES256_GCM,data:ffVg2tAm8/wa8wq4cfQHnQ1Cd32KWGX80xlCrnZoMM5xahpY,iv:rUmpT36BpxoWUkqU6r1r7HNmgMg+5kQ2wF9zNVnXDL0=,tag:VRfMKvQy0Se+feU8alFydw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscExsVmdDV1B3M3ZSYzhN
            SGtqNzB6MStWYlVUcnk2VXFqNWp2Y0FiVjFJCjBnVitaSE81aUFqWG1OZVFFRXVE
            ZXZMQjhrTmVEeDhNV2t2THl0SHFmQ0kKLS0tIEw4RUpjbTNGRXQzVFNwREN3UWFS
            Rk1YNmZYemJvd0RqOFZGaGFTNEtqK2MKtGSuCOjmQCP1bJYXzoKMuVi3olXNTh1m
            sNzKesW/jUu9qVgDpxJs/UJ0sYCbYtOMvRv3CdjNREDzpkRId8kq2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T05:17:26Z"
    mac: ENC[AES256_GCM,data:ROq6u/edfqwDhMWWmtcbaf3csFWvW4sMllQa97RfYsqmMHE6WsfRcbwTDWnvT1Hf3effBBCGDCBcpp1uPmvSIkDTxXRICtSLvJNr9lyFUWmc4NCz2prf+gWwRYz93EBQMgyHtgeuocaJi8/7soa9rAtkH58KOwm1ADU+k2HBIl8=,iv:9ac2os7jVD3642TZaTojBFcN5yImL0mY//7lPz/+P4c=,tag:lt/DM5FdkW3Vxkc+gOD4jw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
