apiVersion: v1
kind: Secret
metadata:
    name: scrypted-webhook-secret
    namespace: scrypted
type: Opaque
stringData:
    SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: ENC[AES256_GCM,data:9dQEc7jbd29CxKvPDQL4Lp4JUx1KuUJlVWdLkSk6VHvpN4Nh+GX4zdA2KKAWtwKYOw==,iv:/LV3qBAAn/g2w8CIU3jMwKlkccQvwym6z5NypszcNnc=,tag:SAJd8/pU7yl7MwssEwsZag==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZEtOaUpqY2Z1TFdsbW04
            eVZ5WFI0TWZUbFhYajF3bUY3UFdYekJHTkgwCkNrbU9sVnE2clBSQ01nRy9kSzQ5
            Uk41L0o5ekVUaDVQaXlzWFlqQnNOcmsKLS0tIFVFLzN0NWhNaWQrNzhOQno2dStq
            dDhSNnh4cXJBbWxYSzBualE1ay9Zb1EKhlEz6miqtM86UD748bYwSY4etWuZzGCk
            aV0sB2Z26YNlZapwFHQ6j3cShSGuGfBqIxPUlpqltOpHyb8p6svvCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T04:32:43Z"
    mac: ENC[AES256_GCM,data:1y/Od7dl0zPal58G0s6ddkaSXEwXNTO8dT+nqknp2jQgKiOSML7pYBdNQ1ykUgoLbk9KxF+jhY5GF7LRjU8wRf25sFuqjbigEEsUN/gEaGRzZIREkmYlcuo5gpUQOhJ/ulmKbsE8RPhK7jSHdALcfWnniijCO0RFnl8Irq7uXZA=,iv:Swn/Y2DUAWLvTLgelMP52pmwJufwo2Gkj4Mv/GXzTsQ=,tag:NH126E6Sux+frWGP4QmX3Q==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
