apiVersion: v1
kind: ConfigMap
metadata:
  name: nitter-config
  namespace: nitter
data:
  nitter.conf: |
    [Nitter]
    db = 4
    base = "https://nitter.white.fm"
    title = "nitter"
    port = 8080
    https = false
    httpMaxConnections = 100
    staticDir = "./public"
    whitelist = ""

    [Cache]
    listMinutes = 240
    rssMinutes = 10
    redisHost = "nitter-redis"
    redisPort = 6379
    redisPassword = ""
    redisConnections = 20
    redisMaxConnections = 30

    [Config]
    hmacKey = "change-this-to-a-random-secret"
    base64Media = false
    enableRSS = true
    enableDebug = false
    proxy = ""
    proxyAuth = ""
    tokenCount = 10

    [Preferences]
    replaceTwitter = "nitter.white.fm"
    replaceYouTube = ""
    replaceReddit = ""
    proxyVideos = false
    hlsPlayback = false
    infiniteScroll = false
