apiVersion: v1
kind: Secret
metadata:
    name: riffado-env
    namespace: riffado
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eGQYvoX7uBEnqGhoZuvF12yxccR3d3a9pYsCvBnIUOi6Y/47Ji9pBbn9XKPRIqxYage9H7C0GjMQ5iuLsv075ygCi4QlPNUBuw==,iv:UW3m0/itDAUZXW2tOAKyaif2Wu4PQnzLxkcQxWMue9w=,tag:PYFjcCd0xsu//ZNafF4+pQ==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IlAQ5uP27HmDjoNlXKgetNvVt4isrW/dSiiv7gUSeXTgSI1mBRZnDnKDKbUqp6NB,iv:4TSrfXZ9ycNHb8V6Z5YM6vt6rMwF5J1+gBJCacwsm5Q=,tag:2YxI3pZespVAOGlcD1w3qQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5REH5sCxfxaH9ZGw/KAuPnPpo2eTVBMe8KLcR52UVscrJrAx1yExMT1lj9qaxPw1ahXO0z8tPldn4dY+0nLflq428YO6cPTR8EDBvGkSvphKfhWsQEQEU+cQIi260F9vQI//ZQ==,iv:rDOiOb3LIK5ZHRJvMlJATeaFrbfzRC4LfeaM4q1+YWg=,tag:YGjuRjghE625QfgFFvM4Yg==,type:str]
    #ENC[AES256_GCM,data:2rRaCjowZ1fWHvO5dZBbk9BOj2aFqaoxkbGRSA04k+mAzlZ0,iv:8duwuk9GYo2Qduv7su7LYcGKLnaw7nyw4iu010kOFYA=,tag:bSAw3m07mtgYAZOY90aweA==,type:comment]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:f0Wi8OiToEPy2/56w8ow92VfNqhJVU/CDb3IN5+Msg4M4tdtwzn1CD1uJK9Mo98VQhKZwyNlD/Eh82xkvW0DxQ==,iv:8lCdk0U+nCsJTDoT8LEYVD9HuYOjPqO1dkuYI5n89I8=,tag:94isFPTA3atkrnAsfddiKg==,type:str]
    #ENC[AES256_GCM,data:5RxJtqeuerE0E9uSmu1pVCKg+4PzixElqQogVUqjyCQjPTILRn/nqXxpzqBpPG45sRf+Kyu+FYEKIqzrHtKLkjkcs2s7lZiu3A==,iv:hJA7hKnP1iycKFECKTTJD2+4cK1L7H/0lmHOL5BA4qA=,tag:7RCyS0faTifdqfkwX7aXkw==,type:comment]
    #ENC[AES256_GCM,data:bXivqdr3afdWWFU/1v/YRVLeQpwFkoVurQ2N+1eeehn1in9NJh6Bn2V3HJRVel3FIT9T1AYPvQrz4Kq5Jkn2cGHEXC1F0dNy2fJx,iv:EVDxi4IaXy2dgs0buRS+vC46Y4K33xMNQQRr3Ma4QOM=,tag:fQDpsfjLC7InOwxCrMfPdA==,type:comment]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:BwW40TWNwVPgvdxvjmM5UfBxU1LJuGz/z9y9G6YfYkdWPSpTkx5oORvlogFFkH7hSmVkRBHJJOvlC7RV36RjRA==,iv:yljk1uQ03yeagV3SG57fZMBZlgQMv5cczU1hf2G1hqw=,tag:BOZPVqfrArDR6qxAh9A4ew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaFRDZ041cFBHaXM2ZWNp
            MkR2UWtwWUJuYmxrdTFGNTdVK2plbHRobEc4CktGY0hXODlQWVY4ZVlheWVEU3RB
            MVd1eUN3MXl1cGdwQ3lQVXJVRmE1K28KLS0tIGZCYk15L1dTUkhGOThPR2hEMWVE
            dGx3VUtEbURBY0J1N2pMcVRuRmMzalEKlcY1hh4/Gt74dxzY2ehWSb55ZrO0KKo+
            F+M6TxvRywlnVxzTUeDAtg9hsl/EcWzzFVAKlXPMzjMCkp45XA1yfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    encrypted_regex: ^(data|stringData|parameters)$
    lastmodified: "2026-09-19T23:57:49Z"
    mac: ENC[AES256_GCM,data:aOKaM6Cd/ipPgOoFBeZOeYGYvVMQZreToc3dIqT3hC3TZkxaUYgQrVijH7PvhLIkzvMQNsE3g4AR//BTF0BxbenJNtgWQKIUZqVg+X52kkng/OyiAN83rwuYerxIE/SjceeHa2quwv4+o+fPZZAkkViC1g54VxA/l/FNGwc881Q=,iv:5hyjgM/+BQITMBg/Tw6DmLX3kOwmklT3cT5K9VYjlsM=,tag:0e3sxHKj7XVmb3MpVlmqlg==,type:str]
    version: 3.13.1
