apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: riffado-nas
  namespace: riffado
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  accessModes: [ReadWriteMany]
  storageClassName: ""
  volumeName: pv-riffado-nas
  resources:
    requests:
      storage: 1Ti
