apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebyte-web
  namespace: nodebyte
  labels:
    app: nodebyte-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodebyte-web
  template:
    metadata:
      labels:
        app: nodebyte-web
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: web
          image: ghcr.io/robertdwhite/nodebyte-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: production
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 30
            failureThreshold: 3
