apiVersion: v1
kind: Secret
metadata:
    name: tailscale-router-authkey
    namespace: headscale
type: Opaque
stringData:
    authkey: ENC[AES256_GCM,data:aWUqfgbYdp+JJebQfZAV75LOzxzOO1mXXQ76Am4YCNvo8MlFhBUZslabeaV5D6ccqbpzQmFxyr7hOC4HsuD0MGdElPT/sr+9P4nhhJ0ej+apUPJUwAwVDA==,iv:MaBHi/P3GzpFRAYENid54o8jSvCVSFYUBgWDGESMjE8=,tag:PeZ7i4YHex5EEJ+kFLXTuw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZE9HSUgyTnZUOWY2T25N
            aXZ1YmErL3J2eGR0cUVQWVZxeUg5N0NRUFJvCmZLZDdIcXJ3VlZkWU9qNUJuYmJE
            U3owb3FFR05BOFlsZXgyUWsrdmswdTgKLS0tIEp3ZFdFNU5FS0xpN2pGc3djQXhx
            VnlzSUxXK1h4WDc0d1JRNHpnWC8rVWsKcEn08X23e3nyQT0CZ/EwJSkQ/TXc8EpH
            XVbyF7GK5NVWloAKYxtHSs8OLttHa5VsaRuy3X6Jvt+4gyKAgKzKBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:27:46Z"
    mac: ENC[AES256_GCM,data:5fy8aHo9FHrvBFayn8NzHFhG3ZAykd5rHDbL1s54uaQjJiTOi1uTYcI3H3XW9Z7fj9/9LX4ym1AChkZxtr4YKUaceE2PzoEJKxKCaXd3gStO9f6U+zqYc372fTALX2rzOLN/yGtzopciAJD7F/J1VQpG3bToycztghY7mOs0gvQ=,iv:u1qoO0ohXvGRNdWjmCMyIGtDO7FeFGHgwnKBE+U1AHA=,tag:cYP5H/gIeHqRcJcUBD3IQQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
