apiVersion: v1
kind: Secret
metadata:
    name: authentik-bootstrap-token
    namespace: headscale
    annotations:
        argocd.argoproj.io/sync-wave: "-10"
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:h1S2k76h8x/coVUPGRYdoloo7HINV2WhYHHgpUqh21VbQI09lBOK3Yos2fZFHQwRoiCW1DGdE6EXjx/p,iv:SGUlIXKrPS9mOOTDLGDDER6NFQ4MwGLkE7BV6brRVCQ=,tag:l16cmzPj8IKm/Vs8aySHsw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRDlabm5sYTl2d2UwL1dq
            aTRMcWplQW5ET3FNWjBZamlLcEE4QVd0WmhFClVaSWhlRXQzcmZhNVlUKzB4TnVx
            SWljS1R5dzVld0R6Smk5VE95NjByNDgKLS0tIGVYVmZ2cnN5aHk5K01mcjJoYnEy
            T0diQkRNdGFGcnp0bXl6WmJ3Nk5uQUkK2Y8uIqtOQjsXnCkhRLGAWSRlriQdh/pM
            13iYCS0Lnr3tjX0l7YN+2WsXoCUfpw4sIjFmBC5f40epLoX22Zb5Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T05:02:13Z"
    mac: ENC[AES256_GCM,data:uhodQvhjGEkmRSyZkU8vfQshy56onW3r5zX08VTyCfw4cX/JDn/CgntLegqsFof/zww37aT0OZWFIYBorINMJ9fW8i36o4CEWJLxB1+z7Mma66cYOhRZJUt8nORFtSjNDfOOTVqgbo6G4yDqxQJqT4gqsFObHZpKJ42RIV83kho=,iv:mM+csMm5NCMroXyGmXF28CyIW0ZbBJc0/su09JWGeWA=,tag:3tYWeArRtTLQftZae88jcA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
