apiVersion: v1
kind: Secret
metadata:
  name: technitium-credentials
  namespace: technitium
type: Opaque
stringData:
  admin-password: "REPLACE_ME_TECHNITIUM_ADMIN_PASSWORD"
  pihole-password: "REPLACE_ME_PIHOLE_PASSWORD"
  sso-authority: "https://auth.internal.white.fm/application/o/technitium-sso/"
  sso-client-id: "REPLACE_ME_AUTHENTIK_CLIENT_ID"
  sso-client-secret: "REPLACE_ME_AUTHENTIK_CLIENT_SECRET"
