apiVersion: v1
kind: Secret
metadata:
    name: technitium-credentials
    namespace: technitium
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:qVOH09pKI9Griv0uk95y12tjJUB0vV9upVJ/mDWuPt0=,iv:F4aC2hskIH0pHFR/w2kKSTvAh2hoi2gBsQXDOkgxNTA=,tag:NeKy2yHmmh8zp/efXhOhyg==,type:str]
    pihole-password: ENC[AES256_GCM,data:u4q8eqShakWKkg==,iv:dTJHiUPX6YvQ18Q8puqVXsh5hUrWKMO7XM14EuLXKuc=,tag:Nd55ED8ymSWh+pOG8eW+HA==,type:str]
    sso-client-id: ENC[AES256_GCM,data:0k9l+iO7GnxMrFgTD47derBoRGyNTLqMlv2dVYRDx26DDVDNmNAykQ==,iv:jYnZCS+FfwYp5tU6BsbHJw5WRjRmHi3gACweCM1OGhg=,tag:ujuPJaMTJ+Yl+Wv+SXFrtg==,type:str]
    sso-client-secret: ENC[AES256_GCM,data:F9S+JT9y39cxvM9mYmuFYekXCbS/iNWUh6fYFxOm8zT27g3rk5FpkgCy5Rw6zc+kNmDQvxhUFUBSYj34hNbHHj2Q/Uu1UHjC7Xk19SMWM0U8vzt8ITuiKM5ymaYsVMHM9qMEYh72V+VvpZt3c1a6YHK+TUeaF1yEusdonvhMjso=,iv:Gbm7/usNf0Zsi40meHavcVaMgYIQ8XktlMsLxJDlwOw=,tag:D6eUF8lUgf9FJUxHxgF5yw==,type:str]
    sso-authority: ENC[AES256_GCM,data:CbZbse/gvlPyJCiA0BUu7eTWmmkkMgy+qeIa2FKXeESEftZEUIREPtAzcRExy4gFIu1OVIPE0RszrjYC,iv:XJKWreYQ3QK5bdmWplrqPJnZh2FHcSonYIkNupnQkMg=,tag:z85RejduF7AiKYRseGebfg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd2tONmhaK3laOXk4eVV2
            NUljUWZsb2FVc1lFc0QxcVZ0ZVhDMDYzbmtVClhmSVUzeWN2ajBKMVZ2QUVnY0NO
            bkRyWjMvVFdlTWpSMUtrMGtjdVNERDQKLS0tIDNoMkRWUHJsVCtwQ2hOL2I1aVRW
            Y01VYkxUTmdHWndwc0hzYTN5MzZ2aG8KoKPAkKXpalciBrutJDUkyMxuTg7gxkJL
            FR3iOvN2Ic3Fp4/j8V5Qv75pjzevYN9H9oAfZl36ogSUwx7+tuPdLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T17:06:19Z"
    mac: ENC[AES256_GCM,data:gyvDjz7SdC6gR7IPrr7E74bWNRmSmGwEm3d71feM8vwgwcIn3VjhoAOloajLYTjzAM0oFOquLJMNpMlv9Ns/ZkF/lazjmqjAjenPlXqgO+eRf0Gi5RSfs0mVIRBbupYB2j6lxl60ZRklUUmr16C5Ae0owl1dhjq9JuNV6hc4euY=,iv:VU4tnJ8X+iX6uWs4uMzx5wxBuESwiJRgAcnFMEkNSNk=,tag:PY1SH6xe7cp17fubFQB6NA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
