apiVersion: v1
kind: Secret
metadata:
    name: odysseus-secret
    namespace: odysseus
type: Opaque
stringData:
    ODYSSEUS_ADMIN_PASSWORD: ENC[AES256_GCM,data:C8D0605tRI8HKWZAhTvhTdhqGE9ujojEn9zm7g==,iv:NSie7A4CLVJl43twMFlW9ewISgqogSTtx+pjNDwQkfk=,tag:QOZF22pJaUqwFjQOLOy2pQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0U0FFOGNLZ05TZm52Nmpm
            ZTZoNWNhS1Z1SEFCMk82aWlReHYrbWU4T3c4CkhyMGFBanpWM1JxNEJjdmtHSmlX
            WTc4YUI2M002SWNqYndCVENxTEo3ZjQKLS0tIEZZdGVoc29wTnZaU0Y2bG5XZFJQ
            a3p0enpYVDN3andiWDdGeEkraldqUm8K2NOxfJsOSFS1eorwJ0Ch67RVEqhB+yca
            CCp5IDHTW/DopDhJYQt2/jp/PyapkjVENHL6Wsq+/0Qj9/FL8p13rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T21:48:25Z"
    mac: ENC[AES256_GCM,data:B2qJaxVmjdEQZDY/rkoY4KVrNxpD16oRQ1NJBCCaYFPEsyfNY32CX6vJMk1vDE/7FI46Kr+ksObGSmuRpf/FOOo45lxlBo7u5zZtRKNLR0Y9SKF+dFTmx1znLtUTStbJK0MLtu7OZ7Ri41dZQWGX4/5C1yRmwFnqw3QkYWE2U/c=,iv:oLpz76Mg/30bdrhgEf/VrKv9yIcxzmeja6TUsCn3Psg=,tag:G4i2j54O1LvuaSPGf9qUOw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
