apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: odysseus
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:7wAjfqtNW8Fm0i9xAxZ6VrLk5C1W1g2MBe0/VSSaOIP6kKZ4cv8x9lzY2jYA5v3fdATYWrx8faQjD5yUmtoZwyFKcS/6Cf3e7/IL4lihzg9kJVmOcjU3/Vpr06Lt3kQGmyQBQ9MjGcd+TpD9SnvOR6gXSRM45qVV1DpshdvyRFZ5zBUIG8qVZlkgtOST5ZgsxD0ntwPFKoesXZLyiGnvZKwTB3HBbgjbF3Yd6Vss6zmb0+121NMAoSR9S+rVEo3/,iv:EqveIjkMIeRfYAZYg9FY1RhA86tN3qdYV0ylEKSyJy4=,tag:l34F/pJkTpIWi8CBHj2KEw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU1Q4WjNvTWlxWFRyRlQ1
            RUMrdTZiWmZWYVYzb1AwM2tuSHN6TFkrRUNJCmVtZis0M05Dd3UvVWtadnovYjdj
            WDM0UXNUUFpNbWJYWkV3WTBZMVFnKzgKLS0tIHdXSDB0RmQzL1pXNWxLM2F3UEJu
            S2MzVjNnMFJGMmc2b1J1QjBkUzhBQmsKLMalCBEXxiL20O9/eRxWJulLTs3eHIQy
            ukkwDTQIklJjsN+JHwhOl3byUOSDcCwYXL7gqPxiKuUyG3KkZidbuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T22:01:57Z"
    mac: ENC[AES256_GCM,data:EUdaHT2DonCekmNumaeVTKPKJxUlJ58LZU96zBAADoOtN+1VbZR9WawpCVUGXx1HgNxA4RVGhTKr6TmsJl14j32mFRA8EyMOzOiFwtnpVBVO/wExOmKZ+EwvHps/csPWK4fPBpw5VSZHBveCyAikV8ESFoshqitYryxd+YrOT4E=,iv:WqzO0yPjGXgVsyek3Pd52+kGXJvTKKnLrASCBOWsyPQ=,tag:Ps24bb1KjloPBnkAR+Fkkg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
