apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hub

resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 20-service.yaml
  - 53-httproute-internal.yaml

generators:
  - ksops.yaml

images:
  - name: registry.internal.white.fm/hub-ui
    newName: ghcr.io/robertdwhite/hub-ui
    digest: sha256:3426602329a5e722e5eecb71ff08f97068fe24d9f0f66dcc4d3fb74b95691f14
