apiVersion: viaduct.ai/v1
kind: Ksops
metadata:
  name: codex-refresh-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - 20-secret.sops.yaml
