apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: media-mcp
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:BelWxQy2onwVb+KW203yLjEDv2MSOypWW/m9egVH5ZTh30tWnKjkwu1QgqAupSYA7e0enx+RKz9+RZYA/jPQbA3lP93ucijMIcYGQJwrQvbP1PviYTjKLXn3KrMpCT//Q7Yhxi/M2O/kenbGUXGEig8CdHUalJHYpH9yZdgQMmtGPC+0yhbPrnVGCmMuucezEA5w+an14mVVk3GgvfQaRlDSkTr+LgsnNjbV+JhYY5YxOcqE/4hgtT2Eq128eq8O,iv:ck/87VCEQi7XMdLKumfYTAzaRzG0erygB9kTmn/C53Y=,tag:G3XFl1jdB6u8Vv4yVys5Xw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZVlxTjZiQjQvWXU3cUY0
            VnBXU1BpS1ZRczZMV0JMYjBQWElyckhZdTBZCkZBSDU0d3F5VHh3MEY0bzVIc21E
            c1NzRFh3SkN0WGFrN1RrKytqQU5wV3cKLS0tIGFHSjZMbGVnRGt3UGFFQnlhVXI3
            NjIyRmJJam1RbmVSakVRb0Fva2R4eEkKjlYzDkbYM3R3lqgvfanRHCTl4Z9RodHv
            2x+DXh1xQaer57qzR3JZk7l8nME5KDdwDfYRjv9UQmRTgzNSKZ7qPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T19:43:43Z"
    mac: ENC[AES256_GCM,data:4z3N+YZ+m3BYoi0iRmToVkd23V/tPy0lzfrFxozoo5dcvttZAO7b0CY0LWNrb82/2bltJ6QJ7E7NAYhPk7/IswjOL4ySo/UPwWF9Y4gyeNNYwi7Vc7eRBbbEDd0SJ2fULwSP6FB/RyW/m8u8HIAc0uD8g4ZbVsD344Ns9lkFE/A=,iv:PVYnIlaksr7XueoE5wsGNgw2/fe4A47r6vo2YHFDG3E=,tag:yZiqYIf3qczyNwJH7aQywA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
