apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 20-deployment.yaml
  - 30-service.yaml
  - 53-httproute-internal.yaml
  - 60-networkpolicy.yaml

generators:
  - ksops.yaml

images:
  - name: registry.internal.white.fm/media-mcp
    newTag: "0.1.0"
    digest: "sha256:546c55c69e4e870192f22163888171441206884b91fc73f0fbbd3d9f8967a756"
