apiVersion: v1
kind: Secret
metadata:
    name: gibt-es-gott-git
    namespace: gibt-es-gott
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:33zZco86vgLv9Dd3hCjAnlkDcDO9+RDIcMgNGYjOLDThYz+mBHpnvI7yYgQ2ce7BaA9Chc7925iXZwW3OFvAF+mgFrfMQ16q0OxCqWNpdm7CmQdSkIgvJGZ8wEl2smtU4w2l1Fosad24+Ipw/TMMZC8vdGEayWPyNZkN2A8B/tVxWpvAwadq/dtlyy13pOIA+QAKcE3au5tWujaXbxHcRPzY/49/RvsbcCGOJDtZBjhJxyWnQ+tWgwm3D63KTVbrD1ynuPMMMLxUMThxzooCPXsvx+UoJeEu9iw9NvO9yV0Sm0MymJcVfUcXyQ/20nZM89c4gKC334jHtm++njtpVZpND29hsJ9dxlQ5o4hHPIrJlZQXL51QSpH+ShbciW5PO0HoHsBWlPGv3a2smtdv+2lvC0DqRFsysM0dEvBf71qeu84wMim/ISLVT35UvysApVLrN8u2OLWAgz/usM6tDUXB0hXIQFCEzdCuRvH2xSk3H70JhzlNZROGsAkg28oO7sYkDw531Wkpd2JsW3h/KHC63DsgqCqd5AadTu0cOGbpiKH/2/4QAYB9E1OcJTI+MdVvWyKZMGU9Zagqa79+GKSWXUE=,iv:c5/mncpL3IG43KSr4I3X2nEudtbPDTdv3a+6qcM46Uk=,tag:OPa/FRaaoUfyR+Q4wcWKvw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdUV2ei9EZk95NkQwNTZP
            UHRPRHByaTU1RGR1L3l2eUdSY2R5cE5UZXlBCnV3S0N2d25NcU1tcWh4UUIzb1ZO
            NWFoNkJNdVVraVdYLzJ6dnFSVFRjeVEKLS0tIEpaSWV6ZjM1WlduMUhTbDRDMXk3
            b3Yya2JMVzIrc09UcDZhampsdUNEejQKYxctpNYShMTyutlVoSMblT3WtK5heajR
            kx102sq0z+71mio4w1Td79kiQ9MMCWFi3wUxgTay3ZIfNtKrrtt5iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T05:45:13Z"
    mac: ENC[AES256_GCM,data:thh1L3s54h0harcbsCve6zW6tWjlpf9T37Ep2x15Pk4mlRaSBEGpk4DZ6WONjzuueyVamVCXSseuSDmA4pYBjwpRWafXl9g635JPcORaRXt7ycZ+vn3eqwg2+RU0AI604Gm+P43DQNR/gh/89jlOQnv6u0maclb6XNSuxZHswQA=,iv:TyTRr6E/nv5OPJwnLSE/qf7ArEqVzAQDvA6kvIW0uXQ=,tag:DQKbrJGM3J06Q11v8ak0jA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
