apiVersion: v1
kind: Service
metadata:
  name: gibt-es-gott
  namespace: gibt-es-gott
spec:
  type: ClusterIP
  selector:
    app: gibt-es-gott
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
