apiVersion: v1
kind: Secret
metadata:
  name: repo-1password-connect
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: 1password-connect
  project: default
  type: helm
  url: https://1password.github.io/connect-helm-charts/
