apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfmark-books
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
