apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 10-configmap-settings.yaml
  - 20-deployment.yaml
  - 21-deployment-valkey.yaml
  - 30-service.yaml
  - 31-service-valkey.yaml
  - 50-netpol-egress.yaml
  - 53-httproute-internal.yaml

generators:
  - ksops.yaml

images:
  - name: docker.io/searxng/searxng
    newTag: "2026.6.14-b3e08f2a4"
    digest: sha256:8f1e32b1013b1e74a9b769686edbca03ff5439395743725f3f18369b4841f709
  - name: docker.io/valkey/valkey
    newTag: "8.1.8-alpine"
    digest: sha256:77643d152547b446fc15cbafaff22004545663fcd40c6b28038ad283837baa75
