apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 10-configmap-settings.yaml
  - 20-deployment.yaml
  - 21-deployment-valkey.yaml
  - 30-service.yaml
  - 31-service-valkey.yaml
  - 50-netpol-egress.yaml
  - 53-httproute-internal.yaml

generators:
  - ksops.yaml

images:
  - name: docker.io/searxng/searxng
    newTag: "2026.6.14-b3e08f2a4"
  - name: docker.io/valkey/valkey
    newTag: "9.1.2-alpine@sha256:48332870af354a799964c0012ae1194a0bf2bf894eb508f945810596dc2d8d11"
