apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: plex
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:vjc3Tu1b4eL6eVY3Kw4W/60DBOibfA==,iv:F82O55eKrvHDLHfT6md24xjnfxDBXQGD0uG07ZhStiU=,tag:OJ4FFP0ejC2YTEt1IuEnrA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckQ0enplaTRLZStHdnA2
            VTBYVWhvN2VRMjZoaVlpbEhNMkFEQXZIcFdnCnZTemJMaXcxUkc5M1RnU1FwNHAv
            WW1rNzlKZzRZUldBQVFjSzVGVnpqc2sKLS0tIHFKZEllaFpOdzBmQVJXK0J1M1VR
            WlVES2lJNWwzRkJ5MGZreVgzdVhDd2MK0j27MNbTJeqlIqcfVAvKZyiGdTCGGPJA
            w/8Jzq5g/uFzHnfGxfylQAWLRqtlr42B4PWnuhIU29jkv99eo75ogA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T04:56:36Z"
    mac: ENC[AES256_GCM,data:Crjf7worHXf24gGdv0EfyWs700ivDCpvKzAU5SPJk6lnppPPhA1RNnkqZ7yHgG1QaOXwbzYeZmtGkHTpMl4CUGhaUJ7muFrqxfeO9T2JStQHYkL9Jtn+Iy3oNo7/gBnsOQVZCslWyJSF50S+ZmaYtL91qM+3QZuviqy1xhfPUUU=,iv:VTqRg9AWOwBQVXdKHNklZaSkKGtjPDUEFTgsKT4nhgg=,tag:BH53hEQnnHNgJp67fq8yhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
