apiVersion: v1
kind: Secret
metadata:
    name: grafana-postgres
    namespace: observability
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:MvxCUPZdFg==,iv:yrs+1EiQ71ilYRN4YTxWlkL+g2gDhNtLfhBbpf4XU10=,tag:IEYrWdDn6XvZAkBtbRvC/Q==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:n5MP60fYHQ==,iv:+5ZpEwx2BK70n+bRr6FZoWt0VOwJNT24hx4i1WwV1Mk=,tag:UZqhTTc/e+rMbB5p6dIgaQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:yw+TF1m38ORRvA0H2g6pYHt+wAWiYugVWHef8o64ZearxcK25NGfkd1KZ092vRoh,iv:uYk1ZP32T77jttHZaux0Q2jSmpJYzczrFJMdOQ3xn2U=,tag:syf15Lo/r52gdn/115OLPA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL3IxWVRIcU9aK1RidEcr
            dldPYWdCU2pFU3ZZalZma21HRWd6K0xTMWt3Cldqc2s4NHh2S0ROU3hVL3BPWUpp
            VWdRZThLcENyM25GTFZSZWR5NkFpaVUKLS0tIHlGRGZEOHkxL2RsUDEzdk1wWkQ1
            UmFQZzJWVEZtT2Nwb2tPN3ZKekhaQXMK1lw1QCU+lbZBoDGPhbErbQ3q6i2qO0I6
            NuJiFzpMcIZzjl808Kpz3ZVpkQGUz95iM1cRTEMkHsQN5wCuBnW6yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T04:02:21Z"
    mac: ENC[AES256_GCM,data:ZotNGiDld27bV+EqKO7PaIgVTBPTynXrEqpnLKDdE/lnAvHb7SYAdaJHCW2Dt6NmCtnU+x724cxmYZOYKWBHtzobAcHiFvnnx0eqOSDLqK+O+8k+MSW3HZsLSjrEM9Tpx/TPUKWpqnCX6zuzQ+fWq3LIzZzJuaLAqtJvXLcwWOA=,iv:YMSXD2hPdvzlpa1D6u7ySEENUpTN/gYebT8PFO0ROec=,tag:SP95Jwhpu6tzqLZQ8hG8/A==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
