apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-mysql-v2
  namespace: fleet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
