apiVersion: v1
kind: Secret
metadata:
    name: politics-secret
    namespace: politics
stringData:
    freshrss-username: ENC[AES256_GCM,data:ZqAhtROZ,iv:ns9ZxN0xgM+Y0yGdGcNCkndkf3XivP2rPUvVBowjBwg=,tag:Qf3kb076fJVjfCQD5j7mkw==,type:str]
    freshrss-api-password: ENC[AES256_GCM,data:TagHwhg5MRazYjVFrh4JP72lxA==,iv:480/hB1FHQ+u1RZTacslL+WXCtjYwMw5wSD75cyUZSs=,tag:pGuUwFw++sbm1TsyJbBpeA==,type:str]
    x-politics: ENC[AES256_GCM,data:pBZ9bx9qQyRlEqFqFLSYlQpaQOjufSgW0ZQ96yu8L6k+/ydhar8zIzrfnqLoscYCYeFYjhmh,iv:4oNBRsfp40uvuT05G9sB5ov3PxQZr7oE7853+ZUPnQ0=,tag:ZjHXAw9lnCN34esnaPKj6w==,type:str]
    x-government: ENC[AES256_GCM,data:Ye6lcYJdsQlbF4JSz/Fq5AueqQah4emUtCGVeJZnvZcaNAXEVIgkj+LqI0xCJuvKwfZNo8udmTx1TfzbpTvPtBMYk2uYnli0NHjifOhTsTOd+kXk8X9N7i942aLj6Ycy8mKPRgIr,iv:VaApwHlE6BQkWAzK1TJvA03Lbzn36aKJfeEPdVpknn0=,tag:aUfQ8wa0DpfXUvi8S+32pg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc0czNWp3b09IR01ydkd2
            dTRwNUc4THprRy9SSnN0Um03eGI5MHdrdUR3CkM3TXl3dy9WSzJoanZXMWdrdnZw
            b05WOGR0ZEhmSy82YXl3T1VDUnQ0TUEKLS0tIE4razVOc1pId3ROb2EzOTJpVnlq
            ZTVmUCtrUUVRZ2dxQmZqMHp6Uk1GL3cKM0QnVik+EimcO7bwmyBzi9fDHaOo2HN9
            dG/+rHz7PlUfJfh4629F3ak2ZhT7BqFwClGPHjTpnHQu0S6pklkJqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T14:24:11Z"
    mac: ENC[AES256_GCM,data:H2PdXN8TzEapLTUAYkglV/6uJBAjZ7SfSx6/f4bPaCPYKJRjqu/nKdDK69rV5M8lqJQ7H2KwIPzEi4ktzOTznDZDs1NgDim1qtUQf1dRt8EYwlkuc7KagF54EKuEdNzoO57maBel8YPaF39EaHI6MxKxDJK8/qdneQ0TaGR/020=,iv:FXhaA6Gl121d2DUNVt5uIR4Z1pOt5pFaAgxtrX/7DGc=,tag:2DYCOpmQY1SqO6QW3Zrw+w==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
