apiVersion: v1
kind: Secret
metadata:
    name: politics-secret
    namespace: politics
stringData:
    freshrss-username: ENC[AES256_GCM,data:b6WFD+qRA9Q=,iv:5V5t1iyFj0aQFJ1npoVFPRyB+p2+oRvLMeCtMzBluEk=,tag:+FM+QJ9FnADs07Gij8AICA==,type:str]
    freshrss-api-password: ENC[AES256_GCM,data:yIxgePKAiJOl,iv:k8Q+poXEaS51UJeak1Xd+xf2cemVKqcBHRoFtI0Ds2A=,tag:L2JpWjn3qZxgk+P8VXshnQ==,type:str]
    x-politics: ENC[AES256_GCM,data:pBZ9bx9qQyRlEqFqFLSYlQpaQOjufSgW0ZQ96yu8L6k+/ydhar8zIzrfnqLoscYCYeFYjhmh,iv:4oNBRsfp40uvuT05G9sB5ov3PxQZr7oE7853+ZUPnQ0=,tag:ZjHXAw9lnCN34esnaPKj6w==,type:str]
    x-government: ENC[AES256_GCM,data:Ye6lcYJdsQlbF4JSz/Fq5AueqQah4emUtCGVeJZnvZcaNAXEVIgkj+LqI0xCJuvKwfZNo8udmTx1TfzbpTvPtBMYk2uYnli0NHjifOhTsTOd+kXk8X9N7i942aLj6Ycy8mKPRgIr,iv:VaApwHlE6BQkWAzK1TJvA03Lbzn36aKJfeEPdVpknn0=,tag:aUfQ8wa0DpfXUvi8S+32pg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc0czNWp3b09IR01ydkd2
            dTRwNUc4THprRy9SSnN0Um03eGI5MHdrdUR3CkM3TXl3dy9WSzJoanZXMWdrdnZw
            b05WOGR0ZEhmSy82YXl3T1VDUnQ0TUEKLS0tIE4razVOc1pId3ROb2EzOTJpVnlq
            ZTVmUCtrUUVRZ2dxQmZqMHp6Uk1GL3cKM0QnVik+EimcO7bwmyBzi9fDHaOo2HN9
            dG/+rHz7PlUfJfh4629F3ak2ZhT7BqFwClGPHjTpnHQu0S6pklkJqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T04:19:29Z"
    mac: ENC[AES256_GCM,data:j3I5Gy+G0DlQJJtuqKT6g0IiN2cI7YhrN6DeqtOyB9OM0lVad557aF0L4ZUffqm2QViLP5hbuoLFK3CxNc/Fpo+8GvYy+kWWOTWTffeLUuhaiO9+zUCjoWXmOFeXzNn6xUyNTkz+MmzpRWsbI38dliGoepEzsVzH3pDLfwUXdsQ=,iv:XO/zFvGV3tH4PkQvUrUimilq8fFQam44/p3Sz0v+Hrk=,tag:dM7aW/k/zlA3EHUFUwCdTg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
