apiVersion: v1
kind: Secret
metadata:
    name: politics-secret
    namespace: politics
stringData:
    freshrss-username: ENC[AES256_GCM,data:ZqAhtROZ,iv:ns9ZxN0xgM+Y0yGdGcNCkndkf3XivP2rPUvVBowjBwg=,tag:Qf3kb076fJVjfCQD5j7mkw==,type:str]
    freshrss-api-password: ENC[AES256_GCM,data:TagHwhg5MRazYjVFrh4JP72lxA==,iv:480/hB1FHQ+u1RZTacslL+WXCtjYwMw5wSD75cyUZSs=,tag:pGuUwFw++sbm1TsyJbBpeA==,type:str]
    x-politics: ENC[AES256_GCM,data:c+bHHdjutYAEObkE4SdzcXyubaG9hAnSTzAj2ltWqJSSpe/VseAwmEjqXnPzPRrqJhx954LTBA0siZqoWD1KoWqUinxtfhWs9WcNIlO5EWSYKazjuAbXRkEmMxvgO9PaIAHicxawo3UKLw2gk2IhvXpJ4vBYopHm53t+NDjNv8Lt6emo99aEHUoRYliayCoIwgMjK1L9/0d4sKNL0RlZYCyUuLZRMwetO8gYhGn7oWIxMY9nAujtf6uPqI7AuWmYYeWmtxQ3zY1MxaBMFq9Qma9uwoehCdKM2+eg,iv:RGQHt+UKFzRlODQH3XNF/61v/CEl8Eej22yJdznKn0k=,tag:wKU1FZ2tZAM/PgKTYRFoag==,type:str]
    x-government: ENC[AES256_GCM,data:ma+isSMErQv2GgCHsj6eshwB3AKNJs4KpzGurNSHEZ46eYwn/rKMp09IRAypDMzK6lKeN73tv288t2BaEtZOsuZ6vEE5oK4Yu3q7WH7p2KIvlLf2fmTcBMTf9T8pesJ/bZi1P9v1vWNCysG9FGws0ugCxJM5oKCKjLVwrD04a10N5MoBgCU8JXA08wPfdgIbvWBriOHxtAf9t9dbRUVic83oQW2cg+sqw/pImCd4Uk/khvYYCRre/+JFHQmbTHA1iR7c3dY6pB1pF0nsmhFrwg==,iv:5uF46NnIihStY3Po3U8E3pAvydS/Ihivry8uJX5rHCo=,tag:Zia8bWOOxn53AvEm2fbeuA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc0czNWp3b09IR01ydkd2
            dTRwNUc4THprRy9SSnN0Um03eGI5MHdrdUR3CkM3TXl3dy9WSzJoanZXMWdrdnZw
            b05WOGR0ZEhmSy82YXl3T1VDUnQ0TUEKLS0tIE4razVOc1pId3ROb2EzOTJpVnlq
            ZTVmUCtrUUVRZ2dxQmZqMHp6Uk1GL3cKM0QnVik+EimcO7bwmyBzi9fDHaOo2HN9
            dG/+rHz7PlUfJfh4629F3ak2ZhT7BqFwClGPHjTpnHQu0S6pklkJqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T04:27:03Z"
    mac: ENC[AES256_GCM,data:cwslLvbGhOvF6B4nfDkT1AjBN++tSiITE6x97YF6R/DAfCoGHA3ELmnXu+CPfVuzKg2qB/kYwYPamMOHdNrRDGOQhYZ8oG/Qn2rWwhlg0HFqMoMYmQJ/rT2ITIQDVzf7wgCc32tBd3BQ1dR+TEZjDup4CdgTRqCa440mcBp82iU=,iv:KzhyTxRHirmLBjEqLf6ISnwa7Nhx7viiuXZpRRw4fmY=,tag:zkC3ZjtjUdV2mp6t5kwOkQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
