apiVersion: v1
kind: Secret
metadata:
    name: mysql
    namespace: fleet
type: Opaque
stringData:
    root-password: ENC[AES256_GCM,data:pzjHhHJSGwvIZPiWezTPumhsoQ3Tb71DZ2ud6Ymd0sU=,iv:leoPeOy6vJoqLKScmc0tW544gmSnkcTWAN7nhpwMI/Q=,tag:YEt5IRpqYglzd8UtqxJoAA==,type:str]
    password: ENC[AES256_GCM,data:kDYcsDICTVF5AHPCSfgPTuaHHxHSt32Je6zTL5/f/7o=,iv:R6UMLpHiKJxPcPqcHGSNHX9IeJwuhhKZYGyrx5XXDLA=,tag:JxOEXV37xG9pWsL3sn5V7w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJem5NT25kbjgra05kUjd4
            anVpdi9IS25Da05DMmVBZkNxTEtWR3lMelNRClg3b05PTGpKV0NibFJZT0RPb1dq
            RU8zWFVEdU5jWGltdjRDUGp5U0NOa0UKLS0tIDAydGdIUVJ1NlV2OVJIYjFsd1kx
            TUdKZnZhaWF2OHpSL1BtRmM2RUNlNWsK819ASEWnp1BLV9dE8fetTbL+xnSNgt5w
            PnGBvrukauCpktV9UjAGdTH3+DFo/uBtedPmrpPhton9qD6kO1SxTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:38:47Z"
    mac: ENC[AES256_GCM,data:AID2uYP1eTXDoWCTUO1CYs1HLv9tMHfK9u2UgYdouD6fjfTmshtMnIC4h4YV6uxaJ/OA9XT47Jycvvh0ut+BzVSNkzP3XjsOkjjEddQi2fbUAuj1FCoboAj16qse6//KazcGDu1rkYrJrpEXGlFU7hUZd2vR6HfTV9gfkvfq/LY=,iv:ZDsXX1Mph/z2ufbPt3sbt66dyA+buJE+2FyiVNVTQm0=,tag:7RBy/vC8E7AfoEp/dEzyCA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: redis
    namespace: fleet
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:LW9S7bEmfWDULLrAm8c+q12EeihYitSds0neBjWlL0U=,iv:u9aO6MWXjYx5MYmVtPKo8tvZynhuR4Dl6EoO18DXlfY=,tag:COpT+S30SRge2HjH86LVGA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJem5NT25kbjgra05kUjd4
            anVpdi9IS25Da05DMmVBZkNxTEtWR3lMelNRClg3b05PTGpKV0NibFJZT0RPb1dq
            RU8zWFVEdU5jWGltdjRDUGp5U0NOa0UKLS0tIDAydGdIUVJ1NlV2OVJIYjFsd1kx
            TUdKZnZhaWF2OHpSL1BtRmM2RUNlNWsK819ASEWnp1BLV9dE8fetTbL+xnSNgt5w
            PnGBvrukauCpktV9UjAGdTH3+DFo/uBtedPmrpPhton9qD6kO1SxTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:38:47Z"
    mac: ENC[AES256_GCM,data:AID2uYP1eTXDoWCTUO1CYs1HLv9tMHfK9u2UgYdouD6fjfTmshtMnIC4h4YV6uxaJ/OA9XT47Jycvvh0ut+BzVSNkzP3XjsOkjjEddQi2fbUAuj1FCoboAj16qse6//KazcGDu1rkYrJrpEXGlFU7hUZd2vR6HfTV9gfkvfq/LY=,iv:ZDsXX1Mph/z2ufbPt3sbt66dyA+buJE+2FyiVNVTQm0=,tag:7RBy/vC8E7AfoEp/dEzyCA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: fleet
    namespace: fleet
type: Opaque
stringData:
    server-private-key: ENC[AES256_GCM,data:zV2Uatc4BEl1TbmSQShcpSUiP/NNVyXJdTDBtqn+U74LWe1fI/MsDt2/KLeDKAXJeE/UjOJXUAfyIYkmJg5Uww==,iv:/AVJFZRdMYH644XH1LYps4/ZLTguO+2nOJP/GiwVqP0=,tag:4ldbmKhZM4Jb2InAeBEeLw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJem5NT25kbjgra05kUjd4
            anVpdi9IS25Da05DMmVBZkNxTEtWR3lMelNRClg3b05PTGpKV0NibFJZT0RPb1dq
            RU8zWFVEdU5jWGltdjRDUGp5U0NOa0UKLS0tIDAydGdIUVJ1NlV2OVJIYjFsd1kx
            TUdKZnZhaWF2OHpSL1BtRmM2RUNlNWsK819ASEWnp1BLV9dE8fetTbL+xnSNgt5w
            PnGBvrukauCpktV9UjAGdTH3+DFo/uBtedPmrpPhton9qD6kO1SxTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:38:47Z"
    mac: ENC[AES256_GCM,data:AID2uYP1eTXDoWCTUO1CYs1HLv9tMHfK9u2UgYdouD6fjfTmshtMnIC4h4YV6uxaJ/OA9XT47Jycvvh0ut+BzVSNkzP3XjsOkjjEddQi2fbUAuj1FCoboAj16qse6//KazcGDu1rkYrJrpEXGlFU7hUZd2vR6HfTV9gfkvfq/LY=,iv:ZDsXX1Mph/z2ufbPt3sbt66dyA+buJE+2FyiVNVTQm0=,tag:7RBy/vC8E7AfoEp/dEzyCA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
