apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet

generators:
  - 25-ksops.yaml

resources:
  - 00-namespace.yaml
  - 10-mysql-statefulset.yaml
  - 11-mysql-service.yaml
  - 12-mysql-pdb.yaml
  - 20-valkey-statefulset.yaml
  - 21-valkey-service.yaml
  - 40-cronjob-mysqldump.yaml
  - 50-httproute-public.yaml
  - 51-httproute-internal.yaml
  - 60-fleet-pdb.yaml

patches:
  - path: 80-patch-fleet-env.yaml
    target:
      kind: Deployment
      name: fleet
  - path: 81-patch-fleet-migration-env.yaml
    target:
      kind: Job
      name: fleet-migration
  - path: 82-patch-fleet-migration-strip-hooks.yaml
    target:
      kind: Job
      name: fleet-migration
  - path: 83-patch-fleet-sa-strip-hooks.yaml
    target:
      kind: ServiceAccount
      name: fleet

images:
  - name: mysql
    newTag: "8.4.9"
    digest: "sha256:c36050afdca850f23cef85703f84c7531a5ae155a11b5ee1c60acb09937c4084"
  - name: valkey/valkey
    newTag: "8.1-alpine"
    digest: "sha256:b027235326507cfdade9b6684056ec1d0b0c0757412e628245129b5d7b788618"
  - name: prom/mysqld-exporter
    newTag: "v0.19.0"
    digest: "sha256:eacb4b18e2ec1e0abdf2d64851b68526c964f6d9cb3e9458fb5d5f5062ea94c1"
  - name: busybox
    newTag: "1.37"
    digest: "sha256:0d3f1e630be52ade0c06107515937607be2cab11a2ad2122099fc79e19bcc18b"
  - name: fleetdm/fleet
    newTag: "v4.85.0"
    digest: "sha256:7d8d9dd8d2ad1c7e190b7c51cb34ec7ddde8c59af594a68ef9aadd900870e7d6"

helmCharts:
  - name: fleet
    releaseName: fleet
    version: v7.0.2
    repo: https://fleetdm.github.io/fleet/charts
    valuesFile: values.yaml
    includeCRDs: true
    namespace: fleet
