apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-routes.yaml
  - 20-network-policies.yaml
  - 30-routes-batch2.yaml
  - 40-network-policies-batch2.yaml
  - 50-routes-batch3-internal.yaml
  - 55-security-policies-batch3.yaml
  - 60-network-policies-batch3.yaml
