apiVersion: v1
kind: Secret
metadata:
    name: homarr-connectors
    namespace: homarr
type: Opaque
stringData:
    #ENC[AES256_GCM,data:t2TGm/FalAAU2l1cB1ErHZWIUK65mobdvQsu56A8T4VZ6qm5VO1ofRpBzANE5dBlVmYcY7Z3HAFH0bbv4nSKw3Y=,iv:4R/kGzPfx6jbYZfkXuE8PqS/6gD5a1R9jQqOG9+xPeM=,tag:3bkmiDGAFULNGK/+Y1rMgw==,type:comment]
    #ENC[AES256_GCM,data:kVtl5314XtQ8+s+EOh10dsFKhmGwlto/UZ4cwbSYhVSsLCFJ5G4/HeWvvLUXw26SjXTZY73NatJpuda6fNkiUPcpdRJjQ7dRYhqv,iv:+4q7tWiiHOAdtfzs4FUcQbU+aoqQGujNaaUZL0pj9ZQ=,tag:NQWR7+2ko7erZK8NFJiA9g==,type:comment]
    #ENC[AES256_GCM,data:kVyVOhhhoKVYzk0QLiqYd8G1CT5squsdL+LHEosYG965xNMqQ8BCQ8mHBCwhC74Z9geC2cH6jnByhKxIzOLdsqdJ5gI=,iv:ahd4uUbVkLtardgSyXw2pu194pFFoV653895UNt3nJc=,tag:zYiPU0bLh3nwC++S4nxa2A==,type:comment]
    #ENC[AES256_GCM,data:lkfVv52zEoiS4H1gXMdldqCn3ZQlob4xBNbLrQYxE09zJtJQ0sAvKsBdp3lQnPG12Vy7pM6JBNZSnJOhYRv8KjIOiqrdk8ntyyaA7g0=,iv:oVXrK04EhDJvpGoJCi1RWPvs3fZuqKpZss638T8Orbg=,tag:Q1h/WBMCe9kZt+yqu3DpjQ==,type:comment]
    #ENC[AES256_GCM,data:mNg7wFV2z0W4SiSN4+0L0kOOFMiPQsEFQstiv8m0hscUodvIRxQ93zJngqjZn2iK54wBBeILBProZUpoLa0G8/Ygx95jGeVR3MRv,iv:WG2bTe1pFUC6gFsrQEDJ4FcdDDNkU6EETOqaYCQ22bc=,tag:hdC8t0wZgPmwhhrzYyBGeA==,type:comment]
    #ENC[AES256_GCM,data:S0Ve7JerD0aVVt3zJ/huJDsnvW05VyO0gNQp2AC2qpkcj2t5AEiD/jMQoQQ7rMXUlpyVh1VdrD04qVB5LNnBfRdq+rPyeO2gq+I=,iv:O1fVSc809D//X7Fsf4qr9Wan2B3pCioodlHDlNygkpQ=,tag:mHNUR2Z5YYnaqHJMbvOucg==,type:comment]
    #ENC[AES256_GCM,data:Vv7mjghys20dH/nT6alrX/rl7VqyJPIvClHucsu2xMFRENV3ZxoLR/68CQs=,iv:pSCbMVZVV6Eke8XegymGLcwMA5LLcgyIPWAkWZ+ipHs=,tag:y4HTOJd1sfCwkhpcoma/yQ==,type:comment]
    connectors.json: ENC[AES256_GCM,data:eXG//ZKB5hYqLYXMvd6WrBE9g9Z8ucOx+Uq+7aJsgdk/5qbVNwXTYCgmoRl1/mMvXELl7nHAiV7ZvjVBIfmeAUU7T72v9j964lm3EMQLun7tzllWeltDEU+ziKUEm6S666uSJGes7sFM5Al+HHI94Wi9UH0QUgPwFEZztEL/0mZD1wQWKqZbwPPyEZj+fqJ8Ni3kLQfn8v09eWMgYRp83QcvVEwYghwyCYqrF94d8+5ltuULO+sIXtXJJ+NqZI4=,iv:4qCIozEO2ixj0mg9OLIN8JLieD02FNupfxfNjIAMikY=,tag:JPjDNfsDzNar7peEp2nBpg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRXQrbk9lU090OTJ6bDlh
            NHVmNXExb2RNZG1qdzRqSlAxOXFjUDhZbkZFCmJYOENFRVBodFdLdDhrRS9DK1Iz
            cmp1MFBJRHVyUmlnbG9SMlRTSTRGV1UKLS0tIGJ0NHRRUTRSQk8vR21zK0RmVXR1
            VmpXd1FrNUQydzNqR1llODF5ZkRiSUUKL7tPHuxWhf/JAQ8rgrFSysSqaIzotgts
            ha+CU1Ko4BobB3TECpFSS9dhBPTVIZK76RUHjaZAAnDjXoU5rxsNfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T00:09:27Z"
    mac: ENC[AES256_GCM,data:ZNJNkcFNL2k7HvZDXbN0ti8Rztv5T0UD9nHYA+m21fa5ZllxVwPth3cEhaX5qKjyObtK4tHTAEAcOT4noveuq/vaSUrrxS0j2hTT4cLe9in9YH4B4q2aYzeghrq2utxbtunKeKsKL+gk9TI4X+h6ApFV/iqQzq1YN/tWLtKCKKo=,iv:VnZ63hxNpTY1ncr4gH0HkrAAnMDRfPcsMinBmOSk4rQ=,tag:McxySIUvoQ4vUuPcz0C9sQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
