apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ground-station-data
  namespace: ground-station
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
