apiVersion: v1
kind: Secret
metadata:
    name: monica-secrets
    namespace: monica
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:Xf+ZzrG3YGaaUd5WC4a0ID7TiMKLig4TVeSINQ7lhdRPm3GoGTC60L7cJylktGesnANx,iv:xcUP6jrk947o18Xcut6p6LbnhgnTnl9U59BsdctgVAs=,tag:U+ukvZPJjkSXr7OTEijp9g==,type:str]
    db-password: ENC[AES256_GCM,data:pG6C9179bBaB9F1KB2JXmwoZzW8B63XF,iv:iJ0UjvG9zhtbXcrWrgX5klIEaG0ntPlyn+puLn3BOPM=,tag:7KdtoABFtqL854B71Rv8Dw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbEFBZDFSTm5OWENxV1JH
            RjlDTHhZcXdPMHZoNy8vdjk3ZzRJUjNHQzBNCnRRQnlzYzVNY3IvWWljY0ZzZ3Br
            SFRGM0ZnSVJLek1uUzM1NjdNTnV5YlkKLS0tIDV3K3NyUzRDL1Y3RUU4Y2ZCMEpu
            WkpBSTE3UlJzQmxmSy9IbklmYUswSXcKnh6iaO31MnkoobA//qBiZT8GnJoAtbmq
            0DPvnJq9w1YZdTsdrzB0tL8kI+NkKNEqPCyr2FdzO9adrxQ6jofRRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T03:51:19Z"
    mac: ENC[AES256_GCM,data:VV4qTFSXLvxZ+KmMYClEn2oWoewAXOFt4Cf8WUCD8fJ1miyhHNSYBT28kMRPsikkJDGoKD/BvqsgHaJygHVPGfbtpJblqfLcph0Rc5LGPLXtUTqLjBPxyZUUTvrbunn8qdJP6vZIfEE9y8tnGZ7k/vJGza5ctvRwhPcAaRKBhus=,iv:c2N8qewlrEYafQ+mseJjJHq4cNBLDGGw2ogIghltIwY=,tag:diRppTjMjAWO4T2g5twK8A==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
