apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monica

resources:
  - 00-namespace.yaml
  - 10-pvc-mysql.yaml
  - 15-pvc-storage.yaml
  - 20-mysql-deployment.yaml
  - 21-mysql-service.yaml
  - 30-deployment.yaml
  - 40-service.yaml
  - 52-httproute-public.yaml
  - 53-httproute-internal.yaml

generators:
  - 25-ksops.yaml

images:
  - name: registry.internal.white.fm/monica
    newTag: "5.0.0-beta.5.16"
  - name: mariadb
    newTag: "13@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"
