apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - adsb
  - ai-stack
  - audiobookshelf
  - authentik
  - comfyui
  - condo
  - convos
  - fleet
  - freshrss
  - gibt-es-gott
  - headscale
  - hermes
  - homarr
  - homebridge
  - homeschool
  - invokeai
  - kube-bench
  - listmonk
  - matrix
  - myspeed
  - observability
  - ombi
  - portainer
  - registry
  - scrypted
  - snappymail
  - tautulli
  - uptime-kuma
