apiVersion: v1
kind: Secret
metadata:
    name: meerkat-secrets
    namespace: meerkat
type: Opaque
stringData:
    jwt-secret-key: ENC[AES256_GCM,data:XidERb4Hijax9aPvaSsDPFbkKGANEEq3S9pqAGvqPZC24ogwG/eRUB7F/vrxO4eLZpeBcO5XuSnnatRD5mOrTA==,iv:9boIP2Jt+C9tYQgJ1RxR4lyFizD990rebgRUHKcsI80=,tag:y1oqHhnPEzayDas3XloaMg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndE5nTFVFbTNxdWJHOXFQ
            cmxkMWN4c2Y1R3hSUS9PSXNpc2NOMDBkYVdFCnY4VWZSaGlwSlBNUFJVbm5NVStO
            TUhHWTZBVW1TWHV5QTI1b3ppT1JjcEUKLS0tIDRCd3VOMXV2c0hGU3JwYmxGQ1hp
            VE5vWFdlUzh4WkE2OFhBM3d0dzdmVTAK7cveUJHOEcsWWtrnjj4IjtifJyI1CESZ
            7iqKL1UNWxopf9Iie+xVj/kY1KotyS8ahzeDiFIrLeR9/k/l98LwzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T03:43:44Z"
    mac: ENC[AES256_GCM,data:51IROuqS8Vljbvv4sE0ERB2gD5ZxqiMKxQaCRha+wIkMwm29CRoVnkZ80w59Yntq+SvmpL14Rj33WuJ2HpkM0GGrM4ObG+Ss28gKEp4UNhIz2xto+mjhR6iR58JlV+7K9eX2nENCshKlOzuJEHO64sv/LOKo5P6HoQrdyoIEud8=,iv:fRiEt2Ldz953t3Qm+er0rD9lz8WU3e9BSRsNrkoIPLM=,tag:BLRHEK9g/OE6KESy1ysclg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
