apiVersion: v1
kind: Secret
metadata:
    name: postfix-main-smtp-secret
    namespace: postfix
type: Opaque
stringData:
    SMTP_USERNAME: ENC[AES256_GCM,data:FXhzS0DMBBSxO8PSAToecK8z2w2HrGU=,iv:GUNLwLc2ppKJujOPsk6ufdc6LgBYSZAPb7+zO5opubg=,tag:sRk5VirpSfmgg3s6RvKiGg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:6L9gat6m7ZMcqNoCXKyrsA==,iv:dM8bvUVsZ2690rgBOZNt/0+MMGZ3GPcuf184VCPq83U=,tag:+sbghVqjg6Arevsk8fWPZw==,type:str]
    SMTP_SERVER: ENC[AES256_GCM,data:3ioBSGEV5mtyYwm80y6d7p9V,iv:wsY6X4DzWFYJ1VzofYhZf03YbvmJKJHZt5uOaZeeyRU=,tag:HqFwH348uZPUY45e/MYotQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:ur9d,iv:SaHYaTef1PvV7hiKeDW5wxPEMhgw5MB3nR6CH5kxi78=,tag:npPOAZfri396J2ajb9pOdg==,type:str]
    SERVER_HOSTNAME: ENC[AES256_GCM,data:EUtGYQEm,iv:ZqztdmGz7IbqeHWyXUzSgdMczFB2n1/AyjYv+uQWwD0=,tag:snCHlJ/yVYlL75pXCjFzQQ==,type:str]
    ALWAYS_ADD_MISSING_HEADERS: ENC[AES256_GCM,data:12w=,iv:WtAcq7rWTqDqcXTBg+cC5yZd1eHONZYVWIXdDK/4oKU=,tag:sSac2zpqGNjjwuiMr+3Uvw==,type:str]
    SMTP_SASL_SECURITY_OPTIONS: ENC[AES256_GCM,data:I9ZuJjkXt40Iwsw=,iv:Qmq6uaCCpCDUPfoD0Nh6GoyPQAO6eARskr++y/FGz78=,tag:aqu2s2jWk0qQ4f7o0IhzUg==,type:str]
    SMTP_TLS_SECURITY_LEVEL: ENC[AES256_GCM,data:DreBFTKH4w==,iv:dALWJjGU8o1LLxHvMzwlyo/fz86PEg6tpS3dspf5uT0=,tag:C6C/tenSG31ih3mPhy8mdw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMXlmRjQ0VGVPOXMvKzBX
            aXBXZ0w4eC9lQ1pIbjB2YXN6SVc3Q2xLQ2tFCmVMejMrSEt3bGhBZmF4QXFtL1FZ
            dHhyM2k0dTRCblJZNnNHR3Vya1RTWEUKLS0tIGtEaW51ZjVWLzZNVmhOcUdmVDJ5
            ZVd3RlExMnlxcGp3NzduUzc1c2pRODQKG9J1GUd6YRUqGIm7khzUmG7QKXrNfXYD
            EshPTW42akzeTysC722NIjEZCpSkYZrPWZ0VXdaKyVRH1k2ukz8v+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T04:13:49Z"
    mac: ENC[AES256_GCM,data:esSTHcKVzH84XCGYouWjPxqvo/h65AaiR8f1uG8+Jssi3P5QieXaG38L3EL6Rofpxt5FIJzsGO019Vv1x338Qxyyg+mkchkCGjrRNb9rSk58I9O9U7VGQ5xDuPWxNtMMFDoh95Lp3f66ClxFSO6nwrJYA93Fuw/Q6KeiePnHSJs=,iv:AH83irOuZ9wjUaE19CNbYeKdOsN8H8HznhgKKkLs3OU=,tag:bQBZ0JA/FaKPrSjbukz2YQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
