apiVersion: ENC[AES256_GCM,data:gDvQV9H8Ng==,iv:9Q9L6CUl2WxplgRoCXEiQCkz8WzCzPD6hgeeayZhMF8=,tag:NqKW27D+QqHUxg3Su8nPfA==,type:str]
kind: ENC[AES256_GCM,data:ukIyZ01BR/yjLA==,iv:l7dhsbFHxU7mA00oDLfZTrnEtFfyd0i3p1E6gef9/uQ=,tag:lfOqHozVTC6DfKMWesW0Kg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:olwyNyvmLFnQ,iv:rkfCppsfYv14/sQktMnrqxs5QwFoOW/Jduorfw6u0bg=,tag:rJYznsBAMehSry51cOkvbA==,type:str]
    namespace: ENC[AES256_GCM,data:IWhBD0Y=,iv:TUE9DyZpKawlxgJgZRGJxmEBpLRgS4rckAnNGJdfZi8=,tag:B+h2OgHbBWDGOBWJ9pfhkw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:H/w4DojnXlID,iv:6BS0mk18y5bvuNe/6W15VFte48Ru8N4R5tu+bb4JWko=,tag:oONUpZHjkxm9MjzyvzOGcQ==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:vA==,iv:P4EzeqAlj08mESmQIMmXdPG7cb6sFF+eDUDrXQCgPuY=,tag:Tt+UgLGPEfTijnqaMcdZgA==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:OIwfvpqt2f5c,iv:5GpRhc0v9hUIcvrU3bWR/bxlU2fi1JdGs+VVxAN9lA8=,tag:oVt88RY06o7bSkWqpl9lLg==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:HdG8P0+0De1m,iv:mEehGxacSTUmz6MD2TLQXlyOGVGKm/4T+0hFq96KrX8=,tag:FXIafF5Ml1ly5LUqL2rM6Q==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:fmmnG1Q=,iv:PjLrSmlIalEktfI8+RPX+Gwz84xGGwVSaLINeJcDbTo=,tag:2TvoLfi/2K5/WCcmcLovSA==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:PwiWui9PiA==,iv:eXLPTqgcsV0cxvb28iUuD4GHIc879S4OS3ER+G39Zw0=,tag:GsifwVoHNRMxJvC/Omlt8Q==,type:str]
                  image: ENC[AES256_GCM,data:wvsUyu2hbGsOiwpAReoGWS9Zv7XUTUF+yDi7RbI=,iv:Sm+vk7Zf2L/jt19Myi6h91xp3iP4e2Q9NVonoozoIE8=,tag:tcGl6fwj7EBwic0FoAq0mQ==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:MgxabA==,iv:7HcpGBe9855GBDVAuF4mo00KVEHDmrZbJ9ZhKayduI0=,tag:LAM165ECLfNk6aaGGkihJA==,type:int]
                      name: ENC[AES256_GCM,data:EltMnAg6ybpNmQ==,iv:/tDt0aWDyoZD3DQD6nHkGhtG8qt/1XJb2W6Utt1FXuM=,tag:33R0HRG0dFPqUsWuby8RTQ==,type:str]
                    - containerPort: ENC[AES256_GCM,data:oIOM7g==,iv:Hv9mE0W+xrCvSGm95jX/fQvLDpGlbyRRaTLU37gGhZg=,tag:KTnzl723HJiSDG4uVwRkyg==,type:int]
                      name: ENC[AES256_GCM,data:1nXsm3wf,iv:2dz8K9cTKrJwfZHRAEOOF1suFneLvE3Ljz8uECAXNaM=,tag:j5qLij6bf9XBr1BsaK2zmQ==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:IhURk27NfxXun6zXabvt2i4k1Jk=,iv:Kv3kHv9i/0dk1qYvl/W5STbK02mGapf8LpXK/lLCs+I=,tag:3TAWdyQhanHrIvp4dlKaNQ==,type:str]
                      value: ENC[AES256_GCM,data:PLjQdBO5lncAfu4lrPsHTCWAknwKp7s=,iv:Rat4ATCAiwFOsnJCb6O20pPOxgroJ8WpXbDf8RLjNSs=,tag:H1UEtH+kVFKIf6htgUwXWA==,type:str]
                    - name: ENC[AES256_GCM,data:uk0b4JkYpPI=,iv:HbOUzaHJ4LtqARgAN4mheCGsaU50Z6zEksfZmxudjeg=,tag:jo0f6JWh1ssicz+zVeoyKA==,type:str]
                      value: ENC[AES256_GCM,data:YhPrGoahR6Pp,iv:7sQaDxYfjP+TCn3l2HxPlNQmdFnXU2eK4W8TP90LYyA=,tag:CvuAlJTEF8jXd6iJwvdi4A==,type:str]
                    - name: ENC[AES256_GCM,data:7D5GzR56iBnqfgL3nMk=,iv:GamNnTD7o+vgFuI9PMmz+7Amw39KyLS7Uyp4nDIlsMU=,tag:d8cQEEVy5oGhSIeJCJihDQ==,type:str]
                      value: ENC[AES256_GCM,data:kdppaIDCvA==,iv:+Antv3AalW1QMVTIuITc1a0Sk+54YKRWa2luaAgJz9M=,tag:qgfEi/KaSMhp6PpRntcN2g==,type:str]
                    - name: ENC[AES256_GCM,data:DkLgdaN33Gyb,iv:KdmGk4/0ahkpQeDi4AkrTCnfb6xOsCHivW68AxIDfbs=,tag:BYr+N5ru9TO/4aPv5xVIAg==,type:str]
                      value: ENC[AES256_GCM,data:RcQ=,iv:OhjU4S+qbPRt15srT19nzm4lh/BA1Db6lLq2tvWG7GY=,tag:5zmVaxder7sEkNRWkLa7qg==,type:str]
                    - name: ENC[AES256_GCM,data:aoaXfSq12Q0I1Ailqg==,iv:nUdofZ7NP0yE1KhNmI59kJ6kLcTj78ieCXj7gQshTCo=,tag:sIRzIDMPA5nqibXV/Ki1YQ==,type:str]
                      value: ENC[AES256_GCM,data:c9Pj,iv:tf2bUk2HbgGKfT/aXcRtNdJch4yN/6ZKmhFqbyTlr38=,tag:fucLV5U0A0lcDm+ufEgIFg==,type:str]
                    - name: ENC[AES256_GCM,data:yY9xFm+mVaf0q3U=,iv:9EV8BFHwN4o6X9TGCMSrnPo9npm5Pn4WF9OpiBQp15Y=,tag:T35fBytDTx5w/09oCP0prg==,type:str]
                      value: ENC[AES256_GCM,data:tTld,iv:ULiimv+rCQk7gDsmlDtLplQJa8hbE7RdfaVxO1Zs/7Y=,tag:R+ofKk9uBx5GKwjbiv/faQ==,type:str]
                    - name: ENC[AES256_GCM,data:VjFe/mIxvjM2l4wdJnIGf8wekvk=,iv:Cu0Y/unnmouaQhxCe2xrOCk67wPA0BbTcbDL61hL1WU=,tag:oB8OFK84Tyn0njLzyljQvQ==,type:str]
                      value: ENC[AES256_GCM,data:y7KgEBKjIwyA,iv:4JmD700tG3LHRgjlL40GNMACHScv0iME6INsuQjXQvE=,tag:tzTZagsI++M4Gj/NZx+Glg==,type:str]
                    - name: ENC[AES256_GCM,data:OVzMXH4oshoqp2VL86WNN3upuVzlfowBMg==,iv:h3vLs9H0kUTgfp+nh0RG+5AnbdgK4QwN1S86SKvPYv8=,tag:0tBEXCqTJdJgSuxEWLX6OQ==,type:str]
                      value: ENC[AES256_GCM,data:FawB2TnXxAQbLPhOWSZ/w0Pb0NiTwlcOkZgMgMDFiDCBFc2CkhCU,iv:kiiUh9ivYDLwR8JC6WRxNOCoJxe4bwVJFKLhlhQazqg=,tag:ljAWXkHWJ71aZ+71cEILGw==,type:str]
                    - name: ENC[AES256_GCM,data:a2QqFRDhufIxm7DM,iv:44AUMZpfUWYWamLZADQq2WUBSuFvB4TdDKp1MQhFU0M=,tag:eMewIMB2QvWPdu5BvxJatw==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:tQQDUwPIXZVYIMLZ4NRH,iv:y9Hzcb/AkdCkx2LV94fFWG8IXqukonBZkYYizbEtVTI=,tag:onGRq1u/nvg/QmN7dFAWEw==,type:str]
                            key: ENC[AES256_GCM,data:ZX2G6JEomYI=,iv:C9oTaAUfZTboApaiMmQ9awz0us/FGprPtY9xXDT5sMc=,tag:fzN5YkpDBfj7lrsMKaJI3w==,type:str]
                    - name: ENC[AES256_GCM,data:ipjOPgX7LgeokhUSITO/Qw==,iv:KcVFlU3ttm5NXZtTioATvGfzAegkVxuQ4duAzvTbMfU=,tag:suoqhsAfESS/ky9R1OZ85w==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:jYnMcn80289eBuP/DwOj,iv:U/TX2VYimYSf+ajDV3uflXUqIm0Hp5I1IB8gvMYqMqs=,tag:5fhs2RJGHHn5K/tfSUXBFQ==,type:str]
                            key: ENC[AES256_GCM,data:dnRfNxaeBFA=,iv:43CNO5mJrrTBlpYY2zWR+sp8Jh5XwyZ0zJne7Mz76ws=,tag:cnCALF7LCXoA9AiGPQB99w==,type:str]
                  securityContext:
                    capabilities:
                        add:
                            - ENC[AES256_GCM,data:a5IUtR39cJ4/,iv:AgHn5ggIOYdiw4tyBy7eVc2YYrj85MuKMsadOIsVA5U=,tag:hDfdUZC70x/yWJXCX6t+pA==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:Genw,iv:wX/9exdGlDhJMQXB8+RuC3cyvmBIMgKt6V5fxTgXyEE=,tag:WpW9Il6ze/rTRUkNePG5Kg==,type:str]
                      mountPath: ENC[AES256_GCM,data:9PAzWg8gmqagC839,iv:b1Uk0yWiBPhqM7lZSzFSXBk//7B2xxwWmLDwQEPfaXE=,tag:alIXjYl+TtXAio0hoUtEsg==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:62OLDA==,iv:v+7irUty6PsHYzdQ0KsTYLGjxScL0ORdqAQg0DDnfR0=,tag:Xkh2PWCibfiYVD/nF/GgEQ==,type:str]
                        memory: ENC[AES256_GCM,data:g7CqEA==,iv:9ONwyBwo8NexzmMQfjddEP8WKLHUuRdwiJ+hzTFuf6s=,tag:1J6skhZVkF/AAd93lPsyEw==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:SQ==,iv:cnPzZHsgPAXH2GLGZ4Gat+MP3EJ4m+AXqjpJ9oAH0Ok=,tag:BrqNdQcYUaM1g3TqYJ45hw==,type:str]
                        memory: ENC[AES256_GCM,data:w2swMJ4=,iv:CxO3aBLlvLg4iidimtgyuKXOLqGOHHG5cL86VKhxeUA=,tag:150RjfsWd4MjWy8Y/prlLw==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:E27mTHQj+HO0cA570zMhSUHs,iv:Ij/wDV9x1Znq1xz7fh3VgBEwsmKMitE2iryrQ1WVtxk=,tag:3tAk1wMvPZqQqkEtrMLqNQ==,type:str]
                        port: ENC[AES256_GCM,data:7zJ4RA==,iv:MxhIO/UjQ9+KfKpQyRyPKapsHFBn9u9sY9QGDrPeLOE=,tag:hWYDNBC9mQ8JfEE3qurE0Q==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:ctI=,iv:7KbqeUo+RkY7lQVx8wjuowAyfa3lSKlV25LCMrmBw/c=,tag:RjY5r3ROzwdamdLYO+xjIw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:OBc=,iv:Y0N3Ht4MaoVA4YWQkfrVGTVNVK0bU8rWv994gLzloss=,tag:wIINnVStoN0XYaEe0QJ0SQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:Qw==,iv:hs7aud23apTloaRv1YC4CeOh/aoafLpi/NN3DgkcLdQ=,tag:EzDdwFS/HmnJcrAdUzwecg==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:DfjM38lwyfC6jl70z9PW2DOj,iv:hXQxDPKXkbfawmaPDyENTaKe1QCA8Mg3rbPZQCg2UV8=,tag:1htoFK829oWgwGIOT3f/Gg==,type:str]
                        port: ENC[AES256_GCM,data:dxVZVw==,iv:FAeyL3MO5IZ64DfGlyemYNZUZGzPN8joGIqrTrx+OJI=,tag:Jewm8K/F0jwM8pjoDU6l/w==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:EzY=,iv:KrfCWZCZKXZY+XQMC/DOlPjvWFldor7hHGZeyxMatSs=,tag:DIcWQbEL37Jh3uuGwRwGyA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:nPY=,iv:ec0nKdtrfo7z7AetxkHdhFpYvFLq4rZ643MaPxDClBw=,tag:txxjER28VL+5KoU0r+bLZw==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:mg==,iv:eL/rUY01PGhudBeQmCjRuEILh9m9Jg/LfgEshjToYJk=,tag:4Z/SyGyemmLi3N2wWb5eJw==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:WyK/,iv:Z0kfDfjPzpuLT3Y+6JwmIaY2FOzlpIvheMmt1xGrpaE=,tag:MaR8c5jhSiLpRcAfSi57gQ==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:96NNZuBQHBke28Mz,iv:7BHOVKUBCXc9lzb9xSxDgyapjyBX3hrqjOnlvuvlbpw=,tag:XV7pRa2zOP79A0r4RbRRvA==,type:str]
                    type: ENC[AES256_GCM,data:RriTMdBIznESxQ==,iv:FDrnWvqXiCxsR7mE01mVOqengIWjkxhS3I8caq4Brgc=,tag:djcfxu4B19SlnA9pSxuOww==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHRIcTdqa29BRHJPRWxJ
            UUg1dHFlbTFXbGFCUmxvM2Q3SGZkY2NDNTBNCkFNVVhvNlRBUW9JOFJmSk14STk1
            VnBNMzZ2cm1nalVkYWxzUjVVQUVtQWMKLS0tIGt6RDJjTFdiQ0I5emo3ZW1zV1JO
            d0c3QTBldHc5Wm5EdFhYajFZQXRha2MKym9ZDZoAbiEKha6WkXNKCBkAxm4k2Hzy
            nUQVLIiSKJ2fLbnmqqDCIB+RWjAHJgLabREpk/6CFxe60BkOMDZJ8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:43Z"
    mac: ENC[AES256_GCM,data:HKXR5ZhVptgrRE7ovoibSw0/V93ZVF/u+NRiuoUYJ1o0YSiIbdD5/eYmJZBLPVR7WQFQ4EmCAcz4XXTIIAFG8u1TU+a8prig9CKJ4pzJv1suaC6uVQA3e6wxmFxaWFQyFWc5ffTDSgTIqi8D4HnXR42bCzB2q4ZpoFu3hDZQnV0=,iv:e/2+JQUKYVQ5X40WwWpx/D3ld9YaKlShRPmIO9cblCA=,tag:w497KbXNYzr38PrP42LkWg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:MBs=,iv:rtMS5cyhTi8vr4sFpPXlDvHq6KQ0fNKGKzclWAnJY5M=,tag:Pk8Rgft65eqWnnd6NC5LGw==,type:str]
kind: ENC[AES256_GCM,data:fQXPmXFnXg==,iv:VePiNn1xfJ6Wb6k/GEANTgh02eEgU7Jq3k0hATIS1OQ=,tag:racO42zF9aLwT1Nxshv9YQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hLYAMnqM79Hq,iv:8vfqCxtKSdkLzBTwcqnB7Y65Z1TAWPacUUDv31P9hnE=,tag:LuaXfal0VBxrh+ABf1F+JA==,type:str]
    namespace: ENC[AES256_GCM,data:lOGX5ec=,iv:8/1IZeIhN4ujoNPNrGmCDDtrycU/L9kXP1FDLf58aDw=,tag:jsH7TOU55xCLgSheCYNvxQ==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:67vk24kxCcg5,iv:M99dewjUqHZotrw1xfwqF1vP/2AKDR3kAJhS5arvZ64=,tag:j8u3beLm+q/31W3CbyV2Xw==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:CVfBJ14XGRdtfg==,iv:Id4ddf+VjBGL60itDkT43zHF34VgOS4f+F11JwsGJCA=,tag:GTLfEXVZBHcl3SwB4MXY1g==,type:str]
          port: ENC[AES256_GCM,data:DrikMQ==,iv:PUY0KPXwOe7qqQTFrUqystdjVmOdgjFnNGkJCIPgRI4=,tag:u7nW/uPJLQoGYL1PnJejLw==,type:int]
          targetPort: ENC[AES256_GCM,data:JXeU4w==,iv:PvX1ZqTSWHIy3N5Gv/3dZ7i0mM+c21l9UabH+MYDTFs=,tag:niXCYXiAEqmPuFNnsi54wA==,type:int]
        - name: ENC[AES256_GCM,data:dBWBXYM3,iv:aDFEbZoSrHduoYIHXTkQX0c7e+HiD8flIaW9oA9QtBk=,tag:9kt9EUqEIfjpdk2EN/cI3g==,type:str]
          port: ENC[AES256_GCM,data:UV5LqQ==,iv:EGU2igOmhgCH48/70m4noI8Tm6/jNsaW+ZSK44zAKJc=,tag:pWGli6mGMPm/QjsxpAn38A==,type:int]
          targetPort: ENC[AES256_GCM,data:rrI4pg==,iv:UdSzL7ltR1oURBZ5NIt9xPz1+gji5VcdmcEWgww3XOM=,tag:Ri5N4g27yq36wS1EDoZgsA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RHRIcTdqa29BRHJPRWxJ
            UUg1dHFlbTFXbGFCUmxvM2Q3SGZkY2NDNTBNCkFNVVhvNlRBUW9JOFJmSk14STk1
            VnBNMzZ2cm1nalVkYWxzUjVVQUVtQWMKLS0tIGt6RDJjTFdiQ0I5emo3ZW1zV1JO
            d0c3QTBldHc5Wm5EdFhYajFZQXRha2MKym9ZDZoAbiEKha6WkXNKCBkAxm4k2Hzy
            nUQVLIiSKJ2fLbnmqqDCIB+RWjAHJgLabREpk/6CFxe60BkOMDZJ8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:43Z"
    mac: ENC[AES256_GCM,data:HKXR5ZhVptgrRE7ovoibSw0/V93ZVF/u+NRiuoUYJ1o0YSiIbdD5/eYmJZBLPVR7WQFQ4EmCAcz4XXTIIAFG8u1TU+a8prig9CKJ4pzJv1suaC6uVQA3e6wxmFxaWFQyFWc5ffTDSgTIqi8D4HnXR42bCzB2q4ZpoFu3hDZQnV0=,iv:e/2+JQUKYVQ5X40WwWpx/D3ld9YaKlShRPmIO9cblCA=,tag:w497KbXNYzr38PrP42LkWg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
