apiVersion: ENC[AES256_GCM,data:9nGmoutSeg==,iv:sOvx+mEpMnyClH5Vh3AwJDWI7KdEe2jovLvJ2TY7iPE=,tag:7tnorJH3RiFlVuZXP3sIKg==,type:str]
kind: ENC[AES256_GCM,data:Yzp8hqsNv3Wz1w==,iv:PdIAYypJwSjXAoPSI28lbmxx7EqErbzZk5IGX2+kMpg=,tag:2qSb8Wm1pHU/nPGYt9tBcA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WAYONDw0vA7Y,iv:rjK6fdF/tEi6x/WLkk0uH7RHQMroJmeW5mo3gtsTcyw=,tag:9Nnopj6bqt31lV2QQjz/uw==,type:str]
    namespace: ENC[AES256_GCM,data:I89Ppw8=,iv:NT6cPiV3XbUu8HcDkKYILY0jGZHIr99G22f+C3VFXek=,tag:kgl53O/RRTiqY0ayAP1lHw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:xPAosIXpkaW9,iv:NigduVZqCblFb0p0ZjkOloL4iXgNiwUcYK2yiJ2lAEA=,tag:HpXQFU/qzmZL/aoO4oFyog==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:2Q==,iv:Fe8SX3mJWfie2f9Z3f44MBGJWNijNs8LnAHD+u/FssQ=,tag:8eTH+1WnA4EmYT09NsRtOg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:/LPHufqpTqxm,iv:n+JxKz3aKokc8pXA+zYkvaFhUxFj15B4HzSe1hLMI54=,tag:RkphX5NLALcEax4Rp96iow==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:7ckaWbQA5UGU,iv:OxKiwfCl4HSDFnCF+YzQI0cynHi9LVS3QArUnAxuKw8=,tag:Hbq34hzqrrVhlCbpIligHQ==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:Z1td0m8=,iv:PE8ZLaLC20XCB1d5DGc/xMRwN69Syc2M+uegoH/Yifg=,tag:IJY440miImLojVwhdCfOrA==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:562kuLZ83A==,iv:/CN70ChQL7x6ZlozURr0bJn+BEMjqKpkItXnTOix5Rc=,tag:0Au09FGonqCCV297DIGRsw==,type:str]
                  image: ENC[AES256_GCM,data:pSIiVuVGH8BMBf9JniqAZvUSKmWuoVMbbpgVXtY=,iv:q4Njk/Y2geHQu9AWTK5y00qnrpvXhH2mFHevBdCATR4=,tag:QarXcVNDkHV2LAl94ggu8Q==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:1fO+mw==,iv:iKQyuWXcntCntwl1MRbsBV9GUoO/SVX80trhFF1dzTM=,tag:dFp+Cs7rKrzvuOzFzhqVwA==,type:int]
                      name: ENC[AES256_GCM,data:bxcd9TpXwJeHrg==,iv:VFP55UHIj6DSf+5vxfhj+aOiR1WAXfemoD01HM2WbHQ=,tag:v5mM7vhHEZk9iYpP4RQlyw==,type:str]
                    - containerPort: ENC[AES256_GCM,data:RazJ0w==,iv:h4fdrJPPhaMYfXDYwWMaTZx5d8GNSG0ZNSpb7O5dZPQ=,tag:hxPPzHK+C5BY/g6LM5WOvg==,type:int]
                      name: ENC[AES256_GCM,data:rbXvmhxL,iv:ZYQeAo/RbZvYRLrAmVwkERWWnm3K9BvZx/5R2ye1ugk=,tag:EqXJdPhexOwz7c9oa8Xetw==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:Dq51ELp1L0Q5bKp/HmyvhdDWjTI=,iv:OHwEtdwT/nWuRhE69xeLyqPeVePs38gn/8fkdmNH20o=,tag:/QApHKuIUt4cmOwnTWjCIQ==,type:str]
                      value: ENC[AES256_GCM,data:eKttBvDe6jMvuZkAfMJSgfXQOEymLJI=,iv:2Bq4+sKdsb2HRrKKs3myDpGIVHFYkeVW+nZFxtmSuLc=,tag:FqGTcSdruPmR/hiV6jeT1Q==,type:str]
                    - name: ENC[AES256_GCM,data:TLELjSBiIMQ=,iv:CTs3JhvUy8x2YcqQq1Py72gR/m9ZbjOlfWD/a3tFUvk=,tag:seP66LZbMawlFPaNLbuDGg==,type:str]
                      value: ENC[AES256_GCM,data:gXTYtwWaSQ==,iv:oFS7GH2bWG0oOZkHVbKuovNlLARTm9GGJpPg5H/WbRQ=,tag:ugU+LPsuNzZRCupM6H/vJw==,type:str]
                    - name: ENC[AES256_GCM,data:dfXdN7IXXJpN3GpQwfM=,iv:3MD1+OEYeVUvg+196wUk24g/DT7YlbR+rEGsU4Zgdv8=,tag:HtAV2PlNR4+h9yZzP9yu2g==,type:str]
                      value: ENC[AES256_GCM,data:7B5XYTUyAA==,iv:Sfk/hYPHFcHpmtApDH1wHCOrAe5LEcWdAU5a04aIGk0=,tag:Xd9me2irNKbB4g6lKr2/Cg==,type:str]
                    - name: ENC[AES256_GCM,data:/WKFIkZ0yWH9,iv:Ya3KQHBDe6snqwv5iDW2qyZx7k0fd6jgCNPiXCvdOqg=,tag:oXVWkywDTR+KpqSfeNBFEg==,type:str]
                      value: ENC[AES256_GCM,data:mv4=,iv:D72deVme7I/d0WA3QpbGLz1g5uSvhqttvcIcv3sluxA=,tag:5eYLnMzsgLkcaOAhNpe2rQ==,type:str]
                    - name: ENC[AES256_GCM,data:Qep0Mwrb0Xe0jbWARg==,iv:5CwxyWSQ5330TyNf26yIGB4rsH63DdDJqZwH6uVoLhA=,tag:KNGX4O30/N0bU/UDtGa3pA==,type:str]
                      value: ENC[AES256_GCM,data:p/DH,iv:KB7XN/3rbCIKPUWTVm98qb1F4UdtnWL6dfwOGj+Uens=,tag:S7WzV1obbj2dOeA9AcO3kQ==,type:str]
                    - name: ENC[AES256_GCM,data:41S7CTtT7OM8Zsg=,iv:IniiiZUbJr1XLIHztYTiAwqGHExBpOoF9U/XRA6q0jc=,tag:jrF/dL0+NMcrj+QJk5k1ow==,type:str]
                      value: ENC[AES256_GCM,data:JyIN,iv:+fJqOP0CD9jowBCCIyUGntWk+KjX0JlBGH9whksiYQQ=,tag:ZdgUN3goDNEUg4MgNfqEYw==,type:str]
                    - name: ENC[AES256_GCM,data:rFFTDqgqqYT8R0TafWEo2cjH3lE=,iv:HgT7brwEAOtVU5LjA5oMuI630cgk7b9YNssh5FwR2lY=,tag:8oLeSV/N8Ah8oO3H0HEJ/A==,type:str]
                      value: ENC[AES256_GCM,data:NsJCJCk4XOiublVuA4c=,iv:oRTfJABJ/QouuWF6+QEsj9VRUDMXFDzcdLjoHAKd9Go=,tag:YGlQ4+MkYI67DPbPF/F1Rg==,type:str]
                    - name: ENC[AES256_GCM,data:qc6i2dm/J/bFXHgUwzusia8vw7d9I+e9AQ==,iv:zYH/IVWY5woZrWz4hIrbYL2x5ti9DgMn4xgOKQ8o/Ns=,tag:0s1wqLPy5LPZMRklnMy5hA==,type:str]
                      value: ENC[AES256_GCM,data:6T18lXq6DxDoEfK5sjYzEJOPH/uSM1NDO+OEySciowQE1/UincLa,iv:P5l9mYAnxdnqp9j9BeS2Wc4yA9ptZbkHOMFw/QzWoj4=,tag:4R/+xFxgf/NOPW+SIb52kQ==,type:str]
                    - name: ENC[AES256_GCM,data:BjqUTroxqUL8PF9V,iv:kJQvwSp01FeYxF7B73SMr3qkFOnbIfetbbUzvtKzW/E=,tag:SqZhiQmWfz4dD8/rwxJagA==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:t8ThFFbveMMtDdoRUo3H,iv:Wz7nzXE3YycFORevosMH43c8kdDUE5BsbAt6tnO5P7M=,tag:2SpnXqieVYd+x+o7/SEHEg==,type:str]
                            key: ENC[AES256_GCM,data:SO34DCAQ9VA=,iv:SKZ7D+/UdwUuUzUlKkyiRh5o/Q1k3B/fop0kHtU97Uk=,tag:sBZcomeRy4StEDWRcOU5BQ==,type:str]
                    - name: ENC[AES256_GCM,data:oZO+F8fF6Kvr0h7RUduA2g==,iv:cPnhqD09CCxqbzZ8q2kKR4ntQ1SWJXimpQueF4mhH1Q=,tag:HYe3WIGI4/v8uxOOHbpO/g==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:anJzeyTHMonsElxai5PZ,iv:pkA+mLD2VZCA5fx29861idhEpQiZU71l3radFcL+g8k=,tag:r/t94Ka+yDNWgBbr05zCOg==,type:str]
                            key: ENC[AES256_GCM,data:FJLOdNLaHDI=,iv:m4wjSw4eX3GprZ6i062OFe2mZZpvufWBGGLK+u2D4Vo=,tag:hG+jsKM9qlVprUkai7SHgA==,type:str]
                  securityContext:
                    capabilities:
                        add:
                            - ENC[AES256_GCM,data:GSQI7HB6sC3W,iv:N54kYmRjG1QYTnbHZl4nyJI48fsqubj5+FVlo6SzPus=,tag:WEFk+zaS260lURWtnCWrqA==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:nOSB,iv:Db4E6gTN4a24m4UQSqdqHfunr2SxoHOE3JcaLfuNtTY=,tag:cNbZ/2/Avu+5Y3X5EUgmDw==,type:str]
                      mountPath: ENC[AES256_GCM,data:8CWc3IqvQAuiPlC2,iv:XB+mL/Jt5NW4ObruYNVbH5q6v4gc6fbwssZV4CbGJvY=,tag:YNoLNzhRtb3yVYYnyC+qpQ==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:QVs1nw==,iv:8h0gvDbozj929tb9yI5ySwcdH5GRmPIPrf/1EBbIv+k=,tag:RHqnjWYyn+hdcSQMuBCNPg==,type:str]
                        memory: ENC[AES256_GCM,data:wY8dWw==,iv:xENjaqLM+Dk5rpZQup9Yw7jdHn/rwFy4rxQQDSc6WXM=,tag:5T1Fg/VwSS64lIYUIRlYSw==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:jw==,iv:rjPHW5QpbGWOuEGe9BDFoY/2ph0XLlHuiksdOV4s2i0=,tag:gA6hNIZSWS0WZNVRbJB28Q==,type:str]
                        memory: ENC[AES256_GCM,data:mF82th4=,iv:Vx9AVwLh8rAqDfHzm9WOUjO4kZ0dV2oK1sfc4JVgTX4=,tag:x9np4TETxVO+R4Dy/vfwIQ==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:koM7vJlQ1mWVcZLWeeJIZpfe,iv:luTCbPhkzstwGGsc80jrZNeLFkj01tLc9w0H49gYszU=,tag:YPeyaZWIt7wdSF8NE33xUw==,type:str]
                        port: ENC[AES256_GCM,data:zEMZ1A==,iv:U8Gge3nhNI+dXqcp9U+sPEEDTrBCQwc3UcsrPe5uTa0=,tag:N0LQCwAHhhxM9LIGqwQrTg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:uG0=,iv:0xS+FPMK+R36lGv4h7e3CmlzyRApuQuT7QyHPB3c+cE=,tag:St/K5bW6j3myRhAQm4MLzQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Uts=,iv:/ZwSG7azCfe1kr4uN7I244O2Q/SYgIcopDcXJtTEb8Q=,tag:ulOQbErCcpM2ytCfX81nmw==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:lw==,iv:saMOHNKrLB8Z1iGoUn2mi5jchEHxPmr14FONsDPZkzc=,tag:1IkvwgiH5voed4MR7uXRlA==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:/rPzrymXdvriqkeHPmW4Ka5x,iv:4Pu9ad222ObjgytTLYIF3MFIC2fcdVj+t167TpCw+zE=,tag:X2lh8SI0w7ec/lQQg3+v/w==,type:str]
                        port: ENC[AES256_GCM,data:KZweTg==,iv:m4TIPbTSUHO99KDm9m7qaZt3XfyiaNLU4NvXFn/szu0=,tag:fSijdn32DhbZh6VKEd9CYA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:8MU=,iv:INwlFcc7cd2NZIRyz9k942T/UKI+XixZyhKB3DHFc84=,tag:nW4NqjBBhfFc8tmdMTdeVA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:+RU=,iv:ohWli3Vsklm0a2ivDVBpOMXWY4do8EMcrh6qqe4GGfU=,tag:xbz+VRRUcCpT/unheTrBFw==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:XA==,iv:1unIPskB5UsjIM29LrORt/YLuob9r2oHePq6q8mo7js=,tag:eNQUwYj9wypcfOCVt8IDrg==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:q266,iv:ji/MxTYVEc2v0lKghvT+8W0ONb2SKwO8yFhiU2ayN/8=,tag:5h5hanSwTGkXcnVqv/A2kw==,type:str]
                  hostPath:
                    path: ENC[AES256_GCM,data:wUsxfczwMk0dBQXs,iv:nGIBxf+UiBq0/y0Ez/RWiQzpuqeC010kp/K/hnEH/d8=,tag:B7vnqGgTpGapSp+AmhtmMA==,type:str]
                    type: ENC[AES256_GCM,data:Sl0M6FSaIXr70w==,iv:FP1OJNs+b8l2i9Sz7Dh92iCbHQ8ym4ONdOz1+NpJzxw=,tag:dg+tQ7etDnSgAHfqMF0n3g==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaWtnazFMR1FDQjBRd1Zn
            N3Z3dWovbjNDZ09mV0xWTlJMWkM5Z0Z0SDFnCm9DcU1YVXNqamJFVU9PaUpWUUV2
            U1RQYmhvTnB1WExKVVNZUkJqaU9JbVEKLS0tIHkwOW1uVDBWazZMK3BBNUlyM1Ra
            OG01Ymk1UzVRZFBzMVRFQ1Y5YVNBL2MKnHX5HXSXLxanVssfZWnIJ+G0cKVH06lk
            bgOOEKLz45vCPK0WMEbJzfLFNTeylknqy3mOa/msGdLEwgpvOOwKVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:28:17Z"
    mac: ENC[AES256_GCM,data:vs75wG1z12SjpKycOHkrfeeAWmH5qW7IieghnP2tdIkl6VFq5UdibcipZqlIeQ1tlSDwEngH53ggH3mwYlAKK+VFw4M7RWcWE9d7HthKxxiQR0R/nY3r3BaMUfHusooLjZF8s+twkZFAaeKcGpo18tit/QwI6OQgtXJ0jnvnpNo=,iv:BXjtx6UTPvj+Mpj/opL0UYG8Q9eMKR96UzAAk621h98=,tag:W5aEfDqhODQhgEZu3gYAiQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:1fU=,iv:wj/ZanpuUZthNVaP8ijUHsNf3sctO4BJ9hxwU3liunc=,tag:zYaTnEpzrErTWVOoZl0iLg==,type:str]
kind: ENC[AES256_GCM,data:ENcJESf58Q==,iv:KK1TX/osumRg+7+IBcMqTujx+nLE0n4noTNv+s5B9fQ=,tag:UEFotA0DbZEs84UPXem+AA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vtM1zrNyVIHk,iv:38gbi4K7ejCH97u/5jS2ElVSDSbbrPfg6TLIRtGMfcw=,tag:Ug6ULLkBRq0Z0gXe5Clrqg==,type:str]
    namespace: ENC[AES256_GCM,data:ZKUnBGI=,iv:dPYOzDnG2fz10lBFAodj04ZuG0lOnMi01EOw2k4tTS0=,tag:MHQmTw8YMclU7c5IjC0Wow==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:HRfAlcgtVrJ4,iv:cnue/E5ap/chwUze5RzYyVN5O7iW0g8hHa5s8CToJEo=,tag:1AupDvshEhgC6KYukLlG9Q==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:3v/ezXK6nrvWfA==,iv:d+OvoA7fF7NYJ/170swQ0RxIzp1d9beCsWjlhvkUmak=,tag:GXoBnOeN/4i3161aX2TH+Q==,type:str]
          port: ENC[AES256_GCM,data:sxkf7Q==,iv:ZJV4VDWqfsfEqPsj0s2M5TgFUOQ0h079F26pavuQ2gg=,tag:zRErK1PdLZoIlbo9Tcb6HQ==,type:int]
          targetPort: ENC[AES256_GCM,data:eNkg3Q==,iv:Ig7XlNaBOZVb/mmy/WDtjY6lq9mEjx2T5EdV3gULL3U=,tag:sEjcDhWgLzzTEnIrVH3j/g==,type:int]
        - name: ENC[AES256_GCM,data:nq7yH7tU,iv:E717kLib4TkOC/5r2KgWPq8SngXdfGDmlIK+PCSKcmU=,tag:32ecFg3Xoj0CxoJ7lHxpVg==,type:str]
          port: ENC[AES256_GCM,data:an7IGA==,iv:oDLA1Lmbyu97fomWwb0hGe5F/nmHx5Bd6vjkUygiaRM=,tag:z++MMMfph/Qigak9x95k+A==,type:int]
          targetPort: ENC[AES256_GCM,data:szkA1g==,iv:IZwyrjp5CyaD11VmR7lqMfp9ppqD4a5R7g753fgvLDE=,tag:TnijzXL/I7MPnOEEsUJstw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaWtnazFMR1FDQjBRd1Zn
            N3Z3dWovbjNDZ09mV0xWTlJMWkM5Z0Z0SDFnCm9DcU1YVXNqamJFVU9PaUpWUUV2
            U1RQYmhvTnB1WExKVVNZUkJqaU9JbVEKLS0tIHkwOW1uVDBWazZMK3BBNUlyM1Ra
            OG01Ymk1UzVRZFBzMVRFQ1Y5YVNBL2MKnHX5HXSXLxanVssfZWnIJ+G0cKVH06lk
            bgOOEKLz45vCPK0WMEbJzfLFNTeylknqy3mOa/msGdLEwgpvOOwKVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:28:17Z"
    mac: ENC[AES256_GCM,data:vs75wG1z12SjpKycOHkrfeeAWmH5qW7IieghnP2tdIkl6VFq5UdibcipZqlIeQ1tlSDwEngH53ggH3mwYlAKK+VFw4M7RWcWE9d7HthKxxiQR0R/nY3r3BaMUfHusooLjZF8s+twkZFAaeKcGpo18tit/QwI6OQgtXJ0jnvnpNo=,iv:BXjtx6UTPvj+Mpj/opL0UYG8Q9eMKR96UzAAk621h98=,tag:W5aEfDqhODQhgEZu3gYAiQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
