apiVersion: ENC[AES256_GCM,data:n/4=,iv:CKFb2vsNcBNk5j5t6lLWjxthhNWdRlKNYXSmPtisCh8=,tag:hHn/gEKstgyxZJWH+Np22g==,type:str]
kind: ENC[AES256_GCM,data:IyFy/Xk1,iv:SkADR03P50t9frx5dbydBCai2poqeax4qWWyxKXHhj8=,tag:+Plmr3+Y4XNitALGZYN+Pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6/19pRiu0XggfeWKbpKt,iv:SvD4Swju/mlSz76xlJO0vK66b6yHz+UtHLkKRWS1TVA=,tag:bLUMQT9Dz1qDezHRmC+rCg==,type:str]
    namespace: ENC[AES256_GCM,data:rVdSnaE=,iv:3fLrNnX2Qd/tfE1mqzp3FivK2gpmDNrwyjoP2m6307s=,tag:cvYAPhC0SP6v0f7caKilQA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:8k1P7JB4Vrlsoe2jme+Aw0egv79Xu2lX4A==,iv:8eK+Wiev8VRUg8zQtLDn2ojIiZY7o1tSHdYmaSICEu8=,tag:IcesaO9Hko82DUB3ofPY5A==,type:str]
    password: ENC[AES256_GCM,data:elK4YEQaOQoTa8tIpW6TH6Wqk47Hyf08Yw==,iv:J48s40oRHEG9Y3cC2UeOAFzt9iSF1EMLxIdstl9bXWM=,tag:ipmEmBX70CyClUSUT+EXFg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdVZyZnN0QUptL1pEVGdE
            RzE4ME9SWmFrRjZ1M3BrM0JWby9HdnlZaWxNCnVTVWNuaHlFakdmOHNqQlZRdG1x
            V1M0c1dKZElXNGRoZ1dNWjNVZWNybVkKLS0tIERydEF1d1hQbEkweWl4a0VkalFa
            V0JxSERnbnM1MExzNjVwY2Nka3BZZHcKJgGPM6i0RFEfE1hn/lCjY2BoGP6R48Z2
            NW06NuyYVWlBathmfgb+NbOip/6BXGctgddWEufJITbReeDqRPQWbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:43Z"
    mac: ENC[AES256_GCM,data:/F4jFGp8pG1Fyz+aCbOz88QPVUpt22EHp77lligzj5nWRj6DTmS8j0LgivOJijLuFgWkPyIVZ7wcBA7UmNbUQ4wJ1+FKAyH6EumDP0SuWRl5nqhup+bnUygVdyFay1YURMn4TUhBuOTig21e5tJy/4vo09Km7x5f32BNjEtRE8Q=,iv:9S+mtgCaWZixR+7+np5JoGcAyC8S/tF8Ae5tRhKZ3FU=,tag:FWf28fQJmyJC/GD4hZaKAA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
