apiVersion: ENC[AES256_GCM,data:4vk=,iv:GQiOHT28WP0FNYe4TBpxkBCHXRT2XMxY4hkJTpb8TKw=,tag:b3OWaOmULg13vty4VzvmBA==,type:str]
kind: ENC[AES256_GCM,data:bi5GX7lvtZWqGad57fv3D9HEnenW,iv:2mYUCJw2jCT3djTEpuXkBvALBmiHVscm1mFReE9qXAo=,tag:m2ATI7Z6xXnh7hpuY+tu7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TJw862L3V7fLXmIv7g==,iv:HPLxqFInYDFsz4McR3zUnA6tSMS9Pk67RbbzIelT0Ec=,tag:V3ImSgWUfwRXNAceOEXusw==,type:str]
    namespace: ENC[AES256_GCM,data:bX+yL6Y=,iv:ZXmknr2Dc2QpSO3zYHYgkdDHpmgKPUOOjNU/t++g59A=,tag:hym1zVctpFvoygHENMFseQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:gz1iXs83f9Qez9epiQ==,iv:Q97JBCvJlOgGJKoP0OPzQtBtXlDOHFzsTAXKqhxw0qw=,tag:81lMwAs6C/gkpTRot6oqNQ==,type:str]
    storageClassName: ENC[AES256_GCM,data:EBVGC9Mu3kk=,iv:Nx+gpMZMyYkPnfj4XlMFBkrQXk3ew7I3ib0qakP1L/o=,tag:TLdIpY4cSr2WieMwHxkWQQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:op/b,iv:Cdr++E+qax9NzNNKBkj9CHWi5JtNah1woQNgcJBF9ok=,tag:QgdPmiYE9Yy0hRNN3bAb1A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDlEZVZsL2ZLaXM4OVZa
            S1R0eTA5L0JFZ1R5YWUyYjhoaThReWFReFFzCm42c3dUUGU2bm0reTZxZnNmZWNr
            cTBZOUxFbzJnK3Y1ZWQ5cytkQzhCRjgKLS0tIGRITGhRQUZJU2VOOWpUUlZtekxn
            dmEzOUIwVmtsSkhkQUZFNTBkU0M4c2MKQADa/+qT3+NyZcRJUVm4rsubiIpXMJq8
            evSL05nlJ/8q8dQRRS4UD1lKVdBF4Xh8qfbhci1xnV1jf1/hD1/OQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:JpA/SokRs0WJpOrfwD1v6YDp6Q6vXnd6r1QQhu1faVUHo55k/M99AMKNodvr1c903o5IOvbW+4yMsBTUpCr4QiRE+jGiNqqroc6Ba23rV4ry4lU2dXUPwNuTk+CRhAedYA/qJ9vHYLZ9gHarwbSVkcMlXn6ekRdHyZ1GWf3JNhs=,iv:dKD/kyJshcsGxitB2qhJxRtJmyLk1Nm7VxN/mVEkkXw=,tag:tVCYGQVu4+z6bkIuPWr3Eg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:avZztEO7mw==,iv:csprlPp8Il87KMYJWtWqj/4j8Ck+aVdyiwNmzIOeuCg=,tag:T08ZySfI0n1jz3x7vsUoog==,type:str]
kind: ENC[AES256_GCM,data:E/1ctfccFi4jjg==,iv:GNOY1TTsEnqfxVn7F1MTzGrhxEATrFpDd2/rLfpxKGI=,tag:6MW7PJXMQPvTpJ71Qx69YQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hd4j8l2c,iv:SF1Kr5R5YtteXyb/OVdA34eVGf47IUMNiNqiYP54ksI=,tag:z6HZyPJ8A7b8qrwMCF9lKQ==,type:str]
    namespace: ENC[AES256_GCM,data:U36QZjw=,iv:5xiXDsnT8RFPVVKjPI1BzJ3W6k4/8KLxKCU8vm0ceH4=,tag:U9hKIqXKkRm8osfuDsZpUQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:O4TY6cym,iv:KGwn1HmgVWx3ErujPzj6SnSR3Ihlm/2nxUQM8EdTxpM=,tag:GK7R3ci/fkot0eaJx1Y5zg==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:0Q==,iv:xWS9HevCfPXxhTyzEZNYe33NsKjNZbVlrG5BPe7E+/s=,tag:ibxh0KciL2vo61bhaEv3SQ==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:zmzNqQpH,iv:3X+0Y/QhRzYezLOsk+iPASql79XyeOaZCfrx2pA8Ibs=,tag:8TlPFCXYLM794JEWNlOkKQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:xNZqtqRe,iv:xHRiRhWCPF6hAR0/JieTfomG+66LWD7dOBRzytrTaes=,tag:Bu1DtuDKPTVjX3vzieMR0A==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:pAKbS8U=,iv:UsHNbEBmawOHbrZ1NP4IP7x4teAe7ZNDD5nxxNZpO0Q=,tag:t7CRXu2qUapDe9NTBnh79g==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:qKKlubcW,iv:qsRLBc0nkpCDZtiMkbnVEFYA8RE89sIaWYNbubze5JQ=,tag:JbcfhnjxeLI71lkVej7Neg==,type:str]
                  image: ENC[AES256_GCM,data:lotkzoQHGj19A01bOIJO35AtOLiqlFAQTEUv5IpJZVuYyTnAdXOjVrjqDSg=,iv:EyO8PnYLeS94o/PY3KtNmUzhP8HTp5D078osaw27KmY=,tag:2HzVPswNnibRQJ4BQtNcDQ==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:66QtFg==,iv:XeVtj5n5whhBUSfg5HUsKcM0SFqsRZx4/Tux9XFrtyU=,tag:ys+pUzMPRNSZmKZ5sz6oow==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:oImaJg==,iv:MZH2Nn1BL78E5dOPoDtk2I1x8nhYBODgOHCf4kcS/Ow=,tag:j9JvtAu261aZ7uDHlrUh7A==,type:str]
                      value: ENC[AES256_GCM,data:RQm3/w==,iv:S4eeajY4I+mS7Msc5SUoysKX8KR9gDAvN0qbPMfFf6c=,tag:Z1JdR3E64NpwmMdKev6iCQ==,type:str]
                    - name: ENC[AES256_GCM,data:pwKCRw==,iv:WYELjwTyF00AaEsatJPrbwHK1pJL0wtmWzYjnrhysTY=,tag:vxS67bku6dBUHq1AMnSuOQ==,type:str]
                      value: ENC[AES256_GCM,data:/F42,iv:P9Xk2CdFfs2lV4cYeInbTIFbUcG1DlrwbmZ9YJwyhy8=,tag:UuFWH6oDrUYK8vzuHjy7uw==,type:str]
                    - name: ENC[AES256_GCM,data:SlA=,iv:q2/AgdUfQIpj+hPwniaMZvvZUSMc/aUp+YN/Xs1IAKM=,tag:57oGyx+US4QjE8M8AVtV2A==,type:str]
                      value: ENC[AES256_GCM,data:tyWpHi2fo+WnKQ1mBwTGUw==,iv:LvJkY1Q08zgv4s46+jj6rqTvs0HnKloOx1wuvG14aaA=,tag:7UrNC/iMDQUWV1Ut19LK6Q==,type:str]
                    - name: ENC[AES256_GCM,data:VHRKHuo98pZJQQ==,iv:JUqQ7kBrBosRZ6jT8F9TroQ7MhUjvcKnxz62Ixv2900=,tag:celJnZTiH5nGK9SIef1uAw==,type:str]
                      value: ENC[AES256_GCM,data:45zlo9NIMxPatDPy0SWhM6yz0YpL,iv:n13pvS5kk5U3hGCB1HYO5HwSdbx7/glAD4oWytIFVwA=,tag:gvWx0+dDS/pk4FvCPZfhcg==,type:str]
                    - name: ENC[AES256_GCM,data:PFq0lt8dfL3nKBw=,iv:bo0O0wZATwO6tp0+uAcTeh0w6PAVCAeH0qVMrTLyC80=,tag:vxdMSQCIphM+xsVPA5XGew==,type:str]
                      value: ENC[AES256_GCM,data:SfFa8tLbApeE/6bLLLwb8YG9t7w2,iv:/IIojBzR/KAJvdWO14O9tud9fEsDZXBTuOicdSwR7Ec=,tag:Hd4fwH5Ki4JD5OvOls21NQ==,type:str]
                    - name: ENC[AES256_GCM,data:jLRCGVgOvJU=,iv:avVGuCDTg3fvyOhXzFDOIbeiI5p7GVfLqSOMa251l18=,tag:hOhHXHwPRDHoqEZeEs6q4g==,type:str]
                      value: ENC[AES256_GCM,data:PIwSEyZBE5LJcCo1mYut/oqbdbSQePuT3pxLwxqVTWXkqz+QPVOgYhhs3+F11Fd/N457otiKQc78gYbNzK/wPcUqGpETmil8iwZC+SRyKhuj8m9K/k9pUjbfzslfF3n0wJRJ,iv:ktTzcxAYQJ048xn3vW6VDkz7AtPKz8Kz4SeMLxGTQ0k=,tag:LyTSacYo/mjEphg3DoznpQ==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:P6MwCvCA,iv:vufqWBoJYyae9f9e4WB+VyBK/lgIbgbslUGfygxFnBw=,tag:eRge85BqZ6XlR8icihrVlA==,type:str]
                      mountPath: ENC[AES256_GCM,data:DR7hwcBRJQ==,iv:TfgkAV8bxQ/t570jCNHwXuDIWCVnazYSRyDVTux1WtM=,tag:LgmBwm8OUZGiQqbfUyOxOA==,type:str]
                    - name: ENC[AES256_GCM,data:zWpH2/8=,iv:aiWEp5sJ4WuU1RoByn0/0pb3ja6EO7bZ9q8kDSRiuTQ=,tag:ThI47aknd1S3UZagTB1Qng==,type:str]
                      mountPath: ENC[AES256_GCM,data:OH8ssqWymw==,iv:hRDqjUEiRCyfYsUsENGUdwdDjmdqclK+H+TSh9q5BAI=,tag:DJP+DNDWMQrCcDfgrP+ZnQ==,type:str]
                      subPath: ENC[AES256_GCM,data:594IhD+t,iv:soDgdF6EhSmFO9OYBEm2GKmPshNk7bwcXh5hAfa0JhE=,tag:5BaO12IxeiH3FYQkfPipUQ==,type:str]
                    - name: ENC[AES256_GCM,data:OdeNu5c=,iv:rKUguhsBYvw7wRe56R7NIX+oWPHanqfDuN7kSr+U2Zw=,tag:awBFChSgqD4jfdaOS14Phg==,type:str]
                      mountPath: ENC[AES256_GCM,data:JSS1W4DNuVVj+mG++qk=,iv:JjBq72Jyjetp1qGjpfssQxb1hwp/sKaTgS4xtAGuSq8=,tag:vYUfe3OpVLvVP4vTgg0Qrg==,type:str]
                      subPath: ENC[AES256_GCM,data:tq8QZ2NOjTpEYDxqoYDAibji+y9Niw==,iv:GQrMeWIoiEcQOQHJByWjthgiYFO6jQTZoIWOPBst1gc=,tag:B9kmQ+nHzbHPhUlsnAEE3w==,type:str]
                    - name: ENC[AES256_GCM,data:DAPJbuJNQ7Ia,iv:7/JtIIqCLq290pyvUrhqJ9r8Y/N5sA+AvCIKWBlE9NA=,tag:PCov6XEZ5TB9UcQPE60Zwg==,type:str]
                      mountPath: ENC[AES256_GCM,data:WueCVlIv3vyANA==,iv:qXzKxXEROrlbw85rilKm+uiYpXJ9mhFZ70T3HkIsbSU=,tag:YY9KzauxJxDAH6f+OCxVQQ==,type:str]
                      subPath: ENC[AES256_GCM,data:3LjzxbpHVCbGcCc=,iv:RPMmo38GVUma2+DOLP/FYs2QIfQ1GOOrbaNeGuluSoA=,tag:ayeKG9pqnUprKJQJtU/5rA==,type:str]
                    - name: ENC[AES256_GCM,data:KZGb/J81JLQ8,iv:ALnSe6PQnT6hb1TY0tAo8O2tspN4aY9JcL5xsN+GBGs=,tag:XxkoygnqNdDyH3m/nQf2/w==,type:str]
                      mountPath: ENC[AES256_GCM,data:Nir1HgT8ZPYc,iv:UeA3eDHYpogQA6mVui41ewdzno4yF5YR0ha+SFF92FM=,tag:+FGthB281sh5Km791EQRGg==,type:str]
                      subPath: ENC[AES256_GCM,data:YnB/EjUNfHw=,iv:dOIWhFiSDXwKmN77+G8v0xTLMkjdhMq+5E3IGws5Mio=,tag:sUmfNgUF1ZxpXreRu0UUsg==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:/ZxHfA==,iv:xVqZwCGFgwPZabg5f9x2t6qtOwJdVhmg3VELX8Ydybo=,tag:V033u2Rhu2F+4mahPqiPrA==,type:str]
                        memory: ENC[AES256_GCM,data:8lVHmWA=,iv:iA8YCoDvnRAyOmdH+5kJfnGQuuD59AQ+xmRLFIPFW0s=,tag:R4/jt5kmZT4TLZks8MiFVw==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:XQ==,iv:y2x8vk6CnXAArV27ULn3v1ARofWUPs83DbcdBC8JdcY=,tag:UK6PfLfSEpBGuPTAZFLVnA==,type:str]
                        memory: ENC[AES256_GCM,data:qZ6Z,iv:KbiNzns3g+34cMK9TiX7D6u66HlBNyy7zqBy21vSjQ4=,tag:hdGW31asg5p3hIN06Dg9kw==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:mYHbUko=,iv:zyOhp+1pZI18Ow2BWGccXN3XtzeJaVv22Lpp69hJPQo=,tag:c7w9MfJAcDvBsb+FzQxUEA==,type:str]
                        port: ENC[AES256_GCM,data:vcbLvQ==,iv:InTZJlyTG4zpF/Rbtt2tOfLqyqEljfQbA6IKJj7FImk=,tag:tIPgkwKZthLliDYug68cLw==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:4xM=,iv:QhAVomqhB1UVW5K2xr7AZn70CagwJNFFCp0LqQLbeMA=,tag:P/aXyzXdjnRDAkuwVQjTjA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:JG8=,iv:fXH2Kuzd7xk5533LgRucghEaW+1td0KoDap8HJr8WkM=,tag:GPTkbXRfDDUtZjRiH5d95g==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:NA==,iv:bXGRPhx9zHVpL8oF67KPr24O+NdCMvrvKVKYVQ6KPKY=,tag:/hOSUD6rP2qPDsAszkT/sw==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:VC7mHPE=,iv:/WecNVSbCiFaaghX6HQ9K+PGozCBkuOcUcEYDVicAbw=,tag:t1fk7J4A2UlBiZ3+5Enpsw==,type:str]
                        port: ENC[AES256_GCM,data:iofDDQ==,iv:NIxLowWZRE8E8dWlYiqED2qbZ9OiFykPo1YBVtX+jHE=,tag:VM0Ci/C9kXBxccrATFe3sQ==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:sdI=,iv:tFDyjlxcg4JfdNgH1lJfXLXg9bvFD2y3uBmsFiC1XI0=,tag:7oQjqF10qpS2XCDbOO31AA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:7DM=,iv:Eh2xxCuP45ws6DZQ597aBtSCv9CcXg8aASBiboUVdWM=,tag:icK96SwNowrcGnxRtCmBuQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:uQ==,iv:sn7zZNvnhT+F6Nt/k6t6kug8jAv70jMwE9b5NKnlKDU=,tag:bDEMM9raSk4q5bNK7tzIPQ==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:xZ+udlQo,iv:A4rY80yc3DEi0KByAfOJlh1alBqBanWwOV8XgwdtCu8=,tag:87198/INvWPnXsFd//xsew==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:KdvhB8tHYHTswfScSw==,iv:tEHY1uFokWLaGhWexrHDd4xBX2uqMhFgm+o/ACujOsw=,tag:+GXPBoGM94llhvIFuGxbUQ==,type:str]
                - name: ENC[AES256_GCM,data:QGPcDqQ=,iv:elVcJw5NKOVrk/PWl3VmFE9RSA1lXfLsgSwpwZPG3pE=,tag:P/Mcpc39Hs+Z20fJi2oqRQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:dEBhZz5fFb7xJ8ueKBwfbw==,iv:IrBCgwDZAd9kg0flG/Ei0gVirwAGIsAxCtLSz4C0qIs=,tag:L7oIJiZfYp8WnmhFqD6fuA==,type:str]
                - name: ENC[AES256_GCM,data:m9MEq4uUNhWi,iv:09GmS351Ja04uqBnvM1jhJQnXHOmmW3IVPeX5pfRzuU=,tag:Qs2vvrcZmcgGJAVwr/eP4g==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:bFzT3xgO9wH5Ezf59B7t66YN244=,iv:Nw4cJhOieLJjs1/sJY6ZfQsjwliEeRGULtrr0gA8WOM=,tag:bysh+B4l/iWFY5w63kSYiA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDlEZVZsL2ZLaXM4OVZa
            S1R0eTA5L0JFZ1R5YWUyYjhoaThReWFReFFzCm42c3dUUGU2bm0reTZxZnNmZWNr
            cTBZOUxFbzJnK3Y1ZWQ5cytkQzhCRjgKLS0tIGRITGhRQUZJU2VOOWpUUlZtekxn
            dmEzOUIwVmtsSkhkQUZFNTBkU0M4c2MKQADa/+qT3+NyZcRJUVm4rsubiIpXMJq8
            evSL05nlJ/8q8dQRRS4UD1lKVdBF4Xh8qfbhci1xnV1jf1/hD1/OQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:JpA/SokRs0WJpOrfwD1v6YDp6Q6vXnd6r1QQhu1faVUHo55k/M99AMKNodvr1c903o5IOvbW+4yMsBTUpCr4QiRE+jGiNqqroc6Ba23rV4ry4lU2dXUPwNuTk+CRhAedYA/qJ9vHYLZ9gHarwbSVkcMlXn6ekRdHyZ1GWf3JNhs=,iv:dKD/kyJshcsGxitB2qhJxRtJmyLk1Nm7VxN/mVEkkXw=,tag:tVCYGQVu4+z6bkIuPWr3Eg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:NY0=,iv:2WcVNi3BBWDxAfneuj93MzExXInNCP4PtoAU6IrnU10=,tag:Nh7LrgMIt/J+OdZJTzL7jw==,type:str]
kind: ENC[AES256_GCM,data:2n540/nYlg==,iv:OBnYkLC902YrAaqYeXLLbIBS69zLvz5SkLqLlXxp4gE=,tag:krtRyPFEfO3lqfeobakPCg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9gG4Jbok,iv:SgYnfUdp4O7ChG9QN03NPpjvMlBLH/piPKxQk9JeJYE=,tag:4OLrZ0lX04f5/4ov4mLOJA==,type:str]
    namespace: ENC[AES256_GCM,data:WV8J1is=,iv:ZPkK/OHaqYJhdCz1hc9jdPHqsFJkDbnS+vlA7mIWSNg=,tag:xRoz8oCkawi8JHhaxTjM0Q==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:/lfisPBn,iv:ZkP7wHj9p7qXaoeOUSHgUnfF+CjExiyo5peMfvf1/0E=,tag:sCVsyYaP2VivlEr8JOnqhg==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:Oc0WjA==,iv:8e+AePNwz3IthSDBEKlFYrmso/IxBb1XM0atTjD8lYc=,tag:OgLQAsr1dgDrRDfw+MfIGg==,type:str]
          port: ENC[AES256_GCM,data:yPPxBw==,iv:Qg/a/ZCZWqk8KmBu9H27tyfAKoMZvZH2mVS27EXv9gE=,tag:kgMBdcHZqmQfPeHMKxH31A==,type:int]
          targetPort: ENC[AES256_GCM,data:G3ghLQ==,iv:UTncN++YT6JbeoClF/IXkzh7h0VAx0dx3Et2hrlKlyk=,tag:QxT0y5KUPSXpQ0zlAQ+C2g==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSDlEZVZsL2ZLaXM4OVZa
            S1R0eTA5L0JFZ1R5YWUyYjhoaThReWFReFFzCm42c3dUUGU2bm0reTZxZnNmZWNr
            cTBZOUxFbzJnK3Y1ZWQ5cytkQzhCRjgKLS0tIGRITGhRQUZJU2VOOWpUUlZtekxn
            dmEzOUIwVmtsSkhkQUZFNTBkU0M4c2MKQADa/+qT3+NyZcRJUVm4rsubiIpXMJq8
            evSL05nlJ/8q8dQRRS4UD1lKVdBF4Xh8qfbhci1xnV1jf1/hD1/OQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:JpA/SokRs0WJpOrfwD1v6YDp6Q6vXnd6r1QQhu1faVUHo55k/M99AMKNodvr1c903o5IOvbW+4yMsBTUpCr4QiRE+jGiNqqroc6Ba23rV4ry4lU2dXUPwNuTk+CRhAedYA/qJ9vHYLZ9gHarwbSVkcMlXn6ekRdHyZ1GWf3JNhs=,iv:dKD/kyJshcsGxitB2qhJxRtJmyLk1Nm7VxN/mVEkkXw=,tag:tVCYGQVu4+z6bkIuPWr3Eg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
