apiVersion: ENC[AES256_GCM,data:2dc=,iv:C7aOUoASaUk8bB5me8cHUl/S2wREZU1dLiEmHLvdlCU=,tag:w54/mZP7r7yGH9xNQvYHzQ==,type:str]
kind: ENC[AES256_GCM,data:2WGT2L22Hun/LguZnOpv1+9/GBU5,iv:VYkaSnuIUs0lKypuvKgX7oTxwWX23WDD0bgs10pUJbQ=,tag:ZPjTuhrt/rXoPP4yvg11oQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8yxPQUQ/+uALNx7Psw==,iv:FOZU/t1qVz6gpSSAG/wlN2Ntutt8XcuIlQolZAuCTX8=,tag:GhDRvYXj3x7Kx/MY0BkUoQ==,type:str]
    namespace: ENC[AES256_GCM,data:nmhmwdo=,iv:Q3HcbTceiL+Bwc0WxGDTqDisqSgPljMUxrEN0z7i+gM=,tag:Z7CT+dvjRJA3b11Kcm0HZw==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:C7yYIgRHr8PAmYn4Dg==,iv:RbOkmNLYcA7cb2SpByZ6Tf18mVsKMXeq7Rb12z5wCu8=,tag:9sU/DZNaEbtzEYmY6lim/g==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:Jh+y,iv:45QVCYwfPrgj9mPExr6u6XTlK9fqpy6vxS/QTm9Y1z4=,tag:jAKG5e384mOlOSbGOboNRw==,type:str]
    storageClassName: ENC[AES256_GCM,data:+hOXmA7IJG0=,iv:CfwYio0yPPpkOJ6RzvVj6nI5oqkoFBuNXW35AuvU9d8=,tag:oot/byKb2C2uo0yHlDZnvQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b3M2TkFKVnk4Ymd2YVpY
            NHR3a1IxcitldWlyMlNZUWw0bFoyd3hlY1dFCkVTSG5MbFZ3SUpSOE5NU1M2Tm4y
            ekxxRWpFaEFSVjV6Wk5sNzdWSmJiVEUKLS0tIHM1cngxSFBpU3lxRE96dWNQdkZE
            ZUhjRW5XRXpFVndEWlh6WWd5clV4eVkKrAekf6Ym9K2oSLdwiX0tZDKftKQr1Ix5
            UCew7oSmAaF8Trm/uzlqdxiegCTryLF8lQFEUHtzGNxrhmMa9lDeVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:+3aSyV8vRytBY7rGn5n1trMqfIPu6TERGMV1E43l+fEKJAv+xXgAKjwof1F4jdrqJ9vfQVLcj84KMlPLRMy1zrJdwWW/taqIw/BMmvXKXXpMggdmV/bglsH5D+65wUKU8a5V5GT+c+1wytLW7z6/mQGLjY8QIg2boxmVlF7ULBw=,iv:Y5PbF+hwfrRJ+4P+0oye+tgiUdS7HcvCRd2PQXdNec8=,tag:ZoZJsJwBBWaF5ORn7LqsOQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:l7+oyhJkbA==,iv:WpUFpQqzV1Hxw1UF1nipSKVbhab/rWEJx6x4MVqgO9Y=,tag:Dz2nTEIeXDHkOB6t/yq86A==,type:str]
kind: ENC[AES256_GCM,data:h0x27MfHfVdlFQ==,iv:A7yiZ5SJ1FRn7/vX7CNKuYcO2+JRJYrwR93ZUndfTuM=,tag:wLfgDseFvp1cmba34nbM3g==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:dSIRGaKd,iv:Aa1Hh/UGC3AqGqhQNIWhBv4aJRHh0WrGujNDvMDKzVc=,tag:JmWhMiRwe7Fgh2W78xsWUA==,type:str]
    name: ENC[AES256_GCM,data:n6Ih9tb5,iv:Y+dwKyi3TeWkEbOzEIFgskTJ5Pz6EHL8N8hsA3A4yKU=,tag:Z0pF0NZ1BIC8foFVaG8s6Q==,type:str]
    namespace: ENC[AES256_GCM,data:HaLcntk=,iv:LxC5lLpIyiZviRDZGlAeQ+5BflovOSu7iztUdZ+UbIk=,tag:DUL4YCLmmE4qjGBc/EwF+w==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:FA==,iv:BNEQiP55kdR5jMC4ARECeSqzA3AEFUpGoqSgiqMLeHA=,tag:aLLw3EDIvdC5yd00gxz+Fg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:hBNJvAer,iv:+1bacZiNXODrbdqcFz2wf+kOwnURl1BDG3yY6482viE=,tag:nk1sK8GJM/44tEf0uahqlQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:Y257JT/J,iv:Q51y97w/A7d+sW7oUeCe/q27h1905LnizOFWCzZhpo4=,tag:v5tlhu1BaefM3MEbOrgI2w==,type:str]
        spec:
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:l6PkhA==,iv:ELkQyH/VcOIc3VCBkG6R/FtT0YmednWt6aHWaHPKTM4=,tag:klD4V4ix/dC/UN8Puwli3w==,type:str]
                      value: ENC[AES256_GCM,data:VpjzhQ==,iv:XQa1TezhTpKG46xZnL+BGO0MmWBGtPmMTNMwpGX/rsc=,tag:FCkcqhMnc5LiE6SdndQEiw==,type:str]
                    - name: ENC[AES256_GCM,data:Xzv78A==,iv:ieUToCcbqCl90YSDbG8Yu99khd82Yq8WnsPV2soggds=,tag:fXc9KcXK/qNzNhqIrAIdzg==,type:str]
                      value: ENC[AES256_GCM,data:6IoE,iv:k3vJUGbY00qpehFqmwsh13F3T6laJRSZ2/PaG39ZetQ=,tag:Flym/S6tNaB9w1thlkhZgA==,type:str]
                    - name: ENC[AES256_GCM,data:30I=,iv:45uoCgrAEUwQwBl2Bxo/RILeG/SwNboOMxZ5rQV1bH0=,tag:/2PmkVGv5O9pt9a3lFPtSQ==,type:str]
                      value: ENC[AES256_GCM,data:11Bt0CsGXe6KJ79BcOxHQQ==,iv:kBJD5XyDpKHFuQt4PKM60+zPXXk8E9VO7rB9J5IdTng=,tag:tE4a+f9+I26smiy1MirirA==,type:str]
                  image: ENC[AES256_GCM,data:EAJsOjrJABQ1HemEaheAB9MBGpyCIOegcZD5PgY9PxCRjQSlg8hccYKngIQ=,iv:hOYjJ6o5F6Rh3hnurdW9b3mYUrIKSmNEwN3Ne4pZnkQ=,tag:oUIwof1QGka6xcow8HV2Jw==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:XQ==,iv:PneRycN7epOUr//JNSeEd2C8TtWWvS5g+PQGzdLhQRs=,tag:wYtxhP9/6giTXmhPSsZt7w==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:pSjsfN8=,iv:2GawsuaJ82TrGiAwoy2WFbAzfpsBYduSBiST08L2meQ=,tag:m+mL0dcNHyFZp9RwFSb86w==,type:str]
                        port: ENC[AES256_GCM,data:YSHWGg==,iv:c0ZXI6IaY23guV21L1Bba687yaBQp9Qz4gsUcyALu+w=,tag:EszQkECJjSGDyzwtIUN/ug==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:otM=,iv:3EZcCtzN5fv/Kx6/mSCaqzFEyYKjMWuu4XiEcHB+V/A=,tag:B2UgbC0yxQNRCh7LfmGbEw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Ilo=,iv:4pDcHKqETfjI3Y+oW3hw+KhrSgA/BWMyv748R39hYoo=,tag:k/XUtAL/srLHR7MHjs6EMQ==,type:int]
                  name: ENC[AES256_GCM,data:Mfcx9Vrh,iv:gLsEvn+CVwi8cLWcrse9oqDhQoXuddzT27znT7SI+9Q=,tag:bIgM5sxD+5rQsDA6JpcGfA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:ACWl1Q==,iv:2W48t+fBNRtMsbLunftEkjitcIPJUmjgCB0s9WMgPqA=,tag:eNR4KUBOrAvrrL2RKKsang==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:+Q==,iv:5U5rqC/7jV0cRzQPQ5qcbVB7MUUrFLvrIFhyH1ROfao=,tag:ISZc8bt8xN0JSycjW6GRcA==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:OLYxiGs=,iv:632UdJrn6+RTl53o10b5J7WBOVw+9HP7jkOsIcGZri4=,tag:XFyE2Q7ZlaFCvhQkTt3nNQ==,type:str]
                        port: ENC[AES256_GCM,data:dG0a7Q==,iv:aUbo31l0qPvQNYL/9vB10ZA3Z1G/eMeKackjUDQWRdE=,tag:A9SnlfN8WYrEFa0iIzsQ1w==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:yxo=,iv:hUoTi7v/pliYRFdX7qxWAZ8KYbnh7itG1wt/K6NTcKQ=,tag:wt1J/Cb64CGjtaejRl4F2w==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:KOA=,iv:W9jYM689PJjJQMbawi0HvlwCQJO519n7a6n0iJZ5yIw=,tag:XGNp/GC+6GEwbOPCFOoNjA==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:PA==,iv:P9OhI7z+w8KZ1WI0qtyN4gr5nhT7tzVGbd2206DewSA=,tag:JArtZsU4YE90G12hfRt/+g==,type:str]
                        memory: ENC[AES256_GCM,data:5DTc,iv:oesGCPClpLvHpfoGyk1YQ4SO6PKfR8VP2HDkfdwV+L4=,tag:/08Vj3QlF+y1njpdFPvFDg==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:SyeUjQ==,iv:5jbkgIQg2RuQgusQPKvYfnUP65yZQfMRFu8X1jxzvRM=,tag:HTE2dIeJTN7Vra9wpQ0z5w==,type:str]
                        memory: ENC[AES256_GCM,data:WFTZX2M=,iv:0T22lDE8TI+mZpRD4tRCAn4iSfvmuLscp36RlDfCkyU=,tag:FF/osFEr5KWmXZJfd/y3aQ==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:s72gAaLZjQ==,iv:kUX+PmW84ZJXcqFbOyMUl5vTjLgOam7cyas/B798aek=,tag:wHnEWMWJ4ugY2R3x+9z8WQ==,type:str]
                      name: ENC[AES256_GCM,data:r1/xWKD9,iv:aqlPvE3wmw4sxfAosy8wSIOVZs/W2EhStVe2zWTMqIA=,tag:eKZpjRG3urT3Mylrrn0gJQ==,type:str]
                    - mountPath: ENC[AES256_GCM,data:MkOhx+y1IA==,iv:Q8uaZhtnTyl6Ho8V8+AMEuYnhecyoHi+xFqt+VOdjWE=,tag:OXWqPkagEv6fKwgJl/lf2w==,type:str]
                      name: ENC[AES256_GCM,data:4cdWuF8=,iv:b74aiH5S3Rs/0FaK+JburKCF6t8zjxjrabLCc0NZa0U=,tag:vDrtR2T1eMG6XVgGGiIluw==,type:str]
                      subPath: ENC[AES256_GCM,data:SvYMf4K2,iv:DySmRfZU8IajEsJkzPUAA0q32gQ8XP07le8wuZGJDIU=,tag:kMqU2Nzr1OQBjuXHVWt97w==,type:str]
                    - mountPath: ENC[AES256_GCM,data:2Gciqll9kokj0ssESgk=,iv:f6egUmUgt48OlqRwv3blVwHJNjbfkKoBsD979YWoaeE=,tag:ujIfpLqQ4Sew0QR2Hfop3Q==,type:str]
                      name: ENC[AES256_GCM,data:wQkO4kM=,iv:gaQi6KKkYM9cpY860e2aUANjhII1dsfUuX7WxUvAfdE=,tag:oU5z8FvxBOOY/nCj2D4sNw==,type:str]
                      subPath: ENC[AES256_GCM,data:fZ2unf4z+a3MAbaHTjfEUrMXneVGzw==,iv:cNAML2LLSlCzauKEv0v9NMCM6SGZ04+kPjYIJx/OLdU=,tag:gP8aY+hxCxZenXzpAXJfIg==,type:str]
                    - mountPath: ENC[AES256_GCM,data:NviTnroNmNlK/w==,iv:UPrB99hmuNyp/rJyxdC/7st8W4C4+iJafr4yfI+SrnA=,tag:j9w6UcLtcF93Ltgobebp8Q==,type:str]
                      name: ENC[AES256_GCM,data:8q8zACjZLRpH,iv:wAUVd4MoJo+XyWRYm7koLnKK9zGjAXEuhTErifi5P0U=,tag:O1blbhO8k2AKm/xwvUJu5w==,type:str]
                      subPath: ENC[AES256_GCM,data:kfmEPyyd+okWcr8=,iv:QmqY6eGd3AO/QsQfzjdJ9xUp1HJbwHWjzlbHLTwCJSA=,tag:yhWNTcXkV0vBaVbA9hSjZA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:Ex6j3LE/8Q7N,iv:brABuK9tUATkrqHWxItgsoWz+/R1WlqvCno/UJw9g3U=,tag:/QM7NF2TySvZiDCpdiLmww==,type:str]
                      name: ENC[AES256_GCM,data:g5vY5HSzI+AU,iv:dKx3X0qonoRnaNIfbI/l3dzcADpG9Ql7VEe3VEKLkNs=,tag:lbokaDsR6u6Mbb2YrfjRDA==,type:str]
                      subPath: ENC[AES256_GCM,data:nZ6NLwS0WPs=,iv:d2GWCjQIFA6iw9M/yEv1lPFJl2N1I0/GMfraRAtrI7w=,tag:Lm9fPHRw5tNfB8vCm5X6Hw==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:ieuDgBQ=,iv:u8f0LYcphDJIVzv6eRpMVIodw2dutyMqITrdjFTTFIo=,tag:y+UQ2AM5tSeEerPjWlEQJg==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:rjPcFZdm,iv:dTrHTFVGUjOBCjlS9TTpT0UxIRYqlXshN/++M0uYC54=,tag:p1Q1FL2Yhm57+IZj0YAoQQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:JVvjZSRa1J8YcRAG5Q==,iv:C1Djjly/BZdN5dUPBC1ZHL7GNdACe72zkAlZfHonV9o=,tag:AbbQ5ueq1nVBiBmHZu6/6A==,type:str]
                - name: ENC[AES256_GCM,data:5pL0xuM=,iv:V61dHzLChjCA/AbMe3KyrRAD1OMqRk08UxHec4uJP30=,tag:2ePk4knAS4kkoZEkktBnwA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:LJgVUXC0JTx4SQUTdcc4rA==,iv:uOKURyd9V6wbSqokwnDQza9BmDDSEa/1Mi3mA0pGkUA=,tag:DLEOy1foKHcboKOyxugE0Q==,type:str]
                - name: ENC[AES256_GCM,data:9SY5OM7LvAFk,iv:Vegfxe3VC1eIE9fBuEf92HxVL4zYPSFv9IL4Os/QeHo=,tag:Wr28iUTbXJ/0/VFlQHrJqw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:z1ujjGxCD+Xo+q/1zcNEzHQmmNg=,iv:JAxVUykvkuVJHnrv/0x+FhcHo+47nDH5reyAvA88icA=,tag:dVWxENGnbQuA8AqFaVb13A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b3M2TkFKVnk4Ymd2YVpY
            NHR3a1IxcitldWlyMlNZUWw0bFoyd3hlY1dFCkVTSG5MbFZ3SUpSOE5NU1M2Tm4y
            ekxxRWpFaEFSVjV6Wk5sNzdWSmJiVEUKLS0tIHM1cngxSFBpU3lxRE96dWNQdkZE
            ZUhjRW5XRXpFVndEWlh6WWd5clV4eVkKrAekf6Ym9K2oSLdwiX0tZDKftKQr1Ix5
            UCew7oSmAaF8Trm/uzlqdxiegCTryLF8lQFEUHtzGNxrhmMa9lDeVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:+3aSyV8vRytBY7rGn5n1trMqfIPu6TERGMV1E43l+fEKJAv+xXgAKjwof1F4jdrqJ9vfQVLcj84KMlPLRMy1zrJdwWW/taqIw/BMmvXKXXpMggdmV/bglsH5D+65wUKU8a5V5GT+c+1wytLW7z6/mQGLjY8QIg2boxmVlF7ULBw=,iv:Y5PbF+hwfrRJ+4P+0oye+tgiUdS7HcvCRd2PQXdNec8=,tag:ZoZJsJwBBWaF5ORn7LqsOQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:whY=,iv:QaGbgqrbP+X18yh5fOPizxxqaIfz/2gR1O2oL2wX2JY=,tag:/LimJz0G1NTXcFVc3MCing==,type:str]
kind: ENC[AES256_GCM,data:LTkEcme7WQ==,iv:qi0TzvZrDrBthg9uH87HQmvQkAA7v6NWevZUZyTVhAA=,tag:+iGofRQOFYpmIYc/k0Yv7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XVFFxxxi,iv:kZp0E4iwcM16xOB/giu+3fxBdvKNLJ869N3MGNcAtqw=,tag:ZP69AcDQa8RihFsozAKIDw==,type:str]
    namespace: ENC[AES256_GCM,data:o8OGFQY=,iv:AeJta0AxcJ+TGbkru3hwAOg4j1Bg2AqywJuK0yIfzsg=,tag:IpkKnA6TGXNd4/TSqVhycg==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:tTfVAQ==,iv:L6On7ITwkRKsRZ/avVXnGHWS8y9mRbuQ4VnbefBsBcE=,tag:m440ZQn3fXYPJxq8VYw28Q==,type:str]
          port: ENC[AES256_GCM,data:IykwLA==,iv:dYesPENDs0cL68DOmaLHkeFXCqlqHtF0G8AQe9bpc+Q=,tag:X/csXUiNwZXHjBsW/C/1JA==,type:int]
          targetPort: ENC[AES256_GCM,data:vmar5w==,iv:VgejQbBz9Og2zRUHVbbxEIbIIRXhtY0E8BApuGJWOB0=,tag:6jS8HQOOHc9d2g2mfBICCQ==,type:int]
    selector:
        app: ENC[AES256_GCM,data:JAx+DNR1,iv:CxEXN3sxjY8VYuWjQzamu5bVVakvsXS5sN3mOm8hJhg=,tag:C2H+kQH0OkHZCovhAkBP2Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4b3M2TkFKVnk4Ymd2YVpY
            NHR3a1IxcitldWlyMlNZUWw0bFoyd3hlY1dFCkVTSG5MbFZ3SUpSOE5NU1M2Tm4y
            ekxxRWpFaEFSVjV6Wk5sNzdWSmJiVEUKLS0tIHM1cngxSFBpU3lxRE96dWNQdkZE
            ZUhjRW5XRXpFVndEWlh6WWd5clV4eVkKrAekf6Ym9K2oSLdwiX0tZDKftKQr1Ix5
            UCew7oSmAaF8Trm/uzlqdxiegCTryLF8lQFEUHtzGNxrhmMa9lDeVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:+3aSyV8vRytBY7rGn5n1trMqfIPu6TERGMV1E43l+fEKJAv+xXgAKjwof1F4jdrqJ9vfQVLcj84KMlPLRMy1zrJdwWW/taqIw/BMmvXKXXpMggdmV/bglsH5D+65wUKU8a5V5GT+c+1wytLW7z6/mQGLjY8QIg2boxmVlF7ULBw=,iv:Y5PbF+hwfrRJ+4P+0oye+tgiUdS7HcvCRd2PQXdNec8=,tag:ZoZJsJwBBWaF5ORn7LqsOQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
