apiVersion: ENC[AES256_GCM,data:uyo=,iv:8PI7aKxKagSXQyMmndC7sdYXg5MrD0wIwyzt5QxHoCM=,tag:uP8sFmO7aYsoTszoROVpEw==,type:str]
kind: ENC[AES256_GCM,data:fkgh0SgBjb7/Li9v1sgklBFip771,iv:7RAYy3VHoo2wlicbX2HiOsnlXdPd1n+B4JAOxqd0tOs=,tag:0VfymNekuKbKwzBFCAYKQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZoKe97XBMsmHaArmNQ==,iv:lPlLDxEHQtYmvbmCp3N+T4p3Fb7bHBDdB4TbUwQnoqA=,tag:vb/MqCZQbTJ/XMWPaPD+0Q==,type:str]
    namespace: ENC[AES256_GCM,data:vc9iGK4=,iv:qNG2h7adlUTA2xYj0fx1JSVLRGDWQQ5JSd2Vt/NmUZY=,tag:jkBCYGSCowN6FGQIq1fd4g==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:+wIdDdncBtt3vqrzNw==,iv:mZZypT7wWdEDszfnBeEmZmdTk+WQQEA9GtuTb9PzG5Y=,tag:mQZGuMdH+cfA6JC/ehCAug==,type:str]
    storageClassName: ENC[AES256_GCM,data:T/dvWL4c/RQ=,iv:4P719x+ZUIKGe0jYw0P345veqS2YD3vf7Jto9Am5ko0=,tag:O838WeP51nPrbHFd+u9kCQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:Mun8,iv:KNPLBWOywKjDZXaQ2R5+Xf6Y+imUK4RgWqMuyDGCWyk=,tag:H82OZMwAbgNkU9pV2nhVeg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdHoyR1MxRFJMY0FtajZJ
            OVhXRXRSRVhlMXpvQU9sc2M5eFNKbTNkVmhVCldhUjF4YnBsaDBxK0kybXl0K3l0
            TkM5cjNEM3N5cWVOdjBrOTR0L3NYbE0KLS0tIDArWnYxU3o2RlJEdXIxYlJCRmMz
            MW51b0t6Tlc4UzhBVHZrcmFlSHFyL3MKXvUJw9+jcs3eLxZ/ej/7V1JmLun+8aMB
            7o8ZkETm2riqtK2AhItgOvK/mdwUB2cQiEYyjxWHH7vTNDOr7SJboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:aJ80dlbgaRR4QHQfn4BcPJA4Lp3tu3Gzl6vgJ8pQ4uKNP1bCdkHU1T31V3AvPjQNeXiOD8zu+KQbnXmknRR7hrkIdMtPKoh0LwspJ+KvWn587xj2k0nXV9GKNdypcMOT5zWIXgPMyMmBjiLIq57pOXe9ElZl0m4olFU9mhEie+0=,iv:8LiraXEhwtngbNFt8rscp1LTxrfa1rq2cEUC2xpc8Ow=,tag:PuAZiYFsQHoSLbe7H0Y0XA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:+A6FiKjgpg==,iv:ZDIEmEfHYtCzdSUseLpFrBX/ShdnNtDzFlFSVAgHGMI=,tag:0i7MOh4CihdZXZxn5PCD3A==,type:str]
kind: ENC[AES256_GCM,data:NuMoyuu9OkRDpQ==,iv:NgRKmI/pDxkJ4/AlqkYvjCk1zfSk6KL9FJrKd/kKKDo=,tag:NivAJFUy6NKq+I04kxDEDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cOzf8Lr7,iv:A7vt6Ii5qxixdFy200N2FmNRpYhq80JiY1uiH7AA0eA=,tag:1n7dx8TR5LctTvYpnMCQXw==,type:str]
    namespace: ENC[AES256_GCM,data:fGob0ww=,iv:auqNmHjM14goU4O4EQuQC2i5Y9PsNmzgXzqjxk9LGb0=,tag:6yRTzdvAQJ6dr3lVeDzzwA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:krXKoDfA,iv:BKPy4PNUpvHUm1dnEOL/+zufINAs1fDre43wmTaDFns=,tag:V+gocSSm8LDnwxroGz8LfA==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:DQ==,iv:m2Rgyn6r+8hm2HuMqLVwlqQ2nq1pV27wE/wDQ2v5UD8=,tag:mIIxlXfpsde7YVdBh4/lOA==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:UA3F7hKF,iv:0XIau4V1WNPEVH6hUIMKZiVN6UwcayWaNfIrDaROvEE=,tag:a1kaGiBGRg3iQtwbDsVgKQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:9HpCWUZe,iv:53z2bN+gXtfZHJP2Tll9dd8uQd9gvQNUIGb7MZpks/s=,tag:LZPj6f852xeyuteKsHzRAw==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:PfvJc3E=,iv:xwFOeQTfl2wi0dcoYuszHYV+PcS8e/ZUszs9z6Ro7Fc=,tag:gK+8aUbwG+/wtC/f338dzQ==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:VoLwfalX,iv:2As0xMUKe6gc70ZuAMNxWULrNtBkjl7vYVVW9fyJhXs=,tag:hKyssy3nFrFM49uCprNzLA==,type:str]
                  image: ENC[AES256_GCM,data:GbXUbtF6itRuA5hyJfOEx4U22VjsDX2ZSE3mxkfcESk9iuAR6kAnbUNtNb8=,iv:vHjOoh3Z4igCglpjjs0u5+5bKOgdETPTcv0JaYuMbo8=,tag:edbeENjiClN9Szj6W4EeOw==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:OV/9vw==,iv:4OYJCpU/BALIPFWwWOE/7llBLt83AsasAcSzYUZOBXA=,tag:6urNRP1U7rYXC6V2/t5siQ==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:2zevlQ==,iv:3aVYaoYFFXYK/UNzu/ZT4TkFFrY1GBI6RBLnZhxCxcY=,tag:cBokyLMqcX8KMSWRRTLw7A==,type:str]
                      value: ENC[AES256_GCM,data:X5ZIOQ==,iv:1Hpwum8EHbssqM8L2+LSyRaG9ZzcaujkAysgvKyRYL4=,tag:yX3Y3xn7P4yYIZ8o6Fwbhw==,type:str]
                    - name: ENC[AES256_GCM,data:I/uGWg==,iv:m5Gkl9zo4jV+Nx+cdvb0pH1yCUpjC4e7ZrFseQgAMGE=,tag:izY/ViP3pVDI/1MUhceyoQ==,type:str]
                      value: ENC[AES256_GCM,data:Nwwz,iv:9to4dZjKiy0/SvF2qGb+3yuF1v1niOAc7l0IjsAFaKQ=,tag:/dt02SxOyKCTYyi04BDQAg==,type:str]
                    - name: ENC[AES256_GCM,data:8wA=,iv:vMt8hwZ9HNwoxCaKnxi4ekqsHqQXAziRgsljWPSYxfA=,tag:qV2hR10aE0cp/SD8poxS7w==,type:str]
                      value: ENC[AES256_GCM,data:knw46H0YZgQ5ct/PN9D0Jg==,iv:n4HmUVNKgoejYeDLyV8C+qHrPji9CjI1pMuz4rDs8Mc=,tag:g3NCziZr2XIA9NeWAv1GUA==,type:str]
                    - name: ENC[AES256_GCM,data:BaCzkXPNyuupew==,iv:vysVTcAJx9RQNoZ/Zsv5VH3U+6bII6qJ02xuKv1rozA=,tag:4R6kJGksp8r8Rw2NRvnZIQ==,type:str]
                      value: ENC[AES256_GCM,data:0grHcg6+px+AR3HD/MK4vJAi/4ES,iv:8Zt+oyBnxYjsgBJMfaVFuYQhRJKaHp4cWFrlOM+Rtc8=,tag:x84omOY0kEDlGvl0gW376w==,type:str]
                    - name: ENC[AES256_GCM,data:KvbnppFeLbq4zEM=,iv:t3QW+o06t8dbKfZf1i6r7DZGNap14DBWC6uWN0JNp9U=,tag:me5hQPYT0S+g7xZb6Vpqng==,type:str]
                      value: ENC[AES256_GCM,data:8BrojG9d+FJc1yr+ne3R1YWkI344,iv:i25hJHegQdsIWW20NeAAawCNT0Qs8V7e976J4xcKCuQ=,tag:hY931cALiGnQMQlVjm1XHA==,type:str]
                    - name: ENC[AES256_GCM,data:S2WGcNsF31c=,iv:5/ukzqkClZGOEKpt4D3xxVGpAGhidl+ywWr0S8XbWms=,tag:0pA7eaHBzv0gK2xFVXM9HQ==,type:str]
                      value: ENC[AES256_GCM,data:gR5WcEgB3rrBWwYEjGS4uybyNpoyP8VCHS6aulGJWwE3trmDNJlKaCWATZEU6coLwGZFxKE1b5sFwJR9ZACduQcGiux09tooT2NIDxgwMYmUGdHwxX6KRjZI38ASVdmCeUBP,iv:ADLeybdw6Iy43ON5lNVS09hNWAdzp9MuSD9eqUMrBzM=,tag:8lq7EgdDhpJBep0VPAJTFQ==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:/0/oGRUF,iv:MmspVQpcc53l0U9RwuyCMYn5zcypn/5CUp2ClljSUNo=,tag:+aCNLdKSPeMI3mfWKzFBLg==,type:str]
                      mountPath: ENC[AES256_GCM,data:CNpMLPYJ1A==,iv:klU5p/4O42xk/NSuKvuUKmNcZFTmxO70tDwg0GSDtUc=,tag:aewhe+4OWMURRWoNtq1dgA==,type:str]
                    - name: ENC[AES256_GCM,data:2+YM6ns=,iv:YNwK77t2D+69LXsEgoYji6zkxU+oHv/EeV1hykGK4aI=,tag:YVlT64DjaRzTsHlIxbGvpg==,type:str]
                      mountPath: ENC[AES256_GCM,data:wrcn,iv:X6K9l1ZzlWnttInCzzmWwKHpo54KvREGm21PsgqIXh8=,tag:UXJOD1QTGo98p3i77icr/g==,type:str]
                      subPath: ENC[AES256_GCM,data:uW+p51IoN7A=,iv:pCrg7ao+S8F48Zsg2Jpn5tJE4InPoojys8zGYPBJHXM=,tag:ZCmy8NP/s+lm6LLg12kblA==,type:str]
                    - name: ENC[AES256_GCM,data:A3R3kqQ=,iv:EWKN2U0AD104Y5+8sGo0kElJ5Y8C6sGVvsrLhkQXiCo=,tag:51RwAd7fuMDGEmI5ftTqsA==,type:str]
                      mountPath: ENC[AES256_GCM,data:vwycU7+yk/LmTYXlzpo=,iv:41WeZpBxLtmQUvj5V6mME+/ndJCy4momeWSVKmPLU4I=,tag:sNiuZYMnM8D7QrpFfTuaEQ==,type:str]
                      subPath: ENC[AES256_GCM,data:EsunAx+8MmJTwvWq4qk9+FT0FBw6YQ==,iv:UTig7f25bjNk7LKQpo4RPdEYr8A4lI/D7qo9tE5PvMo=,tag:IZXyY8PW8CdMzEnDC+lqvA==,type:str]
                    - name: ENC[AES256_GCM,data:MmboAhZoVlH1,iv:ptTaN9Xhgmy+ilaw4Q6H8B90Mg2oL+f7IapG04ZxHyo=,tag:ZbwUXp/33Wlsp6HQq2dKBw==,type:str]
                      mountPath: ENC[AES256_GCM,data:RxU2D9fgSNJ4jg==,iv:B5Bm/aL+Yn/dI2ro0lkgXX0LmNJn9RHwQ+6vqSVTWDQ=,tag:u+h5NOyqgJ1lTQUiEDKI8g==,type:str]
                      subPath: ENC[AES256_GCM,data:Gpqd/dSouDwKDa4=,iv:b1vFigO0/K6wXmsChM6QQq4eP5KVC2PsmKhaFdLdKr0=,tag:3k9PcecWqKtmoqEI09GPrg==,type:str]
                    - name: ENC[AES256_GCM,data:XRwoYEHamAq6,iv:pEoIaATrty5hl1bEvId5hE5GFrnuyQvMJOXfd+UpiJg=,tag:txJnwZcfu/KFykwDh7padw==,type:str]
                      mountPath: ENC[AES256_GCM,data:YDTDsDlvEzNu,iv:q6LYGjfCUIDf6bk9vCyTnwe4F0F/HoblDhE0Me5/Rck=,tag:D4kj3HJG9YtPjliSZSURsg==,type:str]
                      subPath: ENC[AES256_GCM,data:q4wyzu8WxWw=,iv:VY4o7MKTnnNgW7yoJcpFzyMVsc0DIRKwhZOLWLR2BlM=,tag:f7bgI2xxnOo92NyFOwKqBA==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:jM3Ydg==,iv:lIX0cnYEaWv8PZ3VMMizubCe8RB4oGtr04E2EaOR7h8=,tag:Psw6f+D87G+tDnyif3jYsw==,type:str]
                        memory: ENC[AES256_GCM,data:6Fbd79I=,iv:ejFgVtpwdOYYVtQbZnv2Z74ZqkQwAl0iqluzvIY5c9E=,tag:TYG5JQtCpDIh3DROV62SwA==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:ZQ==,iv:knR2k/3nX2Sg/CH1j0PrRWkXjVZZWKHkiZRXAhbLdHo=,tag:E5ZpaklSzT1y73OGr2f2Kw==,type:str]
                        memory: ENC[AES256_GCM,data:XnYb,iv:RyAIj8LTDatQVFR7OSI2CFofutqRrKTvJ4cXWV+C9r4=,tag:btvu0mC4x2CM8U8B7IbLMA==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:ZaNPhew=,iv:hbsIpRObdnHGI7wUWChL6VeV1gK5phBr/UixL0I5lKo=,tag:FH6VR9lT6bc58JLE2gM0jw==,type:str]
                        port: ENC[AES256_GCM,data:RnLmoQ==,iv:4BZIm+vDeYUxOsZHK5PrK3BYEHwmcUph46tnAxmK2Hw=,tag:y39pugysZRgQ5YxgJ+pnLA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:i2M=,iv:CJHgix2vS7XxvP/J7ElFXt6p4jSBTVudaeGUMFeLgSY=,tag:CwtV+ioq02EKRhPAZ9qHjQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Quw=,iv:uoBC4D1Gj+90vrvhXLH5JY9z03GZXZ45mdGwiPx0GyE=,tag:ieOvn7WnTi6bCF+LrpLV1A==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:sw==,iv:Zp4VPqclZDbEfOnFMuxz72ICHwb+uJ4zROldiv9jhc0=,tag:kdBC5fdFELIJcGvazNXN7Q==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:9PX2YsA=,iv:509rW6TPnPft/bKUwMcx3lruSOpBBfsT7UTJOlZ7AgM=,tag:BAUUPZvnfgSDHmEg3EsUCA==,type:str]
                        port: ENC[AES256_GCM,data:4/gaPA==,iv:TQ37QLvm5EYwK/XRaCcPXUfyprCdKOUCPPVdrOts0Ws=,tag:lDHrAALowbQb7NeuJD2mtA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:ERU=,iv:ZlwBl7M2ONs0DKiPDtNKY+7ila3Kw2STea73iFcQPlw=,tag:n6E/xvxRVzMHRZP1uVOS7g==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:29o=,iv:lMrZLPShypWhiwp6qmi8kWogzwrdl0zKyOO2nxdISyw=,tag:67tWOBC7hucO3yZh2w+AaA==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:Yw==,iv:5TauGRIKEa+qjcLftomAyZwxVHXhtxTA2GtvWcywq7E=,tag:IJIcdV3PAeu7GwjqL42JIQ==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:OvFSzX54,iv:0/kD6rNoCgln5wrN4PAkelk/aL01BgmAcQVMl60FGf0=,tag:MxS9SsrLR1190TmJxIw4tA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:HzKPFkfMpeTzkD+qzQ==,iv:GB2UNuehsIzrbGJyA1c5Nt8CHHzXJLFcwXHNAtKU/+c=,tag:DrbGVy3EJsCKuNQ9C3PMxw==,type:str]
                - name: ENC[AES256_GCM,data:5EyuCgY=,iv:qBghifNAnxhCTAVoX+u4KA8N53WveyFntk+SGbSMo98=,tag:FZVyvoJucXw62zxBubUQYw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:5Ltve+FktrMsaL0Nb5JsSg==,iv:Lr6rZM9cNjif7vW9eUoyHbFkrLgGQKeIztJ3TyKQGq0=,tag:09f5dgPBV6OF/SgrNg9G3A==,type:str]
                - name: ENC[AES256_GCM,data:H0epYGzoYz+Q,iv:dCzYqQIvbmMEx9SIlr172KRkC0+Gn/Ht/ckPgBGgIkU=,tag:tWDkVpI8QkOvc7V3BPMjGA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:ZHbVfs0qAYOf4cHskPcHbRQJ2so=,iv:ER/BdF1d1A5gmnawmOvMGedUXOxGrM4jriCUjSf0x7c=,tag:Te1jipwFI13LZMazF8HKzw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdHoyR1MxRFJMY0FtajZJ
            OVhXRXRSRVhlMXpvQU9sc2M5eFNKbTNkVmhVCldhUjF4YnBsaDBxK0kybXl0K3l0
            TkM5cjNEM3N5cWVOdjBrOTR0L3NYbE0KLS0tIDArWnYxU3o2RlJEdXIxYlJCRmMz
            MW51b0t6Tlc4UzhBVHZrcmFlSHFyL3MKXvUJw9+jcs3eLxZ/ej/7V1JmLun+8aMB
            7o8ZkETm2riqtK2AhItgOvK/mdwUB2cQiEYyjxWHH7vTNDOr7SJboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:aJ80dlbgaRR4QHQfn4BcPJA4Lp3tu3Gzl6vgJ8pQ4uKNP1bCdkHU1T31V3AvPjQNeXiOD8zu+KQbnXmknRR7hrkIdMtPKoh0LwspJ+KvWn587xj2k0nXV9GKNdypcMOT5zWIXgPMyMmBjiLIq57pOXe9ElZl0m4olFU9mhEie+0=,iv:8LiraXEhwtngbNFt8rscp1LTxrfa1rq2cEUC2xpc8Ow=,tag:PuAZiYFsQHoSLbe7H0Y0XA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:wcQ=,iv:TdKhFYIcvan4ZdOZqu9/oatcJGhpuYH879OarW28ofY=,tag:htUf/LRkE70SXXOhbCYP+Q==,type:str]
kind: ENC[AES256_GCM,data:k6ib9sQG+Q==,iv:pa1HCGFcLpPMyJdfzeXkVQlEyREu8h4RZZRIGxIgWJg=,tag:o9OM1jTLS4TW/aci1OQtXg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8yrjRe3N,iv:4TgN0H6iN7OTozZfV/HrspP7IxWg2yIXIrGv2n8Wx5c=,tag:N1o7ejSeEbfMzxVfdSUYdA==,type:str]
    namespace: ENC[AES256_GCM,data:zZeLBd8=,iv:S6P/MXqTYzrZbDnlInXG6FiA44c1b965R2kbkcBL4cg=,tag:W8lUeOEI+e8n+qgqy6MVwg==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:yPDvatxQ,iv:6p+1+Gcibp5PIcxAlBkwWRyIq2ELaPhbBEo86Y1WoLQ=,tag:3REty4M1HBHlONUNvdWGFw==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:EiuM8w==,iv:TzFBR1XQbmsR/TyrwLwIxikVZ5rn3Tbsyp8l+5TmxLM=,tag:Z1CN3GdN0Hih4wl+OHx/ug==,type:str]
          port: ENC[AES256_GCM,data:jbx1TQ==,iv:M5RN4zBBXJVM/sx3mD52qpEzDqPxNWQKF2q9aIi7isI=,tag:lGDdRvdP8RJFh69vnQ00Iw==,type:int]
          targetPort: ENC[AES256_GCM,data:jqnxAA==,iv:uL3/mjk920+42DVu3TV5eAeW+vnZjUiKXylRP11qDps=,tag:9qNDQPl/KVBTBRASNbhNQA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdHoyR1MxRFJMY0FtajZJ
            OVhXRXRSRVhlMXpvQU9sc2M5eFNKbTNkVmhVCldhUjF4YnBsaDBxK0kybXl0K3l0
            TkM5cjNEM3N5cWVOdjBrOTR0L3NYbE0KLS0tIDArWnYxU3o2RlJEdXIxYlJCRmMz
            MW51b0t6Tlc4UzhBVHZrcmFlSHFyL3MKXvUJw9+jcs3eLxZ/ej/7V1JmLun+8aMB
            7o8ZkETm2riqtK2AhItgOvK/mdwUB2cQiEYyjxWHH7vTNDOr7SJboQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:aJ80dlbgaRR4QHQfn4BcPJA4Lp3tu3Gzl6vgJ8pQ4uKNP1bCdkHU1T31V3AvPjQNeXiOD8zu+KQbnXmknRR7hrkIdMtPKoh0LwspJ+KvWn587xj2k0nXV9GKNdypcMOT5zWIXgPMyMmBjiLIq57pOXe9ElZl0m4olFU9mhEie+0=,iv:8LiraXEhwtngbNFt8rscp1LTxrfa1rq2cEUC2xpc8Ow=,tag:PuAZiYFsQHoSLbe7H0Y0XA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
