apiVersion: ENC[AES256_GCM,data:O7c=,iv:dp5fnYoBIuAAl2rxw9BJot4oi8Tz1bfPnNjKH1ZUmME=,tag:2Sei+RgLRPGT8DRcrOodug==,type:str]
kind: ENC[AES256_GCM,data:emJCdF3ugkoR1CPyihhkJ72ep7dy,iv:xV8UIL0Rtxt4mDTOu2aChf3CNCBr5o7dq+cDyDkA6SY=,tag:pAOFSRMmGEFnSh120EkBog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:n9TeSzn4z7XN41qfEA==,iv:HqJ7M5bBe5BiiKSAHgnIRsVwX0yxB101CvvggC+rTRY=,tag:3h30fBNeE/VgVBy5zKxmmQ==,type:str]
    namespace: ENC[AES256_GCM,data:pVaVVwY=,iv:Bg63EYh21oFllFcGxoXZZd2dRiMRO92BgR81SncI1mY=,tag:YNV/DIRZPHqsFW2u3YYxXw==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:nDdm8Rz7o0xSqa0fqQ==,iv:3bwLL/xJpo34da3CTUzvD6RqwIyOozuv91OXnF1BIxk=,tag:eL/gfYQkCrZxpkrVAtCnIA==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:AnAB,iv:h3njGf3h0wnwyy6Jv6eOcGUCzHLNzWSLmdKA36+Ij8c=,tag:xFi6WOLTLuF/sVPqKcsh5A==,type:str]
    storageClassName: ENC[AES256_GCM,data:hUEthq94P8Y=,iv:ezupWCcdS6FjbScJ2HAIJ/I1CkVKL+P6u/mmz/X7sX8=,tag:QK8SPO/YCVzNhEfvbCfbiQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMnI2K2FmV2FZTmdaRVdY
            UU51dzJHNW9TbDNPN1Z0bVh5eStEd3VyUzIwCmdkMzVuMWU2Vkg0NjVSVmgzTTlB
            a3NSQ2orMTJnbVZXa2t0eS9mV0Nud0UKLS0tIEJCTTFhTk9BR1llWHV6NzZlaG9o
            TnduN3RsRW5LTWhoM25pUHVocStJS2MK7X0sePTXEs8TyrlrnlDxgyx489dkw6FT
            K79BBJCw6OkDo9y2TUENMTFM5Ov8VT+H+P1rgohYZOmKYn3A1Y7TQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:zLJpsZ8UKnFEUNxxHXHqFgjJsHn9TmUa2F2D0kLoYSC54R72Uo2OmaAGMZ7hoWX4TInXl8AwA5e4y8s6sOvaqqOMvpXqvk+ZXs4LwYZrNIcVdvwlqM4I9Fr9AX5nik95JpXHgrWSSopHVlKl989k5TQCZ5uTEzgpyp0ImOEQrW4=,iv:2mLzzWerndWe/M0bZKkJcx1lRoYzfA3JSmPBbMBjV8s=,tag:sQR8Obr7ztGo5BR73bLhgA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Zifs64thow==,iv:nSwXdgZHCe9YXYm+s+MDiTVdh7nrPaFId0stciZMKa8=,tag:NpREC7MnHTNT9Oj3BwBsHQ==,type:str]
kind: ENC[AES256_GCM,data:1xwPxFhLxn0CUQ==,iv:I1g7cjoNuRs+8v2Nr7mt4tJEKqoZAbsZczjWbVMwcM4=,tag:tV+fA8HzgcCp83B7nIuDBg==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:AOGmnteH,iv:jBPY1DEs5b5x6fdcPdIN18wOofNnVSngSUr0B0H53DM=,tag:GpaE0BCoXtPURg5DZmcB3w==,type:str]
    name: ENC[AES256_GCM,data:DieItQm3,iv:9f7lO0168Iqd8dFfXp8pU5BGRagfCzenYHH42Ph3HNI=,tag:afwPYndoI3/KF2XsHO0a6Q==,type:str]
    namespace: ENC[AES256_GCM,data:Y11z6gA=,iv:FfkChxG0CwzjG/I7tNwmOKnaCSP97utvDfdtHZJJj1A=,tag:MT1Ik82QK/Gf2Y2LuedPNg==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:Vw==,iv:GTPsdA799KZhPiD/j051moYPuqLh025vBHjdy0RFUYM=,tag:BMdVVmFGpQkhAmNl3wv68Q==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:eeCXH2L3,iv:CJHBD2IjqD7/nrkTaIp/9w69wx3l58xRzAbKNRviPb8=,tag:LFVkCu4CLPCWXa3BA+hqIw==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:QvP9ugp2,iv:3aQfoSFMynnPgOzwZtE6lcIK1r37jRg8zszpiz7z7as=,tag:3K3QOI7KM6o3T5ijv1aMlw==,type:str]
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: ENC[AES256_GCM,data:f7n9uvprlvVY2ERYgNX5TTREj4AEng==,iv:S/INADUNBxCtZYz9+KBcmvzlIfbKdzrji5tAx5Nlvac=,tag:Lw5MU4C4z1cnAKVvXJj9ew==,type:str]
                                  operator: ENC[AES256_GCM,data:TTTdAzs=,iv:I7KVnR1WK6MbXA5lTjIcl4HtwnMQ+89xzS9HE6CsKjQ=,tag:pzKAJMPdzn6SriEJQmcIpA==,type:str]
                                  values:
                                    - ENC[AES256_GCM,data:8U3J03Yna2kfzVXX,iv:snDKzm+Fk0JOMFd22vcqAcL9VhEEYNwYR/aFwPD9Q/o=,tag:rRNxq8NBK8zVBC4wt7GXLQ==,type:str]
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:uIo8Tw==,iv:AOAbQgLjYdXd7b8uhBr1ZxDrCq15uqeLNkNMnzZUX+k=,tag:cgJeQX069E1YAFnUnNR5YA==,type:str]
                      value: ENC[AES256_GCM,data:73YXPQ==,iv:vjkkqVe4YHTNJ7ZLxSYTqeTmDmG+JbYXiPJvhYGGuwA=,tag:wSI7zKn5T+cPLlK8zjKgrQ==,type:str]
                    - name: ENC[AES256_GCM,data:FqgntA==,iv:qEUJW42o8Lry8XnTgks9K9x2Pj9rzbknEdWIOSqGlIY=,tag:9XtjEegakHQl7NB0v9DYhQ==,type:str]
                      value: ENC[AES256_GCM,data:SJZO,iv:mKNIgvVuiEuVhUUU2YB864f+jv+Ol1kzk9CxnJkW47A=,tag:q+wQRiSBtEAuzLZiFXViIg==,type:str]
                    - name: ENC[AES256_GCM,data:Sj8=,iv:zPXlJB2zDEEqT2u5ywpKCuk/b8oHvVhhT2cew7wAiRA=,tag:Qfy11Ifj+ItLLsIV+88a+g==,type:str]
                      value: ENC[AES256_GCM,data:5DPF+ZCzF4rHQfk4t00xgQ==,iv:SDGc+PB2zOVVwiOKYbLa8H7Mea3q7oLENGgA2rPvHys=,tag:tYGNULYexyzj2ggtOgFeMQ==,type:str]
                  image: ENC[AES256_GCM,data:97Sk9Xx7UeTsL+Ks4DaQLnIwHRZQAg/uiJMX4Tuk5a5hWC1o4BdpRaG/BOY=,iv:X2Jv4v8eG9/25Eu5U9DxCWbYuCQ6QxKQN18h41wacZs=,tag:FY7V8oLNe0SPo25Ga7ityA==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:Ew==,iv:GjIu8aRDebrVMMjM087kf0qddqnGASnhOG9qPzYFg78=,tag:6Yeoo9r6ThFErsAVZmm3LA==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:8h6rbQg=,iv:XLFAigaDqNZsltTYZe5iquYshQYyjGxiUghSvIYQdtc=,tag:iRMLprE3alwgqhM15W9pOA==,type:str]
                        port: ENC[AES256_GCM,data:WygeFQ==,iv:xocKZQWIJH6DwWJ3gmbxi1c4FiKs3+OujjPCkXmNx60=,tag:XJOcEpyGg5G8+dL5wECTHA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:S6U=,iv:I00VJJ1nJphYYCWKs23Pa7S50DI/sdxU1JZcHJxoY/M=,tag:1ZxDKH75mWHhyZDw14GjqQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:o4A=,iv:FvAGnj/uxqugWuxOA2e4mvlRSGlhfrHXEASQn3ln1RE=,tag:c8xbSVeF1ETD3ROqp23RDw==,type:int]
                  name: ENC[AES256_GCM,data:aDATvi0b,iv:gnBnRh9pRJ9kSAZ8ZbBApxs9if3Ow/IxcVTuqboP0Js=,tag:nulkMqePD4/fmJ+LKwisdA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:Dh9efA==,iv:YRbbyyKoGp6RWyY9bRn+Qr3P9X5mWg/IzgF9huJMPTg=,tag:9GY/2LPqkXUqlC3Kp6HF8Q==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:dA==,iv:Q/OaVBK6Y/SLU9yMwxTFOTyZkQxF3DvcbvR4WUcPFLg=,tag:kBcFX6iSPWGYuiYNh4m5fA==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:pqSUYzg=,iv:LNZe78C9ACUZ6UtYJeWsSP1H9slyAUYVgo0mpDbH5YI=,tag:IXEdRuzt/TaCNj/3+QaERQ==,type:str]
                        port: ENC[AES256_GCM,data:8r1wQw==,iv:orU14ldmaF35O6m04mfuBrx00tt5T2Jnwe+0xnOmVcQ=,tag:60yy+2buQoClP9mjTB3PSw==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:/FA=,iv:O3bOtXRr/rWUAVBBgqDqUh+hVWqAvY9pSSSiPh4Lu5c=,tag:SRilfucT1/0ZFOdXD8VkIQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:s2o=,iv:Mw1dM0HwF6V9MVc5+wRo+MKJZZPUHUpwyEfWPwTPbgg=,tag:kg6cGu2M5N+ympM/mahSEw==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:Fg==,iv:mGwf9cB8wei8KmAhSWjvfOq3tS8EuPtdrc34TdkmJoM=,tag:XOtx1oCF93keKC1G0S5ZYw==,type:str]
                        memory: ENC[AES256_GCM,data:1Vem,iv:85S5Gq1laemd7/i5Ly+ZCJw9aYkVyNhPk1bN9sH+x4Q=,tag:jadJkUZVutvf1jE/tuS+wQ==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:k91KNQ==,iv:BSAtwtAUAacCr62T8zChejP1FPOqoGJhpi5jnGZLL6k=,tag:XoM9moh/mBG47Dcu0Y0rtg==,type:str]
                        memory: ENC[AES256_GCM,data:XTi5QvQ=,iv:2WMVTvoRsyisrvjUFQY8bbsyfItA94AMexyhxbSpx3g=,tag:zxvAJq+Ax7QnLGbOROKTHg==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:SKcBqFWBLQ==,iv:3X24Xr+9tJHoERC3/7D8MGMap5AY3Lmh53ymfakYjr4=,tag:QvQTCo0CHTKaDjEyMm0eRQ==,type:str]
                      name: ENC[AES256_GCM,data:uOh3OEGR,iv:cfiAJ+Id12NZZKl7VW+ze9DWsPv5Ll1aHfoBofXVtTo=,tag:471EIp34l7aZfmlbXzwWMg==,type:str]
                    - mountPath: ENC[AES256_GCM,data:+vZl,iv:P7YjX8cuXoifj9spVzscOna7KRsGsg9YvltOTwZ5PqQ=,tag:QrpHvB1nZ1Fd4A9MFmk8fg==,type:str]
                      name: ENC[AES256_GCM,data:pqRwp2Q=,iv:ToEYNdhtB5LWJ1/kJMFVG1Ank4vY4NIsL2LJIhaHJN0=,tag:5eP3M+g6t8J1se1Z/Ai4IQ==,type:str]
                      subPath: ENC[AES256_GCM,data:WuDokHtXYI0=,iv:Drwb/YN/1KiklEb8KX5Lr9Qxl7VTkNl69KvXDwrtWbQ=,tag:TWOtf0ZZJEhL/y6AEnZseQ==,type:str]
                    - mountPath: ENC[AES256_GCM,data:vDfizAkBjvUWT8TC5RQ=,iv:yJZ106rT5c8sCP1HCF7SdoR7oF7z+k+lBwaL7/YE4vE=,tag:JroExdrb3gxInSpEMXhlmw==,type:str]
                      name: ENC[AES256_GCM,data:I9SgGD0=,iv:FvztQE+3EWpDp6aYRbibqjHp/hgToXWSKOV0V73PrZo=,tag:FGmA2e62IWUpC4ASvSYJzg==,type:str]
                      subPath: ENC[AES256_GCM,data:Umgc9IEhaDSDl+3eZz0FVFFhVte/5g==,iv:shBtzH2L+CF9It8s5A5XnAQlSasw5/oIvtn5gxTN7+A=,tag:LsASQ0Gl4AlJ6Ob9LyPAtA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:tc8S8/UT3Obzgg==,iv:+JVbg+5JuvwiHS88V93AcnR2y70HCJXnCLFNefoEizM=,tag:ANFYBJ5rBo5+eB3dunHJ8w==,type:str]
                      name: ENC[AES256_GCM,data:vd8Wae/Hab3y,iv:NAPTYt+TnjR1VQ14ubaM3YJoN14hPTY4fWBhvBY7NxM=,tag:22KtIKlZ9LgiWjvXvt+3/w==,type:str]
                      subPath: ENC[AES256_GCM,data:gwAHyMzyRZmvSbk=,iv:CreEE97n0W3zBIBFZWUCiZOebQFRVPqwaBehH7YRtZI=,tag:Pl8LKyxTaf47Xd+a1+prOw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:aocg+SkkBETB,iv:qgpvEp7ZslOsHh4jwCJvwSqzOC0j5LTc/dKbm8C+eA8=,tag:lVoVJOkrvqkU6AE3qkMMvA==,type:str]
                      name: ENC[AES256_GCM,data:gSL/PV5URb+p,iv:Kd+gFx0aA8YDc2KC9tU5GPdDPLNnX0ryLKM7NoRNCC4=,tag:MXoviil7FHtYbqy9ZMuXyg==,type:str]
                      subPath: ENC[AES256_GCM,data:OiHNyrF5guQ=,iv:TpuCbPBllETXlIkeybr9djBSQt5yKsnQ9ykf1WnqQd8=,tag:ZRSUOOMOlY51K62kXLRW8A==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:QFr6+N0=,iv:ML46UjufqkprZLGnztqs5JAqdAdf23Wy4J2zIBT2SUg=,tag:bBNdbPu9PCK3ih+INqiW1g==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:j+Wv11on,iv:+xtmQYcGW907ySnyTyteGqCnV51nrmpMJVcxVx16hQU=,tag:NwPprUmYZp+QDFPpf69Y9A==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:bzDsFXC3a9Wok+EA8A==,iv:jGNXw1K4EBHtCV5zAMtCWsqtc5WTSB59O0pF3f6T/7w=,tag:pYo3nUbw4qOa6jzKy3Kt0Q==,type:str]
                - name: ENC[AES256_GCM,data:BdP8NfM=,iv:DL2Dx8aNXp8CnmHjqPV7u7S/sF3BJFCo4KAzi5F8Wec=,tag:EH+nNHQ536Q3uYOIPePLeg==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:P3JQy2jnwSth2CfCsGWlwQ==,iv:AMVai5gU1W8y31ez2i06zeMaWYUb9QILgUNm3oFJemY=,tag:WyRHv5Vtng+sK4a3jFMZXw==,type:str]
                - name: ENC[AES256_GCM,data:q4B4ppdm6IgE,iv:LYlEtOqYXTm3NOU29wF5lUlEllLs90clbffA3y4H2Xg=,tag:aZYCl4SZdwA789T4VB+X8g==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:IXilFicTAhBRETAkdRIL5UTJFbo=,iv:sj21cKdgxFremftpqoj1FLSQyuOGxe4+KrZtfI8dB/s=,tag:lv9Fqk9KlRCbhcPzvaIQvQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMnI2K2FmV2FZTmdaRVdY
            UU51dzJHNW9TbDNPN1Z0bVh5eStEd3VyUzIwCmdkMzVuMWU2Vkg0NjVSVmgzTTlB
            a3NSQ2orMTJnbVZXa2t0eS9mV0Nud0UKLS0tIEJCTTFhTk9BR1llWHV6NzZlaG9o
            TnduN3RsRW5LTWhoM25pUHVocStJS2MK7X0sePTXEs8TyrlrnlDxgyx489dkw6FT
            K79BBJCw6OkDo9y2TUENMTFM5Ov8VT+H+P1rgohYZOmKYn3A1Y7TQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:zLJpsZ8UKnFEUNxxHXHqFgjJsHn9TmUa2F2D0kLoYSC54R72Uo2OmaAGMZ7hoWX4TInXl8AwA5e4y8s6sOvaqqOMvpXqvk+ZXs4LwYZrNIcVdvwlqM4I9Fr9AX5nik95JpXHgrWSSopHVlKl989k5TQCZ5uTEzgpyp0ImOEQrW4=,iv:2mLzzWerndWe/M0bZKkJcx1lRoYzfA3JSmPBbMBjV8s=,tag:sQR8Obr7ztGo5BR73bLhgA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Suo=,iv:xDufwd/Il9Jj+hvDdoQ+Y3Qzd0TO/nWiUtvCnTzZ618=,tag:mf+ZHVs/5+R0UZd75RPwfg==,type:str]
kind: ENC[AES256_GCM,data:XkNXOj0YHQ==,iv:FQgujRpPI/xL/SywQYwmdfqcANCmsg+mqSoFfyji0w4=,tag:K++4mb/Bondx0ruZ5e5SrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Vf3Yo1L,iv:XLXPIeXiqahop5SKqfCNpSyeItwE2wREpVZu2+YoFGE=,tag:lxYvqx7IYHWar5GfKkc07Q==,type:str]
    namespace: ENC[AES256_GCM,data:K00fEtk=,iv:FF8FwG619vNoR0F9SHEDEzEJ0V08repXQqS1mJOt09c=,tag:yqcgcPo1tkniYyCQCUBg5A==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:38pmNQ==,iv:Triy7WaaTrlnvLfoagqyUJkATdZaG4cJPsMIW9czdgE=,tag:HVntxbdmT8qxxnPwumsJfg==,type:str]
          port: ENC[AES256_GCM,data:cKzTzg==,iv:VEBBv7C1Zuc3j53NH3xx9oM+Pd2BYtfc6NAqwH+xuvE=,tag:aQRrySKUEJsKE86icgWBGw==,type:int]
          targetPort: ENC[AES256_GCM,data:0Req4w==,iv:MvF+GGaT99WSmRiPv7exjHH4uQ9Vytbk9sny4Kp58FY=,tag:UpoHv4NKgn21kK9zRIzXZg==,type:int]
    selector:
        app: ENC[AES256_GCM,data:OXCsjeuq,iv:HBfebUwcvDM3UtMrgKBmc82oxftso9KVvW3NX3jxP5o=,tag:6F3OtOcT2Q+BPW1db47GNg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMnI2K2FmV2FZTmdaRVdY
            UU51dzJHNW9TbDNPN1Z0bVh5eStEd3VyUzIwCmdkMzVuMWU2Vkg0NjVSVmgzTTlB
            a3NSQ2orMTJnbVZXa2t0eS9mV0Nud0UKLS0tIEJCTTFhTk9BR1llWHV6NzZlaG9o
            TnduN3RsRW5LTWhoM25pUHVocStJS2MK7X0sePTXEs8TyrlrnlDxgyx489dkw6FT
            K79BBJCw6OkDo9y2TUENMTFM5Ov8VT+H+P1rgohYZOmKYn3A1Y7TQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:zLJpsZ8UKnFEUNxxHXHqFgjJsHn9TmUa2F2D0kLoYSC54R72Uo2OmaAGMZ7hoWX4TInXl8AwA5e4y8s6sOvaqqOMvpXqvk+ZXs4LwYZrNIcVdvwlqM4I9Fr9AX5nik95JpXHgrWSSopHVlKl989k5TQCZ5uTEzgpyp0ImOEQrW4=,iv:2mLzzWerndWe/M0bZKkJcx1lRoYzfA3JSmPBbMBjV8s=,tag:sQR8Obr7ztGo5BR73bLhgA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
