apiVersion: ENC[AES256_GCM,data:1kw=,iv:qzPO2GGNg1OvvkCiKPazHEJe+FVM831y7MaZtpf6YGg=,tag:norZ6ieUkK46F7kXnEF+NQ==,type:str]
kind: ENC[AES256_GCM,data:9FIAq5BVKXrk/tt4BPMk0TD8zF6e,iv:nwOdtcdLWXFsLF2Audd4div07qYISeSFAkv2qXbKTeU=,tag:HdNHJtIdAl3AuZIlR86pWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2Vw5OA8NSkl+w+/OGw==,iv:x9g4i/pT6RrfnHr8f8dwiue0eekawppVSj4x9IA06NU=,tag:M+wFhZLHSi5WyU7oKfXXMQ==,type:str]
    namespace: ENC[AES256_GCM,data:uXW6OOQ=,iv:eMJ5pnou90xgb0IFgeZHm9pKzcNaKglAkI0CRdgumKY=,tag:LJDlR5VrXglZr/ZrAYfsTg==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:36eyb/3jxhSauHRx/Q==,iv:063IJgXFpDWdaZpJxwoPUTdWlZtSpF4RhcD55NvvT4k=,tag:GwRG7zxc4tVRQ4+TSPsRGg==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:JGk/,iv:ixcYPOpUk4t4RsRb7lrvaCCgxhVSFgw9/16s3s2NxTQ=,tag:T1O/KeGSM41RfIj8tGoOmg==,type:str]
    storageClassName: ENC[AES256_GCM,data:SUkaroOKmNk=,iv:MAhKuiYRObQoMnJSd5HzNIcUEgSIksifCocEmNOKOSU=,tag:fWH1iSZ9fg5L8rEG+mTmWQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSnZROStxRGlmSjJTS1ZN
            dkxGU0x6VTZiRGVPMVdaN3hZcDY1WVZUMkhnCmJUTHBFRllJZmFCR2F2SlV6VHBr
            VXB3U0NKbVBRalFyZmxwZzRETlNjZU0KLS0tIGN0N1BLbnFvczVXMWNWclRJajNO
            V25nYmZ3bUp2b0pQckE2QjdLaE4yakkKYyMyKgACfbP4sZWaUC0KtMfjBbpamwur
            SykOV3G/py+ciZnsUHaW9UvKS+AESAdTJ6xSe4qjU0kXAz+m7V0fGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:FhJXEFC1mwrKfRwoC8CeJcTZ8AlJy5qWy7Rn+nHRswxZYEjWodcOCyFtkoF+IvMvkhxYRZXAPoTfbbbxnaFuGCm9ZmXgws6JAE2c3fyOCainvHLVF8fQDHA4zVWLvR/J1IkHtvIpKEVcRp1N+JXM2ROWMU16hiqC7RgqLnw+AGo=,iv:AwVoblUHElowpubDfzqKL5R8lhwRo77egjh4rcq5tNw=,tag:jDfpw3vYo0/h5EORY0fRnQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:UviX0bXVwg==,iv:cxmCuLvWn9kfDaNycD91JGyKIgfF22AOVk8JeWUSpNE=,tag:OEKZAvTjLpORtTYSqS9AqA==,type:str]
kind: ENC[AES256_GCM,data:o8gp2Ofgs9RjGQ==,iv:J6KZakKrkpGtyIqE6U1HhCfV0Ir3BEWjS52EMKgnvno=,tag:nCk7OX32bDA8WTgDdohEZQ==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:zsQqp9t3,iv:5UV7hbKFJpxQydYHKoJ8DjMmgW34uRUVJitv2RulQEE=,tag:vNwp5G9KIIfOyIowmnoCvg==,type:str]
    name: ENC[AES256_GCM,data:TlhenXTZ,iv:jjgagXNGRPGosxi+MpLOZjDb5VbfzchcWv+EXDxGjys=,tag:RaZDbMYUZzhVNTrYPWUscA==,type:str]
    namespace: ENC[AES256_GCM,data:pC0gHtc=,iv:bPcHwqumIxQ+5XP1jgd1l9/bIWokLPpywlTUhlfdEg0=,tag:voWMYXl4Toq7/IVtkZoEww==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:qA==,iv:xIltfYhIuL854z+bGsuhqL+GjM1eoXOV3yH5wzE/4VU=,tag:43RurmHAfR3Y4ICkfTmnyw==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:GiaosF7R,iv:l2YRrMhJmXfxy6mM2Lzyz6LQUgHLL2FKvxgk0gvmOuY=,tag:8IDu0kTuiJ1g1B4QvNEOfw==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:8F4cggrm,iv:fFHZu3L49FpxmQyrbDNPszdCHAODF1PX7JoCE4QjIBk=,tag:ZTVlliVene8TlMFnHL15qQ==,type:str]
        spec:
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:mC8Y/Q==,iv:l0UVz2d7qFVYXImgvrf172hq1K5PpI6oglJW8chnKow=,tag:xM8z/lXOAycRxSsP9qnOhg==,type:str]
                      value: ENC[AES256_GCM,data:M+RGyw==,iv:zLgeSF67nYY+FxQuTbLQMTHdvsbjVfoOr6qKXaGAlkE=,tag:H8Rvhg622ErWnfBcYGT+Jw==,type:str]
                    - name: ENC[AES256_GCM,data:L0qb4g==,iv:eyo+F1g45G+nk7+4RiBW5exkrBjKBYCjuQtnsRB3nNk=,tag:XgENBCqlhwqOWYE/xhfl0g==,type:str]
                      value: ENC[AES256_GCM,data:FfoI,iv:hwXamp9F+5v3yaqMH/11fkAk3naiBpwtt2m0MqG3nDU=,tag:LZVsonH+5JqbcD+syqWEVA==,type:str]
                    - name: ENC[AES256_GCM,data:AG8=,iv:1LywOAB0Y7WhDeg5smekD2Q2JExHkOSp42pOyGnWR2w=,tag:cYPxiHTI7V0i/O+jvqNhjA==,type:str]
                      value: ENC[AES256_GCM,data:EjXBF2de3/AmAuyDmKhJ5A==,iv:y21mmT0uajskx9pP9cxSYKvxwlK9ameTP4smhyPreGE=,tag:yPY0y9YUm1q9zDDq9TB4mQ==,type:str]
                  image: ENC[AES256_GCM,data:j744etEBrXkdtpRW7AxEqqMUNDaC2QDck6gx2m9FeygbToBlFQdLDPZAhSw=,iv:l3xuYQHuiSpe/AX7ekc6Lc8ykXFMkwyc3y4dEA398P4=,tag:bp6gXIKSDzjLvp1NbeeIjA==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:vw==,iv:LBAoI2EZ1yIMFXcAC0GXxVku4j96Uo4NE6vgJ3+PCcU=,tag:M0YIkBlBv+goW40Me8G0Gw==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:irp9Q+g=,iv:2bzRL4w+3WeQgz7T9Pb7k74LpckyHdZZ6KZZDQxn8h4=,tag:jDAz4mRBZmyYK92uNrE7TA==,type:str]
                        port: ENC[AES256_GCM,data:vQiNWQ==,iv:6Mzkdy4WcQTobAIwR3ZIb9UI6vkiRo2vaitBBpBvc4Q=,tag:hFel+k8c67lcgnBUVltyMQ==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:Q6E=,iv:jrLjTjKZ6pU+930bx7GWFUhuz/pX7pzcoUkxs+o71X4=,tag:YDmVrrPQgpmrU+GZj5QYyw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Uec=,iv:7YO/OdoshnSNfnLrJmLY5XIcb4jJ2oAfvKeMPB3zTl8=,tag:vIg7tyHj91HXTrTpOdXpJQ==,type:int]
                  name: ENC[AES256_GCM,data:mQs/DVef,iv:fkjWjUboYx8wyA/l0xi/n4azfYEEjYR5TqrkOjtg83g=,tag:LJdCm6U4nd4iAnD5lQwjaQ==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:DMp2Tg==,iv:COPnmui4N2fBDhS+vg9lwu6hEe1MH2p7RhwI+f39s3E=,tag:vXv+tp24n0MBiVxjBpZ6Mg==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:IA==,iv:nd+ePiHfmOfXAnexHnMOvwARGSvYlh1frrz2HIhWOkg=,tag:h3L2oH3zeAvunMsRWXZYZg==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:nRd+9uo=,iv:TI/lluew23WDGlnjmXYJWYPF4bF5AZGLNeceR1iFccM=,tag:8iej4DDjc9EMO4e4vL0fOg==,type:str]
                        port: ENC[AES256_GCM,data:ABkKmQ==,iv:c550K8gUmgop6IF0w6KLS4q8u1Ix5rsZmZa9UFA77iU=,tag:TGXAie/fRTMRah5ukCK1Ng==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:GNE=,iv:9xc1CPiG2BuTi+DZ9SkcSPETvBRsnz9KrfsjDev7XMc=,tag:mX3x9N7Qd1kpicxpf8QSuQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Ql0=,iv:cWSWJn0yZnwAO8Px12Og8PXl2iOMpMwZPQcW7BzRLZQ=,tag:ff0RFJQ83J/gc10nZI5ggw==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:nw==,iv:0/Gw6VX7YimgSjyFLW+PdhSD/PSkB4eSCyT2pMRgGt8=,tag:r/IpCGFN22wLD0usWY6/OA==,type:str]
                        memory: ENC[AES256_GCM,data:SqIq,iv:JE04M31RuTSITNXxRE10cUuw03ncW3OWWvgCy8crJvA=,tag:RNRjTvdKh3JZ77nQJNzGQQ==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:cKRLmg==,iv:L6VSIQFKTcxZVAlNbnndapvzVV19kuerLhLmaJDDqUk=,tag:G2INAA8VCJpLbJy8FaLzOw==,type:str]
                        memory: ENC[AES256_GCM,data:pRtJUmk=,iv:kEEObgmqKE8fWIgO8wHqsA4Bnx7PLwPEUup8WeqppYc=,tag:UH//mnEJ2pG99XA/uYh8VA==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:R1CkJCwyLQ==,iv:qb2z6LSXgIkpxVl3fyfL6UIHnP/efn2UXjxchsLYXRU=,tag:jcOOx7OedjZVSVgbOV8fbw==,type:str]
                      name: ENC[AES256_GCM,data:dk9Q1Bft,iv:p1YRtdKLG7Xc5C6eu4ZQEavzOQlE+WZQXj5+Z/W4RrI=,tag:XPdafEp5bn9km8JedNOmVA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:c1H2,iv:fQZj+SC14lu7hYHdv4PFNBjFsmckybniKOzKSKWHitY=,tag:xwoacmnoB8g4dbqXi10L1w==,type:str]
                      name: ENC[AES256_GCM,data:QM66b6s=,iv:NEqzK6wPrnQIw/w+SNZwh3AES3CpnhIXrUpfulaB35s=,tag:nZHRMk8hdAY54QGYtAGwCA==,type:str]
                      subPath: ENC[AES256_GCM,data:Zv6ijdYWYTk=,iv:Eo7rAvxkEmV8MoAmWGdohaxlsP9YLBgiCe4aq/yru00=,tag:hnQ+0PTxYNL/+Qp8OGuerw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:gYjZwwkbFy4amWceUUA=,iv:tAh+wjZCneREpeUDR2V4ie6wIHYi/xtxiJMJlTMu97Q=,tag:lwzMBKqQbWAuAmpl5VDqFw==,type:str]
                      name: ENC[AES256_GCM,data:Vg7u+Ys=,iv:0JyJpDKPMouA0zary9CjZgei3pJ70w+/V/2EBkIYQ0c=,tag:ekjng44R1iKq/KxLO6+KaA==,type:str]
                      subPath: ENC[AES256_GCM,data:pBo4DSpS8hdXvDW/DxPupkcx6PCWDA==,iv:35XQpxO0cuNUdR1+XTJVQ2AGsC4mJThhWpeOnkqdmBc=,tag:FUfq/0x7XeWnhnq5ql+jcQ==,type:str]
                    - mountPath: ENC[AES256_GCM,data:1Ba+QmWYPSq0Yw==,iv:Yj4W5a+p3Ks0vmxOkGGYRjYu1rc3XBNZI6KHhSjJnC8=,tag:+OB6AFMQw9zLurWaJf/K4Q==,type:str]
                      name: ENC[AES256_GCM,data:FNFy1I/0aOrg,iv:/5Odgqijw0xdZeAcGN9ypHk9M/eiJ7mpLhK8AXvMoQY=,tag:m+bx7oPAVXr42cAxKLMzZw==,type:str]
                      subPath: ENC[AES256_GCM,data:/bDci1JUg/P+lzE=,iv:S8pp+rXWTo7QNg10YSTyqYeF52Try53yhJh9fF1NkhU=,tag:WpDHIf/H+wmck9nGQYTGAw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:qwZK3AYIbqPK,iv:BXLcxvPgGnI0eerYJW0Sr1R3BajqEZa8eJqmKnd5AHM=,tag:3OCVFwtsFV69xvNKsKuVow==,type:str]
                      name: ENC[AES256_GCM,data:80sYTxjrx2nP,iv:GBFkYdWqHzv7/DhzFvPYHDuqCHIC/MbccFMHNKkvhIo=,tag:uQERvFInuh83+Yu39xyktA==,type:str]
                      subPath: ENC[AES256_GCM,data:U5NH7kZanBs=,iv:TeQbF0q8ZGQRvHn+QLhiTPC/T0XLLLFvbU0S+Yi/mfk=,tag:uey+QDzd469nz+HwQM9ZLQ==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:ITlI8Lw=,iv:PX14kXzNJla3FrtOTrNMQ3oLZCx2Xq4F03A8+C8MLsE=,tag:WAmyNyMzXe92zZA6OXMNJQ==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:d/y/oCAO,iv:UsLFPb04BZQuT37yFxHIQh1QD2V/uHqZvXCYOeJH1M0=,tag:cbgzjsbLq4wEIhoV/z1DEQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:8vHLSRNG2Kj3rpCPOA==,iv:rcyzsISBEzjEl6excMFAZZBWEwGY4fZLIMJ994IfRRs=,tag:U8MsvtBD4Xs/A5K3JqG3WQ==,type:str]
                - name: ENC[AES256_GCM,data:a9mmFD8=,iv:lSYJtK56QGE80yYVUJgOt/s715FcA0VuBazUCQ5cLLw=,tag:YiT0h1wOHiKuTI2BbYWKUg==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:uK1Amyf7T/Z2jYGFOwXarg==,iv:3XUlfkwE7c42mRd402Ag0cVVrQkS3Z7d3/8sLpnhmV4=,tag:VhlF9z6b1ipuQ4oJJ1b4hQ==,type:str]
                - name: ENC[AES256_GCM,data:WogLS6aK2KMf,iv:sb18TlpESNKz+vXfU25bFU7aDTHY4ICEPYwB5nA2QO4=,tag:AfsPYRt6he78psMgCwONqQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:fzDgI+HdjNOH5imZbrpSYtn/uNU=,iv:dN9ootdbimjePtDnPOyxCoV7NLlF0CGjL1SKmHLByc8=,tag:F5HXTciOMIgxQfoVumn5OA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSnZROStxRGlmSjJTS1ZN
            dkxGU0x6VTZiRGVPMVdaN3hZcDY1WVZUMkhnCmJUTHBFRllJZmFCR2F2SlV6VHBr
            VXB3U0NKbVBRalFyZmxwZzRETlNjZU0KLS0tIGN0N1BLbnFvczVXMWNWclRJajNO
            V25nYmZ3bUp2b0pQckE2QjdLaE4yakkKYyMyKgACfbP4sZWaUC0KtMfjBbpamwur
            SykOV3G/py+ciZnsUHaW9UvKS+AESAdTJ6xSe4qjU0kXAz+m7V0fGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:FhJXEFC1mwrKfRwoC8CeJcTZ8AlJy5qWy7Rn+nHRswxZYEjWodcOCyFtkoF+IvMvkhxYRZXAPoTfbbbxnaFuGCm9ZmXgws6JAE2c3fyOCainvHLVF8fQDHA4zVWLvR/J1IkHtvIpKEVcRp1N+JXM2ROWMU16hiqC7RgqLnw+AGo=,iv:AwVoblUHElowpubDfzqKL5R8lhwRo77egjh4rcq5tNw=,tag:jDfpw3vYo0/h5EORY0fRnQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Kb0=,iv:DQFHYlJr/q9PbGVD0joXhAvhjYvnX3YJ09vbdvtvcXM=,tag:frAm6DBsBIal1ZZb2qiwYw==,type:str]
kind: ENC[AES256_GCM,data:JDZTGaQZPA==,iv:N9yGLaRKyDV+1540ecQ2gMglFB1vZzrY19YoI3qK8NE=,tag:E1TkjyiCDIei99OEbtLm1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IvQ9fSwK,iv:tWv74YcSPm/ucp0IcDRqte3kjitafouOBMzzQzJ8TYQ=,tag:ucVLgI/FlvNt8goje879ug==,type:str]
    namespace: ENC[AES256_GCM,data:GIviAwc=,iv:qzGJ+HMjOw1Cmc5hBXd7f3XWaf9PCnEX0ukOfFyw2Hg=,tag:0IAxhrfvx//2uv36awLBvg==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:JtfiIQ==,iv:fs/g3K7ugNLXUozN+sW8wM9rDtug126lwu2x9VoDbiI=,tag:H4cm/FZygbPoqDUPrpFGfw==,type:str]
          port: ENC[AES256_GCM,data:yrPsLA==,iv:7UH9ZMqDmZYdUIjT34k6CNE8TWT0ZKedt6RmPO3F0xg=,tag:t7+4HwuM3zMpI9z17Zp7/Q==,type:int]
          targetPort: ENC[AES256_GCM,data:xRVa4g==,iv:M7lLgOHlN31pil5DDciqhX54vJjeAHn8WSk8OOPrffA=,tag:1oIxhUQrUQYhjVygzktJfA==,type:int]
    selector:
        app: ENC[AES256_GCM,data:6UIJ9p69,iv:cijceIsYZSshPpxngVtGOcHW6lHp4UeuFqcGnUVo+/k=,tag:6vwBK+V+CKrQFTRFcgBb9A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSnZROStxRGlmSjJTS1ZN
            dkxGU0x6VTZiRGVPMVdaN3hZcDY1WVZUMkhnCmJUTHBFRllJZmFCR2F2SlV6VHBr
            VXB3U0NKbVBRalFyZmxwZzRETlNjZU0KLS0tIGN0N1BLbnFvczVXMWNWclRJajNO
            V25nYmZ3bUp2b0pQckE2QjdLaE4yakkKYyMyKgACfbP4sZWaUC0KtMfjBbpamwur
            SykOV3G/py+ciZnsUHaW9UvKS+AESAdTJ6xSe4qjU0kXAz+m7V0fGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:FhJXEFC1mwrKfRwoC8CeJcTZ8AlJy5qWy7Rn+nHRswxZYEjWodcOCyFtkoF+IvMvkhxYRZXAPoTfbbbxnaFuGCm9ZmXgws6JAE2c3fyOCainvHLVF8fQDHA4zVWLvR/J1IkHtvIpKEVcRp1N+JXM2ROWMU16hiqC7RgqLnw+AGo=,iv:AwVoblUHElowpubDfzqKL5R8lhwRo77egjh4rcq5tNw=,tag:jDfpw3vYo0/h5EORY0fRnQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
