apiVersion: ENC[AES256_GCM,data:Cdw=,iv:z8lFlLw8mvrdCoOGTgR98AvC5Kd8maX8fJswM292DWY=,tag:hYVJ8Cy1I3JwWSytei5VKw==,type:str]
kind: ENC[AES256_GCM,data:NHnDwockMcgHMm7WHbVK5fKvh1cB,iv:JFgeCtIxYFyZmTSCF0SgjkvuIZQD1RrdXUp1BV5xoRI=,tag:yZn1PIt64kldY4sK/Efp1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:j7CvRhjVUo8j9wo4tg==,iv:YKB3vaWCI1iFJrNA0BZgRDjZ30GuZG+4eb74hqd5s1g=,tag:qBKelpc5ibwP+Tf0pTDv2w==,type:str]
    namespace: ENC[AES256_GCM,data:S/eri34=,iv:aPCZmRvL9CB2eUZc0U54Pq8NqvBiFQvXhDGxcLWU/Ao=,tag:TiUGYLP232wPV4c1CoAP8g==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:kg0CPJeD4fpgvhRf7A==,iv:Z1yD5tVvhPg/nVJJ5R9TF71sPbIllUWT4tjZ9qw2Hkg=,tag:lD0+Nm+szimHjiwTcEpp/Q==,type:str]
    storageClassName: ENC[AES256_GCM,data:3M9YUIzZ9K8=,iv:5HvUapiZaG/YVWeXLeMhud0taqHvUmFXIyfgNlRmcIg=,tag:LF1GosQyhZYeUAFq+FnMag==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:GgvD,iv:bUbYlXrpynQu9vgDlC2IFE/7YhYY6fDIMB6UxuiBfD4=,tag:06zANUbVBBh51Xn2/TS+WA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VFh6dnc2YnB2ZUxwMHdo
            KzZVa3VUOTY5bVliZXJZdmRjZkZrMTdHTEU0Cm9UQzVkRWJHMVh2SllYT1F4SzRI
            cUlCbThyUDh0S2llSmtHcVdXRGk1dXcKLS0tIDJnb0t1b083Um0zaE1nZlBNdk51
            eEwzUUMrOUtZMkFENmQrazFmUnY2ak0Ks77+3PPFcVLKhlgVZAWZUcYl9nJhZtUJ
            tSVHRIz7yEIMbH4iPUk98pFCW+ioK3XbhXRtVc69e+Ern8Gv+Hbspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:YNWMOygXEC+XJlBBK4KKPFdeYGghVNaA99StHHiuyKGf6ztfy+UZTv7MzFN4z4ydvSmK8y/TMhRQs7kYSnIY/QK/Cc1BAkEytvYPsdM/MvkBSEz7PxCtX5we3ke7nQz9UFHQgX5M8OvQhDvK3GlDbTZZFQin4rPtqN00VGt5ANE=,iv:5MmSoUqcJjLtFv8zgDpRoX7msMlYZ8DYzC2qfvy6yYA=,tag:ypTDk9gk5Fr8tpcuPm/Nog==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:ruasK+6wYw==,iv:O7zCjSRYXRQm+HG5ev3sJwqxf3BhW0wwPK0qK26o0EA=,tag:iYIKyFgMaRdak31FQ7GDBQ==,type:str]
kind: ENC[AES256_GCM,data:I+odyj+yOvEqjg==,iv:ctxcp+FOUv8K1whPK5y0FnZ4zFoW6TbcZ/hXRe1H+Zk=,tag:So9TKPQcxwHm4QXrPlmz7w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ED/MTVR3,iv:jorUYub1p+J8SqietOEmWgxyppYdQgQxNq3c5jZUYpU=,tag:1Cb/nmHiCVtnubBRNmYK+Q==,type:str]
    namespace: ENC[AES256_GCM,data:1MOXvV4=,iv:YDwg2CnBBdOSnReJQKxyDnEcgqeO53Z2DLRtAxkntUE=,tag:UteTa0dl+oQk9d4NDEf0kA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:IQ8pIBE9,iv:VgfUDWrnY1IrLOT+CuiBM+ZhP6SVaUga3mLcjEhEmV8=,tag:Ea3Okzvy6ngZzXr4mYhSLQ==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:0w==,iv:A9xmyGDQlZv2kagLPSaQdQXkprcnVNtTYSkCoeI8saY=,tag:JeVxfHEGfnCiF7Eo6i0/ZA==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:cwD3+/z5,iv:3kiQ+afoBAUdw0f5jJXlYkz9mmpwWn6COfEaFmXpnZA=,tag:R+ZsPr4Z+ZOqzJ8Sy9qJUg==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:/OpuqoYi,iv:gOhmmcILszh3SKrWAfCNMA7xWIAkWtiUZwR4OTWnvgI=,tag:J4Zt46kDXBSUJi9wUn79KA==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:hhulp6k=,iv:XpcA/psDs9jJmEQYQ3cTSi+7ZSVgvWBfcSfUasOCzS0=,tag:bGl9HMhUfWFa015B7t8DMQ==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:6JmFzEzd,iv:TB1NnVphziq6yLQgVL83z6WwZMBfZU9DYZVNDw2XZJY=,tag:/Fze5vcPRqK84BSmPhSvZg==,type:str]
                  image: ENC[AES256_GCM,data:iKNM+T8rfvxMng37zHhrxc4w9Dm/jeTKVaSe+bFrdwtk7LNOmiLd,iv:N76lNxmTbd3XVv50HKp+MoGVOJgXSxZt0Jx70xbDByY=,tag:VJ0j/LEcgOGM2c0q6np92g==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:31fz4g==,iv:0r1beQslc/eDVsND2a/qFlHS2AOcEiERjzhDNa+CVg4=,tag:z1Ph2F0+ax6kd6GL8Oh0sw==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:lZ6+vA==,iv:Wojjnrv8qNksT5X0G3CQPtGReSpk8/PPiWa0C6D8zHE=,tag:tljQ6LVTrsVKHzdePHLH4A==,type:str]
                      value: ENC[AES256_GCM,data:KVRmvg==,iv:tbXEvm+r5Oe52NEwR/LuBkFKzo+Kz/4ACZ/E3ucz3OI=,tag:yvPtMzwbyzzrP953vWnVlQ==,type:str]
                    - name: ENC[AES256_GCM,data:wvbQ8A==,iv:ZulUXtzx8WVg4mpESNsqoDLX0wu7oKo9rmnNaSiZ+bY=,tag:tA1QJsRWpFp8TlJXChajhA==,type:str]
                      value: ENC[AES256_GCM,data:GYXS,iv:ZVZv+/w2EGfUyWnpfOupAIzEqaKYDYf1MLWrcXC/efo=,tag:S/MxE+VBFbZO+MkiBYwJ+Q==,type:str]
                    - name: ENC[AES256_GCM,data:jvs=,iv:sEbHoh3LQPf+ZflRbgXdAbBfNqyCnQibxKIN6ktnJfg=,tag:VGpFwGRmEvL045Tk/yHk8g==,type:str]
                      value: ENC[AES256_GCM,data:Y9hhHReqsak/0s7FAzOuqQ==,iv:M8KhxtGNLwuv6H0WEO1ZkTilQVYha5pl/raxWWAerYw=,tag:S6y9O+FWgBeHdFkj5k5vIA==,type:str]
                    - name: ENC[AES256_GCM,data:RguyOFuIH3rcPQ==,iv:WBaCcVPIovlMzEZU4XklfWAQY7aTW0C+6SrrdyRk9dk=,tag:Li/Vi7M/q/4MsKs5ePQ1HQ==,type:str]
                      value: ENC[AES256_GCM,data:k/0vo1TNKGOIlwGMIBKEXtNeZ1VS,iv:xziVuh8cCYyH5LIjLXhGLPyjgLezrOnM9dOVLtyPk1k=,tag:wabWRr0c+RBHRhQL3/v82w==,type:str]
                    - name: ENC[AES256_GCM,data:1w07Dk2MFQfVLRU=,iv:yqQrSK6E1RSh3VaIzyT2G2nSfmOkCcaVUd38IrGfJBY=,tag:HzvEzG9pT8IatB1ZTO6HoA==,type:str]
                      value: ENC[AES256_GCM,data:auDH+tG8YkqUjcZ1h7tIRwyAfEIl,iv:pOvuRjGyJ4z41VaSLaquii5TbVmB93yFsl8D5WkRDeA=,tag:pUv0M78Hgm3TlfWQ7K3rwg==,type:str]
                    - name: ENC[AES256_GCM,data:V27AlEvPo9o=,iv:4x30Xwi2zt1LC2hEOkrlaU0I/mBO0LvuYUX+vZc4J0A=,tag:+PRGpvGt1e2de2wTv2x93A==,type:str]
                      value: ENC[AES256_GCM,data:hF+5HrKZ45GlQcnIVZzbBRpKWtKbShJbFh+lxsiW6+dqm0MeLskrKj4ejMwtZ/vwqty7cfobNenlVTCx+fchOTwZPSZTJmlwKXLJZJaHdQ==,iv:k4iRvNI1KeghbLjLtvnMZZ/rvZU5dN9A0JqLx3snTnw=,tag:eBIpJzkxi6BMSzgh6LZybA==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:WTddwAuK,iv:ZjNrSVqWEqVkY5QcqxOaOazJQFOukWOSsIrntZ+9tmg=,tag:mILGHgjcxu5D0yeAssX27w==,type:str]
                      mountPath: ENC[AES256_GCM,data:w8Aya9VBhA==,iv:zrnGIvoKVhxzTfxVWRjPnHXqHlehuhTkLQn7Rdjohyo=,tag:qPwUKObeeaNbT6/sfvCMrg==,type:str]
                    - name: ENC[AES256_GCM,data:vqPIeA8=,iv:SuZAnBPJpyQza6HpeUrnbdxDAYX4J/H+PGIC6+Rbfxk=,tag:WUz+UcOA3qP0pHcOrmGDlw==,type:str]
                      mountPath: ENC[AES256_GCM,data:jSd4dMP07g==,iv:M4inmB2iAi9r8SMGcBKq5ueKIbYW+zcBXtZPbvOUdPs=,tag:FVe5DUeOwajs8Iac5VvbZw==,type:str]
                      subPath: ENC[AES256_GCM,data:Kl1an50C,iv:TnOp+d99jTax6QYpbWtejgCYcQMUCOXPpfg+GIfOV4Q=,tag:vVo94M4KEL6blQsDenBNuQ==,type:str]
                    - name: ENC[AES256_GCM,data:znU+MFE=,iv:+UUh5aU7vTX2L9pmEOxIprD4I9R2sffENa5h0Mo8NRo=,tag:3pU1SKaXsApRPoJUwG/xxw==,type:str]
                      mountPath: ENC[AES256_GCM,data:mP38,iv:ftCg12YTOkH7x0LUs6P+vADc8N5H0URnPWcS66xvoOk=,tag:FKMb10TA9+6/Ced5woMNgQ==,type:str]
                      subPath: ENC[AES256_GCM,data:ro7nKO0qqHo=,iv:zuTvSEY5XqKfRf68OShwx71es1K44ze68CAZZi1H14s=,tag:0mRu5uc0fRTpse6liBIjuw==,type:str]
                    - name: ENC[AES256_GCM,data:CFjcqbynzYHi,iv:TrUcnEP2VY9wHZTa+8vKXcrlcY7w1XhSdpInb8Dc6KE=,tag:JYtu26f4H6JYZSWG7O0iYw==,type:str]
                      mountPath: ENC[AES256_GCM,data:Bmd8GRtjgtbx,iv:2C1X7g3FYrHNWOx1ed7vhUrKzh1jffEt9SeoNMl7wDU=,tag:+gWCrOO5QTbHdWv+AWBJmA==,type:str]
                      subPath: ENC[AES256_GCM,data:VewZH6RqLvs=,iv:4u0wgEkGQ1WGhBmSDJ348GRP1sr6yKFo4CWYZdMIm54=,tag:LRJJbOcPybtK++02OWbkZw==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:RPBK,iv:WyozhvUDkQ8d4MBL2R5TEbykOgoFq6OB2WzVGd1TSl8=,tag:k6o5Y4//AtHnMMPIgOCqLQ==,type:str]
                        memory: ENC[AES256_GCM,data:s+sWbEs=,iv:XBZSo7L2Bx8HtqZEQC4904FBPtsfSRQbNojd8ygNQl8=,tag:Wym4DtUVV7CGdPZf6s7JUg==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:yA==,iv:0zkQY+WmOHlE9jAveVzM8Eew1qkAx+wCD7HQcaKsUis=,tag:giVaaE1VhtzA7AlFn9NMug==,type:str]
                        memory: ENC[AES256_GCM,data:0RPpl+w=,iv:UNV5LsWWzZayInzgxIBZYw3iWMkKb+2F3dmamNeJiHE=,tag:wg8Jigsewe3s7ONZiOqzCg==,type:str]
                  readinessProbe:
                    tcpSocket:
                        port: ENC[AES256_GCM,data:HzTF2g==,iv:BKCbYkWOGJDJ4YQKHwwY9ZoXkH3+YFs7oWgBYle0q0A=,tag:CkWeo40CHRvCp0Gx7LTOFQ==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:6Tc=,iv:hduBt7dTFmXe4IF5fa7I+54CGOKn4RtznXqiM3ZWzzI=,tag:uCBylZf6SRKGUhN6PgT6/g==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:PAI=,iv:yLBlYNST5KSy5duqDaTK3zl6YzkiGB8IK4tkw/cWYFg=,tag:oUU4Y7t0yWDKiRRNaRkiiw==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:Sg==,iv:vCzubOZYi3D5Ad9pF45Rq/BbhZpFrgj9+H/1Af6bOJ4=,tag:qdBwgTKxuneC7RN81TvCcA==,type:int]
                  livenessProbe:
                    tcpSocket:
                        port: ENC[AES256_GCM,data:DbMRKQ==,iv:1it1AuRItdb5xcerX77Z71Z+GcILZbfgn98c9rmbo4Y=,tag:uqN/NWs4iftdeLev5b5iSw==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:TcQ=,iv:7hwEaPfLa93zvWtaJLiTjQ3GL9LLa+6384TSQR9+r0w=,tag:+XvC/KZmhAAFna1+Tcz5+Q==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:fEQ=,iv:7NGuoHmjiP9nSccivpxxTA3jxy0x4xT1EggckqmMr9M=,tag:awWMZkXS1WWUmEO4IJDGZA==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:HQ==,iv:6fc9REhxLHc7gs+HJpQcJh1CJaQfOrtAI8WvSPduSe4=,tag:1Qha0sM2J11fZj/eJKqNaA==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:ZtW+bQVK,iv:VV9tpk7Xgp+NUkABLIITEYrGEJQvwbJGoOOE8lo+Z/8=,tag:cJaG7evD1rxoQlhLg4vdOA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:RLesHF0T3MUd4F3DFw==,iv:+fT2m2XTPKKr3LBgQA0WAFD2duapbK/pFuM+pcyKzZc=,tag:oRBEIdbbwCYcjLcj/v74oA==,type:str]
                - name: ENC[AES256_GCM,data:2NI5tww=,iv:Pzush4np63TQgzuF6WeCYazxY5WRhvriuG9njGUkrgg=,tag:v+W5wo3/TnIC6WoqXAN3yA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:MVxIbox2lY/I56ut/MJMlA==,iv:pwAHzK/3kyNQJtzYpn17up6josRD3czJbwddd01n5ew=,tag:i28QzQkjNu3GLcuIxITcxQ==,type:str]
                - name: ENC[AES256_GCM,data:PZLKPaZ2JlbB,iv:5NdjjwwVuXQSWkZrnJqIsEnc1b+ySuHifmg8/C/1DSg=,tag:Q7ExmL55oTKk3DHSGsCAUg==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:rJWcmc+dytzweJ8ma0UahCkjYDE=,iv:ELz3me6DUTDug7MeSo29hjeFIMJv83D1wbn7yRrlKcs=,tag:qV8V/jigRDyEHp+EVpME6Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VFh6dnc2YnB2ZUxwMHdo
            KzZVa3VUOTY5bVliZXJZdmRjZkZrMTdHTEU0Cm9UQzVkRWJHMVh2SllYT1F4SzRI
            cUlCbThyUDh0S2llSmtHcVdXRGk1dXcKLS0tIDJnb0t1b083Um0zaE1nZlBNdk51
            eEwzUUMrOUtZMkFENmQrazFmUnY2ak0Ks77+3PPFcVLKhlgVZAWZUcYl9nJhZtUJ
            tSVHRIz7yEIMbH4iPUk98pFCW+ioK3XbhXRtVc69e+Ern8Gv+Hbspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:YNWMOygXEC+XJlBBK4KKPFdeYGghVNaA99StHHiuyKGf6ztfy+UZTv7MzFN4z4ydvSmK8y/TMhRQs7kYSnIY/QK/Cc1BAkEytvYPsdM/MvkBSEz7PxCtX5we3ke7nQz9UFHQgX5M8OvQhDvK3GlDbTZZFQin4rPtqN00VGt5ANE=,iv:5MmSoUqcJjLtFv8zgDpRoX7msMlYZ8DYzC2qfvy6yYA=,tag:ypTDk9gk5Fr8tpcuPm/Nog==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:hwA=,iv:+fgc3YIIDblZaDa+WdFTqnk48lTg0CDfvwbOUoGxyYM=,tag:VLDFZd4NoIkfd31xoKRYEg==,type:str]
kind: ENC[AES256_GCM,data:4LlNey4Hcg==,iv:mYSTRktKiUUlyUY9+U50Ji2WG7sn15OHEAERL4hA084=,tag:4yJ+efe13BvXsdGgeAW6SA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:scCQmw8/,iv:QKJq0zSL1rUePyh4WGhuQqjjr9ciBTwYs7f1DmjYaiQ=,tag:49HcF98ew+5QgI2uCKU8bw==,type:str]
    namespace: ENC[AES256_GCM,data:PMLwu2I=,iv:xKJ9sS88nlLzj9I1iNFAsuAKCkF2pYVGrXMi0i5tVOk=,tag:LVJ/5emusG16zquRzTkhxw==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:PRUjysj6,iv:/HY4Joml1CG2NYdzJCFkCcXqRSZDA9u4tZvX3Vajl6I=,tag:UxAU1sO4eRzZm0RWeAqmQQ==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:Eam8QA==,iv:QWFoF1njGsgRqJAskAk1AtQcWoqtURSQBcvCRSFbWMY=,tag:fwNM9rV8NQejasVw0tP5eA==,type:str]
          port: ENC[AES256_GCM,data:Gf5tcA==,iv:45X5pZPIneoZieTjNURv3TyKfOApV3gZfgwcZHezmpM=,tag:CMrdSEQ9WIjYYaFc1Q7ITQ==,type:int]
          targetPort: ENC[AES256_GCM,data:mO0kcA==,iv:DiQ42jqvjVnPcqOJ9Wq+XKIC6z2r0RY/jeJZp+C+8hk=,tag:ag1/ZTFs/5ZKlTg/2r5zuA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VFh6dnc2YnB2ZUxwMHdo
            KzZVa3VUOTY5bVliZXJZdmRjZkZrMTdHTEU0Cm9UQzVkRWJHMVh2SllYT1F4SzRI
            cUlCbThyUDh0S2llSmtHcVdXRGk1dXcKLS0tIDJnb0t1b083Um0zaE1nZlBNdk51
            eEwzUUMrOUtZMkFENmQrazFmUnY2ak0Ks77+3PPFcVLKhlgVZAWZUcYl9nJhZtUJ
            tSVHRIz7yEIMbH4iPUk98pFCW+ioK3XbhXRtVc69e+Ern8Gv+Hbspg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:YNWMOygXEC+XJlBBK4KKPFdeYGghVNaA99StHHiuyKGf6ztfy+UZTv7MzFN4z4ydvSmK8y/TMhRQs7kYSnIY/QK/Cc1BAkEytvYPsdM/MvkBSEz7PxCtX5we3ke7nQz9UFHQgX5M8OvQhDvK3GlDbTZZFQin4rPtqN00VGt5ANE=,iv:5MmSoUqcJjLtFv8zgDpRoX7msMlYZ8DYzC2qfvy6yYA=,tag:ypTDk9gk5Fr8tpcuPm/Nog==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
