apiVersion: ENC[AES256_GCM,data:L+g=,iv:a+Cmjx14HhisEL6nEZPBOZ3a7L/GiIxoJBPwdPEiZWs=,tag:eiPiL4T5HkHW97JFQchhbw==,type:str]
kind: ENC[AES256_GCM,data:ekvwaF3o6Dt7FT6UBXPM11HgcTfr,iv:ZXtGp0KFqFUiTEPwMfvuJLeo8pFXaI4bDM9jeqVkuMg=,tag:+IknMHt5eg3yV5HcMp+j9w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/y9+N5U18IH9++OHDA==,iv:HGCqU9DRjNPY6SkKHksk+7cwwI/zg46wjzaTTs6hSN8=,tag:WaNFEocGr/ZyO4LIznbj0A==,type:str]
    namespace: ENC[AES256_GCM,data:/mhez1Y=,iv:hfEz1Fl5JCAL9K3UyjCXRHhcsGvSH0zfxAWPzGo1zcw=,tag:m7GA0Rw0BlhcIOFeR2QZdQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:sluT+fXpBLCu1yHqzw==,iv:ZCLCrakyme7iO+2mmkJL2qNiO0j42Cz/jwnCYdtVxD8=,tag:GnygPMVn9tWekOeAFaGUlQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:HGqo,iv:Pee0EE/16WiWrWLDBh3l3xQcgzsCJa3gPCHZLU5nIms=,tag:5dwnXYMoVfqgOHfak2PWgw==,type:str]
    storageClassName: ENC[AES256_GCM,data:yazrCZcMbBk=,iv:2gb9Res5GsNt7G2LlQLGK7ebHGqhTj77eY/wQs5eaGE=,tag:bE5iRvoRSHXe5fvI/Sdzqg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURm9rdHJuTTZCdTIxM0Rj
            emRnanAxdXBqVE9kS1BmRUlPWGtnLzZkR1M0ClpqNjBIdm10ZWN5V2dYYkNTa1hL
            bnROTk04Tnh5QVo0bEpoMGZFRU1LVUkKLS0tIEN0ekpOc2xpNERJc3NnRG5JMm13
            SlVadXlzdU5FMUk4SS81OGxMdm1yZGsKu+vxEH+rqhsy2Fdp5hXrVc9QGhUFvPtv
            OvNFBMEd2q6O2hIyBV7lS3qZ8UYWJx/iv/oVZhOlarvnmwc3AHWyVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T05:01:00Z"
    mac: ENC[AES256_GCM,data:n+InhIX0J0bY/2M56hUWAfbR8AvKnLsb1xs+b24zG1JbhuodbQmMmYSdeICo4oAYKBHuc7m1pRqKsiVWoPkGl6Tz8q6Dpo+CSTYD7e3uC/27P/fB/lwI1Mxek8HcEkbRkfXZTRINUyLNe+DDH5+wQhpxAiPCx7WJe8TtCXnAPNA=,iv:JbwbK4XiJnZxXXUPq5qjBunNizqsphj1A6DCJjNZb1w=,tag:zqSghvVmdGci847W9QJTOw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:atWi4s2+fQ==,iv:chs1KvYD+BP5Gwikq8fezitcIS/iDTZ6vOnOndH9oKw=,tag:qHkZbltWR21iXZ1azMDQUg==,type:str]
kind: ENC[AES256_GCM,data:23E70TkN1k0U4Q==,iv:QFsvmWWVY45ZwlOPP4t5CHx3bPkejQfGi0+3v2KT9fw=,tag:3MKL0ieD+UAQWkhSFxqvrw==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:GhisIb4v,iv:t3m34R6gnK0BKDLkJckY69l9iygkBiZYMxQQ9/5oKUU=,tag:i5lMiQk95WuH7PoD66HNCw==,type:str]
    name: ENC[AES256_GCM,data:An74ouAH,iv:+54Nv/oL2RufYCbcaL+5pzBrh6L5WOmuxUhlqLIJVSE=,tag:VzjuoRpppgUWH2MNQq1YTg==,type:str]
    namespace: ENC[AES256_GCM,data:/mhez1Y=,iv:hfEz1Fl5JCAL9K3UyjCXRHhcsGvSH0zfxAWPzGo1zcw=,tag:m7GA0Rw0BlhcIOFeR2QZdQ==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:Vw==,iv:JT7+ynoDORLO3Mf7MSMhMGyzuxJiTKmPpLmWYikK0Bw=,tag:F8Vh6uzVgLeyWwtGuyxmdQ==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:El9kb4IW,iv:20Uq8AqlZgAs1WlQYdbtn1Xd0uSa10RF8yu4KZ7jV5Q=,tag:mKi63b8prkew4GMGqvtGOw==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:jG4IqYZb,iv:QY+uAag6iYCnZ+lMzB1sToixIgW4Zlgk13/GiCXSGss=,tag:w/b8fbJXrNGtNs3A3Eh6iA==,type:str]
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: ENC[AES256_GCM,data:Bp14YiQJRSsqKOEbh0aBLh3umh10mg==,iv:ZhB8aJ8Mtd09SSi/Eer9lJFRgtWcIcA922xcIGdm6OM=,tag:F95I73TKFRV8e+GXLKnUEA==,type:str]
                                  operator: ENC[AES256_GCM,data:XMgOQrI=,iv:KPq/q7PLyGnXn7QWim5RDY0xrPGErVanS20rNdpVhvs=,tag:AtCxry4BVtUJpUhSw8mOmg==,type:str]
                                  values:
                                    - ENC[AES256_GCM,data:eoQ15eSPTm2o9E1N,iv:N4DcOg4IoNc43qLle6lj9SC/fVZzE+Fm3REDI90SBbI=,tag:iJQxpw+Jx6ETr3scr0YMjA==,type:str]
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:OsIORA==,iv:DxD3IMQcNziOjDKFpAIO+szKv6dz4PuvApb8JOyuCF4=,tag:gnf/Pe85LHetKefW7IQ95A==,type:str]
                      value: ENC[AES256_GCM,data:RY091A==,iv:+VmW9BPjH1MOiuE76d6XbDyjqTUxscFxoYwoWZVKTdo=,tag:ac0yLd5JbgNlhAP+4FQJ1Q==,type:str]
                    - name: ENC[AES256_GCM,data:RjQS6Q==,iv:r6SikcxIKOLl73wn/bDDPtFL7LswOJad+gdloBKrMwU=,tag:5jTMsYNor/66KLp/syGOHA==,type:str]
                      value: ENC[AES256_GCM,data:jE3I,iv:VuxNxAG42xpWPWVApd77/awEGeIOGVMSemSXiKjqrYU=,tag:c60bx5swVgAfBTWIZLrhYg==,type:str]
                    - name: ENC[AES256_GCM,data:+BY=,iv:fUCeXn1WGMaiEBQF0HxPO3ZikLW2NU/0VsM9+KoVjnY=,tag:xnPZy1x4hStWzUWEKWrQpw==,type:str]
                      value: ENC[AES256_GCM,data:u2b6ePOofWOnIi1DSDLPtA==,iv:KJMxxy/lqTX0bwVPtS3KgdobPm8BSBbqV1joPcmknNE=,tag:F3mTs9GRi/EurTIcjVZ3lw==,type:str]
                    - name: ENC[AES256_GCM,data:+HKx0ZPLNpEWFg==,iv:jLibtqzRpXzXf9u2rxqZtSQ8mqkSKQ60wMn/9YODX2g=,tag:vJfnml6wYiAOTWjj7vZLLA==,type:str]
                      value: ENC[AES256_GCM,data:wD1go9ON+GieeTeYLi3D8EYNrf6uq/etIphDQn8IfqGpwja8PMOOs4K2/lJ5,iv:/8P3VxX2c2t4jsejrTBgKR6WOGWhMRrnuAUz6f/u+IM=,tag:GWxMYnSJSyj5UAu6gIz9xQ==,type:str]
                    - name: ENC[AES256_GCM,data:aqQoMH8HYtE1YAI=,iv:qJgiFBNWaABq5g7pS2vyr4PulmN1K/65YBnjGU8bK2E=,tag:6Eg6UiMyCoAWbZPB8zV5cA==,type:str]
                      value: ENC[AES256_GCM,data:+7LmNwA1T8iPousfPzFlIp88cUIkwUyCNSd47l0N2+YvgiCZAZDGAwtCFPdM,iv:WKByOsjN7hGNT7zgJ38WVEYtGVFKBKUsRxb1ahbEUXs=,tag:eJjclnkgjUAAbv9AkklEnA==,type:str]
                    - name: ENC[AES256_GCM,data:+nkBt97Z/isg5g==,iv:jH6/oX15QHdeeCcxcQdmquJizZhYOBHkOXtnm0IYkLs=,tag:FGu4sObDdjoW9oiKp+whLw==,type:str]
                      value: ENC[AES256_GCM,data:3ZjtcAcig96REvp8joVN0HkMr/gPCoD3vwplz5Jtzof0O+frsHApUrZ0v7am,iv:fqEi7C0K+N9mtqW7hp+Gpcs6/fz3Dso9IlKIgRG/JA8=,tag:+8qRCokNRgJNIXeje27rTw==,type:str]
                    - name: ENC[AES256_GCM,data:5IZ0B54FEvcn4Vk=,iv:UhnevZ/EridS1ojAI6ScQR5SNxTzgLC/DEyYERGGL1I=,tag:U8RXXZqaGqHF72Acjg4d9Q==,type:str]
                      value: ENC[AES256_GCM,data:vxiM7K6m6tlCwzdvw4ehS6VZrR5lTP1B9co2rPqfMaSo7M5Owv+tdbmdhqPg,iv:PsKrMo3F77QDqbfqWnOFBdSrfNwTb8zL7kgHL6KDTj4=,tag:1g6kGVXBbgUc4N6ICDn/+w==,type:str]
                    - name: ENC[AES256_GCM,data:5Te47glrDFo=,iv:dJq3gNRmWbZWTomLhWAgSCjXY5+9WH94wbDvDaOcaxs=,tag:sm0JJz2wJ9C+CVcfmXMcdA==,type:str]
                      value: ENC[AES256_GCM,data:unWvdESKRb+g9Slax9Cv5v80nvfCYG7/CvKmB2GlUEg1PF8piC3XHxZ45mpPbA2z7+mV3yixhAwXeNCQbSgbz0m/uKw+,iv:NB8gxnHZ9/5H01RUMy7Ez4r/3npIpeRauTa2MkkyDZE=,tag:NsP4gK0PeOUTFiR1BtmWNg==,type:str]
                    - name: ENC[AES256_GCM,data:WyIpazU0RjI=,iv:KIvIu+QnTmIaIo1CxhQjB/1wDaXYF+E6Miyj1qVPjjE=,tag:HrLX6sEbor6Lcx8SvSOROQ==,type:str]
                      value: ENC[AES256_GCM,data:wTY63pXZ2vR5VuYk0E5Oi8FJuCkD7LRa5m1XlD7fCC+SjwLW0HGqK4OgteDf9eRWfApLiMpvEnMOyba0AXdt2rEnXKYj,iv:idYntU5egEJe1xP87NTnM4JS6WG2/JEM5L3SMFf77gs=,tag:xxQHiYICjrSk2aW5P5IQWw==,type:str]
                  image: ENC[AES256_GCM,data:VC5zjOeRHDZl0bnwnpcgzhCdLAl2VGV/51zcAuoeSU80vIpRL7Yv,iv:rfHS7qg3gqojgIDFQKMvHlu9ju6Dnm1hInwSDXNu85U=,tag:43FU8y9WHxhVN0lvmF3E0Q==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:5w==,iv:IUDiut3E9YVK7p+9e31qLrrfrPvT6PRTpkGKFJu9XN8=,tag:Zb2AxgyCCCiNX9iJw+YvjQ==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:nmI=,iv:x4O9vBYrfWJDats0aoxi4QEf2E8l+TAzY7ZoUQoQQ3o=,tag:YmeQPVm9uJwtD7Sda4xQvg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:37Y=,iv:gNWHi2GYs5QyrPCFPsYlLDJr78wNk/Ks694vKR90f+Y=,tag:GGolhd/5h+zOfPKCqbvMsA==,type:int]
                    tcpSocket:
                        port: ENC[AES256_GCM,data:8FhH0g==,iv:R2icTMLxYBY+/toBWiS8L+lHj+HrOBdRpoxO+gT70EM=,tag:+pK6AnC8yYTgyQArGnKx+w==,type:int]
                  name: ENC[AES256_GCM,data:T60VeomE,iv:EdUyKlJxDUQAlGpD+7b9t1/nvqWeOL1XeShkBPKYXvA=,tag:GFJkTmTJcjgnb6RLeJfBWw==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:Xk9MYQ==,iv:VWYpZx7onERsSDWoa70BltMbNi4B+XyNDXjuGzotby4=,tag:+0R0hNDGKxE/DKVf3gU5ww==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:oA==,iv:rEcZ3cFvhfALPHntthVOaPDiZeW4V915xodO9fTBzgs=,tag:zNhysshrmAvltHO4QtIn9Q==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:Thg=,iv:1nB3OJ4UcAU4omIqoZz4EnomZMtJHYwqLJHEugsMLIQ=,tag:6W2SS+3M+++jEPKuR+M2Uw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:zy8=,iv:VcNxdnVCIa6ssOqnZLuQ/n3DhA8tjzSgrftki+i5ldY=,tag:LOYbWezg0M/+BMDddeg2Nw==,type:int]
                    tcpSocket:
                        port: ENC[AES256_GCM,data:tuFPdg==,iv:b9r734Bm++D2fYP2L2mZxJ56asS4zkWuat8u8QCFJRk=,tag:QAlEeKAFmATXBcB+FtBDvQ==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:xA==,iv:q4A25wmrFq4HcK6SXQ4ZiFmUgyrClYapaaFN2Ps26jE=,tag:PJuSfVxj37NS3BXQT81wIQ==,type:str]
                        memory: ENC[AES256_GCM,data:VaxgqpI=,iv:lfJFxiRETz/7DFwkVex2LLf6Ib6WvDGY7tTV+S96fcs=,tag:Km1JVisoXfkqcDME8iS74Q==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:ihci,iv:HiRroFstDtR0QVzeYPjMUMdAIrtJiEIyU1Jf7SpIOdo=,tag:124HjqSbXccxqd1rJG/YWQ==,type:str]
                        memory: ENC[AES256_GCM,data:fuT5xqk=,iv:sdrqhPx4CttFiXvyaqkLQseqbZ123vDrlkf2KvRFARI=,tag:CLgqf3fKslzDmeCyXmMUYg==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:zOSCMP/ZRQ==,iv:dLMB+JdGOuhS7EOT1JGzeJtVNwCqr+oLQuSvzbusK8U=,tag:d40T1UC6cC+uFPAjyGDtpA==,type:str]
                      name: ENC[AES256_GCM,data:delOOqYL,iv:jz88+E5m0Z4oUAZO21TYSxaa5lJO+Z8X0l5wUXTXAWs=,tag:IYH/adifVefFdjPYW9zofw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:a+w3xYq6rA==,iv:RaPPsWTmaOtPvwXRHu+1jUA3r8lOHWsk7WWbG/oywjw=,tag:v9HxtMZXxTCh1w0vY5bcOw==,type:str]
                      name: ENC[AES256_GCM,data:gc5SO3U=,iv:80+iLMBk2+EfiSyvWivFBN3yR7Wjy9WiM58tzZ6Qj/Q=,tag:nOPH0JqNGH0AEd76+QjEHA==,type:str]
                      subPath: ENC[AES256_GCM,data:jgHNu6gv,iv:v3uHgSTfG3v/q/hxmVOCpIXfw153cYQATfk1vBygJTQ=,tag:WAwMBdgPG4NplbRNIDURww==,type:str]
                    - mountPath: ENC[AES256_GCM,data:SajC,iv:xxijFqXRYeat3kQCoK126bi9XjcQ6vsBKe/RN3lxCx8=,tag:UUq8VsT0FDXsGiG8IUeBjQ==,type:str]
                      name: ENC[AES256_GCM,data:gc5SO3U=,iv:80+iLMBk2+EfiSyvWivFBN3yR7Wjy9WiM58tzZ6Qj/Q=,tag:nOPH0JqNGH0AEd76+QjEHA==,type:str]
                      subPath: ENC[AES256_GCM,data:1cnuagkhqHY=,iv:8lOB6SD8v4uaEpGbzy2/phrtjjLK+UwBLeceVTmqBGs=,tag:I5BADD1eQmiIBIVD5W+6NA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:squ9Kqa2NxWg,iv:abDlumnOhXxlJ1BPRG2pnl67WU8+FDmGz83DgYd5aUI=,tag:6/F/HdD3X9BQs7MhtR33Ow==,type:str]
                      name: ENC[AES256_GCM,data:Yq8bIC1Ukv+y,iv:CdV3zYzuit314P7Uc7DdIcfUy1JZ55utg+fED+JweoM=,tag:DeNRtGZFrJ5kqa2Hur6e8w==,type:str]
                      subPath: ENC[AES256_GCM,data:YIGD6HBRETE=,iv:XM2EC3fYg/kNoR1PTqCBfZiF8F9ww5S9HSlqlSE+YVY=,tag:iRLOiaLfWb/M/yteQPUwqA==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:b6gumss=,iv:TSkUg9+HAYd3TpwSSBuEekPRkiqbxBwhx41kzEX/sc4=,tag:S5pV+YnraSSGuKvfUBbb+g==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:HxQ+Huxu,iv:ww1KgpWuVwbBaTnh04UF6o8oHMg4D59MyrT7mCZWyao=,tag:CobOYv3KkSv3Mr1JrTY2iw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:1lyLVu9+k1ftwyBY2g==,iv:tDGUaeXFwUwCjDByKFlh7KnC46e1TERzQTYkbVOSxLY=,tag:geo07BxdmLh9D+YFCulbgQ==,type:str]
                - name: ENC[AES256_GCM,data:RTsFxXs=,iv:bOYWkBCu8QJNfjKQhs7kv39/XKgr/Cfdn9bm6ZYPysI=,tag:LVG2BDIOt56/zO0nnpcs6g==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:qSq1IFV5SY0brdVlatWQWw==,iv:VQ/9Iwsw3ct3pz1q+v8z822DysWaDFGppZJVLSWiQq0=,tag:Nk3PdamXY3PqRVuoNB0dhg==,type:str]
                - name: ENC[AES256_GCM,data:FlW+/570n+xA,iv:ly/RFieO/Tb7SH4okB53whKZNsY5vCGWyM6Wfj4suTo=,tag:us28MNOLrI/5eyUeln8miQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:OIIIxbtXPuErBl3IgqrAoNulthc=,iv:TQzZPA6IqT9jHd9E/UdGiQIWXAjpBEWrAzrgltU1GLc=,tag:BpmfqwYvReNgMQoduVHntQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURm9rdHJuTTZCdTIxM0Rj
            emRnanAxdXBqVE9kS1BmRUlPWGtnLzZkR1M0ClpqNjBIdm10ZWN5V2dYYkNTa1hL
            bnROTk04Tnh5QVo0bEpoMGZFRU1LVUkKLS0tIEN0ekpOc2xpNERJc3NnRG5JMm13
            SlVadXlzdU5FMUk4SS81OGxMdm1yZGsKu+vxEH+rqhsy2Fdp5hXrVc9QGhUFvPtv
            OvNFBMEd2q6O2hIyBV7lS3qZ8UYWJx/iv/oVZhOlarvnmwc3AHWyVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T05:01:00Z"
    mac: ENC[AES256_GCM,data:n+InhIX0J0bY/2M56hUWAfbR8AvKnLsb1xs+b24zG1JbhuodbQmMmYSdeICo4oAYKBHuc7m1pRqKsiVWoPkGl6Tz8q6Dpo+CSTYD7e3uC/27P/fB/lwI1Mxek8HcEkbRkfXZTRINUyLNe+DDH5+wQhpxAiPCx7WJe8TtCXnAPNA=,iv:JbwbK4XiJnZxXXUPq5qjBunNizqsphj1A6DCJjNZb1w=,tag:zqSghvVmdGci847W9QJTOw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:L+g=,iv:a+Cmjx14HhisEL6nEZPBOZ3a7L/GiIxoJBPwdPEiZWs=,tag:eiPiL4T5HkHW97JFQchhbw==,type:str]
kind: ENC[AES256_GCM,data:V1VLXksc7Q==,iv:LstbRUygKJzLLu6aRiKQ7kJEmfTJKI3YaUirnArT9sA=,tag:2aoD8tsgITIvJd8+Hs5+8A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:An74ouAH,iv:+54Nv/oL2RufYCbcaL+5pzBrh6L5WOmuxUhlqLIJVSE=,tag:VzjuoRpppgUWH2MNQq1YTg==,type:str]
    namespace: ENC[AES256_GCM,data:/mhez1Y=,iv:hfEz1Fl5JCAL9K3UyjCXRHhcsGvSH0zfxAWPzGo1zcw=,tag:m7GA0Rw0BlhcIOFeR2QZdQ==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:GKBCKQ==,iv:HbhAVyW9q47GRtxizLYq6fOxCUZnViwzSEjurwmDBqg=,tag:t7HRvyrKFmAqO7yPpZg2Kw==,type:str]
          port: ENC[AES256_GCM,data:OkoSIA==,iv:OZ/g0JKZGLO6EhtRdZDypvbf7mytHhlPk5rmlYJgD8c=,tag:gJ74u9vhyib7UdPNNEAlzg==,type:int]
          targetPort: ENC[AES256_GCM,data:4wzUxg==,iv:0AtwLu0mn5l3yzvm6yBjHCXZKYpGI/LLI0408uH9u5Y=,tag:tukYbs8sFFnqnf430TA1YQ==,type:int]
    selector:
        app: ENC[AES256_GCM,data:XHGGE55l,iv:fOx5LItVmqeiIzRLSIAtehQLp/+MSN24BZ1jpSU5sro=,tag:sx1CDJ2NjDek0mgZvD6HRA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURm9rdHJuTTZCdTIxM0Rj
            emRnanAxdXBqVE9kS1BmRUlPWGtnLzZkR1M0ClpqNjBIdm10ZWN5V2dYYkNTa1hL
            bnROTk04Tnh5QVo0bEpoMGZFRU1LVUkKLS0tIEN0ekpOc2xpNERJc3NnRG5JMm13
            SlVadXlzdU5FMUk4SS81OGxMdm1yZGsKu+vxEH+rqhsy2Fdp5hXrVc9QGhUFvPtv
            OvNFBMEd2q6O2hIyBV7lS3qZ8UYWJx/iv/oVZhOlarvnmwc3AHWyVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T05:01:00Z"
    mac: ENC[AES256_GCM,data:n+InhIX0J0bY/2M56hUWAfbR8AvKnLsb1xs+b24zG1JbhuodbQmMmYSdeICo4oAYKBHuc7m1pRqKsiVWoPkGl6Tz8q6Dpo+CSTYD7e3uC/27P/fB/lwI1Mxek8HcEkbRkfXZTRINUyLNe+DDH5+wQhpxAiPCx7WJe8TtCXnAPNA=,iv:JbwbK4XiJnZxXXUPq5qjBunNizqsphj1A6DCJjNZb1w=,tag:zqSghvVmdGci847W9QJTOw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
