apiVersion: ENC[AES256_GCM,data:Q+I=,iv:irC1PD0VstZUus7zJbRIv7f3F7ubI7aFtWcfjUMmGs4=,tag:pkgFjbDT+SWVYP59LeHehQ==,type:str]
kind: ENC[AES256_GCM,data:p2UYXEHYwxZIQcR4f8dix4PjkBHp,iv:54sC0ZAKlLeO7KoEwDAYb+lYY/GYgHRaLl/1COkMRck=,tag:da9hpS/hZZ48enPYf94AJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wxG3qxL+FuBXVpaQTuFc,iv:SN2Aocj8NXekxLARggY3hczs3fXscok7EzQqB88TyHk=,tag:ioZmyTknNhVAcXp/GxkjLg==,type:str]
    namespace: ENC[AES256_GCM,data:ZrVw/Ag=,iv:gZz7R5cpnZAx0ATRYEXvrarX0Fh3upAlMPPVVUkAnJ8=,tag:xfpWRSRAS5n5RWfVYWYKzA==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:5UYimSpvSipBRTpOVA==,iv:HoTsq/kGpTbJJbOWusAFr1GzNvOm9FpaVnXTPYs2Jhs=,tag:6//ZpKa2Re/3qL8yquafMQ==,type:str]
    storageClassName: ENC[AES256_GCM,data:9A3SYWzcg4E=,iv:FPbz+Gq9xpXzt14bLbwyquoV+3j5sFC4WlhmdK3wnIU=,tag:Xa7k7ZQ8owIG51sxeFIZ/w==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:sNmH,iv:i4+WjrXPYHCjwBQSTeufT6nl7AJJsuMivucOMZDzfr4=,tag:YKUabgFnibMOSM5DW1UhRQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL3NLTTFrd3pnd2tJMG9K
            V3dySW9PSGQ3Y1ZNNFoxZkNuTXB1TjdNZ1VNCmRqZFJ4QWVrazg0M0VjYmZKZVlS
            WDg0SmRDejRDeTFlOHFXb0hNdXhxY2cKLS0tIDk1QWRDYjkwMHpJcm5aSlV4cGVU
            SkVocjd5M3Z6NTVuT1Fpa2w2K1JSYXMKOrYSL4lqoq1Zd7dQgfUzaDAuOPXRYdYI
            ixweziq8fNQMwplOIMrXINFZboIGuiE6fOrbVZ2ke93EoR2Di0oNKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:WMs3owB0162/l2o8afg71BJdinYvkkIKbytMcwihtNSSdkLTUT1dcHX98CQlDYCYnV3AT98Q9f57P1skMuleJ5p3vmln9OJ3a48vze7P1JTMoRUP+bWxxHR8sM8i4sdtLp8x6l1pcNd637NGYatkEKEMk26d0Kp4gHiJ2Uvejf4=,iv:KpD4YTvL1TJlSQUOgPjAjtjsgbAmA3bYJqb7lAeGWgk=,tag:lD3Lk6RQj95P0tIwL4SjxQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:cAufV6J5Lg==,iv:O7ZiPIVkPqWiO+MTBLXZ+rC+MbZTByJ5FYnl9xuSovI=,tag:A7xPKu/1DLdJooTioJwCHA==,type:str]
kind: ENC[AES256_GCM,data:BUz4mD20lMwYnA==,iv:k1zja7dQByQjP/FPkRlmtONpbPKIdaKqHCycbFYYzpc=,tag:X2P5026quAA05ruWJDDhbg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1POnz8cO3rA=,iv:ZEb7TLt5Z4AHykyn3Xc+1wTgBslhv5KBj6DG9/8bpnk=,tag:oNiQ0jo+2Ch0998pdKEcVA==,type:str]
    namespace: ENC[AES256_GCM,data:SafNlqA=,iv:tBiu5LHgBA5KG2yRCoZD9Z82hmJ7N4yJp7YpMjAZI58=,tag:VJiJoKZuMAmTwueowCoEJw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:arNMk/a0bS8=,iv:Ea27e6osHjO6i7RTl0/jf3ItaPMntF//uWs7PpEq5BY=,tag:4qJjlH/0HhV/XLsakFcAJg==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:IA==,iv:GQYMAwixOB7EMZOXbOoMfrfaYg12Y7qDXCftiUOQq9M=,tag:VuXSzZjU8ppchfzbiG8TKg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:5l+9FRQIpy8=,iv:2liMdVYLmErjGXWrS4Affg6sJB5uDgG+vpzG9k5EyJA=,tag:wYN6mUrh2z/BH6peYj68Hw==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:5xawW1+PTDc=,iv:5uXeY/QOFz9jR6z8TAWm1VbcEFRsy0ZXyaVP/Y0nooc=,tag:NJnS531tz7tawOD6xHj+DQ==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:txAw3LY=,iv:f92TXSvSbNk1oD2q4OQIwhB3iw/cOfxswXyBxEWrUz0=,tag:mOADUM7CZtGoL7Ncw0381A==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:okUoYPxf4po=,iv:bjeXvtK10/LGYmnU2KnOVgtvmivFHTUJJy0bleAAyc4=,tag:xQp5AFZ8LAaxm6G37qiqvw==,type:str]
                  image: ENC[AES256_GCM,data:aNKfEWoic9+8RA58QdCkJR2PIsxFfM27ujqiWe5s40oow+XXtorno5YF3hgm,iv:sGEB1cyRUAt9+ILp7enFspUXu3p/35e5dIZiYf07JEg=,tag:UYS2Rs8eIjiG5exhnMdo8A==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:60ll7Q==,iv:o8Noeoom1nWNW5Nl8Kg7vrNC+EY7fQAUAf8hdnah3ZY=,tag:xGY982Xbevm2+U63uzG2Iw==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:OhjNLA==,iv:JJLqYbB3ZX3WVkdf+dX5v/zf/ANcwRQTAzNda3hZBv8=,tag:jAr2W2XPm9Mc4n2SZ9nguA==,type:str]
                      value: ENC[AES256_GCM,data:K3k8BQ==,iv:DkuWl1BM+xuNDXlFsK+qZPn6LT7haIjm1NRfKGiei+k=,tag:nXQ528GKYzAybXJZGKLFrw==,type:str]
                    - name: ENC[AES256_GCM,data:ctzJ5g==,iv:vtdeLXpaYbycvbbL6IcAQR6EwiedqqVC1VYaYhf7eOc=,tag:lEEnNbq2hoOs5m2r6zPH1g==,type:str]
                      value: ENC[AES256_GCM,data:VK77,iv:zxQvKp+Rp4uGCwXYHv4mhT+kiCoe1h9JLqxGZ1tk+hg=,tag:8+JzKJZy4Uf4XnywLmArmQ==,type:str]
                    - name: ENC[AES256_GCM,data:eYk=,iv:pxL3EuufFi0+F1JrcDHdYwiZxya5uArWbijcBh8FzHE=,tag:QHLuFuiVZI8W9LCpdjhxJw==,type:str]
                      value: ENC[AES256_GCM,data:TjYVOSPyltNPWUHx7mCwgw==,iv:xZpAjLjpHSyQmKOipeT3rA+di2/A2CvEHo4OCpdpZBo=,tag:gomEt+OhUZO3bIYjiOLLfw==,type:str]
                    - name: ENC[AES256_GCM,data:NwEc10hrG6OzeA==,iv:ujOsmadMUY0YMe23K7qfY7At/71cfD+5L2pbfyyvR3s=,tag:3r6WnLdrHRRI11uyqYXclg==,type:str]
                      value: ENC[AES256_GCM,data:2BY7+e5AHTKKkKhfl9rtTpYp9JA8,iv:cbSa0wH+ygKEuKtPJKaGchJebyELBBB2HaMZPrPh4Eg=,tag:RBZ1iF5dXFMO8ULDwb3WlQ==,type:str]
                    - name: ENC[AES256_GCM,data:oDDa+UryAbL9jpM=,iv:Yols2UaG5SaVdSox628WIe8ksWz9hLJRxv4p+31qQQc=,tag:o+nNOo4XjOtV9/kHLxKVPw==,type:str]
                      value: ENC[AES256_GCM,data:+uokzlYLHoGbtLaxPIbTrgO+1Qo3,iv:FIJQ9xwKOvR+lKKAEiG1XNH/SXDtvYCYfAlHzx7AwiQ=,tag:elADoJqP3iGfxWVw1BKcpg==,type:str]
                    - name: ENC[AES256_GCM,data:oMo19MKAquI=,iv:XIXe4bA3BmW4BhD7i76HlpCsC9wQbQpNWgxwzGDtkZY=,tag:XfRXuFBg5UU2grA3ITpYuw==,type:str]
                      value: ENC[AES256_GCM,data:m6j/HqUlPep2mE0UjUM6kl+S/xXvrw+QOF4uToNR0ZO8JgvdOvprcNlz/us74mTRMZ8WiJzj9XXJU330hG0x5tq+o8xdk8+Y4GxbZXI92bNd6WXmol5/8rHFC4KIwpcsZpgQ,iv:eFbZAgp5hHkqyMdmRUgqkphQ5WNiWsbGDjW3RvJtLBo=,tag:S9gXrEO4XJCDJW3BQ/QLsg==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:rdjDP80X,iv:+yxy5GGjx8p+EVNyB937Q8g9ODbGDYBHSmMdZFwY2iQ=,tag:cEAjts1OB08Y1+kuHPfhQQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:kWXxrYzIaA==,iv:5lnCQTu+DpHyUn+tJcRmR03RBlJh+vlkZXglTiB/+XM=,tag:omPGtBYVhh30FycPbtSAfA==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:oWO/,iv:4PrKbQJPSq620Q5Lfj184KN++X2c9nJmly6EP6AUd1w=,tag:0+SanDSxAhbi76pnqPawuw==,type:str]
                        memory: ENC[AES256_GCM,data:Grzei8o=,iv:1J1WjP3YlhfiSRi5ctVScscB5ILCNDCCzL1/uWiZlW0=,tag:nxlwbThUD/Whg6n6cy51mg==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:bw==,iv:0LTbtAi3SEVYFaZwePJYBOI/Xl4bu1wqUPFuPZytKQk=,tag:A7rHct0IwJowk8S6147V7w==,type:str]
                        memory: ENC[AES256_GCM,data:Nd4VTTQ=,iv:0m/2ERCPCnJI9HSjTBfrlALaNLFsCMnfHewi+EJh46w=,tag:O7LiBhK0ZtPOR+E5DNa27Q==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:/JRVuUY=,iv:DPD8UBeGpl3350EUA3IVV6wSC/l7+PgbkWRDQqaveDU=,tag:vCDNV/cN4yrLMzb2YJ7Z5g==,type:str]
                        port: ENC[AES256_GCM,data:sOazgQ==,iv:Sjzl4le4qe1hhzIiRkBEF3+ayHO6E6BJ1Dm4Bpc61q8=,tag:rhuR8Fw+wQr0YAT0kBvgwA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:ctA=,iv:vyEw9Ukpu4Tq0fgzbVIe2O5KLkU6glQP99/3QnYfVF0=,tag:+zCRhz+dN9BTYhwC7a9+AQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:QlQ=,iv:7oVDbF26oHu8qiAN/7tL+hM1IIAMcj2bE8YRp3DwB2c=,tag:fKlEv4TEo8zdF7A6jVQ8FA==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:ZQ==,iv:RkgT/YNm+BK7VpubN4o7zkOPMSLZpVMyuMKDW25Uy2o=,tag:tay/YKlhNsyqRo9gCdiX7A==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:UQ2Zt2Q=,iv:JXuP6jpnHQkCCio0kclLfz/YNdIUDkeBqmudngWPP2c=,tag:jQBo67JFBZzgejpQePIIRQ==,type:str]
                        port: ENC[AES256_GCM,data:7Y76dA==,iv:B4PuVVCRQDL36gu+Vp6O15b/HtfJzAiAP41wepRc2o4=,tag:vJ5uxQtDDsIbBSQBzjtleA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:cUo=,iv:gpYRIjI0fCXBqUKJJnCywpVvqyHc0AUh9L9fyDiFXBo=,tag:UHiERWfeicmIC/YYyA6Mqg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:HVw=,iv:jLBE/lZOpwbaSbHAPnNAB9NECtXU1sHMq+Vu795htOg=,tag:TK9YtPl2/SAS/pn5qrdyQQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:0w==,iv:pLrb0kqU2cgOKcrslwAce882v8lQqyY4YNg0fZ+Z29E=,tag:yayWosaVScvN4s2RNN+rjQ==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:JEO27t1r,iv:9T1ON3bEjr4GnkCu+GIx/97ITAqciaGfUPsivSr8eMg=,tag:KEJTr6XkOI5nm+C7oV7GAQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:GoG2+fwPP0kKp0/in05W,iv:ylkzpU6LotdbgFjbl0XIeOgHPeCVnkS9/vEUQBpOYfs=,tag:8C00fTADr4UX1CbjppfEwQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL3NLTTFrd3pnd2tJMG9K
            V3dySW9PSGQ3Y1ZNNFoxZkNuTXB1TjdNZ1VNCmRqZFJ4QWVrazg0M0VjYmZKZVlS
            WDg0SmRDejRDeTFlOHFXb0hNdXhxY2cKLS0tIDk1QWRDYjkwMHpJcm5aSlV4cGVU
            SkVocjd5M3Z6NTVuT1Fpa2w2K1JSYXMKOrYSL4lqoq1Zd7dQgfUzaDAuOPXRYdYI
            ixweziq8fNQMwplOIMrXINFZboIGuiE6fOrbVZ2ke93EoR2Di0oNKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:WMs3owB0162/l2o8afg71BJdinYvkkIKbytMcwihtNSSdkLTUT1dcHX98CQlDYCYnV3AT98Q9f57P1skMuleJ5p3vmln9OJ3a48vze7P1JTMoRUP+bWxxHR8sM8i4sdtLp8x6l1pcNd637NGYatkEKEMk26d0Kp4gHiJ2Uvejf4=,iv:KpD4YTvL1TJlSQUOgPjAjtjsgbAmA3bYJqb7lAeGWgk=,tag:lD3Lk6RQj95P0tIwL4SjxQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:J6A=,iv:PhICvFflAyWnaRTVs/wP1PECraw1sjAxyleMqndjYjM=,tag:+Op7sng9y2apRQX2xYovaw==,type:str]
kind: ENC[AES256_GCM,data:+RB+T0JPng==,iv:H8Kx3uwSy0FCpuaQwF1eER+NGVP5+Sol0j9MFKIP2/4=,tag:6Qg37zh00D4TuycRc4xY3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LHBnuQ/qQAU=,iv:gqRatUYDClusbDMyQLjPJ/xAK/sz0Vj/RQvjoXIOI/I=,tag:XEDm0F7zo/pmw5obatvi1Q==,type:str]
    namespace: ENC[AES256_GCM,data:041oy5U=,iv:gRxAtdoxWofJHcevKU4NQGn1aj1fXtnprJtTBggNyek=,tag:in98tF0LHc9z1XqlYLg5hQ==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:6uM60v0v5ik=,iv:5YK038diTGcbypIuLY1g+KBS7zdcLnl4wCbqsAyX6nY=,tag:bgXL1O5qX5B8WqdVoo16EA==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:VCD1Pw==,iv:ZonuaQ1D7S/Icg+HAw5AdyqeqS8FVaau0rtwv0QAIIM=,tag:Hh40Ct70F6EhY6vQav12GA==,type:str]
          port: ENC[AES256_GCM,data:TEN70w==,iv:K+ttQZdgOYNMuIfFLthUPbdX1gV7cWj8ceH/m3lJXtU=,tag:Dc5oRKa2zZfP5fWiporv+Q==,type:int]
          targetPort: ENC[AES256_GCM,data:GuL/HA==,iv:VmSzuLnqPivctvF9vhWBQBTrZHs44cNy4UOhli7yI2s=,tag:ZpQSn8ryHrg4rUmnRtNvQA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL3NLTTFrd3pnd2tJMG9K
            V3dySW9PSGQ3Y1ZNNFoxZkNuTXB1TjdNZ1VNCmRqZFJ4QWVrazg0M0VjYmZKZVlS
            WDg0SmRDejRDeTFlOHFXb0hNdXhxY2cKLS0tIDk1QWRDYjkwMHpJcm5aSlV4cGVU
            SkVocjd5M3Z6NTVuT1Fpa2w2K1JSYXMKOrYSL4lqoq1Zd7dQgfUzaDAuOPXRYdYI
            ixweziq8fNQMwplOIMrXINFZboIGuiE6fOrbVZ2ke93EoR2Di0oNKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:01Z"
    mac: ENC[AES256_GCM,data:WMs3owB0162/l2o8afg71BJdinYvkkIKbytMcwihtNSSdkLTUT1dcHX98CQlDYCYnV3AT98Q9f57P1skMuleJ5p3vmln9OJ3a48vze7P1JTMoRUP+bWxxHR8sM8i4sdtLp8x6l1pcNd637NGYatkEKEMk26d0Kp4gHiJ2Uvejf4=,iv:KpD4YTvL1TJlSQUOgPjAjtjsgbAmA3bYJqb7lAeGWgk=,tag:lD3Lk6RQj95P0tIwL4SjxQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
