apiVersion: ENC[AES256_GCM,data:NrY=,iv:xolqa5jis8EJVDml45qe32AXR2Qv0TLJ4bLH8RKCdOo=,tag:ecoJSYCT22XtHLtNelQkgQ==,type:str]
kind: ENC[AES256_GCM,data:WBCXU5uV32jYcNWmnHfIuoVxLqV2,iv:GqF/z8Euyfx73lXTl9eHnNqk9qdUiIvX8a9oVIW0BsQ=,tag:OJuDbJD7vK4RJSE4Ltzbtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kmpUs+ZvKL3JORHP3pij,iv:XlRkdDBOuDDO4NwbEc8Ya7i3SFtHsUFCY8EQHUjeu40=,tag:GPxwG/Wnbo8PTH1dxVOxPg==,type:str]
    namespace: ENC[AES256_GCM,data:dFyAbg0=,iv:+Qh40PPx4Vvdl4sgkB3o4kOl0RmcRgmfVsbAK8J4bDM=,tag:LXonia6p9lB8pYeiomzHLQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:AXiXpphfp2aeU30WeQ==,iv:ZMYyf+nhOmoFNSBm/COjxI1ltvGDipDLjOqHVHu/U/s=,tag:+vsr3Y/SAnEZN/NQhN6lcQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:IOQ8,iv:o3LT7hS/g/WKeBYP9K/kFNsgRhON7WUrz1LH1hX5qPw=,tag:M6hnxd1MS3GTnaRXc1pQMA==,type:str]
    storageClassName: ENC[AES256_GCM,data:wqs0NWopFW8=,iv:+q7bniuUE05GxLUhZlvfUBMcSGGKc0RQ2j7OpLNVu+w=,tag:g7EiHYcgCRh3poj9sErIxw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SmVkQXpIbm52OW4waUxP
            WFkyNDBMUHhrSHppMXZwQm43cHhJRGlqQlJFCnFYSjJXWkNnanExUUNEM3BSTWNx
            SUNscGRuZWE1TXVyeWV0SGU3b0FVRVUKLS0tIGtYaVhJQlVkczBiME4rcUdCa0NR
            aGtaUWZRamhRM2xJWndIcjcyZ0NNUzAKSasO3GX3rQDiRmbFX+DBh9XC+t+Yzty5
            r2pb/isP0hKV0N5/yiHuh5G/pTv5Tch3BKmOMa7rEO6K/dhMZxeu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:R0mTyP8rctrCCZACJysb8QKitnvFfvFtPTEod8H3XorEBr5OZYppYcN8bTb8e2ozNXGLSLBnkQNW9lxFlGXrTiEmcJT7ogbtrOY28cC6K+9iI+D89xI3Yw6guPYzH+Nnpz82nWVuxE9vH/34VEQ6XZbsEE0GRkvjykMuahBNRAo=,iv:LiLHiHDnefA0fTxAyBfSjhY01d5w65wA5qbBtZTJRsU=,tag:QBt6zTYsmVJNIZ80EPtgcQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:NGMiURfGHQ==,iv:nSebcwkP+Y//1pbSS6gRYJyNM0QFdfsrDv6iFulpUUQ=,tag:/SH6DaDUqXoW4tISdsduKg==,type:str]
kind: ENC[AES256_GCM,data:wQklcJ7GcSSfPQ==,iv:3PVugoZRsGahc4RO+vOL1KomXGCq3wP+gq9qHDfy91w=,tag:vYZt7sIV8yP7oNrbj0YI0g==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:Z06/H+zK7eI=,iv:3TY1pBgYSn49M9wZv/eOIG2zELf1yDG5moubIe2TYBA=,tag:JC6QP+w8ovpfPyYYic4Fng==,type:str]
    name: ENC[AES256_GCM,data:Ya5EtOStZ4g=,iv:mpo8eVQHoysCP2hfI9ZEnc2PKOnxGmAb0T8tKVPqv+c=,tag:62XZhJ2rR4PUXyU1i6vlAQ==,type:str]
    namespace: ENC[AES256_GCM,data:GBtqy4U=,iv:bxVl+a0sw78JSGk1S4k4RA8/7KrUeyR/znNDVMnu98U=,tag:J20a8WSA3u9OTalgfxQPig==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:BQ==,iv:jwEmHXRlh05Vaga95R4BljhLwa1wDahmTDsTIeO5Q9k=,tag:Np+xZ2xdJG1mipgGvJr6wg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:/L4V7M73DVc=,iv:vDB932jd6LEolIu1mwimLG50xbnq1xV94no5wvJokA4=,tag:sucQagdLQ1FJkgRit2SBzw==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:1OUTxfQX4+U=,iv:CuxBTkPQ6nzXaaHxLubOiSN8Ch37pX2KlkAzulDL4UY=,tag:w6ult0fQiCR73BK10Z9vnw==,type:str]
        spec:
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:PPq8rg==,iv:ekRmA4xDDFizFEoKnnCA2TDRjLFtOZu92vqCnNiT91A=,tag:fSbnPV7ZQEZ41tKWZu3VDA==,type:str]
                      value: ENC[AES256_GCM,data:zKg8tg==,iv:Q1rdnuc2AQ42mPl13kQvTschY2z/XZ83d1VVVQ+mrKw=,tag:4rrb+YBv8HPDoXO/OKjW7Q==,type:str]
                    - name: ENC[AES256_GCM,data:mnJ5Sw==,iv:/AfDL/WO8kq/SI89U78W5hUcZh/AvcCpBzsAjVi6jwI=,tag:tHCnIAw1V14AyBxDT3zkNQ==,type:str]
                      value: ENC[AES256_GCM,data:lnhq,iv:AS+SW1rSZYeTjfgVtGEhUhrEB6VifU7NjU9CdS2TTTw=,tag:oStE30bT54wXnW3GTJtftQ==,type:str]
                    - name: ENC[AES256_GCM,data:3pc=,iv:7Pfd5xCNBa9omjuXxMCvyciivzSH7D756bH2U8LXs3c=,tag:JoQQejJ7BdajYNdYPxvjag==,type:str]
                      value: ENC[AES256_GCM,data:W+jW0tBLEGgABfmo5hEshw==,iv:WcYWNv3OYGnq0EplCGRqEQDzuLcA5x3tJCB0skv7D+k=,tag:QkMX3BXqTLLjJi1SxVSz6Q==,type:str]
                  image: ENC[AES256_GCM,data:X6sq/mzC5WgjKz7l8dsWhnVsmyOK6R85TyJK0F636obHkZnuSvVk53iKWspN,iv:FsuUmKgfd+QAqGS+UI4+8heqF9E4/qzRaiWKYxyOIKQ=,tag:g5QbiWKnWXofEiw5jthnKw==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:DQ==,iv:hBEPrNUpgd+dV113QVuKrPFjOHCsSJ/d8qMTLFrImOo=,tag:u75EEESV7y/teEunk5W1nQ==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:uaPJc50=,iv:B5AK64MdzIZCCVhIkH6s+9vqwOjQ5ULpDFPStLNRbG0=,tag:LRgykwh6CrWraUc37yMNNA==,type:str]
                        port: ENC[AES256_GCM,data:IsusZA==,iv:y+3+3FzQiGPfsQ1EcMD4lrdSpfqm0+duDPjWcp2Dkwk=,tag:Hzh9+ahvVmr3FuTFKwgw3A==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:TtM=,iv:1TdA2rPjnkqRwmun+XJ6800Ku9IphbpK53caGNjYDPQ=,tag:Oa/Se/uu2sVaxIUQTJYVqg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:CSk=,iv:wjsydwyrzP3s/90KgHwrmuB9aslzfBMqg6ZOCIQt/8E=,tag:FPwthIpWpbJ0DZDNhpQFuQ==,type:int]
                  name: ENC[AES256_GCM,data:/V3Sa3yxAqw=,iv:0sVrrdMpLCuoGPYo6usmtGKdIOigJpj7Umegy8I9/Vk=,tag:vdQnqRnZwRy+Gf5aKSC/Mg==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:QGAEQg==,iv:y0iesdomcSk4h19JE80XyHjYABAdg0pk7hD5RRmNIL0=,tag:cDJgMnzDOq3kNMon1JqhUQ==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:rg==,iv:ZMMQTLL8UnDKWFhXNrAuHY1XsD/X/chc9r/r6uXyD7c=,tag:OAk7sVPLKC+fguHiSSfhaw==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:QF2JrE0=,iv:9Ur8jxFnKfh2QTXYzceWazHMFMM/0/ACx05Ng9BJJMo=,tag:8C4RATwIPBJXU4zRuvKJgg==,type:str]
                        port: ENC[AES256_GCM,data:g2KrsQ==,iv:ZEYkpdW6RktIzD6hVCaVxd7G3HuEPYYno1KGarpjvPE=,tag:DNJc+QT7hIiMr0FQVmyfJg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:HfA=,iv:DIUrIluKf6FcmD9nzxwh9N8ws925C4ih9Yhb56EOCC0=,tag:jx6KkjNaeJrN4Y896osesA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Jcw=,iv:UEwJK0ppx+yCbx/DAOECvFNydY5xxiiKLeYFfXRV7xQ=,tag:a76bL39GcrcqGx6DFsMCNw==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:RA==,iv:iUmMPXHyQhRtnKIqNFCRXQb5ZPMoYcd1DuKI069Z6Zk=,tag:BuLrJzBLhQnWMGxSF+GBKg==,type:str]
                        memory: ENC[AES256_GCM,data:h9boObs=,iv:iU1/d/qwe/2qf/u9As5bKgoL0c44PBBZWMxz8z1XD70=,tag:jXKw88Wstiyv0Dtbx07tmA==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:5ISR,iv:hZ3OcPhctbP5pSjKo4KZ4FRggZImxSr4lDtukYq9Ek8=,tag:KfsuxZkbZjlX4d73/zz2Iw==,type:str]
                        memory: ENC[AES256_GCM,data:Pogor/o=,iv:zWP2G27L8/adwO1NTrhQv9AQ1kogtKRUAn2lbB6LBys=,tag:2c2dZlImmVNJt7FzyJAfIg==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:zVk/kELCBQ==,iv:1k5LrowexxGUHDrHZJTjrzV+JS7c+8cIG8JcBfT7wWI=,tag:dU0S2tBP6JNcTuQZAq+DOg==,type:str]
                      name: ENC[AES256_GCM,data:vVDjd9lJ,iv:Q0kg9OlsYPr0gdWhkcChPtOh6IN3Nd8hnBng+DgMTTw=,tag:wV8IibI1rMR7crGtqRFODA==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:KxIQZcg=,iv:zL1cOrPyfj+3Aw6jx99iDI9lOA7tL836wEiM7wMKzkA=,tag:NGOf/inwn/3lMnGOX5/T0g==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:18ocw5Mq,iv:TPsabXxzd+ud8eN6qVYTyh1flS4Wg6qDXjFn2dka0tU=,tag:OXO9zW9bm81kAaubDeX0sw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:jpcYzCt79CGTTkncWQUK,iv:Oo7RVBt25zTpZ6NHFkB0i9qj9KiEKA8kj5BVQZ2HABo=,tag:nEsvRXJWOGW3aY7BfYX3GA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SmVkQXpIbm52OW4waUxP
            WFkyNDBMUHhrSHppMXZwQm43cHhJRGlqQlJFCnFYSjJXWkNnanExUUNEM3BSTWNx
            SUNscGRuZWE1TXVyeWV0SGU3b0FVRVUKLS0tIGtYaVhJQlVkczBiME4rcUdCa0NR
            aGtaUWZRamhRM2xJWndIcjcyZ0NNUzAKSasO3GX3rQDiRmbFX+DBh9XC+t+Yzty5
            r2pb/isP0hKV0N5/yiHuh5G/pTv5Tch3BKmOMa7rEO6K/dhMZxeu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:R0mTyP8rctrCCZACJysb8QKitnvFfvFtPTEod8H3XorEBr5OZYppYcN8bTb8e2ozNXGLSLBnkQNW9lxFlGXrTiEmcJT7ogbtrOY28cC6K+9iI+D89xI3Yw6guPYzH+Nnpz82nWVuxE9vH/34VEQ6XZbsEE0GRkvjykMuahBNRAo=,iv:LiLHiHDnefA0fTxAyBfSjhY01d5w65wA5qbBtZTJRsU=,tag:QBt6zTYsmVJNIZ80EPtgcQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:c6s=,iv:trXfnNIX4Z1E6+pY3CMM3mapLrGf5ZwRv/4ejitmZe0=,tag:zRTdrZau78AGwBHONnviFg==,type:str]
kind: ENC[AES256_GCM,data:PYKwdL9YiA==,iv:oon3LInFy0qJZ2fko4g22fflAsy/ytSj72Svn8BaJjM=,tag:acD04MODKudBc8s1UNwmRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rN/Dnq4CaGU=,iv:W5ZbmiEEOoZe7v+vgGFvuJK99QWlvwunVR8qlkean4U=,tag:KUT3Rvr9oJwcvatfFI57xg==,type:str]
    namespace: ENC[AES256_GCM,data:opuwkF8=,iv:MzEVO8rkBVtEs3if2Rou2+h9gK5AbZp5OIw+JKvHQ6Y=,tag:BJ2DQqG3ryKG1nAmRMqrvg==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:Z46iaQ==,iv:ix6+WQUoY2i6tG3t+qjHMqICvuFo8t0DZkvOd5P4yCc=,tag:jBdXkH1TX4UplS7E9YQdDg==,type:str]
          port: ENC[AES256_GCM,data:X7bDJw==,iv:3WwcuU8J/0XA8NN47XfKQtNBxikQMekRwhO7D2ZzyMU=,tag:UtHeMf5+KV78H7xrz3zrmg==,type:int]
          targetPort: ENC[AES256_GCM,data:hChfwQ==,iv:cwCtDg/+uRf9DHj6JhDBFSEDC2AxX4phVUQ8OZrkkWs=,tag:yW0/PinWlZSa40vffOjLWw==,type:int]
    selector:
        app: ENC[AES256_GCM,data:ZW7vUPG92Ac=,iv:SOTf7DM8Bqpi/iabFj7WANGBBCgTDJz1+m5SOsdYGQU=,tag:lOBxeiLzX7j0Xb536xYlQg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SmVkQXpIbm52OW4waUxP
            WFkyNDBMUHhrSHppMXZwQm43cHhJRGlqQlJFCnFYSjJXWkNnanExUUNEM3BSTWNx
            SUNscGRuZWE1TXVyeWV0SGU3b0FVRVUKLS0tIGtYaVhJQlVkczBiME4rcUdCa0NR
            aGtaUWZRamhRM2xJWndIcjcyZ0NNUzAKSasO3GX3rQDiRmbFX+DBh9XC+t+Yzty5
            r2pb/isP0hKV0N5/yiHuh5G/pTv5Tch3BKmOMa7rEO6K/dhMZxeu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T14:43:39Z"
    mac: ENC[AES256_GCM,data:R0mTyP8rctrCCZACJysb8QKitnvFfvFtPTEod8H3XorEBr5OZYppYcN8bTb8e2ozNXGLSLBnkQNW9lxFlGXrTiEmcJT7ogbtrOY28cC6K+9iI+D89xI3Yw6guPYzH+Nnpz82nWVuxE9vH/34VEQ6XZbsEE0GRkvjykMuahBNRAo=,iv:LiLHiHDnefA0fTxAyBfSjhY01d5w65wA5qbBtZTJRsU=,tag:QBt6zTYsmVJNIZ80EPtgcQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
