apiVersion: ENC[AES256_GCM,data:uTI=,iv:OM/PRfoBId8EtB1hTAgIFjZSX0O0MvFk4lqnTCKfkSA=,tag:7FgCXlBUZxqUd8k+12awjg==,type:str]
kind: ENC[AES256_GCM,data:0N4xu7BGrnKfHgdRONHGPYg/t6uQ,iv:n27lQWBcy3HT+xeXtPnWotTrwKTzchmDM/VEuqkVNpU=,tag:NuTgdb5BuhfKTGBueV8PNg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:F7dBElCUn4fhtESTMXwc,iv:jvf9ciPhPCI/giXvF+FdN8AF0COuPwcU8GDOYZmRAWw=,tag:DJMBvA2xAkUt9dkB1edRKg==,type:str]
    namespace: ENC[AES256_GCM,data:gv7ezvI=,iv:dtiv2x4HwK9y1oYXyfhHP2LUFMeSDJZ2IcDQIBEtkzo=,tag:NmrmeYND+Ve0ewovUFRbNg==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:t3eXQFfgqGPw5fwzmg==,iv:iN3ysc+JZ46ddsAcpn/D2FmUVZ83eeyX/oL56a09Afo=,tag:l4xWuVdFWpzN3ylMCF+BIw==,type:str]
    storageClassName: ENC[AES256_GCM,data:sUjw7u6mFko=,iv:9qIoRPoCW2sdMn6T+/axjcLeMPfGPEqHPFCMnIkq1pE=,tag:qUDrdHbOtEcpOa1umc8cQg==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:fBCq,iv:aMxpkYIeq3fEXdJUj+j9n6I+Qy1ln82CSdKfvGQItWI=,tag:kWnMYWbfTgf1SDYds/ODVQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZWNENUVwYXE1NHFLNllr
            MFpIVVFGVlJRTlpZU2s1UUV4dkdBYjV6bERZCkduQmNNdFNqdU5KUUlMZnRzVXNZ
            NmhTNnVDQ3RmNk1sa0hGMjBaTHgwcG8KLS0tIGtlOGtKZnpLTEh6MXZqZ2hFVmUw
            UG0waTFsNzZkSHZMUzJIVUNvUklVWG8KIzS8vbXbTas2mEwhbyZ3d4PH2pK9HRRk
            dEEMn4rYE2zAKbVfu4XM6XRtZbGo1Za/RfwGz/1feEw01Bh/84sJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:NJueSGm6O0vTqPIJ7o/Jin1UMjlh28h6KhHcyhGM9s15jTTyjbWYTa4r4fUATjochSHaQz5VovHdiN4H8i43k/VfXafxxOoAMwcwOjmdxMLe98KV2i7gnvsdAkI/PDHtCTAY160dr9ScXksvCfnm1L1CxlfNZ0NE/MRHZ39e5MA=,iv:AUc1ReFrii6mMmg75lb8vgJ5IaVQdtdGhlITgYt+WPU=,tag:ZGTBNdZQ51VBbeHHscIEEg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Vlp0xX1nbQ==,iv:/OlpVNJUggNCP79nDqByxkhtqwfZYNKqgsHhCEJAmas=,tag:v9cHLCSaba3rliqkYkeAzg==,type:str]
kind: ENC[AES256_GCM,data:0LEsEB/xPNzeow==,iv:Kk5p6YeadDQ0lx0Kc1z29rDCErc5Lzk0fCzNsOVFqxM=,tag:oJ3T5dPqwIQcHF6dnivE+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uayOBAoeQcg=,iv:vNh8NHZmxlpihydbGwbc4LDChNWId7hAlHTH9vU5ZMI=,tag:7Llp2nmngCcqt9Jinm976Q==,type:str]
    namespace: ENC[AES256_GCM,data:1QasN4A=,iv:VPWscm54ibG4clWdF9HYtdgMQvvj8jUzK2Jw98CYCbI=,tag:faG3CtGWKqEWFpT3uSSgRw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:whrC2ne3v7M=,iv:H4KLCnu3qoIAc2UOfRzu4MDN6r1chaD0r+Pn8Qxfxb0=,tag:Y3qY579GtIua0XuppyvDuw==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:2A==,iv:gE8o5ZPoybsstwp6GIJTjHU0obBQyQhA45xt1rk/GnQ=,tag:IQrvofjxQWahHhwefvj0hQ==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:mfiKUNd9la4=,iv:tGnngRcZXZqOP3JWvkgDZpQi5ufYDUCTvU7+WmIfbLY=,tag:7wT/CgHCEzb9c4KBDms9ZQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:nLXq5JD8Xtg=,iv:IU2zsyAtoL2ibhg1rC9KRGB4XXib51lbLyW8LxIoyG0=,tag:hbkEIRTUcjcMsHSWdCRXzA==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:GTz70QQ=,iv:uPgfR5n4tK1/LKIQTxbcsoTIXkuKKENzpgzhgftJX4Y=,tag:IccrMCYAKoJ+3JFh0lYU6w==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:pWNRWkYleD4=,iv:Yrrks7tf6BgVlPIdgFV09esgZ3+sg/iWiaekYUv09tY=,tag:6bfdOTuvxcy7swmg3wn82A==,type:str]
                  image: ENC[AES256_GCM,data:AUlneRXr25HbVupxAMuZ18E2Ht92A7FFsAviivmxksOLASkatbSze1FkZxue,iv:Wit3xCKWj2+lGWPF94en3jQyhezKB8YsVvK5EAVx0Ws=,tag:qgMy5cSrotAgXpQipuBk3g==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:xyU2Cg==,iv:XznxYgwgx3XCxb1IaaF/HqIpsyQLk70KSpdhKpGwUSk=,tag:2i57OHytUZd1sqye3GjblQ==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:0XcdCQ==,iv:p2iCN8txJrT7z6Tea5y1X5P/DiXfa4RjN2PMaDcoJW0=,tag:JsUfuKW5H5mPBZ72GYyd7Q==,type:str]
                      value: ENC[AES256_GCM,data:J8WFqg==,iv:U1mG+joCrzVskwG6GNbey9VosjrCnn6xLoV/ArS44iA=,tag:CYFfq4LU3pWL2bAFQKb4cg==,type:str]
                    - name: ENC[AES256_GCM,data:/3yVaQ==,iv:FUhWBXii2sm4jPTtEl2CYqDROYl1RRTFSMyGU9Ar6b4=,tag:VgIo4Ry5HvDKBuNQKJEjMQ==,type:str]
                      value: ENC[AES256_GCM,data:n9vn,iv:fPTkSiw/gPzvpwZPQ11fGfTNw1qymFNc9Rx9u4YBU94=,tag:t0f6mDHYRSi9Co+U8E+M2Q==,type:str]
                    - name: ENC[AES256_GCM,data:qs8=,iv:9PDhxALu3xaQOQmLZCz+QXEzpSL8YZrlQAZ8TG9BdqQ=,tag:U+rVNovFHWdvgKoaZwkH4g==,type:str]
                      value: ENC[AES256_GCM,data:C/i0cwyy8lGBzkJzWmZFbg==,iv:QAsIdQuKjvy6aQmfEY2H62CNacfqWm8pytPPg+3Iozs=,tag:ZowBEaulUjd+YE0ihHQjnQ==,type:str]
                    - name: ENC[AES256_GCM,data:eRruT+T7RuqfTA==,iv:ZS8JlSM3LsFaJuURzxyU5R70Hg75V6noQK5MajAeFns=,tag:lTCP5PFlgZCsvMktsBsXLQ==,type:str]
                      value: ENC[AES256_GCM,data:7gGuuIRU5gOB0QnWjCpvM2io5xrb,iv:Ww3lMMCKYruH1uwk6JTlMda3NibvV2N1W3LnQr7hRwc=,tag:m4VYEi8k0CSd7LefWGmQOA==,type:str]
                    - name: ENC[AES256_GCM,data:GSBYMu3sA+751VU=,iv:0EzBf583oQ0sMqTE5We2TyQMHShk54zvRvZNsv5GkRk=,tag:wFvylb3pVZm8iSNmnTiNzw==,type:str]
                      value: ENC[AES256_GCM,data:tXx/3YU6mM5mpx6WxKXDtcoP3/ii,iv:40sowj/j/eo8Zt3pAHoezLOUl1zMNiFtL0EcuPIJty4=,tag:D8ar70hwcjtLMJsHD+xvrg==,type:str]
                    - name: ENC[AES256_GCM,data:nw7odiAB90A=,iv:HZYGoOfY66+Rf35/b9ibxd1bSiLSIzW0hTpP4CRono4=,tag:5nHe9hmFhFGlHt0i5ha2nw==,type:str]
                      value: ENC[AES256_GCM,data:TxiT0fUBejdVvaYoPqjHnbjUQgCojEersUEgWLiTsUeav6eKbWbO2UZX+OPkBLximtjTbmRarJEjirb7V57AsVuQFBIFrMPJz+Bd89PvRA==,iv:GkrCz5Z/MBnYrTIEmABdIVz5+BCL/f9vLDCTseuJSZk=,tag:kAGGzEabB4z6NflrvfTx2g==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:fUBI4C+Q,iv:JS86fSbFmcPoHy7jHD7AkQAm1lCw+dmbmBdnKrKggnc=,tag:CwyU7O/dMUoKBYYJcUYfiQ==,type:str]
                      mountPath: ENC[AES256_GCM,data:bWWbI+dPiw==,iv:p64glBLQbG1ylMUQBzhIyXT7Evqo/+dEIQQk0Eg5Vvc=,tag:nAzna0IDQOZy2X2C/I40Ag==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:9doa,iv:bBJVXuEApHPuNCaTrryBry3JwjfpOaBM/eOlLT+4JMU=,tag:xbRDkPWxLR7EDhXqZh2PNA==,type:str]
                        memory: ENC[AES256_GCM,data:dsrRdzQ=,iv:WHlHWH9VcwJrQNJFZHAKnhXrMBenG+IPRXeaWg/QMtw=,tag:rundeRsOiqzPvyh3VMiryw==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:fw==,iv:tjmvhgSHccDiZVGA6COJjKAGxn+r0s1mUIP0xwqIECw=,tag:0yjQ1V9i/umUPSZHfcvWTQ==,type:str]
                        memory: ENC[AES256_GCM,data:qhFFWtY=,iv:OIZYhHLlc59KmyVTuUkAgDhRjlYVR59DDFsSLUUrQ7c=,tag:DgPgjjvQIIlc0Tb5+O2onw==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:wrTcJ0w=,iv:rzD9wgSOCL6CYsBozz3yKWjPPXYYhApeD37yFS/vEtI=,tag:tGwIpi5AIiVfOtfgLX8tyQ==,type:str]
                        port: ENC[AES256_GCM,data:6FuNzA==,iv:3r0NZzFhFddJKo+lksvTQ6MQGiyBjCBW9YMaCwqn0Xw=,tag:FMZ06NEJhDWgAal3IiATtg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:WPA=,iv:hOtk2GAsqaGPnKAMiVP8hrseiEV1rF2UfHN2nIF09eo=,tag:JtYr0w2bNxK9gSILbJxU4g==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:ph0=,iv:o3zwyCRx/7GI9We+5vZZwKYuISw9HID79J48uS78dOY=,tag:sq6psjkvqJLkiMZkc52UmQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:OA==,iv:utLi0BwAR6edRnzGTfvtoUX+4K8XjhqwcDlk5VyCh7Y=,tag:X7/1akCqsa015N/3hO87Vg==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:WjwAjws=,iv:FE6kXBW9fhcGyOrp9NWNNe+8qqwD3HEMETAKLfCbt7Q=,tag:p7trsHtroFU+YganL/qBTw==,type:str]
                        port: ENC[AES256_GCM,data:VRqAXQ==,iv:cGCUwUotu0EZwMQNMo/qnpPnKeuWVcaKuLnODeqawkc=,tag:k6hI0XPOe9BpqMZRlJGcUw==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:R+E=,iv:cnnB2fEXZc6msZiKe/v//FFINDZnAN1s6hAGUE0uKSo=,tag:XKLyWp8DeRDCMuFm7XcZPw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:x3g=,iv:Qw5+4A/JOQJof81YMnD6JDymDpVBcKfNrYWYpjddq0E=,tag:59OIKyeSSUvy8DI0F7RL+Q==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:cw==,iv:x6toqmU+0sV2n3roB9kL/M2beho62HpXDkNC6N5P3XQ=,tag:aYX8TmtHhtdAy8qxQUgymw==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:sEt9zSfx,iv:9sLgKT8DikadDprUaWJdvbWhDbN4bV8IAkYqOkRJ+Ck=,tag:DjKHC4RaAQqIpZyFjbdvzw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:BZAT2d0cozziPEaUTTwI,iv:KbdFldifMJpb8sRPfLpLj14rrZig8lGpuTozWxQD/vk=,tag:3Ki59a6IKlE+iIzb0ToE+A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZWNENUVwYXE1NHFLNllr
            MFpIVVFGVlJRTlpZU2s1UUV4dkdBYjV6bERZCkduQmNNdFNqdU5KUUlMZnRzVXNZ
            NmhTNnVDQ3RmNk1sa0hGMjBaTHgwcG8KLS0tIGtlOGtKZnpLTEh6MXZqZ2hFVmUw
            UG0waTFsNzZkSHZMUzJIVUNvUklVWG8KIzS8vbXbTas2mEwhbyZ3d4PH2pK9HRRk
            dEEMn4rYE2zAKbVfu4XM6XRtZbGo1Za/RfwGz/1feEw01Bh/84sJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:NJueSGm6O0vTqPIJ7o/Jin1UMjlh28h6KhHcyhGM9s15jTTyjbWYTa4r4fUATjochSHaQz5VovHdiN4H8i43k/VfXafxxOoAMwcwOjmdxMLe98KV2i7gnvsdAkI/PDHtCTAY160dr9ScXksvCfnm1L1CxlfNZ0NE/MRHZ39e5MA=,iv:AUc1ReFrii6mMmg75lb8vgJ5IaVQdtdGhlITgYt+WPU=,tag:ZGTBNdZQ51VBbeHHscIEEg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:VKg=,iv:J96rNkQQ5VF5w9UvgyUIQOI3j4IZD44NIQ2XMKhxmEM=,tag:ZSUfXPmKjmLnRJrPrH//7w==,type:str]
kind: ENC[AES256_GCM,data:qODTWI2JIQ==,iv:VbqaJJfn/eChgSKcVBaH7ZkEJ14hv+lCXzYayx+k3Mc=,tag:zDz67dzszF9H5pi3FiwnWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qQ80sL6Xiio=,iv:s9R9KBmwbPBH9EGgI+wgr+QUImBWF9A3kaBjqwv0csU=,tag:0eDDdN9yf8/zRnDnXRDfig==,type:str]
    namespace: ENC[AES256_GCM,data:1dlvH84=,iv:H3v3cggMcli5x/PPR745URu4ZAHFUOzXMDSChvBSVF4=,tag:OCqaUtDSkg1fUpzKBiTxDg==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:jKqiw0efaf8=,iv:nfgWQuvB9VveciIo1bV51Od5JNjurYhhy0/TYVdEsZE=,tag:L5Y6ArmFd3yqqTz2cpunxw==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:L1DZvQ==,iv:1n/GfjdZO9HFdMfidkxmp/AGIRjbyUxJHBduzK/tO6I=,tag:LbR4bO9IxMTUIa2nuXi/pw==,type:str]
          port: ENC[AES256_GCM,data:askaKQ==,iv:hqm8qcMlldc8CwAQz7Qeuy5YCu2u2ecDhLuYWFdKj4g=,tag:99YRS2IAh2HQOfQnJGdkzg==,type:int]
          targetPort: ENC[AES256_GCM,data:h9jM7w==,iv:HAfeaObvihtTec/VubV5k3ADINzxqZUTl4JAZvNIg6k=,tag:bKS3U1LbkIfdoymOLdVUqQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZWNENUVwYXE1NHFLNllr
            MFpIVVFGVlJRTlpZU2s1UUV4dkdBYjV6bERZCkduQmNNdFNqdU5KUUlMZnRzVXNZ
            NmhTNnVDQ3RmNk1sa0hGMjBaTHgwcG8KLS0tIGtlOGtKZnpLTEh6MXZqZ2hFVmUw
            UG0waTFsNzZkSHZMUzJIVUNvUklVWG8KIzS8vbXbTas2mEwhbyZ3d4PH2pK9HRRk
            dEEMn4rYE2zAKbVfu4XM6XRtZbGo1Za/RfwGz/1feEw01Bh/84sJpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:NJueSGm6O0vTqPIJ7o/Jin1UMjlh28h6KhHcyhGM9s15jTTyjbWYTa4r4fUATjochSHaQz5VovHdiN4H8i43k/VfXafxxOoAMwcwOjmdxMLe98KV2i7gnvsdAkI/PDHtCTAY160dr9ScXksvCfnm1L1CxlfNZ0NE/MRHZ39e5MA=,iv:AUc1ReFrii6mMmg75lb8vgJ5IaVQdtdGhlITgYt+WPU=,tag:ZGTBNdZQ51VBbeHHscIEEg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
