apiVersion: ENC[AES256_GCM,data:LwQ=,iv:d+Al9rexRdhvv75MTW7RGbKhO8YpRy0C+NNE3fUV7+M=,tag:2epoQRz0aCu7VN1LEdzIOg==,type:str]
kind: ENC[AES256_GCM,data:kT7QTy26D+px0iHuQPDeDk1k+7Jt,iv:0J+H3kOj7hsQ7R0tUNIDYOgrD4s6SL1sm2jKEwv8sTY=,tag:YTX1Fb7TKEH2BzaQxnU5qw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z5/zOYHLbP1lM93szjM=,iv:cPgy7lXcXOFa7PTWj2/ST4Qd0kTOgGrhBNKHN2VCnuA=,tag:vKeORdicGxvIowwi1yoeAw==,type:str]
    namespace: ENC[AES256_GCM,data:WDUpFsI=,iv:A/fRT2JaeDGEgBr2JLfF/Yf++AeYzONXTPXjJ0MORFg=,tag:hDbf7EFDNeDDQrHGBNlYcQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:ljMnk0CbK+Pwa2mtfw==,iv:dnbWT5qJOxD/W601R6H49s7OBi0+Nan5Ip33zZtrpRU=,tag:KyrIhXinlg9IsX/KPTJMfA==,type:str]
    storageClassName: ENC[AES256_GCM,data:09xK2cBbTWw=,iv:i3p392ukVrN+AL+5PfCA3eBUe/cTQlAzOKgyopw9UWw=,tag:Get7G6MOm0IlIN00PNRaoQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:eFuX,iv:BIVPNebAWAPYSqKLhIsnhK1ULcw4orG9X4ZcKjN5XsA=,tag:KdlfmaME16pLvBIE9Qn3oA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUhKczZiQ3BhMjE3U2VB
            YTNwRjVGRGdrakFvSHJLSFpWRmY1aGR0UHowClVmMjRSOUF1akhaQU9WNUJUVkxh
            OU52TkVSbnhHS1dubTF1WUhkOVVFbmsKLS0tIDNqWitjU1llVGsvUndrMjQ1SXdz
            U3BZeThGdEVwaE9La2xFVDRNNkM0dHcKuXgFz19XRS+huJ8cqtEbahM7wqgkr85Z
            ybksgz1CEnaiFJMrpqMpwFu99Icj/T7dbIR+a1EJBzSWALAGaFCc2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:qmLPuRfT/XtY/e2a3Hbsk+B0zESUFRmsEUaQO3PgO0K8gARatVcUOB7FPK0cM+SnxlmBSMABLZvAviLyudcI4jnr3ddXpV74YXDFZkRzJvb9WvpsjtfFEi0ILYr/lul6MnieEsoQ1ygWxmeg40dp0hRRMbk1Aup32Szg75wSM4Y=,iv:PrXqHEUWK+4QVqsxIkUUXcKH2pXIRy33wUFo0ZKVdBg=,tag:PKYDEAnDc9UsvNMHcQVKIw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:SiH+mg0msg==,iv:T0R8q4uGGraEelW/oS+WbniWuBryaxxtuz2j7MxuBPY=,tag:BWXNHl8nRis3vQunQQmHow==,type:str]
kind: ENC[AES256_GCM,data:nBf+zR2t1tP3xg==,iv:qCb9mZ5hf8Rtp1d+8EVzKc+bGW/FJWumI5cdn1HOaQw=,tag:Hx7uS+y4IQJ4SibFf7Bgyw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:brXweWMNlg==,iv:pdvfaldvgNNY2Wqwz2IbyeGHuS4JlwEvSLgfZMbb9nw=,tag://paB3QYZWAbdGqsTQXaow==,type:str]
    namespace: ENC[AES256_GCM,data:i87QL6I=,iv:e4qNfkr7WpUZ3jRU44KzptfOt/BuCuargd5IV2F1MUc=,tag:o69hZnK+DpJ7lvznTL+XKw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:bu5jHzHO8g==,iv:heMmLv/x6Z9TrJDPLRg3bFW2fY8ZexKnOr2CT+UztRg=,tag:BVoZywsi15GVOxccNmt8vw==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:9g==,iv:YtXqRShs32uBH0Vwd/sNhIWo4eDh4vHtaq+JCWW143c=,tag:GhqF3XqrOXGlAKpxz0oX8A==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:AxV9DRfD2Q==,iv:VVNIXF9uMOqzSuAKGYTKa5GOjT9Zmy6pE0drZRpqsKc=,tag:C/CIWyJIiPR6UGFUkq2hhA==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:bF2SOb/ahw==,iv:uUKLitcJCEOObMp+wIcjJxzi7Jho+jg46+ZN51Bb34E=,tag:D10iw0yeJpsqgjCVx4W9pA==,type:str]
        spec:
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:YQu/RNw=,iv:SVREXCD0YiLphmeSkttwVW0/o4MWdUilBklh4XBYGrI=,tag:ci2f3SzmnJgohCkQJTangA==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:ySIGE8Ke5w==,iv:gE5lsnxegUyEt3eYhKE68GSLOCJ+dD03OfigKVCQfWI=,tag:T/O8+nlq5t6Cc/h1efv82g==,type:str]
                  image: ENC[AES256_GCM,data:VyFRfxnTQKADlT1450FD7xheA6/NMTeLA5K+1JqmBKo9b8hkbefJfG/KQjli0U3XYC4XKzHEUA==,iv:DFEjKURQMIIcNBBq9gapYdKWWja1peTNzB8y/VAZe20=,tag:YpW8YuLpUw/QcVHloEbmPA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:IkqFTQ==,iv:nAWuJfhrOCodN2HPW0hut0/79XEUvalXoHpq3RPE/Oc=,tag:L35MXOORDACe0ZXoeYVk8Q==,type:int]
                  env:
                    - name: ENC[AES256_GCM,data:J4Wwqg==,iv:c7RALYvt7Cdi4mJH7nGisNDyfMkWmC3titJ8y9HK0mE=,tag:3OWnhLA57Dg4xajap/dqfA==,type:str]
                      value: ENC[AES256_GCM,data:2YdX7w==,iv:Q0I9DHLfhg/ubFaDZRpxKfxqRkEmOx9J2qmRHEYITNo=,tag:WHFTu6cV9uQG2+qxPjri7g==,type:str]
                    - name: ENC[AES256_GCM,data:GWDDfw==,iv:J8qxH7UPtWzuFLqEFmqg2R310ASqbhvh5X5BQfT6Ptg=,tag:UH+tUYdyFNd8+tkwkSrAFA==,type:str]
                      value: ENC[AES256_GCM,data:uhP/,iv:dA+7An1dsMx3hllF4S9MEP6aZsNJVe3/e+Yw1JnBTZk=,tag:5BkSgzf3Qvka1Drkh92OhA==,type:str]
                    - name: ENC[AES256_GCM,data:rN0=,iv:Ck5/+xv1VPN6FDLHySqHxIXwg0mIYfGarxsPnLn4ox4=,tag:FnwvPYnrDGla0vIoznHSFw==,type:str]
                      value: ENC[AES256_GCM,data:9CqRjVMxcBDR4CAR43MmOw==,iv:Q8pkajtpV96tagGshKGkMdnpyMDmKem1McH4Ce7l9aY=,tag:t+mgIgoMKPm4Cd4QZwGMAA==,type:str]
                    - name: ENC[AES256_GCM,data:+pK1AtFMk14NIA==,iv:PMO6IG1vIOoz5rshmjOXbB2zUDv4wRvtOjmRcRuiDdI=,tag:sY4gkgrBA6UDGsbQY88VJA==,type:str]
                      value: ENC[AES256_GCM,data:xZAjukn+8+0XuLVWOc0afcTg0cL7,iv:eTVZR/TJSYR6JM3DeVO66leV+CqyLeiHhPl7IdKTis8=,tag:fiq8/FuPpWUof1xLXeUSCw==,type:str]
                    - name: ENC[AES256_GCM,data:6X2EZLNW4h5W3dU=,iv:XFGJvozCnD7JgMfNQLWwaVTIb6GRm1bLGEUjlGsM7ws=,tag:Ad5U69n0X6ASoL4chuTVKw==,type:str]
                      value: ENC[AES256_GCM,data:kk2w1OlFrB04NoOqbt7yooTrcSnh,iv:g4Gjq9jBkZOfxh5EH7eTm/ruVkN1+j+Io611VxYuz34=,tag:qWmSmAfqpdMypMjqRiYs2A==,type:str]
                    - name: ENC[AES256_GCM,data:mXdxUQdqQd4=,iv:EBOrUTdBjzwA14rhq4eEZJ8zJ+1Gv11PTu5eqN+3dsE=,tag:YX10vT1kEh0++ZT4UXEBFA==,type:str]
                      value: ENC[AES256_GCM,data:QHrxV+V5qIhUOxxhh+JECRBSF0pEwl2mevd6SY6lY4ODE5TA8Bzx2Adbn/Z9DT9jCHZVfJ3SNRVw06o7YyjwSQ5WqQrFPQAnsb7AOEvrxw==,iv:FFSjnZ8pG0kREnQ1uZopJP1xMjL2W9xUlfUOlkryMek=,tag:9A+h+H1ai9m08nPmPoCPKg==,type:str]
                  volumeMounts:
                    - name: ENC[AES256_GCM,data:R01WRT+0,iv:kU+jRefsrTnbDmpGU+QNEFYbflEo9MPwXXWInN2GXVk=,tag:sqOxlcrlYmpTE0lvqxzpcA==,type:str]
                      mountPath: ENC[AES256_GCM,data:LbuBzvzHxQ==,iv:N24YHdHItgk7jPOLo1eS6nCybxsxW3GmTCJFOjopmWw=,tag:aMn+dMOTUNiUOgDSUQJW6w==,type:str]
                    - name: ENC[AES256_GCM,data:qMQ1d7Y=,iv:818Qf/LbhMjGZmINm867GpcB0iLH0gkLeborC0yWBUM=,tag:xhs5M7y8YWL1XPawoO/t9A==,type:str]
                      mountPath: ENC[AES256_GCM,data:hWDgCXVU,iv:Iru1xEkMp+xpfCmF2jEtvM6hS8D/KlGQs/rQZ6/w78U=,tag:odahr4tvjwrrxScW/DTC0Q==,type:str]
                    - name: ENC[AES256_GCM,data:Tmac20wl9EOW,iv:Hg0fIURBS60YMO15qNJhjeXTPsWh1qYRIjAaFY32ksM=,tag:Ehs/vlA+fnek00fu9owv9Q==,type:str]
                      mountPath: ENC[AES256_GCM,data:K44UAEm/HqkBRA==,iv:algz8BOAFlJgkVfqqQc15Dy9A01LoC4kidDlPMedvT4=,tag:pfLPE+I9bzcPlYOua/87Rw==,type:str]
                      subPath: ENC[AES256_GCM,data:ItYs8DRL6A==,iv:Gb7S2eyLK0O60ANYJxF3CzSAl4AqOpr013kpu2TVVfs=,tag:0EF8InZ4GPdhhhCzszR7og==,type:str]
                    - name: ENC[AES256_GCM,data:HuLIP6CrpAZN,iv:gAsQF3BUTSwms7DNrUGdrjKAkH3V439mquBMCvH+XQA=,tag:f+84JcpyE6pXW9ncaEAfwg==,type:str]
                      mountPath: ENC[AES256_GCM,data:VYtRTvZ0fPdR,iv:4Xr5RaDr8jNBLAtA69NgO4ngFvTT2M2Rd4mJJouRJW8=,tag:U1p6aocChLOQ+WiJwawNTg==,type:str]
                      subPath: ENC[AES256_GCM,data:K0r0VsmHY5E=,iv:tBuQO6G4e/bX0gu8Rbx7ifTUQOHygILczm5aRH61e0Q=,tag:jt8m25/uqyzcsmSmDCfo4A==,type:str]
                  resources:
                    requests:
                        cpu: ENC[AES256_GCM,data:FCs4,iv:J3R/IPps4uAk8GhvYU7iU45GBcs9fWjVI2sTjKwHMVM=,tag:Ik6XWTENyCDVZP8ViEXcnQ==,type:str]
                        memory: ENC[AES256_GCM,data:/PBH4Zo=,iv:+ALngwUdFMWVoUHZnozM77pRVKU77Lrixawpz8saYH4=,tag:eIn8I30U/9OuSW1GwqXHYw==,type:str]
                    limits:
                        cpu: ENC[AES256_GCM,data:9A==,iv:UodeldFGv7EKIWticsPXrFKGRwiiXDE6Q9KlIXv11gc=,tag:A4LaRIIec5dj911pvWA9Xw==,type:str]
                        memory: ENC[AES256_GCM,data:bWvphtM=,iv:UN2TArr76mM+Wjr3NPtejfHZE43qJdgdYbh/QXDhkJk=,tag:uw/yPnlw46p9QnZP8f7P2w==,type:str]
                  readinessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:hc03jPM=,iv:n6ny7aegYkGfzpY1q1SL/HOM+J7qit7U/qTWf2ehg9Q=,tag:JrgV5iuq276by35yNMZQpg==,type:str]
                        port: ENC[AES256_GCM,data:B8VSCA==,iv:p9M5Kr8jdolV8dlISIsl50BaUl5MR+mbMeFvxPF7W8k=,tag:NlGa6VSNCG1j1C9ANqgfBg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:ufw=,iv:mLLzQP2Gi0pae8T52GZjOFVEq7DW/30ZuTGqucyrAFQ=,tag:wJpNdIj9iBYmj56A+Zf/sQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:RlE=,iv:PpVAMWy3Wm9IzwpLlKfpOvAz7eGxHDgcKlfTXZ2FBKE=,tag:nIlcR/oCgKS2EyqPmFt1Lw==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:FA==,iv:aTqW8vZv79k5oWuqOxcqRM6k0S9HpfsRNS8wYH/rSs0=,tag:v4LFQf0kSKL2PUMMYEQTHw==,type:int]
                  livenessProbe:
                    httpGet:
                        path: ENC[AES256_GCM,data:kAH1k5U=,iv:il8dncq4PTaStSYccfPO7HSx1/UqZdR/ArnFAO+iqmw=,tag:DK8ZZR7wnJmOFIcJZeAfBA==,type:str]
                        port: ENC[AES256_GCM,data:dYI6WQ==,iv:GwFY3k9v8RIvOHFH7xxAK/MzkjVnZXD15FcQbJpWwzM=,tag:oN/6DhagwIdtTSOv3PYJmg==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:IwY=,iv:L+QpvcWoa/uHoh7mvujOmUFqTtPvqQANaSBC2bt+j6A=,tag:/T7DSAb73D98Rk5Vy/nvCQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:8Is=,iv:FgBqMBJ8iW/a96Sco83/gAXWo7YZwmYrvoenH7b66PU=,tag:pBGuBXgyMdRTGS9tE2BOMQ==,type:int]
                    failureThreshold: ENC[AES256_GCM,data:ZA==,iv:oaSqTozGcoez0YdaZqWdxhyY23KdbxYNtEhaxSKgvl0=,tag:hweHdj8zHbB4X2suKcKjMA==,type:int]
            volumes:
                - name: ENC[AES256_GCM,data:Q7E9Qgof,iv:xpseeYhuTiUiThHkDn2Wr6EMZ7UpFKgavc4UFO2mowo=,tag:NvlgfjeTr6QhNZZedWC0sA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:jYG+V6L9WKTPhTpHZho=,iv:FZy4wLG01iD1OmB2ZaFjoaXIi2LxIif+4Q/5MR5NPpc=,tag:3MqFJ/O9bu8DeU5Mk1Q8cA==,type:str]
                - name: ENC[AES256_GCM,data:SOe346g=,iv:QvHIHBUnNjkvreX09IYbVhS3pHPoOfh2Ie4tRyIwHNg=,tag:gYnItuLdK+tjqVWQ8XI//A==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:HI2x2drhAq5K0+PsiHsCLg==,iv:GyRL5DVGrt11gFbH+o7OXx9uHYMtN0ec8zIZzEANNyg=,tag:h9BjrbxNv5zucoY7bPSQ5Q==,type:str]
                - name: ENC[AES256_GCM,data:DFugv/urJs3l,iv:jUzb+BGTdh7HgMSDLyqM/HFkdOp6L5q0UHPLYFbj+20=,tag:6hIbMkmVVU6RsA/DQt6lcw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:PE9mwQKxGOsrQ6SsYnZ+UyLSLXU=,iv:2IiMecP+A0d1PtyHU201gypl21KtNz0XhGWUh9s8bTI=,tag:nayb9Zw1D/s+iwp2sG1D/w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUhKczZiQ3BhMjE3U2VB
            YTNwRjVGRGdrakFvSHJLSFpWRmY1aGR0UHowClVmMjRSOUF1akhaQU9WNUJUVkxh
            OU52TkVSbnhHS1dubTF1WUhkOVVFbmsKLS0tIDNqWitjU1llVGsvUndrMjQ1SXdz
            U3BZeThGdEVwaE9La2xFVDRNNkM0dHcKuXgFz19XRS+huJ8cqtEbahM7wqgkr85Z
            ybksgz1CEnaiFJMrpqMpwFu99Icj/T7dbIR+a1EJBzSWALAGaFCc2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:qmLPuRfT/XtY/e2a3Hbsk+B0zESUFRmsEUaQO3PgO0K8gARatVcUOB7FPK0cM+SnxlmBSMABLZvAviLyudcI4jnr3ddXpV74YXDFZkRzJvb9WvpsjtfFEi0ILYr/lul6MnieEsoQ1ygWxmeg40dp0hRRMbk1Aup32Szg75wSM4Y=,iv:PrXqHEUWK+4QVqsxIkUUXcKH2pXIRy33wUFo0ZKVdBg=,tag:PKYDEAnDc9UsvNMHcQVKIw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:1U8=,iv:OQAl287J0j6CxoR/Oqo8STeEKAlXgeMoraDQ+lNVyTE=,tag:aaUgo7L0xUU8KfiKb3rAQA==,type:str]
kind: ENC[AES256_GCM,data:h3fzyUkOyQ==,iv:vcNRYZB8EscmlcJDR5+0e4ZBcVAC43ekOZ5T/nl1ZVM=,tag:1rcvdnMkUdAZS55ySMvJEA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dBynkyXr8Q==,iv:mMId3HWLbp/2yRVZsP1UnH7ujf8gFOgJzaJcY9vFSxc=,tag:CdPPGQEGou157/iNS1filA==,type:str]
    namespace: ENC[AES256_GCM,data:A5lELa8=,iv:d4yHQqHXodIet7VkD4CmapUFj5HoeoU6Ecni3ujGHl4=,tag:6NuF7cz0xNtXTeRYr5X6RQ==,type:str]
spec:
    selector:
        app: ENC[AES256_GCM,data:Oaewu0hdFw==,iv:xHHSNxTGWMut0VBSnhLgUtP9FAXO7HRbj87D++H3/Bo=,tag:8B+bH457pvZbVvYAYh49lw==,type:str]
    ports:
        - name: ENC[AES256_GCM,data:SaFc+Q==,iv:g8X3kZ3wCMDwIeKxe/zWG/wTlhIOWpg0vc1mLDISDdI=,tag:EKmFEXuAKmZDdcfi0YAEEw==,type:str]
          port: ENC[AES256_GCM,data:e6SFFw==,iv:12Ie2f/510+n7kJ7JFcGBOiesVuJaZcSgCeWQjcdbyQ=,tag:YISTE6mQsECmueWSAd50ow==,type:int]
          targetPort: ENC[AES256_GCM,data:6uIAig==,iv:++AwmC8oiTRjBtlTuHRrrmg8Qn9LQKENN3yEwww++Y4=,tag:6rdanxSNNO6EalhI5AdGOA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWUhKczZiQ3BhMjE3U2VB
            YTNwRjVGRGdrakFvSHJLSFpWRmY1aGR0UHowClVmMjRSOUF1akhaQU9WNUJUVkxh
            OU52TkVSbnhHS1dubTF1WUhkOVVFbmsKLS0tIDNqWitjU1llVGsvUndrMjQ1SXdz
            U3BZeThGdEVwaE9La2xFVDRNNkM0dHcKuXgFz19XRS+huJ8cqtEbahM7wqgkr85Z
            ybksgz1CEnaiFJMrpqMpwFu99Icj/T7dbIR+a1EJBzSWALAGaFCc2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:qmLPuRfT/XtY/e2a3Hbsk+B0zESUFRmsEUaQO3PgO0K8gARatVcUOB7FPK0cM+SnxlmBSMABLZvAviLyudcI4jnr3ddXpV74YXDFZkRzJvb9WvpsjtfFEi0ILYr/lul6MnieEsoQ1ygWxmeg40dp0hRRMbk1Aup32Szg75wSM4Y=,iv:PrXqHEUWK+4QVqsxIkUUXcKH2pXIRy33wUFo0ZKVdBg=,tag:PKYDEAnDc9UsvNMHcQVKIw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
