apiVersion: ENC[AES256_GCM,data:oJxCaial122l99wpBRNEoCUzoYA=,iv:Q72hz4j2lt+jl6I3zwpuqFy1PW3RZb63objwvsEONhk=,tag:KHiWFWUTCdRIX3yFYm/KCA==,type:str]
kind: ENC[AES256_GCM,data:3NJEDHJieqaGkqg42Q==,iv:qPJGl1nFZjk/whXf+wdLHGZ/ZvroNTKAv4qiHapVDOI=,tag:MVZYRMrHeNxKjveRtAHW5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UzWnIdv+AJQPSCtD,iv:PUQpU6RM58R0BgwmusGxNLCXRBZJcwuUPHR4WN4hWts=,tag:BXDiP7lC4+ysOuHuXGA1Bw==,type:str]
    namespace: ENC[AES256_GCM,data:sasXqQM=,iv:+usVVrO2xQkIuCRTroTaBJ/3WNuRBGmqX97yej1f7sw=,tag:/iMypWUns0CFDSlki0zTHA==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:BpnLwo0tfw==,iv:nVI4dT2N//uZLOMfM78iXtfjYRJf6ct0nXPzHDvN2Dg=,tag:Os2QnzC2AvvZvP4ugiKnKw==,type:str]
        - ENC[AES256_GCM,data:enIZmqTx,iv:pkUCpAUfji74PTZAY638J8dRmuv2v0tDgsdlmyBzKLo=,tag:HM7bZAuw9uSpb4+cEj2xSQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Nr8kj/AXUpY40RyGzw3Q6YJLX5Q=,iv:ohOqEdICiJx4sm0WZiJS2CkwRal81ZYxCnrpbV6CxJE=,tag:uOvFlJoe1PalIA4uKXKkZQ==,type:str]
kind: ENC[AES256_GCM,data:fhm/gRDqac/4rt/0Hg==,iv:Y3DG6iyGCVkoOBeodvvfn/jCN4cvllF47elt/FrwVSI=,tag:c1ViWVbV2y/oJ41yX0sQXA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5c/lrwA9rZFj,iv:wKCtpVGT+ajCgv4WxfaZnS2JkMbKQh71iwhafNIhddA=,tag:hS+WS2ezLFweKUDsh7df+Q==,type:str]
    namespace: ENC[AES256_GCM,data:N5pCF8Y=,iv:MjW52bQhWYZBKmHLYQbnPFyIl8XA1Wdmwtpb8OJV0co=,tag:NPeuV0Oiv/d7+CX4Wb6S5A==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:NQG/6Den,iv:ic21IgfLsCYP4lZsTVMw2qX8w/es6ZLCxlQ8hBqdlgs=,tag:YeezEzZjoPBZ0O+RmR/b0w==,type:str]
    egress:
        - ports:
            - port: ENC[AES256_GCM,data:Hrk=,iv:OPlb8knBNRmHz5cDJFf/l2KMGdjf8DXUZAc8Gz5FZRY=,tag:IZSFY97/XKehoBN901mfww==,type:int]
              protocol: ENC[AES256_GCM,data:xmP1,iv:e95g6+U8WBZ841lq+ELsqzmymtC5M+M3ZVljiWJIeUk=,tag:tAEjwI52G2bXNdXlJLNCcQ==,type:str]
            - port: ENC[AES256_GCM,data:kSc=,iv:qWvAC/+h8uiUT8+939jM7rejLczu6dz4tkm2sXHAwo4=,tag:9JClh44g6zhrUBNy/z73SQ==,type:int]
              protocol: ENC[AES256_GCM,data:8L0I,iv:2ACcb6X+ywYDCrNpSR5XwhbN7g2/vZlreR8A1tVmUS0=,tag:hFPwXNvodW/0ZiTdKEKT5Q==,type:str]
          to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:3wV9Y+qye8Trm9g=,iv:YpXxzAefrpIZLUu0lIAkKkea4hykelbP30woSOsCRIU=,tag:oH33sYnjB21Ru++ekNuGlw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:ekjMzn0PhXZr1bNRXaIuN6tvnxE=,iv:6n8s/FdFGSfDNj2y4+QulIWjA69TvfBdV89Xonet7bI=,tag:WNyVhTXvN8R/OKBfNav5Bw==,type:str]
kind: ENC[AES256_GCM,data:P3Af6ajsS1GUVg9wCg==,iv:3KmyuOn8zV7Q7Y3cfaxcF88qSXT6Jt67F92Q3KCj1Jc=,tag:6Wc73hJqYzcqSWGgpkq4Fg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WeAqq8QRy6Y+/p/MOdqwKiBRiHIy,iv:AA5KkAf/TJfNMoodrjR+o0CBxAGz5SXvuqpHAtoRZp4=,tag:3/X9HDThMnuyubcQ3z/cXA==,type:str]
    namespace: ENC[AES256_GCM,data:DQC/bSo=,iv:zeLnMDHsEToaEKVavvRxoCpev7MakDbavrEXQNCa3bA=,tag:LDdD//AhBaANArCfspf/cg==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:flISRRaE5A==,iv:/YQ1j24c0epDTlzlC+GWgMWmxMy+wzm+HguL1r8ugRY=,tag:IpCQ7px9Yil3LfiQzxIceQ==,type:str]
        - ENC[AES256_GCM,data:rXhEJ771,iv:08lRsPLqWgCBgN2I62jdFZeNlBr5hCafVLyVJxn58F8=,tag:6KTFGsygIGLPs9rlf2wxfQ==,type:str]
    ingress:
        - from:
            - podSelector: {}
    egress:
        - to:
            - podSelector: {}
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:xBnPyGM5uBqduWxBi9KktJq/s7U=,iv:6rDLe8ONFE3VBCPRTd7Qam3JTI92Bb/A7Zccqdk7nhA=,tag:W2QmptiEFnmjIgFaj2ZjUg==,type:str]
kind: ENC[AES256_GCM,data:+8929MIPnv9qUhivRA==,iv:X0KuG2CyXeUdSe+icwg6t2AIFMmTGnq0DsSx4sqxRC8=,tag:FEp1D2cN8uBwJMSLFZkeNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:azpaSO4dckg7OvNu1VMfipe57w==,iv:2G7XSempTL2ARkjCnfusp4YKrHNhUnOKWDViorHf730=,tag:JsIo36996rkXGc8n18e2kQ==,type:str]
    namespace: ENC[AES256_GCM,data:un3e3nI=,iv:2IMh2KFKu4bgXsMqEy9rB0xWyB7Rld9xPbVXMBxtARc=,tag:dC/xcWcONrhKfH11GwySaw==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:hlr5PgrAmQ==,iv:XzFcm83vxRar2RsmMS9cpDeUDVt/UhleJ3TwTjHtbFU=,tag:NyyuHN0C24OJwAXgmbBp5w==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:sgfh+cx8ksdaE4V7k30xl9PD8iw=,iv:3iAv53E+xcrLhxESzbLGuowWA+738JXh6VlgPpfSl08=,tag:5Z7uHTuWfUg0N9MPEMSLwA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:whinRJHNNIiM/oiUfNfGgPuhwVc=,iv:GxDsZfd+W04+ZmMLtD3Q5S6NWQVAF+x0a9DIHSu8z7k=,tag:x7LVhIs3Z+Xjmq7f8rh3UA==,type:str]
kind: ENC[AES256_GCM,data:/vN87AOg5hTwzwl+ug==,iv:m36ihWTXgBdE6OPlV7J1XqVWuW6NCbRjHnWUb+B4f28=,tag:/fvoixNwQt8sQN0X9Pwg9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XaRNsJlmsZtLhRcRf5BERA==,iv:wsv5yAb6I/0duw1/tqezhJdaitc+Qooonwm6zunTQU8=,tag:uvKOsesVF1osNiIO4i507g==,type:str]
    namespace: ENC[AES256_GCM,data:KrFdbzc=,iv:IMzSckS6dsf0xoJ7W0XVYzlLoh1agMqYQaZyXeO8HBE=,tag:FxjdvGo+j2AIJ5uxbnjE2g==,type:str]
spec:
    podSelector:
        matchLabels:
            app: ENC[AES256_GCM,data:/9woI2GVz2tb,iv:WWglctm6sVifwRHSFHvAc964gLR/Zr1HS5n0JxTfSfk=,tag:voE17Bbd7mjYjhhwjvfnzQ==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:VOsspMF7,iv:9Zrps/rxHcOd0WVH08G63+3aj4oPENKmbOpfrTi1Scg=,tag:K1vwuyKuc7TwhziKbpNrMA==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:+JPVgZLk6YhX,iv:v0guC376AWHS14ZGvkDatt6q8LYc1a7cdSzdkcNGm9s=,tag:55EWoF4PwrvIypjFnpUPKQ==,type:str]
                except:
                    - ENC[AES256_GCM,data:jKsGNYcZ71KSYA==,iv:hKkmgQdnvtXSTczp1NROKLBUGXfUG0e8y5wf3VkXaiQ=,tag:AAk506K+aeFXCgefdFFEQA==,type:str]
                    - ENC[AES256_GCM,data:qqb4Q/j7hJN0F65gcA==,iv:PUkbvmtogVidiRmCgei/gTZy8AxBNKLz6d6H09562e4=,tag:bN1xzRiKhIfRUE54OJPEaQ==,type:str]
                    - ENC[AES256_GCM,data:22wln8+bWRRtjjWaMqM=,iv:u/zwlC1W4kpZQnrTax7c7F2tp67i+NESq9N/SSbqrJE=,tag:j2dGlrsy7qH+6j7fW5Lfgg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:C+1mKR41SGvmCvdeWoW/y8jt/Lg=,iv:c5FmP/fvqEIHRr2fhIx9tq7LanZOKrkgjzivOuNCrHY=,tag:o00pNDkTolHfrv0UAgRHOA==,type:str]
kind: ENC[AES256_GCM,data:8G+1RRG/RkjtcAmCPg==,iv:8lcSV0LODTNCKKG6doUTxyz6FEuaeAqBjV1ATSv4fgg=,tag:xUcJAb0WN62Vf97oIvQYpQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bj/o2dVj0Ryly51gjMcGCQ==,iv:Y/OdvE0YEn66VHm5FA/7XdIsZwEBYtIXnpCIWFJXgn8=,tag:bqorjF+auyjXxU5FsPzXIg==,type:str]
    namespace: ENC[AES256_GCM,data:EGo+AsE=,iv:LKIrHWsv8HwHr0ug0MJCWen3B9DOOYdLI0cJMXjlKtE=,tag:OCR1TgyY4pHr64LfH668fA==,type:str]
spec:
    podSelector:
        matchExpressions:
            - key: ENC[AES256_GCM,data:9L6K,iv:fkHl+GOFOMq7aIr2Uq9bwV/VDzN1dsnrosF4l9hnEQE=,tag:Hb5MdYcLSHptg5jch7V2Rw==,type:str]
              operator: ENC[AES256_GCM,data:cq8=,iv:+HjMub5/1YzjHex5snzy1sv9K4/VFFzpH22V+2tWD68=,tag:wWPLZwmOkljzG1iqyR0ycA==,type:str]
              values:
                - ENC[AES256_GCM,data:zQMJ/Gjm,iv:84W3ukLzZbsacwg+8sGyO9mJcucEttBEIAxUIA1o0fE=,tag:2HVxzPB3YAo1IgVewORNFg==,type:str]
                - ENC[AES256_GCM,data:+BPQ6wtj,iv:tpHpoIm6P8Qcv0ChvG7dnkR7yEF33soeMxUwe30fZLs=,tag:afljpn4q+DQDgVTd8RjCcA==,type:str]
                - ENC[AES256_GCM,data:dDPdlSeU,iv:ehgy018AeAWOFbMD9aVo21Y7jMj18w94AIkuQpxOjIU=,tag:PNq0uOrq/mmDXG2XIbngHA==,type:str]
                - ENC[AES256_GCM,data:rOTZUQAMKw0=,iv:1CAbXkWjxWzYoio4BvN/WFI3EOAc66/xazADunggOQo=,tag:mKsGIIW8abhJvb1NXFNkUw==,type:str]
                - ENC[AES256_GCM,data:EqXLhQ2CLA==,iv:B1FBDRkzCpkOXcujCCPAw428VweSjwaJthhA6FQjXNU=,tag:aNXQU2NncXmXmwAQZu+VvA==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:1Gndu9UB,iv:E3o2HHdnL5OMUmxvVkOtFhxkjhUDlp1XFvLwiUbFG6A=,tag:Xdu2HujFx4HkchNwJdWeNQ==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:MVliojAkecKEoBJ9RE0=,iv:m9Itihy4J2IMh3jEPIWNLj1B+HtQfhGTrS12kVD9p30=,tag:nAaJcxmGH7mOKMq2j6yoKQ==,type:str]
        - to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:YssCAhkd0hqh5IfAnFRsd3Qf4r0=,iv:K8u9bkFSSaXUVBj64saXfvRDyXvwjtMUsR0f5eReXkg=,tag:YmzPU5CtdtVXaJmR+Bq5Cg==,type:str]
            - ipBlock:
                cidr: ENC[AES256_GCM,data:i6J2tftB06e1celxMgc=,iv:aUsA98rj1EoyPF0fXq4mTtrNazrg0s49eYSb4Mcyjac=,tag:Db1LDKtFbzJkAdA5c7ZG7w==,type:str]
            - ipBlock:
                cidr: ENC[AES256_GCM,data:DmcQaIajkL3N0Pz1DIoM,iv:YGC4KCxfg8xs34ypAya+84/eEgDj7pspWRVGg2I0+o0=,tag:lyeP/S+1QOv0UPQjY38sBg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:YEUJ3yP4HrNDUjOYE9PfYayX2y8=,iv:lbffNy9tFe5LdSp1UczRvWyawe6xQKQRoeFNeeIXwyA=,tag:X1GqZZsatrdXe1f74W3GgQ==,type:str]
kind: ENC[AES256_GCM,data:nkH+SySYetxOgXugSA==,iv:yWQeVIgZJis3VljZ5KpHekPMXShwQ9H8oSxSZ4iIhMM=,tag:M6yRQ7tzbqnr4B1e3dHS0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XqHFEWg5tIYbRMZYj3zhHBeATpg+PnI=,iv:zkXBEg7Zl9y26FS0C6FmSabO1kWHEVPHMQDxuXEimxo=,tag:3vPz5Tx4aEFOMnjNhSoUkQ==,type:str]
    namespace: ENC[AES256_GCM,data:H0kszkY=,iv:xlP1s5F3IJuJ5MOSZu9eeDYrFe5iRK0upRPVV+FhW9M=,tag:uF89/mWkGh5IlrzeWX+Q9g==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:awybr0m4Ug==,iv:xeCint6OIvn019174D6GngEFQzBsQ70bnuyTHrLtX+Y=,tag:hpnZwtpwYEjlrlx+q/O8jg==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:2nYzl0rSDxPXpLfdxg==,iv:ZheqEXHoMNcfR+QlOkloJdgkC1APEBeWyDBlakvP6dI=,tag:aJgh4AK34Hl4wk40ZnrAvw==,type:str]
          ports:
            - port: ENC[AES256_GCM,data:kHXzXA==,iv:ijvPCoTEeaiJev4y9WnYxHv6OqdxXTcKTcqxGTvVvDU=,tag:N6w7Pbg+vLOm/UZOvpthXw==,type:int]
            - port: ENC[AES256_GCM,data:rklikw==,iv:7cZewKyH3BG18N4qK76F8p479JS7xe2Ts+wOhGRi4tI=,tag:eAa+2Gm+j9UWtWpZATLC7w==,type:int]
            - port: ENC[AES256_GCM,data:9u3lrw==,iv:XBe9gMhq8QKJj6g8aJ7hdqOStx+D4L0ZllDYS0YCnnY=,tag:51z/KnPbYM1h0uoTfvJ0Lg==,type:int]
            - port: ENC[AES256_GCM,data:Ix9gtw==,iv:FyIJHeeJfPKwFpu7GJqbJwI9fbjhHGPJrtj1vCvS7QU=,tag:Fm2kNXXFR8pBhK5iwBLdeg==,type:int]
            - port: ENC[AES256_GCM,data:t6X8dA==,iv:ncTylErWOESgsXAlw0CRhyETQKkhJxaGIIt4npgm2rg=,tag:KJ0N0TGt0jYObl3h/mrvuQ==,type:int]
            - port: ENC[AES256_GCM,data:8BMz5g==,iv:tM5WtqUtwX8AZVY+sKgY6qLS1UrxQIRxCuiz/wAFn7o=,tag:Rvvu/fi6YTVZn6Q+aAmokA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NkQ4NWxLeUV2RSt3TE04
            Q2lQYW5LNTdhN0E3OS9KUVJuSGFsVXBYTGpnCmF1aUd4Um9ReEgraStsc3hFNjVH
            ZWFRYWV0NXZIT3RIWlBQNDBsTWZCQWcKLS0tIFU5L1NDQ2MwcjZoQmFCZUpRUkZi
            cHVJWXZXZnhzUDJRbHNkWE9HbUdvSjgKAvR/y1IlmeptkF8UoDWS5idqqWuqPWwm
            gBvZebovMX8JnJ22P8q7p5HMDmhISkoBnH6EDEoYKwoGTuRHkMd0qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:12:14Z"
    mac: ENC[AES256_GCM,data:S7pBm5kUBn5AxPoo9XoxHQLQpZ2rrNsDQeSVUohzUDXQm+VTQFqXySc1byZXumdazLaxrjSPjDAxpkiL1Mgx7gl47v13T8B4tBjVK4ikwgxCdXW1V984uMeOor+s7ryELB/gOE94UH615m8x2/1eGlsJHsLGwfiGtx4HQgChU0s=,iv:0QCdNkiJm0pPFPbC/OvxuRKGvOAfKI/029J8RzX5ioo=,tag:MxemcmDFsXEvQEoz6gnlEA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
