apiVersion: ENC[AES256_GCM,data:tss2Af6Pb3wd5ICHjvDarDBcG9w=,iv:d5jhRFur7PKdkQxgNntB1EKqJR865oagHDBrHwgvEkM=,tag:/8ORhe7Hf9FYFA63PFWbJQ==,type:str]
kind: ENC[AES256_GCM,data:P47mO6IJrPgaIy3AKw==,iv:c0X7C2KT1Y4KuJ55D9j6Hmhk1mlxmYzML47+HTPjPu8=,tag:aqYcgrlqp4EWEhXCo1fXJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jTY+NKATYd2XbQIw,iv:Q3Jd15CBvdp8Lxt95gUtw8kpuORKhb+IqhKGtNcvdmo=,tag:DUqobcEGX6+MgS1sZ/ecLA==,type:str]
    namespace: ENC[AES256_GCM,data:1+KiEDY=,iv:HhuFa/dm9LZ30DZrE1kd4p6ffE+DKDVMpVVyvx8G4Yo=,tag:FOQBRuWIti2l9vilTWAu5A==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:RVmWZu/Zgw==,iv:63e4js9Sr5r/dWZp8Xz4/ltytFIrSeHxUkiD7DVgUS4=,tag:b8sHhJt/M0BhHv22mdQ0dQ==,type:str]
        - ENC[AES256_GCM,data:TwB+TIWn,iv:21L4XCkQI/TW9f12kr7p26Ym7N3+CBCpQNy/yk6EbBM=,tag:Yt+0jHCH+/WYaPyjFnSJpQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:4ZtZTbJIbyqJN3aeJHaz4d9HLE4=,iv:RTle02fp59jknz9rhH49Zc3dj9mWu586CAR7xMTo2Ic=,tag:C30uqEhcxhmRjZz7CR+0rQ==,type:str]
kind: ENC[AES256_GCM,data:gBN0L6K8D5bqRnSMLQ==,iv:pB5Xm3qKY07syMvzal+TJ2i2Lr+rgJu7gUXns5PP6Es=,tag:wMsF589sjsp7JWdo6jP4ew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JGN3TR6k98an,iv:OVrt5E1yWuHJWP3ShfuTikyc9BC/GIe1FvkVnwfhpJg=,tag:+mAutrp9KyezH3cleYMwPA==,type:str]
    namespace: ENC[AES256_GCM,data:yNaNcVY=,iv:sTFXyt+kZcQBVJZSMW5WXNBQomHoZGy+AkgOhRmSO5I=,tag:bzU49a7RqTgDfex3uOjZuA==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:tOX2Sj7q,iv:3vKVGC6ioawGCFm9mvzaaVbpfLFt4OuKi8glE+WTNhA=,tag:WBig0PHwoR1doG31+xQW7Q==,type:str]
    egress:
        - ports:
            - port: ENC[AES256_GCM,data:x4k=,iv:VX/Vrvbvfp9MhrrnKn+drTIhKuA6caYxQxgiiEluzv8=,tag:vFCTlbop/uN3Mrl0L5s+hw==,type:int]
              protocol: ENC[AES256_GCM,data:GAMY,iv:Y0y6sc50la0/EjC6ePv/OhS2n1EQVtq708RuUfAJg2k=,tag:k6K/YMIcnfuE984rcmwlcw==,type:str]
            - port: ENC[AES256_GCM,data:rlk=,iv:1+XH6aUS6YxTB5D0r6Z2IF6pOTWhOCq3tVIAPyn7Eis=,tag:0bmrZJ7lcHzKk+kbHhqsWw==,type:int]
              protocol: ENC[AES256_GCM,data:opkE,iv:DtDzDCJr58TSv0UR/WxN1c/mh2W3N8qrK2MrZpOv9Og=,tag:7AKaFK/d57f6MEPS9jkOig==,type:str]
          to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:bLexG7swCNKGaR8=,iv:/thjsmqF+xP6U5Yj2NxdfmHTwMQV0BqBaNDek7kxRd4=,tag:PaqDkIHSAUWlbZdT5T9jXg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:o2pyAawTy/EJzx/V71XMLvL3Cq8=,iv:VrUnCBl4bpKRzhOuWgw1IiMDOGU0nVHWNz3q8wCAwM8=,tag:uXcGjjd5zLAXiKBsGl0NtA==,type:str]
kind: ENC[AES256_GCM,data:RiMt81iH3U/OgLM5Zg==,iv:O5+6yvPr/PeYKvz9nsz/lh4fCwIEVB8JRnhZyvUCXO8=,tag:Q+ti5stiU53nxsXi+u+brw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+Xcuo0Ma3YaJAjGqY1pTOlRI2XoH,iv:wlHQYLnEk+UeAup5VuBy1BcU9keqGBE6TTkMzMgrGEk=,tag:ROsS2CoAJIjoEdV47byP1g==,type:str]
    namespace: ENC[AES256_GCM,data:FB63gGg=,iv:G1x5fWVkhCKiEGMAKHw4iQN0fkgW0AXqQuGKJifBcWw=,tag:fWfpXaI+GXvpKkqf5gAC/Q==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:3VDg3hhd1A==,iv:K2T5S7T7FXGvSz0whnRIpoER4jTRdCe/e33mYF/32JE=,tag:59x8MqsQdGbACQghpoCKbQ==,type:str]
        - ENC[AES256_GCM,data:KU6+gWEI,iv:wAUBfKEVLpEQlv0cf3ACtc8QoDszKALrOMCIsTKKKh8=,tag:IkCPkgKomtAV+uwI5AWCkg==,type:str]
    ingress:
        - from:
            - podSelector: {}
    egress:
        - to:
            - podSelector: {}
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:IPAbGwEGRn4TH4/jhLZNsTNU6zY=,iv:++OFKPJKYNPUbBdb50mowL2nztpCbPcqTWwM8VwMV4c=,tag:8/A9txjsbbGDdb+PoroINQ==,type:str]
kind: ENC[AES256_GCM,data:nplS2RhLSUQvfvw0yA==,iv:vHU4WPKdRjLsUp/Hm/1lLZtMv86m5OvpWZ5MRge2FKw=,tag:N4RgRIwjN/T45dt45Chr/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0+nXiqzFKVrQOg96ohJK6S6irw==,iv:zdCq5QWVwmqdGonFD1a8825yce4sHhv/hjPaHo24bF4=,tag:dWmgm0vR++2ZHpyHPrk1jg==,type:str]
    namespace: ENC[AES256_GCM,data:fwswj1w=,iv:08BqQTTNw7Twoa6TyvXVK79A/T31TQ78HhIrJk0dKR0=,tag:xEwTP9lDLvo6RY/3+stv8A==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:tBPqbKf/CA==,iv:/cnbM3soryeHrzECfU/8qsfCI1VKHZSmnD8DvZ+Z1t8=,tag:8fhMPWrieBt6AA0DfRW3bA==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:epbogRWXxiUBGVV8RUWKbNR3fsI=,iv:gnHsbTY+AKroEyUilsVLh5ku9GMFuWDLAw7JhKVDMWg=,tag:SH6WlN8gHR/uXuDKdKKFYw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:nzGrRbEFb20N43qI103gSQs+vv8=,iv:aZ1bA2c4d1BJrVbfX4Rovap5R2k++JY7ufAJ/4t1MvA=,tag:EDMqSibjbUGVY9VXXHRxcg==,type:str]
kind: ENC[AES256_GCM,data:jixvU7UlBp13l64itA==,iv:1ZHJ3JG5EVjcSzeGa0YI3VGsjKVd6/snrO0PEyq76U8=,tag:eRgtI9R7FVHKE5kqSEFBjQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OheUxTERnfGzMarh38H6Vw==,iv:Oee6+vHKvrmsQjHdJrBrDuOn7wmuCtgGU42hK+NhY78=,tag:U79ng568EsBZg1fbbisjNw==,type:str]
    namespace: ENC[AES256_GCM,data:3/D5u3c=,iv:StaFGh55WGJRr6HsyhVGQ5mdNOnTEKsw802HjSl/hZY=,tag:hHXiq7t56w1xEDvVwCrk8w==,type:str]
spec:
    podSelector:
        matchLabels:
            app: ENC[AES256_GCM,data:4xMV1elr2Uzj,iv:9Dg3PyiKGWYpB08Q/X7mJT2KfIeoHIHp99LiNZf+vCo=,tag:8+e90xRL4UMJd138WQLeJw==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:6zp5qOVE,iv:tqaAqGNcCcI77W+7p1aIaMnd9lrlkf1fFmUutpW9HLg=,tag:zsqAgydJ9lA0jHHPDG8Blg==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:RKUOQ7NixuK3,iv:m6q2gUGJ3B+xaeEnrFt1Vdi6MLcmKxOT56NbLePD5+w=,tag:LtdBPwdILgIzWhlPF+xT5Q==,type:str]
                except:
                    - ENC[AES256_GCM,data:Gw4Ty56NCpdhoQ==,iv:IUp6vgyyYmP4bXjVPMKoyo+xQ+DIdAClwyERb1Xe+Jw=,tag:hECj20rApy4KZgFVul5yqg==,type:str]
                    - ENC[AES256_GCM,data:+C2u8vaHElp+psuMnw==,iv:Hiih4vvZb0Yr6deeFEsk3o1/ZRgP/68DiZJQUZkEJh4=,tag:8agJtuolvWsBRE0bh8NgKw==,type:str]
                    - ENC[AES256_GCM,data:6Jmx4mZteGL/JYMrQ9o=,iv:8PGTWN1ZjXn2uf76wfD3l8yw1nTF1lqEoi42S8uf+nY=,tag:/0qyDNi+GTwVyGy2Og3HXQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:HLhCf/4zS7uX+u8qWWFhnnBVW4c=,iv:DiTonJZPZBtVKbCxEr59dsS/mVJmPyEUq0txImX1ctI=,tag:V/SATRcdKrUwUTMOnNFCUA==,type:str]
kind: ENC[AES256_GCM,data:qYHVO4eLvNrbUzuS+g==,iv:EBZElheWF16KiLyD6XiC9rxz0dn4x9OXpRnXPRYZz8c=,tag:WxHvieEGlWb4UTJG5auc6w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mgfalB5yP4MQZABN3seNtQ==,iv:t4xV57ymK0HeK5GjJJaJvgK7m3DTf5G1X5wgtMyvxbk=,tag:6hmAf/BO3m0d/0n95SbDcQ==,type:str]
    namespace: ENC[AES256_GCM,data:cxI1xrQ=,iv:yfbSdneblBnKpL8bdX8fyaUfCjKJ8EHX5FiCmuEwGQc=,tag:76mUDS5NQBqfmoC3A1xnVA==,type:str]
spec:
    podSelector:
        matchExpressions:
            - key: ENC[AES256_GCM,data:pZws,iv:bSIpMbZ4tsa4uqdCxilRDgePEPoDYxWSF8IPo5UtXtc=,tag:0UFTFbb8p55dp9seb4AYlQ==,type:str]
              operator: ENC[AES256_GCM,data:58I=,iv:9bT0ABRAupszMiaLq4cmeMlXLnLH8fsl4/qBeXsz+OY=,tag:AqGbGfyyqVKdc6qYTb0Yog==,type:str]
              values:
                - ENC[AES256_GCM,data:Jsni93Bv,iv:Y6USXD5l+grE8FwNgVK3TppdI8KBBGelXBw5BOgtMi0=,tag:AadyTioHJTY4LmywlikAYQ==,type:str]
                - ENC[AES256_GCM,data:NZsSZgjQ,iv:itHCU+mvF5x7ioSH7RQfd/QGUW984zuXsu4Sx1Ze0K8=,tag:lPKhQu72VxeKEGD4JF7WlA==,type:str]
                - ENC[AES256_GCM,data:LWjx4+pV,iv:1lwwFylFIdRMTJBMmJPHMo4nBB7zksJdRaOzHCbW9+E=,tag:VQgeE25ZjJ2Llw33WMh/9Q==,type:str]
                - ENC[AES256_GCM,data:WKOQEWHLvas=,iv:mqz+i3Gp2S6TJUKf9R5UpxPkbBkynt/HReyalDhh0/o=,tag:SJ5omE4gKIWiAeiXqvm+wA==,type:str]
                - ENC[AES256_GCM,data:zQNx8qZKuQ==,iv:UpMg9pvkAmeYSOzJ28fkoAVDaA/fI7wHbY+cryGDDEw=,tag:yNQMF2ysZyFYS7l2pON+WA==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:g9L+bI0h,iv:TN0P5tEz/1AZyDlyPY/y8mRZ2cO8CBXJz8Q3z7Wv4fw=,tag:UM4G4SlXXNHXY8kOivbBDg==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:vdI/YWlXbBu5/cFmtf4=,iv:8q8bkjxQYsIFMt0vXU1HZbh9236jjDS0BUaSnkdcYBc=,tag:mlv/lUV2lO8OMAasjPE41g==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Ymk1Lda4NGBoeUJMGdY5yP/cdD0=,iv:UNxx6a9pJmPxJ4mfTOfuH/dwu68HJosC1A0y4R2W2Pg=,tag:oIIzlJG38rMhNxmYJke33Q==,type:str]
kind: ENC[AES256_GCM,data:WNVb0AvyMPnw67kz4w==,iv:512fF+IijFJzgX5YZdvBFmciDW7NM6p99MS+ZDv3ACw=,tag:e4AYHQMyBkL67+ObKciwPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BsDhJ7UfU8ZDJ0GFWRULCCb8AwCLzT0=,iv:7uOC2WkLAqvg3UCNuWtLgg5SmyhmQrZjVMl74taWhwo=,tag:ge0Fmhsdcmei6CD2NdFr+w==,type:str]
    namespace: ENC[AES256_GCM,data:fx6Rc4A=,iv:UpvdoHug5UejrNK0Jy3FGtdeb1Cs/s/FeSxKLguWTQU=,tag:yEwjKtmbNxSnKLX1jMREEA==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:KgMkI4VCcQ==,iv:rp4fcR0xzkuaFxiYjzP5FkITt2ADcmeTdD/JLzL9exA=,tag:5zS0HCePXJsigVW6VkxdRg==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:2P1meVCz62XPJkrrRw==,iv:EnLo6P5f6OCvXj1IKUkCMXxjx/0c57Dk10ZWIZLwx2c=,tag:1TY7RWonm0VqxDdeVNsQ8Q==,type:str]
          ports:
            - port: ENC[AES256_GCM,data:b8In/w==,iv:Ex71dgr3JqnPb9VYzsqDpwqa8LqIoTLUfJTdCoVddJQ=,tag:imA3D7pjZOW2bVMYSs1W6g==,type:int]
            - port: ENC[AES256_GCM,data:Z7HTFQ==,iv:LzudY1t4rufsbKsBy9n20YilAAsIDJGc/B5OGXEW9zE=,tag:+nTo1QzaVEdjD/ywKaXPAQ==,type:int]
            - port: ENC[AES256_GCM,data:RqTjzg==,iv:BqZy8j4epDVzHaWc7V+PjfniMZ9C6C/OPfYeQpKX+LA=,tag:eCbModye4tZ2qB/bFQ0e8w==,type:int]
            - port: ENC[AES256_GCM,data:sKiOLA==,iv:Rv5CFSF00uN0m5oqb+eO3vE6Lo8R/EZx66ckvL/s+pk=,tag:zkocnX5fs+i3lfqrPUFBIA==,type:int]
            - port: ENC[AES256_GCM,data:8AiJ0g==,iv:6q3esXwua2Gfk/7tgEdcCtroNKETCsp2rSfBXM/FGiQ=,tag:7dPjTlRiODkK6DPCI0IysA==,type:int]
            - port: ENC[AES256_GCM,data:gQ0WnQ==,iv:Ot6IS15wzhaWdoYuQFVwIBNolRHwnxG+mP5S6p+aoog=,tag:9gr7vptVO9/VMajmjcKZ/Q==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBN1Z1QmhQUm1JL2VpUFVn
            Nit6OGdJMks4UXdiWmtrWFZsNGlMSWwrSmhvCmZuL3B4T2R6b1ZTL0s5MjFPYk9Z
            MEI5amJMTFBzSHl2YTUvM0ttVy9qMEEKLS0tIDZhSVg2OGM5ZHhWT0xTWDBNVXRO
            aWtieEtHR2lTTmowd2w1YytJZWJmZmMK+S60U6tYmeQyLwfBtV5tI8yYEZQU+Qyi
            0QwzqllBxAKrZxNINS03bH8s7atbr1WQtSHfhOrKye5n/1z6bv95aQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:BA0YzwgJ3KHQkkxFBWNrOfZjkqCe6t35OVPg8w/VQgrGYuUXKkDPUG0pyWzl6I30IPLz6sohsfclBE1iR7vSUHilTzteDzfqvmCuPORxw2iAKxHX9kmWVsjy4Ev2e20OQZXjdVDQCX+huvnbaYLdaG7Ac0Qzgzh+pNWjq6YPTP4=,iv:aKM3yFW8q9y0Rj98vWwVxxiynE0XrY10/8ZXE748g4U=,tag:zPPGKk2o7gfzzRFsnRaPMg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
