apiVersion: ENC[AES256_GCM,data:xL21pjZo3ZE3Q3vlARI+VQN/8P4=,iv:y5ZbJHTDHqqB2IwvQQF9EKl0ZJtxSiP9EashBzgoI5Q=,tag:raVeLKKtNEjpNv+z4YsdCA==,type:str]
kind: ENC[AES256_GCM,data:z7/BlG6YlicfCGDflQ==,iv:3vP4JK2cZs3Yu11axkDKYke/jMudSeXxBBbG+ni21Qc=,tag:eHPpkJ6pLTE4RF8sI4FLRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:E5iB82LpNJASOvEG,iv:oIGMUD3mzeEtIh+O09tGdZm82uaA1wZW3yTGJhKOdqY=,tag:X2dI0J2rpIUQ4od2hS0KBA==,type:str]
    namespace: ENC[AES256_GCM,data:4o8h748=,iv:hgeeVKE/jL60q4g46N6CnlkL+HkU98l4v51RCYJTgRM=,tag:AEbg5NnKNpAggw9SNqjseQ==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:V2PX6NDRtA==,iv:sT/hAdcEw/jMK3XW9vT/F3MKLVTnna4wmVYZJgt6bfA=,tag:tDBiM3f4FUZHl66/3w8How==,type:str]
        - ENC[AES256_GCM,data:eS2iQX5n,iv:2m4WhA/N8U7P8HUvpQ6aj01w7y6+uWDLLoVy0vO1Guw=,tag:/pSRVJTO1+9bHG74RJjM8Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:9JfTQKxWy2wc9mHWVPqze+HSUmM=,iv:DCEcvmnBpZi69LnT2oJ4l4oNQTTUHHWolUDkFCTFfZI=,tag:whQ+l3kvnJ+khVzxuwIHHQ==,type:str]
kind: ENC[AES256_GCM,data:EYUoBkxLJBMKfzVswQ==,iv:3DraP7bb6rIuXcqmPjiBcQkQ8QMufJPakxKnvPyMeas=,tag:r8HDeasfqMszTc5cirbgkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tCkB0hx3rIP3,iv:Z7BB9H8Vb+JqwYAjlJ74fNfxvmq+5ghYxJbB1AsMyto=,tag:ZgNdY1Pdk9Tnf65bCsPbzg==,type:str]
    namespace: ENC[AES256_GCM,data:3/utEP8=,iv:fEG+EVtljMI3Css+0vCsDdHBF0ucSC/12MJ369xf/4Y=,tag:YX7ezGBgO+hNkazDDD/6UQ==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:hru7+T6T,iv:aciA+zno8ntgVBWuqhiVOoSXbOuWwBokNN1TKWBcn1o=,tag:TY0Lk3xF0r0QLl/U4ywjSA==,type:str]
    egress:
        - ports:
            - port: ENC[AES256_GCM,data:1X0=,iv:eyaqI5u9UU3jewtwUmVYFls6L40FuuE2TH7SeZ4GAv0=,tag:uOPlvA2oVS+1zkVQsYUt5A==,type:int]
              protocol: ENC[AES256_GCM,data:GBP6,iv:RFIPAyZ7DNYKm8CzjosSI1WF2r6pCQznTi+fsd2WCY8=,tag:33/8/eraeWR/gCtmSWXXPA==,type:str]
            - port: ENC[AES256_GCM,data:/FA=,iv:EPz98q53/Ftsnw276yRjrujDlV6c8G8vzQplTgIa5C8=,tag:UVW/QQCDIGpIgkxxSbZn6g==,type:int]
              protocol: ENC[AES256_GCM,data:pBT4,iv:ajDyyaNSPVafDkJZXVWoApNXGanNCGtZGOKnam6o9zA=,tag:cApvss+40Zf2TC+t22VY8g==,type:str]
          to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:pmFqGiZulMjW4eU=,iv:RgnofMINoB/xsUdOQK3wC/W/lF56a8uM0lYGvn90wY0=,tag:DiVWvp0ki7fJBF9M9bqq6w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:OgTSku8DuMxY14rfXtj6/Wp/8M4=,iv:eblNS6DTsYweLNsxwBgXpOpQ6r2zCTtJ3vZD5bgSRKY=,tag:zJTD5OWMCvwAV1/K5NxpHQ==,type:str]
kind: ENC[AES256_GCM,data:Ebkw/W8KiLZtgwTngw==,iv:JORr9sELTHcBayfj101h2tLVVPy8P4A83Z2XvkEojOM=,tag:2ZJVvGS0gfbn/T57prGdOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4GwRH6m/uQN8B93ayrOUVOtkVDH3,iv:1zyPiIomk1MaLLaN0iAkMPd4fZKfruMcsoA8AylJ99U=,tag:SzW6qlz/6pMo11Cc3XCQFw==,type:str]
    namespace: ENC[AES256_GCM,data:kMXztMQ=,iv:Nf9lzx8BrpceSDyj9cx7fE0wk3CbEwLqsDMT4rLP0u8=,tag:JEoYblqJ/8lASYJPvzarQg==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:qRRMF4Ikuw==,iv:qFzt7yKYNTdTiYe0jH4chb0byRr3lQvjyvUFTMgtp98=,tag:F+EwpC0vUA0sgqqKJSNJQg==,type:str]
        - ENC[AES256_GCM,data:jGU3oHGh,iv:9tzCd8bTXWGwZ07aOp2GY6ioJ4QdT3Iwgy5ulQIKf70=,tag:NuTXAdpcb0Hmj7dyNRmzhw==,type:str]
    ingress:
        - from:
            - podSelector: {}
    egress:
        - to:
            - podSelector: {}
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:TGdp/Sfzw+X+9RKOu7q0lpRlq5o=,iv:zv5Oe0uF7LZ27fjimUgLVO06DbSZot2EIglPAMhGrUU=,tag:vLgoEYY00rRbPosLNjICqw==,type:str]
kind: ENC[AES256_GCM,data:O09vmncjc4Zuje9MIA==,iv:Z1W/wmObNfbg662UrgV0yJ7TYnPEvKfVCu9wV5J+y5Y=,tag:QZSTBkDMVOx/6H8+QNY/xA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:t2CZlu81WtG1H10YDBIxYshSpw==,iv:psW/4X0ZMA/xGG8E6gHtakaozCanCGd/wMp9QxnScHo=,tag:48uYvin9XfiVnEMdh1Ddyg==,type:str]
    namespace: ENC[AES256_GCM,data:Olr0cOk=,iv:VFCODvtStFo8Rwda+GBQowPtAXrcQJTLeYubekrjoyY=,tag:/smBbJsLptrx7y+yH6lg1g==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:zaaF2LRj7Q==,iv:pAcIijHjm5lLk2CHJTWpNVdFL9UUccsjWUttz56qiDk=,tag:h24CRO2TCRyezG36+Lz/Ow==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:oIgVA893wUlF286eHRVXi72Xv/E=,iv:SraULKEAAM49uhlMxCvu3MXOeEusukR19qFNMp86UkA=,tag:XzznaiQFmu/lE9OLI6S7bA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:2QpI77b8Bs0KikSYbfL0Y5IdXXU=,iv:1FyHoi+OcmF5SrKRdSVVMPcaKVEZgFhM9ELPBK+z0W0=,tag:u6jN23m7BusnqWG2qMyWng==,type:str]
kind: ENC[AES256_GCM,data:vaPbgPXPHdlg7QzW4A==,iv:yLY4YxvmbGstXC8WNO/53/pVZU8C79IPoVNV0cGS/6Q=,tag:J+JGnNq0cqd3y+L0nevZqw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l7UAlRUDZ8/RUTKZ34J5lA==,iv:TxrShjpgdNYQG++TAix+6Iw7+IIT0yf5Hoqv2Bi4cRA=,tag:eXcKzNw4hdcrOvypNwGXZw==,type:str]
    namespace: ENC[AES256_GCM,data:MUNfwYM=,iv:1fyn2T/s/2u5S9ry7c/PLC4KWJJO0rlCoRM93ntKYTo=,tag:N1K1+Tx7OL6iQhN6f2SVrA==,type:str]
spec:
    podSelector:
        matchLabels:
            app: ENC[AES256_GCM,data:uLOxHmhKklJ+,iv:tqeNdrQvgKddSrPPhECcugwLAVZDFIU3j0+PrWQYDog=,tag:GKPjCN4Rf9d0o+XQIlhFNQ==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:mUjnrxXW,iv:VHi7x8h1hqLYHI74TdEvg4jIXPwP1NFlLh7Cx6ZJ/Q4=,tag:Vk9tThpgpLTmVgsDl6KCHA==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:DpFLNOEuMRcd,iv:FvlDxB2sOCbKI+N2xtodFKXn2qYBr7yHt65+qCyf4ek=,tag:rAswwNT4Uc846qzGP9arWQ==,type:str]
                except:
                    - ENC[AES256_GCM,data:aEySHuA9HoEjMQ==,iv:TsUWTyi8Tn5NrEF0xflU0w1owdpv4r/hzv05tcfiTG0=,tag:YjVkE5r9t73Gw1TDhOU9Yw==,type:str]
                    - ENC[AES256_GCM,data:fm6NfZ4cQbJpvuvJSw==,iv:tiHAbrqsKhdG1sq18Sc1Q5fDu8sddKDMlCfd+kA79XI=,tag:Xj4dy6IkHxHnwGaiFSn83A==,type:str]
                    - ENC[AES256_GCM,data:OSNvrFaqLyOT65C5ZHw=,iv:Uqrvnz7oEqEzrwGHtk4tWz7HZ9//dR/UMeb2qp/H2/Y=,tag:TbEuw1NMtM2iJ4HFqHzrmA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:46FTgvMx7wEFcbxQra6RmGvtApA=,iv:Wclp+n1bGt6fJtiwCUiXovrkTbO6rBrKv30NljepqZ8=,tag:HE/LHCWDOGwzFBq64OUDYQ==,type:str]
kind: ENC[AES256_GCM,data:bbV8yQN4tgm1NEiMjg==,iv:61cXcvO9MjFcIzo2ieL/MKVq/CXn1B2BGGYK3qdoudc=,tag:ggOzFPLpmPx3Wq+QKv6neQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qeO5F2cgxB74WcoTS5aEDQ==,iv:lqIImHDD2u8dTUawzm81po5kjQPbC5SFvC/kO2EnFN0=,tag:COh3FNWHSgXWnG5D8NRy5g==,type:str]
    namespace: ENC[AES256_GCM,data:OFmDF1Q=,iv:3tBb/RjHtcFzzuj66714jjNPuidRrUSLvfrK9IWfRrM=,tag:5/5zV77hzuawTLtyhFuLJQ==,type:str]
spec:
    podSelector:
        matchExpressions:
            - key: ENC[AES256_GCM,data:KlGD,iv:9R2Bhtoor5Iip5LpO+2p+b4eH76DVAq+ISiSf6NNSjk=,tag:nEFsL6fg7d1ohG0UB43W4g==,type:str]
              operator: ENC[AES256_GCM,data:Xss=,iv:lBAwIkbTubZeGMhqDdWt+UOsX41VN55zjGouYov2iEI=,tag:NekHqexf3jKroJZRkwd/rg==,type:str]
              values:
                - ENC[AES256_GCM,data:2pEZK+Hq,iv:vej3BU2vg6ecbo1BmVNlh9lQripZN3x7MjM9PUQHBnA=,tag:ZcqoFWDDnEm1PcnCRFhHCA==,type:str]
                - ENC[AES256_GCM,data:+pvJ7Ak/,iv:F/Q/aP4vE18+BFkaX5kV2igzcXO9USezFrODSrVDvWw=,tag:DQ8UigkpEtblJZTHO+JRZQ==,type:str]
                - ENC[AES256_GCM,data:hmQnwCX2,iv:ChegmDlrApBJjuWu7w/GkD9q8DyGn69Rp/EPpDTrCzc=,tag:pvBvvZqmaLolYpty42pGVQ==,type:str]
                - ENC[AES256_GCM,data:jnAYzsMgCWA=,iv:D7+Uu2KqYLp4GZs/vAPt7+IoBtMUz02pND385q7YDCw=,tag:e/Wgo4ZYhHUJ2BoKMdyDpQ==,type:str]
                - ENC[AES256_GCM,data:vhajG/91rg==,iv:MFoSyR9zYz71Gt6XCNhWgf5F1G8gFUwS5916Puitt5k=,tag:whDddRxivLwg1QdaTgYWmA==,type:str]
    policyTypes:
        - ENC[AES256_GCM,data:iy/B7gzW,iv:n10rXBi3s1e0iOQ0+2s5RRLU6QxTIwOHxEC3ku9Lmuk=,tag:iSYDwB3LAy5ExUbEr9OGvQ==,type:str]
    egress:
        - to:
            - ipBlock:
                cidr: ENC[AES256_GCM,data:WZ8lkE7BFIkazpIkvJc=,iv:NU6+0eksQ+MTMNPcz2LHUD0jR3FCZx2PnArgH/LVYNQ=,tag:ItiAu8/F+AvxgXbMrrw+Qg==,type:str]
        - to:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:9rc74A9xDwfH9NpsLAG95BnzfIw=,iv:CzwrfzerobNgCMGFE8vYYavMOzamIfHyKgGMudoumqs=,tag:0FVa+HsDAkQp2fyLrQ0fBg==,type:str]
            - ipBlock:
                cidr: ENC[AES256_GCM,data:46Ae4nbVufn6j4etxqs=,iv:yMnJ+BFy5QXcp875XlHVjBgy8Z86fGMbyP7vOuI0wtg=,tag:aKph42AwAVaQ5oorVJ2ZWw==,type:str]
          ports:
            - port: ENC[AES256_GCM,data:Z5LA,iv:53YJBII3eNNVndffi1QgBpw6Yphl0EZ7bcdF9P3crQ8=,tag:xdjKyJxqHeBgSybeZ3cCmw==,type:int]
              protocol: ENC[AES256_GCM,data:n3fZ,iv:xfjP0VFDUHRBWSJ0y6ShIpWjc+Krw5wnZT/KvD9S+qI=,tag:c95x+Ctw2KiZLBRFIJ0SmA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:3RyN4QV34+Hi2azJtWJbQDY9oy0=,iv:R9eQGEsNi/qsLqBmGWJ+09uXmmvHT3r/S9me6T9t6Rg=,tag:PGlOrp67w0VUgPkAeaf/3g==,type:str]
kind: ENC[AES256_GCM,data:bJpgmTnL83J3nGRRAg==,iv:pYSqgyoIA0CJRkwBaT+l9bEho+i9BBvEzOliti0uvfc=,tag:aHk+UXpKHJ3H9seibn5Pbw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4vI2ra/eI7qPM19zspKLn3dXyYZ0x14=,iv:PBw6WrlXfBhgjHOJkz7joYEvzoLOaGz+MNN2hhcIYeA=,tag:zWvjc4CNPlPpSnGrFr3Dbw==,type:str]
    namespace: ENC[AES256_GCM,data:MIru3FY=,iv:LqkSBd2AugB7wWuf0OmBUBKHmS9qlvB1gkw7KiK2Rxs=,tag:Rp6bH75Enk9+byCLCNudvw==,type:str]
spec:
    podSelector: {}
    policyTypes:
        - ENC[AES256_GCM,data:EOXCgwwXvg==,iv:OpxG/7tfqugcCl0xTD/RgboHKHQ/uJKIj2FC1TbX/QU=,tag:CDF1FCcc1EqzkckprIJasw==,type:str]
    ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: ENC[AES256_GCM,data:oUomffDZvR8S7a9tTg==,iv:omlC+hCLz7yIXoCKw7FaVu5UIUEHz2eRxRrn9cNBozM=,tag:4oV86d2khNywdg34XooARg==,type:str]
          ports:
            - port: ENC[AES256_GCM,data:4r/gFg==,iv:X7/6Z1y64aaInHUE/ayTgCicV3y2q5H+bbdobjXsn8A=,tag:uz7bf6uDHFHex397izNtPA==,type:int]
            - port: ENC[AES256_GCM,data:MmkDTg==,iv:L8Ee5xOcGlHjV6gR7aq6vUGxtrquEhbI1W8dFPEr4i4=,tag:ltSyeN5Zawh2ycDOZMOFNA==,type:int]
            - port: ENC[AES256_GCM,data:EP9cjg==,iv:MbEBJ7k5b+s5ZNSi9539CH6D+yDfS8irC0+5RHPVI20=,tag:coTTQxcZ/vkxrzRyABhapQ==,type:int]
            - port: ENC[AES256_GCM,data:TBRHCQ==,iv:ddoyMyPCJJybllEF/C4YyzoE5n92iNrftyT05SCnYtU=,tag:hdgTDm4piI/aN9aD1aEsbQ==,type:int]
            - port: ENC[AES256_GCM,data:N9rbcw==,iv:ZNCHWGlfgeRsO0uRAzwWM3dSvg/5nbD+OTqFjlKeAIU=,tag:eiVzFIwC7BPhn61n+HDePg==,type:int]
            - port: ENC[AES256_GCM,data:WwbZdw==,iv:zgGXnoKZs1ojKY7a05rU3EqWSMM1PQJy6ZegSVhEjps=,tag:3xe/XiM61ScIJ4BJSenh/A==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNU10SG9Jcms5WnhYc25w
            L29MV242Zy9HaThucFlxSmJHelhjMGlPbURNCnJ4c1BiQmh5bEQvSW1PUFNsTkJX
            bmRialU3elU2V05za2ZsTUgvVy92NTgKLS0tIHIxVG9mYTUvQ2R1VDdvV0pudFpp
            bVBVNGlwQU96V1NmN2ZQOXlJYStRdVEKWLVqQm07s/VgtUpGKeq8sJE/MKyQLF3C
            l7+8cUoVzCPCPdVIfdc06iWtWeFiAsbH9KWo6GsXYrLDZkN3ID0fEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T04:49:48Z"
    mac: ENC[AES256_GCM,data:sEi8n0jFrCBUN2TXeJLQy4BN6JmAe/SJxEg3gHd5jud//BD3lJtzTChFEPRX2ZqIMrFVhWe07UY97DQq3DYa6n0V5dS/Z9/B453hAfqpcfu14QMeKDKp/f6W3P3a45E98a4mqhzC7z/AnNgY+ltHH89YyW6z/7HuVRiu5VuX9+I=,iv:kplFEZbiLJM63IbpC7RLNi2KU1QseF20mfuJQSQMFS4=,tag:6xR4f6Zxp+Fa0u2YxrVvNw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
