apiVersion: v1
kind: Secret
metadata:
    name: nodebyte-credentials
    namespace: nodebyte
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:9CwPM6+EIG0=,iv:SArv0PBppEuYbnEghmcIaBm32FkoFl5rqNrVaxbsZEc=,tag:UusiTkkOvB6f+STEtgIztw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Qv5kCyPbh+Y=,iv:vsr05MhQArd+Nu6t5z+c8s6agXXmvfxLrNPRlE0mXYk=,tag:hLWabJaF33VSm/LQrN8TFQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2U8lxTMZIZ1qJquIOx6GEqvN3sy2jPB4Em+lH4CIqj1BwkqV04PYHxaBQ7P0P74U,iv:hf/oryKFRexOH9XKFCzhFaTwF99i2fPNX94nqYvBLko=,tag:6h3xSpwvpZhFZ7WZmNvXaQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kiAaR93vbxyLLLXRIvTg9n6l2LeJGKwdcOJlw2U27AZKUUcrxbDnT9qQuTlkzktYn1E4pFyEt97Xna20BTKtZJuO3BkKP+bO2CY7fNCj48MwduqVnxJ7CHzWRnU6rys=,iv:Y5i6hs91m5gQJ6MmsJgb7czBbAL8ue4H+C0koOUJxsE=,tag:izmZ+nWNCVOXFvxKwGo6jA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:dmWXmSJFhDlWkHoj8vXlG+93ZFBU1ZOBJNcvJ2AWkDzeR4FilnnCCetCRCD9wE+AMhVeYM2I3wTLIviyem4kiQ==,iv:w1WEtAjJFrHNlzt9OrNP1cq4ZZU4FMM5vFRrIMqHPYA=,tag:AJRPb8NWo2V0iIf9oqdlng==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:mOs6N7UAJ2bKp9cQuGYfwCiSrFVy3W8=,iv:x7atX72kXX1h24wzA5QDul7F6f8H/Uz5GsnsfSqMZ+Q=,tag:yO6opoo5IkenbifULVTO8A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:xburrWsQP1LqkArUe/mjYU97oeFqyBWHQJ+hChgiCHc=,iv:OleMw8obj8VNLpUqAn4wvsf4QntzZZfNCI4/ea1P1mU=,tag:GJZhbmuGEU3x2bR4nyge9w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNE9WRDdMZ2FCS1NoQUEy
            bHkyL01YdGoxOFNjNU56OFl1VEZNMU54dlVRCllBeVdCdlcvdjlydEZTQjByckdQ
            cXB3M0RmdVNRRStCQUk0OXFTUHN3UkEKLS0tIEtYWVEzTGoxcGZiS2t3cmM4STZN
            TEQ4bkJaU05VRlZlMkxiQ1ZNNHVGVzAKt1boentilLzigwNQG6i7vKkXDQGsnPyN
            f3TayCqt2CKL421763oCQ+YQ6ycmQwyPtlyMcn9+HpkkYBeSPPH5jA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T23:08:36Z"
    mac: ENC[AES256_GCM,data:zT36R88C4EUKQhqQkTfjXu/IxGZ/slxGXxZMkCLXKrAlriRgHofRMjwRML1fPe2R/X2KoKGbmR7Wz3JwjvWJDzFPhPXIbL3iK3g9WXlc5sMh86nBQDhzXNKQ2HlMED1vHBriqBIkbsu2x2nN38PercuPp8OBojD1+6Y9uI0+eak=,iv:wZJg9cXFRobHUgdXWPcTTjBGXgSukAmog3N7CFJgmy0=,tag:unZWQiwKBaGeo3gwOcgSkw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
