apiVersion: v1
kind: Service
metadata:
  name: technitium-web
  namespace: technitium
spec:
  type: ClusterIP
  selector:
    app: technitium
  ports:
    - name: http
      port: 5380
      protocol: TCP
      targetPort: 5380
