apiVersion: v1
kind: Secret
metadata:
    name: technitium-credentials
    namespace: technitium
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:iqUfL5IC9H/LrQuev0sbprJsOoaOuPRRFUGHOjfOxng=,iv:3Lk0lPuWMuxkV1GKyQ59cOnFpHBVszRJNAD8bjW+ADU=,tag:0q6e3s475SmgWCK/FdskVQ==,type:str]
    pihole-password: ENC[AES256_GCM,data:XHV7eNESKJiM+g==,iv:NubTa9mkrr+n5helnkFU2o3ufT+7lWC66rIhsy46sDA=,tag:ucapzRX7tXLKmTUTl+c3/w==,type:str]
    sso-client-id: ENC[AES256_GCM,data:GoRnRz5GE665mdSLSDwaWVvlL4zU67DN6zDeWrGif362a4Ytis9Zsg==,iv:39P5MIU0nGsMiUSiJtWAfxLFrk3mPPdZc4raVtPti5k=,tag:Ur5GxicuzYTd9l9qkm/mPA==,type:str]
    sso-client-secret: ENC[AES256_GCM,data:60fXYy3gcaJl6kyldsy+DdQot3vAGkWNTeXL3DsNdx3eyogGCbWJ7DSTm4SjhUvNoQPkHVLsMQ/QuKz2atB0Fbufw5RT49+T2Hgj4CtclYkMnqx3IDf/6J0lhipggy+FwvryY7ON4Ty+XzGxRXUqilYHIGfFqNXgfhTlQKsLVTw=,iv:Fu1WGegvuLw/xVOnY5DByid5if7tBA1P4DlVfxsGV5M=,tag:toXt1fNmkfmzwTV/+vYX8w==,type:str]
    sso-authority: ENC[AES256_GCM,data:gtdTxRzFFDWB4V2VkaIzqikJCqUwu9ednHcq3Hb4Fjdde2nP76fdLU/+rJUf2/4Jneta,iv:dFiThrGZeDXFDg4gBibN7Ll85XadtyH6/kIWF7km/LI=,tag:MOxURoFaK9gIj5fE1GqTOg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY1I2UVE4WFh4VVNJdGRm
            NXV6S0ROU1prSlNZY3BXRjRPTlRlQ1RpeXlZCkc1b2JDNmhDalcxYkh1RXlzcVNZ
            dnNTSXVjeVoyOTdmWVVGd3lnQ1ZRTEUKLS0tIHhKTjU1TU45cy9rUTZNa2tlUmM2
            eXluR0s2QTl6UWRmaCtteTIrL0xBcEEKSf4FRqCeP4gHvd6xaZKqXaH2C0Et7Vio
            kUveNE6iTq9JDCje/I2ZmgH9cnasqiMqGlMIMIZJO3e4gFyD9CmLKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T21:07:55Z"
    mac: ENC[AES256_GCM,data:hAWhro3sB679pmoNAW6n2dfRUKTDLsT9TouHj1/4ap6tbOR5VYhGP/XIz7F1b8gOmkPMVxUwfbR/KGJK9VyK54ZisoDaN3OUP/PzQ70QvpoAX3DN+ZoDTtCS/AoTdVYucfU5QMGMy9H0OlCDZG1FjTg1d62IiUT3Q7HPLEPjUPw=,iv:8p6oeKz9SfgqBgi1oeCJ/lcGGvsFmIastb+xTCM+12w=,tag:JO778DYHzs09e8nI1Wkm5w==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
