apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: paperless

resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 11-deployment-redis.yaml
  - 12-deployment-postgres.yaml
  - 20-service.yaml
  - 21-service-redis.yaml
  - 22-service-postgres.yaml
  - 30-pvc-paperless.yaml
  - 31-pv-files.yaml
  - 11b-redis-exporter.yaml
  - 13-postgres-exporter.yaml

generators:
  - ksops.yaml

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.13
  - name: postgres
    newTag: "16"
  - name: redis
    newTag: "8.6"
  - name: quay.io/prometheuscommunity/postgres-exporter
    newTag: "v0.19.1"
  - name: oliver006/redis_exporter
    newTag: "v1.82.0"