apiVersion: v1
kind: Secret
metadata:
    name: mysql-credentials
    namespace: misp
type: Opaque
stringData:
    MYSQL_DATABASE: ENC[AES256_GCM,data:agXCSA==,iv:MGlZD4U4JmUFaSNXWplbT64bTvocZA8B8EgqJ0qnyLk=,tag:K8F6vgL912W4I+SHWwSMWg==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:16IQBQ==,iv:Z+Hk80+bZftgybQH15R6Ei0iT3TdfLgUsA6lRSpN23I=,tag:jVqR6N0zOeo0z325hdY0SQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:bHB95GDTSL+HY8Ibg2G10INy+wBphpzXvQnWAemMpLQ=,iv:f4RKwQOOmdCtUC2eKx+NOSvSkKViRRW+yQgMPv1QW0I=,tag:mwNi9AbVyZlEltWb2vJo6w==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:dVcY5wNyi5bonmxmXWTQdDAy/oqSm6nt9K0bLBJaNud8rE1V8ao9bQ==,iv:PkXVDdVcXdP8XN4hgWYn2xAXGYACbK0myPOtiZu/P5s=,tag:+ggm4btBCzEYZMaPIW1Nyg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1o0cTRCVnBYYWF1b2dI
            NlhjT2xDSC9kTmE1U2JPbXgveTYrSWYxZFZNCkFFclEralFoRjNpU2puMzNxQWNH
            VkNHUmJ1R1djWDVydDM3MUpGU0luWlUKLS0tIE5Pa2FZaVJBVEpqaVdSTDlLWndQ
            cFB6V0h0aVBjcVlCWlhuelljemtBOUUKi+5CeyGrWjARAsjYt78brsgU03zkBxSc
            sY5sOyryPF99TUJxNj84yfVUZxV8AQ0AzqJHjGLOsUSP/TVjk+vPWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T04:27:59Z"
    mac: ENC[AES256_GCM,data:Gu4LYmD41rPl1ePOS114D75CCAF0ceYA7ulOLgL+seopK2goX5x8EvThCu2YwNhE7jH8fHbdknGbRzgQLX7UgTD19oh79h/qhJ+cFmpzBZRFdGhCXtRraKmRN4SReXbhfgR4FYKBQNLRz6hmS8kvA5MQ+TYnre+5cngmGmSZCg0=,iv:dlj0X/PBWCC1NxkMKXJmUf1vjHkIXLoKVRS4XsSYivQ=,tag:Wc8kVzJX0gpnht8BZSTRIQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: instance-secrets
    namespace: misp
type: Opaque
stringData:
    DISABLE_PRINTING_PLAINTEXT_CREDENTIALS: ENC[AES256_GCM,data:pAr0AQ==,iv:atHUPl4vb5SSv4/t3Jz5kfqp/HDP6oSHXgMDJb6FlrI=,tag:5pdwEioi41yizUfP5TPFFw==,type:str]
    ENABLE_BACKGROUND_UPDATES: ENC[AES256_GCM,data:DlOCxQ==,iv:41WzM1YMUJNhk6gs9ZRG1rgDCxnoCwrzRJovCcF8xB4=,tag:BuL9NtEJQ/2V3LiT7Y6New==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:VepTHrwZEXyGDYqmirSKXvZvTw==,iv:KDoBUnzU4C55Knycm8ds2cUtf0eRGtNbOL5DXA8Adfk=,tag:+3uYvq9zTHwU6hSuELEMPA==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:Dc4v+As9Pbx/qrs+L1Bgdy0mCpYmxgRB0ibDkxFtDPYaIsYxm8DLjg==,iv:9WEWR1QI98lKggFsWpI/Rtb0kqLr9YzCuFFEFTFCJ8w=,tag:UcAdZdp7138GRXoSAeLnnA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ScPydB/Qlw0gj46Hvo9/dHxHArGMAEYTSoFzQg==,iv:9LQWM6HSj6W/ru/vhQOcx44IfjUry90+gzOUY2Se1xM=,tag:5xnEgYLNYgW4rGf5ikf2uQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:8BliwstRFYCQKf4VuJqR+kqDPGn9Dvvo8opkTqsl+FQ=,iv:1FXwS2ZTcYF17elL4eLh5DQnKLZ99mRnVnoBuE8smmM=,tag:IiP4Zdcg1RP36/bsi/F6Hw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Q1a5zYKF65GwEZjfrJJD/jfj4ZvGiFsR8i6sKfKduQXjR/1pkluOqAYgND+8jCbFyL6z46UUyHw10NgdoeVihA==,iv:XQHq9EIF2fjfZgHLtucczS6D6+HmnApSasEH3VMzUU4=,tag:y753omUMlPR8LLlS/GpFXA==,type:str]
    BASE_URL: ENC[AES256_GCM,data:wZSj6DwzSgOCmnBkXA5mIW2zU5sj,iv:q+yWwML8Io3WFO63c7ldLIKidsAP/KOWWBWtllhOiWs=,tag:of3Wwqd1CQFHSus5MwtnXQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL1o0cTRCVnBYYWF1b2dI
            NlhjT2xDSC9kTmE1U2JPbXgveTYrSWYxZFZNCkFFclEralFoRjNpU2puMzNxQWNH
            VkNHUmJ1R1djWDVydDM3MUpGU0luWlUKLS0tIE5Pa2FZaVJBVEpqaVdSTDlLWndQ
            cFB6V0h0aVBjcVlCWlhuelljemtBOUUKi+5CeyGrWjARAsjYt78brsgU03zkBxSc
            sY5sOyryPF99TUJxNj84yfVUZxV8AQ0AzqJHjGLOsUSP/TVjk+vPWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T04:27:59Z"
    mac: ENC[AES256_GCM,data:Gu4LYmD41rPl1ePOS114D75CCAF0ceYA7ulOLgL+seopK2goX5x8EvThCu2YwNhE7jH8fHbdknGbRzgQLX7UgTD19oh79h/qhJ+cFmpzBZRFdGhCXtRraKmRN4SReXbhfgR4FYKBQNLRz6hmS8kvA5MQ+TYnre+5cngmGmSZCg0=,iv:dlj0X/PBWCC1NxkMKXJmUf1vjHkIXLoKVRS4XsSYivQ=,tag:Wc8kVzJX0gpnht8BZSTRIQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
