apiVersion: ENC[AES256_GCM,data:5HJWFmgjyQ==,iv:HGXI4wqrZb14eULig8+jPa1BG3sb+ZUq+kA8LKuTWFA=,tag:ARPRzDlq3b9Pgvm/arFz/g==,type:str]
kind: ENC[AES256_GCM,data:zWmS6FFVkXOcYw==,iv:1/4bnqmuRLgSK0SQo9va6j5yuq1QbiW29/SsEkYuLB4=,tag:AjTYDQJn2iDSx73EVXnWqw==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:NUCci1X2eogb,iv:vOeyJEuzFqY1gpcbmLHIntLAX5RvCZEV5USdRElSoPM=,tag:+wL3iqr8VuciHaIpEKDZ+A==,type:str]
    name: ENC[AES256_GCM,data:RB4tEa8FF2/7,iv:G1A0RzsoXate41IWKvJqMHzndgiqiiIhetNTXPiJtsI=,tag:i9AxtF4ubSP9yKV/jY3A0A==,type:str]
    namespace: ENC[AES256_GCM,data:4mFtrL8=,iv:HhiN6CXcPAwKJL7o+i251888OHNGTu9mWiCTuJbb0F4=,tag:DqD2tFa4nGakrc3nwjCa0A==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:rw==,iv:Dnq91LCPtDZ40NOFgV3UXUzujw+lxeQQoevD9tZB28U=,tag:a3vWHHcJY2kLr4naX5AZDQ==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:kbEDm7AlqDEC,iv:HtsSgQo9SCzsQSuXHuAohaRKWx1r8vlM6VMMF444T3Q=,tag:AkjFJpILliB3JNyTJJTRoA==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:goCRScKpSaDA,iv:F0M1VL6D48CCOGYrDOUSIALXP0z+fsbT9JrYIg6aWsA=,tag:VVSdmoyBb7vORuuTzbk+BQ==,type:str]
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: ENC[AES256_GCM,data:lqZ1RfUCrSAmVOnQo9G5JpXGLWEYJA==,iv:6X/0SUrHXom3gXKlGTF3z3NJL9f1WhvqU77vZ1AUmmY=,tag:Nu7lLfvWraO2x/fR8HlhrQ==,type:str]
                                  operator: ENC[AES256_GCM,data:ZLDkMMU=,iv:9ckB1Y92rFV4w/i8lVSqxi4YTNlwWlv0a9TW647e9lU=,tag:fRzUdYdRYg3v5G/21sC1ew==,type:str]
                                  values:
                                    - ENC[AES256_GCM,data:jvkHf6CYD/j/bntl,iv:VFLqIn/w4s5Ro6g71flnTyz3B42s8/QBNyfXDBtE15E=,tag:CANmqvTSIbg/Xv1xTZlUIQ==,type:str]
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:/YaNBHbxuJnFfoO44YhiI2HwC9A=,iv:Ip6roI4MV85DMLc60KRZhoy5Cq7eu2f/WIjcSAeqhfw=,tag:SJ1kdpF9aaLcMiQSu1ZDlg==,type:str]
                      value: ENC[AES256_GCM,data:y+8tEtGutoBc2/3sbK6nnA+Ju7hTVls=,iv:5fUX/90lXZlF5n+m1WX86Bj+PosS6lvb2OQHyOeqaUM=,tag:5M2lNFb/aGO63gxodn6bVg==,type:str]
                    - name: ENC[AES256_GCM,data:AZR/krBzdjE=,iv:UBSvwq2RrFruxXMviERyR8MPcHc329oYfFXgTArs+oU=,tag:Y3tOAvAfOiWnsaQLtbk7nQ==,type:str]
                      value: ENC[AES256_GCM,data:IKeJ0b8XVQ==,iv:SSe6xailIKkQYdIXBlLUwAM0xfG7MsVxxLCm9rEXgEc=,tag:UokhCtOFGiCODVcBrJ4Bqw==,type:str]
                    - name: ENC[AES256_GCM,data:ExXubWcBXveqZ2vHY4c=,iv:B1c0ZrJNnDgLrw3FK8GafsxfmZOH4EeIzQdN5mJQptU=,tag:7WFCW+cZodyKVj+8RCY4uw==,type:str]
                      value: ENC[AES256_GCM,data:uxM7ByIOSnmC4fipRyzbRJYQhFmkjlwKwsnZpg+rHyteJmJ8fLm1NR32rGVvwlRGUz+FzSwjMVGPq7MEghOiOPU7ttipQj8KI4gddqbKlV6kbidQr5Zsx5BIkbC3YwKH1qU8VDJI1csLH8L7cC4swOvxp522jy6xC13q,iv:Lw6+1VT2dWWPCaSA9SqtJsjsNry3RFeZnnn7HR7eAU0=,tag:yakIXbi4OAtVqH56FlFMbw==,type:str]
                    - name: ENC[AES256_GCM,data:2snpAnQBe12MsugoFfg=,iv:Oh6BFjG4j/dqWM/83Q212nRhk5PR23+KPi+fJyZjOU0=,tag:pUe+P/rI4Hox9bJfSQpp5g==,type:str]
                      value: ENC[AES256_GCM,data:dNcf,iv:XHmqcF2qgB3/7gF5cTfM3M6Y7uAYfBFCWSJLJbUjB3c=,tag:D2zBURafuUEM7BhMvF2C/Q==,type:str]
                    - name: ENC[AES256_GCM,data:NNxhOM8agamI,iv:AD79PFvVzm0AA3XNHHBkUxZtLGv6Pjm8BkWn4DK1lec=,tag:sk8BZBsh3kyT5+Kii9vBWw==,type:str]
                      value: ENC[AES256_GCM,data:J/s=,iv:wnQUWJojBb+hjX9DT+k7YbKfwZEUyvmj0BGUk5zCp00=,tag:lc+EYOVMiHyt7Ki3XkUYGg==,type:str]
                    - name: ENC[AES256_GCM,data:iVBwHULNO2FNQ+lrEw==,iv:dzCilfAPyEhoBFwqn2i+vRvBCgmZvvatsM8YdOF6/zM=,tag:YL3pXsqWc7eiiZH1MApw7w==,type:str]
                      value: ENC[AES256_GCM,data:ZG6u,iv:yxnYXzj0+pHsj1FAXGpzMEV2z8+1dxFhBHHxPLCb8i8=,tag:EYsXzv2WRAYZURMv083uBQ==,type:str]
                    - name: ENC[AES256_GCM,data:fNyrkGiy54+T1w8=,iv:E997YZvXEu2d2Cz/KWHwYWDW9c2ZpUFSWUAXMqqI/jw=,tag:CQc5fUxsl6py4Jp/P//KXQ==,type:str]
                      value: ENC[AES256_GCM,data:5NwO,iv:taa66BcQ+E4KAOt0L75crqCSKZiTOIn6LsJ0eSltA9w=,tag:MMzSy7BHAWsOs1wZOPTJIA==,type:str]
                    - name: ENC[AES256_GCM,data:2P582NGahKcuWrJd7NGg9sVTpo0=,iv:tamNIklVQQswvKB/M0PT7j8BuInocmQkSk6kjI7Sbrk=,tag:dqPC4UTpGC0ExMl63vV7iA==,type:str]
                      value: ENC[AES256_GCM,data:WjIqXnlEPOHjSuf/+A0=,iv:Ritez4qymtxwFW0w7YcfcjQfPDg5AkCcBM+vpKocsAE=,tag:Pn/+JNAsUH7AT2AlKouoZg==,type:str]
                    - name: ENC[AES256_GCM,data:AM8we6iDaNTOOVYxgdcBIfK4K8ueVgozIQ==,iv:H8JfAz6pWECTOqEs4ULKcTQIZOmtDPogb0+6aG7Yhak=,tag:0k7NHvSntlK3OXNwrwYxOQ==,type:str]
                      value: ENC[AES256_GCM,data:zHY9IDPvjWrTXaIDe+w1dEjaq8OvQmJAScXjxxYZFkrIgQ7g54Nc,iv:hnPdkN+Jml5AVGqeUVvZtI9ZHyTH1La5B6gbJzc5Inc=,tag:H5vuUB48F33FUuJ5HKjVBQ==,type:str]
                    - name: ENC[AES256_GCM,data:qUmF9/lQm4bjEqBc,iv:Xm2Yg0Sibs1xXOU1EtiViH54tW3kYMtSAjiTsCQDP44=,tag:R7V/z41VhcrE014BAywqOA==,type:str]
                      valueFrom:
                        secretKeyRef:
                            key: ENC[AES256_GCM,data:V+Ky/bKM0ME=,iv:TcINvrBc0iGB/un1gY8cSIkbscbNeOXBq+Dbj/fCzD4=,tag:myGlJETUTbGh0UPUl5hTdA==,type:str]
                            name: ENC[AES256_GCM,data:Tob1MNxmFiWeuDBuCMRN,iv:RG3np6YeHVlYowxMgHUmuxR299JI73WpRJYRVW0iFXY=,tag:+emz3B3EZE4e6T0OuSYOZQ==,type:str]
                    - name: ENC[AES256_GCM,data:SNrcrtSY2M83+4xQmijwvQ==,iv:il2dc5wj0Pf0BQO8w0PkR52Nj7Z2UxAGgU1Ux9jyWDY=,tag:ufuFu/Ayf1OJq8AoLI9wqw==,type:str]
                      valueFrom:
                        secretKeyRef:
                            key: ENC[AES256_GCM,data:f2akghKV4KM=,iv:gePZw5djAQ9kvEye/8Xn0PlLQ+oTDi959twJT9VaK6g=,tag:Jn0JQYF1JfI/q/0Np8NZSA==,type:str]
                            name: ENC[AES256_GCM,data:+JmnyNuirvOZdwXhIId/,iv:icfPqe1sylPzfNnT6cJvglzryaadyH0WrFXiM9/6jgg=,tag:RLYdf/PqiGU4a7hz3xRB3A==,type:str]
                  image: ENC[AES256_GCM,data:ja9z2R46mgxXSfDLUXJu3FLJmy/K,iv:uPAmj5c/jqd/80zStcxgbbdofx6a7bxTCwBXLUHr/jA=,tag:KdXe517WyVZZNBAZZk0p/g==,type:str]
                  startupProbe:
                    failureThreshold: ENC[AES256_GCM,data:NX8=,iv:92XtxyJwQwJOxvZL3G5nMoOZ955jntGlKFHNh50tNlw=,tag:64OVCEjDaUq87jcETqHvYA==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:vy9CZrE0V4VUnotTHWoFwabj,iv:34AzvBdJp4kcLWHlQJvZgWzZSUcyFSd/s1cuIJKE/K8=,tag:037FF2kct5nzWLgtv+0ijw==,type:str]
                        port: ENC[AES256_GCM,data:gXaVmA==,iv:h2eUq1JH5Z5gENKciN9admrHt0Yt9hFgToj7K5UTkTg=,tag:l0eWnqunPnSbwhrMTpFnmw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:PiE=,iv:/D+momk1GRg45SdcSRFPjRfbgBq/LoJMmsdVU+R18lA=,tag:cNSV4IjBG3Lm9SEwtNHcYQ==,type:int]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:gw==,iv:f8v1pa79pmVpXbi1QlaXzY9sxZnbsBhiZfN84EKgQtE=,tag:a93DQfPbWnhHRKCpPdT7cg==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:jQg=,iv:nf/HgfkkhzSMiDVXY0XhW0dBZnKhQZuQgBRUssFhnrA=,tag:br5YZWWLpljbuWuNlLUQtA==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:xTs=,iv:doF5shWEYnOKNCwrcnPMxKAsLQRbRI8esxWfRC3Qb+o=,tag:gGmLQS2Eenq8ui9xgEbljw==,type:int]
                    exec:
                        command:
                            - ENC[AES256_GCM,data:Mvc=,iv:gmRFgYIdPKI9jFKphi4hKeJufPXzo3D0JMNWGIFKPXQ=,tag:TUUQQHNODcHH3qI6MKkxqg==,type:str]
                            - ENC[AES256_GCM,data:2cw=,iv:KmdHHdQzCJsSKg75IkKQCUsop6vAZ4NbRnaag397kCY=,tag:C2k663R7vOrihRqlM29tIg==,type:str]
                            - ENC[AES256_GCM,data:rYrvKBmq4Lzgy+2Sizq39XTYmLB/4ZKElhmU159U8EZl1vcC5frRtEouNfnLJRxY6yHn56GiCPcv34LjKsALwNCzhIPDKovCQRZm2nGe6Pj5M7hfG6x5PP2fZcMhHRpH5rb2XvqYA8i90UIs8RsYqFpmSOZwr40E2d2TGiDTZ4UPcxLi7w==,iv:jYSRlhznNJ/CXDoAgXlbpxiGeQGhdZ8G4dPA0iKS41Y=,tag:3EwctVjfobBmM3HhIva9Pg==,type:str]
                  name: ENC[AES256_GCM,data:pmRraiOr5Q==,iv:4o6mY2UU9jheVu8uDabwSOtQ5PXCpKEh1ZJXdUf+pq0=,tag:nKupQJsdNASNPZZ9klPvnA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:eOjF6A==,iv:aPA/fjs9m2mhbChDrZOIzuMEBepDNmtBRYLczQtTTXU=,tag:e7LTheUgBfhyAuDPxjL29Q==,type:int]
                      name: ENC[AES256_GCM,data:743eTUte3KPvrQ==,iv:TV4rSuYdcSu7DE2aYYU+KO/mdkVf1WkDiSTuZR71tO8=,tag:w1wYQZ+Vo2wmH2v1psrgyw==,type:str]
                    - containerPort: ENC[AES256_GCM,data:lWFPFQ==,iv:pQH7hdYFiWhpCd2+sA1Dg90G4Y+O6x1pBxq7wrjfQ/k=,tag:NBrKUpC60Hrjv6dSD0SRmQ==,type:int]
                      name: ENC[AES256_GCM,data:3EiaMN2C,iv:dAG3hxgu0SYQkhSsMTg6HVccni4xq3ZvPVNM0Q61+ig=,tag:qruAl1+qXXkBIj+EFKKtBA==,type:str]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:iw==,iv:QtftZNwUh7Jf043kuNSWbZd693Cz/8Xo4F9uTWYtsD8=,tag:RhGDW7fiC2jncB5mpIYDeQ==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:wrY=,iv:dv9VqneCtphpS4VEnqOY7ND4qkD7TNX4dBGMSR4Vlzo=,tag:j/5hw7WjyohJhpu5RI9K3Q==,type:int]
                    timeoutSeconds: ENC[AES256_GCM,data:cWo=,iv:5UN3plR/OhElJCOJwpbbNNcHEQ99RnZSaz058ECC/V0=,tag:EN7/pouBqKh8nHrhK8AOKg==,type:int]
                    exec:
                        command:
                            - ENC[AES256_GCM,data:j08=,iv:kVnuHyzvfMSjxVoQZRj8w1CQM/oMTHyEkmOd5fnB9gg=,tag:nNRm7IvrUmN+YXDsP3rrSA==,type:str]
                            - ENC[AES256_GCM,data:3X8=,iv:C1vUeF7tr5JqdAFRABZ0B/QVpkWTIoE2Jo/AOydckKA=,tag:b7QC8Xmgl8FSn9Wb2x3WdA==,type:str]
                            - ENC[AES256_GCM,data:PPOnMPtiLqX+JCpoCz2BJCIM43M2TwKpPKmLaQOx2Zp2pq1HKnsYuDSOTFr5AokB1uU9tXDpL+rYV+BAdBPRecH2FiDATzgJqb6demwVBOOkj9WBg8Te8Uk0BnCYSvdbrOXry7UMmejaitSeoHEltOlIbpXUudUG8vEc9xXPJ3pgjWzB,iv:wG7Ic8x3NmpwRtUdg3gw3qUkvQasYtDxNG/bbqnK3ME=,tag:KbMCVu461nkms52S2sicjg==,type:str]
                  #ENC[AES256_GCM,data:7dmsZQcNAsgV0DG+fE5/+Am+SstNLrnxeMY0Tg4C7dM1yW6M81HLmIozzQuPqR+FfXvHEDnOKKR88IwKtktQngc=,iv:+rlrYpuMAJZAL+A35NEESaGBInu276lF8EDL5GrVkR4=,tag:sC6I5m4khgdSOoOImkl+YQ==,type:comment]
                  #ENC[AES256_GCM,data:yJ9FBS4IxiYDTQxFdZ3FtHkkuPF/SmagWt1JXuTnNmxih1d9bTTA7aPdJ3Oa5EN+INj+/TH29Guv/4T5LperQ1LyuA==,iv:ml7TSbMIUtW/ikpPTSh3GPizwIsY12VBq1wc3ERz5jM=,tag:G/yEzG5ZuAX3j3l5dIk7mg==,type:comment]
                  #ENC[AES256_GCM,data:2t4oyUXBcidVkWPWJhPkjGLRazzkRBrx24AGWX1nn6CKwny69pmeRc6y3QDYBV2BTzxFR9lkRCFCmNfzM1QWq0NNqg==,iv:zS5lVWvoGA4MptfZLKHTjveADqSHb4u6hqxrt+OLWCg=,tag:1iWt0BYfRaDoJ3UIw86Y9A==,type:comment]
                  #ENC[AES256_GCM,data:RI3AIhyk+5t+Sjtbpl1qbsG3HtUoZ82zOHOjqGjUs0cyuiJ9e0MlhK7yNL0RTTOVR34XtaZmq2YwDdYQaMN2B+nbGA==,iv:XR2ReQdnirhACetlDfW8VmuW/jYe+/le10VxU678P+w=,tag:NSke8ajoLQTnZXKj6/XQrQ==,type:comment]
                  #ENC[AES256_GCM,data:WX5LgyUSqKmRWwrJtw8+j8pSAOyYB3aQL7ggj2/2X6AK/csg2GVPIhGgHMV3ojL/dv3WIz/Js4GIP/UyLnpag1a/ftT7,iv:DvsQSoaNQgCmv/8vzf8+9vHBShBVItEJSW6JeMqYOPA=,tag:r/rIjFLaekLXLrlqI4kblw==,type:comment]
                  #ENC[AES256_GCM,data:RWOqoJggT0WnNas+kZhksRara40YUTYmxpAglm74MeU8gHm7collqmzJNW1f1kQbAmHKHI5PN5aGXOOpI2jnfy15Pw==,iv:3qWcs2htdLkrivu6KmxuTOB9EBntWRaCyp3poCxN05c=,tag:w73gLA6eRsjyp4yICF0K7w==,type:comment]
                  #ENC[AES256_GCM,data:XnmcofL+mhAaFo/HIUfJWdArnxflY8z7DmWO401R1ierxA2tXuXs/pi69BnkmRlKpIJeqCdZdDDcBQOmMPODiCM=,iv:83VubkVZCgzpg6d+oNAwnkg8dmPaqlGFMiB53NhR604=,tag:/DFfh5JwX3wjarCtKWnB5g==,type:comment]
                  #ENC[AES256_GCM,data:CBr4YG6SFTfZ+S5D9PGZnQ2mCJv9gwrHQwzY8bop3Gt2Zs12cqniXFJwZTUfIRDMPw==,iv:wvNUJVV/ZLdvEpydUKrAthvfFrW9XKWPLcWEdNvO1VQ=,tag:Wme8O8r5MwMSMMzwEP7m3g==,type:comment]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:Mw==,iv:7B3JlUPDVHuqynYQXo1zHY8l7L6jc0rSsdpJlFG/0yA=,tag:Q2kFV3iyeq8m8oRoRCb5+Q==,type:str]
                        memory: ENC[AES256_GCM,data:Du1y,iv:IOUEpOJH5vcrHlmT1N6T7L7afAOPXALbuDjeI3mdHJI=,tag:VR27rvRnOXMDgYaDvepwXQ==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:kXkk+w==,iv:DDlya/PRfSvFvD2DVcWvynNpW5VZ5eHtA6n14q6FrUo=,tag:WpKfAMediHNQ07O8C/cnXA==,type:str]
                        memory: ENC[AES256_GCM,data:5s5shj0=,iv:HDouWjmrL0UcvOkBJ4cLGze+5Y2YF0LE+Y6tmGtzslI=,tag:Q7edTmgg1crYdmqIzGb4GQ==,type:str]
                  securityContext:
                    capabilities:
                        add:
                            - ENC[AES256_GCM,data:r43C8qBiBJ0L,iv:eEW9gYKFEabgYu9sl1Wnp5yKnn1tectC0PT538cUBVM=,tag:0IXS2MTFpp2igmsVJwYvlQ==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:v3wFLkniYYigwbVu,iv:dhm08zxGXuZOuUbWkHr1WMfQsIG2UmKCq35Z2w03zsc=,tag:I+CwbdiIK8wEN2iGh5fPVg==,type:str]
                      name: ENC[AES256_GCM,data:MwZl,iv:dkzJlvHHLgdkuPdf2YnyVVlzt1eYyXN+jcBCC3+2ces=,tag:WxAZtLoQKrYA7ybo6uMvNQ==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:q4lo/dM=,iv:M+1p0GivuJnEf58nSxVnY0SyjdCPFFgCq9++WOndicQ=,tag:+e0Vj348TKwy3lN+qEYwWw==,type:str]
            volumes:
                - hostPath:
                    path: ENC[AES256_GCM,data:/WJgXV1Zje8iv09t,iv:qYCl28rnj0JO9VWf2oAl0ofxTXpUQZmQxCtwzLtXPps=,tag:tkEQLlhjvrloDuyDwec+kQ==,type:str]
                    type: ENC[AES256_GCM,data:QIudgAtEcLdorw==,iv:BSHNaRnTL0FE8u1ROyDPddxG9w1YdMAEXIbTRlNEPvE=,tag:UW4EpjBJTn1eNmhtBUzlmQ==,type:str]
                  name: ENC[AES256_GCM,data:6FhC,iv:20zl2duXZbyGDzsnD/IJC4SjgZGQPWHv8xsLgkN4eYY=,tag:nZagHRNPzAHLK1c3Lq866A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL2huTXBhN214MkY2V1VL
            ZXhWOWFtcUt6SGZlU2NpRWdhWHRpNkNKeXc4ClRQRTVSOWJFdG5HMTRVL2hqVzVT
            TVNzaHJKMEZWb0N4M3pGZENLS0NjWmcKLS0tIGhjREpHeVV4YVM0ajg1VlNCY09G
            TXB6L0xRZkNWdUgvaVJLWVAwK1h3ajgKUhBhR2GDd8AgHGm/r4zY4LMb8CQ6mKOm
            xK/rA3vFrviXnc/VXL3EcquREMujjBJQ1HUe4qTTnumD0KrzHbfxnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T03:24:44Z"
    mac: ENC[AES256_GCM,data:P5irY5qGOa7rvf9pdWr4eaEO8fVS16AvvBpNFdbrgZU2Zf7Bn7JwOrT9gK/46q+ZtUqvMtKxAIOMv6GsdHnTu8Ikp2Sl1jD8DljLfzLf5rxnlMuqmkTq8qAqlWmZ3YwMvm6eC4gJxQD9DPtoU8tvWOlZh/ltp45W0OCbGZReS58=,iv:3iWrNcvXJrpH+my2cKfXL2t9c2bA7WWmXT1HBe/B27s=,tag:6bCwoHa6N07jRx8qfC64vQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:q1g=,iv:4UFWIi0GuUL9KvLiRdUg+Fyqk3L0Ck1eNzvZdJFhirg=,tag:N0BImujqVIxuwdDTjtGaCA==,type:str]
kind: ENC[AES256_GCM,data:t3+R8lXHhg==,iv:vg4QRfq7kEAwrz5yuVxfDts8BC/CIFJIoHZMMLNS/JE=,tag:stSAakIH/Mwk2pWwGRlT1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wsbNYAIFlxkP,iv:XuoicVPEVYvKbVDRchIUvEgBaEyLJ13Ii9aUHjR5I5U=,tag:NxCC6lF3h0Iul8/K+l6asQ==,type:str]
    namespace: ENC[AES256_GCM,data:LjLdY/I=,iv:vSZE4pnEQeDapGUQjjwFTLx17Oh03wpQQwpHvvP4gs4=,tag:VA7TJRocgW/xDruP5R0vHQ==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:t4EXMspcXZuQDA==,iv:hpaMxKrpaBYNJ98tJ0uy1t5/va5sJlhXM0y8m4LKfxQ=,tag:QpEteufErwD2AxHIm/Gb8Q==,type:str]
          port: ENC[AES256_GCM,data:kCm//g==,iv:+KvcSWIwoWjv5zRGJGZZAk4SwvpvCoD9BCIbZOBKEN4=,tag:Ecj9+dLFnn7BoLyo5+NjUg==,type:int]
          targetPort: ENC[AES256_GCM,data:agmD+g==,iv:+TVdxI9feAx92h2C3yc4UxoAMs7MGjKbZZGnzcxmpxk=,tag:lDwp4a8u9RKQ148IEGKHpw==,type:int]
        - name: ENC[AES256_GCM,data:rhk+ooQi,iv:z49tzvJWwx8VFIOXhYmwS+apEIrDunqHFbgdgBrjH00=,tag:OCj4IwGokPzPnfC9gqe2rw==,type:str]
          port: ENC[AES256_GCM,data:XD5NWw==,iv:ZgUq81CNAaJMCO3sSKZb4SDRjkW414S6izN3svNgnpY=,tag:aBdxnkHaiMQMik85SYXXpQ==,type:int]
          targetPort: ENC[AES256_GCM,data:lZPlyQ==,iv:p12cB2Xywr7Tg8+xYREyOCJcnFrYhv67qvbSAqw9RX4=,tag:8tsEOhjoozQR/2i6eDlH0g==,type:int]
    selector:
        app: ENC[AES256_GCM,data:xaAir+cPsVRH,iv:2wg1J1BOpVXNSanDJS+t13TcA6cU+7u3O5dgMI110BA=,tag:cYkR/Z6OqnEWHzckwKx//Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL2huTXBhN214MkY2V1VL
            ZXhWOWFtcUt6SGZlU2NpRWdhWHRpNkNKeXc4ClRQRTVSOWJFdG5HMTRVL2hqVzVT
            TVNzaHJKMEZWb0N4M3pGZENLS0NjWmcKLS0tIGhjREpHeVV4YVM0ajg1VlNCY09G
            TXB6L0xRZkNWdUgvaVJLWVAwK1h3ajgKUhBhR2GDd8AgHGm/r4zY4LMb8CQ6mKOm
            xK/rA3vFrviXnc/VXL3EcquREMujjBJQ1HUe4qTTnumD0KrzHbfxnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T03:24:44Z"
    mac: ENC[AES256_GCM,data:P5irY5qGOa7rvf9pdWr4eaEO8fVS16AvvBpNFdbrgZU2Zf7Bn7JwOrT9gK/46q+ZtUqvMtKxAIOMv6GsdHnTu8Ikp2Sl1jD8DljLfzLf5rxnlMuqmkTq8qAqlWmZ3YwMvm6eC4gJxQD9DPtoU8tvWOlZh/ltp45W0OCbGZReS58=,iv:3iWrNcvXJrpH+my2cKfXL2t9c2bA7WWmXT1HBe/B27s=,tag:6bCwoHa6N07jRx8qfC64vQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
