apiVersion: ENC[AES256_GCM,data:n/4=,iv:CKFb2vsNcBNk5j5t6lLWjxthhNWdRlKNYXSmPtisCh8=,tag:hHn/gEKstgyxZJWH+Np22g==,type:str]
kind: ENC[AES256_GCM,data:IyFy/Xk1,iv:SkADR03P50t9frx5dbydBCai2poqeax4qWWyxKXHhj8=,tag:+Plmr3+Y4XNitALGZYN+Pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6/19pRiu0XggfeWKbpKt,iv:SvD4Swju/mlSz76xlJO0vK66b6yHz+UtHLkKRWS1TVA=,tag:bLUMQT9Dz1qDezHRmC+rCg==,type:str]
    namespace: ENC[AES256_GCM,data:rVdSnaE=,iv:3fLrNnX2Qd/tfE1mqzp3FivK2gpmDNrwyjoP2m6307s=,tag:cvYAPhC0SP6v0f7caKilQA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:K9syyKsQUH4=,iv:0B95wbmkZ1sc0q55tLDhY9FsJ6S5b0sftgvg6G18UWE=,tag:lW2WZZPRQusjQnlp+Ke8TA==,type:str]
    password: ENC[AES256_GCM,data:do+wqPZxtxeuFQ==,iv:AWaDv4Ov9mNvRXvuTr2ZvHGFpGWKrus8yTDjzMUDK1E=,tag:I1P1OgtwLB77CIEMbV3nYA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdVZyZnN0QUptL1pEVGdE
            RzE4ME9SWmFrRjZ1M3BrM0JWby9HdnlZaWxNCnVTVWNuaHlFakdmOHNqQlZRdG1x
            V1M0c1dKZElXNGRoZ1dNWjNVZWNybVkKLS0tIERydEF1d1hQbEkweWl4a0VkalFa
            V0JxSERnbnM1MExzNjVwY2Nka3BZZHcKJgGPM6i0RFEfE1hn/lCjY2BoGP6R48Z2
            NW06NuyYVWlBathmfgb+NbOip/6BXGctgddWEufJITbReeDqRPQWbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T03:04:04Z"
    mac: ENC[AES256_GCM,data:kQDC0RUQV0l9VgGb+RUA433B548T58blb3/pkHxTpWo1KtYmt2R3E2XTwghCKdKmY6jw/iLQCTA3CIX5XoaNRgmj9oCV16/Gseg8F0Bq5Sedp9UVLI3EyCcOpkeW+r1o5iBNuDCb/A0HHUaT2jUesEZvPoi7LIP9+XVMOvdiTBw=,iv:R5SBoV9OyAxe5E12E3bzLB3EEHvgD6jhE8Xfc0OVt1c=,tag:yH09aRhJUpy79q4sZbrWpw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
