apiVersion: ENC[AES256_GCM,data:lho=,iv:BYqVPP/saGLSW62skVFnIv+h1m/sSFd4BbywKPFghsA=,tag:8tJaLHmxw+uMgogX3RJ9zQ==,type:str]
kind: ENC[AES256_GCM,data:cKQk3HC1Vla9uFQvrIiG3hs3CpRf,iv:UpcaXnUWsUBOAs9Ebd17X5qG4BMbQuNFkQY1WfkNZlU=,tag:F4YOHW4eUd1jwSbtpT/BiQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jGT6O0BCqhs4jwcchA==,iv:U4jQb+OTcsPgnBvzYs+J8YmPOWd1GTnkfuFHxqOf1ew=,tag:SS3sAa9OZOSyz5uzJXsDTw==,type:str]
    namespace: ENC[AES256_GCM,data:oA/vVqI=,iv:xy27A/rsLbSRSGl0ibfpmJr+bHDujNb5ADkcG8iyLT8=,tag:byjQMIEMB5dv3YmkuSgtuA==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:AGGOy1xrQWgmdxLSow==,iv:ve3zoNLe5Y5ULDdweve6LvOvrkaU0y1Cv8/rTD2e0yw=,tag:NKA1Kjxdm9sfulY5vsecaQ==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:523h,iv:5PSZfo3BjB3ALGNyhzIF+4zHjFAqAb0vqppjYzl6ew4=,tag:OqhjVVjHUutc9cEvM58ESQ==,type:str]
    storageClassName: ENC[AES256_GCM,data:LzRyzadNQb0=,iv:62aZyoSwASGxk7tbp3r2N8m3XI+sNG2qzszRwnQsrgM=,tag:h6pSeByX1QiB3OUs/ePsNw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZUh6b05DNHJSMWpBNVY4
            ZU5jdk83STVSM3ZOdTMzbmJlQXA3aitUcDFZCmJUdDdhazlOWTN3cjVXMCs4d3ZO
            aThxZE8rZkVwK1ZoSUFpbWRwMERxV1UKLS0tIEJ2SXRucEdiL2s4YjFPSDFQZWFZ
            aHBoWWpodVhDYnFIY0RuWVIySmZ4TkUK4zr6+wjqT47xXGkUX8podxf+DsWNZqXx
            f1Vv2/PRCqlpaduKGgQvPKZH3jlei/S6eZJsom5AMI7xGyNG0xDgEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:43:34Z"
    mac: ENC[AES256_GCM,data:3ctXJJK1iOcOt771dv/kUoGA1KruFRRnzCtWMltKnwvSbg41v9fN2GORPmdRYBhP5DXvh0wtLavvBYhMBAMrVWgieddTGm8+o8zCi6pTzpbuCkMsCKo2J6phT2r5V9C2185PcB9F653GQ+ZelTJ/XdTY76XAgUOWKMhJBWh9Qzk=,iv:RtBE4E0JwQQgL1FNNvQjObHJba01auZYOeVNV0WUPJY=,tag:g08El1y/B7xwB5s4w2A6Sw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:XOTvJ2V1iw==,iv:YGa21kXVFHF2URuSp3jNjzTZb+kirSWoYejcHkDd62Q=,tag:EAiJshyC3mburMgxygToZA==,type:str]
kind: ENC[AES256_GCM,data:Z+Sj3h/5R31bWA==,iv:lcw6/kfWkcZ01J3QHTZS39j7j2XF12iqVM2AOA5w1U4=,tag:hAmYNtMFp5C5Ek4yA/t+2A==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:FAPec1n3,iv:zdMJhsDatjRXYegKPitVt2I6gzMU4oGQvLL37Jq2LKY=,tag:viCBHSFViws4xwKTXef7jQ==,type:str]
    name: ENC[AES256_GCM,data:7Wv2wvAu,iv:s0iOrouRycbVsV7O+vsOyv3YkFJXRt69FPGo/LSo+1I=,tag:yi5R79UWzw7kDErIZfQmxw==,type:str]
    namespace: ENC[AES256_GCM,data:PVEGvzU=,iv:6KrHEcB6fy8CnSCosYBpUEgfdqp90UNu7MjIparTe64=,tag:qdTqR7DiI2GMSDeys+BDGg==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:6g==,iv:W9w0CVdB1GtqfW751fvwnAOP3253tqu8VRc9SU3Zj1g=,tag:A1znVqRjtCDsko+VlPSuhg==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:pPyDRuYF,iv:ayE/B/8D1UEN/HEOSHqX9VRS2BObanHb2pTkf5rCVSA=,tag:hsuccSf7FBlIMG8HY6gZ1Q==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:l0V0T+x+,iv:MImeszK+MM7MooUWLXquq4V4WzoyxIOOwGAPi9jxjP0=,tag:FRVDtZLltVkg/oNVtWUpBA==,type:str]
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: ENC[AES256_GCM,data:63zNZhXk7a+uoRpiHhqA0IgwEHA6JQ==,iv:nl/zF/ZvvINIW5BK5zOUCY2ZuNB7gdKr2qtJLSbREyA=,tag:ilpTT6PIMrVfdeDTsK8qlQ==,type:str]
                                  operator: ENC[AES256_GCM,data:ITO1Hzc=,iv:3i8hz7bohYBEZahNPJ67tEsAwKeGPHfaZfbhglvF+fA=,tag:sssftB1BHScq1Gjn40ms3A==,type:str]
                                  values:
                                    - ENC[AES256_GCM,data:bkJnKsc7hCq42T2Y,iv:NNsbBfYFQy+5mL8EowXIdenW9f+/DjCqgw6PULEMRVY=,tag:Ah+fu9oCc3x3hw16QxFIyQ==,type:str]
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:omhiYw==,iv:+xY7jIe+OhmQRuV/HbO2WX1gxtrvjIGkmm8tMFXQn/A=,tag:Je4mc7CSpsqRD+udqAkElg==,type:str]
                      value: ENC[AES256_GCM,data:SvjHhw==,iv:kgtOyGg7FfNtK5njiJS8MdAP+VXbzQU1LNCWttIXFDU=,tag:TP9mw/foZYcs7+AvSV4mDw==,type:str]
                    - name: ENC[AES256_GCM,data:YxUYNw==,iv:ZcIBKTL8pdrcZUECNswPyLj/umEIBbZHmU03GapNrKI=,tag:3pELwydrWFemtMdrww9PXA==,type:str]
                      value: ENC[AES256_GCM,data:3hBP,iv:S9gv67Kj32R8gIsSCTH48/do7M8Ot1hKVj/NWyJDCm8=,tag:Hxe63rNfOVlM4ArG8WsvvA==,type:str]
                    - name: ENC[AES256_GCM,data:7XI=,iv:MyBgoI0b5Gp5tou8ev5RwGe/XyM8YwPw5dKxW2gAm98=,tag:fG6GrB6eoj5uP/kBpdb3tQ==,type:str]
                      value: ENC[AES256_GCM,data:Utk6gQk5fgGzJwxBKlqTRw==,iv:Hw6YNJZU0IxYA8CE2zLAo7d97tzfDXBjDtyxQXqQHbg=,tag:j5KUyv8FA/CPH3rxxCUvIA==,type:str]
                  image: ENC[AES256_GCM,data:IMdzvVYMn6/6dwC7SEOLY9CIriHZcm2G3OhmRkMI13lF7ccWq0aqUOY2bqA=,iv:3vnVVhdLQiJY0bUr4BpPelSOBhuiVgou+PtEcsJn9CM=,tag:fEkR26Q6eVVzPFVKI0+NKg==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:tA==,iv:n1S5ykjeR4PXXAluDsDwZf4/i6WdBDcEt+RsM3pfNBc=,tag:0MhvgYY+G1JxnXCYqahSOw==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:Sj4mbGA=,iv:U1Wyf/4UBDF9JIthnEyFdHCiYeJ2neJztOlVK5vmClU=,tag:TSW9vtWDqEJ4nlO2fOIvYA==,type:str]
                        port: ENC[AES256_GCM,data:OukZ7g==,iv:rzOHfW/LsSVAYqbrIILB9wsb1VvfoHdV+I7hT5J591k=,tag:2GvS1PTCIIZ0by2zzm3dOA==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:bXY=,iv:C15YWizl0DvzwTwK1KvX0c44ctbO0sUxr8nUvYXXg7k=,tag:gxcOn40Lw/0rA8hDiXUMCA==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:rm0=,iv:NJ98l2jxTdwdqicdUHkNDkb4NcESh9NgtEt2fioPIkk=,tag:nmCAsLVlV7sFUFtOnxYJ0w==,type:int]
                  name: ENC[AES256_GCM,data:C0S/BvHt,iv:37dLhWoZtd0rwHy0k8FwP5hsShf+QT43Aj7eDsIXZvc=,tag:+1QMbJRV5a84hj+hoevPLg==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:ki0B7A==,iv:VWQoTKBGAwj4cMPjsUi4IPBgypQ4U8a+pnPFzlUg7Wc=,tag:Zu2pYFq1S/esPAOaAM75Kw==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:ZA==,iv:ftzxYG7hd6BevOdiG5N/W3dq1NfYJtvfLrX/O0IErR8=,tag:S9lMXAJnU49FeEoyoZelBQ==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:HYAvFkk=,iv:kCloNJ+x22kBSWg6X4PnOIgkh9DSt8co/h7EQSIbDr8=,tag:W5N74aQpGWQtZt/kQ9Wc4A==,type:str]
                        port: ENC[AES256_GCM,data:rQBMsg==,iv:/NVF9PtcggbVu6EDZ97Efcw9C3r6ok1YxvVqrRkhkxY=,tag:FwGQxv5PF2D9smGGhGiZ1Q==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:T2M=,iv:P4CX3C4fSV3iPSu7pUsolrOvKNr5Oz4ZTe0vjDo+bhI=,tag:jdbb3/nBiwRu33ajm6eO2A==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:Evk=,iv:Zh2oqRzYMTpSn/2PoTngZzX1BKn+2A6AMNIAb8v0+zo=,tag:F1U5RS0iGuNjdhX4oyORmA==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:zw==,iv:WRcU/sVldMjxDcNUwE0H2TEg7JaJ7AqtrBNaIzTguP0=,tag:nO1o04PohYJkE6JddVQSyg==,type:str]
                        memory: ENC[AES256_GCM,data:Qmt7,iv:uJKAAFpal0ZoCiu5xRzWa9MrMzuY2u7NndzKE/n2G08=,tag:mbrZ8GC61mdVVo/GW0VpxA==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:LMdtNQ==,iv:pN0P13Wg73WCOGafdoBFYN5nwCXySR2gfuhApyT9/P4=,tag:QE26RaejMCK7QG3Ddtvphg==,type:str]
                        memory: ENC[AES256_GCM,data:TjpLjAE=,iv:B7fG2TpE1DvXZ42DwKBKrCYUtbRllaJ0NbZZfW/JYFg=,tag:y64UbZA5alB02uy9Sf+dpQ==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:jNjpuAMLeA==,iv:DDbhI97OcZvG3HqTD5mXNpN0O6aAaLTEMU19MMrzMr4=,tag:9sTC4pEHB/8LWmqXGZICCw==,type:str]
                      name: ENC[AES256_GCM,data:obbJuZfH,iv:/Kk5YWRAfbOI+JtFRE/z0Wb1oRUVOqbcNVrgDohEjDc=,tag:J3rlmUGHaAX0OBOo4j39tQ==,type:str]
                    - mountPath: ENC[AES256_GCM,data:/j5l,iv:YfCVzBqAzWOX6cSR6zie2IEd8yJYvT1YfZtcZt5WDAw=,tag:gkXhDaZW3yUfkbnSZSKzNQ==,type:str]
                      name: ENC[AES256_GCM,data:Xzonv7k=,iv:78KYs+/v3Iq5A3SvqPNvTAMe2ghv99PCHg1HhR/Mwr8=,tag:EvlsC94TDI08TkPSNRMY9w==,type:str]
                      subPath: ENC[AES256_GCM,data:yB2OzFS9Q1A=,iv:lKjgNoVan7/KByhd6+dZmj/MmyH/a2BQ05GJeuEDcpM=,tag:0o/CQ6Pw+jT6nIZOSshbGA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:Qu8OKjrT+wGQD0OoCWk=,iv:EYzSBNephWhj6lWUb1jn5ol1swW+i9xSWYMPInp8rO0=,tag:cgFKJVJs0rKHz5UZScD+nw==,type:str]
                      name: ENC[AES256_GCM,data:6URw+/k=,iv:a06mePpJNT850GD0c6iw+lEBidAub/5YWJZVFhlf+Uw=,tag:qsZOtUoFDX94LbLDB8awVA==,type:str]
                      subPath: ENC[AES256_GCM,data:vsqlCf0+bYvA2YhgLOFvbshhfqpI9A==,iv:egN/gjAfL0CqHvVjJYaJbwRHCFufnMtvqeEY+TVFnaQ=,tag:fjK4lfDI/bcfhXIuw7Dcdw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:qEzVT652NZlxpw==,iv:vrk7u4FU7JsW+6BT3o021B5a3BUsVQU6LjUPkur/KWs=,tag:ob65HfWn/C6aMFuOXreUKg==,type:str]
                      name: ENC[AES256_GCM,data:z2QpHdt7FDeq,iv:Hl+N2vDOFvwnyyXdxn2aPEoyBHvDBgmGbLwcIn+4tC4=,tag:DFyk7O6RZRRRDLgBwpZrVw==,type:str]
                      subPath: ENC[AES256_GCM,data:1yuKtQOGjc/zc4c=,iv:rZoUXp/5myRYa593hFfHPvgEnzB9ZMSoZ96gTV+IJsE=,tag:T9/zQQVlbJbuRI5zeaULYA==,type:str]
                    - mountPath: ENC[AES256_GCM,data:EDcoDjlcThTg,iv:NcKfPI0TzpT2UIwmrDU0In4ytt0SJP70ol0P3alht9c=,tag:7tsVAiiytTs3fWA6EuKjQA==,type:str]
                      name: ENC[AES256_GCM,data:1ytez33rXRzR,iv:YPrWcflUmlQjZ6VPquYNoZwL0TzeKRI09HYoIeLCd/4=,tag:6h3T0bAf185yC6ZL/CdXfw==,type:str]
                      subPath: ENC[AES256_GCM,data:xOegtG5pqR4=,iv:5WBKpwZcrU/mAJgWzV+iFqvKh5oy1yKaVSXYLO+bCks=,tag:udSZCv/9Lw3Z453UPkllyw==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:6MWGBzU=,iv:GnKEJKf3bbdoP2V/cP5ZE5vt8TSMNWzbKIPLZfD1Nhk=,tag:rV8sNO6+JJtGTTgOxef9/w==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:QmKrGWqv,iv:ua6cWWTNy/e2+06ClqHd0sBP2jUn3Vrx7gCyuJCD04c=,tag:3Pg0LRI0+Q8zLCbVxCemSQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:eGFMjV2X/P2ALhuIIA==,iv:jNN3WLMLnfJ2+TjQ1Jr1tJ/yQJKUpnIxhjJ6UOkKKas=,tag:05uGk97btMDiqwClQK6EIQ==,type:str]
                - name: ENC[AES256_GCM,data:XigDey8=,iv:biAvSJiEHiqqB37AX2S8mb4cC5o8g+/4lvItuD55xBI=,tag:7POFRG9ECV8k4S4i6n0Ozw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:qyxGf7Hie84d+Z4gp3n4MQ==,iv:+XdSnBX3wKEJfv5Les1Unk/7ZKcPZTONo+JgPCNoFt0=,tag:8yScClCeWEsm8NhGJ0/LcA==,type:str]
                - name: ENC[AES256_GCM,data:uNoatRkEgayZ,iv:R9Ef4tVaIPkAyR0y7N3blyK1HFD3Xom3RqCa+cosXQs=,tag:7ChBmPXfK6FnUX2LjcZA1Q==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:GnHyAJ4V5f/6sicpgS3is9qP3ek=,iv:jS2LnVxZv8UfjvW40egNdUVGkAxExbHWHjiPS1iDZ+o=,tag:3VaGZAVpH9FF17/U6YY0SA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZUh6b05DNHJSMWpBNVY4
            ZU5jdk83STVSM3ZOdTMzbmJlQXA3aitUcDFZCmJUdDdhazlOWTN3cjVXMCs4d3ZO
            aThxZE8rZkVwK1ZoSUFpbWRwMERxV1UKLS0tIEJ2SXRucEdiL2s4YjFPSDFQZWFZ
            aHBoWWpodVhDYnFIY0RuWVIySmZ4TkUK4zr6+wjqT47xXGkUX8podxf+DsWNZqXx
            f1Vv2/PRCqlpaduKGgQvPKZH3jlei/S6eZJsom5AMI7xGyNG0xDgEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:43:34Z"
    mac: ENC[AES256_GCM,data:3ctXJJK1iOcOt771dv/kUoGA1KruFRRnzCtWMltKnwvSbg41v9fN2GORPmdRYBhP5DXvh0wtLavvBYhMBAMrVWgieddTGm8+o8zCi6pTzpbuCkMsCKo2J6phT2r5V9C2185PcB9F653GQ+ZelTJ/XdTY76XAgUOWKMhJBWh9Qzk=,iv:RtBE4E0JwQQgL1FNNvQjObHJba01auZYOeVNV0WUPJY=,tag:g08El1y/B7xwB5s4w2A6Sw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:E/g=,iv:T1HT5Ms32qdmIw9DPPQEhMy4k0jDFqvzvVVOsrg+f5s=,tag:X6osjYQr/B/mqhf9JjR5mQ==,type:str]
kind: ENC[AES256_GCM,data:MyXgTOK6ZA==,iv:CgoBv3ZPMgRFENmnhZWOhr+ZRMelICfF/z294O5LiFE=,tag:+c0zByrI+GBIGTZnZsy/eQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tKRX5oUA,iv:fLAB3WdHEYvqUbwm8Tn39xiQPvwcBDrRokzXUtetap4=,tag:rSnNlPa35QiopFI6WTWepQ==,type:str]
    namespace: ENC[AES256_GCM,data:Mha2y6c=,iv:lFr9P/rkCNX1Ja8/Z0AosOw/X5m8DFlJ9Teh2MUC5/M=,tag:2l39JCkzIPPRY8dVGix/zA==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:pjePZA==,iv:F/reP1rRIaCnSX/IX7HHMqv+6A1hs+YL+gdNwB2beHU=,tag:YCoPy+SFNGnNolncfBZWZg==,type:str]
          port: ENC[AES256_GCM,data:+xrqYw==,iv:yVO7KTmk4r5CqLfcOBw0gVS71U+aAUKA1TcUpdknkog=,tag:+u+v55g1GVb4lupiV69+rg==,type:int]
          targetPort: ENC[AES256_GCM,data:XQIy7g==,iv:5ntl92Uk2OHYtfiqBl/lxbOYT1JRhRrA9Cz3m7KuHUA=,tag:k5JCXlTsrQD7DcjU4TopLg==,type:int]
    selector:
        app: ENC[AES256_GCM,data:X47iC7k3,iv:uiFl24svng1mBLDz3RcDdVXSlfVl2EzCgTQqE54W15Q=,tag:mun51O+OLdnYOccYhHLj+Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZUh6b05DNHJSMWpBNVY4
            ZU5jdk83STVSM3ZOdTMzbmJlQXA3aitUcDFZCmJUdDdhazlOWTN3cjVXMCs4d3ZO
            aThxZE8rZkVwK1ZoSUFpbWRwMERxV1UKLS0tIEJ2SXRucEdiL2s4YjFPSDFQZWFZ
            aHBoWWpodVhDYnFIY0RuWVIySmZ4TkUK4zr6+wjqT47xXGkUX8podxf+DsWNZqXx
            f1Vv2/PRCqlpaduKGgQvPKZH3jlei/S6eZJsom5AMI7xGyNG0xDgEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:43:34Z"
    mac: ENC[AES256_GCM,data:3ctXJJK1iOcOt771dv/kUoGA1KruFRRnzCtWMltKnwvSbg41v9fN2GORPmdRYBhP5DXvh0wtLavvBYhMBAMrVWgieddTGm8+o8zCi6pTzpbuCkMsCKo2J6phT2r5V9C2185PcB9F653GQ+ZelTJ/XdTY76XAgUOWKMhJBWh9Qzk=,iv:RtBE4E0JwQQgL1FNNvQjObHJba01auZYOeVNV0WUPJY=,tag:g08El1y/B7xwB5s4w2A6Sw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
