apiVersion: ENC[AES256_GCM,data:kts=,iv:YkZ8Tkk9ZA6QQOG2EHNrl2omqYoSqWO3IPzjVtWXhZk=,tag:1UCV2C/jKVuFUpHdqMFy3w==,type:str]
kind: ENC[AES256_GCM,data:v3wwehpvIzw1DahwnMdWHyT2NQrX,iv:0azDARw46GGBl0ZDoRCLHEURQCsxX4TCzr+NRQChQLA=,tag:NI9HB3QeZYtQkyZZnfNchg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5KC4inESUGzwUbGkTos=,iv:w8DmuDiydALl6EENvP7CGC26JAgvpu8mtToDO4wO82s=,tag:g8KDFu+wOu9AeD1j3XMdEA==,type:str]
    namespace: ENC[AES256_GCM,data:OLf+xXg=,iv:k3Dt+Glbabt2k94zRV2fL6mA8kH+MjOyGdT0NyUiCNM=,tag:c0i9mF5/B+ZWbzIl89nbpQ==,type:str]
spec:
    accessModes:
        - ENC[AES256_GCM,data:wAFi1BKFDVzMWM8zMQ==,iv:r8VPfHqkT2MDIyQVoXCPqtGbD6ewiEsR/J4dzOsy0GI=,tag:HDBBqo8R3LkpmrUhcqmkJg==,type:str]
    resources:
        requests:
            storage: ENC[AES256_GCM,data:lXc8,iv:FhRFii2uwrZjpSDy14I7tovj2W6CTAtpTWDVpkHwghA=,tag:ep4zPCwEhbBZAs0L7Zru9g==,type:str]
    storageClassName: ENC[AES256_GCM,data:uRC2GN9/O3M=,iv:IKD4L3j/y2hIomTSvdIn5YM1D1XQAJqmsDXZnjPrjcs=,tag:vRFK6AyA0Z0YSYEoxJUmOA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ1ZIRm9xVFRGUHlxQ3o1
            WlNQeUQwUmU2dnNKR3pidXFBYm5pOXZNcDIwCkpHRzc2djJ0UmJnWWx4T29lMzIw
            NHo3aEhwajRrNDRncFRsVWNINlE4S1UKLS0tIDBiczZ5OC9hMmRzUlZ5MTJ5eUpl
            SmkvRHNETFBYdEhhckdVcWhtM0libTAK6plrlXVwLBA59JK6bb3Fxj1PvcWynk3c
            uSkGTYfov8wL5ht2ADkM95VcRBKTjTcVBRGcHanV1+JZRtmZEU3Tzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:7B1Q+vNF8le1LMdww6p9ksMiepCS1ysM6QmEHxCLI1yABcrUJJ/0VVNDpk2D+y7kXcvtFvaucBuhtN1Ye8OL38JKoDWtWwxDuR1kp363s6bh9pzT/+XCkOXnryK/bIIZqkjsNEhbyJTpjIPUmOxGjEggfNhIpXdDOkZFhc8P5kE=,iv:qRLVSxDptUEkKXg76NeIMmkpD2U/oleJ7HVPRx35aWM=,tag:M/2nnRzArV5NdFtOfvMpsw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:vL4FZKZK5A==,iv:Y+VNeMUSVgl12378WsZ4cu5Ko+g+oBMQ7Oti0ohbQYY=,tag:GbFlGxRbIylrylJaiU5fAQ==,type:str]
kind: ENC[AES256_GCM,data:C3ktrfvYdlZ9hw==,iv:3TAWCqMdqZ+qryyYj0HYYjxBwRP2u4XioANArO6s6+o=,tag:Jjfmi/r0xk5/2BwFYDqhdA==,type:str]
metadata:
    labels:
        app: ENC[AES256_GCM,data:dWLm/eJh5w==,iv:qGTkfDoSLcH9ox+qyOQR+t8+Vo0ofbfCOZhg9qAo2gk=,tag:O3ir2zJoNMOd0BJhp5Mc3A==,type:str]
    name: ENC[AES256_GCM,data:i9BScTLzOg==,iv:khiY8DSSlYhtjAamV1DDDtvvaJjL+LccX9bXexmFitE=,tag:1SDVupv4Ag3zCSk8PEgkNg==,type:str]
    namespace: ENC[AES256_GCM,data:Xb5TDOE=,iv:ODTB2jx2nhtLbV30SDdHcCXt2nB5VYAiwFpv852ot4g=,tag:aU4AM/vfKpBuzK+CENHRfg==,type:str]
spec:
    replicas: ENC[AES256_GCM,data:qQ==,iv:khAjHn7R0nlqDbCeq6qiTvTVy2HjLytWgmEog3ua9Ug=,tag:Shi7UtAUieQEHNnEUG4L3g==,type:int]
    selector:
        matchLabels:
            app: ENC[AES256_GCM,data:JZ99YSzoXQ==,iv:reI0w0a9TfLCCnZZ/2I9n5VAVDECg1sbO6hAlzYi77g=,tag:SSkrS8k/C4rLrIb5mXSAPQ==,type:str]
    template:
        metadata:
            labels:
                app: ENC[AES256_GCM,data:bhTb6O9nsw==,iv:iKFL01XaI7u9OLtPs63huzA0Im1VDI6r0DGry69Trxw=,tag:skaTKtNhsNc4LGRIdP6YDg==,type:str]
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: ENC[AES256_GCM,data:Lh/UAF4lnRNOarrm9gAJZpcwFa/HDg==,iv:5NoM5Z+j0Yg/NvyXkLJlXZt6fBowYS03vtepC87E5Tk=,tag:5CeuoXkIXGhSDGDR49+dKQ==,type:str]
                                  operator: ENC[AES256_GCM,data:tpfkOxY=,iv:ECJZJb46eGZLDvIOhgnBklbk+HEBNspTyDPgoc41AxA=,tag:JpT/09yB4JmA43BY3HuHdw==,type:str]
                                  values:
                                    - ENC[AES256_GCM,data:RtG/Hvf1IdS1TexF,iv:BpwYrQbyelrkXTvJUuatjPrv/CtF38erxauiA3TdukY=,tag:xn7/EMsRG6jW2EUZ80n2Bg==,type:str]
            containers:
                - env:
                    - name: ENC[AES256_GCM,data:sIwO+g==,iv:O8wZKcq+kSqCw6UV0aA7w8DW41NiqWkFM8qtEMznkBA=,tag:PivlbPoEDOxnHr79kT+EiA==,type:str]
                      value: ENC[AES256_GCM,data:FCoVtw==,iv:uLHnBTTn0w+JQDup9GG2Nhw6lb3Aq9ODtoFLUoZzn6I=,tag:qMDqKrqwYiNlI8xaU/nFmw==,type:str]
                    - name: ENC[AES256_GCM,data:nAjaUg==,iv:0d45iuZMN3ZXKZ0xN9xgPKbwg5Dt5n1g+umHnnFVbJY=,tag:BxHhCgj67AZXunJJ0RIIhg==,type:str]
                      value: ENC[AES256_GCM,data:jenn,iv:RbAf6ikKQ8rRt/AVQaBm/ZuRVbvb7qgtmLkNWJocJOU=,tag:dw7H4BiOYcsVscm3vBAK4w==,type:str]
                    - name: ENC[AES256_GCM,data:zWM=,iv:VgEI9BPLIAOb0Ci1VAOb1B3SOt+ySUSIcUKyY4d+h5E=,tag:kZA7XZ/m+SfW5LuS+DN+zw==,type:str]
                      value: ENC[AES256_GCM,data:CZSkxTXXLR0BOLL6SXrF+g==,iv:YmcmiSYSKhg3DEOMM6Hku/IhLDhj0ZopEbPUE0bUVjg=,tag:oM1rydXn7Li+b/W66E3gmA==,type:str]
                  image: ENC[AES256_GCM,data:7ZQ7/WCoIUp6XcLRBlz31OZYJl2DIBUucnRzCR3HU7CICEGXTJYrl0UaCZrurEcnNxTvza6mvw==,iv:tXJuTE/nok+MIqxhwPK304cinzFha71fja1AUfG0daQ=,tag:ngd9pWBr4ZaAeq9Ie8yr5g==,type:str]
                  livenessProbe:
                    failureThreshold: ENC[AES256_GCM,data:IQ==,iv:KEgL6I+RrEBikA9jvq31aDs27l7IJ3QKVodi/HWpywI=,tag:qZgbQsl+1FJSIWtn/iUZAA==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:4l2Zu/c=,iv:c3hrBvBU21ZWYmODu5x4wet2cpmnUreKCH9y1RxLJUQ=,tag:QKkRZ6VuOSjCzha5ZEGC5Q==,type:str]
                        port: ENC[AES256_GCM,data:kfMWJg==,iv:RWpkvAOXWkUOOhqdISw9EumjQjncZSz5YgSEg3PQD1o=,tag:Qvo/0Byem+cr6mriHeVR6Q==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:nqg=,iv:QutliPmqFE3m77cYy70rzkaBZq5o31ltXduv2EDEyO8=,tag:Ywv5iv2Cg2s9CK8Yw5niAw==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:5k8=,iv:VtkD+BHAXf1vCEa9ML1PwgjE5E8x1ouAP3jEv8cj8DQ=,tag:aDgvvqHSEnsGBntb70k4xQ==,type:int]
                  name: ENC[AES256_GCM,data:qXvlaHR5uA==,iv:lK3AqeRBFtWrwLX+XJp+paYMBhkEtPdTNnx1tCFA4S0=,tag:KQTW/VwWXvUM+Th0p4f6NA==,type:str]
                  ports:
                    - containerPort: ENC[AES256_GCM,data:FdJZPw==,iv:SbqbYu7eC1JsET83F56jqRA7qQM907R65rMrEm5rvsI=,tag:Ask8cgkBB2UsSIuC1zli+A==,type:int]
                  readinessProbe:
                    failureThreshold: ENC[AES256_GCM,data:qQ==,iv:dIR3k/j6G2l5e5ftylV1FXWo3FXQKoXVNWK2K7ygEcg=,tag:HWXD97yYi3cnxuAV1QgSWw==,type:int]
                    httpGet:
                        path: ENC[AES256_GCM,data:im0NUjo=,iv:aTFuiGAxYBx0ewBuOeybykyayQneDoO3e9bcwa5kYy8=,tag:Xn+0FjfAkM+cJM+Vcs7w9g==,type:str]
                        port: ENC[AES256_GCM,data:cm1hew==,iv:5WmAnbnNp3Fkn61n0jKdxhGx1m927C2RW50tv75X+Ec=,tag:Ej8oxaXDfcbXe6lnpIx+5g==,type:int]
                    initialDelaySeconds: ENC[AES256_GCM,data:q6A=,iv:iEKfal2ogSrAdy7xbKnUkVQqAeldGdsXybBQ5fN7NEE=,tag:8DNDpMyr/iQXT+Fh1kxf3A==,type:int]
                    periodSeconds: ENC[AES256_GCM,data:PEI=,iv:wvQj3mNI9IEQPS6C0ZpLX7cmwKvfU7GrhtdDw2UCURM=,tag:vMBDJUDHyhf5YbtpCT1xnw==,type:int]
                  resources:
                    limits:
                        cpu: ENC[AES256_GCM,data:CA==,iv:L7Siybsq6Hoirb07iJTFDPqM2iE6mkUEnH1RGj/JexQ=,tag:dxuYHhN2LMoUifJCoi/Viw==,type:str]
                        memory: ENC[AES256_GCM,data:aE88VQs=,iv:19Opt1bvbxHYJLPeqaEvO+8MEkrpu7X28F0dyMyFoK8=,tag:2FJAyCKhnRQO1toI8O+Hnw==,type:str]
                    requests:
                        cpu: ENC[AES256_GCM,data:24Mk,iv:FQLRCIFCthNsbf9YeAxYBVNen/lw5w94VsM5gUcaXw0=,tag:iD0A3H+in3iLGzpI0OCo2w==,type:str]
                        memory: ENC[AES256_GCM,data:BLc3c64=,iv:V3BGbjSTf9KKupLpbfZrjTCRCGV0InKyfwegu7kJ9Lw=,tag:FTy8kmxN+07EcXRnWn8xtA==,type:str]
                  volumeMounts:
                    - mountPath: ENC[AES256_GCM,data:tkbAII/9Kw==,iv:ptHE5tRoEYtTyrpCVX0LNfEEvJvkwWqgy4HMqhtFaqU=,tag:jUI25oH7mJ/dbvd1IETJUg==,type:str]
                      name: ENC[AES256_GCM,data:/to9DXnm,iv:j5baXWYPn/TeCszJ4zIpaXAsW+BkQOPAwWsC1ddrtOw=,tag:5LwM/b9ML019OxsM86/+2w==,type:str]
                    - mountPath: ENC[AES256_GCM,data:NO0gt4af,iv:UB/O+nM45cVpFgMtd+4H0puruj4cwEydIn00YaMw42w=,tag:LFaBxHiblPSTXvBZXtxpaQ==,type:str]
                      name: ENC[AES256_GCM,data:dYr0KgE=,iv:DL9sagsXxqMZUjUw7TzaB8XfAyid4ANfiyxi2FvY3HQ=,tag:bNL0H75ba7E1wZ7Kc8RyCg==,type:str]
                    - mountPath: ENC[AES256_GCM,data:lxYxQFw6riKUDA==,iv:Dd7x/V7UOkMvpsVPUs6Fp/yBDHouLUkW4DnDxAIWXdw=,tag:vSq9MMl3M502y2u6prNeoA==,type:str]
                      name: ENC[AES256_GCM,data:bymYKoZ2AJvz,iv:ohiYedLvDoQsS619V85ZvG8QMMddvjPHKrdfmVEPEVw=,tag:ttY+HkUvTSrDC9uFqJ1HTg==,type:str]
                      subPath: ENC[AES256_GCM,data:vWaSodOdvw==,iv:4KcqmzCMV2DeHnvqBFEzJsdGtXfPDhcQLQJjhVcJGCU=,tag:pJamBgAyTXLycb7OaBu2iw==,type:str]
                    - mountPath: ENC[AES256_GCM,data:MEUlsLYb2sx4,iv:Hy4u/+sCDfTauYMFErAmfFMizRmj+hs2bN5X8ssnkyg=,tag:L5YwDK4G9/wQCVWxtEOotA==,type:str]
                      name: ENC[AES256_GCM,data:WiHLAAi344ag,iv:FPWw2RL2VOjZO2jarQ/mL2n7TmBhFNxRaiDkLliq05A=,tag:4vfWEnV7Tw6NRcK0ubudbg==,type:str]
                      subPath: ENC[AES256_GCM,data:ainoGsBXel8=,iv:gdlUk2nh3tdWgIuGi7qR6e1qj71GwneekBp7ubY4CQU=,tag:VfwvRnvpxmLD/+3JNtR0ig==,type:str]
            nodeSelector:
                kubernetes.io/arch: ENC[AES256_GCM,data:hVzo9GU=,iv:uT4zYvITQC58ZtxzsIJFAxkoTcILevxhh03pXakYZzk=,tag:n5vHb+pFqVEV6g2xDtj1Vw==,type:str]
            volumes:
                - name: ENC[AES256_GCM,data:sNVV6MWr,iv:qUdXtFGErvCEoAoTqrAujHxsJSMsYQ8CeU4STyirdLw=,tag:qIXCU7tXDuzgqabD8bPMaw==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:Is3WB02bAzqWbCzysCM=,iv:bfKkFDyWcj7/7pE+ukLkUUKgYn6UPXhYRiO+OouB6uU=,tag:tbyO2Ur7RHyNBr1mgBr8uA==,type:str]
                - name: ENC[AES256_GCM,data:mPvFxXo=,iv:rFLqaraNlyoMHHBPQsFIln1LLCPaZAg/wI/m9LSgmnY=,tag:qE7UzOM+zQVTz6XWtS3GcA==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:fRQUBj9UKgJ47J+8LyjgVw==,iv:5lGid3PDVGM4q75uYvpcNyu9leXWJBoALYiPP7SeZWw=,tag:fZdpelwp8ZkzUcnGsR+JrQ==,type:str]
                - name: ENC[AES256_GCM,data:xIRANiRoYQ6a,iv:KtkWSlj0nEy8KwY6q2BHTFoa67/xe5/UOELpRJO1AuM=,tag:1kahB4Vu+grY0u+IYx9TJQ==,type:str]
                  persistentVolumeClaim:
                    claimName: ENC[AES256_GCM,data:OLSmLJEXFlz5by/q3L8OXcXHoz8=,iv:U2u5IL7R0JMb4Yz0y0BtQ1/28U2+jOns5IV4ki9jWMc=,tag:ot1nPbgaSbyrSlNG7gP3dg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ1ZIRm9xVFRGUHlxQ3o1
            WlNQeUQwUmU2dnNKR3pidXFBYm5pOXZNcDIwCkpHRzc2djJ0UmJnWWx4T29lMzIw
            NHo3aEhwajRrNDRncFRsVWNINlE4S1UKLS0tIDBiczZ5OC9hMmRzUlZ5MTJ5eUpl
            SmkvRHNETFBYdEhhckdVcWhtM0libTAK6plrlXVwLBA59JK6bb3Fxj1PvcWynk3c
            uSkGTYfov8wL5ht2ADkM95VcRBKTjTcVBRGcHanV1+JZRtmZEU3Tzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:7B1Q+vNF8le1LMdww6p9ksMiepCS1ysM6QmEHxCLI1yABcrUJJ/0VVNDpk2D+y7kXcvtFvaucBuhtN1Ye8OL38JKoDWtWwxDuR1kp363s6bh9pzT/+XCkOXnryK/bIIZqkjsNEhbyJTpjIPUmOxGjEggfNhIpXdDOkZFhc8P5kE=,iv:qRLVSxDptUEkKXg76NeIMmkpD2U/oleJ7HVPRx35aWM=,tag:M/2nnRzArV5NdFtOfvMpsw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:drw=,iv:9+yuDbmALylXw4JGHmrTt4DNCj0e+0yIgBoa5r10DHA=,tag:rD0r8aleBkmHT8iKzBSudA==,type:str]
kind: ENC[AES256_GCM,data:5unTgYuxjw==,iv:K1ckVTdYF/UVCdCX22WaeBKa3RHMWUF4AymyOGWLXFY=,tag:v8zfE+lQ6I3a2tMD/jhTCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZRixA0pwcg==,iv:9uXHZJDFueTJCSgaxBbM3Ir3c812okpkLpWY+2yA7CU=,tag:zd1a1iQYnF93mZNQ7YU5NQ==,type:str]
    namespace: ENC[AES256_GCM,data:5wggJtg=,iv:Kix13n/GZ/RTCRbrIzn5g7eemXcdXISdorGwm1Hk5rc=,tag:PFNWh/vAGuABl8KuqixmhA==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:32MHag==,iv:Dry7afYmoAVGHVC9MEbSn4/0+fznEQXARE0GzLB58/Y=,tag:Fpz7oQt8d7ucpfzznnUfFA==,type:str]
          port: ENC[AES256_GCM,data:awha/g==,iv:tpfULX8OxFUVIuh0abkM5kh+4KHYT7pUzFTntU/PnDg=,tag:uUmC3xPWXufqS86xkPplow==,type:int]
          targetPort: ENC[AES256_GCM,data:LQYG3A==,iv:x7KPiHwQBZBkHjjeKCD+dCFZtmujMvejvgTTItAsJgY=,tag:bhFovPL3zq/Uh+xuOtWmiw==,type:int]
    selector:
        app: ENC[AES256_GCM,data:S/mlZUniNg==,iv:/IpIP/eoKMK6PanO7QJZnkDCUyNwrdvSnWXkUMO9Z5M=,tag:wxqg6exOT6F71F7Auagg2g==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ1ZIRm9xVFRGUHlxQ3o1
            WlNQeUQwUmU2dnNKR3pidXFBYm5pOXZNcDIwCkpHRzc2djJ0UmJnWWx4T29lMzIw
            NHo3aEhwajRrNDRncFRsVWNINlE4S1UKLS0tIDBiczZ5OC9hMmRzUlZ5MTJ5eUpl
            SmkvRHNETFBYdEhhckdVcWhtM0libTAK6plrlXVwLBA59JK6bb3Fxj1PvcWynk3c
            uSkGTYfov8wL5ht2ADkM95VcRBKTjTcVBRGcHanV1+JZRtmZEU3Tzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T05:19:33Z"
    mac: ENC[AES256_GCM,data:7B1Q+vNF8le1LMdww6p9ksMiepCS1ysM6QmEHxCLI1yABcrUJJ/0VVNDpk2D+y7kXcvtFvaucBuhtN1Ye8OL38JKoDWtWwxDuR1kp363s6bh9pzT/+XCkOXnryK/bIIZqkjsNEhbyJTpjIPUmOxGjEggfNhIpXdDOkZFhc8P5kE=,iv:qRLVSxDptUEkKXg76NeIMmkpD2U/oleJ7HVPRx35aWM=,tag:M/2nnRzArV5NdFtOfvMpsw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
