apiVersion: ENC[AES256_GCM,data:Bm7+FZ+qko1eVJJnu3RJe4Z8wAtGlNWHvNBhJA==,iv:iNTKGCpox5wrOQyD+HpHODridm+wA4tCqw0bqJxZ6rg=,tag:FcJAGyiFDYYlb8MCdDqOrA==,type:str]
kind: ENC[AES256_GCM,data:GEvE6Sn5oNZU,iv:IYAqg3RZEgGQpyZn7elTwl76OGKdY3RPCAhlWlgBRBs=,tag:8+rC23vHwa4EJU9RUWAi6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Oli17X8Vht8+zP8Q5ZtK,iv:Nt1UTIBcuLMoHH5Sr3YkM/nISfuIlK08dEXaQ2L8YFg=,tag:Fib0s8WJBjzeqjNlFnfTGw==,type:str]
    namespace: ENC[AES256_GCM,data:wMINlNk=,iv:En5E9lDkSbmgKouBO7YOvqnu8VA0fdTmJZEYSXMQCNs=,tag:5CGiBm4S2yDd7OwLgdLJ/A==,type:str]
spec:
    hostnames:
        - ENC[AES256_GCM,data:3F/zKzrQLrH/YbuRx1OdNDX9LIbhw000,iv:p9Mz/gZ8U4S7OyF3m5sL1Fw+5CQK5xavDpUzUPj6RyM=,tag:raNzKGa53VAHZrSCMY5rPA==,type:str]
    parentRefs:
        - group: ENC[AES256_GCM,data:ZImT7TGWW7YrCYdWYFrrjkcA3P1xBuOOcg==,iv:bI1PX5KhEp8TSgpjwcWG/1r84O6SIz0Ephf1zMnppYc=,tag:qnb4DLE9ZHAZCZ6U0vP7oA==,type:str]
          kind: ENC[AES256_GCM,data:kezJE5xKtg==,iv:S8ss8DEYTpRRk6Zt5cqbRqaoikEC8MY8IcmsYmklfuo=,tag:QQmJsT663S+4DGOr+C23SA==,type:str]
          name: ENC[AES256_GCM,data:7qsE0g==,iv:Mmt82rvW7FBaDdWQlR1HsuoGVFtBBHK15Tl+O2RlHyc=,tag:foUJOlrgJ8AW5+2/ZWTilg==,type:str]
          namespace: ENC[AES256_GCM,data:qcVvCwvlx1594CpzrGs765alpsY=,iv:9YZr//v+kZM0BEbTh/8awOhPxejXjHD7LnaVdZ+MgVY=,tag:XrCQSE8MxpTa3YXOfkAQqA==,type:str]
          sectionName: ENC[AES256_GCM,data:28B+RMjo/Xb1HlWsgH1qJlFZY3MH8ao=,iv:yZbWc62gwDdKCse6RLSSnZBsQTvgxgx2D6GWifadpVk=,tag:xVEscbJ8EcAkkXgv5pow8Q==,type:str]
    rules:
        - backendRefs:
            - name: ENC[AES256_GCM,data:c4bcMasn,iv:sPJ6kisz6hIwLOjuTcJ8EiIzkLZ0sLf3rCqRH8Ppbq4=,tag:75lt9AqAIQoXz0QczoCPQg==,type:str]
              port: ENC[AES256_GCM,data:BdNJnw==,iv:gk66Wq8u+ElPZdoDC+S/mWH5O4L7UBc1NzTMfKKpEAs=,tag:RqoyoQUF1w5qgBdvEXFF1w==,type:int]
          matches:
            - path:
                type: ENC[AES256_GCM,data:CO9LWyUXqqO7cg==,iv:G5hLomEdwykvanZahdg/qzkmmGyL/KDJTIg6FFnTzoQ=,tag:bFTPoCnHdBSzeQl5cHLn0g==,type:str]
                value: ENC[AES256_GCM,data:9A==,iv:X7jWDVvwM3geerdMpUgiCPsQI9Jh+jNCvza4iyk9dbk=,tag:atPQoFtdN3JbVOn/hP+wYw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0hwWEVvd1IveGdIb2xG
            WkZ2YnFmRmE2aHcrb2RwM29VN0NxM1N4ckFNClpoczZvSXNzQVM3VVJSUnhKMVdQ
            SUFKTDJadTdLTDVMNUJzeTNhWWpPOUkKLS0tIEFJZ2kzOWI4MEtsczl5b3k5RWsv
            cmJEK3NiSEMrbHFpRVh1dlJXcVpRdnMKvSSIS3uaWKXdCE4jrPXq30OF6Pq2TZnr
            wsSJTHLPOmz40gOg6QUrujUznL0JQFp0PK+aFlDX2EshVVU+ebNL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:7E5aU95GJvJTPUAGIMLgNgi6drA+aU0qbmwLbOF46XXu0g+7qIacVU8mvijeEcuhxPdfJIz1dmCK/kXwUNDyalyanToDvemshL+3+a2ZFyp4q95lUD0Yte1Pd8XHCBuTCyjlUAB9Oc5I1ADkmSM2K5TVNuLzxSF+cbbLAbjwHIw=,iv:8851jbJ1yhwxRegnb+nrWlY3JwQYnO6YnUQD33R3wd8=,tag:HdMj3UOncf2qwpxtRWSKyQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:Bvn+ifgSYdJEy48Iu5BkbbNbyw4hFa/f47Vjlg==,iv:1rEZiwzz6VVfqiyqWBnwGSRuorSbR0LkIkUq0I8PIDw=,tag:US1GQequ4frxI1zaAffqXw==,type:str]
kind: ENC[AES256_GCM,data:USkgpDAEi/zR,iv:KF+AP7bth+R8yl6Ggdex+Q2G31MgMM3033xKhmw4lUs=,tag:3u/fjaukYTI3hUlOpOSbEw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DggZLZxDr43aYA4+DoV2,iv:AKjWztyZnpcAJ6WwiawhdfgKgrkQbIKmMlY5Ydq0qHQ=,tag:Qhecqoobe5rV7uJxp0oDdg==,type:str]
    namespace: ENC[AES256_GCM,data:CTn9xZg=,iv:nlCCLCY5XEDL9NQ39aZJmsJqKs5i2CZ75+G2m72AADI=,tag:v6V9a1ny7BKYYtq9Msjg/g==,type:str]
spec:
    hostnames:
        - ENC[AES256_GCM,data:2HfKsARUZ0QNKqD6itiTjTwM+OjEeA4q,iv:epc8gxBoGiwf2jbNlc50xh3PhgDrswj2KzVLuicwnbU=,tag:eb2FPUvrA1z2Kscsid+eDg==,type:str]
    parentRefs:
        - group: ENC[AES256_GCM,data:rX00oFU1LcajjI1xEN0j+qZWGYbJcw5+kg==,iv:sYsTKn5mQlOuuwvziqGzTAgmvMWS9VawAMAbeUXdDEI=,tag:PiHh+ebm7FFyuDTIH2XADw==,type:str]
          kind: ENC[AES256_GCM,data:S1pldJ99eA==,iv:0BNI/VOg3MV9LPOdsKVl8xeOTRicXSi9u2XSxBPi3HI=,tag:CkVL9HkHXusVn32YROcsKQ==,type:str]
          name: ENC[AES256_GCM,data:9Hw2Dw==,iv:p+dUBxM1vdG/BeTUxz6YtCzZlXABf7eQQ9449Lu8k20=,tag:eWzWDVxrOEcg99gsbhd/Rw==,type:str]
          namespace: ENC[AES256_GCM,data:/mBR5xw6Scs/ooCMDYF6q0IBO0Q=,iv:37dvu8G28l/DffQ5MrCIQ2igvtnTOSqRADz1dOCgyaY=,tag:8zSCJvZSYb6gsflxZWP6AA==,type:str]
          sectionName: ENC[AES256_GCM,data:vr+DqL1O+/1tz8DH2nvBspnfKF8Hsw8=,iv:lGA3B6pCTTxVXka7gZozdsNzTnjvyKHE62eKfqDMeyA=,tag:NCoPMJ/0xyvQNlC/OvXn6g==,type:str]
    rules:
        - backendRefs:
            - name: ENC[AES256_GCM,data:2GDpeJKX,iv:ZT6/4M6wOfo85vHiaDVX+ePMka+bRA3qBSzLv6GJ+jo=,tag:dm1SNF8AywasPOpgFwVmAw==,type:str]
              port: ENC[AES256_GCM,data:5JrO2Q==,iv:QxAFjqGdU8A3/xLnP9uMExUKY4rPzmJ+LeJMEmWfzak=,tag:yUaqz8ty+RyOjLIBN2Y2mA==,type:int]
          matches:
            - path:
                type: ENC[AES256_GCM,data:Ie1RcO48Pc7grQ==,iv:hy906jhzdUxQZ8MP/JAE9ZkKgdab/uOSttzm5eVkQhk=,tag:Q/FrCpLfBDjFwEy75Z18Cw==,type:str]
                value: ENC[AES256_GCM,data:3w==,iv:NgHm0kiljXg+7rOjYk1TEz/sFwOQQW5nDGK8HrLyTa4=,tag:UjMkXQ7I8mSGLJRRb+U6qA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0hwWEVvd1IveGdIb2xG
            WkZ2YnFmRmE2aHcrb2RwM29VN0NxM1N4ckFNClpoczZvSXNzQVM3VVJSUnhKMVdQ
            SUFKTDJadTdLTDVMNUJzeTNhWWpPOUkKLS0tIEFJZ2kzOWI4MEtsczl5b3k5RWsv
            cmJEK3NiSEMrbHFpRVh1dlJXcVpRdnMKvSSIS3uaWKXdCE4jrPXq30OF6Pq2TZnr
            wsSJTHLPOmz40gOg6QUrujUznL0JQFp0PK+aFlDX2EshVVU+ebNL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:7E5aU95GJvJTPUAGIMLgNgi6drA+aU0qbmwLbOF46XXu0g+7qIacVU8mvijeEcuhxPdfJIz1dmCK/kXwUNDyalyanToDvemshL+3+a2ZFyp4q95lUD0Yte1Pd8XHCBuTCyjlUAB9Oc5I1ADkmSM2K5TVNuLzxSF+cbbLAbjwHIw=,iv:8851jbJ1yhwxRegnb+nrWlY3JwQYnO6YnUQD33R3wd8=,tag:HdMj3UOncf2qwpxtRWSKyQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:G21HODjZYK9xX4NfhD0RhdJxQyi1pzrQewSAMg==,iv:BTtAkYC/LKo2oOEbdsZxHSkKvw3/TOY/BLiOl35xMY8=,tag:wU17V1csftATgXv/aLWC7w==,type:str]
kind: ENC[AES256_GCM,data:Q9qphjQJkI+x,iv:wurqWYUsgPgdifZEI+Ax88NIRnD1GaiCmm0tE4/EQR8=,tag:l4ne9tPjGFGSDp6aFNWyqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YWSJ/RWiHnZT+HFnzkBM,iv:5XdTOw6wd1qoN0tXHaDYUyuSmEQAPjD8TWSLHAkNSPc=,tag:POXmCyuQ73G9ghj5N1QMjg==,type:str]
    namespace: ENC[AES256_GCM,data:tCIJhCQ=,iv:kVzIJcH2CdxBwpxs+HrtxZ/NG2qYkuUXB8pbk0LXJ44=,tag:GPO3YSZhcTRRY4HdwZQ2ag==,type:str]
spec:
    hostnames:
        - ENC[AES256_GCM,data:zK4gz0e4NIzWGCRO9V07riG7nY5y76qh,iv:FEz9YvxB7AlGDZxubppzJZ6yg8+uVTQXaeZd07okFMk=,tag:g4BdeJo6ZSfXzOQujUHpHg==,type:str]
    parentRefs:
        - group: ENC[AES256_GCM,data:hpebUaB06197/r/2T4C/L8pnziNyWfivVg==,iv:6HC9o/cn+pwvwsIcipE3RN8TEKUzPo4rqqjgBzm/HRY=,tag:npuAhCKYwQi6i3GCfEuQAQ==,type:str]
          kind: ENC[AES256_GCM,data:H8h1BhLaag==,iv:VmKIKTEQabZUr9UXHB4R2RQ3x6s4BYP/uEQsCxm36AY=,tag:LzucYNxYNlAoaoEnSQZaIA==,type:str]
          name: ENC[AES256_GCM,data:9kgJuQ==,iv:BvxKN+vhkErcJNhywF9fhNMCsk72LtwtWPLcXOtb0F8=,tag:q3caVQpB3w4UA55mwGu4gg==,type:str]
          namespace: ENC[AES256_GCM,data:k5SUSh+NLGK61P0N7ehUY/6UbHQ=,iv:oFkNZRboRms7ALaIVN69QilGBvXpFYuSIOKiPLWNC3Q=,tag:Z/ysZncsTAMyT82dKrXsIA==,type:str]
          sectionName: ENC[AES256_GCM,data:a7OE9aTV1ABFVl6y5VZDjNkTHCZCDvE=,iv:urz+Mnl7ZGxxJXf+PQqGsq0Of4VGy7gsZqf8459nVKo=,tag:mto8hKoe6+W3664AQYWPbQ==,type:str]
    rules:
        - backendRefs:
            - name: ENC[AES256_GCM,data:l5moYxyt,iv:9Q5H/t/8bwEPjTubYzw9+0aLW4e2kbNI2bNfyavQRaw=,tag:Yp6qQzEAEkQDopYio4HILA==,type:str]
              port: ENC[AES256_GCM,data:GSXL5w==,iv:2/NLCaKvn0Qcu1PNSm8v0K/z9c5zuRyO79AKO0cFwZg=,tag:JSTAY2n1efN74KHmdZze4Q==,type:int]
          matches:
            - path:
                type: ENC[AES256_GCM,data:IHLpiSH5cpRDLw==,iv:dPH397ANfdq/uUGW7OslHGVuMox9uOOAb8LrE6Qu39I=,tag:+35a9ocqCa1gjEdDYo2y3g==,type:str]
                value: ENC[AES256_GCM,data:8Q==,iv:Wkw1BV+9e3TRANbaP35Us3NbWPib4e0PwXNYAQ7TFq4=,tag:1LUr29fy/RyTd89iLLSP0w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0hwWEVvd1IveGdIb2xG
            WkZ2YnFmRmE2aHcrb2RwM29VN0NxM1N4ckFNClpoczZvSXNzQVM3VVJSUnhKMVdQ
            SUFKTDJadTdLTDVMNUJzeTNhWWpPOUkKLS0tIEFJZ2kzOWI4MEtsczl5b3k5RWsv
            cmJEK3NiSEMrbHFpRVh1dlJXcVpRdnMKvSSIS3uaWKXdCE4jrPXq30OF6Pq2TZnr
            wsSJTHLPOmz40gOg6QUrujUznL0JQFp0PK+aFlDX2EshVVU+ebNL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:7E5aU95GJvJTPUAGIMLgNgi6drA+aU0qbmwLbOF46XXu0g+7qIacVU8mvijeEcuhxPdfJIz1dmCK/kXwUNDyalyanToDvemshL+3+a2ZFyp4q95lUD0Yte1Pd8XHCBuTCyjlUAB9Oc5I1ADkmSM2K5TVNuLzxSF+cbbLAbjwHIw=,iv:8851jbJ1yhwxRegnb+nrWlY3JwQYnO6YnUQD33R3wd8=,tag:HdMj3UOncf2qwpxtRWSKyQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:OHutINyly7IzhXJoQeI+I2PvEZPyAlZW2PHKhw==,iv:O6X+ePuZSn3veS3CfRki6gRC/4poWWpm7+5AjdI5/ao=,tag:hxGpslgEdgijwf2XwuFB4g==,type:str]
kind: ENC[AES256_GCM,data:8xU5j6rbZzAM,iv:xP4ZudF3Vr8HC/5kizAg6F6kO82V5Da7tlbGRNUbJVA=,tag:6tddFf0uvPMO2e6Z2DiR1A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ONwcQH1Nv8nDL584MeCVwGQ=,iv:AjQHjGF8foy2NCMUvwki3xV0mXJMMdgh3lWhnh1jdH8=,tag:NghVPRcRGZcQTdSL+AfoqA==,type:str]
    namespace: ENC[AES256_GCM,data:cil1IVI=,iv:7IHdKfegjGFsdp//4baprA7Wqr1bXZioRljR84YwMdc=,tag:J0bazjltn/LYZCEzO7CRYg==,type:str]
spec:
    hostnames:
        - ENC[AES256_GCM,data:xMJ5QRQ0sxnTl1jmgHEkkWXnBVhRhTNyix0=,iv:tteQCGveoSBhc6aD97HaRS7xIgDrb+j5DCcvKbsgnSU=,tag:6yIQu1oBupVlPUFfujKtkQ==,type:str]
    parentRefs:
        - group: ENC[AES256_GCM,data:yAtamZRy+S3nY+Zey2Zirsb3jkMbwx3ulA==,iv:5GXfLUA6nDVP5XmEAFB/aE/qDHZPaCzihVpTf0NlW5c=,tag:8vp++5cgoiCxEzsTHeNP7Q==,type:str]
          kind: ENC[AES256_GCM,data:M0kzs66N7Q==,iv:MQCS9CsIHtdmqZoU/SzwHbPYvqiXmjh/upUvl+SW6pY=,tag:f420rFN/WaaF2EDJqWmEjQ==,type:str]
          name: ENC[AES256_GCM,data:6W9b6Q==,iv:7ZqDOBpMnGyTfUxT7haIANT0YxfegVBONMjBNb+Yfwg=,tag:6QkTqXyuXYacOYlcim82Tg==,type:str]
          namespace: ENC[AES256_GCM,data:FkFko+PSEmk6eNSN9E3T1R/qBjo=,iv:FUx8WO6WL1sQMjNCIqoX3RxFqth/yEO3XYguMhWPVpA=,tag:zIQMBFyQUNmkVtT9K5KZtg==,type:str]
          sectionName: ENC[AES256_GCM,data:2CkPuax8Jh5UpQjXvn0W4T3ZT8GVsgI=,iv:ETYJCW3uuWCKcd1ohsS3UFlSPUnrOkY5dRP80GHWZkk=,tag:Fqh+LxEc0WU0nqgPdWVb5w==,type:str]
    rules:
        - backendRefs:
            - name: ENC[AES256_GCM,data:Lgvfbbd53tM=,iv:G3fjLfnpeHgmGYOJaKa5woHjGBhW9YRpCw33f98JI7Q=,tag:EANy/4OhFTl1lvAG00Ii2A==,type:str]
              port: ENC[AES256_GCM,data:NkU+qw==,iv:FDlsDMwZQjz+fYFEXfedlwN3o4XiEwgtpDE2rZFydTM=,tag:2G0ZHbJT4DhpTn7dmi3LZg==,type:int]
          matches:
            - path:
                type: ENC[AES256_GCM,data:to+ni7iIjhQpyg==,iv:4TM+TQ4DiIEEtkohJhIWju7kfOS56Nq/IM9Q/rIeGw8=,tag:/QEhsPRR6r8QflahT6El2Q==,type:str]
                value: ENC[AES256_GCM,data:Ow==,iv:et2KGx+VGomxzoQRXlJy7i9bY3ofaNAMMA/AkocblmA=,tag:GUtPpAkARtCWVAU42m7JOw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0hwWEVvd1IveGdIb2xG
            WkZ2YnFmRmE2aHcrb2RwM29VN0NxM1N4ckFNClpoczZvSXNzQVM3VVJSUnhKMVdQ
            SUFKTDJadTdLTDVMNUJzeTNhWWpPOUkKLS0tIEFJZ2kzOWI4MEtsczl5b3k5RWsv
            cmJEK3NiSEMrbHFpRVh1dlJXcVpRdnMKvSSIS3uaWKXdCE4jrPXq30OF6Pq2TZnr
            wsSJTHLPOmz40gOg6QUrujUznL0JQFp0PK+aFlDX2EshVVU+ebNL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:7E5aU95GJvJTPUAGIMLgNgi6drA+aU0qbmwLbOF46XXu0g+7qIacVU8mvijeEcuhxPdfJIz1dmCK/kXwUNDyalyanToDvemshL+3+a2ZFyp4q95lUD0Yte1Pd8XHCBuTCyjlUAB9Oc5I1ADkmSM2K5TVNuLzxSF+cbbLAbjwHIw=,iv:8851jbJ1yhwxRegnb+nrWlY3JwQYnO6YnUQD33R3wd8=,tag:HdMj3UOncf2qwpxtRWSKyQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:lay7kUGUBxjOWF3AB/3cjFNer0Y1/hj1Bx2dTw==,iv:vXbXo3gwxLkKZy6rog2KS7MTqbvfe2vJCzr2PARZ69w=,tag:/+Be5eltXwYdhiMi+b628Q==,type:str]
kind: ENC[AES256_GCM,data:Ll7tj52hvmIh,iv:9L22d4KP9W13Agym5wLQ3HSTEbMDhhKSfKdPSWQOfHc=,tag:Gs0ZEmjQy/YuKz0MQ2sR0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sz3n7c8oXQwe+sXarfbM9g==,iv:CzE7eee3cNs9dwn7q8hYmZdYUzWb7/8mzIos4NF0lNo=,tag:XWA6sJyYXyskOFz/rMUwIw==,type:str]
    namespace: ENC[AES256_GCM,data:pH6padI=,iv:srrE/97XOAMDDnTQdSucF+dFsZJlHe5o5MdM4iI8S+k=,tag:0LVYpujVakKACRNE48JNbw==,type:str]
spec:
    hostnames:
        - ENC[AES256_GCM,data:b3OQP0HqB0HOqwNKDXboaGPn90c3r/EIkg==,iv:6u1VJQkIhX18jnKHiaLq0eAtaqC/bOKdSviyxgLJ9+k=,tag:1ukPvkLKb1XkLDjFd0WvNQ==,type:str]
    parentRefs:
        - group: ENC[AES256_GCM,data:mJOJ8ZVDWh6kvCI99OFKaCRZMkYsL6Rv4g==,iv:oyf6lvlSUyPgp/9Uk6MnbVeHaFJUgdbeMF06y9Qwrbg=,tag:2NysHNoyKkOMwiECGUMYhg==,type:str]
          kind: ENC[AES256_GCM,data:yAgBStd87g==,iv:MZxsX/BbkC1QA9kTSqBhy0wWdwxpuopVdl8dQy3j8ZE=,tag:2N/bl194g3DWWNPrVzrttQ==,type:str]
          name: ENC[AES256_GCM,data:mZTQzw==,iv:a4iGQu32m1d1hNW4B84vKewE8jpk2MnWsZmsFRtXUPU=,tag:fXfaELCCJJ4KJCESoDwdKw==,type:str]
          namespace: ENC[AES256_GCM,data:tMQSoFI5bCzM0kQ+hMgj6qJ8efg=,iv:uuxNoCkwYckdBKJrmjmSS+oK4jtewaADAk9setF61GU=,tag:8jtwU12XKHELdUmwHQdpcA==,type:str]
          sectionName: ENC[AES256_GCM,data:pTsDWoNigysSdRZwV61tQvC+ztb9biM=,iv:81f/sjDJko1JyMmMBGBVTxGGk5ExJqKGNZE/jZR4ao8=,tag:t3tu+KLwZKn+oNPlmSYB5w==,type:str]
    rules:
        - backendRefs:
            - name: ENC[AES256_GCM,data:MUjNtZWFBg==,iv:9vnLYgwyXCL9vV7Mhdv673rNJjIBOpUxxLsCiKZAeug=,tag:RxqwVVnL9YFXLna8E9hpkw==,type:str]
              port: ENC[AES256_GCM,data:O5yJDA==,iv:tbq18vcUE6pQoXrVc/wsU5MPRmbuUBvGsokAzDKVzlE=,tag:DK5cGIbCFs01u6ZIuELo+A==,type:int]
          matches:
            - path:
                type: ENC[AES256_GCM,data:EUkU7s2qfAyWRQ==,iv:5amxVhgYfKnpO15NimeWc/kQT96DoMnars0lTVS1tpM=,tag:njPHh1KaqeNnG+EYqadc6g==,type:str]
                value: ENC[AES256_GCM,data:eg==,iv:cDOlVf3HU4P7azoZwoK5BeUSiGGkYJqPW70N3B9uFVw=,tag:5AZVt5y5oW8n+rxTLtVMEg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS0hwWEVvd1IveGdIb2xG
            WkZ2YnFmRmE2aHcrb2RwM29VN0NxM1N4ckFNClpoczZvSXNzQVM3VVJSUnhKMVdQ
            SUFKTDJadTdLTDVMNUJzeTNhWWpPOUkKLS0tIEFJZ2kzOWI4MEtsczl5b3k5RWsv
            cmJEK3NiSEMrbHFpRVh1dlJXcVpRdnMKvSSIS3uaWKXdCE4jrPXq30OF6Pq2TZnr
            wsSJTHLPOmz40gOg6QUrujUznL0JQFp0PK+aFlDX2EshVVU+ebNL7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T16:11:44Z"
    mac: ENC[AES256_GCM,data:7E5aU95GJvJTPUAGIMLgNgi6drA+aU0qbmwLbOF46XXu0g+7qIacVU8mvijeEcuhxPdfJIz1dmCK/kXwUNDyalyanToDvemshL+3+a2ZFyp4q95lUD0Yte1Pd8XHCBuTCyjlUAB9Oc5I1ADkmSM2K5TVNuLzxSF+cbbLAbjwHIw=,iv:8851jbJ1yhwxRegnb+nrWlY3JwQYnO6YnUQD33R3wd8=,tag:HdMj3UOncf2qwpxtRWSKyQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
