apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misp-files
  namespace: misp
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
