apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: all
      group_by: [alertname, namespace]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - receiver: all
          matchers:
            - severity=~"critical|warning"

    receivers:
      - name: all
        webhook_configs:
          - url: "https://webhooks.white.fm/webhook/e8afc74e-26e5-4679-ab56-103d86aa6b6f"
            send_resolved: true
            http_config:
              tls_config:
                insecure_skip_verify: false
          - url: "http://ntfy.ntfy.svc.cluster.local:8080/cluster-alerts"
            send_resolved: true

    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity="warning"
        equal: [alertname, namespace]

    templates: []
