apiVersion: v1
kind: Secret
metadata:
    name: listmonk-secrets
    namespace: listmonk
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:tC3Nyoi4opnxSvufej2BzJ8pgOFT1yYYFAfw9yFEntAKSr/wYq1wj11uHRFdxE35,iv:BinRZgM0WbS5w8UNgp+BLtbPZII8Mve7/Ktheyx7vMU=,tag:YUAOxNKk1h+Lj+BoFGF2hw==,type:str]
    admin-user: ENC[AES256_GCM,data:7/9xOMI=,iv:SEF7wffgJ4DhN4pFiaWcJoDVMVv9bJpQ8U9cv+EqxPs=,tag:FuXlPFBIL2hv3CdnEFgRbA==,type:str]
    admin-password: ENC[AES256_GCM,data:voEhmdenrHurv9c92uoK7y1EMJF3ZDd9dk3LBs9IHXQWpRF+ecHjItMQUMpdRKXY,iv:73Ly0ddSH2YEQox/O4sQEEwR7GQhNRV/Wp/kwmidtAY=,tag:1wRt3UcoIUw5qVd5DXzapw==,type:str]
    smtp-host: ENC[AES256_GCM,data:k9JdiQVRbFRGwyrs7B6AR01u,iv:41RJcgw8R5wUsdSbSs9zx3VIoPa8mD6omcFNEi1zCxs=,tag:7rc+pGvxlnj1s98Ac5JpQw==,type:str]
    smtp-port: ENC[AES256_GCM,data:84fz,iv:UrHedqRbEpzRQ+DuJp5V8bJ/4kfGcLW8TqfiWu8T7nU=,tag:oKNew6WGFPl9dvpdt+7fGw==,type:str]
    smtp-username: ENC[AES256_GCM,data:5xHi5T2iAbTe/HX/lvY0KD1dMb4x,iv:qKaO1LfrNuCSjFfrnqeqRln39Mjxxwh4vMPIE02QaD0=,tag:UJRnZCyUNOUANgFeb8on8A==,type:str]
    #ENC[AES256_GCM,data:HvAUL9/afe5XwqIm1EkNyxwlTR0ceyCv8DkVhObH+5GJNCk2nEoDrxtbNnK2/VNThGZbkQTHgdQUGxorqVKjut6NwTdsZPcPxk0th5sQadObCKxubYSd2A==,iv:q/dC0qNrrlEBIvmLQZpQnwRsXacEp2WEQKzqqK06DM8=,tag:/rH2yNfBbIB5nSonNfwa9Q==,type:comment]
    #ENC[AES256_GCM,data:hnpPjPES3+IArM2OzLSBpKRT4sBDSlByWZon8q1H2rSbeBNFZSPv37q+SmxeRlJmuaNnqNPMVI3DitNsyjg=,iv:XYeVQjVfYbnys4Fw9qnhkfj6PN9Hp7EKh9MoBwNRLIE=,tag:EgD0hSsHb92GaVzvlzMd9A==,type:comment]
    #ENC[AES256_GCM,data:O5VNppPn2EXHXLGAa3mLhhOy80i5hitIDXfsrrKSI7IB8GPaVXyeLNKTJogCwdojlQZle4khCrE2MGslhFTsZ+kt4GZCsdkdr+vYFwVbkOFaMV0VQrCYv4Brk57ALfTqhoxTR+Ys7X8=,iv:x7dQlAds5Go8sn8uBJxuY6Sxcu8h4z0gb/L+t8hQs0c=,tag:9gQORneELslL59VSm/QDLA==,type:comment]
    #ENC[AES256_GCM,data:RK0JumUcree4xzUSgUaEv0zfiIbKpSm48nDRIftcMpd68ouEI/sO5J91a6wWg6HDSawJWqSSn3Uv2r9K+1VGhC3Z8Ges7A2m0yZgdzlfFC+Ep2k3UVOGnxQ=,iv:ZrUsV84p1DfzhiiNCf6sDVKBZ3wKysGi+AzNSxZsi3s=,tag:yTrGk63TGOVreg9ibl4drQ==,type:comment]
    smtp-password: ENC[AES256_GCM,data:9BtaELcsXEQcr0mVqx3jlw==,iv:K0xyCyaj1lA5YAKNSRc4l8xaajtoGW0/CuwhIot7LQA=,tag:BUa7C9yKvprbOzTRcS90BA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGa3Q4ZWp0alBIaHpJRVdw
            cFkvVVpLYWtxKytBRU83MVNFZXI3YjJaR1JBCm5JNUpTUXlwSHZLYVZlNlN2Q2o0
            VXdHV2JzZURGaFUwMEJ0dEFyRlF6a1UKLS0tIEFFMWd1MTRyU1ZMdUZUQnJTYm5F
            U2JzbDVYWUhDcmFoM29MZFRjS3JNeU0KFVToDUD0AiA02QB5Df52akidayGO4jte
            IUsacAS6ifyNjfeij7LpSCyvITf9T2UJF5ZuITNbwT8YHjxik6oOeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-14T02:53:25Z"
    mac: ENC[AES256_GCM,data:X7By5WU0z6UYpZomU07mfP2f0qm1mH1QI8XC806Kabghzy4lU+kDxUNWOt0zXI9Aw18jh877zh+cDGFG4C5vacoG9F0d0jR5AYmhsu3rVWKSQszCI0XwbPqA/ZfBi9jERdnxfkZeHZzl9nXnNKOErx2YyB1SaSS3bjoP4gWzZZc=,iv:PE+cVEE0wvvhCPlIj67mtgTwIKhxSgIAxcPLcARkMvA=,tag:8tOTVsC6kDqpxgA4/cvY6w==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
