apiVersion: v1
kind: Secret
metadata:
    name: smp-server
    namespace: tor
type: Opaque
stringData:
    #ENC[AES256_GCM,data:fRbE+BwHoHnFxDDdmpvDq1mDVbkGk/PY1MGAdNRD9MUk1l/paMdJMd4A1ICn4j7BYbaGDwRrrCxKqWIp4xl4kqcdq24=,iv:v7FOx86D1cOtIYq+9cfd1GZC+IJ+ob276+UYFiigLXk=,tag:FJooU503N8MmF/W1N8yf4A==,type:comment]
    #ENC[AES256_GCM,data:eLqzHi1BOCUZlIFzPwEbvw2wBgeEyUgW2lG9DD75mUcCiGj5PAaaY6L4pkwe8/+qorIVU8fBcCrpyyy2L50LGg==,iv:vMRB1Hp0Xz2AdiRc5V1aSQXsU/zsh/J+iBjgu1GS2mk=,tag:beYJBe7G3wPTkpvTY21WgQ==,type:comment]
    #ENC[AES256_GCM,data:mLuKyW/QH36GrP9O+cqF50sph/I1i+0EW4E4NAuULfmsAD56TQcfLXwEprracEkRGSHxOdyRWAcX8GxeqFDpNAkM/iTq,iv:wacuCUD+axvzxCkSLrnFqR1V9ocWgkT6pk7JVtmRhCo=,tag:fiBLwuPB0+UArUlYMHjXOw==,type:comment]
    #ENC[AES256_GCM,data:p4Hbb1hwvfO/Di60v2F7vmYRpHhEojV71T03MlI731O27JUJr3mT+N/qbcfmS31pquLQWiylUSHc4S4fPuO+Cbo=,iv:9pD3bT8JF3SPxjma/F473qN/Xlm8R6KVh9igXZ2Bqx8=,tag:CjM7JCFPR0FEr/Ij0iHSHQ==,type:comment]
    addr: ENC[AES256_GCM,data:SP/UB0ZwsVkh0KIq,iv:mEwjptBsQC5BZt4el7fDwq9BCj6go9tZ0hqeum37wek=,tag:w4bDhfU0b69IYfAHGsXf8g==,type:str]
    #ENC[AES256_GCM,data:3Sj8YuVkdf+JYmltTCCyHnFwoVgWDR6uJg1L5XeXoK92HtMmxZa6sFFWtpXB0OFSY0/LDe3DRTUk+EXFh5pbjJDNaw==,iv:ZFP+qTkmPjRaEBUTzudSF2l3zjZPrG5eszpausttyzo=,tag:gmR9AgdGeNKCL7QgjzjL5w==,type:comment]
    #ENC[AES256_GCM,data:HlYAKpMqpNmIfuSwkurcCXtntzLN15Xtz/CaoQUlKydKZCYg5yTREPXdgWErHpZb8DiyqyhyHUGMlIwM+Yyhv4wY8RtN,iv:4OFs05F8FnnnGxTrCfqTLF6q9dc5wug1pXaijN/Po+o=,tag:sGnhF8cHwSC1TAWecA9ANQ==,type:comment]
    #ENC[AES256_GCM,data:NK1sdrl1jQUsu7b0oSNXlxqFhQN0HVqhW2/T7c+37KM6s3xpkPuFdHxOWLUvg8clSKb9GPoyOFM1EsW0XK6BIw==,iv:munsr1mTbi/whMFXjuUk14qYQEwf+DiyeIlCMJ/BVBo=,tag:hCEoz3DjW5vnsbPgc1Na6Q==,type:comment]
    pass: ""
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NmhtSUFVNCtQYjVzVzds
            ZkdYS3JsdnFXWEh2dGNxZFVmeVMvWjBLWm40ClBGb3JiU0JHV0QyVnEzQ1kxWGhl
            bzBQM1JHRkphaHVaY2Nia0x1OERycVkKLS0tIFVLOVorTnZ2Kzc5cjhRelpLUklp
            L2dtNjRwem5jUEx3K2JuU1I5VFd5alEKARRzN/5lMJjz6FaKh0bZsqHKUVwYC/Cz
            CkseX+Gkg8/i8+DMpHGE1Kq+bSYquZN/Dz2MillgPyzGp6Nnb1OgOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T05:03:12Z"
    mac: ENC[AES256_GCM,data:IpWKkUPKPem3v3HJY6MvobosaWMAq6Le0dDl77vMIvNcNjqgNP4+DJ/kN8n+Az0WaXslCpvsJt4Cx1oZXeghxOtifzzuJC2Idbd6aFH+zIbkNKZxRlv+qn4sV2Yv8HEPpifGZe04IUW9amcKItWggQvuXvK/UbB9ZYwXcpenHvo=,iv:pNyLm2k8rQx4Wo3tFbe4iTZKnTR9b7/HrRgmd55rnag=,tag:+mOuxrz0jNa9+Rhy2X/5pg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
