apiVersion: viaduct.ai/v1
kind: Ksops
metadata:
  name: tor-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - 30-secret-bridge-contact.sops.yaml
  - 45-secret-smp.sops.yaml
