apiVersion: v1
kind: Secret
metadata:
    name: gsc-mcp-env
    namespace: gsc-mcp
type: Opaque
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:CC8FCMFCVUN7ghPoT+1VkwmB40NyLXt8kxS/fHpXiJ0puu+ck/+g6U3NZ4nZP0UVOsY2cVUhcLdeqmWR1MQedw==,iv:zwCi0JvcTFyhNTpdBsaOWiOSVTTfVXgPJse2uFSgKl8=,tag:69OPO+sRBs2NqUtfoGzXlA==,type:str]
    GSC_SA_JSON: ""
    INDEXNOW_KEY: ENC[AES256_GCM,data:xkLt3i0yjMA0UrHGSeoiKMuVDq4aqvXz/2PsZeKhsFg=,iv:PiARLgoSomgIn+CnoQO9mOwuauPxH7T8DE1YJWeD3cc=,tag:IbwnnueNWBWDAdwFqIO4rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQXBmcy8rV3FHVkk5M0xu
            M3ZmVXZGekpWaU96L3dBb3E1cHE4WlNreEE4CnUwTEZCZzNFQW1ZZWlyYjBsZld2
            UFZTb0pmSENEZ1duMXF0Tmh2K0JjSTQKLS0tIFVZL3p1YSt2Zm1meDJSUW0vQmlv
            U25kUzVHMnhhT0pzcjBIVVQ0cHMvbFEKva7DHP02emt0T0zT7GG2EqtE0JtshdZO
            H4h4Iy/T8rIFxMlhXoTln1/m3+Ebqat3oR/wBGWiU7Nbc5yjotrRwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    encrypted_regex: ^(data|stringData|parameters)$
    lastmodified: "2026-07-26T20:35:56Z"
    mac: ENC[AES256_GCM,data:3sLJIXUxrFzyo7vv3jaKOzoBzD9E/xNhA1BY56ueMV260OEgY8LRqnGgcUtg25utZWd+6xZ1QpA1jl5/ZByAyo/W210M17Zpi6LVF+rVRcBT5tUud1xqQ2vTO77ClZqnX37PqNQnRLvzwZ/EKNzh9YyDcyAOVtkOOl8aq18TsGY=,iv:jYfiTXxMh2zGm44ail2BZ1XY94JA7UY8QRcEEFbWJz8=,tag:KSOoB689gIkaVY4vq5tpDA==,type:str]
    version: 3.13.1
