apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: gsc-mcp
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:VM6SyP3NsIDakwJvMwhV8s9bKjDPdIv5N6gZRtthCE88bgAo+tXBIQ23UXyv3F3fdOG/IzMYii/veDLQAQpzUz5/RjgAyDe7y/Ub9GIgRv6T4Q1yT/83YASisvGKh1Ho3H7dnzoxa6/bKdujww0XX49S6Y9YpGtjAw2n7+MnjbVnC2EUPP8WFMVF3WdBR2iE9Jhg5nCAxb1d73YateHi6XY7OSgkV1iiSmXQyXKXzaQERMrmmWhFxjNNVmLoGigK,iv:dWuVIwTaVKeytfWypJWeX7LNf/X+5t+RrTejTEPLQiQ=,tag:2Jh6dbRPPdAo9FpJa9Su3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QlhzMURhbDJHeHJXWFd0
            NE9nQkRINWpNcWI4ejFsRjlWTDk1NE1vY1N3ClBsNmpBZUQvQ0JadTZUcXdhUFJP
            SWhWa3lCZEFWbjN6eXM1emFZaTRpalkKLS0tIHUvREhISkhyalorV1dTb1lLNkZ2
            RzdPU3pHNUt6RWJ5VXJJdjcwYjcvYmcKGyaGBtGIjMPG/Dqoh57GJNCg+sIQDI2n
            UG1SBbXZn5X3Q4jnR1Mr7FqwlzcSzM0OXG2EtKKMpW0CGX/tghEhwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    encrypted_regex: ^(data|stringData|parameters)$
    lastmodified: "2026-07-26T20:35:56Z"
    mac: ENC[AES256_GCM,data:QxIGisGtNsopoKEtLowReL+OG6Z/PT2bjKGpcK9N1RLeIVv2nUUa/PCI7CprdXU8/MwtNQ4fsyOOihkDvROttU40HNb5xB0Z1BfXnFcdBfpbED0BMyx12gzUY2XoRTOkLUJ9TKkJwX59C2iRaS9mgDs0YtwyJKvPLx4wgGJA61M=,iv:5LF1DUeGqdfeArHs6DzQ+d+vxbtZLbs217yLLNRVDDE=,tag:OdYpTceUksGnD0MidmV4Eg==,type:str]
    version: 3.13.1
