apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calibre-web-automated
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:RobertDWhite/whitehouse-rke2.git
    targetRevision: main
    path: apps/media/calibre-web-automated
  destination:
    server: https://kubernetes.default.svc
    namespace: calibre
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
