apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nitter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:RobertDWhite/whitehouse-rke2.git
    targetRevision: main
    path: nitter
  destination:
    server: https://kubernetes.default.svc
    namespace: nitter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
