apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odysseus
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:RobertDWhite/whitehouse-rke2.git
    targetRevision: main
    path: apps/ai/odysseus
  destination:
    server: https://kubernetes.default.svc
    namespace: odysseus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
