apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallabag
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: git@github.com:RobertDWhite/whitehouse-rke2.git
    targetRevision: main
    path: apps/misc/wallabag
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: wallabag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
