apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: homeschool
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:c+nDnzjz8LiUGV0scUOzZoS1HXR2+IBMSL35cKJyLVRdYYS9KUgKOJKvrMKwyjYAvwnax1nUfdahNarF+A1m5w==,iv:Cc2QA4dfseAH3M85G96QUO1AMTpFRB9y2tvuY0hRSgs=,tag:oOm6Cdk797ctMNSbn2P6JQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpS1I0R0xJL3N1K0VVMFFm
            bVVJUHJFYzhkaHNwYzVmOEVJSE5icUg2c25RCjQrTUZ6NDVVeXdGQWFGODg3d2o4
            WU1HZ2s0WFQ1TUltR2ppcE90ZmQrcEkKLS0tIENNSnpKam9wM1VwOGE3TmppVjZx
            WFlHcU9scEpHZ0VIRGdxclVPdCtxd0UKKVRheO18yxu1qefUCFkV2i/QdfyekjUV
            u1qQid3qyRMfiA7zqW89r4S6NFxgSdWodWpvXuXwTGag29cUj1sysQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T04:17:15Z"
    mac: ENC[AES256_GCM,data:T6qfLI36KfUp9INapXQQsJRfVORLKVLbJSVoVKQCbnaxdY9zZxkyl8mRUYcTJUVYUMNCUvF6pocHHnhKaQA9hk5Calj7wahBw9Mcuv+/60shYQK3zCQ1dJwqFm2f6mpOyG1Nx1w3Ay/DppVXCJ5JpIuGeL7bUzX+GmiMhqQTTrI=,iv:hoS/x3gGsFzQUFUjtWJtwD84QgKtriSr2K+B2HUA5BU=,tag:dU2/Piful9p30suKWRSMNw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
