apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invokeai-models
  namespace: invokeai
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: longhorn-single
