apiVersion: v1
kind: Service
metadata:
  name: invokeai-exporter
  namespace: invokeai
spec:
  selector:
    app: invokeai-exporter
  ports:
    - port: 9403
      targetPort: 9403
      name: metrics
