apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nut

resources:
  - 00-namespace.yaml
  - daemonset.yaml

generators:
  - ksops.yaml

configMapGenerator:
  - name: nut-config
    files:
      - files/reconcile.sh
      - files/server-nut.conf
      - files/server-ups.conf
      - files/server-upsd.conf
      - files/server-upsd.users
      - files/server-upsmon.conf
      - files/server-upssched.conf
      - files/server-upssched-cmd
      - files/client-nut.conf
      - files/client-upsmon.conf
