apiVersion: v1
kind: Secret
metadata:
    name: nut-secrets
    namespace: nut
type: Opaque
stringData:
    ADMIN_PW: ENC[AES256_GCM,data:cZv34PLY2rCcXBIsKHBVLbY16c8hqDPc,iv:g0oQO+aaHCM63vvEhYJCGaBEArYHi1mFoQdiK1rIzAI=,tag:9s0XXs7aDlFN+/lKT6wYHQ==,type:str]
    UPSMON_REMOTE_PW: ENC[AES256_GCM,data:veD/QrQlIDtE41zqjw5W6Eq2T3US6JxN,iv:OHNIAowOc/q4uRyvupqjk22m+zKYepUq8YknVYA7j7A=,tag:v3yVBU02alPAyqwq9d1szw==,type:str]
    MONUSER_PW: ENC[AES256_GCM,data:wq6EgPaB,iv:SRW0yJaJDo6Ayy5K+5habFFfokKhtB1o0JXxAE5hjkM=,tag:pKUw7BM0Ppi4OEJuFIL8rQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvelNIbUVFaHlDNmlqYlh6
            WXVrdUhkQ0hZeEtjQmk1TTB5SmZOd1krWEVFCk9QbUxyR0RjLzlIQ1N4ZkxLdFNy
            NlRkbG94dnNVVHlZd2FldEwwbE81YWcKLS0tIFJWU1AvNW90ZHV0NkR6TjRpYnBN
            c2FzbGZEL3Z6WUdRbTJRT1QvU09HOEkK1a0DoqLKfl678edaDxU6jHb5Hncq9qau
            fbVjqYzQrwRwv0I+JuGa74b1j1xCeC249ogcMOa2q50wW575sdE5yQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    encrypted_regex: ^(data|stringData|parameters)$
    lastmodified: "2026-07-18T20:07:26Z"
    mac: ENC[AES256_GCM,data:jYjN+8KHqlHcp2Ji1Qozvsno26vezgkmgTXApvGj2cwOE5vd3CuL2QH3qO5GDRv2KTEIISbRnTy5MRzErQ9++YDG63iXy046T5axHBdtmbylMBJI4rPfAByUSO5R70DWAewiC3xsDGo0IJEGLOxA9McQk/uFtflsCidLT05N5Jc=,iv:u2dfBoPuFsdNKqG8K4kpOTYQJ02SMBCNEsFJfr1sAgU=,tag:j+Wq3DIOFpMxjissuEAa4A==,type:str]
    version: 3.13.1
