apiVersion: v1
kind: Secret
metadata:
    name: media-mcp-env
    namespace: media-mcp
type: Opaque
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:C6o0quh7O3kSGkBBUqx3MBeGCBTUcwaGXZJQKfGdp4kTSnQQen8FARRVrmQjqhYoIhR5VUFLJQI25/Ja8XuzxQ==,iv:h6T1AZ+XzZm3Hz6peH9ipR2mreWTTW4vnXyjKFYCWTQ=,tag:715mGW2pRpptTycmFHXC/A==,type:str]
    RADARR_KEY: ENC[AES256_GCM,data:ZplaYZb8HmU/oBvJjdkeIy9eQuxG2tW9d/Iip9PB2sc=,iv:pX88nJb4KbfkCIyZp2RcNmFnfgs9AC4hH6TDRvJjxDQ=,tag:doESxb3qDfjPvKh/veEZMA==,type:str]
    SONARR_KEY: ENC[AES256_GCM,data:qpUzfQb1l1mcE1WeJP3VAmlXIcAF2damBne3n8cHhj4=,iv:647VoZVMFbKJpBPr5MC8/IKJakT0JJKrwkTLtvliZg4=,tag:e8xEAv6klCwAhTtUIbWyow==,type:str]
    PROWLARR_KEY: ENC[AES256_GCM,data:RO3nQtaXDM3ukkf+0J94K/vTLAZvKtVX23wF3Yep4uI=,iv:BP9R3UFwdl5r+8eqrhhL1n/HrypW7jXvjh7NkIaBDiY=,tag:dTmQlUsM++i1oBkp0eTt5A==,type:str]
    READARR_KEY: ENC[AES256_GCM,data:uLN06+M7YSD1EtDc92E1MuQ5DXdG7+j74xRsAn5gBM8=,iv:Ot5sjR+9MbpzEoclur4bKuDItRdo7jNVRguMY5qFV9I=,tag:x3N9OsaQDVEbVrWaKJsrUA==,type:str]
    BAZARR_KEY: ENC[AES256_GCM,data:C0ziMzg0frbmZ3kqgJN9nAhuXUhJ4HveHWgRwIqmg10=,iv:pfvTzTszXi8ME7ZJJV+GeqAKIt5k7g5S8k1w1e9/xj8=,tag:owr5cP9K+rgDCD+zStxGHw==,type:str]
    TAUTULLI_KEY: ENC[AES256_GCM,data:UtUGm09mNTOIbex/wMobkorTh2ieUMASuujHvt0IE70=,iv:JWymaHyRJJzUajcAlcCsQqBcZ6bVv8iBydhPUuSW/LQ=,tag:/hpncd6ckTrQ8ujqQxLnsA==,type:str]
    PLEX_URL: ENC[AES256_GCM,data:ygfJmz+iZP/oI30n6zt15TqeEu1dQstVJBJcoKtn,iv:+CCrPMVqDuHdHqSEA8LDpr7Rk8AX1K3GHs/XQd/OMEE=,tag:a8GRiqw7TbFtlMgkz6FWeA==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:X+G01vZI18k1TA2+mJpxuh8FbIk=,iv:MnX13qX3mfZ2PNxf821R0knHeInbTxLkTVlhj/yJUlQ=,tag:9UbQZuz/7jjnKhxWaj+fYg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TjB2UEJhNHgzNEJrd1BY
            K0YrYXp3OXIyL25mNHZVMW1HeTNsWW5FNmxjCmRLVm8yejdnVDJNbVErcTdEQVVN
            Q1ZyT1F0VFpmelMrS1VMZFlLMDR6ZFEKLS0tIHc0M2lRY2pSYldEN3BGK0k2ZzFr
            L0lNeXhybjNYemVmYjcxMjA2MHZxSzAKSn4cYO/dShsnvSUT/ymZzFABV0oKPWlM
            hN5zZhzCBPM060T+JkaIc47QfjKUW0ndjIX+QuRB9Ecrfwl2UnyLLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T04:55:11Z"
    mac: ENC[AES256_GCM,data:AuTQSZ0ejyOdT1EKLxyrw8PFNhkVVWc6CpfEgjzsmygB3LJBqNUJjUnbE/LNDm7xZVqJZfhzYWNAL7aYAeNi66y1aqcpwAXRKsnDrKEMiiBtXlpkPEgF53h+pksaA1El81UkFSyKfGxvolfeTbi/2j+iNIhKwhbvQp+0eAcwc2M=,iv:P7rSxslIVKf5D84QpfsrHq1FaaTS+NDJJut7BkqVYAU=,tag:VtQ/i7XAx2t/6bBVYNO8pQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
