apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keeptrack
resources:
  - 00-namespace.yaml
  - 10-deployment.yaml
  - 20-service.yaml
  - 52-httproute.yaml
  - 60-networkpolicy.yaml
images:
  - name: registry.internal.white.fm/keeptrack
    newTag: "12.1.3"
    digest: "sha256:a888ef09adffc0fe97d53cbe08c26f76487c48ddfa497a0f6714fd3930c29384"
