apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backoffice-postgres
  namespace: backoffice
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
