apiVersion: v1
kind: Secret
metadata:
    name: backoffice-postgres-credentials
    namespace: backoffice
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:5L4cfR87so/qiA==,iv:nIwMaTpOMqP0RrrvY/U/oGO1rvlNd3Z7hGCT2N4e8cU=,tag:TpVJypLYPBR5epikHwbYKg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:bcZ5QI2d1EJ5BQ==,iv:xfMlV6oCnnFVu5TeRDyHnuOwF9k3bSUs6VjD1y5oQJY=,tag:kMD7fBmpk1K5I+FicpJ4uQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VTHoQRLIVo168T3dkSv144tNMpiF2YjlSPSK4GMFwA==,iv:IrE/BleVVv0FhAIT2TkaVJxr2Sb5eUSofz9Qr6MsOuY=,tag:2Av7/yrQbjkIJ9fuUc2rAA==,type:str]
    AUTHENTIK_API_TOKEN: ENC[AES256_GCM,data:WGvEKKuHZO3whxsuG/EcS/UzjloOqNbQqZH+pnvTZclkj0Jiqwo7kZ2qkY7kwv0h5Lncc8g5JdUNR3hwZAAP5PAB/hCdE9Y=,iv:wHXPuvkwcaIjFTaE49tFadpTIvQgBp9KKGeOzDXs/TY=,tag:0V/xLetEfAYtECFlrv94hw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT1I1TlhXWDcwL1J4NktT
            L3FDVzlwcE5aTXdKeXNPSlp6U2R0RUt6b2tVCkZSWEVUdlN0bzVNT0ljOXhLeUNh
            UGY0SytrU1VQS0pZZ1ZYY3M4azR0VGMKLS0tIFAycFdIZG1peWlHZG9XeWg3VVJL
            eXVFbjZWbURKaStZa3FYdkp4aTU0OVEKq+W/5OJ0mm21Gv2nollXnOJbQx9ubzOj
            xu2gawWyTDi9Ka5o44vjZmzm5uFG2OLqhDKObsTxdZa97JVbzR47Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T04:31:50Z"
    mac: ENC[AES256_GCM,data:xJi+OXdkE+45Dz6OCjNSqPxpuhasXkUgrJYVHPp/C88EEf0QMugsUBKoERqMrHmfmCj4SRVXUsm5QaYTqcAhEi+y7J44aNPDvc6uAaZQqkFa1ddID3X6H64feeatxM9yRliXYBeoTevbU3nYkgH4t34/T63DVaJdzjgrZwZuEvw=,iv:uZff3DoGuyGg3doMZWBikPcBTd/DqZY0TsNX4WsHJ9c=,tag:63mQQXbMcu0ss14toQC0xQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
