apiVersion: v1
kind: Secret
metadata:
    name: condo-secrets
    namespace: condo
type: Opaque
stringData:
    db-password: ENC[AES256_GCM,data:5YxFEmQNOfGJheBq1Cd+fPVmt2SHm4HmON0LKOldtgI=,iv:I7BIUgqJjyZPVLVhAQOU/fTMrdC8jEbNtHtPlK0k7qo=,tag:mIyFMAO/IekFuusBd042wQ==,type:str]
    condo-database-url: ENC[AES256_GCM,data:Mn+evbt3AHHQuKZpUb++0z2r0GYrYYZ3qyfyZ7WdnT9/5HFafzQeVj16dvhXrwHRlhAxMjBoKZ4jAUdllB045+OJwr/LIh0=,iv:na5R+a5Wr7r1E6LQCSULfYI/bflRzHGSiSzfNTlAfdw=,tag:YGwHtBA3WLiWGN9pumQ5sQ==,type:str]
    address-database-url: ENC[AES256_GCM,data:nFa8UyRp05b/SD+4IGZWnPAGaolzHBiyXdhAe9YvE+tuZ5pqHKcVzNBpxPjAdrzEqCGW2lxRUwhG5ho4FAdGqYSC0Bq4/zAMo6pR7becmViJ,iv:fm0x3sFRjJ6iJPRqq4aD2lWTb9qQt3RTw9CncWIX9I8=,tag:EbnR4MBvu5FWQ1+Q6mh//Q==,type:str]
    condo-cookie-secret: ENC[AES256_GCM,data:Li8TiDA4E4ORb6dLkGA1ALE6NrtLV2u6ITXMrhV7GVU0zgcKWixKFlAqKg9c10kp,iv:Holgf1TwKafZcnAtS4+U/X0i4u64aaaFku7bIxp+nHs=,tag:qmUFuPHc3psbjLQETkRc+Q==,type:str]
    address-cookie-secret: ENC[AES256_GCM,data:PnkzzAvdP3E/Sj6fWD+8a4zXIL42mK4VdZ35MVADuSuEMUkAVjyNoadPCNWMYBee,iv:RJT7tZseMVBX+tnUOxCGaCT9RKe5GEJYjDvMTueoXBg=,tag:nCn4xDv7xIOJ9PwBufEYNQ==,type:str]
    condo-data-encryption-config: ENC[AES256_GCM,data:ivIFV3Xsq3e1ZD0BDEBozq+9I1A/b1ilhBmfHilq3JCIZzuo0luQSpUIgHgk5EpXrE4cw/ebSA13KxksKv0tj32QPcXq293OWB/exEJEXNLhPpwAJnF9Jc7mTqpttzIKQNyqVTyet3PhKh2w1ZOwJ0ORxEq58K3xUpvSEMXAhGRSCK0rAWe1cQV6Lq7L6g==,iv:OYtHWhPUEnN/4uqoCkwxNZ24wy/6aM3V1/ozAxcGAvU=,tag:NkUnAt7LFfH+DkyA0YzmZA==,type:str]
    address-data-encryption-config: ENC[AES256_GCM,data:UyLmKbo+8VIlaQSBgnejUTL31ZdfXVULX2n5O7p3GH75g5p5eubWecuvId72htWH2Mi1nWySxWhelBzsZR3fmEaCCq2vRoQpWEFQYTMiGm2NVNfaj6lHYvcb+N0EIT8xHmFU+giqs4uMhruu/6LfZjUuYAMRN12vDaLacJiFheXb5viOTs1B4kng+p45XHVRc4T7qzcN2q4=,iv:aFVogcBqSFPdKZtnHzmbts12pHmXUPsoNSrQ3z7vod4=,tag:AwJ/iMjMZmvkeHFvgOWuJg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUjRmMlFsM0JidmZGYlZs
            VDBTczZZUUNDdHowWU91cHQrQnh6TkhtTGxvCm1lOTNSMW5USjFwZDlzTnA3WGlO
            RjZEV0Y3N00xOHd1b2dGYzZHYVplZFUKLS0tIHBLa2YrTU8zWFUvZ09GRVJTckxL
            NkhZRXhhUzBsQTRaeDQ5MnpYaGdkdFkKLyY+HWmDGGoXL/xI5YuvM4fPjEw55k5U
            E8r5Dwp6bsNMU9yHWrYe6SCsh1ln9LXh4xt1wE7oR6Os8dcBKJ5aSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T15:46:04Z"
    mac: ENC[AES256_GCM,data:d9PGlqIPTeIzjpLOiRF/CTJIvMh/v+P7qowvRVgYJTkcuyLKGUTEegI0Vb1U+wV12o/mQFHo+kuRBdfwJuVA78tHu+7tNmhnL+gLd8R+F3NirU0PiiVHLIe5vG7BlJ3u0+npp5rXEy9h1Q8CzzrA7qCzIkEwWZD6u+J8qd1h3ts=,iv:5mhKvJwZBdRPO4wqEn/HZdErAdAObB52/xCbY/p4ofg=,tag:kIv8FCwiehLhKKh14lVy4Q==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
