apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: condo
spec:
  podSelector: {}
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-condo
  namespace: condo
spec:
  podSelector:
    matchLabels:
      app: condo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - port: 3000
          protocol: TCP
    # kubelet probes
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 3000
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-address-service
  namespace: condo
spec:
  podSelector:
    matchLabels:
      app: address-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: condo
        - podSelector:
            matchLabels:
              app: condo-worker
      ports:
        - port: 3000
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: 3000
          protocol: TCP


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-datastores
  namespace: condo
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [postgres, redis]
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: condo
        - podSelector:
            matchLabels:
              app: condo-worker
        - podSelector:
            matchLabels:
              app: address-service
