apiVersion: v1
kind: Secret
metadata:
    name: subnet-router-authkey
    namespace: tailscale
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:OKXhaWt4EiiRmZPIL9bsceUiCqQTBtql47MBBp/ZjUcOxtcd+n6esWo6eS514kBLnbp5tMyP9A4o8KfuddjQtp+ZhFoxk8oD4QtF3VQbLSXmAy74iULagw==,iv:TOv0yD0Y/irWnoCQ1Hy0kmkUcibbpTdwcUOlIHl4AFU=,tag:OszleI2tKNSuYLvi/1pCXQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYejkyYmZqV01BdjZWdks4
            bmFXOUVTeW9jLzdEVWRqUW15NmV6L2MwblhzCmlXKzRQamUwYlFoYzBtQ0VNaFBV
            M291dktEcnh2QVJ4MzhLTEgyekhHSU0KLS0tIGx1MFQ3NEFnSmt2RnB2TzRWamhI
            UHVScXlENVdhMXE5NTQ1MXVMWGRWQ1UKhi5Lu7RaU/G57EEPuskHKSfDnJHURSnk
            FB7JLGdUEAsXwDgX0DBPRdfBrVyR2qC82wYcCbmrH8rvAQv0I+0b3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T17:44:06Z"
    mac: ENC[AES256_GCM,data:DK3onbgOo4dQT0tCCKpo8zckq3n7AW6GVe5Hyjz3ghtPkG7K8CTEPd2qDaK7jE9gpqvkwPgkuibVJJ1XkE3KDB4ILi3QwgVhouzvttbKFKo+VMYJ7NESeFXtI8W3Ok0UixSg8TPfEVxuGKh06MYIGObQo7+lvIQvAahIvVfOGWE=,iv:vBbUKslrs6Onqy6fgw9sk2nLwq6GOausrw/FRare2Bw=,tag:wwlEtQ4C7JLiHbRYS1YrtQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
