apiVersion: v1
kind: ConfigMap
metadata:
  name: raven-nginx-conf
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;
      root /usr/share/nginx/html;
      index index.html;

      location /raven-ws {
        proxy_pass http://misp-raven-bridge.misp.svc.cluster.local:5678/raven-ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
      }

      location / {
        try_files $uri $uri/ /index.html;
      }
    }
