apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-hookshot
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-hookshot
  template:
    metadata:
      labels:
        app: matrix-hookshot
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: hookshot
          image: halfshot/matrix-hookshot
          command: ["node", "/app/App.js"]
          args:
            - "--config"
            - "/data/config.yml"
            - "--registration"
            - "/data/registration.yml"
          ports:
            - containerPort: 9000
              name: webhooks
            - containerPort: 9993
              name: appservice
          volumeMounts:
            - name: config
              mountPath: /data/config.yml
              subPath: config.yml
            - name: secrets
              mountPath: /data/registration.yml
              subPath: registration.yaml
            - name: secrets
              mountPath: /secrets/passkey.pem
              subPath: passkey.pem
      volumes:
        - name: config
          configMap:
            name: hookshot-config
        - name: secrets
          secret:
            secretName: hookshot-secrets
