apiVersion: v1
kind: Secret
metadata:
    name: authentik-bootstrap-token
    namespace: headscale
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ksjzhtyA/Jen3OruT6KmBZIkoUsoclDuRDIdwQ+sLUUQSCTHvMAOfEnDuPNJe3YtYFDD7tobIHoAlZzk,iv:KJSeclh/e78iiURAZ5So3lGFLoXbo2TSLyYxMEQKn/M=,tag:NOfPUnDJFxgJ6FoP1NPlWw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0L0kxaXJGNU0zbmRqWGdO
            L3RkYmxsSDBXU1hWZkFnaHJnMCtkRmZqanlNCmlOKytTQ3NweWVuYkVmTEg2VldE
            N0k0cjU1U0lCbEdIcmV0c1d4aGoxTUEKLS0tIDdkWWlaUVFCNU84cW44SXFoS09s
            NmlndWxSVmVGNmZ4YjV1QzJiUDNMYkEKhXPPKJneeCDGZ1Tn6S8WI+TvR/GRzo7G
            fI+a3ppGrzPwCqAFzk8obOLk/zP3spI5kuhO+x3cIbpFY966IaaArw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T04:46:12Z"
    mac: ENC[AES256_GCM,data:Nni1Oi9BD/OGx5+JXYSQsegEwVSTRNSkDJKI3AY0SjYqgicN4BinRiu29WQPceVQCSlKt4m9xkNAp+Q182LG/0FMa6RWRaaWTRmGVLRbafCwRusb+Hq7Yib1rJmIbLSd0kdAuFwaAcBYOuR27l7saw2UimobyLQtSq1wDafVhoE=,iv:CITjAS7eAHq1BlBWXlwFM21xg0GJu+C5zVq4onVA96s=,tag:XtqjmZSsHmZ+JOAa9YJ6zA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
