apiVersion: v1
kind: Secret
metadata:
    name: weather-secret
    namespace: weather
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:U8ZKBI3Q+UQE1lHbBELb6mje1UcRFC6ZYSvg1BbXLRSyuPzjquObkdMsM4lIN8iwyZrxiQsM3TKzgHWzYdLlz1V21SKdTk/OCvZV90ndKeoz4cL32/TvcnpA66MdncUs2WySVgKvUH3WSevBmlyKIe5cRg0j88sgC0PNqX58On20hdZ0EKsOM/2Ygc/6+Ldpb21nmzoYmtZfMYfHMi5qU9q95jiSk5obncb6yBuXI8lFHUSgC+QjC9UEFHH56B9YjeHUaBKGiqgHV3cr387t4nUBFEToXVe0fek0dplauqpCzSwKQ2XdgtUZFEIF5pGs2MhSTAy0m/s5yX/m33CrMv6u0NOWIApB7WD3+lD5sMhA1vP3cIjHx0foUbBE4VCwCN1Ah0rBhULODEXvtIWmAT4tCMiMoYrR8wPGPRqWEm/T57Gz0vDnTt+IBthY5NbegALTTc9dsC7tdb14CuRVK15SOMVmofKbqz3UGXHNhfcTcGPCPj/y0Z5xwKHKPsHHRecSUdde4j7/5wPh////HAMYOI8iwtojucMEhiEbIJx6xtVopbH5MuBN462yP+4TnppPHMaEO2vuGrk7b0AZIbkk/7G4YrE6HTgZ0UJt3hd6FKQ0F2GvZfgkjn2aaEDXILdrXSMC11Sap8Vg1vC5dwOEk6LozRqsXXLTzE/5zKM39gLsChxxeuQ4i/ZbVZKiUVmCllX6C3LkVOTmhyDtw5m8HWra4LrGtx5j0uVkd+8So9tAvDOpDXzMOgMBs1BAqyNJsk4ZXMUXHUwAyG+ynyRzXsfNQrYTU8m3RqMppVgqGa/bY8iwD37VyTcey6dNzQ==,iv:39+e//SlHiJgGG4s6zy/BuyhZQDHxgylDWXX4hpnUsI=,tag:/KDmyLpHOH1Lr7gArh+h5A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMWhXdDFZZUdVNkVkajl6
            Q0U3dWNIcEp4Y3phYWdlK1QramtJaWVCMlQ4CnU3ZnRjS2V6VEtrYUVYa2pHT2Jo
            WmNxQ2NOSklHUG9FV0UwdVJ3V0xmYm8KLS0tIEhqbHpVR2VSSmcvdHZkelJsTXNW
            VGxCVGtLQitzWnhFZ1RzazRhM2RUNHcKemB7LeXgja15hFcFlJisxRG9sGoS/pc2
            ++Zgf0IIGsNIhm+B+YNNtBbPExaM/z6MTyDOQLd+5TzN2hsRqgazbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T05:04:16Z"
    mac: ENC[AES256_GCM,data:CXp5KSkLz6kbK/GhtDdiJjzXY9dUrQB6swZ37oNM9J4HSrn6Bx+Stct7Dk8cxd0WflDt/A2rP4gJ5DVwNvMdzvwct10JdETQpWbTjRrh76h/8n8N9h6yydKEFej0ivY5NQaH25do+pCIWFLqOVDLFw7+n/Vq1pLHm6GHG+CThWo=,iv:pZAoHF5sDYYr2Q5K8cJg3bxTI8EBdzAxEJ5Az9V4KVI=,tag:Q2sm6ZrrYKgb1jVa06NS2g==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
