apiVersion: v1
kind: Secret
metadata:
    name: weather-secret
    namespace: weather
type: Opaque
stringData:
    openweathermap-key: ""
    airnow-key: ""
    observer-lat: ENC[AES256_GCM,data:OUQsBtUxvxtXyOgfEBv0wQ==,iv:v9PUpon0sU6ID5+Wzsy5b7j0bh9KyU/AQsGr3jvFjFI=,tag:+ZuLZP18+dF/IPljHQO/OA==,type:str]
    observer-lon: ENC[AES256_GCM,data:XGiBkqYalGKNlUU6wT1fnrQ=,iv:XoQnS0D7W/eDt2TXbzspPeo1bpUgrlNrdOkjHrBlmGM=,tag:iwy0a4Onn5xBl/pQaHNO/Q==,type:str]
    observer-location: ENC[AES256_GCM,data:XkoA9Wa5AF0Wd1Dq,iv:xfvu9BO2AcGl8AEHDi5nFSNAdFd3C6VCugJ87oIxrCs=,tag:Y74JLAX2I0fzBHfKZHuvfQ==,type:str]
    observer-state: ENC[AES256_GCM,data:944=,iv:hQCkbI9S0A3/Np5dN9cxbGiDmNi7Vwbx2WFYgWQabE0=,tag:vCmvOfftJZy8bcth20q85A==,type:str]
    windy-key: ENC[AES256_GCM,data:YVYuo5FZ5PIMyu40kvRTjFfRBSylj+j5q17RWNWnvAk=,iv:EZbG3JmTqSyVfYVi1CRY1sD1ZJgi7aKrxa8ZDzbsQNc=,tag:UiybvsqRKBUs9y9IgnxkmA==,type:str]
    ohgo-key: ENC[AES256_GCM,data:KJyFK1wCRQRSTEt9huxg5g0l2PqaxxocnUDEEeyyTGahVaTZ,iv:QC6bCz3q2ggGF4raFRe0qWWiZ5U9M52kGPq1Uamr95k=,tag:bUxkKprjhntP7S5YEGulbw==,type:str]
    youtube-key: ENC[AES256_GCM,data:G9QLlaYtDcLIzmLgFV8I/Ow2KJQNKCirK5xCXw27pEjc4984YJgR,iv:D2FT0QaXqz9bmB1BvbnSdmHaIT4eTgchMGtuFzcbkcI=,tag:E2BdZbrzb3vUNPqtPAOiBQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMkN3K21raUtBSHJaVFZ6
            V3FNTmFTSUJzWmwzMGZCUDNZMlFyMzZ3ZFJBCnlvQTRXT0FWNzdrWUVlSWNXMGZG
            YlpCejVTOEZDLytiVjlVVStLUzNJZDQKLS0tIDE4QUhwc2k1QjV4K0hwRlkxb2NU
            M25MTk5Mbng3Tng0OXZIajZYdUFCK2MK25wj2J8G3jsaB8P7t1W8f7E0kj8Jzuuc
            4oIaaJRbJO80ohGnhdief5dIqgOBR9IX1Ue3izfq8B1soxfKC1irQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T23:10:49Z"
    mac: ENC[AES256_GCM,data:f6UhuZQOD4I0v0LwB5Gyau1ico0Y/042xzMdN8fAYAK8+eGeE5ZiPlkpPgNtgkAvdcS+dnmybmGS6ssD4mM1NFNmviX6+qq3994GsW44tTLoWW9buAONSHnyR4l6SGo6m/Pi/OQfHP0NzURjLrqrzeGLBi02hyUjKX9OJP/d2NI=,iv:Qv+B49zfICLJOHjxCxSN9IrwDkx6uM5JfIRaEV9OMHw=,tag:DPsckwQ7reNxCG5p1Slp9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
