apiVersion: v1
kind: Secret
metadata:
    name: weather-secret
    namespace: weather
type: Opaque
stringData:
    openweathermap-key: ""
    airnow-key: ""
    observer-lat: ENC[AES256_GCM,data:OUQsBtUxvxtXyOgfEBv0wQ==,iv:v9PUpon0sU6ID5+Wzsy5b7j0bh9KyU/AQsGr3jvFjFI=,tag:+ZuLZP18+dF/IPljHQO/OA==,type:str]
    observer-lon: ENC[AES256_GCM,data:XGiBkqYalGKNlUU6wT1fnrQ=,iv:XoQnS0D7W/eDt2TXbzspPeo1bpUgrlNrdOkjHrBlmGM=,tag:iwy0a4Onn5xBl/pQaHNO/Q==,type:str]
    observer-location: ENC[AES256_GCM,data:XkoA9Wa5AF0Wd1Dq,iv:xfvu9BO2AcGl8AEHDi5nFSNAdFd3C6VCugJ87oIxrCs=,tag:Y74JLAX2I0fzBHfKZHuvfQ==,type:str]
    observer-state: ENC[AES256_GCM,data:944=,iv:hQCkbI9S0A3/Np5dN9cxbGiDmNi7Vwbx2WFYgWQabE0=,tag:vCmvOfftJZy8bcth20q85A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMkN3K21raUtBSHJaVFZ6
            V3FNTmFTSUJzWmwzMGZCUDNZMlFyMzZ3ZFJBCnlvQTRXT0FWNzdrWUVlSWNXMGZG
            YlpCejVTOEZDLytiVjlVVStLUzNJZDQKLS0tIDE4QUhwc2k1QjV4K0hwRlkxb2NU
            M25MTk5Mbng3Tng0OXZIajZYdUFCK2MK25wj2J8G3jsaB8P7t1W8f7E0kj8Jzuuc
            4oIaaJRbJO80ohGnhdief5dIqgOBR9IX1Ue3izfq8B1soxfKC1irQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T21:27:09Z"
    mac: ENC[AES256_GCM,data:w7mjwy6iLP7518gjbnXfYLhRfAtwWJRDPcGm/1zxWFvrhkH6LfF1t+wokETMeXCjxRWN3XFQBRt+6bRRtdQvTTZW1YLoiB0fjieE+P5RuB+bMgQlI/EWy6olN4QA6djLf0mKEZZmLZvn3nYzDohn0kxcoq8a8cVepF9yQHJK7E8=,iv:LRLyZEQvovEJqrSscB5JT2LKRSgTTuT2MFDF3v+K9QQ=,tag:/fL/YCC3zZFU2JEXgSt/rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
