apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: weather

resources:
  - 00-namespace.yaml
  - 10-deployment-api.yaml
  - 11-deployment-ui.yaml
  - 20-service-api.yaml
  - 21-service-ui.yaml
  - 52-httproute-public.yaml
  - 53-httproute-internal.yaml
  - 60-networkpolicy.yaml

generators:
  - ksops.yaml

images:
  - name: registry.white.fm/weather-api
    newTag: "1.0.6"
  - name: registry.white.fm/weather-ui
    newTag: "1.0.8"
