apiVersion: v1
kind: Secret
metadata:
    name: repo-whitehouse-glacier
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    name: ENC[AES256_GCM,data:t3uz37QVoiMwMXBC6MbJ3tym,iv:ffRvzJv3xmPzDmYksIVk06Bwf86hLDjuJSbpA6KO6gM=,tag:djqmmH7lKmULmukIEepa7g==,type:str]
    type: ENC[AES256_GCM,data:Is9O,iv:srAJpCwEGr2lpIZYPj1eI45hZAV0XVdHQYZywxbhkdo=,tag:ah0SN+FswoA85fBklLwkuA==,type:str]
    url: ENC[AES256_GCM,data:iavsyon9WGNaO54IVTUb7yQXHzgH2wMLTUzv4WYUA0vtiX49irUClMYPZCYw9EkqzK4=,iv:nb78lOHllYeZsMqBPKprOFNcNHk9e4dzCCINj6i84xs=,tag:0cYWKAlCEvWM80Kbga6XjA==,type:str]
    sshPrivateKey: ENC[AES256_GCM,data:f4YyExvWNoImd0vHqhQ4ny6dqMkaslS6JauWDPHNMguwvB8G5HuvSY/orESCY1GizTftPPjFnwPQjhqWeWxWsJQCIh9Wm0SkzqzjIisBCGEX51HQzuftMJtYTl9dKM2YxD6tAE+vF7YLjC+o5dyNQey+x3WEQOetg0M6RoT9gA9MoIxMkwUp8RxhuDJKF/f0G9oLTmnp3lvGfb8trG0W0qgdu4vlHNLdsprVeTDpkFFlBthME0pGXA5O9dlFbWgueoxIh9wNs4ApWCQwcEbnA3gvxxL4UL84TaOoZbj+cfu4wc5KfauqqkMF85XU9IWsPZi8c5qGWSsTxDtv2OvV1UsWdIV1BfJd5NMn1V06NjPanJn8OciBl9WmBLIHJvOpo7FvdrOFq+1Om0rh8MbWunRaPVNQIfsybcNV7PHB9+EjZhBfsSVUB1oSYuwcslL2fi1Qu1/WNWq8wUXqVZnr7mEK8DnBgN/KmAl8BDNSCk0paR4htiKKV+AUQY51Zfkr9uskqAEliY7ZxzsaoLxZZuoGj4ZG4PjicSH8nxIPYeqGzP8=,iv:KY1FxRaWEo9G/IMdtDS4S/4Leuyf6wbl9l8+UCpyFY8=,tag:YNZtSWgQZOMVkr5k2EJ0wA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQnc5eHhBUHdJTjF1eXFJ
            MUtyUjEvcUVOa3ZlNHpaQlRkUUx5NWtRYlgwClJiVzJ3KzVlQjhxOTdBYzFPdUR6
            ckNhUTJZUnVvTnVSWjEzVjR4cTdnL0kKLS0tIDRQN1c5M0M4ZkV5WUZKdXRFdHow
            NXlSZ29KcDhOK1djcWE3VVdBaXF5WW8KOmQzvuMUxM5bFYLN3XL8QicvweMeV3eZ
            88RRDto/0QoPFv9QPHcwRdM3XNoGPX5so8Lf1J/2KQpWUuHzLc6fag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-04T04:48:26Z"
    mac: ENC[AES256_GCM,data:4rWGbRE2vq26R0P5xDdT8jEQj4Io64FQUFxIureDvnAyD4yil9t+pWRrWKupKPwWAUJAEeav+ZimyprkRQopQwc405N/rwcHW0yL/fK0Q0sR0i/tF7aIFSSxvVBchpzYS7KOxtgai2LkgAK3eKESVpKSB5/fNPLqKE/7JUOkHss=,iv:AcD8GPmstNuicKDMjF/LCzvdxN7jm3SWJ76GF+T2jeU=,tag:HXwzrq+tW4NRhbvqxqmrsg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
