apiVersion: v1
kind: Secret
metadata:
    name: sops-age
    namespace: argocd
type: Opaque
stringData:
    key.txt: ENC[AES256_GCM,data:id762vaY7jek7OZw7P3s9jCe49N9ichEe57epEwZmGI1knsFkcpLmRCXMjV7D/265FgrPVQiIIe+RmfG093YGYC5QpFqCmR3W3E3eJbDMmyaNxvZiCxHztaXBewMgmZqVJqvvpDSj4N6gT/6LTDrJGnj21b/O3u7Z04RKlPbh50tFkgEaQul+HpNLX1ltmqSBHq+xq5ZiwGAM5Pjf+hwtQZqyIwPqQIwTZVlilXgdhRvxLBfglvj05bFu8Q=,iv:IPf7G6r6SwxqcBzb+Q6tDmqXAqReAPKgfPw6F0zEYbo=,tag:7FYKJQ9Mr9jG0x449Fb0hw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM0NFbUJXNjZxSS83UXZO
            akY4WWQ2L2wyZHk0UUNhQ2ZKYmIvdlk4U1hRCmZJc2gxVGF5Y21CTXJsQ1RiNjVh
            WVVhY2l6cVIwcFJjK1oyY2U4SDNkdzgKLS0tIGlveTA5ZTFNbUUvZWNCN3Q2MkVP
            RWZzQVlXRnBQVXlMQkx5ZlpBV1JtdmsKIpvUQCuNnqHm/yjzDXb56rpBJWSs0n1Z
            FwBumXjOywFVWfFey0a3die5nazHaro2sS9yC9XpE055/jsQAv/8cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T17:43:24Z"
    mac: ENC[AES256_GCM,data:krK2zRxiGEMiJc5VQj1KOFZFkgGwfVf0H6C7SOHiOzmzPD0FUIwelp9XImWI7YGvbQEWFO/hos7yH8bq1y2GJZq2Cs/b9fsgbf6vOA5XmRBFhmrNeIqxsx0lmH4JKMBk76GfsuGqGUQduO0UChNUAWWIsiTwb6cJTRfgNUsdIKI=,iv:/zJd18aq7Bsaj+SfvPYgzkACTwuV1a3iNZIfZoDTuiY=,tag:CrxOWpVs40H5TYTejE2NAw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
