apiVersion: v1
kind: Secret
metadata:
    name: backoffice-postgres-credentials
    namespace: backoffice
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:5L4cfR87so/qiA==,iv:nIwMaTpOMqP0RrrvY/U/oGO1rvlNd3Z7hGCT2N4e8cU=,tag:TpVJypLYPBR5epikHwbYKg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:bcZ5QI2d1EJ5BQ==,iv:xfMlV6oCnnFVu5TeRDyHnuOwF9k3bSUs6VjD1y5oQJY=,tag:kMD7fBmpk1K5I+FicpJ4uQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VTHoQRLIVo168T3dkSv144tNMpiF2YjlSPSK4GMFwA==,iv:IrE/BleVVv0FhAIT2TkaVJxr2Sb5eUSofz9Qr6MsOuY=,tag:2Av7/yrQbjkIJ9fuUc2rAA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByT1I1TlhXWDcwL1J4NktT
            L3FDVzlwcE5aTXdKeXNPSlp6U2R0RUt6b2tVCkZSWEVUdlN0bzVNT0ljOXhLeUNh
            UGY0SytrU1VQS0pZZ1ZYY3M4azR0VGMKLS0tIFAycFdIZG1peWlHZG9XeWg3VVJL
            eXVFbjZWbURKaStZa3FYdkp4aTU0OVEKq+W/5OJ0mm21Gv2nollXnOJbQx9ubzOj
            xu2gawWyTDi9Ka5o44vjZmzm5uFG2OLqhDKObsTxdZa97JVbzR47Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T03:18:33Z"
    mac: ENC[AES256_GCM,data:YOlErPBNPEmRlwB7qlbtQD4mDogjWLBYe2iUKUbgYN013lYhRcD/LexANH2vxhv5I1YwyuIDvXyq+98QV9BM8r9p17caG99GR6tcegfVcTpvDP1j+K8kmeIedQRuqNkoJPhszSA4PI3SDYVYfuoO8Llxsvv/FrVOWERq2IB13oc=,iv:rwx+AZ4+L5ywKfmL8J2hhd5Q0TGIQKQjawwzcfQDKw4=,tag:YMUbCQ0C2GxkruUE388soQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
