apiVersion: v1
kind: Secret
metadata:
  name: backoffice-postgres-credentials
  namespace: backoffice
type: Opaque
stringData:
  POSTGRES_DB: backoffice
  POSTGRES_USER: backoffice
  POSTGRES_PASSWORD: CHANGE_ME_THEN_ENCRYPT
