apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backoffice
generators:
  - ksops.yaml
resources:
  - 00-namespace.yaml
  - 01-rbac.yaml
  - 10-postgres-pvc.yaml
  - 20-postgres-deployment.yaml
  - 21-api-deployment.yaml
  - 22-web-deployment.yaml
  - 30-postgres-service.yaml
  - 31-api-service.yaml
  - 32-web-service.yaml
  - 40-authentik-service.yaml
  - 50-ingress.yaml
  - 51-ingress-internal.yaml
  - 52-httproute-public.yaml
  - 53-httproute-internal.yaml
images:
  - name: postgres
    newTag: "16-alpine"
  - name: registry.white.fm/backoffice-api
    newTag: "0.2.2"
  - name: registry.white.fm/backoffice-web
