apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appstore-connect-api
  namespace: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared
  target:
    name: appstore-connect-api
    creationPolicy: Owner
    template:
      data:
        issuer_id: "{{ .issuer_id }}"
        private_key: "{{ .private_key }}"
        vendor_number: "{{ .vendor_number }}"
        key_id: "{{ .key_id }}"
        app_ids: "{{ .id_graflens }},{{ .id_solacoffea }}"
  data:
    - secretKey: issuer_id
      remoteRef:
        key: "App Store Connect API/username"
    - secretKey: private_key
      remoteRef:
        key: "App Store Connect API/password"
    - secretKey: vendor_number
      remoteRef:
        key: "App Store Connect API/vendor_id"
    - secretKey: key_id
      remoteRef:
        key: "App Store Connect API/api_key_id"
    - secretKey: id_graflens
      remoteRef:
        key: "App Store Connect API/id_graflens"
    - secretKey: id_solacoffea
      remoteRef:
        key: "App Store Connect API/id_solacoffea"
