apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: appstore-connect-api
  namespace: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared
  target:
    name: appstore-connect-api
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: se4nzrvhn55ckbqxgqeaju6f44
  data:
    - secretKey: private_key
      remoteRef:
        key: se4nzrvhn55ckbqxgqeaju6f44
        property: password
