apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worldmonitor
  namespace: worldmonitor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - worldmonitor.white.fm
      secretName: worldmonitor-white-fm-tls
  rules:
    - host: worldmonitor.white.fm
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worldmonitor
                port:
                  number: 80
