apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-streaming
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon
      tier: streaming
  template:
    metadata:
      labels:
        app: mastodon
        tier: streaming
    spec:
      containers:
        - name: streaming
          image: ghcr.io/mastodon/mastodon-streaming
          command: ["node", "streaming/index.js"]
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/v1/streaming/health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: mastodon-env
          env:
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: secret-key-base
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: redis-password
          ports:
            - containerPort: 4000
