apiVersion: v1
kind: Secret
metadata:
    name: meerkat-mcp-env
    namespace: meerkat-mcp
type: Opaque
stringData:
    MEERKAT_API_TOKEN: ENC[AES256_GCM,data:yUUYgfe8Ls0esPgzwO1HKMvI0mFix5T5tA7rfU4i+nQWiVc/9Q==,iv:JqyjZfGqgSpda04pXeK19TeZDY7YEvj9F9ofSIZmIHk=,tag:kSzKKox1GVFLorPEtITpTA==,type:str]
    MCP_TOKEN: ENC[AES256_GCM,data:FrvH7pGnuBmYHclAsF72e0Ntv95n1X+9JXg/Mu/iPZK6ekiPZ03DZGZk2O747bleTNvaJOh1kVUCBNL6x/Y5dA==,iv:prCEXR9cnu7lBig/aNSnc8OxFHrg5VrdBLaFLuIJ3g4=,tag:oM0ekWZLodE59ky6T/TjBw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdzNCV0lMZjZOQStmSXE5
            ejR5ZGVNeG40RVI0YkR3T21WQWlvUEJiemd3Cm1sOXpnOURjYk5wUnNCd0c2UDF3
            V2pyNHUwdnBQdnE3NTBQNEV5SHRuamsKLS0tICt0NkJEN3ViSForUkJlUkVzV2FF
            VTA0Wk14cURSTVYzb3hXWFo4SDRRbmMKdAIlpmxSP/Gw3dWS6V5Dpe57Q8KKpkiq
            ScuqslM55YJ+ttZigFtXHfqRAPPddT4uUpyUG8ORciSFc75tz5uzIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T04:06:57Z"
    mac: ENC[AES256_GCM,data:DUVZ7Y9D/sBvT/A8r4CAwoiKynVWyuSkmSi8usgrd0Y02KF6o9zy+aESv4WXN4FezmhWi+VtbRnzSQ6eKUeC16xlPmb7FNO/t/PXkhqEGmZsI4Ek8LLwrKBq4jIHzk1YSpepUxSA0NEF4r9rMfS5oO5tmc0jkYQOvPE2n3Szbeo=,iv:4dMHbT3dlQtc879RANCPPcGGxfyDfRHRW2U+NTGjwRI=,tag:a/VU9/qyLf+tXo35/8xOIw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
