apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-ingress-nginx
  namespace: kube-system
spec:
  valuesContent: |-
    controller:
      service:
        type: LoadBalancer
        loadBalancerIP: 10.99.5.110
        annotations:
          metallb.universe.tf/address-pool: lan-pool
      metrics:
        enabled: true
        service:
          enabled: true
          port: 10254
