apiVersion: v1
kind: Secret
metadata:
    name: opencode-secret
    namespace: opencode
type: Opaque
stringData:
    OPENCODE_SERVER_PASSWORD: ENC[AES256_GCM,data:hEioN7tfoY1JwMvM1PkwqiAl7q9Kh+KMoFgWbQ==,iv:pIdju96zV9dRcNolX8KnKKXP4QOn6WUFHJAXq19zsjc=,tag:IROn7+GbG6YipuOam3vaqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4QUFKRkhuYUI0Zkh6RjN6
            WmpLeld2M3lJVzJQMWtEbUNyZGcwUHN0R1NVCitqRWdVTEhkVFkrRktFRENEcmJM
            bW4wNVA2Q0VYMkZiYXhCaVM5L1VrSU0KLS0tIFBNTU4vZmc3ZmM5R0UvMnA3SlYx
            bVlzTzg3ZjJIaTVVSXJOdlJkSmx3QU0KXLPPN7iRQEYBFUWwU13rpndX730AWCu0
            ajU195YkKggsxj9Y3kA+9IGXz+7KwJTrTC+Xg2e4x3+w6N2+jdsO2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
    encrypted_regex: ^(data|stringData|parameters)$
    lastmodified: "2026-10-03T18:04:59Z"
    mac: ENC[AES256_GCM,data:gGlCpEM8yiZUfVJ3/BTHEYSJUogth+4DO+jEFk5WEeSGB33WyD4vY4vy3tWMaXUHg86Og+l7QSFwcrMhmw70786gEBFjjoS6HZxsjLKhH92xeQpuajtf37IaHf8YTgHlT0W0/kDvrlJurNtxlqYgQWlX4QGjsxRXqQWErAFy4MY=,iv:Db7cEQlOHVhSZpVURSIs1DWd5mEIoVhnErJl3itYBSw=,tag:kqC59sLYqyp5kqAsiln4Dw==,type:str]
    version: 3.13.1
