apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik.yaml
  - authentik-worker.yaml
  - postgresql-deploy.yaml
  - redis.yaml
  - postgres-exporter.yaml
  - redis-exporter.yaml

images:
  - name: ghcr.io/goauthentik/server
    newTag: "2026.2.1"

  - name: postgres
    newTag: "16-alpine"

  - name: redis
    newTag: "8.6-alpine"
  - name: quay.io/prometheuscommunity/postgres-exporter
    newTag: "v0.19.1"
  - name: oliver006/redis_exporter
    newTag: "v1.82.0"