apiVersion: v1
kind: Secret
metadata:
    name: hermes-matrix-secrets
    namespace: hermes
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:L0V/NhyyHdeqFou34upEHfQ5Nf1rjOhvvizJ1/h0L2UbeXcrGZr8QA==,iv:aiNi4764wF8OuYNvZiJVO8mIkjyVSEf8L8Z161R+rxI=,tag:O7oEud/kHZPyQTz7Efbtcg==,type:str]
    MATRIX_DEVICE_ID: ENC[AES256_GCM,data:BaCBxWII3y5z8WTYom4=,iv:QGDsQsb0gre7So3duPgWJUrS9PrSCjGMXbfWTxtfKek=,tag:b7v72GuK/IX0uyLs3UFa2g==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:DyiTRhdzsI4GLvaRoemcqxG2mMuhyx3K7BvdyOsDGoE=,iv:3v45+MoR51/j3ewWTpDvjgJ/BueS6cvTTAILsjmVzEk=,tag:4mP6Z5M7OfqXVwykvOGSdQ==,type:str]
    CLAUDE_CREDENTIALS_JSON: ENC[AES256_GCM,data:VA+QoP8VXe4E9AwJpWkjoGAifvlmEqvcd9N2Rauhi6k0AwpH6IiRkGuRulDH0uIQXkqLos650vW3WhV3hgo2FZ+wYCeil0Y1V+XrNo0K5BTBZOZ3ow4CXL3EVXB9o70SyI1edWJqKszpW4sMMfpwJjrr+ENKoJ8DD0RlF8hRA9SNMNMvVVzu8UPWk33BfD1HkzougyYuaTry9myU6ukVuP0BYX3I04feQDjIHGABxcZ5O70POil5tlhkcUpeTTYMQfzBBVlgczMPYkEBW5L27wCXeUdPwXQKszZ6GuzWQ1zdZrdYKOSEq7zDdGntkMfMqNA96YIaKlVsRGb5YqbJzReMWFsB/OHcavwsQjS0gj0EsyQ3muKUlr2bCXSqR709J6UR+tNxxvNAPUTzpLRj/M9f7fe5/QkgOZo494Var+ns6jWsdRDqC9+MEnkMPmEnKiKmKN0SSF0igFwsTsbZun0sLrLDSPuXkfXp4UTR8uat4BIFyjrJ+shOrk4GJ8+n29PG1zZ1qDwoOhZIWdMLsA0zw2Rm0ngT6HOhPvsVNhrRPvIaqVpuRE6fHjgTv4Dxe1uEJm68HzjdQFAbTw1WGviNSX35G2WaGksUToik/X4tbydUB2Y=,iv:GmIT/Z7CS0RZF9Vc24Jpjr6FzlfAtbWd3dhCUeCbRW4=,tag:1i7Tt0W4lj0cAvF+1Zpd5A==,type:str]
    MATRIX_RECOVERY_KEY: ENC[AES256_GCM,data:HbMT01mhihuViNJbkF+38/QvNEhKuheJpNmFm7TuwVmUfQu9RPYybqYvBJh+NW4EP782m12H05zJDHM=,iv:CkhBV0NtZj5CNX0Hjj2eMsk9ROlioV1j96s5Ey8PFOk=,tag:ETO8PJPg0Kndj1UeF+ZZxg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5elNrcEIvNGc2Z1E4VEdH
            ZlN0ZjJtSjcxbWVFS2QwS1BkczBQUVd0bndrCnUyaDY0ZVY5SmpmMnBPVnYxNWYv
            N2MvaGdzY1BXVmtxb1NJSjh1eWF5WVEKLS0tIHBydUFOMitVNm9PL01LNFRxcnNI
            UW5wRGhKMnNDbjZDTGxTMmt3UHhEMmsKsVajz/nv7xuybS2kTSGZu4Hor87yPYHl
            G8+NjyYEp/tQz9T0owKK7R9xagKfYlebVnV2wU1qSc0K1kwF29fqhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T04:25:27Z"
    mac: ENC[AES256_GCM,data:5LuU1QJM9G1UMZ7AdFiE4CVakwdOzvVLnCaoQH18c8J8R/ilUO3bY8em4YR+lIecrO5ir2h6RuBCnJESlc4y699cellTrRt2rMzJsXFCfvVTMC2+cP9VI0tRPdFwh6bCO5MH30qHjWMBlVuf48prVpvNBSizfnFovi2iED+kBo0=,iv:E6JDIg5Giemhr7qeGZ2W1fPGSomNyZoj0v3+DO+uDAk=,tag:TqgRZ31QYv7W7ZPKtl7Qaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
