apiVersion: v1
kind: Secret
metadata:
    name: homarr-connectors
    namespace: homarr
type: Opaque
stringData:
    #ENC[AES256_GCM,data:PdaNG+MfzS4bD/NyMN5a0s6TtiZxheiq5BwgNJz8sQKFi8/Gs4GlZtQNzPG+r+N+wU+BalbpkIxRIOE5Wl1GSaA=,iv:1g/ZHwyqfjiMZtsWIPoVlvgmTsvW6NAYWlTVb1CCAjI=,tag:Il5dGY+Hb8UjZtuN6xE8Sg==,type:comment]
    #ENC[AES256_GCM,data:FyyKDtzleV7A0g3DmgkAU/DF+DJBElf5v66un07d3+5r8K8436pdZcjOR4KHoDFBzoYCLUMnD1jbBNWxBKxKNCQ8GaBeNHo9mHkq,iv:yl0fx1i7U6wtVsZl4Va7ViIefHz3HG5OamfIWCjSk7E=,tag:bMAeBlqT0Hki2Uj8iGstdw==,type:comment]
    #ENC[AES256_GCM,data:XbZydckjb+2jZdeWU2nDOr3WTnJd6DQhKW/InyttloE7A6JXain1GuhuZxIXCj4t+TV2XbwpirVDS5GmKSog/5iKxKQ=,iv:VBRcUtBa/CFvnti9KWoD5+Av2hnTG7uHAczAgU18xv4=,tag:hOtHzZGhWpZ66uEBE/t3Ew==,type:comment]
    #ENC[AES256_GCM,data:2AAtwqgLrKaRSAIgdgBkkwuAAYxwHkF7ur2K3K6+C1lskhGgrUOXiotMxFem5PDIuF2ncp/oDuADygv6J1gSv6NvLuctrbqEHwKTsdo=,iv:q0/pSAzEbxGbA1YEov7UmrOczy9fAviosR1E7jSbIxA=,tag:QP0GhIHOV1L2RlVVMHKpvQ==,type:comment]
    #ENC[AES256_GCM,data:8nf00XJg+CSH6Yd3QBRuSafmOiiHDxLwFRrHXQadgnfFpZ57/PpuiYW8OWYkXXcRxmXvPR+iB67mSZXpBF9504tJJCwmGlKFkKNy,iv:jaNOglDRqGoOJ4JKPMVs8vPgFaCVl6/qX7Ha5vvg2yc=,tag:Kv3NS08PY8ywK/kQDdv3iA==,type:comment]
    #ENC[AES256_GCM,data:cwfUowV3d6O3n2XbLn0rExpNw0RRU8jJWeSGlV0eWS5A645cCmeY7EABDQXHpUJeGZqh4ZCU52U1IvljvdUAG28=,iv:yIHGEYx4O6qf1JMDDYLTJpVyHS8bcr/hbpUFvXDtWs0=,tag:eVM5ytzrB13PGZJYo0JQPQ==,type:comment]
    #ENC[AES256_GCM,data:Y8MIf1pzv5S6o3f5Yg7XAjr3KCk1DWm5mc+z7lP0Ne0/ScAT5j7hxgKPy97pfCXyxtJd+tsdJv7TeHH3u6gMLw==,iv:iqnZQa+P+5Jyy1U0YBeq5nBzTBXMc7dXyPqcDpIM6gY=,tag:C5BnASFSsTEARSzKGPgznw==,type:comment]
    connectors.json: ENC[AES256_GCM,data:aa+1pQNOLyFsBJAxiVk7R3MenYVnvbxZJ5n/820PY5IlReyVkhtiSTWQDp14Y7LGUuP29E2JrjvXzc9lbSZBc9euypmnVwBhOMEvYcfd0in7Yf3EFmYQ488RaTpacFmbwJzzB6TjkwYdYMPsU9zYTgSM4pwujz8eLMnPv00SoJLI1oUrO+x9WCuu++MEB7rGTsZR2FAXiVo0yS2W/zQiIQx3Set8emoCSBGYfq9LR5Rlcssl7v/c1KSLvqYWxib+lXQWAIcoSEktDvJwBFhNwuguhJp9TafTrTt9KHmJSLUg2DNjdg0YDOGu5IWvUAlndM3WTSKW5wotk3habp9ekjHXqqPkNnGYuCJQYV964NpRFpyfB0frxHcsN/ykLcDM2jfrkwQzc86TM3Awnxu6S1LDFJe6RgfyWRthu9p+XZXsrC0BJsaTf5yjIO311jGSrVhxwblBnPElOHeXJGIAF31fjunGtAd+/krIqDMN4Bx2t+AUXYzsIVD55Vp75I/Omg==,iv:UixUhZiOuNzZWxSaRB6XHcNU9A2NIxXtPfvkqI2zG5Q=,tag:hWwSE7/z7T/zuCyLXbp/Yg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTTFBSnYwQnNFRUJRM2tC
            MytwMmVrOUdzZEpUT1lUWWlJUW9rQm91dXg0Ci9mSHpNZzlPbkN4ZHV6UjY5dUUx
            U1YvY3llcHZXYTlwVE9lc3VJMlRoVjgKLS0tIHdQYStEcG41ZTh4dldaQk9LZzVZ
            dFZoUWt1WXIxM3hOczJWWHAwU0doeEEK0EhjuTSDNiS5GbPefouvCJ2wFOilH0X4
            BU4gXu+dbScRAfZklWb4P0/2FkM6w/mO73ryR/kPnGYJKAXaFc2/7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T05:30:18Z"
    mac: ENC[AES256_GCM,data:TTX5RBVTpeZJkCBfwLjFMj8XCG2+eh79wac7DDUb233jWB3LZSSeUmy8986HYOj5GhdPnB8KYgfeXrb8h0p3yhlec5HylnaQ+PQvD3Ge7Mm1YmQDnUubg3d2PMn74+rAi0CkOOsb/M0ljPggYU+iNDh9m1cotLnIDCWTZA7fQaQ=,iv:jiasCGvyf70bYc1NivVE+mbryYj4QIF+vKemW9o/xLQ=,tag:IIilMuOWUmpogge8mEEczQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
