apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-digest-data
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
