apiVersion: v1
kind: Secret
metadata:
    name: freshrss-digest-secrets
    namespace: freshrss
type: Opaque
stringData:
    FRESHRSS_USERNAME: ENC[AES256_GCM,data:5IGWRBVYbene+g==,iv:E6+cIJZ8YPgBdvc6jXaI0E4gRz+QhmdAtcNsit5Q6Jw=,tag:uLfRerX0oMdGbPKiRFWa/A==,type:str]
    FRESHRSS_API_PASSWORD: ENC[AES256_GCM,data:069EvV3EzXdg3Q==,iv:RUv4B+Rj3HW/QazQHOSRHPOPVHLJguHFe2mIZu2uHs4=,tag:FdXWA2HD29B1bBSp+2j+mw==,type:str]
    AI_API_KEY: ENC[AES256_GCM,data:Xib+DwQ=,iv:2z/4nPKC4LS2H7MTzfxKL6OGpE1a6zJNa9ElTcnmgCE=,tag:rP41R5cTTYBl0TzcFrxWDw==,type:str]
    MATRIX_WEBHOOK_UUID: ENC[AES256_GCM,data:ffVg2tAm8/wa8wq4cfQHnQ1Cd32KWGX80xlCrnZoMM5xahpY,iv:rUmpT36BpxoWUkqU6r1r7HNmgMg+5kQ2wF9zNVnXDL0=,tag:VRfMKvQy0Se+feU8alFydw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscExsVmdDV1B3M3ZSYzhN
            SGtqNzB6MStWYlVUcnk2VXFqNWp2Y0FiVjFJCjBnVitaSE81aUFqWG1OZVFFRXVE
            ZXZMQjhrTmVEeDhNV2t2THl0SHFmQ0kKLS0tIEw4RUpjbTNGRXQzVFNwREN3UWFS
            Rk1YNmZYemJvd0RqOFZGaGFTNEtqK2MKtGSuCOjmQCP1bJYXzoKMuVi3olXNTh1m
            sNzKesW/jUu9qVgDpxJs/UJ0sYCbYtOMvRv3CdjNREDzpkRId8kq2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T05:15:13Z"
    mac: ENC[AES256_GCM,data:mg+JpBhJ4NRRl1Pu9YNRM0HgOz1uzpWgAOp/bjlFpxS8PyMhBFWny9me+JlNh/QCTrZcQHBvKImFLKB9bcs4r4yNILDxmsEJC5kyM2oFdxV+IlLPfdz3MnaPHZctSGvtpXt11hk3AeAb60FEskfOpOwENqjkbRkK2/0XeKTaL28=,iv:hoLoxj+9BBQYDjFD+sfEuPmFmHrP24kUQa3mTma7uEU=,tag:1OjSG/e7z7qqJg5i8irJow==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
