apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yeti

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - 00-namespace.yaml
  - 10-configmap-env.yaml
  - 10-configmap-frontend-nginx.yaml
  - 20-arangodb-statefulset.yaml
  - 21-redis-deployment.yaml
  - 30-deployment-api.yaml
  - 31-deployment-tasks.yaml
  - 32-deployment-frontend.yaml
  - 40-services.yaml

images:
  - name: yetiplatform/yeti
    newTag: "2.11.0"
  - name: yetiplatform/yeti-frontend
    newTag: "2.11.0"
  - name: arangodb
    newTag: "3.12.12"
  - name: redis
    newTag: "8.10-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0"
  - name: busybox
    newTag: "1.38"
