apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      nodeName: rke2-node-11  
      containers:  
        - name: uptime-kuma
          image: louislam/uptime-kuma
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: kuma-data
              mountPath: /app/data
      volumes:
        - name: kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-pvc
