apiVersion: v1
kind: ConfigMap
metadata:
  name: cinny-config
  namespace: matrix
data:
  config.json: |
    {
      "defaultHomeserver": 0,
      "homeserverList": ["matrix.white.fm", "matrix.org"],
      "allowCustomHomeservers": true,
      "hashRouter": {
        "enabled": true,
        "basename": "/"
      }
    }
