apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: znc-admin-internal
  namespace: convos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - znc.internal.white.fm
    secretName: znc-internal-white-fm-tls
  rules:
  - host: znc.internal.white.fm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: znc
            port:
              number: 6697
