apiVersion: v1
kind: Secret
metadata:
    name: yeti-secrets
type: Opaque
stringData:
    ARANGO_ROOT_PASSWORD: ENC[AES256_GCM,data:Z7UMLhHOjChITCTv+lKUuEdypLa85uAYITCSgSnyEiWQ1ebCHrTFXpB1kDXpytJGMXgftplh0yzCITfJr+o/Rg==,iv:6JCCTFCzpVvWzrXKM1iyDRTlOlC0TpK4Sx+iPsba40I=,tag:QS5PEoCoqMYTSKn+OtHEew==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:9MFYtCuR8x1O37+FLRjClm1eSQQfh32CFRBStYIYi6KFBHfKY/E2mi6xEYBAs5l9kp7OQ0pY86JkuJ8g6mT9cg==,iv:WYaFNFv7TtTbFfiPc8Z6NTHGGjowl9e5+XZHTogPKpA=,tag:42TCeD2Qe1jD7k1Wml2+oQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzblh4M2Fnb3lvQ01pSG5C
            VWRPMmdtQWtPbmxubkxmZzlZeHI0MDNLeGxZCmx3VnRQeEpNRG1mYjFNMTVLRys1
            dE1WQ2pra1BEdTFOdHk1cldFZzZ1NWsKLS0tIHlQR1NaSWpKQjRuRWIrdkdZa1Ay
            NVI3dEV4dGhFMzl3NnlLdys0QXYwVHMKencEsyUNqtmQPKMV2yyknuOskMuxH/DT
            ZL3cre6ftGHhGkbrHyCId0eKWCL6g+xCIOQFvfrPSF8WwFrAAxrGPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T05:52:39Z"
    mac: ENC[AES256_GCM,data:yjUT6fj1U8PM0rJawcLbzqTAmR2Epss5LaoIXZ9LcY4KUNB3eItrsVGI/u+6+y+pCyGzG83nhXcLUPpS01hkglrMDaI/xFi5wrwuIznxYbE41rRqamXwdvjjaDikUehaJriIBVDfBW/pqhhcgu79HRjDFY17gOSg56Sivmm9w4E=,iv:ktJFeCdHeQoaF9zAykJXeb8Dg4/2T1iORkSVOwfhEu0=,tag:yH+6YQmPHswASrLQoflhbg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
