apiVersion: v1
kind: Service
metadata:
  name: cyberchef
spec:
  selector:
    app: cyberchef
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # cyberchef 11.x nginx serves on 8080
  type: ClusterIP