apiVersion: v1
kind: Secret
metadata:
    name: op-connect
    namespace: 1password
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:CCpyM5sHgkjGkDF6VGUVTkMzZJ2+t7TCu69b4uY=,iv:Km95agvw7C6v7G3/ScUs4NECDyR1k+TtA06nknKJn0w=,tag:OClMHoY/BLmbL90RI+ZZoQ==,type:str]
    token: ENC[AES256_GCM,data:x9TNEUumIbtFpl9Dmday44/M16pXhNsaXuw=,iv:oVvhEjfSJuDOj1LlgdtMOymgkKTja6YZOcJ5opdEG8k=,tag:FWloirWkS7EmpMZA8ouFig==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bVRzeHVTcjJ2UmZRL1ha
            cWZuY3pia2wrdXlENUxWQkxKQ0kzVDBZMUc0ClpBZExZdEFlWUE1ZUpPcTdScjhU
            R1lIYlpFc2laTVNCWGZaMWtWbjFNWFEKLS0tIHptMkorZFIwc3pqU0NON0hONS9n
            bDRsS0IzLy9kRjdRYTZwYnZKenZ1OXMKzFVfmGnR16YPECwpT1NFFRv4YVlwq21F
            tgzRJ8Kjl6Q+XC3QYI8tM+levhlSrR6yz7usXxgxyvpYei5nUjvlkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T03:06:38Z"
    mac: ENC[AES256_GCM,data:3qCmtlVLZ2WbNxPbSajLZY2yrt4FgGY6x8vCZiRX+HT/lyZAB86djYeOVDxnO6wTY+rWNK/8VBOYZgRA5XB1+egevveseCyuONqbnD0wHmNewHNEMNy5cfcgW1qgCLsBAcSAibakUTPhZg6AwBjJ2zyowfwXeVjEP8/Kqt7IJtI=,iv:hukpOvvVUXLjy8MxpJ8LKklGeoECkmRmo7BpfttZJEk=,tag:CLyhkwxLicW+6cjJwJZ/+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
