apiVersion: v1
kind: Endpoints
metadata:
    name: fbot
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 5803
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSV1VBL0JMYjBualRrQXFr
            T2laKzBYbS9hbUtzM3BTenBWRFpIc29qT3dZClYwSkF5VXNUMG5jK2ZyTUtydVNj
            ZFdmekJ1dkpaZzYxY2ptR3lkT050ZUkKLS0tIFVGMzFJekdPeXhMVkRjNi9JMnNH
            Ykxicm8yei94bDcyR2Vpc0Q0amw0RncKR+BEMKPWdbpMjcCJ6ZiW7lJ8RB2Mdthw
            AR1uA03uVxSHSb8lrJn4CwPbwxjkF+TJMzdTBTV5mNE3wdxNVMXrPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:h1vX5KKRVnlfrKIWpnt3lj8cS31oTUN8czKawHfzET5aAkPYC9Fz+d/sJG1Js2pkTGNtiBhIy85VgD6EQkAHjP68vPezpCZCzAj+KOy4SMwsglr9VzDyDNC6Z9ZlPxEu97N2dov/fmJQXmUzI8uMv5Q9EnLmLuJXcGjyQID39j0=,iv:kSWLjMZNhqI8UXW7jRo/WVB1kDS4FGfGUVBfRbuW3TQ=,tag:8EvfCNqVjUfg4XF8AL8bBA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
