apiVersion: v1
kind: Endpoints
metadata:
    name: hbridge
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.7.5
      ports:
        - name: http
          port: 8581
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUXdRK2VKczRTS3ptYlQ2
            TXRwUXJQSm8rNDRQRGhqT1Y1ZjNuZWFxRURZCnkrbFhHZ1BjbDhEVll5RFJiYTln
            aVdoeVpZakxsZ2s3Z252WXFtNXFiakkKLS0tIDBvN1ZNaVZoMnBqU0VqVndHeVA5
            NWlNM2ZzYUJXWkNNSlRuam9LZUYxWmcKommHQMbne0F48mPgaMbQN8c+01M9IFUs
            owQ/m4QCoPbUjiwcxvmvazPN0skwNvp0S1pwRtjTMGmodM1kvYXdJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:23Z"
    mac: ENC[AES256_GCM,data:scZa8XPng6ctHo2sYNv1z1kyTfcsFEGYDjxHP/GGkPU/fZIDSNy236HT6Zyx/cb5kpBqq34M4ip4RhyqIMrC4pZUBw8nCzdPkt9LQp3DII/MErT3Qc6KA07q+u22UvL1FXwJz9qPj5kqHjgwPIgqjk+8Zx7O4M1+Hg2l8f20L04=,iv:07HLOn/zHUsEhdJQENegwWVcBIHZHmidzM2p7nSAsxI=,tag:Sbq11YRDCL+z8IdR0FKuZQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
