apiVersion: v1
kind: Endpoints
metadata:
    name: plex
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 32400
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWGd3N0tRZEpuVHFzWXhu
            UCtUcWx5NXpTaERnSVF1WHNYRVNZTVpLUUVjCktkUTJnQjlReHVNcHpoVExtUFda
            S2J5NUtqNVd0dEMrd09Xb2kvRENZc3MKLS0tIExJTXJ3N0pURzdidmJaZzVZWUZt
            UCthamF3cTh0S1JiQzZPblg5blZucFkKDdQbYB7GKVs05nPBxpO2r18qPHCI1WQW
            6OKk0+yBBfzGFoSD9jgFpRRKiTfnVacRhi9Igpko4nvM0EQFX0t+rA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:00:25Z"
    mac: ENC[AES256_GCM,data:UwXB0LaudjJGO1WYGkQJOW/eizs68s2CgAOjdxNZFrI+V1RbnAcHPSmBMac5UoM2LqXbjGU4jAUJieGzZYnqNEO3HK022sph5PJ3DsNcHKCxYSGcvN3FXSoU5Is9+QzG3MqzYz14aHdJBsOpxgzWXBgFbCCWjQ4aATwgRVeGViw=,iv:moQFIW1PuxETbRiSiJDVBYMZnzLrSQA0nQnzfiJkRYA=,tag:94VJQrvMEAUJ6HEncbChBw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
