apiVersion: v1
kind: Endpoints
metadata:
    name: qbit
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 8080
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXalc5OVd1ZFdTVk1PeDNn
            eXFHRUMwa2VheWxKM1BnQ3VncFpCSmhvQms4CjlRcmIrRDN1RXoveFlRaklVL1lz
            SS9vb1JQWUF3TWNHNkhYQ1JEREJGdFkKLS0tIDF2bVB6TzVES3V1dUlpQng5WCty
            ZkR1TGxDS1ExenFIem1FR09tb1orTWcKfDvyAVqA6sVOzXxBBpSRmv5zaNZ04Dsu
            mTQoR3hMfIXD0u3Oiy+64MwpnYjNeNRClArSm79lWPB3FuYww54HiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:udwYU2utP7w+gLU3y4EhFdZPQi8+84nogEdenfObaJYIKR92cR1bRa5chnT/S0v8Fw8s6A3E//IQTkpycXGkK21DeV5/2JTpF+n7kfymJJmwlEWHw+2gTX1QXTpA6rwXwyIOM6lvEs/7DxXnjwplKNwTuEtE0dZxVyMZPBtwKvI=,iv:BZ/fVRWl1gdhLrf2BHvBPMSr6tizLRHlDhhJQy12oaM=,tag:QEtwgNUyF9f6UB930Wy1Wg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
