apiVersion: v1
kind: Endpoints
metadata:
    name: son
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 8989
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcjBEVDd0VlVJa0xhWHBm
            NGJkUlkwVTNNVm9jakROS1MrWEhndFVZN0Z3CjQzRFhIazhRTTBIc21ZZzVMK24r
            OGdvMnpYT3ZrOTBubFZZTXZ3a2hvYUEKLS0tIE5YVnVCOG1WbE5jbVQvVWJMVENs
            eVllMEZja3QvU3FtZFFrQ1FPalE1SDgKIOBsbk8x0dGBVks3E9daEKVbj/+Dh0Zc
            zmGdZpi5/Gt6dleyjkdmmtS+YjEPxtDvxuMvWauTOpda1DACWDd3vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:rWCs+nii0knEbFFvzazyd7yXipOfdhALGS+IBM96/YCro61KaYXwCFCst88jnZhdzy5cbW5mT5BTA3ASOu/CCbEak+gnq6ydtuWQ5WNjfhJzc3DiC6CDTr4NkWFrF6AVaeIPnvjCudHaI+nkSOEJc5PjYS59kpLR9TpmA0kMric=,iv:+oVQKxf24KqxTvrMHbYHMo7RmvN6Yst1Om6/OJg3fqI=,tag:6ndYTGCOOAfxlKUG2geQKg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
