apiVersion: ENC[AES256_GCM,data:k/+InBXk4JNala6eY4AaIZDgUCo=,iv:Khcpe8SPTnQDa4zTAptM3czw6g9NWpJGRRvo7CUyZYI=,tag:mZefd0S2JskjLEV/CaOd/A==,type:str]
kind: ENC[AES256_GCM,data:0+SiMsXdUw==,iv:9DGscFL64TUB/yPniLlA/XEHg50/B2WV2SJ4WOnCkqc=,tag:HNP4ZZtYC5cYEXzpwe+Y4w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:spM4bZB5+YUw9/JmCFSo286OAw==,iv:9ZqpMDZocsur2cODzYtON7uVQzwF9X/9cRacJ48POnM=,tag:PvC5Inqnk8o6e4UMuHN1ng==,type:str]
    namespace: ENC[AES256_GCM,data:Devupkuk6QMtDiQEOe9aG1Y=,iv:rDnd5sLJE07GuxnDSMpUCKs6CRLLVZzbq1F9/jPr5ws=,tag:ZUqtfZOOj+hbT2QpaPPBDw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:eZz071Er+lzynJ8T43TL,iv:6KeuFoiUvwci07AuBqRtWA07nXrgMorrvvOupNkELZA=,tag:0ogLXfmFY0J9/+b0cxwpxw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:nu42ow==,iv:qfzNrmk8oI6s14jC92hB8KI4c/ptrkOZ/NGjTQ5Xmq0=,tag:bSYbwwhGB6Wy1KFfEV7k7w==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:tR4miUw=,iv:rzRPOo1umxH3T3Rsr06+rnMnHwejLecM8Yx2oZNhwcU=,tag:xemt03O2US0j+D+k79FSmA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:7e5fxtqhHQ/+HeZhcjFyY1frcnv4bgQGMKwavg==,iv:5o72NzI5ecnC6TnKdS4gFs0T3aCt/dCpN+IceK/G+Ac=,tag:5FKDxce5yE+uO9rmiqtJQA==,type:str]
          secretName: ENC[AES256_GCM,data:B14M701XMYldcpMeIgJe1KYSjTHHK3FRAkKZd/H0sAE=,iv:RsL735/DLFjXgTXOE3nQFpvHlLy/4+8uCPQqz474VfU=,tag:ICdwQB81nCgV/EAAbj+9wg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:AgGCHL/0w/iH6hIp5LdJB2NAEAST4abIeBNdaA==,iv:wmbV43HXPPQVS/xPCVsABZfYJX90+9xil6QK5P6hSEA=,tag:YBM2TkqyEIIhBLC3bhNnYg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:6w==,iv:Gpoc3kqjIYPCmoETSaoiFdckkFXen2E3VZTyfAVv/ZU=,tag:qgILlmdBBb+/OVqGASV37A==,type:str]
                  pathType: ENC[AES256_GCM,data:MibIm8ff,iv:1MoSoGny749vRHxyGajOG1IpWpYodm9eWy4x7WlUy6g=,tag:cooR59Ib+mnsjl+r5LX6CA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:U6QL66C6rmLebQ==,iv:LOMR9bN3E/fRVXnLsbfx7gHA6j5HY9x/LKT/yb5hcfA=,tag:x9aRXI3mr6ZVzO1SDI+7Bg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:O2cfXQ==,iv:xn12gaFDsdOMRKXOg0KSk1Tk9hCTAx7WpeBqsQjusGM=,tag:/mb4ZK5JpHjxFVYmNxoYeQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETno5cXR2MCtjTVEvdFJG
            SFQyYW1sYUNyL2pBWHN4Um8wTWxGMzFoWlRVCnR6QXVhMG5RZ29lLytlWjNIUXhk
            V0dYWmNDNDZ1UDN4dUJOSGRLSzNCTmsKLS0tIFdid1RZWmRXZHFtd0p2VzRib09o
            aFBIcllGT3cyWnMyQS9qNkd6aGU1WEUKeaA82Ccs6XQ4r/I/oBuLHF/HXGJBqYhj
            wnSrLXGWcr0wRn5saiiw0M2yHNw70sT0a6ak6ihz3o2+iR/OPqXhlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:Fj2/nQO7HCpifUq/u3VJqxjUSBKymhWvd3gCauUDMW2OKIJ78zTiG7nQXF4q9mns8WcczSq7wi8MuJxCWycPNa6DuTRBWjba0OCACMlkShMFkRODwdyjrgoI8hiI6VFutSCV4CG7pqjcKAFdAu2lCAOh5VNlaCw9QznetTux1Aw=,iv:FsBzwihOcGfRozwUs69Qhgd1A5GyTZXw639ipLWxLEU=,tag:GmrhaswigUvkloycJ3ZB9w==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
