apiVersion: ENC[AES256_GCM,data:dM9GL4BBJu+GLFe1XdGST8ZlQWc=,iv:E8nG8BVTEljTlPzH1eWp14DZ0pgyKqmuIGZ0nBmRLCY=,tag:WEbdcGsshbcMLjT/UWZwSg==,type:str]
kind: ENC[AES256_GCM,data:kXl8wMF9Ag==,iv:G2de23vhW+GHMlOViIufqvnkV7CqYgFsMTEqvrVYz5Y=,tag:qNGDyfNBk9MlQS/MKI4pnQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sa8vnC0CHZQ=,iv:l+5R+iWyKsf5wKf9t7WIxtfEC7wN+Ri8hFpFbCJpdCk=,tag:t/gv6HUhks8hcIXDZqnZVQ==,type:str]
    namespace: ENC[AES256_GCM,data:5k41+wZQwY+cE+pPpTdK3+s=,iv:9/R8IkGeupsyvfCrsWIPqmVzutbpg/CTuAJbC9zITh8=,tag:XZN0R0mcGcn0vLeKRsI+/A==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:6CVP45pNr2VcmtnMbKzq,iv:CXMO5JXAZvoCvokpClfCs83OrGWQSE9n49KrEO6kdc4=,tag:JyrLC9Tnh64atbRFtZ0s0g==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:HLq8AQ==,iv:0a2IusTJ9nr5D37q3mU0J0wcTfBK3SaBCES/c1u6RNM=,tag:1OP7yK2pno8Qkm32rqetwg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:JD3kQUU=,iv:Y9w4ZViQGskOEbLuWybsiTcXkszc7ZodiLAxkkFiIZA=,tag:jdfYfGCwkR+32i79PelJVw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:Rr56S6w=,iv:GRMANY6SVukVlC+B6K5nh9w/oeclXrMoxTbHejb/Wf4=,tag:mrSlyAcK1TgQVz9zqa1kLA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:j4V+4DR9h575v3t1FJ7nieafp9Edx4K+P0xgVKWgioWLOX8QIA==,iv:OOxm814CqMJ/GKVRwXTikYVMZulUQEzv+2cVW9M1hHA=,tag:iObtq/tIVV32QW/MIPpNsg==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:nTX0T/Q=,iv:ckOxdLzCUGCtEg04Bs0cdelb6poOsdKUFmU+q9DnEcM=,tag:Wk+PXEFfjNWv63Gl8gGjiA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:ejKkjTDsaMVTMlbpc0qwZM8=,iv:m5o7wYhsWdKvw99CRBRvRON+WSFcKulQZlUp6iMQkCg=,tag:59yGaYVEPbo7F+tLMZ2OYg==,type:str]
          secretName: ENC[AES256_GCM,data:YS8blbo6ytztx0UieyAcc8XP2moS,iv:H4WImznjrwXopSPlIxeq3Q3GshsnvCwxMxA5etPkIbo=,tag:UVMfCbOa5aum1ZVlJH4ZLw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:g5FNkETEWUsKzpIGJAbcrA0=,iv:k7oAVmMrA3IB25NT+XUFTIxnb4Gk5i78qkCE9g0adxg=,tag:cPI7wGoD4Zq7u+ujeMkT+A==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:nA==,iv:N6JhtfjtAAHMZp7e0+dGDggEGDH6IigpfyrjhtuSySc=,tag:FiXflj06ujLWzddJXDsJOA==,type:str]
                  pathType: ENC[AES256_GCM,data:bdwnF9fq,iv:xyhzMus7iDB3BWJbo5gxZj7/L+knFIhVkkMRKWSyPJY=,tag:F4gogyujy/Kt0D2oc6zJvA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:OLfNyitE0wid,iv:7+RJoX6UVEwVbnJo2U+NjXRESPt5OUsLyvjwQgBU2ys=,tag:kWTGV0/8itRp1urIi3Zf5w==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:/1Q3sg==,iv:+J4nAp+uTLGc0MIA4eBAi6ncL5kzneZUB4qmltkOE4U=,tag:gWsQpLQufpHexBiPeuOr6g==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVmdJcUxITVJBYTdNeWtn
            UzlENHN1TENtZkxLTWwraXhiNTNodGYvaWdBCnJ4NWY2TlNQUTZkMjQrbVRUY2di
            VW9RcmVvdGdiZTlzNlNCK2pIVTB6SEkKLS0tIDMvTmh6MnUrZGg0cE4wT216ZENH
            Vktod1BvM1hNUy9CSm1SK1RaWlhtYWsKHMVCGKSOfMD2CsecCAxQVuKOJA7lJqXZ
            7OsuxivL/PKQnw+naR92WB82bSsSCVyzpu+HNnp8eAZsQWH+fuLAyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:lzSCgBBtvsHdJ2ESKUFY1Bd/XSSG/TovXtHe4YUUMf5SH+fgNvouNvWLCbjvvWFQNGx3vIR10UCuDbSw6kCCTJ0FMGADLI1zzSGAmU1u3Ij1RwvD9Hp266Z5YGAUFtiFBwyGFdAwFVNyFqSEL29DIHKLf+etKGORrFeTWDTiAVc=,iv:5JIp4YCQwJuNW+OjEtq6GBauF8MZZJWy0hDN24+mW90=,tag:WAAIGGl1M5oiy6vQe7NAaQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
