apiVersion: ENC[AES256_GCM,data:1mA/l6lTZyjZAY/wudx1/38apCU=,iv:uJ2UdVELa4GodcRhbVaRYcoIA1lGex+Xb7K7icMqp5M=,tag:zOgn+VKNlnzxlnaODaQ3Jw==,type:str]
kind: ENC[AES256_GCM,data:xLNzXtkBAA==,iv:ceTK4INOubZ1M4IE6xPbZlPPxh4X9IssAZui+o/Q2g8=,tag:vq3E34b38mW0h1fWVZhDWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PuoecMVsAU4=,iv:pmRjgee3k0sTqWFy1bigPAWPlcb6vnOhIyUTYzUCtfY=,tag:lE/EUV8Z7ZUn2RDmYLYhpA==,type:str]
    namespace: ENC[AES256_GCM,data:oR/ZOoYhlgwLd+iP1Zmp8vI=,iv:HYNNjIQzz48GDxLS519isaesAptNcPzVmgaBdYnEYRY=,tag:hTWflznKCOWpoinjJKvHeQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:/72mOdibYUHIReC48P/s,iv:cDSv34rXbxztLOCgJtgBljHJrinyex3e1rikVOkatrw=,tag:Xuplto+Sn0uXghvpfd10gA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:UFUfAw==,iv:SS7sad9I5TzJ0e/2wk3Pnp1LKZJNC0qDp8tktibstss=,tag:y0HtrU/Q0RmleEXeuFcQFw==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:Xx1nW44=,iv:HUW6wDSJISexMbe2DHpex/jUa2TbuUQpLVQuI+VrOSA=,tag:vsG1hIMjGHoDsTgeenMLAw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:0l1vN70=,iv:dZLGkS3qV1uF+iLtPyOLSCSNrmOfEFPAx1v40lclNyQ=,tag:3gsBCn75jwyeOjvCx8jUtw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:OIqecy9rW7iHPKuowomKJF7wm7r2rg1O3P4VTcvRwffn2hFddA==,iv:hWrDTWVCaU9QdNn/T81t4EIORVxuycfVIWsPWD/IdRM=,tag:KBAOzXsO+n4mOGlcm91dDw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:E1wWWyA=,iv:PbH2fEyRRKlz8j9qpAgb/QdRPjmnxFDy3EIt+lJ6Ems=,tag:cuLRIOYF7UdNS5t5sFRqWQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:IalgAIwctju7UvbokZHnoyk=,iv:aErNIdwLHxj8zZmEWr00DicEG8vOGVqwtp3izK1DMWg=,tag:HRhYTYb3Jp3v8HV1oHZwBQ==,type:str]
          secretName: ENC[AES256_GCM,data:bCC9lATrk5m/V1hEIqGGjl/Q+ZsQ,iv:zIjGbKxCxjZkgZfMzLI3Sx7APmSH1GX5Tw7y0FojjEo=,tag:SRtxSjhQR5TRw0kxqS2Gkg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:DF0nEaa0MNLtjNE4gYlj5BU=,iv:gfE2N3itcbQroCjUWYumQwV8KjXauZYubZ+uvMOGKZg=,tag:unQiJg9Jf/3jNI0Iak1MmA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Rg==,iv:Gru0GS470BQc6nbt2VXdaGs7GcjqDsPHbcqw2itCfbk=,tag:MAeCISSlp9+/HtkFGx8WUA==,type:str]
                  pathType: ENC[AES256_GCM,data:FttFVVmO,iv:IOUyVl1ICZxZCk3SPw0/ivH4JahqWQOTqeVHta1IGaE=,tag:NwJS2FbzPIdLkqazK7bs3g==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:tavQXestzPAW,iv:fTq9WcVW2ZU5yfluqANbrmGw8NvyaVHTIYoYqHRRwHM=,tag:PwXjFWbrXs2J0OVThqU1sQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:9O7lcg==,iv:qLIFxiZuxiwxFZ8/e7L/AY7mynEw/lqgH4OkvPXqSMY=,tag:k9Hv4IDosE5kyWOTnvwljQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWxJOGVsZUgvRUdIWDRt
            cnprV1BTcFZZZUUwa09vWm9Fa2ZjSlFMMnlJCjdYM2YraGpwckVoeHRPT0ZhaWh5
            M0tUaVJwbTl4UFJLTUdsQ0RiMWx3QUEKLS0tIElONzhabkZxd2t5RDBSR3BwRzJl
            RzA5Nm95NzFxT2hrSXJUUjlINUJUV1EKKgOYWzmipcZrfQ8zT9oBlt4hDNpnMZ+3
            4mydJ+LVdZlmRZD7Nh1zf5Lkb3EysvlP2s+YkOACBVGFZ7W2CrYuTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:ceXq7EJmXN3oeQ2taIIg4x3i+O/8SHTBO3x5nnEB+P96z/oShAL2QEhxVpT7JpiVgB4HlvrefN+D+N8Mkjt+/bibMd8BXoHJ4bCOkvh8nKV2NXc2dgakweiLeh+Zyk2LB6kYGrLfjMOyfJHNlO1DQe+WLAAZ1qjZ4JBmsHLyX9Q=,iv:fPBE0yi7rKqCtE8vFaz70UrkmLUrjD4Lh96ObfvsmtA=,tag:A4WYMmrt/EvUMdJWk6mT7w==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
