apiVersion: ENC[AES256_GCM,data:+saOZc2eHXJyvJewM7uVa79Eqv8=,iv:K7BW8fS88mfnIJbaKqFggUR2PkTz5nWOd71P8mv+/Bg=,tag:rTyfgobgrfZVEJRjHGHpig==,type:str]
kind: ENC[AES256_GCM,data:EqUbmLPHQA==,iv:ksqd3GkSE/uWQat8xO1fRqnN8aF072VPAIsJvQUAsWI=,tag:YWTyFbJdRCy2MaYySmDeWw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Cg+YF88e7utN9CVTow==,iv:EkrJT5WSnfFQm9D9EiAu4Iv7GWcpVNN2VrYQ1ABJxP0=,tag:fX5nSlvXxVTVRw/N+5wbsg==,type:str]
    namespace: ENC[AES256_GCM,data:qcLGfrVQwcTp3Dg+rrMzQbg=,iv:0senjCRDanakYGmzS1TncdITriMT6FFnphUQuisvxmY=,tag:IYN4ELwCNHT/Tdx9/CFQVg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:VY3VqWFEHf7LqLu2tQu3,iv:Z//zpz/c0/ODUumXenfFRbY7TSART3EaH/wXB6BKayc=,tag:nUeYfqlFWErXqEveUAOG6Q==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:ttHAZQ==,iv:hQMDDZnNLy0hwRSIN5cydpA9W3vY2ZLxNpFeGWVV20w=,tag:5qPWmLZkjYzCormTd/g6ig==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:DSTIuKs=,iv:cksO8EE1w/hxNa4/yjJhrWSEIKn6lqueIPQNvjLUong=,tag:kbsfH61wSn8TROCcBrA15A==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:ocNHAakNxosFfCDarbSJxnCjREK/CZWXZw==,iv:A1tjr54QHHFiuEHwuNgLCw2rsULbN5RJO6XnO5Sugz4=,tag:Xd1yZdCg1K9jqWwHeFrMdQ==,type:str]
          secretName: ENC[AES256_GCM,data:+0t8CBfYqDHbw5O9+PvSdPLB4JOidhR01aYMEsE=,iv:01z2r2wHcpQKmZMyovxB2+5VuwzpqZLOaBVWJs1lJlc=,tag:NDCbU3S/2V+qZ7hzoRuIHw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:1IiekUUu3+MatTIpPpOi/RDkS5z/pCq2uw==,iv:ke3Rc7Kb7SQRkzZBgcB42dG57FfkwSe+4HnATI2MlKM=,tag:0iEIJQAVIQNEQJ6Z65FG2w==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Ww==,iv:vOWG8Z3I2Klk4CkedX0EkL6Cpw0uczPx5yz8b7OsXnU=,tag:prWDP7ez3bdasDnHoKkRww==,type:str]
                  pathType: ENC[AES256_GCM,data:sOUhk+1X,iv:VB6p54FtCo2pbRXqkQHZ3C/iKskk/yBVhavE0uvxeRA=,tag:UoRD3fzDqMFbgUCMtqcd/w==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:OSKuBQ==,iv:ePvAxvM7X1t+I0nyRb7tZWi5sOs0WZdEkmwdwYmuXvM=,tag:7DfnPpxD1d8ChMIeyy5WfA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:DuEQow==,iv:kJlZhqYI8UsFnKgp4u0QILWK5DZH05uCOl4Bt3phyIg=,tag:CMtR5WYi6bpl+GWPU7nTlQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiazh3S09kUVRVRGJYVjYy
            ZFNTV2xwWXdOemhjQmkvQXZNRmxtYk8zZmg4CnQ1cGo5V1NheHBSUFZZYitveldN
            WUYrMThuby8wVmxjWVV2WTlLMEhjMHcKLS0tIEJGSEw2VW1MRUQ1MlNDUWJhU2Vq
            NW5qK1RFSmo1WGRtRm16NEpacVd2UzQKt4MMW/gK8m/UmgQeUdqkVB5V5jMiLLRH
            b6oyWynaTDTXdnNwe8YNazONl9Br1D1ppcfa0/L0wOVgye//fEv7Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:0PtbbJpyMLgxskaNRjhW57mvwV4vUUSRCVuQCF9nfIf7+8MLN6rHwJO48enMBgyxUN2OV53ILc2cfUXMlsJ67H4P3Q1Ak33O7NplHwMsA0l0FDJvjfSVCW01ewdUTzngzY+4/0oMabgk7faTtyRgJNs2RkhpJkbog4uiEk7mfPk=,iv:Twj3b67Dt1gp9s9/GazotzxBepneBmBoPhplxiAxxRQ=,tag:t2p5jAEdYCIlHmmRbo2I6w==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
