apiVersion: ENC[AES256_GCM,data:DNVDA0I0sQM0mFm+ZgrHgW50Pl0=,iv:3GzYs3tkaNKU5+u1h/5BqdcFX3m8rIksNd3f2B3C4NI=,tag:RrsCmCqckXcsSQRv2t2G6Q==,type:str]
kind: ENC[AES256_GCM,data:A2fBTCrOAQ==,iv:cSYRyZZ8MnZ/bIgMpgLCydV5zZuS9ZJORAvCUQdWqLk=,tag:a84rjpwLayOC2v6VLy5fUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:btYANqMDUNhv3r5BdA==,iv:8/a4icQo+Hb6JuvSEuSVdO5OyvnTsgNtOhqK+Osd2Og=,tag:eXuZsmq5ceTkvhO+k9i6dg==,type:str]
    namespace: ENC[AES256_GCM,data:Wsb8sY8tnbFNDNCpQsYK+x4=,iv:xSKCWRrMRInbsaKlrCBhrNNGJl5XrUtdbAJgPblCMgA=,tag:80VSp2qrwfJdD283iblIFQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:P8w5wdjsrhyUWUw68bQB,iv:w28DHozgWY7l3C5QmJG+j6fFQA45hJPEAJ4NHAg6/5g=,tag:k2AG4yTSbpIz0ScemewR5A==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:KJVeOQ==,iv:36AF2Pp2DuAYilJHoatf89EkECOuXuf5yGuvIu3VMp8=,tag:Tkgo3nK/HYRZsCSz74zbVQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:yt46ZbM=,iv:DAWMlMlBa8PwFSgM7JlSda3JtocZpcqHHJLQW1mrHgc=,tag:g81xYW2W4lk3mcglm35UIQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:1GArOXBI56ZkuTedDTkJ3z6I+fjNwQ==,iv:j7tM/njD11wUI2k3sohq37iljQDnG9oFl2ORC8avCgQ=,tag:ZJckn3mVWfn3ySR+COHV3w==,type:str]
          secretName: ENC[AES256_GCM,data:MmOah3/IKLnUX6qBjKiaZBVlQhxsqhkw60U=,iv:KI6mPjbRcsZVQCGuhpfFQJlj2+qa3W5LM8HGp23soKk=,tag:baphPyQjWYGak2peHRXsIQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:LVFN1z0IcvfpxhkBhDt7unyifQWk8g==,iv:Hsmj9OCRjMsmHp1YT1aU8Ih8w0JkoVjNZ1COMB0zH5Q=,tag:ayXHFt8elWjug/hXaGtftA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:JA==,iv:i0wzUWkvW/MpeXoDdRnhN/Tt0tfCTf8w1xJ+xt7DbKI=,tag:HTUoZ/vLCee6FapAdfQQXg==,type:str]
                  pathType: ENC[AES256_GCM,data:vxbRGXvN,iv:q7ygSt85K8HXfsyoMr0fs2oRwphcNfFR8fLDfUQpd+c=,tag:FexNgftoLFGzk5UUjaC0bA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:pDNJYjP3JCjYNJM=,iv:E2hZixab8TunW6leOnqK2AdAEgBZNYMMJw2U6Z30eCg=,tag:3GILw/syrMHB5SlGTHDX3Q==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:c+hiJg==,iv:wK0rV5TGr52o/EUM2889vtuhkVJNdo/7dpMR2ejEsRQ=,tag:1ORtQOPvFoa9lR1TPzy/cw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZTFNSmlWUWU2dFBjNWls
            SlgvbWcybHVXRGZkVFN4bEFTTTMybGhIcTNJCkMvVkxDR3pYSG5IMklPTE9HdnB5
            OWhlcDZwTnNJQi9PQXVQc0hRRWY1N3cKLS0tIDBHZVRMbEZWRHEyTDRoZ2Viaitu
            VVlwY0NSYllYbkh6Q0pXT3JxSWxlVFEKX4tUfKj8w11mWmgieO4L2AeHX2dPvK1A
            vXoHMXPwrA3CWHs5qQvCeMHcDTpaFGPft7/NwKeNmbKh7z3Zc30uJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:9OWJ1baMThayR0UukmxnXkLUb/FxVlVlQLlaISs8z1GPcIV5IU2L+iqKF+7SojPXm59JjcB22/B0WZdoNIvsXEp0xb0eqrsidzfm+qMO+z8BMrl75afbcC00ho9XpHeBJGkD5nd7Y7M0Wy5WsSWA+CkMfUHRwCpm+4d/skI9d3o=,iv:Q/RiuOWYI+NlfK0NWoW13ZPm7APKxpvqPnE66nA+tAQ=,tag:7cxDxCaMeUVMio5Ywk0Nhw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
