apiVersion: ENC[AES256_GCM,data:XUVYZPb+zg/toFfSHql8WmNmMR0=,iv:+UexgV6MJZ3FFhLN8rEMCJ68BvxFSC4rMNgGgucXmek=,tag:WWxGATk/BrcQtCF3olkq7g==,type:str]
kind: ENC[AES256_GCM,data:FuRFTTahkA==,iv:XKeTWk6C3Y++VvcM9xJmErZ4/4KJNA4aekEC+kVW+nQ=,tag:XuuKPF6vSqT7XpX/iGVhjw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NbsV6b2r8A==,iv:GqsCY8ae0CKL6WCTYQtb7Qxoj1z8NiXsovbyRBdF+kQ=,tag:jvjK22iJ1P4EogZsEe2i3w==,type:str]
    namespace: ENC[AES256_GCM,data:7JRCxyQUymMRzfcVjqfyrJw=,iv:IXBY8CQiAymq1BQsKezhOwto0Sjz3+6vjDm0hArCqYI=,tag:B2nHY7kJU60pj9q2hotqhA==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:JlqUDnPiSyhmePWtbcs9,iv:HF26QPagi3dVdFshlnpJ2AbiumyM2hDQsmH3I0uO7Jk=,tag:FH/lP/P3hevrizSR6Bnuhw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:V8OhhA==,iv:oF1yu5ZZWRrLVz+0ioASIfL7GApSsWFNqljzBcRw6JU=,tag:QTNP2uieJkoxalz5AHzt+g==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:qZogUIU=,iv:DrK+zk+IUF2efnw5XVwa9d44EPUEYf4mx9AArQp9a9Q=,tag:JHvh4mQqcGeinetD9GMERg==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:GZdOpMA=,iv:mKYAD5HSOPr3P73oj0+O6a7uh1i2sfaNzzwVOPlWNoM=,tag:Z4Yu1tf4vr4ewXlKmPYvRQ==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:VZzQtNCUb61ZN/J3KZBCuFXdTqtceQQczUCdHS+iF6Vy+cNxPw==,iv:okZ/JwgZvBv5Xeo9TJT8F5aLMH6fjTLkRmOHpOYly5g=,tag:47ILudw4i/AsIjliBzGXUw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:WMvk2UE=,iv:O0AIpZV+ILKNAix3gIZryi2nAaiW1AnE3163s00eTFg=,tag:hzXAmhnUa+jqtnFoiVt42Q==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:3AhSlFqkNlb6f9RDjBHKFQ==,iv:iqeJ0ThPldGD7CdpIGxeY9o3jGuKHo0J3JHE0pkzA34=,tag:Mlyq9WJhQ8hefr3rUH+viA==,type:str]
          secretName: ENC[AES256_GCM,data:PO4DBNvw5JXMe/dyHbR/nH+qWSo=,iv:LvM9s8ITwGjINrNqwgqfMuZUZ/OHIRkL93Pla0kYAfc=,tag:fPOR0/LwpwaEC4bASJ9LcQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:VPnEA1903f6OLtM5YmWaTw==,iv:+F4IWBN3wnjAIv395lN1oQ+KpAxs+X0xXgfJBX4ru1I=,tag:sdaFG9HH0+zeeKw0XU5uEw==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:OA==,iv:gSg2idQoyiCqbDgGFd2XH72OThtswp8Yeifb9wDSL9I=,tag:75JME/3pD3fNCj67CkrWZA==,type:str]
                  pathType: ENC[AES256_GCM,data:4qpAdixh,iv:NAh7H3LkJFJ3td5DQgaKld7evzElBAICiB8Zez+b6uA=,tag:ArEhbOG7JvIe00VLykEdvQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:VdIxpqUnYBLJ,iv:XTo/YSETHd4Ws1cmAC0bFacAiXUVHpoPRkLVW2GpYt4=,tag:r70Lmp9dX0KiQShou2HqBA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:BXBqdQ==,iv:ZbNMPA16ENj8FVvinugB4lpaP4KYxYy3CT5e7CGYbKI=,tag:InNtjhgz2bX4rCuexmtGGw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucGp1Y0xLYkZXNUE0RzRj
            V29JQlBQL1ZXOS9tNnJvTWJoVzkzSEVsTVIwCkdVSU5KdVdETG1SWjhpL1I1ZGhZ
            QUZCeGJSYnAzNGROVFkwb09Ic0JhSWMKLS0tIEsrTFN1T3IyM05lYUhGWEUwbm0w
            REoxVWN5VFkvczJZMVRKK1FqcUhyb00KGbZreb/sBj6JFrVZ0Yzkit4+3pFwTrsZ
            RckufSGpEPls9znspoiYRh+IVRQGZAWgFbLcdEoE2aKSMofk35rbuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:30:28Z"
    mac: ENC[AES256_GCM,data:WbJuSlpfVtkzs1tQD143y2UVyWqmmpgXjUZnN04NCQDLYI2iuiirTW8GAXdg4kGBzK8niae3DcygAMxNvJzGJ4TVSdraxFYO+ePfPD9WgEqa0SlyV3ifwPrsoFQpS//CnNhz839SnTcTMK2Dz4bvPYzxc6YpsbudSaFXP0njW/M=,iv:D1O8bJ5xciVAT8TyhWbPFwDhKLnMEDyejH6HqfhCyBk=,tag:MzMpEsSOqOePABMAWt6Ueg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
