apiVersion: ENC[AES256_GCM,data:CfUB30OzuDUAvvTxm1pvYOtW6GU=,iv:0pSycQJ4/PPE6nO4xfqdnkBFORdQHG/JI+5mUsBxmZ0=,tag:VpMicgQRWVvDVlzYsCIZHg==,type:str]
kind: ENC[AES256_GCM,data:mmTJlHkqhw==,iv:hhr2f34ACV5SoDrZH7dNqvCSZ0P6uvGAD1PKSI8bJ2s=,tag:jLVU+LGt202OHOMgfhloQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3Yednw==,iv:UtDXcWey1INr8yW0P7m/fDOlJE9DQ7okqxRnV83marE=,tag:UxYIiX0KUT2g4aaqyAlB0A==,type:str]
    namespace: ENC[AES256_GCM,data:r5y9l3okkZQW+3oN3xVNEvQ=,iv:NFaTHG2+bkg3hQbJSc536gHGRnUW91sqEWId8cV0f5U=,tag:nGGS6CsTwvlWTcbW0BTf8A==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:TlcWhi6ogOwBOFTWJLgC,iv:x/C51KgeAUfqwuzJ6mirNy8CAz3idI7uxwLXwWULxZA=,tag:s+9YMymsUgXUkvo58PY9Zw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:J06RHg==,iv:ir7BO1KR2wmWRLyBGMgllSY0yDQAdAJwRAn3q/f5TRQ=,tag:xdd7wfbgB1/NCNyZvXR24A==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:Drz7og4=,iv:9Fqo3Xp3MlzFSK2wZr7Tx7YkoQqTXj2KnXUdggSDhg0=,tag:1Ko/Cx9c1gjOujqNBNT+aQ==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:PStWb7Y=,iv:38BTR3CveoV+nNgG/vqOZUjXfX7Zj0r2WyMgjEJPK6s=,tag:kR7HUWlGtkF83h12AtPA1w==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:3deBOIxUelfOvMU+YBC9gt9YEAFvahpulvWBkFGg2No+KnFctw==,iv:IWtLU5uFBbQSL8NeZKPJn3XXcJGXkVjzKEu22ZI+ZtY=,tag:ldEpvzbj/1npDLGtQjr4QA==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:r9d2XEo=,iv:ANehcZ/tXJrjHwIDkQKG2cF1C/sZUnuR/tNnioH4aBU=,tag:+1mOepuO9l6VJsucATO3/w==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:KlE+pzdSu0Jw7PZIJA==,iv:k5I1PaMbsOSMKc4y/14tNzuG+7xBY/eLa/QjMt46teU=,tag:6ASMXJmwhai/hOpjyCgt5A==,type:str]
          secretName: ENC[AES256_GCM,data:HJEVjdGtMyRs8t//MkT+FGU=,iv:1wq2iF/Ij8fVsAFlaty2FG12xJ/2iFPBn3EYMjhdv/g=,tag:m+9kg8d7UOu7CIhwmhaQlg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:8AKdJQOshOLSCfSOiQ==,iv:60aLhLQJ1LvOEvF4/AUbYkVGz98gL3UWkqWW+I+Gi8w=,tag:NI29YGH6GfdHm2xHh09ldg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Fg==,iv:Am/qc0vQdRl23blwbS5k/1IeGfxP6J/7awosfCErFPA=,tag:0KmKsqDw0rLAy5zS02p70Q==,type:str]
                  pathType: ENC[AES256_GCM,data:VYSlwesd,iv:mQf0/0XQwuIOhLXPsqZ2TAhj54L7jIc9XgQrOAHOy4M=,tag:Ly2QB+v3rzE2uOclQqlsNg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:1gvcny338dax,iv:7nhUCpyJnOWzEbI0OG+cUD148exidEtbpqyKEI2DmLo=,tag:WgsPk1SSMi+4FPak8XvXAA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:auQGgw==,iv:GrVZ8dCDT2qsgb6ByGQ93dBfa019YHGd2Tvca99xQKw=,tag:hK672CjS1BdO+C3AIvDByA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByL2NZUWdJbkNkZmRNN1JN
            V2NKRHFpaTJoaUJlRXJpTlYvNEgrWTB3d0ZVCnlEL1dUTGVxUDlIbEhJaDZQeWdp
            bEF3NG5EYitMMTlwNWt2SEM4N3ZLQmsKLS0tIG9pRmJuK3I0M3VsaEZFQlNSd2cz
            V3U2L29yeWx0dVVNcVZNMlpEcy91akkKGFLvYY2filuR8XEaZHDKM6PdlrSPZxPd
            YkmsueNhg8CR1SaD0MKX75ZrJs24X3Gw92h0AkmA4ltxDqtyKLuy2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:eBx1lmzZxWRifsxMSZYPdHXX6AgIyv+IX+ap79YWwIPJr53qW/9WK9dsivFC5XGbgpEqAMNiKQtC/3Vi9Lxlsv78qj4zIDkfkBX3Ll61zV9ZXND7mN9qnmHylhK+zqdS69j2KxaEGzju1VoOfGMBTTWFcgofehY3qG8OoIj5zHE=,iv:yaF6AFMXutEzwyre8GyNyN6LE0OEx13VBomFQ9b9Vc4=,tag:p3+KLae0IyQXyeLTthdG3A==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
