apiVersion: ENC[AES256_GCM,data:GmceegBs0VXopamyoyL55qEAKfQ=,iv:D3Hd27bL26xDpuUO6hJ87sUfa20tCFgUluA/T5a+ZAg=,tag:tdJaaq1KajyQ1qGEqKF6rQ==,type:str]
kind: ENC[AES256_GCM,data:KwEU6hmaHQ==,iv:mjhEbQYRErVzuZXNVkdhtPOLiAbfRMjdo/+R/uu00Y0=,tag:0QGyUq+pzyJXcupCWTcF9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eNnj,iv:p8sXSdAC/x4eAbh2gAp/c4agV3ghPate5YjcY0LuWUA=,tag:V4mAhhxN/UCiLeIz0jRPTA==,type:str]
    namespace: ENC[AES256_GCM,data:k9JJ7LGuFQagdmn9gi9q/CA=,iv:KBKEuO7MBclEy/CZrheGT4JyXaExER2RQnmQQR3Q9VU=,tag:WIGw/kK2Z2BDLwb8KqSx+w==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:volPmYB9GZthjHwbys/x,iv:Qrc7ycAP+3o2GD1lcAUyyHISbUQu6wgZaMuh9s7QJY4=,tag:Hq+rgbn7Hlp21OzI4QBGHg==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:kdnGZQ==,iv:zowOwNhigzG1MOuk133RlECC3IudnfdUPHoNgXXTFuI=,tag:vrAwKTr7CS+UAZXkSMH4CQ==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:iC//ouc=,iv:NMa2+SpOYxwwrKUiEoEXY7Hjiw5wQGh4eW6evz3In8g=,tag:ai4rtxfXiMY3Bb12Z8KoWg==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:9yO0uO8=,iv:sjWrApAQl90Bx+iDI/Eb7MbJB9KI21aWnj9MkG3vp7A=,tag:U3tbkr3Vh9ftG64+LMgaRA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:+3iigXTCtbVz41ar6D8AAvNEnUXewdKcPr00zvaTV0JS9CfWKg==,iv:F30P7sewj39as/9X3NeWSMXzvD0GesNhRmnnPZ1tIUg=,tag:T4Sej2zp70NsVmUeH6IKZw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:dvEIMQI=,iv:lr/UbZtJe0+M+TQhykaq071sJUXKMhsulozwQ6/2Za8=,tag:dXGr024K5tOHKGwXi/VFtw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:eDWIOXQqa4c/Szs1pieO,iv:lut6s1VWWDU/DyDlG9dzco3B66erc/9B5HvoXtWn160=,tag:iKOlAruFuM53+Qw2KosUjg==,type:str]
          secretName: ENC[AES256_GCM,data:TsWzs7UTFLAF+hMJakufrhC5nQ==,iv:RlvVu30qBzTq7KLymszlz/YZZZhvM2GINzn0wNqQ3ko=,tag:clSwy5/S/kzOeZk33Kg0XA==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:7P2iNqcae9nmPL9m5JKd,iv:4xwAuaeksYQm5TVYdDg5Nl6rq6rxhSENJsjsGYXXZpw=,tag:JTdyH24n/xns3m4/hjtX/A==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:lQ==,iv:Sn4HrIl8iJr2V/4PinOSh6W63dLtG2zM94bG3xRKmnc=,tag:9un88Bo8S0etNvYm9DcMGw==,type:str]
                  pathType: ENC[AES256_GCM,data:Gu4pjanp,iv:K/zX2XzxkarNb/VSiCbPFEM3N/FlMCVBV3fgqWJojF8=,tag:sUYYMEsGLHS1a/L3T/rNTA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:moIdh6k4j7pm,iv:Wfa2jsGAdZ7n/UqgSpcrt/XeNwf+qoOMnNaH5ST+lLk=,tag:IRYMEzJMcA0uIc9ik94GLw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:m1t52w==,iv:mfbPScMRUWyxVePienryQ9XYnChT7Tpg3H+7WrNHDvU=,tag:Ixinp5v5HKK/BNXuV8GxtQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWGdKeHE5R1E0dlFrWGJt
            YXJ0Y05ZVFJVRVFONmRFcjRXN21hNTFVRVhnCldiUDFMWndsZERxTjdqN2czVnZy
            aC9HM3ZyNm9nd1FvQTdsM0VlTjNJd0kKLS0tIFB2WVptMFRyNGdzNE5rNDk0QVNj
            TGNiL1NUZUZNOXBZUVdXdzdEcFgyYmcKvKezK3iXGci8I2QxHvC/P1r3oJqBFoiv
            pU5ebA4c3Qy7H8iYpkhWOFdroC24RH3iI4q4PBq9cFWxC5xBsl20hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:21Z"
    mac: ENC[AES256_GCM,data:kPNE0hR0eUIkynOPUXzjT5EV4k7LeamOHW/U+iqc+EPpR7jPLJAYvkvMGtZkqo6SehD9SJgWvcBoEexV+YR4/Ppf87JPnnepddSIB/i5X69UIVuTyGwXxc7o5KzgKD4Ed/7vs5vNUpd0RYYg44gi/RfNercAkBq8KCVrLF8MMkA=,iv:er0RrZAczPu1PFTvv7AK4qyJ1KQo1e3PmeNgRGrHkwc=,tag:O9scEsj9L6nqfCT6QgsMLQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
