apiVersion: ENC[AES256_GCM,data:0iN0gMwjZ0XwYtsDSVUDzNYwAbg=,iv:mbDz+Mg8Cbtm/lnB+6jwWeKoleWp1/6Pp5WylyQtOxY=,tag:DSWo7OTTjytImCTZG6c7fQ==,type:str]
kind: ENC[AES256_GCM,data:gOTDKSNOpA==,iv:oO5Yw0nsttwy0YZekRoiKFt3neUmxrkzdXpTbK0yY/o=,tag:EyeSnXeGtjHysxiMustiPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5ohKAt+BIwcvPWRJiPHWQQ==,iv:V1FOJrow8tK5skfw+VzSrnCYG/05yKz/6qvH6/BcIqk=,tag:s0XJdsMrnw4NsP+3gU75xA==,type:str]
    namespace: ENC[AES256_GCM,data:hSaVBAr7E7f4/Ggcq94syRI=,iv:N8+ie8pn/u/ceeUHm63l91hYxQLBpd0bSdF3ecarLr0=,tag:+PLERtLKK5chKZblx75xsQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:YcoOsog2EIG581ThNBor,iv:JZSSGFzRO907wbH8TTcciDhYt9NQSEHW+jYcNUH6or0=,tag:+12JPhkNbXJ66zaQWg2kTg==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:AUpB3Q==,iv:nn2xVkruB+OdWh2vxKlGUC+gwTv/0A/3w+rNDu5F0m8=,tag:igf9CadXugN6Ou7IIm8LrQ==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:oBpA9L0=,iv:p0YV/nA94fBBdAK6DCEG0bdlZNrt8SkULfTgG6p+XOw=,tag:UDtA6nP27j+M4Rv/pqCDPA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:rBUwTyc=,iv:dIekJml9HSUXwSzIXWZ7004odk2jIV9vOctcwMiw0dw=,tag:sN97X7mowhuSII+dDC9NiQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:WGrouj8=,iv:4L8vyWcir1qdI2e/NTkZY4ocx5+0rrQK9po/IXFxOfQ=,tag:HpknrJeRLSZf51ro+ERebQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:gFOcKNKGB1/DkYStaQ0UnNVkkXZPEBZQqA==,iv:heBWqPbZCKQ+KmjpxCYYkUlrX55qHDmsl6WLHysKymo=,tag:TqgRZnLetQ7l5Hl7gTzJ+g==,type:str]
          secretName: ENC[AES256_GCM,data:4EFepBksy8b6B998nTxRZN7BUzwZJEkZ/XonenE=,iv:YlurQhYRhthhVcEGBUDX4by06iR17r6AruHjaOF0qvE=,tag:9aqlB79gXyrwmW13uGt4ng==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:le8jRfJvD2HGsOtNs87LRj8YgD2yfaXpXw==,iv:vzV+lhTIkcBSyrZqg0h5DkY26ql9XoVCqolLc/2Rj/M=,tag:8e7UQhA+ch1273nLgloxYA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:QQ==,iv:kkENQq+hNiU7wytm1kDnXZpNxnCDw/dRqIMkZZbeTw0=,tag:h5DcgaAe2OuGMVDS62Tzqw==,type:str]
                  pathType: ENC[AES256_GCM,data:W0cOU0sJ,iv:SW02oZ/9KduVSvCFjvvjzoizMQT7EWcqx11oomMI5G4=,tag:Yf6VBnb+Rwzwol42tnvLng==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:auohV3E5Pw==,iv:jXEM+4UC3/GY6CCIjcwspli3xNGM6BmgWqfX+LJEkAA=,tag:Hqq1rY2NUSM75NhU67Mtfw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:ng9x,iv:wYIPNNEu6MBEk+tuUvAKPtF85GJCRkdh8W8fPURZ1F8=,tag:OoMTLGfjzpawVdIAuAdElA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c0ZiTDB6SEFxRHB6c3Yw
            K3VISXZlNmYwcVBYOEFaUzBqWHQ5TUR1bGs4CnBocGw1Wjk2QkFKWUluMWFuR1gw
            eFBSclYrbVlTV0NmZ1ZqK05JR0VHWG8KLS0tIDFhUXRFOGp2OGVvMTF5c2hRYVhB
            bDlIQUtnV1NncU5kaW1QYitWWVBheVUKI0tu7FaKEWOGO6MEdX+Re6ZyRqL61RIb
            MU7qTe3Ouq3ybrSbqPhwq34RGotmggm9yOfJDgmnjfgTNZFCelbFFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:02:46Z"
    mac: ENC[AES256_GCM,data:jwkBoYoYliGmxO2MopQ9LTRUNxOeMyDVdb83dqTJ3qizWtk8BUAlRvfZjpcJzzr1MObbJ/QKayn6hu+A1KL1nUOcWpgBnlOq5QdkGFv5k+LCRXhErgdWkPWj6e1ro3Q5Y8iN5Av492WUgnSsY0smm2ZQQWPorsHQ9AjEhPd8ODA=,iv:SSo7CSGXGH+GuZjBqvQxRC9KQrjlUcmq9aPuHzrtOWw=,tag:ub7wPNUK6NGMDY0lMzlj2A==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
