apiVersion: ENC[AES256_GCM,data:b3Q00wRqeqgzxADEzibgsrXEDYQ=,iv:jNGs4OoI4f9Q1IsDfaBFrlwX+j8HiRP0i4mOnOn3J2w=,tag:tZbDW0eB/gB/3fVvRoDlzQ==,type:str]
kind: ENC[AES256_GCM,data:y6NMXkzRtA==,iv:dcB5q+0oYimQroEgQzRvHnfJTcqQjfBoNzqBT2YQvrg=,tag:NmibDo1nYZT3E9B5ULiSEQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uGqlLw==,iv:Lfm/JmSQL3RVaiDbtsoL06mQTrL5E6DNMuc5k5GfsCc=,tag:vLVSFzFx37lw8qZPqUaSyA==,type:str]
    namespace: ENC[AES256_GCM,data:XIwv7xPSRKMa54JgCmYp77c=,iv:4CpUwXqDR1GcHDd0JODlRduSPwmAXvG1M22SETs3nLM=,tag:/ekV3HW2NKBuyCJsTFwDsw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:YgefvwBmWIeHca4mDT9r,iv:53qaNId/bihZ2oqTFO3oWnwGyrHuaDFPdN3XkoPAYdI=,tag:iCJeWua1wVQyPixePNVhog==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:9nMfrQ==,iv:LM0tbKcy4tvtdHZpFz2Krd5oGB8zbw8/ZmK5ySNy6Mk=,tag:J4inTQGomY7kb0CHuo3TrA==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:srIEmOU=,iv:M6rf6TLN/t+iIV3ty9VBJKJDl/LkrjzpzVcSUz8Wy+Y=,tag:nS8fKMB53Uv2uUSSTMQ0wA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:kckyU1U=,iv:Du10GrVbVe80F14jTAVa/d1CAgu3DccBU6sysVm3QB0=,tag:Tsc4vPR/SmgIb7hiACh7SQ==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:VD3PWPUZfdGeW17XoTrRFRB9asbiUZnDWG9JKfhL0k3iHkXArg==,iv:bHqItnBuR1iPMPeSeMlrRHBwYbEPMuVLjhE6RHDXGE4=,tag:CYGHX/1qvLaxgQbQomOc8w==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:XHLOj4c=,iv:DDebrS7hfAPCXyUb1pS5SLNyOv3x+WiJOn+M3ZH4da4=,tag:47S3nJO5wskS6tDGXfzNww==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:3MeyiAB+HdcXemafpQ==,iv:8+L/+neIkvpKnDoMGn+5yi6buiicpuXIkYjl5SidSCM=,tag:kvLX/3+STv3Q3NtO7rSmPw==,type:str]
          secretName: ENC[AES256_GCM,data:gdOQERAEUEcaj+NU+FpNhzk=,iv:PGJsf3T3XD1gy5jR6ZxOYmFy3aWB2DIxHFjg7c1ZnAk=,tag:/RrH7fOcxOy+J3dMfW42bg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:Qfj9vBLuSa/QjYBuMA==,iv:1bIMB1xBLQGY6mOJmSMY7xmp3+8ESjDNSYFp5YsaQ8g=,tag:ly3LraHQGpCL0+DblJUmug==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:2g==,iv:wiNsbmY7KT1Lh5VduTZZFw31ce8t8hjy2BfLS/Cdh40=,tag:ZHYDQq5Aix59hLkK4dTeBw==,type:str]
                  pathType: ENC[AES256_GCM,data:hFD7gqF4,iv:6B2rRu4wuognOTfP1X+4C2mwqncGPQPrNnR8SuJKZuk=,tag:aiDk0AbNU7K4vjE4Lc+xZw==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:0kL6SrJNPEF0,iv:LLMvrkivd2DIMYPbPNPoHrp51hrcgXCJfkW5hHkPU0g=,tag:BZYMQRtshGk/Y0wmRIGkmQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:uIupUA==,iv:QGgLIwngED1qHNGjj6l82BxRy+2yMGfIlAtrfjQBRbY=,tag:24Mll6dY8mILOa2lSd8zGQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSFQ1UUZ6Q2pnN0xIalUv
            N2FQSXNYN1M1QlRvVWpLQzdTV1FrT01ybUFvCjUxSVpNMFRXVU9BSG5oOU9BYVRF
            QjVSK3VYT0w5TFZzTjBnUC9RcDJVYTAKLS0tIFMxbWxnRTlMSHZycEEzaThhd2NR
            Qk43YTRnazFibzRNOHBmUFBSdHcyZWsKxT+9k/+3g8G/vXSKzkMIKzfxTxfYQPPl
            AAEeK9PViqTPKkPso00FeVkfZ/oPHG4f4UhQPVvK0rjgWbj1QhQT5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:g/5D+7noTcwt7QwrXF/kfuNyyxYKeARK414couyh82dLvmF4yDX0kM7AqHymR79Vw73IHKawmlx87q41Ji6Wy+bfjGL/eBu1FSi7AQHPoMmuwM79Kidw5UrQDOLWF/0lj6pQQVXghFozYwxi9IBXos/f/I6gXcW2IXcbtrplw3s=,iv:tJPr7Uwt3YW95RYxrjL39Fg0Kcr3XqjI07R8h8Z4q4o=,tag:H1YZerEAqFIcDitkG89OIw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
