apiVersion: ENC[AES256_GCM,data:2+k7j28hMi48KWwQSzMd94yQevQ=,iv:J3C0QAjAvx4yX5CSoyG1s1vp+SwHjmLYjLM7/nNtC/Q=,tag:Q7/N8878mXH49rNiY+/HiA==,type:str]
kind: ENC[AES256_GCM,data:CuTQ/k46VQ==,iv:Bm11HnfNvHwEb2KqLG+IswawgVFVgXp+Vto7MhcXR0Y=,tag:Yl2BgAlIo8zZMx9Dy0hOSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cqFekw8uMjPcBGLpkfBt5b9GsBw=,iv:WYEj4AA/2KvZjgaiasa5KXYCvI6Zs3YezVWPVD7MuB4=,tag:kbFWZ1gZL9KIB+zI2hBTDw==,type:str]
    namespace: ENC[AES256_GCM,data:/ttyVXI+X+LBXKmjM7UFDq4=,iv:47WBQoRqVUmtqcfTn7PZ1PP9XTe+Qyjff/2qJ7A/Qu8=,tag:Wu9QBkWQW7ph9JywtKxhxw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:8knWCuMBqYEUjXgopTM9,iv:dtCHIcDdg9HeKZtnisq0GSy9beIAF43Xfba/mcpxqFQ=,tag:YiFZ0tRJxZIf5sa0jyEmnw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:bXSSvg==,iv:6FvXRVYLZQJTYGBfx08AU6r3Pwxg0kOyKDXJ/fawcCs=,tag:Y6jtC9et6OLJ4clFPrPTyw==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:1fIRJbQ=,iv:m0CffFpoMVi51LX+0sovcb84bzR6WaVVMwu5e5n0BIo=,tag:IgW/jCBhwKzGlBRxR5lhYw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:DdQPdAc=,iv:aj8z6qBgTK4UcV51ccqkiLUVfJLkvmyOURPbxQ2LME8=,tag:Kzz+smSC3ACrsjVh8nKZhQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:tm5KACs=,iv:iQwskcWims+9Jd+QsRj0luwVOey6Ir8hWxSXW2wMNG0=,tag:EQEIj52xhGsa6rGWl8+zRw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:cgmPTaCWXImdkXqp6VOHo3VTZ4Ty+blJGXO8OC4=,iv:Oe9iP7ciDhIt4eQ4ZUIE9CAiO2oULCWbPLqoZ2xt7m0=,tag:dCnPVXL3Y32ZdHahaCzLdA==,type:str]
          secretName: ENC[AES256_GCM,data:DEEYGeUFOpkfkCwiIzCVeTohecXZ/BaklX0g/vwo2hw5,iv:E7CsyQoAIy/KRDxQoi75ySS/o9puGneIRZEfqSt9z20=,tag:v5tgg9XIHqbGLVoDrlCM+g==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:KdhzNE1MST/FvLbkSN461QkTIWFhKHCQOrr55ew=,iv:qRUOReieUZx6uZBIxMUssG6lVBXdU4DkUVDJ95jaz5o=,tag:WVcVwUmpyJur3OuoLoCj+A==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:/g==,iv:wElpkE6nzjkLgt6oRXiwl9pcrA5uyHh3ki60YEC9Xsc=,tag:CnQPohZyK2ksZ56LWixCNA==,type:str]
                  pathType: ENC[AES256_GCM,data:G1p+L2GY,iv:8tkNzHu86A1Ap5RpqBZ+RP648qwLoqCmZuavFaoidkI=,tag:BLPjmhOoCNCiLrXUkWMQvg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:PjG5QXJBxeouGAQ=,iv:PDfqhCc8hwCwZyqd1m4UoYJtTTXJ5wMC1j/5tDWI0eQ=,tag:z7pYBzCBVK3WmGtsARrC5Q==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:nOSJ,iv:m/QqWwf7YAEK1nA17ERUSwgYKuR0hwku83cdx5GU9bc=,tag:Vl52+OaphwzFOcmg/Y1z1g==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aDVDbHMrbHJEV0xDdVpr
            MWc2b2NRejJXVkdOVjU4blkyalpBaEJQTGtVCitHaXo4NFduQm5GV2dySkFxWlVD
            SWxMV2NCT01ZbTkvYVN5RjV5WGNLWjAKLS0tIDRndUdUQ0g1bGNLY1pVK1pSZGVC
            Ly8rdVorb1BpVWNudVoxdUZDWUM3enMKJ8KQIygz1/pWvDO6tNUlMQ7on82jb462
            +4aR3IxelIFdIzBUnE3vDeHEY+bwU9KHrcxnih5g9Fs9wVpMG3Vkjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:02:46Z"
    mac: ENC[AES256_GCM,data:fC24+tziHDSNse55roNS8gY4lyXCy0IzSDtHihs1vOtDWauFZvrtxqJvErkD8JFEEbSxi/Ph1nB+S/iTQOPDBgoQNvEAGMyAyZ9pJ6pZy70xgGyPGzeBiJMtPJfuKKYnvxcEl9au/ymI8wYkF74BVJgyqJEeQd9VltsUySsNQQY=,iv:MEuuNC4YOaTFsc1/Pc8oNGvsCmFATUaDt57+/IEPCdg=,tag:QOJ0Qfkyt/5xp/v7aQtUIQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
