apiVersion: ENC[AES256_GCM,data:OsOOPM6sj2ozhyfmRHjqqw9zPyM=,iv:T+KrOMOh1BSSn2xLZ3tpIB5dbviSIS1N2pHDP+E/bKo=,tag:n2H4ec77k/43SOwhh/sb0g==,type:str]
kind: ENC[AES256_GCM,data:P349ixrlbA==,iv:hNb4qUiOa/s8agoYM0LGYeayzO046sza6UjbPIs5xmQ=,tag:zzKVq2rFdKJixXmA8YIKlw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QQYdXCKHwiyqQbYbULAX,iv:VRwMPKv6hQlqanBmCAbP42kyPqJ0GB875683Z/FLIVM=,tag:01DukbLVsGqg8bvlFpRBFA==,type:str]
    namespace: ENC[AES256_GCM,data:tVx+xRnAbSc6+Y7MkML/+Qg=,iv:8+X9xxWzgBSxadhOKG2Xh8hnV5+FwILL0meuYFie/kw=,tag:DJRQNyQZ4VV8dTDH/ojWug==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:WaXhC3V2cmVelHI87lvT,iv:P6t/bqVD7ZJ6qT5cDTYIoqhTtAdkpMP7yKPpV3WqVlA=,tag:MUXQ8+bOWlBwGVJiiKnQkw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:M4DOVQ==,iv:z1lumaFtcXJ4QFOWMI1zGlfthHEoBMrNotH8klQtEgk=,tag:0hN1BmXDpXqfrpZni9Ln4g==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:uAJKQtc=,iv:/WsMPpXDVuJEuEjY+FbXbEFIm/B+L3pokuDxrg9UC0Y=,tag:8FqjAxheeuChKekGtBIVQQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:PaRVxXsJUiXLxn0DiJEMxhx580EVCEbA,iv:qWuuX8FidCUwIW4zMUMmIVbTAbJn/nfi9SX18/qEc6o=,tag:D9qyPWHAyjTuHNqXtIJZfA==,type:str]
          secretName: ENC[AES256_GCM,data:xut0hPKBZVNZ0C4Gm+x4zlJxXUsmJk1UazezhA==,iv:2AK0Y42TkqpDREnlp4okat08TguBiKIkSmeZ9KjfEwM=,tag:fGC1bTDqheNzrvmZ3OVGKw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:+OhAaWx7CEmQONJFF/FfoJY+CRoj6+Ty,iv:i1tyi1+0zuD3Tjg7V64/x8B4Q2HbTrmFmE4npl3VWzM=,tag:RnmAaPZR3vw3/L4WSXQNVg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:aA==,iv:Xe8ROfCM3jcPSITlwjxR8IazP/GBCTs/uyMWQwaauMM=,tag:t4Fu8pynSySXHwOcguUa/A==,type:str]
                  pathType: ENC[AES256_GCM,data:eVgdNwex,iv:TD/ctx5rLrNGPLabVdZ/65wEZlhRd2pwh0pO7HW7bGI=,tag:6J3tJhBn94QyuWBf3MLS+w==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:J97qPDQW,iv:49vD5BoQXQqTYHVdEr9aDCpF4CVxNClQWtp2475a36U=,tag:HYnyW4ylHA+FHPT8/GVDEQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:mgf20Q==,iv:BAYc6i3sP8VT7me94XjkR7JCupOh6qS7Fl02Gpp8n+o=,tag:aRNXgUvqADeXNjxLXeMlXg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNTlDSVJMbEFSbU5NcWFV
            WGdLWTllcXdEVm1MdnB0Wjl1bHpRaE43dlZVCk9vSVJsTTd5bHora3hoKzF5NWd6
            VmJleWxNMk9tcUMwTGxqRzBkQzVKb28KLS0tIG9ES0IxcHpVZWxUMkxOd0pOQW9t
            Z0tpZGxwU3pXK28zUFZFYWdDdDloWDAKOZpr8uL1z2zKj8pO0RAb2cFWE7lVKbft
            uKSB+KtDVcXXA30ngYetvaL+UHFvYJUs7aYreA5IkSU1A5RPVcZxDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:7MBtE9I9D1OWi6Pd6rydNHO1cmxaqSuig+o1dDgqHkvpcWg+urw/T1y7S5DPe3tUX4qIxrN8bUAXE8l5qP+ytBBc7uyRNQFvrhUIwBj7Y0j21wE/QV7cwTVpqLKDx+UyU6aAMFb+jbyK2SQoaXB4AEfWaBpKdBbU4jaLpgbVsAY=,iv:WG2tkiMM24DQkyrjvSIq1B4pQkozRC71nmlfy4/FY28=,tag:2fjkRGv7MxKYmxiguzHkDA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
