apiVersion: ENC[AES256_GCM,data:0BtISMlrbF+UQDuDvU6J8gnzGes=,iv:vjgxqpmcuuiVEl8AenJ64aUF0qIlKkWR89mflQgDvHY=,tag:KQqRl7KUbkxOsUGPc+O3vw==,type:str]
kind: ENC[AES256_GCM,data:79Rpxzeh8g==,iv:EJlIb99rUP9WE2nWkojoEvXSUdU7mrJQLfQAK4Ahe6Y=,tag:1BgvXLkHSdcbscvBSt3J8g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:av/fRiJHEg==,iv:CV6ALP+L5+C/n45F1EAGpRBg9dTSOafYdlWesxn6WiA=,tag:YrXhlXNla31o1kj5s94ORw==,type:str]
    namespace: ENC[AES256_GCM,data:g/aeyuIqAAO7vZlpKsvjaSU=,iv:8//05UshnoFTZtUHdpIdG3+m98fSJGM/JSuhFd/UN90=,tag:q90yVb4jGWzGat6ZAdkZlg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:eewBHtzPUOvXn7hyh3um,iv:/qRlHiRe+1plWTPWVdZN1UTOP4JxRcBP5Ltr9F1un4c=,tag:S9M0dXujyB6+hU3qpBxRrQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:dMLvKg==,iv:x5EGLuUy+WUpdJCNXyF2QfUziFsoM/odZx/cT5lDpEw=,tag:POP0/zPhH8+MpgBK/HhBzg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:cqWCUUY=,iv:BBwBEl8i58qHmrFPwORF9H/6gkHFVbJUZEyIgVMXqSU=,tag:/ELHygX5wiBNGTL3SluUoA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:97hqRWY=,iv:7IoUt2qZyOEuBrG3O1uvgfLHIU3WOAsDj8sGWtRO0ck=,tag:iXrFCvmYs9h0giEbRKZoFw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:0vSV2C9W6bVJSbX/XmkjypDmvYcGIS7FHPqWwZJy8moxJoc0+g==,iv:WZN10I0ns3dkCmMMs1YzOUetq+XAOwzQcp3DRGTcdXQ=,tag:Jy7JfTptIK84x/sixpLuww==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:KCIRKrI=,iv:WVHwjyioFxGGDDKCZRjJ1dD0mjsXO9zHywMtfPHRPaA=,tag:Bi0z8PElgQCYMP04/E1Tbw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:tkOYrlWpfRTVWZsDn5qGmA==,iv:Ie1WZdCMd3z7vtKeCypyXeFwW1TsjY1LnNZqWFnvC3c=,tag:sOvlK0tru3fuUEozZQCnuA==,type:str]
          secretName: ENC[AES256_GCM,data:HmFFs2iFQw6HzV6kiWIhR38M28I=,iv:rZox9U09Cdlg/fNcRHG1x4MN9JdOZ8nuQ/dHgmMDnzM=,tag:Tid2SUv7CDKIEAvYLper9Q==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:IucnFM8nHT6H9W5iuVuWSQ==,iv:GJy8SmtVtsGIBmYnCn0P+Y2g0PhCpK/UwrW9R4ao8rU=,tag:ph2QUENqRdppWSg7X+2z6A==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:6A==,iv:Wp7rtprGmYSSZdC0jJn1oOBODZ2taKYygAef58adxy4=,tag:mK3xfK6C8hKDDL+YMZVZBA==,type:str]
                  pathType: ENC[AES256_GCM,data:mzeLbxbz,iv:3x5cPgSVtqE9yXVbAKYmgVIoOV3B3KvA+WpGb+WANck=,tag:yL8kkLP4mPTKah34N5JoqQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:AIwJdVEFPiTC,iv:1hdfEGiS7hdjC6jVUmhQHh2LGeN7hLz5uuhRL0YadKI=,tag:Cu+A1oalXjvQJo2/xkCS6g==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:UG81WQ==,iv:DV+ufHsWh8Bhd4tYagSmYfDHyvWPkkF0LXKppQndDMg=,tag:zrmXxv2cS0282NnhY3LaGQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV09mUHV2MXgrbHk3SUhs
            Zzl0bmdqVlNIWFA4TS8va2UyVEtnRVhDZHdBClBZZnJ6L0FvRVd4a1p4NWFUSHVi
            VVgvQ29waGg2MjVvT09yUmdUdE1SSVUKLS0tIFBCNk9uZEJ4K0RwY0xlTE84dzQ5
            SzFRRXpyYUhGQTRoZkRvZ01vRWFqOFkKkPMhpYt0ZQGHtw/bQ5zOnwjc4Rp6PQxl
            XGLQpyxyToWU20o6OA/Ep5dW0WG9/oGFoycxTCtdMqFpJRK2ja+rbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:30:28Z"
    mac: ENC[AES256_GCM,data:gWYlkrbLcY5PG9KoUkvIkHZbaa0otOTFbyNFTko2CdHPo3wrBD4po/uaxu+YdWLS40XNCPvpottZGRv2/vSYQzB+iAW7ib8XuljaMfQuhCOibJgCkc1JNQlolDeV/Ai5v8tCArH1iQDF5t3G48KFllGPn0zgYN3A19ez14je6oE=,iv:WeTskm79EUlNV7BIDQlQnd/2bDybtguIBbTb1l5GtZo=,tag:VzcqkoJ3xij1+qUt7GxK1A==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
