apiVersion: ENC[AES256_GCM,data:GpSohQd4L3WSh56NiZT4NoHEZqA=,iv:SR+i+NNNgIgSU5Y5yAuA0jj7/JtFHM7nb/Z2DFvDD2w=,tag:wQdhCnn09h7q83iwB61Rbw==,type:str]
kind: ENC[AES256_GCM,data:efYlK6jsKQ==,iv:WXQouZFK2F4dSDlF0LwINsdQhM8zswe44/nwcLrZAkA=,tag:dX06qikjv7eMWYKji1Oadg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TLOrUy0=,iv:ERRQq+wFYyUgOSKf80oH4skA5N64HjWxpK/r6lYIMYw=,tag:K8ibusr7Wi6zuoLrqTEiGg==,type:str]
    namespace: ENC[AES256_GCM,data:QA1VlZ9giBK84HjY+jgJSSM=,iv:3VdbocAm1X5flWwcS/Wm7voVlzMW8MI6/qNPLImTc2c=,tag:2P53xyaog00OMMCiSVHHIw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:UpI85T2eB97ao83rMM9x,iv:AkVGuT+8evjLrRyUAEwCLAgL3ESRb2MQ0e5SDq76ca4=,tag:hsSfWL3/WhlNBMYa/5YLHA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:51mxVw==,iv:A577hikpYGpdo5AqUIcUP85E9NaHgZqIUwX/nNSjJjY=,tag:5B+xMu/5bL8iKLCSm7cccw==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:vuQlv1I=,iv:qCEzxZJ4ZNj4TREeYrEFSbik+q+4v9Wt/3VAZGYwb0A=,tag:0YYcXvhH8cjWjxbnaomy+g==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:4ImovqM=,iv:zZG5kJWxPU35qiDASxar+rjT7c7N1sprfaOF6FyonSM=,tag:HutsMw+q4/kmUGF6W+a14w==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:EdlMKzkf3yyElBm7Y858IexAJZRwJSXplyJDkLtjZ1JX+3mJbA==,iv:ROlk1cE2VyrJWZ9+fAaiPn/3nw0aOhKPXcdgjp0p1F8=,tag:GXoaFt9oDiOXD3cFBTvi8Q==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:QslFCG0=,iv:h099lbJpP9HqPELfYsqZwHMES/C9/CphQ2jrpIBwS1M=,tag:V8An23hFo/BBdozn0iZHdA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:3YSlT1ut9N6iMekGNXPGyVg=,iv:JErMqTSvddtTFpaxbhZiVE4BMsNZoCX6eG5BtxXbN1U=,tag:Ps6EW1hS6U0zsOGanMP+2Q==,type:str]
          secretName: ENC[AES256_GCM,data:clYQZvmjr1Fydm7G+j+qZAwDffOz,iv:TaGMhjnlS8bYKTbGpnf5MlomPaTVgF2u810XxD7QDG0=,tag:p5YzkbtjSXZCbI43Fh/KJg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:UFHEN/CYOjGOA5Myw/4uCFs=,iv:nV7BBUD+hzAO9/xLOf2AmUnv4XRoV8Dbko4beENfO5U=,tag:MVX4X/PlAwgQn4H+XzKjaQ==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:wA==,iv:vH8Q5lPPTFb277y9JMfVGVM4ecWj1D7KVgq6QdhPMSc=,tag:LIGNUvFiy+jLFwnDqDemzg==,type:str]
                  pathType: ENC[AES256_GCM,data:tLRq7vHP,iv:2IDWfN5BhGnSONoFsXxBw/PabE6vWQ0BwsQbYBZTTDY=,tag:cLnRJ18nJuGO1jSm5XlPWQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:+sroK86BibYH,iv:MQekdhLJSucXGQLJtL4PnX6y2WAoksPLdltUl9gvMn4=,tag:jvYgVyO2xdEarP08DKFGZA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:MKdRsw==,iv:YESZ2HwA6vdhkIdZLiaUTMZ+j/GgA1dqU4PyV4hDlD4=,tag:PdRuECwBqgkvSvS5xHy5Dg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMXZwQUhOSVVSOTkzRExw
            WmZnWlJtcjlBRUtmbEwrZmNHcWFVOW92RUFFCmhCbjhwaklrTUxaeWttV3d6OHhk
            T0pNMDl2aThGUUVHaXJXS3hiZnFVb00KLS0tIDVZTnNyR3MzaVJaVGhWOFhVSmpO
            UGl0aVNsLzlKNEZsUkFZRkxaYWZQWEEKoBAbBh547VeCilEuIjKUuCnZ0CZgSupD
            KdtoD0eSz2rX3kW+sBu2r4QxjMXE4JK/M351FeM5nzOITwWbrAzOng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:jVl4uQN5JDp+NkVvi7uCj/vN0RDtokLukaULhPrxOTdVzNPRcE9xmO0wCLT/F8ChQAzafeUlR/hhjfvyjypdjCOQFDTrDn/lWeZdFd1U8kzARx874FLn/79uAc8nFpOpCQ2uiZODhex4saUMSxT2TCVUypqCv4OZHXgME885eMg=,iv:EbLSiIu3Gl6KH47e8UxZSEs3h7dEQi+H/qpHoTDw18M=,tag:skgpOWRrbrqcj9fC6X4ckQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
