apiVersion: ENC[AES256_GCM,data:sRrhJlEI7ho82KA0ObrTT4Tx4fg=,iv:Rtr863R0alPoDx1Ud0X+wX4qRasyLmIf2RtD6D0Bq0w=,tag:/CK5Hq2nQSqUuxTzJC6+2A==,type:str]
kind: ENC[AES256_GCM,data:c4T72+KIDA==,iv:ViG1dtT5MOVPQ1W2fQgJcKFS5u/LP2WJvMxZgK42IYg=,tag:PhqiU9Zw81N9VjayqFo+4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:acoV,iv:e96O5mUqSy4ITzMRuB9HGLWFo8kk29px6pkGj++D1h4=,tag:7l8QgVaLvgE2TrmmQ1Bm6w==,type:str]
    namespace: ENC[AES256_GCM,data:f+OrnwC03j+68nNtu0usU7U=,iv:u/egX5XLs1P+t+fzrdz7sGOyjKMnYZzqZCeAbfEFaCA=,tag:UHxOuC71qrbHXLP7UD1IPA==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:x1z5HsYD+Jj6DfifAy3R,iv:w/Mit8iE/zD5GACkExfEYAVPWwqI15A/ZoUfJCtXYlo=,tag:Dz0sbD4QcNHkL5RDDLaLMQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:hPsfdQ==,iv:MRAW5OiQOk0oIHrjwEeyhjnB2lDlsad6UgIPdz7UZAw=,tag:73GrXXQBX1gh2ONIXJsOtg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:99RQa9Y=,iv:B5jWWlNc+ZJv7JWsCBQ+guCcJ8uKfdBxv7Az3dJTRVQ=,tag:dGQv8VOFCjM5UDnU9dat9w==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:2mgeMGI=,iv:unuH4j0xmblrV+8KLJnBRd0eWqW+ozhNd7sj5FkyMHQ=,tag:7e6a6GKPI95ZH3lD/G3m/w==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:SYQRy89LTkS6SIw6M5kRX+8pLuBaSpeuEFFgKBfnIYYGZ9ASeQ==,iv:cK8DVYo8K/Gjih+e113IeWJGbwP59AXcpGaeqexLQfc=,tag:zHTZ2nSjv7JLIPR7VSfsPA==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:k/Hm7Sg=,iv:tXHyFz154QIf2fArBpZb5eVsQb7OFXk3LzczV69CSCQ=,tag:NrJaookak0y4ntmdSm7kkg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:HDSmqh3XMBfKBrVjexER,iv:mF/rplztye6Vt3CH3VSorv3szK+JKGbEH4IxofWz1Hw=,tag:tnrQwNavkxoCrXlLMm3BtQ==,type:str]
          secretName: ENC[AES256_GCM,data:49y75uM77FSrpnqHdrUP/fl2Mg==,iv:2xZpohKR5rj5s+yVCnf7ZfSbuvf8xMz6DxBCD8p7KZg=,tag:E0NSJH8558pSSPPnqQ4ycA==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:RlmoSbC7+zi0komNWkOc,iv:aT5W9PCWjAu9nH4dh5WQ5mDTZe8HRjbpNSUBZ9N66Io=,tag:se7XTJ94T/PzCenY0uoBug==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:aw==,iv:1uCmHyML8umf2LZXtBKOZD1s29QurMbVFXmb7RX9D2c=,tag:jghES3ufGUYcZDPonElcbg==,type:str]
                  pathType: ENC[AES256_GCM,data:r/+iyoIn,iv:LK4QNw1nHKS18aLygtA9y3lCK8g0HeK3fRkPbItKsIc=,tag:wwpjsCNQM4yYLUHeHxNMbA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:AbRaWTBkN3m7,iv:EiJzAid6Tju7HnYZFDcenjpFsIGOk1z72JC6CVZ2hrE=,tag:mdIkCips/PCuM/sNTqsQ2g==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:IpBNSQ==,iv:4eg+foz8gPEHGIYLLQiXzi4ss6LgGeMYYMihSvfvafU=,tag:zlda+d/5/fo8EA67l02TJg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK0Z6djlmQStGTEJxVVVC
            WFlnZXFxbXp4a202U3hVelJwd21iRXdPbkZJCklrZUluNnZ4TnRYcW5RWnRiMkIz
            ZWs3VWpkOGxFOXFCWEMveW5hb2FFTVEKLS0tIE83eEJtRmRZUXNZOGZBVnBmWVlO
            WmpjOUhhREFocU9kYlJ4RUNjUUdSSXMK6mJiJZOecmL+2i4OC6u7lZ2oaVFzanNw
            U720Y8VO8rkTD+/KYReZdeItjyRtb96h2DDACa1q/2vc0mu79pzvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:tPSn25yGY2jAVoe1XEdOC62imSSCyo16QbdaSKeK9uKN9BEgK1qTRQCph/ovE9jVpiXeCcvGabaf8iqBLkCSP2Q8WfAv1R40IXZLUJfA3ffORDdWXINnBARehh0aL2W5fvPqt1cYP9dKmIvsoCpcxjCDOnrMG0biHntlODv/pkg=,iv:FypRTYoPTh6toiXYbIysZIllwBc4MkrF+ev7LxbypBo=,tag:5oz9/jckwRpTEJgngFUtWw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
