apiVersion: ENC[AES256_GCM,data:qIImqMfmbN++HJwDugDcCQurha4=,iv:TZRg4dcvQO7uhwCSTD9GgPiRMiXes4pWYMehFGHzE6I=,tag:4AVIHePM9uyTbkvF8+2UPg==,type:str]
kind: ENC[AES256_GCM,data:4JZoWMUjdA==,iv:xYxmhUDnnJNORW+uHktUQKaW4ie1n2OgRHV0qkqG5qs=,tag:cnclarOsANB90PTzek5ufQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SS7BX76+DzZFwgYk,iv:rVZop9rsJ4O9UrvUmsShKT4b+fzTf0rS1byztpLFECI=,tag:zhdg0tlGyF3FGJN1u6sKrg==,type:str]
    namespace: ENC[AES256_GCM,data:Jh+Q/Ty5oDxKs1WXV3oxHqA=,iv:JW1sb/r9ANb/dhObHrdbdwlPYUQMm+SHj17ZWZwCHHE=,tag:OsU3AvSkgPV2BVjC//jiSw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:aVC+Nf2VJaVLHQxLS5xc,iv:IldfLcAVxvI8b6O0Gxh0i1VQjiWr8nrnCgALltr9I7o=,tag:vOKQBwHPlAxny4NmDfQgFQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:OPV9IA==,iv:+EK8P6e8BL7D48DgOOJfmSX2Ye0AiAdtp8OYvaKqIiM=,tag:IZcV04q5YAIiypy4xp0SQA==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:vy6wNdU=,iv:1W4E/68ACa4bQgi/e/yL6S1zlV5xMvV1W0P26oLGLCY=,tag:bv2cn4flaPevUShcFWF3aA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:onOFlFEdFSD2Gcq5AafKwLqCzRaCBjkR,iv:X8xBwlLAz9KJD3Cwh3fRUb8MPwCUFxxE7XxsQ64kPB8=,tag:WA1dDcGeLPETQhnzRobDsA==,type:str]
          secretName: ENC[AES256_GCM,data:ZiyixhiONiZW58PY2oEX6z6ZujB1plHghZzk+Q==,iv:ypplrVuGTKnOwhDahLFbrYQAyMS8wTmTiiDoai+HoQA=,tag:SdSVkP6cTO6OqTlZcn5l5A==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:YX6XVSqttPA48hjyF1T+fA76pE8HnKnT,iv:LQw0jARiIrc/pvvCff0zCa+A+NtPpNe4Orbu6xvPvr0=,tag:hdlByhQOHo6udv9XmbOlNg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:fg==,iv:Q1IRAf8wJeZHkaRaGYXReHpLq9H80ATqfGQ8rjAJx+8=,tag:Je8YPlGoGinYJQM/KKy8qA==,type:str]
                  pathType: ENC[AES256_GCM,data:Ugg2bSD7,iv:MwARt31QZe5uaT4+rHXCVxdDR5SlKaOcdI4ti8HnNZU=,tag:ByGZfA2Se9/y7wlerfhHew==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:szdk,iv:kXKI2m+TT1xKOyHfDAE9y1NC+UOlFDQfFKqDutScGmM=,tag:Y93nlGRcUMeCnQb24jsROQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:/iboOQ==,iv:7YgaTGGfGp68aOGlFMv9Tfl6Ck44nY2nPbt/U6BSz3A=,tag:5+uOVkJGKzbFGFFM0J/1Yg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZllWZFFzYkJVY2hVSkx5
            M3ljL2JqVmJEcjFnMmIxdjB0M0xKblo2Sm5VCmxQSUtLUnUyUTdyVVBIQi85QW1w
            a3RvR3ppRHdwNGd0dkpCd25PY0xBYmMKLS0tIDlFTlJkTURUMFNpbS9Xd2tiREU5
            RndwSkZCMFFZeDNBd1lEUXJrcVNvZjgKjUEpbIxN9lVBvfb9zUlZGcW4tF1tlxwv
            WOrlx95v5G5oJIG1hqsfVGIXeEI+FJ5socNBYN4iln7R5mQdLuiTbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:21Z"
    mac: ENC[AES256_GCM,data:k0NmwxwRNUkSOzKu13Q77O90f/NditXiyrw96jJKdcpppEH7/WBQ4Pqx1gLFo/ghYRo/YC9orDWR4Z6LzBk31V5cCNVFw2PDzZUTs8F4Ty22iQ5Ei35hZ1yhYq32GR41QHm13O9KL/6xZ9Fl7FWPZmC4J/xNpgDcudIjoxMQziE=,iv:YdTBuV2MkBlmlhm/RXTO+mgERFiNEN/HeiKa4PEiN4w=,tag:zQQzR1RORhgn5O5wLsJprA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
