apiVersion: ENC[AES256_GCM,data:vmcnilImMMO8ONBOL8MI3KHJJ+Q=,iv:vhQW2iletdszN2UWXbCni70qaSH2D4MtzOpst66ydIA=,tag:DjjqhhUhHvODItCFH9byXw==,type:str]
kind: ENC[AES256_GCM,data:vdjNIqS/mQ==,iv:NMZ5YvDPa29N0YpW4/VoXPySpppDab2tIYkb3hlfpyg=,tag:P5buUaU1xi2SpyllrMXUCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8jeWcNfckir3X/ZLAfD5nQ==,iv:8is3RzeykyHvJ3qOW1Q4xErvfaz/ZfvmfJZqJ37aqhg=,tag:ZxbrbT1qLA2iJez5xFr4vg==,type:str]
    namespace: ENC[AES256_GCM,data:UBbEWU1/3TJtN3hq6q/4bC0=,iv:5cQxIYuSLvRXAhAnsaQyYHiP0hrPem1rBoYUfZAl5xE=,tag:g2EpvOHzl/MzXZu/tQl+Sg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:3nUDP3eHvSaT+Ii22ubm,iv:Fb67nj8RowIwNGWhLZsnhAz1XmGM68nW5vYXqa6GA9c=,tag:YdJpz51A9PrR7DkRh0FsqA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:VxdanA==,iv:JsvkKKg4OPobtYnrtoODMOOl/oP9obX9JbDL6WTf1Lk=,tag:JTKWJ1it3YfTlitmDDLziw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:UDoLaqE=,iv:VAp57zfV2Z5SvaHtUq5P2CoWWCVQvsRMmmkmK8YP9jQ=,tag:fQRl2iLrzj3h303dS1wBdA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:G6QkRndMIo58SkWjPIuiUIMHxiB1ABMmNA==,iv:9blp15GlDNDIrHz8Tar/BCEpadV4XDM0iIqwDWb/kkU=,tag:W7TD5QmyZSTTNaFQO/UlBQ==,type:str]
          secretName: ENC[AES256_GCM,data:pOznwU1kenbabdyMya2wMp4R3kHGrg/Javv29bc=,iv:Dz0Q2A7Ulg+i6sUQ87VTTPQcO/MYx9arsqtmnuMVB5E=,tag:xQs/CSZdo4dumRFaCre9aQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:g6dEOCgfzUZhoaxpjam8DtwrVAJvG3u+7A==,iv:TexGvNoJ0zW7VsFyoKin2qXa2fDGiG9Oc2VTSuLPcmI=,tag:FbuzbD+Nv2BLUwlaKIX0JQ==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:rA==,iv:0QTXQFvggnCQZdcO6C7y0AlAdas0GFTC8ZgXjTryygM=,tag:xB+odc5puH84VZgK4vgGQQ==,type:str]
                  pathType: ENC[AES256_GCM,data:6oaY+BvN,iv:yOKlWOTsUCFakOgOfmgiA3rw5WiFPex1tLXDEGUblBU=,tag:clGxkAbE92D/65OgHdQY7w==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:N2NQuEsLdA==,iv:Mlb79DN2fEqxZG0pk3MxtvLSUKCQy6gwdKLvsgwH/AY=,tag:KRa1QOpPjPI6UzdCoNxwsg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:faQCCA==,iv:E6BU89hZNQz1bAjlp83afTek0fzhq8pjBRv5KtRtKkY=,tag:3tQJ4WO7wHiWiUFC7itK1g==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUa09TWVRGeXFIczdMRm5o
            WmJDS0FXUXRaZCtPN2pnOU5USHVRT2dPNVd3CmF5NU5kbEVDTTcyMjg0SVRnVDFP
            ak1iSUxKZFJsMEY4OHp0bnhNdG9UWE0KLS0tIHR1VVlQTzRkL3VodGQ2NnJzQlRy
            RjIxRUt4TDExT3pmb2F5aVJacFVXa2cKZdxFKLOod+xYKzQcKoHw29DYZ9pa8Qr4
            +gKoLzHRxk66T5PJ0XdPpLY55OtYxAXkp8FIpwMi0FEII4UchOTFqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:x3K2Bw95Yl0rSWAqec9W3Gt/G6R0KzU+Xhzb+ffAgvXLx4wjUlxqE/Ti+BOOZut12EKpFRNiZMb+ZWobPK3ndNcNETbX8VCY23rfxJhTka6qoFyXtTIMBu9wwFm/Q+reQLhcJbyd9RJwEsWyZc6M9SkfD70Gra/H/Mj8FO5xt5o=,iv:BfsWd4kjoQeQZ1bwdK+Sp8EO2Zl2ARnR5aANKgRh6Gw=,tag:8x6tCoGKfczmPYnOh/LQTA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
