apiVersion: ENC[AES256_GCM,data:NidtyEL9bhSEU//rlY1MC/iwCks=,iv:h3x/imHRj+pYHHCG3Albbz/Y5sARzHSBbZ4vRUHr5uM=,tag:ujYMDB6BJFzQPfR64IQQ8g==,type:str]
kind: ENC[AES256_GCM,data:KCveNgKkbA==,iv:iU2eZPxJTEAEZxwvy8DA00/oIVv5YrKlGk6NYOX8t+g=,tag:Uxp0Du3B7qpAykJtbEQiMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BlyI2lp9ncbrZcpnfokGyto=,iv:4da1s5ZPNEK78y34+230HHrpw24udaMvBtUq43kyrbo=,tag:nGcUYZwVk4tFELJIcveIyA==,type:str]
    namespace: ENC[AES256_GCM,data:JrFmieemwj+pgumfolsB8Mk=,iv:fVLitlzsAs8pJFRymR24SFY+hijebUO/8obg+Cmfllg=,tag:RHlBis8EEvYvevEWRDBtAA==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:PKXi1S9VNJ75vKQlFsNs,iv:KD8WDDnYOJggt59Iln/Uk/WOjIu7F12JHuE0lkzXI64=,tag:xp7wM9GQV4RPwdNdKtN29A==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:x2wy7g==,iv:zZeYZBu4eUZg7jostaZ+xO9vXwKE5wSITxwZGF8L5Z4=,tag:z/co7V2SGPiFUrsR0OlbPg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:JTY0VRA=,iv:2zcBmXVy2CbwhB4e/s3sW9Ca4+6JKP+0Ka1UWgidpug=,tag:OTiIzdLnRxeoZP8XDrnwGA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:Q+uhUGg=,iv:gx5zIso74dYoyQztP3OqPtTh+q4/fcIkuR1t86RlIoM=,tag:of2hItVM0Pq645xMdGNBYg==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:HBFK+kI=,iv:zWausVAyEqk+sJmKS4OLJjZruBC4fl1GH2+lhkQ7EVc=,tag:6G4hi9zLXtqoaGVaOB7SuA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:m5I3R3j/BH/r1ln6o5ANhRAzCOzoaVKLne4=,iv:E2zietWWU8YD0GvCbua+d172Oo53IQnW3B6YOxp/XMA=,tag:keXqZL4jEtp9wtI7U86iLA==,type:str]
          secretName: ENC[AES256_GCM,data:xjIY93v4UBu1a6BYbdw14fcxxl7iT8z59NUKf7BU,iv:Fte/J4T6T+B5GzKpP818ogruDAUNX/wK99fjd1k2wcc=,tag:bZUGk1NOoQ19JB0yb7nnzQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:yxwfrLlIJaN5O9xFhBLQWRbCWnu2sigbnmA=,iv:VnjL4bT8IU3IuisGG5ZhmIs+8bWy4Ejc2nALLozSJmQ=,tag:f5C9+BKKZC2BSCNOpDj+TA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:ew==,iv:4XtVZgPb2HFLr8WFy4P+41AVM9OtM0UKoRVWg7tumao=,tag:strPQ8CYnlU2XiDTkK43IQ==,type:str]
                  pathType: ENC[AES256_GCM,data:4pG2iaR0,iv:/Iz++rncsFpEOdfNMsCk8ZAaqKsdDpg4tAP/UTyy+IQ=,tag:y5/kKUYuIGWsXUwzFBHmnA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:yOfDvHAzPMY=,iv:y13W9AuBYgCNn/6aAku+qouwxxS/r6sXuwWpqLPaCME=,tag:FG+6kkT60IyRTWcDNFtREw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:B2i05Q==,iv:2cc1ZDi5jcB4u4P4zoC4/muMFZFxLZsMNBK0BxcgR/g=,tag:Q+oMcAzJMybYaVwWXx5U+A==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSkUrd0tEM0JHVktOM1JU
            MTFVM09sbEtjRVNrK1A1dEdzRjhRZnp1UHpzCm5SKzZ0bGh1U1lnbE54Q0svU1Rk
            YUx0a3VnM0kzTm9MaVdMNjFiM2gwZjQKLS0tIC80WjdaQllBYjQvaFR4VFVtL3VY
            TlAxNCtBWGxpQmlzS3pIeEc0TGVtclEKPCi1VnZF1HRot+OKPc0FKAxLvULPaE7z
            4MCnAPDPbogex2stslv9ew4lpLkgTE5/dwAu6pC4hhDyGKJZFt8AeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:Cl7hPWZg+ZTrojDPdWTKqdrXVv6esuqIC+cOdEay1CAtIxCAPoKQEJS5tvR7qqMTulHLuFYhQSEvmD7x+7IBxInugWTRt34AJkVGy5ydzjL9haDFaqUIINb7OuwIs6BHi8GVAPIbZoFfRO8nO6uv7v6NqP6GHyMQ7F5FZsnbBrw=,iv:279aGBr2rQJJDXP12fifEpLsjGGOphvHVIjTTZ2eaFc=,tag:YlaK2xTZe+uSFAw5FhPiFg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
