apiVersion: ENC[AES256_GCM,data:Rfs7yiNbLBe2/F3xp5losjXZNSc=,iv:ZY8x4z9l/Rboh4iX44BgDL5xjDLbdy89BtTOk86qjvQ=,tag:61HVI9pyvKOh10u2Z484gQ==,type:str]
kind: ENC[AES256_GCM,data:uuDlAsswYQ==,iv:z0oUoqhsWv+9fwV0GCmREDICGP65D5VxFcXCEDEinL8=,tag:MjeMJKzWxCRi5k09EGVc0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:shGJ5//ayXRK,iv:nq8pZJB0/GG6uUDSwayYnB1maaqbqb2NI9ZoNH7XxW4=,tag:aZUOaPXDyylIh6nfDZ9dTg==,type:str]
    namespace: ENC[AES256_GCM,data:zXoM5ZJXZHm0AzDgJ0Y0rMA=,iv:GwBndX20UUw3vX6zRWcj6Q2KHmK8OT3/rfiNUkBo7Yw=,tag:PUIl/6L2y/IDn7T/D2u2Pg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:ZUXGsngnMENZt+HphOUT,iv:YQbGNXxVJehySipO27RjgCgFajH4yYgW70z6pntTkoQ=,tag:YFeSvg+viDnXadfkzrvuPg==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:H28kjQ==,iv:0rt8HE/ek/2UhtD1qoM+NQNUHRlMEDzo181n+7OroDQ=,tag:CINnExmP/R/6273tWZXI4A==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:NUj/ZU8=,iv:Qfnm/+KPIhPsb+PppXzOWQdmBhfvDfts3+/ZbvWGqZU=,tag:RG3QIVH8ydmiVX4Nl/y6ow==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:j+A1IA4=,iv:dMGSBmRfmNkCbUKhDXCCc/1JNxJupj/NTonsxq5Sv7k=,tag:wAlVsRrOWeR+l5Xu8hCm+w==,type:str]
    nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:o51T6x3fBT7jGIlrYgexD4JWWE3vmvFVAf9zQ07KdB6uJwi5Tw==,iv:xsRIlMFEt+yooCu/z2hQeDIb2uLgkrPoV3Mi5ng5glM=,tag:D7VQGjFv0DInkRTD4dYnZQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:nLUM21I=,iv:x3c/ZjPROi80bGELzNC2LuqINiZhdJ4cGINPFqWlvfA=,tag:vqsYCUwZsiuqSACkKqA/2w==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:H8bNqJvwy+oYWc6v3PvXc6GYjzE=,iv:7fwaNVzgz00/5lPlGGNcIJSvGIQznoGq6JhdpMCufuM=,tag:VKWjQcFDAl2fWdioCGx7BA==,type:str]
          secretName: ENC[AES256_GCM,data:NfHJNbwfZrKwc/Ro1dQ7c+bZEfLnfKtr,iv:Tl4n5Pb+lRlpdVCClxx2O0S+Ey7yjtZQ6/KudyJOIss=,tag:jSiCLOrELLvIe1LhSu9Spg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:xZCw1YiKwi829gLd3eGsB/EiOUw=,iv:1GX8t6IIafOAEf9n5lIl1Ep9kd69umQ3E5DUZ+HLrIM=,tag:4IXliyFfhca9pjsBNdSNbw==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:ag==,iv:WCNOZF12hm3Q8T/KkiLzm/9QAjwFLHrkuJfG9986gUc=,tag:70ffgI2C2Sr2iG5iQDMWiw==,type:str]
                  pathType: ENC[AES256_GCM,data:W6G5ErYm,iv:Nhff2urrBHnh8/g+THg6qA63Mx93qXyLa0/1JJvEc/I=,tag:x6cjZLdfuDusV0h+8vIg8g==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:Jdp1zxhpclDx,iv:ExhF64jcM/SNwyRgDkXvSvLNaCFDHpoon9eXwrAtG2c=,tag:bvgnWdifTAAKnJ8HZUSzNg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:r38Peg==,iv:tB2VAYFpYxKcNYpzHPRaKCV0/dHWbVB3Cwj9SZS0JC4=,tag:8g3jifcaqK635Blmc5tZiQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVHhZNEhsVmRBVHlQRTB1
            SGNFU0NJb0xzN2REY1FEak1weVFnYjZTanhJCkcxSUdzRk5yR1hIZFFDRy8xRnNv
            RGpkSVpVd0huVmIraFdwTjNQQmhwUU0KLS0tIDRIN1RiNi84UklpMEZxMW9FZGhZ
            empxMGdjYXlYek9lald4ZnZKcC9UZ1kK4zCtRHNuWiz5Ofz6s1PG20uEYVozn1qK
            axBXoKQww6uevn48utYFSb5M8TuHoYdvXQuNsrN415vt1AKrInleuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:28:10Z"
    mac: ENC[AES256_GCM,data:jhAV9k6Nny+Sce2woF6mXelb/8cS9WcXNCcHEG0QjEmOWS57IlJaVnpCVDcHlUxzCSL7+epeKzf2srjGdM9F7aRbm7OBkRoShvHUll5hR58Bjfv6ELq09+T25p5CuCBd2C0djV3k63SyoSpHv/whaSlVWfjUfkJMqntlbSk81bg=,iv:pZZB3fC310wo7WcPTM08pStWhIQtl6pUMvdPx1RgH3U=,tag:i9jT9hRx8P7sn00UKbocOw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
