apiVersion: ENC[AES256_GCM,data:Sxd4SswN6mLZzQd/ZoQHG98UtWc=,iv:dzjGYsFpNsX/CZzPTLr43eVyLwIg8dEqpPfaI/yDWuA=,tag:5yVy38GspmFWDzo0/xf13w==,type:str]
kind: ENC[AES256_GCM,data:P+AZ/zY+Ew==,iv:VmGOUxDrn215F/ccmxDet357QLqjng0nMzc2ytgEazg=,tag:p1H3iuYjTiveQ0u/sEYBRA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hPeDsJBo29f6F8U=,iv:pOSEb0j6/35onYFF3RvA0LOFo26VigX2sAhhNH4l+wo=,tag:/yQEI9jQ+zWiT+d+Ksqg/Q==,type:str]
    namespace: ENC[AES256_GCM,data:G05qr5IPytt8F1tCKGDU/pE=,iv:jvyEauaGuZ6ib7bIxeF6/0CEUIggj3fQLAhO1pbR13I=,tag:tbCWsIJklCULiD77j2DXBQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:7CR63lolQz4JDvUuP1uM,iv:EDKsY1Aox51cbUgfplAi8gei7ROGw6A9YjCcp62KYuE=,tag:WYIE5nhAavd6tdp/A4vZyA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:GdUP7g==,iv:ji/3oAxGWmCKORD90o2nnZfUl6rT8PPVFFOBGA/kG1c=,tag:0G1aTOoRSrklI9IY9oxtNg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:NuIyvag=,iv:A/N90ZKA24zwHh2gP3ShRUtoXjTSFQH6UC6/mpqhfJk=,tag:PyMUERIGkq2PLW920e54hA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:xi8VIeA=,iv:Zoyb3Ky8cnjMfINmeRSJMvgZmmOOV8+ACzZDYHp8asQ=,tag:PsxqI4o7oO/cyensSnelWw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:bsqrU9I=,iv:u+RUV4OziM6+M2r8A35gSL/6u01NhzeASOt67V57xl8=,tag:OKA3xeBGStRgBDhaEOMw4w==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:ZAKNIPcmclldWuE3zEUvsZMGhK8=,iv:ucSijFXUZ4OYSMIdg416reIrVqftsSYpBiWdf4uuLLU=,tag:Hios+mOIxXb/Kh4SblovmQ==,type:str]
          secretName: ENC[AES256_GCM,data:vFHFMj32j2bRfV5DAAKBuYdomPaRHCj6,iv:U95bKgK8HHZMpw/JLZv5iQfSVSc9MmzrGU+a9M8mmfY=,tag:P1rVixaKDqmRvlI9G3z6JA==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:rY4+D/3itVl3xgnu9GBMrnofil8=,iv:A/EC2B9cvKIadS3/Tsa0lK8+bfeLtx4ZWVZvRrUt9jQ=,tag:D83DF+77ygyJhCTt+ULGsQ==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Eg==,iv:WkTs8/ID209nxNGmgqU2nnLOrm9nEBFWgKEWpl2fB9k=,tag:OXDPjFjYGmh/SZd8d3QS4w==,type:str]
                  pathType: ENC[AES256_GCM,data:KJnjNpF1,iv:45H82RF68/FC0TbIleyHM/92T55UNsUS/KH5TsVgVs0=,tag:eW+J9BKZ8EHLH0jzcxs4jQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:SOngSZyQpAAkJ10=,iv:8h4oJAIfLj4PSI/6SLEvy6fr1ZBXa8P1X3e5PAbRiiM=,tag:j+NfvQpUnun/kx4ddg9tEA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:597x,iv:KIKiF1+LDzz1TMH9r7aNygleuU4ivaK13uzPn6PXaW0=,tag:rVykt4T21pHmQN49E73P3A==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkxpelZodlUvRHhZaDFQ
            OFk2Z3BrN20xaU9TL2hnU005dFpWYWNVQ25BCkxYY29ZMU1xZVlEeHJuZjUyamF1
            VFIzZ243SGxPRXRQVmkxNVZNa0pETHcKLS0tIDQxdnpMUzdoS1YzclZsTyt0cGtO
            djZ4Rm5RT3ZuakwrSENpTnZZZWh3bGMKE7Yd0QI04hVk4gOBF9Px+o8KIxz2iSXv
            b0U3hc+gsf2aTtPlA+wCE/PrJOIOrdaa3zRBk4+ZAOR9A/l3J9HoAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:02:46Z"
    mac: ENC[AES256_GCM,data:5LtQ+yy2auFStiOqHgs4qun/QRdfXJV2cV5WVGUo54sRqNT34C0ORMLJEmgDTACy3gNVYCD4NuVxU5c4twXTGBxpgOpN5GqiDkF7BQAQDs7NsgZO2+S7lQaqJIWJ3Y/uiMGgB17Jw3TfmOcgIYAjHaxr3H93vK5SaRikRiuGZXo=,iv:BQlKt47g9BMMqWYF54Nz+V/ohzMRkqvF4kdCSzorItc=,tag:tq+2crHpz3r8Eu5N0h6AOA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
