apiVersion: ENC[AES256_GCM,data:2Ouyyf68LBK1qsAzm1E2kBD4glY=,iv:HQOZR8kCjGamKr+7N9AMbpmXIK1yRXE1M78YKjQf/Ac=,tag:r97D1dKfymhTgT907IDd/A==,type:str]
kind: ENC[AES256_GCM,data:khZpU/HyHA==,iv:kBKhBZV4xPEDJcXJs9peXaPNN3dF5r1qCJJowiUv1Ig=,tag:IzGRPLl5Cp6Cc7FqciDsWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KqLgxy19eA==,iv:nJajrJbwrggduPRK/E9zOG9VsqV8wnMskH3JYbpX5wY=,tag:ZeTR8oqkm+35T+2TLB7A7g==,type:str]
    namespace: ENC[AES256_GCM,data:D5Ut9xK4azyfHJuwQxTxPec=,iv:44vYlHV+rehepjkNXcZ4zjCNCW0bJtsH5mrzblYfk8Y=,tag:/Xnj/sG9ZtouepLwz5AsFw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:SuCGjpiHOrWc1fnD9g07,iv:aV0l30ms5bTliGYz4JSEsPb4X4AJ/9oCZ4zdcxFxFJE=,tag:T8DfNFqgsv+0odyG5vx05g==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:vSFbVA==,iv:mj8yRtJ0G11N5MnNdS0tbQXTMefNvBvUn+JgmBVB9vE=,tag:RUVNbnwRT4oO7q4LkrSmMA==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:Bw88L9s=,iv:GgTtei2rTAc4AJqXIMIu/X0cU1X1rl9i2wQZqI7hxOo=,tag:j9OMMZTjZR8xIum1aG9n4Q==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:MtRWAhU=,iv:RGqB0CyeYOCFLwrKPdaTelUkMEslR1X6rEIIAZ5pmAU=,tag:X3MPadeXZ5cV2jcO59eE6Q==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:HUuEg6TEGBLGW6SnmmuvlUjdauAFUm9sqUQkTuQXoAAMFHWjXw==,iv:3Fwaz11F3qUZj5WTCQsTRJR4X+TDoM7fCNYAqKqk1/I=,tag:bFYxpbjguozsY53frrT/fw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:9LWHOzE=,iv:aMImh2YC1Ta9mJr1tIIQZE+ZN8P0CrCg4/tvERFyuEI=,tag:VP03wO7MWUwg5VwTn6owLw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:RcOsA8AdmBo/2oAOv2OhxA==,iv:GRenJOz3GN5KJ24/5mYeN+yYKkotqQacnDhtJ8K6w8Q=,tag:a6c8PZOVUMfgknecjbs+0g==,type:str]
          secretName: ENC[AES256_GCM,data:eYBJzPkd+eSFAwdocj0IYRpeRxw=,iv:MDI9aHpOyP8M+bsEcSMkG7+wKhNz7/ua0lXPAqSXQaA=,tag:IRxJ9ddl4Dgo53cUPHkOYQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:fl1VKFnYipqYH5COF4hwLw==,iv:mFVAURX+5VGrHreZq9vLbbv5Z0COY/g7D5WhPsAeKvU=,tag:8Ba9n2A7Ak8oqdIyudB5XA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:DQ==,iv:xzdCLX0ZwzJjKkia0cuwqKAwvaCau6AaxkHGmcTqU9w=,tag:GwrfN1lwlGEJdhQcprtT3Q==,type:str]
                  pathType: ENC[AES256_GCM,data:Jk1YQ+VW,iv:lY9v23mf6jQzmhEBlOzH3T4XhHhT4c1Sb3bZ45+d1PE=,tag:xOjqmWgy6spgf0pp7nnrmQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:bg04xjHx7krs,iv:VfGOA/AYzLIKWbVFaivtNZ+j2nYzDzGvugBwrt+mPlI=,tag:/n1+6XIRgSntD8iePtzWxQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:/fDfVQ==,iv:Y2JPXsg/Kkl2cmECZzQCRj+GJ0o1QQknDQuYjei76LQ=,tag:7Orf6Ph7QQa/cNF5NeUCzg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRUoyY2Rxa3YwNEw1NEVx
            ZEx4ZjZFSkR6U2dtakZmbVVQRWhjMUdPMWpvCkUzbkswakpMd0p2UG1qaFUvUmho
            cjFvZUs1eHduTVdmTHRWMkFFamxmT00KLS0tIDBmMy9OVFU0a3prSGlldDVQakFv
            NS9hcFRMSjNNNmVkVHI1OE5hcEhLTTgKWiU0ZU1pj9IpUNAQyInJtzuaUnzzCvVx
            M7EY72KPAJdgHK6qy0otI4mVgk6SWSKvDdT/Fd03Cs3IgkAyrHXJ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:goClkP5oPgZuw2yJKjAFis9A8Z2ZyJRx3U9pOeqLHdwQX6HMD1bvPa8slOUbZ3Uj9RLFMIWppw0Fl0G42dDBBv7xEbYFD7V9fbZKy6oRzqq1+fYU6gpOf8/oee9AHRJ9Y2kKVo5QWOaWg5WwItXzVewRdNcpj+Rc1ZrApl8CkGA=,iv:dh9RSNZjEHAZVPCtSRRLSM4lsdB54yxtjcZo2KovYsc=,tag:XNLinUBMfb10p9q6XsXAAw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
