apiVersion: ENC[AES256_GCM,data:f5zXWjUQT46zlETZh7y1RO8i5FE=,iv:aalm9y9MKFi/C+dqs92vK1U2QnCPCeF9+VNnHz5gmwY=,tag:V71dM6lZ+kZQqQqJUllSrA==,type:str]
kind: ENC[AES256_GCM,data:PH4W007yMA==,iv:oh22Acu67f6andI5SfmAMgHjuZRCRZK8VlIPCPpPTKc=,tag:uk6bjT2RX5EcxHor4c9NTw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UFeyyj4TdA==,iv:Y3vXSC7aUj0hBB94wv+PZEYlY2NtcnGf532+ELsHNF4=,tag:duPKqAyliZBpOHnW8HnqSA==,type:str]
    namespace: ENC[AES256_GCM,data:ypB9zlNQ+5AgnV68WIckVRg=,iv:F0LRXb9FYIe9PSnSNtCZSuj2bNjI9vy+MGXaGRltVCM=,tag:jnnHC0NAtDPCj1c6fDwFzg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:SV4YK/XgCv/yZHvXiNQ1,iv:OEG5dPnCxET1ez2P+yR8jCaOGIHceFc4CXB39h1Dm9s=,tag:+UkrzC10url02gNV2p4AnA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:65m+HA==,iv:CJgWrZcM5vfJyVmRGUmISPzNJvZYrQK3D+qGnPvKSas=,tag:M5hBRHHU4k7iyz1VvrVhjg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:coWG6tY=,iv:RG5JCuMceXvWy4wF8Ir/jg/6ui9OWVck6A663sSxltk=,tag:d55633WzqB/DxuCQ3X9y/g==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:nDTXHXY=,iv:znHq3GS4kd5FKuQHNAMlMj4PDfY9PkX5Gk7qUhQCSOg=,tag:KKBCXGYWGg3eptcpgMuQNQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:7EwSGlA=,iv:0xZ3wKraArtB7wxZ17703TZ++DsjxMUsO9xhVTr7KQs=,tag:QHYIzCCSGuzv5X5B2FBJUg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:Ons2JCRZrBeHG9Ps+/WB8Q==,iv:56LLlmJlwoFPu+03dCPEipH0DWO2KU4n9fXEWrKVido=,tag:RokVfuNc66al9GqHzfbI6A==,type:str]
          secretName: ENC[AES256_GCM,data:1m6+7nLujNJLgJLw9783ed36D+s=,iv:FmpavStBTsMYJEqHM2PFTMScvWErtyUmGqyhIrPCdjk=,tag:c+OuIBCjAjQX2HNPbaWyGg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:tuEYUntuGiEpd4ncvaGfXg==,iv:o8eX/4va5RGqxXiXUmathz/z6tDVsVwG+GGnT/QjeGI=,tag:1IsNW56Thyj6HaKFMDqbuA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:TQ==,iv:GDhMy/Gy5fwcUSyEiTRbMbHloV4B4mj98JoZHXJcNP0=,tag:JpRZTfI6N/+hK008oYTiqA==,type:str]
                  pathType: ENC[AES256_GCM,data:KMse8t5h,iv:lxZn4vwsd34Je82ns/yBiaqy0RIm3bn8rIdJ9B6JDgM=,tag:vaF+i5h35UPV9cYnedk1tw==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:82AJ37f69A==,iv:PCJizwasSzXILDIMBguMgZrm84LAbKFJDK5qmI3r3oQ=,tag:ZQWIi0SaQ7kGGjYnIyetww==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:7Fwr,iv:V0noXFrhqSf7L1cTLcRIxw9/3TXaq6CmkHkmjz7Be/4=,tag:FTe+vc/TZhs5ob5V/nc/HA==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGFORXZVcEpJS3dBVnpp
            c2Q0N2xVbXo0Tm5jejJRdFdyRWtqNXRjbmc4CndsY1hTL0V6V1pYV2NtN1dHM1Iw
            U0xEdmhjZUJVMy9iR3RzbStWZGJYRjAKLS0tIHowQ2tncjkzQ2FiOHd3NlJ2Yk4z
            a0xHWGtCeWMwSHJYRmJTZGRkSG1PNjgKweIVw+a2YMlO5HeKUmloi4P53mW+ji23
            5IiG26VRcXWPQVoWlP9iRjaGVNtPxAthipUxlByVoqTngk4FpbeIFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:02:46Z"
    mac: ENC[AES256_GCM,data:p1w5OMfoaz//TKdHSS29BaELZfiO51Wby5bcER+X5eEGfQpwogWrow/Un7rfNh1+dJoxQ0WV02k7rRn4JzmnRMMkiA4ONagrlZ76ZLS7WI0KEqA6dH05/50REqURJM2mOTh6CEu0vk0MXNVYHI8jEtrKdPc+SWcOJmzUFVyqV4A=,iv:KuJCCm2GuIme6ZRLeIWkxBNHr6mvVFj/AyqPml1E7sI=,tag:FrQj4Cw8ePt57JxRgKfC/A==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
