apiVersion: ENC[AES256_GCM,data:n9XpJ9covtFdarVdFLBcOChZOfM=,iv:LseDD8JtUa1uoq3TVb/8Bdq+hjMyer4CE061pSFi/pE=,tag:ASrnlaUG8q2kDitxgD9XSg==,type:str]
kind: ENC[AES256_GCM,data:GrmKVrCttg==,iv:xxtRAB5RGE7c3MqALvsgL/AzkeelWlxz4YTN5IYHy+I=,tag:au8HBRkEmUT4YTU0Az3yeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:94ilpzyB,iv:JoXJ0TVU6j4700+d6N45CNkHqq8PLE0w+Dgjj3z1SVo=,tag:S8AB8TWfawtX6hUNp0xrwg==,type:str]
    namespace: ENC[AES256_GCM,data:a1C+wOwxYmZG3TovkxJIdN4=,iv:VmiAos8NNSqSeO8vxv9UKOvppns37DHpEGkB/I8j/DI=,tag:FHt9xbg/ylk3u6dn3cB9kw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:SVecdivvdZzj3fDTuVK9,iv:2tppPyESdzvdRsPT+lc/ptf9n1ED7uaf+96sAKTU9no=,tag:hPaQBmeL3QERq8F4sJB0Kg==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:pH00ug==,iv:F/Rj7mha3H/gZFZBiJE7A2bEwrn6CQWQKQmsbUqB+9E=,tag:e5bwTtwUEPv6rI3s7mV9bQ==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:va/Lgsg=,iv:3q9L6+wVUi0tFVGuAqtA0OFQ1eYuMtC1BWXBF5JAwYM=,tag:ex8POhHDAxhcNyuoYfANvw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:2c2H/44=,iv:cClQiSfXjqe+DPJnTdhgGlx+uMmJOBAdzFkblDclQ48=,tag:DBIo6o93aSb175wVltx70Q==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:c80mbw2xBFWow5FTEcgMbvIcXJUyc6i72pYfqT3A1oXbSpJBvw==,iv:BoFCFje/K3VGhCYUz3MrQJH0O3gGHLpn4xx/4W5P81Q=,tag:UOwGZvARJOFoCOG7jf9UkQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:qGeh57c=,iv:Cw0G6AOFNB9HYoEyso0ysL2ZkjftmvKRgqV4FXpLG8Q=,tag:zKayFUOJ3+WteLBAAAq0SA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:yGdNjHhphfjgGM/LzyQe,iv:h4Tn5+G/ixC2VQ4TuY4o2Z78jYDOiAQJ7fnK2vOoRR0=,tag:/DgCEHU/vtpsthsOwIvzWA==,type:str]
          secretName: ENC[AES256_GCM,data:HIBL6w1gRimE8bkFSdOP36PYWg==,iv:Witkq10MyiD2GnMvyG0VYbja1jYH0oneL9D6Q19MR1Q=,tag:YTl+Z3Fuxqe8H4XaUiBXMQ==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:7Nx/7OCgVPj+QZwxMAFs,iv:6GdTyvLV9aCJUY7HwyPnzeRfUCT/fAVpWl2pwG+g9v4=,tag:rp39xDCi6bRrXTtzQJazIA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:qA==,iv:wrkgdcCsktPhfGPdOtHI9rDcDImG0QeUxaTANtSrHVE=,tag:7P6KHvuwAwh1HDQxeCa8tg==,type:str]
                  pathType: ENC[AES256_GCM,data:5dzl9LM/,iv:Qc5/2bIMvlqn0CvGdH+8pgqBIIdKgKMexsfJkg74kiI=,tag:iS9H4DTwBesFzNtTh1ZMDg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:sm3Qo+6h6Tgr,iv:jTGBXPZyLcNGzuA30udyBg9YEW1D9eT+77VpwoF7T6Y=,tag:SEYy7BAWUrbTBIwzZy7s3g==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:nYakqw==,iv:CqX4XuSieEBJqksSGDgDZIr3BqitYh5qZtdgz0LrZQM=,tag:5mgMr8vzq2+yB+7+ePjqRQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNekoxdnM5UVNOMGJFN0hv
            REs0YzUybmtreURXdmxSN2hyazZMa1dPL1U4CkZzd0VVNTdJMnJCT282eVNZZFpR
            WWRhM1BGK1ZkQlEwNm5HckxUTjVzUlkKLS0tIHppZGxxVkJDSWtoeHpJekRVaHor
            RmNjTUgveWErNUl2bWRBK1liSUppNTAKzyzT8J+MObKXJOZjgOyfDAIJnnmvCm2C
            8V1TPDQS7Ga5UAqTJP5g3OOTOV+QqJ+RbwdH00yItWkZv0cBE7DauA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:RKet5LUatFBlepzMO1PCUZUsFH2xY3EouPQqRFBmi5cHKStl1u1lTnvf1OU5XOyxuR9E1tVS1H8znEuMuM1m7AFKOcQgk2uX1pu5kx9OONm5I45LiaI8Y1ltMqsS7kaW6wIUbrmigqc8uo//NKhY6+4yYcdT66yBO03rSIDGmSc=,iv:vPYvaJaGurMnKW5xknvvX7pNUFbMZow7vFT77C6yGvw=,tag:K0Q6ZiCKfBQhzWGYoK1BGg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
