apiVersion: ENC[AES256_GCM,data:rDcOvjseUNZDEZjPrSCuUUoYC1c=,iv:QtUYS3bQHtaVt2IUV0kRT1TdkC93fun8jWFjYq+AzXw=,tag:c/Cb9Y1jSfQ1uxgQ9rkKhg==,type:str]
kind: ENC[AES256_GCM,data:2iAFwtC9ng==,iv:oiWI3yRlFjULyIDiZFxrBBoWCNOupdukfubd1rTAm5k=,tag:28qdsDJhdIxjTdawfV0DwQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hkXi1Chw6A==,iv:tTPIfPDMKxc8+JagWv4gTIyRMgHaLm6Y8cQ1eGAAkak=,tag:Bk9Sseb5nPPgSsEw8GGKIw==,type:str]
    namespace: ENC[AES256_GCM,data:it80ztO/OTy+c78pGLmBd3U=,iv:DOEQtFKF8rGKap9fC4fWcAGmc7XPsuNc76NLMIUpNgQ=,tag:buFnMITT25BBQsQLINTdOQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:qrLLdXck3szIzhACirtT,iv:4bisIl78ZR1DjBWm0sMwe68V2pacyxfiIolVVwFYiYg=,tag:nTdP/BTVqiMxF9HlMuYwsQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:IONLoA==,iv:B09vEdvKWQLLgaDMEUUvXjw/01nB3HnlAbgfKUOve3U=,tag:rfANa76Y3lrnIdRbsRSOSw==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:G492TMM=,iv:n73N+wdM+HXmW2oFjN3ugZmmsyf79uv1tqfSYK4hnnE=,tag:odLEi718l5tufF85LHwtAg==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:H2KNig8=,iv:Mtf/2zcBrv5vQvN1vrjlJB7O9VdqTZKRFslJjOH17XA=,tag:4bmLQ0Whb1IqEESpQI/CwA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:cD0U1kKTyzbZIePkN1l+pgdbznkJ2wABCNGfytITLzhK+t3WlA==,iv:J6WhG4/cRe56un7qEr2EkZ+bsyIw1hd1mLhCygZry/w=,tag:PXli7EzL7hMCfv6NkZ3tOw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:YltIFFQ=,iv:gr2peN6hvwgM8agr1R4HwrBP3VgATikeGySXTmZPdE8=,tag:VHc/0pu1YgMp+fSut3zNZw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:5N4Vo5OEvVE2kOjwRf7bAA==,iv:QiaTQzIAUZoZBD7aHZr8bwGsLwW1x0MSvbkD67N2OwE=,tag:5CqzyJK0gpFV0RGny7fPMQ==,type:str]
          secretName: ENC[AES256_GCM,data:NY+ivQPg6dy8jst8TKRzd6QzA1o=,iv:UtzGqK5C766m7r3xwYaoYruUYwOyp6bG5NuRggE/HF0=,tag:2lE3YC7Gnxa0cvepf20rAg==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:7ublsgvQroQEtNlPvAqtiQ==,iv:9ATkYylRHltwGtuWTUZm6kSMndOYV1MJAMQQ8xBdass=,tag:9Ww6qckLCRcREt0fN9x/pA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:bQ==,iv:2AIzx2tnnaU+mf/hgKhnHbzF4GX0LETDAN2b4dLaUl4=,tag:bK2fGZg6HutaipqBb7j/kQ==,type:str]
                  pathType: ENC[AES256_GCM,data:KTm11iJw,iv:7+kzXIxPezJb9PJKhRwCsRnDZdXe8sRzyAH2yy2+N0k=,tag:8Xw6L6NyqtzUj2d5RimrfA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:6v3AWNM2wyV/,iv:1CudMq8xiwHE0vDgvvQg4NTes5SyxfB7heZ4EMnac/k=,tag:+hqQY1Bds4IxGoLoe1hqfA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:I1UDMg==,iv:rvdHBJdg9YFiSfv4z4KsPg6dgEGV3D6VRokRi0O3vRA=,tag:C4+CvrI0eDLOrT33OFYjRw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMHFxamFxdUdacWlPMWtw
            R0g4WWVQS0t3L3lIRmN3cHU2SW5WYTMyYVVnCjhydmdyZFluMEFhMWRNOHRMT1h2
            RWRUS1hWbFhTNE5LYldnTVVoRU1xOWcKLS0tIHlRYmFkZ09ZSGpEdjBaOG5rRGll
            RU1RWWVudkI0d2dTcmZzZklKeXZVOGMKP6/2HZ3fuxJ3dmzK/1rqrN0mF94GwQ3T
            Boxd9OGjRl+2vnXSvYRzy5DoD8j2O4Wj7Ayn+Xl4CPBlDafZqH7OUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:RNP7AcSPiwUj+7QsTZ0vSm+QBR1GyGbdeDfym6DEFhYE8Ezm+ISPli0Pu5n39pzdVmUZUQRCYRAjDN1QcnqaGW+KqgEHJDkEiOvR8GJBtiP+yXNS8MhFaz6zAi+D6gCCdv54a9LiyuD7OKBg8Qp8wvNbukq8uW/AhraT6VSjmZs=,iv:fT00Bpoo4/p6MEBsgmlnlu9tyz7wUYcMji5qGD2e/iM=,tag:k9S8zkitBzp0ngSQtv5tvw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
