apiVersion: ENC[AES256_GCM,data:aDNlGZJSQ1rCVLOgNXhG/CfWyO0=,iv:rEhOLIbPA65Z3N2+B4oORV4fADgWB81JB0ohO9esw14=,tag:GqOuuzOGxDnCbRxCcO0gig==,type:str]
kind: ENC[AES256_GCM,data:mjEZ3UhdoQ==,iv:HzWXbjnnDVXYwLoWVJVdIBGeYh3X1ymQ2wekwEM17nU=,tag:NfgFfh80NmEQCigeJy6OuA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:up9xYAxWnEyMDucv,iv:+O9IAlRHRHLVc6LU1cmBcEPXC0R7OcBPp1o1v1Ds/qk=,tag:knFz8On3x23gB4bznUlzdw==,type:str]
    namespace: ENC[AES256_GCM,data:9CNzzTqtinnfWUfirfBeOMA=,iv:NcOlwFjHiKRjFFL8uREZpVNzVtAWjHUCyM3fZW2JVDI=,tag:6eYrNe6TtpIJhfiFCCh0GQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:MPCHDNtQHmTqdkZsZ6Ls,iv:IApIiJJV/jzBuAworwedeZyW0HaAnQZOqAGKRjbmPno=,tag:IscUz3my2X758r4rgD3QBw==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:xP4MNA==,iv:bN5PWNi3m1MD+Un9vpsCU8MHqkmAFfuwtlYkCOi2PqU=,tag:xC4oN0/oshjeSf2cGsb7Zg==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:maDXr2g=,iv:WuLRSkDBHtzanXgJQdfWLoxCspYpJTrqhdQppa9GCfQ=,tag:zMtb8iu9/q36ZC7uZ7r3Og==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:WiIGPZs=,iv:SSQ7swWP6O/5mIPDRfKfXec2i4vxoobeN101vZnv7CE=,tag:NX4Tqw1vtH0Q7lS/jVz0pQ==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:YREAstI=,iv:P0ej0MFzANRz1XYKE1lxggtG3a3AC3nz5P9j7lFZLcM=,tag:PnUGfCRkm9PwieZGw/AkNg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:+KNEMsiJz5ErXkF43xeeeVodpCldvkpIfz8=,iv:VSMtIvUMxi5p/3P8ieSOYlr4XjO5MdarL0JB90YLDII=,tag:ZWiNQwfOd/rF5Oi3n82zkQ==,type:str]
          secretName: ENC[AES256_GCM,data:bqtPUGgNUhqax0Ed3b7ANcRGXqRSTpo+8eBn8ny3,iv:jyFCoXrN19ExhMYKqNAQdr8xc2oIojKzL8li3Fcss2k=,tag:PS7PmZEiByVem3YIG8LqHw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:JGWPDnR1MqWrcsetVelz7yXVpAOhe9n5aOo=,iv:QAyK9oysWcJ63vOIrVtI96vjUUSyd7r4u7ZYbnpBJmo=,tag:00l+qq+4zQajGZXj9zi4UA==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:tA==,iv:Me6IBwO6YnN972qwjuj2VJmnk6DtrRjdotP3VFLbeg8=,tag:x9HzzL4yespWwk8A090ERg==,type:str]
                  pathType: ENC[AES256_GCM,data:W4le6Rfu,iv:1xtN+r+wHI1o/rFCsTlpEACR/B0x753bMuV5pPbfzXQ=,tag:dv5K/iqhg9Jjc/dQI1DkjQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:KQrY,iv:sL9lWLTZm9F/wSSVnEoLm0OPQfZadWcl/gBkTtt/p+0=,tag:JuYJoOKQjrc5i7yjjRroEw==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:bm1+yg==,iv:71SHi/EANBGXZQxDzms7OJPox/jg1xbnAjRrPse5FHo=,tag:edAxd/gFYSsrg147NjMTTg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMG9KMnN3dG1yRXBMSzBY
            R0taVUt2cjc3anZCMDlITGFlSHJTd3dPd1VBClphYmF2YjJsc0NjeFBzQ2tLemZa
            cVdQazVaQUU5cXRsTlQ0NnQ4ZlpCRjQKLS0tIHVHSFRCOHZ6bnpmcmFTUDhsbE03
            cXAwbFFpSVg5WCt6bndidmJGQ1R3azAKE4BZ1/uKWg6/l8/nYLm+wkvStT3J0X9J
            NUDSaMLA7kFwZPP6wmcGe7PffED9WLlDB8n8yXLeVvhNxk01k9xmBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:23Z"
    mac: ENC[AES256_GCM,data:JRlPmD64HOEljy8n8xUgkx/USxEOrhTeujPEgKLBP0T63+SgKYxsUotS/UCePG1w/vw5d5M9imSBPGKfWR6XP3/VZKJvaD1QObMhtbmbpYiSS0DbGQa2kBgSLAqdaSxRPCfCwJnAeP6JexLywWszqQ38ADiFhXMZCCOuVicmCCk=,iv:3tbywdHsaQsYIaxbsYCX3w9ui8giuha3Q8mUYZJfFcg=,tag:GBz60MbV85APa/KXtpboCw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
