apiVersion: ENC[AES256_GCM,data:XJ5RXV0MM1KFgDpb1uJemCKQ4hI=,iv:du0hOFTzOWVqKKu/lB9gxEmT8+e8cgrOCAwQQyqqT4U=,tag:Bwpo8HEN+XnN1skwH9t2PQ==,type:str]
kind: ENC[AES256_GCM,data:B2roEKvbtQ==,iv:5MFJcv0fSwlzIl4+IVPZiSX5w+04TqHySnZQc3eU48E=,tag:2EUsEOUeXXliZuG24r1i4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hhE9VRGJFg==,iv:wbvZWjjG5ZFqJ1TKTSEdh+Q5KU2uPFY5XxtxU+UNzd4=,tag:W0STvJ3x8Vym7/znSjGKNQ==,type:str]
    namespace: ENC[AES256_GCM,data:xwJWhNtRFDC1vK9P+SFbm5M=,iv:cXBoes7Z67QpabS5NRCDkdMHEBowZ+tFVOQ3s0W+LR4=,tag:KnEuGGYaDdqlmzoEGbTKgg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:aiG7zAtATdy7QVqVo5V6,iv:ECERRt4AUW/2VC1R+PyM4pVgQiC+VEvnGp5k0tpZACE=,tag:JXigvfq38KksGAQ8YGfeMQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:EKXfGg==,iv:yMNad/CD3dkbZK0foyuwXzCrCtLH1bSUavwzIdowQwA=,tag:YAOPS9fgx4j6sFBMczyu3w==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:T/19pSM=,iv:OGDWAknYKCctaqe2ycUOrk7oTrPsaUXbueRzxKBtwoQ=,tag:aKJ/GknzTbax3NaGp/W1WA==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:qPqncGI=,iv:4zAg+jcM1otb7xtN+DuD/NQWURDtF2kODCJMIrQWlA0=,tag:RyCINDNiwCXtc6lFUmJczw==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:W7PxtyyV4wY9hl/8AxaShKx9GY1YONuWkQZtZV0qqf5pVeWSFA==,iv:MEjCx8LwUl+b8humVcfpwsIZk+rYSwT5dTIKzBdgAnU=,tag:qnN4CV0kZeutpSzhvvc2RA==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:FYBRols=,iv:soN9hADaCye7NrugGQuv8mySrUJbzdnBwQY8x+6UbMg=,tag:Mu+kJvsL6gr0WqJJ5WAgZQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:NCXD3yUaOd5l4pJSCVe5B8jt9Q==,iv:YEGqrgBQEzKKYDeNvEmWtVmi4BSDd4UFaST8AEejBZ0=,tag:mOv+nUi9Nu6qHvTeabjVaA==,type:str]
          secretName: ENC[AES256_GCM,data:Eg9FurZI5P8ua5GR3rKopejCvProFt0=,iv:+C281uTVBj1ohdIISix21sepvCh2eWsDFlnhVuEZucw=,tag:Y+oXft93a5RtI5PxdlT+mA==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:NzzpOB/dIgBD0NtqC6Oeh+vHMQ==,iv:jpUlWy0OhBZDH98tpiLghckO9K53RpBH2wyl5gmy5Rs=,tag:GZ5MnBmU+ZRJyglYYv4pNg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:Zw==,iv:A6JZc7o/azBrAyL7X7TE6YDXbOYfW5JdupwnJ9PeYGQ=,tag:030zTXGfhhsbG4wawAgYkA==,type:str]
                  pathType: ENC[AES256_GCM,data:3CCPjHiX,iv:5W8z8HCi/U585XyEIOFvi9ezpoK9xjVYBRjhyU9klM4=,tag:SKJmDfRdQW3R72anN/gNXA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:RX7LPqHvxR7+,iv:OEn2uVjRy24uNJ2pf5MIFELEZi+/lGImXbDzIy4Meos=,tag:STVe2hkg3bqdARO4ciPoeg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:z6VaFA==,iv:SkH707olnXystc0QUAuMEyPHLonQdrdXHLj17TZEI0g=,tag:2NQ0dR5AgQHcuV9DiEcEpQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGYzZrNUtON2pJQ0I0Qkxk
            MWpVanhUazZONWsxSllkUXBRcWFnL0tqUWlVClpBTWJ4bVJOVE9aL2hMc0hTVnJN
            RHcreUs1UE9sdEZ4V1MrMnJ2M1JKb2sKLS0tIDlnQWlLRklBS0huMjQwMjN2dXNF
            Qy9XZm5pbEpXZCtTWHloUlhwTWo4SDgK9uznNl2zdTq1jRLVKyryAxroUVWTyKWI
            Dfr1PV0HHrY6qKP8hwByUybbIVzIXtBfj2OOddK00uliD/EDeHrQSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:23Z"
    mac: ENC[AES256_GCM,data:F6SBtb7f9vOrVCnUbtU78+jY6g/etj1UMbafSLO6c9bO61wghfsRRpIkZYGBbfr9qEKqEzl3nUx81kckQZ/9bQJIjINXsCSMnVbHYLbQsTDz5QG+rGAdF144B51O4fupYTJDu8wVid9XK02lDdPbJIaHOOiOqc+bypv7FHwVtCs=,iv:5niWsdrkfGdzimZfGaFg926BE3qopQNiyGxV7zndIQs=,tag:LJckd458ZLPaSQAaH/Pf0Q==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
