apiVersion: ENC[AES256_GCM,data:L6stQ/bLyH1nb/mDwCBI5TD0EE8=,iv:oi52NUllC6lZ6Zwyyk2BEoXjX1FaZScnS0ff6exxvzU=,tag:Fx7XkqDEAOSckSaWqi+MhQ==,type:str]
kind: ENC[AES256_GCM,data:cKwlUyoH/A==,iv:nMe86U7fNhBm3TzNXOmb63j8MkdyVnDF0ydA5cvtPT8=,tag:quMGsEtVB/UiAb/QOblRqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gMMS6qI/DGf5axEMNA==,iv:06HSV4JXpRIXVWX+BUqFVhsaPc3iWFZQNdAKUx3Luzk=,tag:p3fJhvBbSo64SLbvG78DmQ==,type:str]
    namespace: ENC[AES256_GCM,data:2RjNB+uTF1dYFgLiMU1ZuQ8=,iv:K9Ogk0c76406shmlOmpTiQj2zn7qFu2K/12iz+08sTc=,tag:ujbPcDWQ5+r8JUnoOVjNOQ==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:CZpsG3LdG7LkCEc+9+MN,iv:6Z2qhd3kQdyN453oGYSTINdsAFYGiy01T74koTl0MHk=,tag:/OaLPYCAgiFmcD6AYydDQQ==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:uPO5Gg==,iv:msb3ejOc5XySrxSbiOU3HimbTYekyMpiZw4c1L8/7s0=,tag:NHofr9jYin8ynynhxHCdqA==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:4+uOET8=,iv:eEXPe/rDJFrTbj33x8c985wBG5Ohgxh0vtCG6ktRI58=,tag:bRo1vvTBd1lhywqB4tHACA==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:7yBNe0toOJOXU1KPL4SOVLXOGVihGQ==,iv:pOq7wVAjSSROinF6RfM9/hpR7NuAst4WEeiC6oX+Xb8=,tag:ws06SQJqABEAOz9BZLozNw==,type:str]
          secretName: ENC[AES256_GCM,data:UvpVcvRwgarGWRhV0bHx+UIx1ZDAWyyzlIU=,iv:AF3fqnPn4qwo9IejVg79oa9OL6O8mHktIyjUBNL77lM=,tag:+CwT6W6xDv3t9i8yCaRTOw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:kt9gVzpRDc5x8f5OaF32U5KT5xYc2A==,iv:1t2Ny8TWVA8JxJJxATcExYLLkAnNidC07f3pbdvzSIs=,tag:C3F5+JBaFhF1+lk9L5J/Kg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:dQ==,iv:YIJmUkHwaCKg4HfQr7LLo4djtGoTkPpvkhRIgionBhM=,tag:x76epwnLzvMS6mVa7OiwRg==,type:str]
                  pathType: ENC[AES256_GCM,data:eeYgF30W,iv:i3Rn9rLGuzQwCnaeePEJeaDlFDAVjq0VHLP6/1mvSZI=,tag:xXcBSFrvIogIqJTCEYda0w==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:bwedvA==,iv:lKRtzv2l1pl9HehmidarzEWISMCciJIqvb8zcFVswZY=,tag:5anR1ZMdhBUKDj8WL6PYVA==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:sZd6qQ==,iv:v9nF/UFDR6gA3gBvckaS6tkbOqZkgPNPfNsZBZ1kjYU=,tag:GE1Y8XQDBVrxJ1YblZDm+g==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTjgyaTB5YjJsMnFnd3dF
            ditESTZoNkRYTDlHenM3djlJUHlIb2tDM1NvCmlJSkUvaUhMbzE5RHhYM3RGbWlv
            ejdaeEVJYXoxYnl0aWRYZlZyeXE2YkEKLS0tIEYydldwU3pJVi9aWC9vL2hjU3FF
            TFl0QzAyQUZJVWxQTkNBOFJrRytEQ1kKy2PZvJS3eYE77YAZ31IxKX1NhTLvKgHp
            1EOYLZWEJy5IXq250pzd4mFnjY6zbet6/hLtWn0N9Z3LtagvMrMUyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:RN0Q3iM6B61pjZvb69ubtojf27m2y7bFbNccaam4i4YDWJppO++GbY8Q/ck5ClzDA7QXsZTQWz7dOtl9kvauUXRSlhI4Y5nq/JhTmlgmJkdNGzT+A/RmVP8VpeJnLQoBvRlXm3Usxd5Ww77EqbGI54tk1szhFOoWsBUnN53o01I=,iv:bfbfx7zaIVl2U2l///TbbCW0I4s6HiplSvzYUJRScVQ=,tag:tbqL+bcm4AvQdE1Z84dNzw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
