apiVersion: ENC[AES256_GCM,data:VE5xb7sDec836kLsuoPYvxEF2AE=,iv:g9Hb2qyXVHM6oRN/r1qHn9a1IIys/x0hjeVxPR7ZKU0=,tag:zGUGh0rQfBK7PF1T6in3Kw==,type:str]
kind: ENC[AES256_GCM,data:dyvmuWe6bQ==,iv:oi4onP7etam3FLiehG8q9jmXa3bkLCFRFpT+QR/N7bM=,tag:wjVgDeU6vBUKskdkyr++Cg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xq9D6RdSyw==,iv:28pQNzYDO01odt22RwOvyBaZjx6/Dbmn2i+i7krTk2g=,tag:qs/RMxEeXPRX5gMt4JR/Ig==,type:str]
    namespace: ENC[AES256_GCM,data:jW/phNsFZeuTDFqM9nBt3Kg=,iv:7IW40x2EJN4nL5fzYJ34fhdhi7jP/Zrp/klOWMVOL3I=,tag:XKbYCF7iKmM+uzpfsuaGCw==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:ydwj3RWnSLhhp4T4H9TK,iv:LfnrMtsAm93kKbg/bgt+7ycNRMpWLZkaWrnKVzWWgUw=,tag:vTCOf1RbucUT6X+I47iL6A==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:i175sg==,iv:HUG13P6bLVhljXEqocuQXNlPJ+q8YJBBPYUBs/M7COE=,tag:XMS/ueEjRFHHla4IQKXQ8A==,type:str]
        nginx.ingress.kubernetes.io/backend-protocol: ENC[AES256_GCM,data:g0JLPlI=,iv:je78szGsqSwNNiHXmRahyz+qigF8t7R/uIvPWmIUjXc=,tag:5t1AheVnF+s0A0e64SJZHQ==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-verify: ENC[AES256_GCM,data:DOn7Yks=,iv:SVbsOoXlzNbzN2wS0vd5Z+XGPVM4wWke1Hppwz1CNhY=,tag:6WwBZjwpZBbI24iDYxkvkQ==,type:str]
        nginx.ingress.kubernetes.io/proxy-ssl-name: ENC[AES256_GCM,data:w8cpZ9fpGCmpoX+uEp+8rwbBrxuMWX/Z0YeESBJssjnTT/z0ng==,iv:rhmarD8Wq6/4mRE683dJBFg1iWCJJd+ukzuXmv+9P50=,tag:ej1loauArAqlcIVRai9vEg==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:9MTgzLM=,iv:CCx2EeDS2UdSH/hHZKmy7pqTrtOiADp2xvCSHEoV/Qo=,tag:2PAPCQwYjAZ9UcyOV/PRsw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:hwN1BAkmUhVG+GxtKOVbow==,iv:JG0P7lTZZzGqulDotIjptLdrwIpOfN5Qcn0rmcEvKoE=,tag:YXyOFgeB4IKDwOATsrOcqw==,type:str]
          secretName: ENC[AES256_GCM,data:xE+pWPEYFOFHKjvVL6oZBsqBUzo=,iv:wsof1j+XrROD4aK58gKjexpmqpMMQAw2pwhgvt12KCI=,tag:clxMOKrIi0TPake6GJI+8w==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:io9PVJo5swBisso3cztkhQ==,iv:DJsY7jlLQ1fGv4cuQVUHlb1GMW+KGgSPN14Cbewvxo8=,tag:uaYnSipRYA7M9qAWq44r1Q==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:zQ==,iv:0nc3kWrwucGDS4eW4udc+eXc80Gz0EvuBKeXrryVGRs=,tag:Egh0LNX2ZKCnZkciuREi6A==,type:str]
                  pathType: ENC[AES256_GCM,data:OaWlRyiT,iv:ztfX+2mYywqr5FWb9hwqJct5RDYK53s7q7cGc/urMJY=,tag:pjOrVsHEc/O/SLz1R1WRrA==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:FJzzooip3fQ0,iv:YkZrXdZ60Zl9bVwKgKU894DyhMYEIMeC60wWCEeqAN4=,tag:K7TFsoxRlnh2DU30yWDIPg==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:Daq/tw==,iv:+wIx0e8D5fibQ8lHoo6S1O1P1PKk6daBdTPg0m0fVGY=,tag:HCLgGRJb6AzqVVBsF1ZVkg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RW4zU1c5SkJ3ZGdGTmky
            VExPQ2t6SkFkdzZ3NWtBSEp4Ui9tVlBRdXlrCkZhOGFKN29xSEhERU1HNHU4VzUr
            REdjUjZPY2ZoQTFrTjZrZlY2alBLb2cKLS0tIExGL1ZJZXlRT0tpNU1aYmVnTzdU
            OHhVdXNsV3Y2SDFCZjR4UCttUUw2eWcK7GuXgFvlfnfqMAgCjVCpP/SGOODEbapZ
            1B05UPJwa3S2E/1beGqqJ4GLdjdR29Y8jG77IhZh2pTfvGgf1M0oTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:VGOwVTYVatXt2yVbOsRXUqTeMrTHdg5qYR4GYk3Zs7W+NeoL5G9+e8ahgk16Eao+/pFaU3JK7xjlEmplWzUjmrTEbfimSh4V/QdrEedc92bAZALZAMcI7PueIBWeRB1bhCLmN/bTjTI0Vv5udr9VLfD3PkkJIdwAAL4pNvy6MTo=,iv:evL5bmjCDnLbOua1v9B1mGTobxvTf6NFAtIfyxiJv7U=,tag:8/YOMt+jy1RM2sIUEmcIfg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
