apiVersion: ENC[AES256_GCM,data:f95W/zbihR19hhJUo08E5HSUmMI=,iv:MeaTHtV2NGpi+PNpMfYKMrMGDfb2EzzRQ3XrjlcY14A=,tag:iQuh9zD4VXNTSq9hrZ51eA==,type:str]
kind: ENC[AES256_GCM,data:5x4206t7Pg==,iv:FIlG7a2C0c5+X7v/3hPgOovlXiBurpq35/DnLh1NeDo=,tag:KSJ12epErxkRkVdt7cWsyA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:knz3LC7xnh0KfqPk,iv:65GzEKsO4EYcXspzpBN0hYrm9cGiL+BZ8s+DmCAaumI=,tag:Wtz18WsW1nPhU5xLjWnJng==,type:str]
    namespace: ENC[AES256_GCM,data:bMEa04OLlBg/oNltBocZdPQ=,iv:x2ToicbgKSJ7Y437/7p4OjoSN4Mr5nYgLfivlBySOfE=,tag:pp8RhX7aqecvhNl4EcOn4A==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:iFwq3N0j9joQ6Ae/lbQE,iv:apIihxKXqtiOtw2JYmSlP8ZItV2MU7I4VtzC9kuuWoI=,tag:ZZqZd/HX/A24VX6/inqB8g==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:r8xpOg==,iv:UEDLeqz8u0KjzlQQeMXkXV5++xLHCEnSlxWN/oiX2mQ=,tag:lBGSsJRlUVf0ktNN8C83qg==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:62oFwPY=,iv:/ec/RmVNmPTd8zDhkiMI5DnUrfE5YN5s6ONMT7qoy3Q=,tag:8LM3p1ZrDubKrGjCnylMuw==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:wjbFsSkuethKPZcOZDk5MRt68qGjHEYS,iv:NFHEOfa0QDESPak0Qd2AVP2l8nJ+60iHAHN1PBwgKNE=,tag:4EEKtYaJbg2RQC69/vfhFQ==,type:str]
          secretName: ENC[AES256_GCM,data:F4sCfD3+ZphHXRQ0SpxRMjnKhfQbgnodNSCzJg==,iv:WLI/7PDbI8shbV9432g2Auc2gcPWpmWLwXF1MajojpQ=,tag:wOOTf0o78ZMVewBLZ0oVgA==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:9NyviWcFZMFCoRRAShHImxy52BtEVN2/,iv:b6swok/un5b8b4Chdg/LfnxM7ZYuEXoC1XqPZjC1Cj8=,tag:PV+4spZpY9uyodMACrL3IQ==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:1w==,iv:fiLNV5DY5hMEEq7d81gGDpwmUvkBbw6aQwcua9nNcJ8=,tag:QOCDuGQ2cenz7e/BchZDCw==,type:str]
                  pathType: ENC[AES256_GCM,data:DouaXA8x,iv:tyDZeO+gIkA8i2uFzQtb1nC0aTesNKZHf5ZE8wcjGsc=,tag:HExHU6cv6bO/tF+9moRwaQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:ZdQG,iv:NcvRGeLn81zJA2AukY7twq4vLZlBRNOvYvcva5SKwe8=,tag:O7sOtyVprVrfkZy6tJskRQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:MrpBGA==,iv:34esYwzRG3Xp2BANJQ1/P8EaPv/lpoB064qyQxj5LfI=,tag:rnp4znA4SryhALa5dnqrFg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUTI5M2JpTTMvRzBUSTM5
            cmNISTdrcyt0VFJOYTVxd2xseitseTRUUUE4ClFkU2Q4WVF6aG93OTQzZkRXazVQ
            ODFCOE1DdCtFS3ZlMWNWMmdXaVZhaFEKLS0tIG9zSkkxamlMakN4c0FYdHM3T3dN
            bVY1TjFFMG8xN0l2TlVJUWlWeHlWNVEK2iTx23jnnW/QKNO+jX346W3a5YeTLcrj
            xDpylxx6qkZe+12R9VOkTEqToXHpkaIs50C7cm2aMINlWoU3vs/cLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:4OnCxIIjc6VroH7I3xmAtMHPklqzKqtvMQEVQ70OeQ0+8UFTul4JSWHinT41Y8LwlkXNfJ6yp3h3riWKvpqfdxjph7uuYFpJG/gokyjGW82wvL1qMz0Cyy2hVpYRyQWqMU9ri7OXG1dXNlvKoBrWJhf24lbwlQK7T6it6RlBjF4=,iv:pasTr7e/PqSRYGDeibjmFyhrs5h40fblmfE5a1fjC1c=,tag:k8PxfCixf0dAO7uB5nSXcQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
