apiVersion: ENC[AES256_GCM,data:oJxfII+LYi3dci7gPVdpdA/OP68=,iv:QnlWqV1zEVps1wdtx5kmmnrBVfg+ntQL6Kdd6N82Y9k=,tag:pddMQQ7e5SpNwNiZeH9lsw==,type:str]
kind: ENC[AES256_GCM,data:zyFJQltNZA==,iv:5pYDB053LGVK6INWt7o4GW38wYS0+Z2B5rmojExbDmg=,tag:DrUWOzFjtwzWrMWyMNfzCA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2H8NBceaOGKvLIxGxcl0Dg==,iv:LnoMIzYlYB952+XOQtF7WkRr3cAl3RIMBPnBI8GfhB8=,tag:ACxVdwnTJuaKVRoPN9FszQ==,type:str]
    namespace: ENC[AES256_GCM,data:kO6b8aKTeCckc+PZc1MkFfc=,iv:Cf6VT1UZXaiUEo3E+o28Wr5yniYVDKUPTK95Bx3N2ow=,tag:QpPvO5XZoTysI8ukV1s8xA==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:boIrGIG+laB2wPgazsmz,iv:b64zvSrL6vI5KrVrmwX5QFo3KKd+XqHepjROsNig6mk=,tag:LQRKDDme52p2Q0an+X08lA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:5FD0sg==,iv:VI0+Zs00sxXSe5IA99coMr4ezHAKqaNYc0MQJYIsHfA=,tag:VxkgWiTt7StA6/cKJpolJw==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:QyAsivY=,iv:lDH3sOeimPPYQy6I144gaHIqOYjYMv1YMGrgI2Z4HsI=,tag:18JUkO5nsg6UiDysWsF5Yg==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:hdFWCM9MaUb1VzXtZcy3uGUmEUD/cnkj4A==,iv:oXW6Y6kxbw06TM1eZf+xmJbODts5+mVxAZNL7VAoI6w=,tag:AxnH2rrbdquk8i7WnZPXHA==,type:str]
          secretName: ENC[AES256_GCM,data:DJyir+LOeto1gkyOtQaC59qWzoQn7JjTsbJTK2E=,iv:Q9CMKRDbuRGeUfd+iIFKvSwBq9weo2hpyp5IGPeKasc=,tag:Yxx7n0iFV8L2AH5EeMhZZw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:zCrLD1DIc+byP6argzoIBmp1tMy+DHlwjg==,iv:g3lBVv8OuGDmmKKb63DjXnk/f3lEL9HViJkYVvX3Esk=,tag:UVEitskH8e8vGyQLYigirg==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:lA==,iv:GI+5tZwMVHpqRMg46+dzADRceDKQa5iKZ3gsPb4EMAs=,tag:qvSEPQcHys/qDToa8WLq0Q==,type:str]
                  pathType: ENC[AES256_GCM,data:Gt9+5/IO,iv:DJ9nXdwzl/eBoSS4qcwpNwGod6oRoze9r4aztMuEu7k=,tag:pRJd8vf5kqr7g4aK92yHyQ==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:fsYFJvEK7g==,iv:+6OGfa3q/2hq8V+2saDWUd3xitC4G1ETJmo/VqttHDI=,tag:ZNcp1hRzf7HSRxdb5szsLQ==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:BFZkXA==,iv:aip5ijEMUWmYWqI/bpara6TU7rsFyZihhu/YhW0b3h0=,tag:SGLxzd4HCcTrMoMAxDhmSQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMmxaa090d0VNQWJ1V0Nv
            UFU4RGVwNlVkODI1Tys5cXRkMDZHYUJHa21ZCjNmQjFXSzRrNGhXNWdwSzhGenhi
            T1pCb2JnZ21PUkt1ckpObFlCdmNGOGMKLS0tIGQzdi9ZOW5HYkp3OUMySGdablFl
            MWtCYUVzR3RDU3ErdVFhN0NnN0c2S0UKSPqbQntO0U2WwSyjh1ZDu5Mk2Z3vUmop
            ybTULxoWsp2YhOu5kS73+QkPi7kamvUBtDUTkNJg4Mx7HBhmynTUsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:XGcgJhkUV04ohtgWuvWvEq0iEJKjSbQRNlnNzuEs+gAKpUt2lx63Sph4geemxnpZOybDR6qLYwnfS2KaDXlovttYyktv6KoNh5src8NMmpNZ8kmvs9xW8fxXaWMeW51lhnOiOaW4Ltphae5T9lmiGuSLXyFkyhxLUdiDHuDCFjw=,iv:jRhUjUhLJIiElCvnsm7vW2lZ2GBg2OQNEyZTD7zLuXQ=,tag:rycGwW5NqjncMukW0HRGSA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
