apiVersion: ENC[AES256_GCM,data:uTmTv5m8kGndMrM5AFqbQdLE2Q0=,iv:lAwS39B7wYgNY1jzebbgqJ9k17E4k8kf5rOjWxT4VtA=,tag:rgeh16F/YzKWratABRKwxQ==,type:str]
kind: ENC[AES256_GCM,data:U3ubiLBKiA==,iv:iPbNM3JQbeKWmcqZADYkoSJk3i0AgOe+KND2Ua59w/Y=,tag:EkwRajC/faBmyq3Ya2rHog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zzpGVml5wqSHdNvrShn0qw==,iv:s048HA8cN44t4j2fvg/vCszOpa7f7R0zWeq3WQafaUk=,tag:mh6wYYnrqFzbSFd187WO0g==,type:str]
    namespace: ENC[AES256_GCM,data:8RSlL0F30bNf0EaTK77Wo8Y=,iv:ossVedORwStEH1zYWFgueJ5sIf/tkYY57gNpECw5Las=,tag:fmanRCvTofeAlsKsd+Yosg==,type:str]
    annotations:
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:KCtrOjRLdUYKogYT+vdv,iv:nH9yP6PdIuU0kEC2F+E4kib2PmLsWCg0ichn39gAMdY=,tag:AFNtiNKdaUK89bkx+43YLA==,type:str]
        nginx.ingress.kubernetes.io/force-ssl-redirect: ENC[AES256_GCM,data:h9TGUw==,iv:Pa/yCWh3cwtW5UsQxh4+6BlliXQtr2/oIbolm2oYcfo=,tag:bsQksenPkw6bMzA30Dfg0g==,type:str]
spec:
    ingressClassName: ENC[AES256_GCM,data:pllniFw=,iv:zmFkIhSFBi1LTUd/6wasJuG3xKyexVrCEwisDEABAmE=,tag:PGPO3+vKvhvc3pmnSH/CfQ==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:/Hp+47NBb/PdiXDSpSlKdbI3cel/h51GVQ==,iv:NOS5w6a7S6ZlSOMXnUvDrukjKguKRy0yJtSUm0K+nKw=,tag:bE3BiF7zMqEggVTAVpqDAg==,type:str]
          secretName: ENC[AES256_GCM,data:YI7kR0SZzMf+OB9HQ+GU/kUV0bsd9DbhLwBsrWk=,iv:R+gdacyak5cIAXjb9cjZKyrJMAKQdfbzkPbT1pjlpCI=,tag:TrmYbA9imcjJ80BCfs45Uw==,type:str]
    rules:
        - host: ENC[AES256_GCM,data:HO8KQsn56e4y0zmmvqgWcSBPZliREArPig==,iv:ImYUlubtzoZuT/ppkwg14bAbuszctuGCO1Pl8358tuY=,tag:g/YDdFSJYOo7S/n6eiEX1Q==,type:str]
          http:
            paths:
                - path: ENC[AES256_GCM,data:HQ==,iv:YcozFXJNGhUystMwt7uR9v7XiDbC9cRIja3Gykpbh3M=,tag:D/R+zPN8q/tGMoYkx5X8Ig==,type:str]
                  pathType: ENC[AES256_GCM,data:wKCbfL3c,iv:9ceznV/7nBbd3TnlTe+jlHvMLKj2f+CYlonyzFE+y5Q=,tag:btCgn4jhXEDHDsPHPqaZOg==,type:str]
                  backend:
                    service:
                        name: ENC[AES256_GCM,data:W8M9iggXJw==,iv:ceS/ekmKr/nwDBeOxaRS9WLj09wByC1G4/tKS2kDYkE=,tag:YUo20sbJUCVVdMFY30lS0g==,type:str]
                        port:
                            number: ENC[AES256_GCM,data:l9go6A==,iv:j//bCjtsyxwuJfGZqdVGLYGqky5rQu35i1LuLsB04SU=,tag:a8RF4lycGUqBl18IVP3FOw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZU1kZlk5RkNzMW1tRCtz
            eUVGOTR0QkVqYUNQTnlzYjBLZ3hzMGN6ODNFCmF1MStoVS9LLzVtdnJsUSsyWTgw
            Sm1vOEVlRC9zK2hHT2N5NUMzR0N3SHcKLS0tIElub0pJR2NWU05BcTY4ck1SMkpH
            S1VtZXR2S3VjNExFR3dPMmd2VzZ2dDgKUxbNFq0wzfdxx3LrFLjTCxMYX8xFOdTT
            4MWDgA/IlNQUbCqUfgEt7hBquAJ39jyqjUpqkvTlsDUOi/2cUaN1VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:45:05Z"
    mac: ENC[AES256_GCM,data:pg9xOjI96kB6eg4d3ctkvkIWany5Ku4abJwrBNQBpK3SJSH5x5+8Rrja+ve1bk1LSNDolZmlo4oQVe1r+Yp0+7qx0E2gLzgudnaqj8GkaY03GNq5gbMNQ/8AAG8CMCcUzObG8ukmn5meQTKHv09BM7kE/GC3zsyzG4LfV6pd6h8=,iv:G2Xe9GXKaTtknbRU+6D7qp/KqyuVA6N1Hjql2BkSibU=,tag:36lZUdXxiOSiyyfe4s4PBQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
