apiVersion: ENC[AES256_GCM,data:lsM=,iv:VAshGa4WLFynYgLKomJdJCjsTKlB/uY3GjRWqNjNKEQ=,tag:S5Li4V+FSILbs+UGFllb7g==,type:str]
kind: ENC[AES256_GCM,data:TSg3O2cvkQ==,iv:aHyNh953tEoiGo3cNKUKnJv1mtSvWNZfGf1YJg+Tnfk=,tag:+JpUMXO/psyj1TkiM/OBKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tueleQ==,iv:FKR/Md4lPXL637Lm5boswKGtF1rZO/Q2WhvS49/iiEc=,tag:0kwX8b0j83VzyzQrx24ZtA==,type:str]
    namespace: ENC[AES256_GCM,data:p36cFcua4o5D2mZS6v/cHIs=,iv:TthOWuGWmApMesmuSm7dWX/KwgWxq5UvzaAq5cSggtQ=,tag:GivNril9TupFd2zI16YlPg==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:WwRZRQ==,iv:IeRGSNy10X9H2Jc8XkytNtJCIym/wE3C9REJG+KzjiQ=,tag:nB+lqG115dIWXWlppJ5ABQ==,type:str]
          port: ENC[AES256_GCM,data:x7jRsw==,iv:rP4aLUtNiAE114In2uZVWxWuCXK3nQZXB3dKMHC88hY=,tag:6SknBvGMP6N/MzDFrn5Ewg==,type:int]
          targetPort: ENC[AES256_GCM,data:sPJozg==,iv:ez095peYrlK1drdB684Ff8j6JPjN1ch8n90avz0VDEU=,tag:LuhHZdAAm4VyVkXVL6shXw==,type:int]
    clusterIP: ENC[AES256_GCM,data:WQ+x5Q==,iv:Yi6H4XFKEkeSS0AxKdOa8JKUNYYGQbvOTvXYlsGUFsQ=,tag:njTFTJS2RBHdEDIJf9FFCQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeVgwYjBYMDdMRTlGc0J4
            QnRMVDFOVU9aY2c1ZWRjWjVVemZWdnl6aENzCjh1UitueTZheEJJOHduUmg1T1VP
            SlhORncrZzRQZnRMcGRjWDM0K0VubUUKLS0tIFY1UyttVEVTUEVXWGgxQ2lCTUQ3
            cGgrVUdtakJDTC84d2xVSHpDbkNta00KS6bdcUVahw7pvbsYMVq0NdSrNiHisKPk
            bCTDWpEV2WddsmcKcBXvv1s2OdhagKqUnELHVQXA/mnC/7JXDMJU6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:r1UwCwutoobEiT1JxrmfR+hSqwEBhxTImH7O+EqYoYoAe3Li1ZHVmPOVtgnZ8Ei9qLFJdKIDTcIeEGsi3z6F4Oq/lQJC1b1sJbT9NlwO54DhAnW+JfDXUEYqiGoDiJK/RVFW+w3HEWrOokNdZDrXYs8XCrG6Fc6jThFxIOkuLqw=,iv:vKNqkm0SLM6ucsmB1vsHgFEszGveTVZWvP6sQincSug=,tag:gUWx5ZzFcAM77jiNWM9xxw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:xZY=,iv:CH4UyHLN6T2OHygwl2/j2lg7FuTlMvITe3nvOZSphOk=,tag:yYF+3tx9AxS5SYyok79UMw==,type:str]
kind: ENC[AES256_GCM,data:2XYEBOsXIojr,iv:M/LeXvo2Z07NPMZARPfc4cdeSN2wscg3Q0jP/N7+IXE=,tag:f0ga+wFeiHpGBypbkwkl0Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:okPRDw==,iv:o77dkjag+OD2JkeZHPW0jzKpkjTWa/zMXnJxDN7yCPs=,tag:E+C141k10Gj0KAQ3UGkpEA==,type:str]
    namespace: ENC[AES256_GCM,data:3Go0o+mQUwg7iFjG+cO8mQQ=,iv:xpwFegDymCe+EpZCQa4rj1T/rQuAmVKQtbvEJyaOGGg=,tag:TkSq26LLMjS02jioG1MPKg==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:aF9tLZJzIAOjunE=,iv:QtQuJV5Rcir8/k0JZ1AZxv7mEB9auGNStbG7L91STVQ=,tag:uDNuAR23nN8ojuVB+blXmQ==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:iEEhxw==,iv:c0JfsAUY3232MmbF07DgDqWvqbuJKwUsMpL96sICDu4=,tag:FIHYqezm4CjAKxAnsBf2MA==,type:str]
          port: ENC[AES256_GCM,data:FCo6Mw==,iv:gf+3NryhV2lkwPtEDNNsF+Wiip8fYiahkl8wPKmfZkk=,tag:c3x16CWzD2aC+3M7m4xiSQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeVgwYjBYMDdMRTlGc0J4
            QnRMVDFOVU9aY2c1ZWRjWjVVemZWdnl6aENzCjh1UitueTZheEJJOHduUmg1T1VP
            SlhORncrZzRQZnRMcGRjWDM0K0VubUUKLS0tIFY1UyttVEVTUEVXWGgxQ2lCTUQ3
            cGgrVUdtakJDTC84d2xVSHpDbkNta00KS6bdcUVahw7pvbsYMVq0NdSrNiHisKPk
            bCTDWpEV2WddsmcKcBXvv1s2OdhagKqUnELHVQXA/mnC/7JXDMJU6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:r1UwCwutoobEiT1JxrmfR+hSqwEBhxTImH7O+EqYoYoAe3Li1ZHVmPOVtgnZ8Ei9qLFJdKIDTcIeEGsi3z6F4Oq/lQJC1b1sJbT9NlwO54DhAnW+JfDXUEYqiGoDiJK/RVFW+w3HEWrOokNdZDrXYs8XCrG6Fc6jThFxIOkuLqw=,iv:vKNqkm0SLM6ucsmB1vsHgFEszGveTVZWvP6sQincSug=,tag:gUWx5ZzFcAM77jiNWM9xxw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
