apiVersion: ENC[AES256_GCM,data:k34=,iv:LKtY4QwOug6zJ/bMbhZUVHPw/4xH5DB6zdaYxxk6scA=,tag:9qiH1Tbc0IGiPUAM9+2ZxQ==,type:str]
kind: ENC[AES256_GCM,data:QEoai++y7Q==,iv:7trlSqAyLS3IT9PPE8jAROek7Aiqy2ZjNq1bvAsZcbc=,tag:aZYY8Gw3UEymop0/LXG1Hw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NE/rIaviDZE=,iv:Lt8uDZ2UMQ7ZVHJMc+GHIsFGT8p8PspfyKyixdkGHOM=,tag:L/OqoubNYotT28rL+NeU4w==,type:str]
    namespace: ENC[AES256_GCM,data:dp+nbzAUu+53XrMXaJ6bXAs=,iv:3of9aS/xz5eVnlVraTfhVNGjgQRfwquwix2g/RViabQ=,tag:cbkozzhEuKPHxhVZCjVyLw==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:veKC/GI=,iv:8QJNRBOqmp7EaFtTf9SacnQmJUbkkqhhmsqxAm3ht80=,tag:zM5wlUIrPh/4JuSvqn9vDw==,type:str]
          port: ENC[AES256_GCM,data:mbh4iM0=,iv:8aeKcv+k+T7vwKStXkTAEFerLX/eTmoRtyTFTP6JKGg=,tag:JpJv2vfhkBHrkAavq2ozQA==,type:int]
          targetPort: ENC[AES256_GCM,data:paTBoQc=,iv:+x2+7K2Zvw6gMowc/r6iM93RqSGS7AsPLCzLLH9sEQ8=,tag:1VCfXNVBU+dNPYkduCRfYg==,type:int]
    clusterIP: ENC[AES256_GCM,data:hrWP2w==,iv:1qDW7cQjoQyUMsHeiamkNGk7lliwsmSu8kF0CrZL7pY=,tag:HvGI8HUw/u1U2WXKYDNORw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVRyQXZ1WnBGTWhvQzlY
            cU04V0xyN0ViNWVjaWpUUGYvUE9TNkJNTjNjCjZKTkZmN1AwRmQvY0c5V0RFNkd2
            MFBuUFViNkJiU0dpdW9lOVZpZUkxNE0KLS0tIDJEaDMySWpobTFEeTY5R1o3RUlj
            ZDgya2tUZnE0SWRJbE9BbHRiWVJ2S2MK9u2Yk0+fx0r+0bF/Bx1L08E2SUNGdE8j
            SF/UYjrjCNL0VSB0RgE96Jzz3/zRwm9efymIkeMiyTmlUFg0kGG6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:0cLdPZ2EQ7sqtVe+UCIIKatv4QyzpnGAkDcAKblFBolCzpoBtPEqdLxknv9XV+OJzlN2Y/+s/atTpMQMV3SUnwStY9+4XEk2ECH/1zYD5XZ0HWxn1iKsIEpZxr0puDkw449nNenj0KSZ6Z1Mdq7kHAxfxHBfSKB9Li1jrKkneLE=,iv:ZWaWDR8kPiS1x3ATSXVM/YVYwkj++VdVxCXH8fRnjH8=,tag:tLWxGQVZ9PAcmgOT376APA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:eeo=,iv:RrgsvfehtEbeqPDmJ7LI3ChBIINrWyp12frlktxCdMI=,tag:eFY6AJ9Ot4pHLukxWyxYPQ==,type:str]
kind: ENC[AES256_GCM,data:ZkWEMtZ5llcB,iv:M7yIWKVMQqg/mB+x+ectq93X1JUfNbsa3T2s1nanJDI=,tag:0k2/KbzQOSgs7jM4O1YgKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VEAX/BZRSso=,iv:ntLVtVVd2HOmVdFqBz90EAlEFb9nL3qjFdZRiEErK+I=,tag:NIRrIUPxWNAH5DYWSd/K5w==,type:str]
    namespace: ENC[AES256_GCM,data:t94d8st3+fZJnifbrA9ei0Q=,iv:oMcjhkxR7h5kXd3wE2v+5XDHC9JWt2wYg8gilErYUW0=,tag:tX+wNZq8sPRJhZyiZFbitw==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:m+YFYawUGDc05g==,iv:QUU5WMvmq6gUH3oJjXXbpmaruw5zsl3U+WQc01BwLFc=,tag:z/hY8NMZuLyv0dtibK8KZw==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:u7abxAg=,iv:Zfawg75mhPnVDnEqb7KQbYzcIFW2RmpmGCprbuWNCFk=,tag:VPW59wyteYE5Ju4Q6Y/aIA==,type:str]
          port: ENC[AES256_GCM,data:hu3UvKM=,iv:ksnK5nFynRZk8feeLyIDRh8l+vCCH+oBLRANqHrCx2c=,tag:rZJxDWE+cLA95G0j0BObZw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRVRyQXZ1WnBGTWhvQzlY
            cU04V0xyN0ViNWVjaWpUUGYvUE9TNkJNTjNjCjZKTkZmN1AwRmQvY0c5V0RFNkd2
            MFBuUFViNkJiU0dpdW9lOVZpZUkxNE0KLS0tIDJEaDMySWpobTFEeTY5R1o3RUlj
            ZDgya2tUZnE0SWRJbE9BbHRiWVJ2S2MK9u2Yk0+fx0r+0bF/Bx1L08E2SUNGdE8j
            SF/UYjrjCNL0VSB0RgE96Jzz3/zRwm9efymIkeMiyTmlUFg0kGG6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:0cLdPZ2EQ7sqtVe+UCIIKatv4QyzpnGAkDcAKblFBolCzpoBtPEqdLxknv9XV+OJzlN2Y/+s/atTpMQMV3SUnwStY9+4XEk2ECH/1zYD5XZ0HWxn1iKsIEpZxr0puDkw449nNenj0KSZ6Z1Mdq7kHAxfxHBfSKB9Li1jrKkneLE=,iv:ZWaWDR8kPiS1x3ATSXVM/YVYwkj++VdVxCXH8fRnjH8=,tag:tLWxGQVZ9PAcmgOT376APA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
