apiVersion: ENC[AES256_GCM,data:W78=,iv:E/UsJ+IWgEAX16pD3XeGruj5rauw0uAhtFGrKSzvkFI=,tag:eepeu92LBlXLK+8RLCHnJg==,type:str]
kind: ENC[AES256_GCM,data:i/7hlT9Z2A==,iv:1DcD0F4vLDY8UKwiBuxpxs7gnWTDTrkeQO2zurmXcDg=,tag:tGm1jn7YlqubSFMncYZ4Ag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dhBJ4s1mS7s=,iv:bJ5IBJWJNEjhQl/rGvrFqEbIdILSgRgMmGun5PXIj7E=,tag:QE5P9vHXW+/laSEOYeXRBw==,type:str]
    namespace: ENC[AES256_GCM,data:cEvgbCOp809ZT+Hp+5Sy9SY=,iv:OowEnKoBscwnFOpY1mdGLqi6XKBLt+WPxP+rrKLy614=,tag:9xmeoPpdxm1tHP7rWgvAMw==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:SvYaJQ==,iv:5034K2fUlQuiNRpK7kQF4K9ky1WZxaSSYQZHW5KOVmk=,tag:7VBN24aWuzsnDULHPrpTgQ==,type:str]
          port: ENC[AES256_GCM,data:G9gbNw==,iv:Q/GTjKoRf8lWVVAtx+f7H8KE73sU2EZOTw7Dypll6Qs=,tag:VOBgVlAOjBQTCQA6S+2w+Q==,type:int]
          targetPort: ENC[AES256_GCM,data:aCemnA==,iv:8E3iMb2XcsBECnSG1c8QgOkxebmyvVSARjTzFb0yu9M=,tag:DwOmZxhSnpSVCVCsF9qqRw==,type:int]
    clusterIP: ENC[AES256_GCM,data:qzP/Rw==,iv:e1w0qv0M5k6cr4GTBn3VbEu3mZaiA/+9AI+4rIYDbh8=,tag:a57jfywYPK2cRekI4WKmhg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZnlPMlVZTUhucitaTzR3
            ZmU2QVhSR0NGVlRZRXZiK01JSUdvVktpNUNzCnYyUnJjQThyNTgydDBmWVdxa1RS
            ZFlvbG1uTE9KdVIzd25lV2JRL0orMGMKLS0tIHp3LzJKdUtqNGQzemJLTGJDVlF3
            eUN3WUFWbjZyZmE2ZXdNUXRqNUwwa0UKLYWEr6XoLzjrrZBcjkO9M+p2uZ5p9cn2
            QXskBIechlZjFo9rQMat9X4XBfC3vCU8PkLKqJMOfqiKDR5EGbD26w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:XubNtrSRi022Kx8X/PRPhh9F840MnOzQRtz4oHY7o3/PmFYy6ZDqg68UOu5BgqRPJTMmvjzJ2HBy6hSWDLbf5IEZX92VgJbxm907X4PUVNIiXrp3x9QzufR/GWyXpnWdJjJbomFCnPuAJuSGQKdkQS70OUOcnU8Iz6O03MrbTPs=,iv:9Ym5kr/pSPhUsNLSytHl/bHceBqiM8Rpca0JM3aG8uE=,tag:+n5ttlsvF/1qmUHFyriBqw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:0Uc=,iv:aTFGVIqLKP7ZLWf+25BWU9FB+imyVSV54xzJRF42IS0=,tag:kENL41Zd4Pv5+Y8yn8VFew==,type:str]
kind: ENC[AES256_GCM,data:sFNGhC62M2b2,iv:z83wYZoTXfCuY3vLYTsyTJJkVxWz9keJCGiWPDhnfzA=,tag:hN0Xh0s8gvamA2fd45AMXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+ZvFj9Shc28=,iv:XvBcEb8Q/DahtThhmmvvkqG/vPlPIUtan8BSmcBhjhA=,tag:BQ8xCHBHG9BW63BSSpfynA==,type:str]
    namespace: ENC[AES256_GCM,data:y7irhQGW1oxOol2xekH8Uj8=,iv:FuO1HfiMeIg5HUfH8AeS7G2vYdrsIKMLTqNHTvk+0zM=,tag:QbxD9LxQYglMoyioDbdeCQ==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:xsNqc7nQTnVA5Ns=,iv:ouMwk0OWHaTSs8Sxd7aV5r36EHKBz8hSiVmtTtCOOFQ=,tag:KcFGrphgyKXcOMBYCA+GpA==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:ui5oCQ==,iv:DWZrhgqOumClM51lncRBhBjeTU9BINTEyiuYWvAoux8=,tag:60f9JhyYl4s+Q1SMAapfow==,type:str]
          port: ENC[AES256_GCM,data:uYTI/w==,iv:QQYvi6j4FG/N8eabPw5omAxAksUe0XbCgoIt9knisBE=,tag:6zhomqDG2X+7TCxglhBFGg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZnlPMlVZTUhucitaTzR3
            ZmU2QVhSR0NGVlRZRXZiK01JSUdvVktpNUNzCnYyUnJjQThyNTgydDBmWVdxa1RS
            ZFlvbG1uTE9KdVIzd25lV2JRL0orMGMKLS0tIHp3LzJKdUtqNGQzemJLTGJDVlF3
            eUN3WUFWbjZyZmE2ZXdNUXRqNUwwa0UKLYWEr6XoLzjrrZBcjkO9M+p2uZ5p9cn2
            QXskBIechlZjFo9rQMat9X4XBfC3vCU8PkLKqJMOfqiKDR5EGbD26w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:XubNtrSRi022Kx8X/PRPhh9F840MnOzQRtz4oHY7o3/PmFYy6ZDqg68UOu5BgqRPJTMmvjzJ2HBy6hSWDLbf5IEZX92VgJbxm907X4PUVNIiXrp3x9QzufR/GWyXpnWdJjJbomFCnPuAJuSGQKdkQS70OUOcnU8Iz6O03MrbTPs=,iv:9Ym5kr/pSPhUsNLSytHl/bHceBqiM8Rpca0JM3aG8uE=,tag:+n5ttlsvF/1qmUHFyriBqw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
