apiVersion: ENC[AES256_GCM,data:Gbo=,iv:g3j8MfHXBjx/HvnKGp2+STV8oH4XFwX0e//QezNh3A4=,tag:+1GFV8fjTvnvhp541pe3jw==,type:str]
kind: ENC[AES256_GCM,data:7fPmXDMgxA==,iv:Ku16ngCBgdOcVpycPQo0+ccYNARYaL46YTtaqGo3Ca0=,tag:Pifqy90mVIugXgFJ/YRqDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TQ7tyD9q4+3wjQ==,iv:AAlst6/2z2LxzDqVVUDDCuuWaYE1L0kJQXayJRtFv1k=,tag:DQBJ9Z0UFy2CD/L2hcIGew==,type:str]
    namespace: ENC[AES256_GCM,data:t8qH9HpCAOhH00nxSrUU+EQ=,iv:dbwPdw390OVLqdndvK6gPBWMEI+rSCWFgoma/KQr7PA=,tag:U47/25RVo4xD6dBOLWLZvg==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:0/w+hg==,iv:wUoP9NLnAYiN24SEPwJc1QXhoI58f46Zsvd2sey9R48=,tag:+y+8GYtlgqgfa7JPUgGShQ==,type:str]
          port: ENC[AES256_GCM,data:H6bcHg==,iv:ry1/k0Z85Bxel4k+/NSkQIM4J6nQt3KmHdPl2Qommsw=,tag:7QwfrKyYgcGKj520vraBJA==,type:int]
          targetPort: ENC[AES256_GCM,data:NBaAwA==,iv:0ijTG8Gb6+yyiEtduJTMEcqeJA1Ra6/owGCM2H9NjWQ=,tag:mHsFHXnmM6Sz+zZepS1mkA==,type:int]
    clusterIP: ENC[AES256_GCM,data:Gp0ngQ==,iv:hkOkbjcl97X0Rd5Gd/QUg8la+LnykpmaOhSmZSMCYL4=,tag:Q+5BD+agRsJIstqF+0lM0A==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTWtiRDBvQ0RiOWE1WFQ5
            ekNvY2V2ekppZmdpeXdRYm5YYmE4aWUyMjJJCmZja2ZqczZNWmc0b1c1U2lRWGt6
            ek1RMkh2OVE0a2luSld6Tnl5NU1ZbGsKLS0tIE81bDViNU4yMnoxUkJwQXdBT1ZH
            eDU1cEg3T1Q3c0tVTDFxalRVTnBaQVUK1Bbar+j0lVOUy2VE3iDtrSeT1B1kSEVm
            tzx5FdwaWUyr4JgPOTV5sa4lL4NY3X7dC+WfeQUe9OrZLgtUoUM88Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:Jj5RwBAsUfTJuWnMzklZ1sbdEYRdQ2Url5+hsybi3flNTx+oUFs9W6ItkjUkpL0+VSF9LRaBo9wD6R0sNcDMBXgDYG3rBAqkBdujQBxSLtnK/hof5p8ouUXt2+rukvsn3pG7RGPMVwXfpXNFtZLGc3n/p9f1yVnZVkxEqxcEn7A=,iv:Jgs5GscO58WeEiLex0vu/M7KJQNd1KpYjaGi4CemBBs=,tag:ryuoVomiGwkzIkrTdBfrVQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:IJI=,iv:wBfw32/1dxMRreT8vmXGCllr80eohOiaFAbGbi9i2Jc=,tag:Bd36YbSP3TbQw+OsX0Mngw==,type:str]
kind: ENC[AES256_GCM,data:OtheJLNV/Cdv,iv:rCI3TTtPR3mE7KoYsNT+mNA8xKcopiWiz1ZKvFQADSI=,tag:PvVCV9coLaj6KN5Bbc7S6A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KzLcJa4K7LOmNA==,iv:R7GdAgYgweBQoVYUi9+S4sCkzzQHA9+Fqg2blB+SR44=,tag:E8li6SJ6KCpzJ7dRShXuYg==,type:str]
    namespace: ENC[AES256_GCM,data:fZZtjLtND21ZFdzAeaXtatE=,iv:BFoj5rO+f13uBsTjr/MWOwcb3Zx+DjNaO69luTUV9k0=,tag:XjA8sqa8f/hd0/edj2w3fw==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:Z0So98UU99WY5g==,iv:xwBFzgj4dWPa0/I04cDjvIe+0bsR5oVnXKQoYVlAb6o=,tag:pEzxwNnE36/zS6JwFJ6AQw==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:BG8idw==,iv:/ohoz3pcwnXIdQw+hMBz0dJUNVhjD1GVvYx/RzVw8Mw=,tag:7m/tUknJkPfU823jTfT84g==,type:str]
          port: ENC[AES256_GCM,data:sbLL9A==,iv:mwngwiNdmWbOlbNiqYC5iPS7tlZoF/M+i32FdHvcahQ=,tag:gGRbn3XtHNpDlFmg1l+Kxw==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTWtiRDBvQ0RiOWE1WFQ5
            ekNvY2V2ekppZmdpeXdRYm5YYmE4aWUyMjJJCmZja2ZqczZNWmc0b1c1U2lRWGt6
            ek1RMkh2OVE0a2luSld6Tnl5NU1ZbGsKLS0tIE81bDViNU4yMnoxUkJwQXdBT1ZH
            eDU1cEg3T1Q3c0tVTDFxalRVTnBaQVUK1Bbar+j0lVOUy2VE3iDtrSeT1B1kSEVm
            tzx5FdwaWUyr4JgPOTV5sa4lL4NY3X7dC+WfeQUe9OrZLgtUoUM88Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:47:39Z"
    mac: ENC[AES256_GCM,data:Jj5RwBAsUfTJuWnMzklZ1sbdEYRdQ2Url5+hsybi3flNTx+oUFs9W6ItkjUkpL0+VSF9LRaBo9wD6R0sNcDMBXgDYG3rBAqkBdujQBxSLtnK/hof5p8ouUXt2+rukvsn3pG7RGPMVwXfpXNFtZLGc3n/p9f1yVnZVkxEqxcEn7A=,iv:Jgs5GscO58WeEiLex0vu/M7KJQNd1KpYjaGi4CemBBs=,tag:ryuoVomiGwkzIkrTdBfrVQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
