apiVersion: ENC[AES256_GCM,data:+r8=,iv:xpc09OgNu3y5aqZQI5wmQ9Rcz1WJPBgg6D8eVCog7T0=,tag:rbQxO3Im05DKFx2tYt/Ypw==,type:str]
kind: ENC[AES256_GCM,data:RLrpaiw4vw==,iv:2HoCYNlhFP9Gygio38iyQXZfHZ2Ggu2IppetzICqWco=,tag:CnnyPmDc93rtjscy+6ZhpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mXew/WqMd28=,iv:uL8S3zaKTnCJGw1k7cWEAOQ4x1m5ONuKjpnjSLP8wPI=,tag:3xe13RKtW66rlJ0lcdxWbg==,type:str]
    namespace: ENC[AES256_GCM,data:esdq/SiKzUCd0DLVLuf90IA=,iv:n2Va+j1Oh2w4cpba0Id9eUDGFph5mpIx3mQkU+3JKPY=,tag:vwlLj2AYNNBk9+wrwnSsKA==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:DaxqZIg=,iv:dJ+QsGwRvWbW+uA7PL9T2IEm3xyDe6FkUSF6yxS5sVs=,tag:bPrMZdgwwWuGkigApNwrtQ==,type:str]
          port: ENC[AES256_GCM,data:Yty/xI4=,iv:xmQbcpGeh3dCGZrSD8vhsbSL2HKMhnxk8V0T5l4dSNE=,tag:Vy8XAXMiGu+IQDzQ72hExg==,type:int]
          targetPort: ENC[AES256_GCM,data:THJeDJQ=,iv:sOale0yAXnnnvCNwr4HaiHJl2GCh0CRLxGSOhN2oAYc=,tag:NvGoX1oRmN3h1t6BxIeG4w==,type:int]
    clusterIP: ENC[AES256_GCM,data:THaY6w==,iv:OzBIysjWcwQ4Y4VbfQjz9khZTjTVMSJeFrDccjqnBOw=,tag:QncBEjFCaXIczPP0/FW3JA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMGR0Tkg4eGNja2NZZ2hY
            TUI4b1RBekxlamZ2dnhnQWI3S01ua0wrblZJCkZSUWxoZG5nRkFXL1Rjek1wNVlL
            bjFLYW5OOHFSSEVMUFR0dTFOazk5NmMKLS0tIE42cjFPOE5yeE1yRmVrcTNkRzFl
            d3VEUWJWNXhDSnk1YXU5cXRZYUI3Y00K+TuT3upv77SBNfyf/Wh7+/P4rxV05XhE
            /gVVZCVcd35rEDWsnMvNLjDnDjWdJBY3rJ8nqehOJmHiMtcAGkCc7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:22:04Z"
    mac: ENC[AES256_GCM,data:UBtp3z27DocC8sKZMX65NVR5ScIXYfpWMu70SxB7F57I3bmpv24ZjIQYT/fF/hT7KLoeIHYXRzwB/S0lzpWm6IsECXVxh35RGA0myZeUZlBpVWMn/ViYd4ur31g7JdG3D87+WSyOuwkqNC/gNJjqXhar6e0EDPUHCZYZuIryDO8=,iv:OodZTy8a5/nsOfnZy2teXgzZIFLve77Q5XLnRarvfCs=,tag:dm35KSkUAqxIUpN/vz9slg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
