apiVersion: ENC[AES256_GCM,data:2Vc=,iv:IFza8Xl8qwACno77qkXgVc88RDwUn5Ew/am/U6pYpAg=,tag:gk5eDmmF4kUS+76UQnCbfg==,type:str]
kind: ENC[AES256_GCM,data:bhcxUnt5hQ==,iv:L/SP86AoorOx8YYRv4Gg3XxtubyGZp7APCalAOHtA60=,tag:RgameA5Ejb7y0ez1IdVjgg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8B2e2QOUqQ==,iv:7za5ZvEzSnHxGoHPg9LvFqoABcsrm4R3xODcF6tPcH8=,tag:oQaPMgbuFL+HVg/+Rpzqhg==,type:str]
    namespace: ENC[AES256_GCM,data:+bnqRb1SJb31xtZdZHG58MY=,iv:M/BRNuIB7H+jTT2STHgajndPMYE0BZtwMWMfYs2FjNU=,tag:jEbblaLziBE+wuO5l7O2rw==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:a0Nvzw==,iv:fGyDA4AaIY8QExZe3u5qkz3LjPbQGpnnB/27RbciiVQ=,tag:3pF2XVpzZf0yjKQOqPPiEw==,type:str]
          port: ENC[AES256_GCM,data:E0IH4A==,iv:Y+1p0lGAjIpnxnG1S6f4d7xDvoXUeXuVqZUWQCNVoLM=,tag:aCl+1KdJVnsty2JUvcjQLA==,type:int]
          targetPort: ENC[AES256_GCM,data:9rVtVA==,iv:UKsmqgfrtoAMSd07gzJqwGwD+9PfYGiwp2oJSeBdTdA=,tag:Mv5lofbW/Z/r49iTkxHgcA==,type:int]
    clusterIP: ENC[AES256_GCM,data:XBCMNA==,iv:HM69kzoRlG0nQ6hiJbhpypyrQdtFJ8smEN5AaPFdOGE=,tag:eT3Pp048l+KsQF8dRswIzg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3hzNHBXRi9xTzQ1Sk5l
            aW41UVAxM3c0TTZCSXp2M3pvQjF5RHVxcDJFCm52d2JGUlluREJMS0ZOL1l6KzhQ
            NDVDVWxQUlVBTXZwVmYyZEdUWkZUQTQKLS0tIFJsRjE5RnlyTXRUMHRmOURaSUZS
            S0VqTVVONk1oNEsvYktETnJsQlR1UFUKkrG9IUq8+wrO6O1qnl+E0/EMIeaE+cKD
            7X8gM2Yb3bRVB3u60LmwXz6E2RiRombP5WHyHTczpDUZirEeXLxACQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:mfOgsFvgXuI2FcwVrHFCAlR+FgwjI41D889O2NObUqp5aWAW3YHNn/qluu3zgphFsDuk1ILuz60YRsb1ydBKEwdh3UElXZxknjTDvgBHrzXQioDRcmbM1AVnmUkmWq8qGclmIGeD5ckE1bsehkw5yD21bw2jn33f/S5ErLlpaZk=,iv:tIy21mxKtgAgu+NXNKSNCE0dCbjf+PGi+MrO7/66f/M=,tag:CQna3JHrXmhIoQyErAvSQQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:nEc=,iv:rI1E6ZxxXz1OAOXH1xqP4ng4hmPNMAvA0hsMDfZ4Oq4=,tag:NeFjCYRdSUVzb8h2n2jZ7w==,type:str]
kind: ENC[AES256_GCM,data:RTEPBJPNajfK,iv:6cLnWREkW/ShYLlDYV3Uryf3w1WQwMoB7eH0KUPcpzc=,tag:NmBfjIc+Ve3wAOF8t964Zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:phrolR6/Ew==,iv:sTr5nI0dp8/pOhB/7xNpPeVY8jnH4BY3psihZYmm3as=,tag:s5/ihhBLw6OCOj/z6QuZEQ==,type:str]
    namespace: ENC[AES256_GCM,data:8v/UvlmduFTxP5QMKMJ5Rx4=,iv:q+RccVKpFJa4SKcuSercrMptzmEGHnNRJVVTx4JUqME=,tag:71fTNjXKurFugDIRCadmJA==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:hr2yDxxmSNzmyzI=,iv:XmyP0l9I7IYxRBKGS8MDDeN90MuOEb7jAHWtQ8LVMrQ=,tag:4Kc7nHaSs7orXxdXbGZOhg==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:Po+Wbw==,iv:HXaRyLPKNi9+jhvcaWWtPlGUoaLrt/iaX+PIVHmhy1Y=,tag:s7b8D5E3SvAweHRXlARpig==,type:str]
          port: ENC[AES256_GCM,data:iAQWBw==,iv:0wRG35fQlROKKIf7iGRXaJRgFe8KA4G6el+5FQui9mE=,tag:uqnXBgCK1yQ/iRf+SkkDdg==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK3hzNHBXRi9xTzQ1Sk5l
            aW41UVAxM3c0TTZCSXp2M3pvQjF5RHVxcDJFCm52d2JGUlluREJMS0ZOL1l6KzhQ
            NDVDVWxQUlVBTXZwVmYyZEdUWkZUQTQKLS0tIFJsRjE5RnlyTXRUMHRmOURaSUZS
            S0VqTVVONk1oNEsvYktETnJsQlR1UFUKkrG9IUq8+wrO6O1qnl+E0/EMIeaE+cKD
            7X8gM2Yb3bRVB3u60LmwXz6E2RiRombP5WHyHTczpDUZirEeXLxACQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:mfOgsFvgXuI2FcwVrHFCAlR+FgwjI41D889O2NObUqp5aWAW3YHNn/qluu3zgphFsDuk1ILuz60YRsb1ydBKEwdh3UElXZxknjTDvgBHrzXQioDRcmbM1AVnmUkmWq8qGclmIGeD5ckE1bsehkw5yD21bw2jn33f/S5ErLlpaZk=,iv:tIy21mxKtgAgu+NXNKSNCE0dCbjf+PGi+MrO7/66f/M=,tag:CQna3JHrXmhIoQyErAvSQQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
