apiVersion: ENC[AES256_GCM,data:qnk=,iv:p/BpaV5k2Y4qb8VigwhLo+PxX4ENnXBXssXTKdvODR4=,tag:lLd+dtsp3+7lrUbW87IQvQ==,type:str]
kind: ENC[AES256_GCM,data:/r+bfpEqRw==,iv:0JF1mnbAYLPAC24QT+RU/GSNeZbur7V6WRuoO0rYwro=,tag:M7a3cvyLoT8hg3FnA0WHjg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GZj3uj7i2g==,iv:uTOv/oGbSW658csRVb/MFuS/cbTrEHLEcZeF7Hj2Mig=,tag:iWmhasVtISTAk97raiEJrA==,type:str]
    namespace: ENC[AES256_GCM,data:gjT5k2qOECa3igeVoWprwLk=,iv:heAMIRtMBYb5doTTR0wa61H//z8hY/xceXf+3w2MsbQ=,tag:Pt6jKR91qlrIOz4a8R9r0g==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:QmG2Ow==,iv:VRX4ekmULk5Qs7z5yCot3zBxfkdURCawNfgddy3Wxq8=,tag:TBx1SfDZWiVmMUfCw2H5PA==,type:str]
          port: ENC[AES256_GCM,data:6XSybw==,iv:Ir4sNWAJEpg1mPqnxv/2MZTChLSOOsThCdNIQeX47CU=,tag:69lQgH0TMYfHZynH2UuUzA==,type:int]
          targetPort: ENC[AES256_GCM,data:TzFFSQ==,iv:WRlPUyF2szU5IPf5S4Dl1Q2u+9gQEpl4iGSgP4hq57o=,tag:8vTkOLCSh+mE8JH9QCl9+g==,type:int]
    clusterIP: ENC[AES256_GCM,data:bbqs3w==,iv:6AmgsLpI1t/yVJuBZWxCfwHtzXXZCk1/4Z8SOZHGhH0=,tag:+tBlGMxwtptFVYkWVwTg7w==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QksrbytKZ0VjcnFyU2Jy
            YS9PNmdwNFB4MHBRTTNBQmU2QUN4QWUwalFZCmVuUlpUQ3dqQ3BienB0QXVCRnZw
            Umtid2pIYXFSb2R4dHRTeTJ1MXBRVVkKLS0tIEVYRnRnSnZBZEFNQkh2T2s5Q2R3
            WGpBQUJpaXJ1UlovekpBN1E0Um5uOXcK7PpL95Sldyh9oTS+mTV3nHO2ejeCEWZR
            GELXL76rryvTDF6dNCEETOhs6RjIH7iyOrRZwqx7Fqn06/rpyerCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:nCFPESNzoFJ+zZ5uXQet7UKTQMqqAjYmqt2ig0hgn4W3dDBXEN+3pECHL7+7IfWBuU03Gy41F89lM6GlhQRQRHZGYPCPVAwVal/0e5xHsMvvXDwj4BnDEggeMjgfWpHqhq3SRxv94Fgo5xIqV+lCB69G16gmEc/vHpnxrCwUpxg=,iv:oqm4QWoR1IYz9Cw/s0L+jwfcjCVZDS8g95fKt0H1p0Y=,tag:tnlja7zaD7K6ADxf87ASZw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:94g=,iv:OagHWnOxXOEq8ZGj5xA734U4QeyQUv46BbGzvTLx4LY=,tag:Ai2Xeo2+NrKeszrLQdePSg==,type:str]
kind: ENC[AES256_GCM,data:g5Apbcile4sQ,iv:UMj+WV46hCZPctncKKPTlqOHop63CdScXM7kmqKMWok=,tag:wQecRHanKVuCXBnaijyiHQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xT54DjbxWw==,iv:91PqwKDGLAYq+NwrHxmrAO15bolinrlaGy3ragT9OJ4=,tag:fX/2EQrxbK4vRW+msgjyuQ==,type:str]
    namespace: ENC[AES256_GCM,data:vjLHKujzEfSYhddtk8SEc2Q=,iv:+ita2R5NcXvn2MPaw0393pxrQzYjFtANBqsHUaCV++g=,tag:ikUn+0nGdRZjnCSP+h9Uqg==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:yNDnmWXx9SaWOkI=,iv:9uYh0UJOQ2qKmTxeWz12NU0dsvm+rNlmmdmFSv8QRVM=,tag:e6TWc6HFpz7dL+O389jazg==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:MFtxWg==,iv:csKPJEtZJXNsHLmmcz55DdeAOVLHa77yLQe/2JGQxv8=,tag:wCQiiXuA1Aq8O5XjqE8HAA==,type:str]
          port: ENC[AES256_GCM,data:s7zwHg==,iv:sm9i3piLLkmcH6Bx2z3TrRMM0tIDGJrUQ4JtwvRhexA=,tag:jEYk3CO+Ze10xz0GVerwUQ==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QksrbytKZ0VjcnFyU2Jy
            YS9PNmdwNFB4MHBRTTNBQmU2QUN4QWUwalFZCmVuUlpUQ3dqQ3BienB0QXVCRnZw
            Umtid2pIYXFSb2R4dHRTeTJ1MXBRVVkKLS0tIEVYRnRnSnZBZEFNQkh2T2s5Q2R3
            WGpBQUJpaXJ1UlovekpBN1E0Um5uOXcK7PpL95Sldyh9oTS+mTV3nHO2ejeCEWZR
            GELXL76rryvTDF6dNCEETOhs6RjIH7iyOrRZwqx7Fqn06/rpyerCpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:nCFPESNzoFJ+zZ5uXQet7UKTQMqqAjYmqt2ig0hgn4W3dDBXEN+3pECHL7+7IfWBuU03Gy41F89lM6GlhQRQRHZGYPCPVAwVal/0e5xHsMvvXDwj4BnDEggeMjgfWpHqhq3SRxv94Fgo5xIqV+lCB69G16gmEc/vHpnxrCwUpxg=,iv:oqm4QWoR1IYz9Cw/s0L+jwfcjCVZDS8g95fKt0H1p0Y=,tag:tnlja7zaD7K6ADxf87ASZw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
