apiVersion: ENC[AES256_GCM,data:G0E=,iv:0MI4RDzfdw6hr/+VrC11usyK/ENdTkdthjDLmXgrSEc=,tag:yDzKAuPI5XoDiJAA5+0FpQ==,type:str]
kind: ENC[AES256_GCM,data:dcOElJT+Lw==,iv:fUuYM3SIouzk3NulS9aAQK0Ns40voSlEByBhbNjvy5o=,tag:7o95MX2ittIf/kgrq8tHUA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gzps,iv:2OkHJsEakxdJcaj7nktI11egaqeKgMEW0qY4zQpRKV4=,tag:ygSqK8j7CnDAwzzR68CvwA==,type:str]
    namespace: ENC[AES256_GCM,data:HYBt8thW1kT8dUL1hps0oNc=,iv:NvoYgvvX9FqKQSJfwY1uiBMnAR3ze4ssOmyTEwEs1Bc=,tag:2qQoWNuD4E6gLBDQKhnomw==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:ivehtQ==,iv:1T9oZ8TSwk10y+Yl1lpq5Cet5JMCZhYqyJdi5Oz9VLU=,tag:Br7Xhkr2whu8H0H0TyaCJQ==,type:str]
          port: ENC[AES256_GCM,data:e8TicQ==,iv:e2+oHLXja+8bWU5Ozzr65F8k7P2JybKdD7uOZ32TJe8=,tag:hqTYUZfT2CFcL35sXzF42Q==,type:int]
          targetPort: ENC[AES256_GCM,data:2L/VYw==,iv:Z2ZIYqeed4Gcma54b42aoRFcftYvHxbOZaXuYxOAXC4=,tag:/1CaN8945COWarbIUWsTaA==,type:int]
    clusterIP: ENC[AES256_GCM,data:PdcYoQ==,iv:H7wKt0z/Nziy0Mt8Q1vksljfXsRWJqiA1u+f/CvkcIw=,tag:y29itsBBz/W9kHzLqvzqaw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Mzk3V1N1dzdsbjlIekxN
            NW91WkZNM2xCcEhCMzJ2aTZXS0ZXSWVsdkdNCmxLbjR2TEQ3K1JjUW5DUURrRTVt
            dTFlN3VPWUVJYUFVNmtRTVVhaTZtYTQKLS0tIHQwUlo0aGlWT2I3UG9JQW45anlL
            VFBLV2NYSGdnaXNFWlJxMEpxTVk2NjAKMe0CewzA7BdlYkipDMDCZJEVAVoDiwRt
            divOScf2k5dh8jdu0JH594jVY5EGAy4IObcs640Wl71uCnnfZ9j2sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:M1S57eSGih8Ehjxy7gXA1c5KNFzjwo4ZnF1+6OabpwzRqOnjkzTq2a2H4ykMCYgPeTBxGYi2pQb3B73cyaeaOdxVnm+VvpFmuxYkwCPOvqHPZjZT+HqmWTyWEVNuaAlRk/HsTmCHiOnT/ELMTR3sSYXemBJ6bjW1h3pEOIbTDpw=,iv:vE26u49q5pytLvJVro6/BWGeW1NF7giJMBpwSHmtT8I=,tag:Lmyx+pZRCgbx1N0F9oNwIQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
