apiVersion: ENC[AES256_GCM,data:6gk=,iv:Y3Ccl2L0dBV+kfMTtn4o45D52/cbrMX/LBVs6s51Dd4=,tag:gO5Qw5zWWXHBLAOkaa1Lpg==,type:str]
kind: ENC[AES256_GCM,data:Hl5D4WKemg==,iv:qfZhheT9A1j6AU6eLL/cJ5mmpZBFiO4bvgM7R0XMIS0=,tag:T3LKyYUeIzKsD29IvJ3L+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9oPL08RXmg80dwo=,iv:Ud+0/SDHxCO0yRmNxUDZwtge0KYOR6Pi5EBfVffto/g=,tag:K6zpNuhnAqsjMQIKD3Oh4g==,type:str]
    namespace: ENC[AES256_GCM,data:j3dHU9US8WeGBVrQ4dQ0A9I=,iv:mKhKp42R88PyS3RcLR6bZvqONex97JIoOsBgylinOBc=,tag:mFhtCzeojJcXBvxFk1S1iQ==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:OKeFKQ==,iv:J3EPtaQxKO37+PPNMu8qY05Q0/eWe1+rUBYpN2CKDWo=,tag:uYKGYR/F5ci++eNUtTZ2wg==,type:str]
          port: ENC[AES256_GCM,data:hsalTg==,iv:hW53vZTxurS2SoI/QlVJ391WLfLGqWNFEKRwmOCPWts=,tag:DRtYU2J6KGZuZCcolV51/Q==,type:int]
          targetPort: ENC[AES256_GCM,data:ePmv+A==,iv:ZUXhDBUHlo5OuVMBCQ2ycryPjt0aRx7SJP3+R1xU9sc=,tag:/q36sKuprGF43CgM2HXHKA==,type:int]
    clusterIP: ENC[AES256_GCM,data:K0JTTA==,iv:f2WhViaIPn0XQPLtjAoK1BzkWOuhlL76GYxp8xvlrlM=,tag:Hj2zonyRUulqrixNofG4pw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTmREQVcwdGNJc0hSQ3pq
            QkM4T2pTc3VBbFVVM2doTzU1REtYWnErVXdrClVlOEtVVmRrUSs0YUswZStuQk02
            V25jZk5ReWFOT1Y0MGQ5Vkl1elBKOVUKLS0tIDM3dkZvWlo1SWRsV1JqcjFTZjhj
            dkNHSE4zWUdrOHE4WlpuTUlKZWxCRUEKwFZHP8sLgVYLg8gEJ7mQ8CVeT8D0Mbm0
            VqgY2ej8y7QuQWf9rhslv4tXJnj0JgjrVBJYG8Dt6gsQ0nL9poOYfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:53gMFF+RKT5iylD/Of9BFDDRxJzZtat/lB7YsRyN3IWtF3yRLvkEI4qSS2fxQpB4N/w4dhJkYVrAOBvqZHjoG8FWzHdxsp3WgbgbCLbAUCuYWz44XWAbzM9tia2L1sjZAj1YqpmL3nJPINTF/UT/aTiKa0pyCd1f4DlKplhYva4=,iv:/gQE2KoGzqktB5IGPMBgymH+ZZ9AyxEpxje1tr5Hen4=,tag:Ihg015XnMBe5KNlBD0Lhwg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:YpU=,iv:wX2rpT8i+J3hFQv79zn1OIniX3xFvUutjciernawXts=,tag:eJQKvy1COHz15B2K43La9g==,type:str]
kind: ENC[AES256_GCM,data:FgGn1Np43Rgl,iv:mZtz/2MBSyVkpI4IZvbc4FjwhD24XSO7qEIBDKRdV60=,tag:h66PBWIs9EjBYpXPDjRnAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7xhq9vF9v13Clpk=,iv:aEr4/4duDSjGEwBytPAUYREAwIdlx9A87OAoC2Jv4q4=,tag:m8cpH2lU9oSEFRnTNTMJIA==,type:str]
    namespace: ENC[AES256_GCM,data:xQkimf2LFxIgaPIa2sRjjQ4=,iv:VkRCOhp6hgsKe+N5b4O4urzUjNB/UzKd50JKlYGgxq0=,tag:c0L1Sp/czvvfeWmEucCG3Q==,type:str]
subsets:
    - addresses:
        - ip: ENC[AES256_GCM,data:xBMI50mJGJEPT9c=,iv:IYfHAT+mBdJG9alrdLy7DRN/0LQq6qgk2neQCsZEk8c=,tag:hMj6gfvAFbuXvjnSayTccQ==,type:str]
      ports:
        - name: ENC[AES256_GCM,data:am5Lng==,iv:N02kE6s7/mbnzdpEEuvJ/VdoCYDjuvX6xgFL7NF8rwU=,tag:Ol3FYA5wR9mCdkOuW+SULA==,type:str]
          port: ENC[AES256_GCM,data:j9Q05A==,iv:0pmSRZa7Xpe35n/O55UKsEX2qdcejP+JRuinmrid1gg=,tag:jIkp3utIx80XqpTD093G4w==,type:int]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTmREQVcwdGNJc0hSQ3pq
            QkM4T2pTc3VBbFVVM2doTzU1REtYWnErVXdrClVlOEtVVmRrUSs0YUswZStuQk02
            V25jZk5ReWFOT1Y0MGQ5Vkl1elBKOVUKLS0tIDM3dkZvWlo1SWRsV1JqcjFTZjhj
            dkNHSE4zWUdrOHE4WlpuTUlKZWxCRUEKwFZHP8sLgVYLg8gEJ7mQ8CVeT8D0Mbm0
            VqgY2ej8y7QuQWf9rhslv4tXJnj0JgjrVBJYG8Dt6gsQ0nL9poOYfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T05:43:13Z"
    mac: ENC[AES256_GCM,data:53gMFF+RKT5iylD/Of9BFDDRxJzZtat/lB7YsRyN3IWtF3yRLvkEI4qSS2fxQpB4N/w4dhJkYVrAOBvqZHjoG8FWzHdxsp3WgbgbCLbAUCuYWz44XWAbzM9tia2L1sjZAj1YqpmL3nJPINTF/UT/aTiKa0pyCd1f4DlKplhYva4=,iv:/gQE2KoGzqktB5IGPMBgymH+ZZ9AyxEpxje1tr5Hen4=,tag:Ihg015XnMBe5KNlBD0Lhwg==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
