apiVersion: ENC[AES256_GCM,data:f6A=,iv:QTCOrSsCuX1a5fptT94o0DAW2BfmAR/fFWHvgG8GwQU=,tag:1TqPZzIXt4CWTGs7Jweo3w==,type:str]
kind: ENC[AES256_GCM,data:M7w/KsnZgQ==,iv:x2Cz68+LXzNycc06rI1wNlrLEtDfmr+4EAXIbJa10ug=,tag:riXbGEPipVixtP7msmC5+Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UjyiDQ==,iv:PbyhkPNyQAF2eeg9oKPOqBY278W588fGUNmpDuUhiQU=,tag:gws1K+ebpdOKQ12c5rf0Ow==,type:str]
    namespace: ENC[AES256_GCM,data:EBTbzYlIHEPvm+KYGRD32aM=,iv:z6MK6kknH2OILklGUponxDTFvKc0sI0eOrZ74b3IKz4=,tag:+as4jbyRhAqqCLNDtlHM2A==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:B6oMZA==,iv:DrS2VGX8lyflaFPNV8Pv23zNUuSGJiuWLi7ljPrXSZg=,tag:xis/3TmcY998WFa+WquGhg==,type:str]
          port: ENC[AES256_GCM,data:AIVoEA==,iv:eBSQAexwUUufVAiCAYuJ+sg4eDpuiPHkV4bSg4jkunw=,tag:+EQc77Fe2JSt4d6/gvdt1Q==,type:int]
          targetPort: ENC[AES256_GCM,data:16sQZw==,iv:SyEHiJIdGBA7hJOh3mFExlhjAUo7eu/LOLXLnPsRKps=,tag:/GTuMQbDBYiGHt84NJtjFw==,type:int]
    clusterIP: ENC[AES256_GCM,data:0Afy6Q==,iv:aMVU05uGcykdXDAZHsjvYXneCtTQe9oOZVm6Y1Hl1OI=,tag:vQSmTqhvdILuSgJNpOJ0Hw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuc3ZmNENSYkttU0lUQmdk
            VHNqbjJRWWkyaVI4YW0zQUF6b3RoUUdzemcwCnBUYVNxWStmeXorNFdVcWZSUkN5
            MmdtVEovdkNnTFJ3WDNUempkQTRDTTAKLS0tICt4MnpKcnJRSnVWTnFLeG1LVXFC
            N3I5bFFURldWTnZNaUU5NlViQk8vUE0KBkmx1Kzx5WFvd+fIrv8tz5WTbd9P7LTa
            QCa7JK34WS2iFJqU1uZ8AMJE/V5h3U4tbH63sNMlAzy1BHXJoJSx8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:21Z"
    mac: ENC[AES256_GCM,data:n7EBTwHiYwqgEmj6xXfYcprak07bbY+9KAbh4IyRKlC+0mppsy2XPrFnQ6hE+akUjbCZaSVIBhB6y+FXjV5pTdltXIt9V0ZbVropKjmxL113I6KjY4Dex9ibumaO93Pyqrm/vTukmNi2DpQXdcQXfqbKQciMiiPZTyQGKLEj//Y=,iv:pesJCxUyB6on+w5iZmGXQi5+2JbREpATYBGZ7f4iC6s=,tag:m03zBY6xk8h5ZKEch+ZpHw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
