apiVersion: ENC[AES256_GCM,data:o+w=,iv:W3m3/0kN2dTE/gumv/fBRzIYyEAmoEQfUhsgeJyQj+k=,tag:fpIhanbAJE9+EO4vI6SS9A==,type:str]
kind: ENC[AES256_GCM,data:o2E48LPSvw==,iv:9UwzVeybe999gVBBiGTqGI3VZnQBGWVpGV5kcusfkCU=,tag:4FUZi9BGcJInlraIJ9oM1Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mE9/Eg==,iv:TSVi0bgNkxRyDGAwWAZiCBaKbOPggFbidhubGKO23yg=,tag:xO1wxATtvBkp1xUtKcpSnA==,type:str]
    namespace: ENC[AES256_GCM,data:M8Z0+uQ4qCauYuYHDedxuQ0=,iv:52cGBPN2bcn9AW+igW0BKTXIf/HselwM0/4KkVToXLQ=,tag:YhGTUFXYtqJsTO64jcnGNw==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:EtnfzQ==,iv:Mph1+MwsJVoz2RbRtOkXOoDKZSyCtogstXM7eMT2eAw=,tag:VWaS8qh9Dxx8cSmys6k/vA==,type:str]
          port: ENC[AES256_GCM,data:1wV4Kg==,iv:1FWNImAh2WZYdlX7UgyvFUHukXDjg3EoYQ+dE2yp3KU=,tag:xRB/5fTCdxR824y1dxCcIQ==,type:int]
          targetPort: ENC[AES256_GCM,data:ftI9WA==,iv:7vLbsSC3E5NSZuKT8+xkmT2a/kFOPk6r/n+EIwnDR1Q=,tag:j01REmKAEDzzIRVPV3Ykjw==,type:int]
    clusterIP: ENC[AES256_GCM,data:0zNuKg==,iv:fCQ4awT6UNhbtnDtdRdrph4O8tM150ki/3mrT1Tcl3k=,tag:aCug6IVkSHfi8f4OwW1LmQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRmNUZzgxUGUvS0ljU1gy
            MVVGODRjK3R5UExNcW53ZSs3OVNYNXR1eGpNClhNdlN0TnNMNjV5YW1BcHMvVU9D
            cUhRc2ZlUnB4aWgyRHB3YWNnVjhwRGcKLS0tIDhPZ2JheXhVWHRrT0pUNmd4MERJ
            aWpmaUh2S2E5SzMwZjNwM2JTN2l5d0UKfuiLmLyx/5IxITALYpc+3ekjkars7j4S
            3H2+y8eLJskxCAqzbamjMAO/Epv6APogPkb0mXmXMhClvQiZlYVyEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:MO/7lYXwv9Y5nGW6MtAZ2vHdlY3S0N/MHHm5CN04dka2K2f5PCLa7k/mXhPK/eUKEKVgMP37LUlPy4I4LTIvlZN5isSmsS/lZ7J3NcWhQPcqUyvKE5HOS0sVGBvXKQvxCF3KaVNE3rJEV992V6ryXIMgsYz3JUy9EgCSb6lXjIo=,iv:aYHktrpuOWV/VHDgrqeOBvbnpp75/LsZ5nHkwhpi12M=,tag:bTdMnSShl/CngcONbbSmvw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
