apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: hub
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:+/QEMw358DqPlC983lvvwyTQT6y1w4A22ad53BVarpQEfC7mRp5QHx69kv9eRNMfga3WdPDq+TjQLMFEDL3rEg+ldFVIHghMLnSedRMrDlkzKKyo95yPUNVEBQEcA2SyWfwDyMXqd2keJIkuBGVrCegAyLGyRHnzyL/auKh6+YeLy21kI0H4guLSP/rEIslWu+6ZCX1M3Jf5Bzpo/sa82o71yFkc3gJ+uNTaQhB+5cYVy47PVzN9+WYWL2IrUk+o,iv:n2QsfPTVIO+K1UpsUwoTHXCTxLpt9Z6zlnjJfpMqY6c=,tag:HsuBH2wiNUkp0ljJRDZiPA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ3E3R1ZZVGc4UWJkbGtN
            M2VKTW1iRWJnMCt4a0QydWtPbUZJMENSUGlJCmpBL0dmTlpiNVdUQnZKTlJMY0U3
            R04reHZsVEhjTjdWNUNZQUJ0bERZS0EKLS0tIExEdkZzbGdndThRR2d5N0RkWFJT
            RU1WZStUQ2lJWGMxc3ZDQUVVbGROUUkKkYgpfHQtuqiJ8mZUnmehoqhu6ZjgLZq/
            oAcsHO8fFOYv9r+fSruPdYu4iROhgwRRU2LbqgO1rPx939RXTNiXoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T20:25:11Z"
    mac: ENC[AES256_GCM,data:u6BTYMB/p+iC31eVRxTZLE11T2oGZh/bgUa9k+ukxirUUJyYFQxtVVWJxv8sqUgt7flyIRetI4YvE01ShWXTdRno9YWxSxY/B5G/4AeahPCLRB7tT4OiqzJN7cDOsj7NpH5sj/Y9DYpf+pOcNqjtZPAerlP/zIKawpd6/sxjz0c=,iv:Emj/zMaKxP0KeMGWi6rtZxt+/HW4fTynW4zUEvOdEtA=,tag:KjHCPG9uFsnkps89hvpFFA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
