apiVersion: v1
kind: Secret
metadata:
    name: monica-mcp-env
    namespace: monica-mcp
type: Opaque
stringData:
    #ENC[AES256_GCM,data:943L+u4o1QP0moZyRcJ7ia/R9uGJQUpL4wSVtUDie7lb3jmw5LsCGgFpyGUnDa9Wu8G5Id8u7m/C2e/Sqderyjry53++veHCV+iYOO1h08PqME4e,iv:lcVuN6YgMbVN0t7k088m9OObWGgAMXP5Uc8bDWfOACY=,tag:7AJ5Zc7o5lkjA8QilrJT8A==,type:comment]
    MONICA_EMAIL: ENC[AES256_GCM,data:dr5vAmuS0MV0Fojp5LRBhQQXzDzChM0=,iv:sRN8MZDPJ+7meJIFlH20nY2gXKi+tqzhZu+B7xaE+Zk=,tag:TUc9a3AdEN6tpIPeET95Ow==,type:str]
    #ENC[AES256_GCM,data:Rp/oiQpfvrdOerPgNxqsI8ue6XDDvGva5OhwLhNr2AOhHAXKbjTUz6+51A2t4O/XSCZzGIMg1A6uCFpOYLyfQMnt2mY=,iv:q0dq8oaiA4lejN6lCMzWm370OfbSX+vBUr+bbSS8WAU=,tag:yi2tIMwo6zcIrg7OX4wsfw==,type:comment]
    #ENC[AES256_GCM,data:tALsGpCA7xc/I0pNLTmJVb2eJWD/uMMEA+d1mvF/wnPdIK/UWobLIoLp7Nl9IQxRuyzjdffl,iv:ymg5pv3xMQi3eQCCioHbDCb4bLMq+Ia5I+xnKyJdxAg=,tag:7RnKz9583fqq5S30yA//AA==,type:comment]
    MONICA_DAV_TOKEN: ENC[AES256_GCM,data:L7jhz9Hv/pVoJb+zKJYA9dZC5hNW+t8PgAgL1BYeP8PF+lBvSnc/ruYv+EKcWELZy8g=,iv:ne21+tL9y9yDk/m+8YWFMmr89fZsV/Yh2k6Qllby3AM=,tag:xynz1I/jStb3F0q3hnaIhg==,type:str]
    #ENC[AES256_GCM,data:gFNLFGZlwzfvRVWFu/jCozyaa/4KOsX/+SmXxw791nGwv2YJsXTlsmbTSYB2vfpXNNNpuZtrG5dETQ==,iv:DHb4GO6Adok8yjWdwq+Fmai0UOlAI4asvyWXGmJXDmA=,tag:RmbbIs9Msvefr+AtcH/fsg==,type:comment]
    MCP_TOKEN: ENC[AES256_GCM,data:sAUNcay+3Jz927JrKtAtp+t8k8BoA6NH/kTgNrD32TyIBy+3+q/PFcXInQ==,iv:2k3rrg54g+cYvSGK5flRw2rasGBfV3sqkmy8xyrS6EQ=,tag:kg4K1ub28XiRo6N2Qirwiw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS2t2RE0wcno3TmliWkhm
            aHJNbjZwdmdDRWgwc1hlTG5iRHRpbWl6aHdNCjc1dmxhOE9OZzczUkpKRzhoUGRN
            MEMvYUIrOG1tNjA1VzVFMENlOXhtRUkKLS0tIGdNV1l1Z290M3BkcGdHU3ZjZDk0
            T0hFYmVhZ0YyaXVtanBYcDFOaHFOQTQKPktEsCzkn3DX1bAUYPVnbXQR3XWa9Qa8
            CVAJkkC0Z5BrcI5BatZqoVpke8RsZVEarxdThEiw/RilzP8x6GjegA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T04:29:23Z"
    mac: ENC[AES256_GCM,data:QCMtogfzzccQEqgOaVAy+FrVHSOBCIwTjq39eENbDVphNlCnaXgpPZtz12zL4yHpjzDPiP0qgdNhqXmBCOWD0EEwUp46dD8WHriO3oCfwB2e/tl+GbGh+xr7PEBDpcJAerZq9kI4Ao6YGXriDYS5XSnSTzShBOjanWZGvOPadVo=,iv:mKgrHcZt/nDUe1D468GFDIeGKripgqvE091Jj6tLwxI=,tag:lL8vGFx+LvgCCOfcXGNf7Q==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
