apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hgnP0ujNPytHy1k6jhJqAtyTVMCvO9kvZ1vjGBFGVNR9OzVuqPnUGw==,iv:Jr215UOlboYprsV7xYwU5YSEnmub/Jd1Z5XmqzzXVWA=,tag:MV4ntcepGJ1SYRNTZGN9Mw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuM3ZFc1F6K1N5M2NpMTRO
            WGNDTklIdEVsdU9XSENVRjVPUHUrWmVIZndVCmRJRDZXbDV3MWFZa1NIcEhFZXFx
            THZHcnh2NVRzckRuaVBrTlFORTY1UWMKLS0tIHFSS1Q5TW9jcTZnWXB6NkpnWm5F
            QkFjc1ZNcEtmRmYrZTV4NXh6TUNtcm8KPuxQJx70qeakGVsQpOXWCFWagWIS+US7
            iadGij7eQuyBVuzfNqNyy14DS4J+JkH9g0Obmdtjz1EFGC+38NgpoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T05:14:25Z"
    mac: ENC[AES256_GCM,data:KGDcTt0uWXvjxvQdVsY8jLHMJgH/zDNGcNxSufoM49Q24ZW5MnJqsyRqYlHUTiwotOOvL5LM5ZSMpC8OnE8tcxyHFLWhVuNfqcRmFk5frWXv4sZqFXo1+t9P0lnhFPjwdTiyonn4DwLA6L9LXF/e+TriU8yNoRLV178zvGBC2X0=,iv:n7CUOvZ70GSpyG3z6djsaTeDwcg1eOd5HIVzgR6frJQ=,tag:V1ElDyznfdmdVGm7nD4+6w==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
