apiVersion: ENC[AES256_GCM,data:quM=,iv:tAqGmSyy3AMUZQFlipedI1hilYPRE2KL4QFatCyvPVQ=,tag:QstGWqoo92zrKkiY7W17GA==,type:str]
kind: ENC[AES256_GCM,data:F3tncSb9,iv:VYins8Wyts5WvB+XJnmh/3Qxt3qPfSWMH6RqgYXVoJY=,tag:cJM3zA1fnEq5aVyIGg8LQw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P5vlppapnB93W3BN8s4=,iv:0Rr1KY1YdgGkKXKef4Jdftfd16uf8sET/4sYnXg4/gU=,tag:YhQp9ny93HyQf4ENSdeQ5g==,type:str]
    namespace: ENC[AES256_GCM,data:1AZi+Hfi,iv:Z/YiZAOOIIllANL32l60Z27QrbyWBxDucpcmfC+/2vE=,tag:XCRhUyyZY5hhSbyBvMFWnw==,type:str]
type: ENC[AES256_GCM,data:SmmEeBm/,iv:rMVwFnsxevVXHQiw3nRu/LrIDP+D8PkwegWke/4C8Sk=,tag:5aAMvTIdOG8ckkNhRxMupA==,type:str]
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:iJgL6iJbQQk=,iv:8SS0FA1E3sSkEC18rNUXPkCavs0O6QiXKQa9+z9qPjk=,tag:3CCX6N3W8IsSKNMODUxyxQ==,type:str]
    IMMICH_URL: ENC[AES256_GCM,data:pa2tUZo9IleSWjsE2XFmMsk5hCxJUhankv9BZR0hHxT73PJJFAK0Ywa82kWXmWcHs+c=,iv:MPi5NWRbJLv+2ITFdq0x5pEdXsEZFJY7Ft6ORyAOe7Y=,tag:2UCxHdCvB/c1SNdJHmCtwQ==,type:str]
    IMMICH_KEY: ENC[AES256_GCM,data:Foblmrlw50M=,iv:gXsYFWCbd2ocg75MfPeeXTFXFSmOOrdjr5pBZEntqHU=,tag:c3BHnbEEYBCUthua6fLOWg==,type:str]
    AUDIOBOOKSHELF_URL: ENC[AES256_GCM,data:INbzbqyDMtkOGzVShfNztiK7u5prfuJGh4XzrWQsY3I1GX+VttPShvl43DtFIJ/FiEE1/Mwu,iv:6RKrYJ0n11UwiITSnBmuNzo221RXoOox7XpZWj9Pwn8=,tag:B0ZuTRL917z3gQNPUbbQvw==,type:str]
    AUDIOBOOKSHELF_KEY: ENC[AES256_GCM,data:ZwgHlmzfwE8=,iv:5Gid2F9LHsnbq5yKtiWnU2xhUDr7Mhtt+IsmoTZCpvg=,tag:PGiE2O84e6LT/Nht3CNC1A==,type:str]
    TAUTULLI_URL: ENC[AES256_GCM,data:8TTO96TS5z9pNMWikxzzNeZr/sXM1lz6wECcQH4UqIoRHA==,iv:Alvvwy96TDqG1vIhb9PjifiItV5plkPtiKmFhq3xMYk=,tag:m7LOi5Y+A9NmMgVrZByV9Q==,type:str]
    TAUTULLI_API_KEY: ENC[AES256_GCM,data:tjqsCTyz9nM=,iv:nSU4YF5U0jKOePPcOLia6UeZTRtDnlqBdc1Pl+VhmN0=,tag:+dZEXgOZFqfT1wkKuBNc+A==,type:str]
    PLEX_SERVER_ID: ENC[AES256_GCM,data:mYDIgVDIaSg=,iv:xxN/OCEIsTU42xqpcCoR3DlYcINLMsRXUsSA3Y30JTs=,tag:8j7oQTr5WHtadTR/SrO0cg==,type:str]
    TECHNITIUM_URL: ENC[AES256_GCM,data:nc6SGLl52zv72E7GjnlXiUDinwaWSBQAZo94TGN0on7tks504vphnCgvg8g/P9rF2yzJRx/DBA==,iv:foJlCs4rgbO091+nPzglSGqDGFQdzu6fonTO7+ePGgM=,tag:HSjcMHStwIyuIh/GgrJXJQ==,type:str]
    TECHNITIUM_TOKEN: ENC[AES256_GCM,data:qPReeWUde2E=,iv:StYoaVdvbBkEr5XTfty7RqpM6zwkmb80oZpreEU7Ka0=,tag:sMnNbEEKFkLsUpu6I0i9nw==,type:str]
    UPTIME_KUMA_URL: ENC[AES256_GCM,data:5sC24NaobjMOqepD0KuSbM5h0Gk//Y3fsuw3YrxNUSI=,iv:3cN8YbZcrYijoqSdvjXL+oZhTLOiByyZ3v5FqGh+gZM=,tag:xnPTQKVEkukbEUvJMdNdaw==,type:str]
    UPTIME_KUMA_STATUS_SLUG: ENC[AES256_GCM,data:7WfiU6kjN/s=,iv:IDUm/xNTGwLeLKNZKkvvaIWb7zjsDwctojEDiA+P9KM=,tag:tk+Aya1Mq61aJ0VETN+FCg==,type:str]
    HEADSCALE_API_KEY: ENC[AES256_GCM,data:rcM7WZo/XJ4=,iv:xc8ecd70Hoz6+EDvrli8BHkHKPC8cSgLkjyk5j+r6aM=,tag:bvUBQT3qFkp9k+/iPpE8UQ==,type:str]
    UNIFI_CONSOLE_IP: ENC[AES256_GCM,data:aim5D7/zsFY=,iv:P406OgKRqckpcLiEirwPCNwS1q3vemi2YJNlk1lDGRI=,tag:oG604xnMTNhUI/HUclK3sw==,type:str]
    UNIFI_API_KEY: ENC[AES256_GCM,data:a3AOHvRQ3G4=,iv:JtzTsYUGMNlapmt0Iq21GPIuVySL1PXRZ90WKRtiOlA=,tag:5ua/GGSrgzfeFtq+WS/+xQ==,type:str]
    QBITTORRENT_IP: ENC[AES256_GCM,data:eoVG33TLnJU=,iv:3bYuFPl05styQ8OSakYaD6SNWqLNG4jSGzH1KKQ6iDQ=,tag:irHYgAHbDECgXgNCfgV0vQ==,type:str]
    WAQI_TOKEN: ENC[AES256_GCM,data:b077kws8D2c=,iv:v0DwcQJMnPuY0jTalYflOy5jTa/69dpMLely/LBKVR0=,tag:7jJJeyYmduXOyA4rlPhKqg==,type:str]
    WAQI_LAT: ENC[AES256_GCM,data:vaSc8z3vNHs=,iv:E0Frgetchvsi3Aerwlq12zg0ptRZpP6+aUv6pMHUvN0=,tag:IPbuSjHWAjV//IvI0C9z9A==,type:str]
    WAQI_LON: ENC[AES256_GCM,data:T1baQJviaGw=,iv:eP80UgU+Gq/dqstKnUQfqKhSWc+/XFJLmrGVuX5NpAM=,tag:73NcMRIfQkdYR6dqVdZfmA==,type:str]
    NASA_API_KEY: ENC[AES256_GCM,data:IrLpbA5QrRc=,iv:ygJZrw3CSoFrV5jVKHT+svUkKHC6yRzgiR+lmZxB08E=,tag:EyxJTRcf+TDavp/jdI7emA==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:q+9LndxfwV0=,iv:8cjYZ46IFPTOy9NliRzGUsjPXgpnAABZsn/s8QYRbjY=,tag:tZo8oppJ9BgAwqDSdm1kug==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yWdcRvFIZoc=,iv:HU9eGMsPmNeBPnX+9M7LWiTls3964m05nuSJ2OEYwCk=,tag:Kz1xrIi24uJraThfS5geJA==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:fE0JIAy0wXM=,iv:OfFc1oVsgpmQcZq02p3pWAbU0e6pVSJbp4vVFIC1i50=,tag:FiFCO4cmq2S7+DvcrN/hYQ==,type:str]
    WEATHER_LOCATION: ENC[AES256_GCM,data:+UleRvX4eCY=,iv:PJq6rZS505m75Qc7vx0Nc1u7NqsCrdeRCl0YEakZ+i4=,tag:pDZOv/x10jV51cFIBHHO9Q==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd0xGalJLVzhxd0ozcWp5
            YkFZRTN2MzVZdDBrNGRrbEp6L3ZtTGhxSGtZCjVYVUxkYXhyM3VMU25TeHF0OCsr
            L1ZRS0RRdWRuYnNLR0dKbW9DQ3lTc2cKLS0tIE14S25nVVZCSzBwZmo2ZWh5ZDdo
            eGRxSXpCY1RESGpsaFIwV1pYVS8ySjQKO4czbuIKdy35bs5dXmjc/mdyJwyBe89j
            4MZHlPxhU36xsK9IgmU0Mo9tnbFq3fM1zqBTm4iJ6jvGJ2Q5nWVRXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T05:04:43Z"
    mac: ENC[AES256_GCM,data:0PWe9RxSfEATbgKvFFsY2tHQjB8Oc9msNazqd21zb5lRDbb1wGAZbiQdcFXZilZ7wTmi5ezo9ksTyq3Y6U+xiDa3H8cUYa/s7zvIfL4KXVoo+W+bcGSZK/fb8GnmjUie8H2q+aEe3GV/HKLGghCGGOIn4Yzwx2pRdIIxxagP/qU=,iv:80Oo8X8Z90Ej+kvzoP7kRQWco7hG5jDYh2+z25PWUO4=,tag:pGe9i0GE4Io9o/Ap4yWGiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
