apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-postgres-data
  namespace: monica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
