apiVersion: v1
kind: ConfigMap
metadata:
  name: monica-entrypoint
  namespace: monica
data:
  entrypoint.sh: |
    #!/bin/bash
    set -Eeo pipefail

    supportedSecrets=( "DB_PASSWORD" "DATABASE_URL" "APP_KEY" "HASH_SALT"
                       "MAIL_PASSWORD" "REDIS_PASSWORD" "AWS_ACCESS_KEY_ID"
                       "AWS_SECRET_ACCESS_KEY" "AWS_KEY" "AWS_SECRET"
                       "PASSPORT_PASSWORD_GRANT_CLIENT_ID"
                       "PASSPORT_PASSWORD_GRANT_CLIENT_SECRET"
                       "SENTRY_AUTH_TOKEN" "LOCATION_IQ_API_KEY"
                       "WEATHERAPI_KEY" "IPDATA_TOKEN" )
    for secret in "${supportedSecrets[@]}"; do
        envFile="${secret}_FILE"
        if [ -n "${!envFile}" ] && [ -f "${!envFile}" ]; then
            val="$(< "${!envFile}")"
            export "${secret}"="$val"
            echo "${secret} environment variable was set by secret ${envFile}"
        fi
    done

    waitfordb() {
        TERM=dumb php -- <<'EOPHP'
    <?php
    $host = getenv('DB_HOST') ?: '127.0.0.1';
    $port = (int)(getenv('DB_PORT') ?: 5432);
    $user = getenv('DB_USERNAME') ?: 'monica';
    $pass = getenv('DB_PASSWORD') ?: '';
    $database = getenv('DB_DATABASE') ?: 'monica';
    $stderr = fopen('php://stderr', 'w');
    $maxAttempts = 30;
    do {
        try {
            $pdo = new PDO("pgsql:host=$host;port=$port;dbname=$database", $user, $pass, [PDO::ATTR_TIMEOUT => 5]);
            fwrite($stderr, "\nDatabase ready.");
            exit(0);
        } catch (PDOException $e) {
            fwrite($stderr, "\nWaiting for database: " . $e->getMessage());
            sleep(1);
        }
        --$maxAttempts;
    } while ($maxAttempts > 0);
    fwrite($stderr, "\nUnable to contact your database\n");
    exit(1);
    EOPHP
    }

    if expr "$1" : "apache" 1>/dev/null || [ "$1" = "php-fpm" ]; then
        MONICADIR=/var/www/html
        ARTISAN="php ${MONICADIR}/artisan"
        STORAGE=${MONICADIR}/storage
        mkdir -p ${STORAGE}/logs ${STORAGE}/app/public ${STORAGE}/framework/views \
                 ${STORAGE}/framework/cache ${STORAGE}/framework/sessions
        chown -R www-data:www-data ${STORAGE}
        chmod -R g+rw ${STORAGE}

        if [ -z "${APP_KEY:-}" ] || [ "$APP_KEY" = "ChangeMeBy32KeyLengthOrGenerated" ]; then
            ${ARTISAN} key:generate --no-interaction
        else
            echo "APP_KEY already set"
        fi

        waitfordb
        ${ARTISAN} monica:update --force -vv

        if [ ! -f "${STORAGE}/oauth-public.key" ] || [ ! -f "${STORAGE}/oauth-private.key" ]; then
            echo "Passport keys creation ..."
            ${ARTISAN} passport:keys
            ${ARTISAN} passport:client --personal --no-interaction
        fi
    fi

    exec "$@"
