apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monica

resources:
  - 00-namespace.yaml
  - 10-pvc-mysql.yaml
  - 15-pvc-storage.yaml
  - 20-mysql-deployment.yaml
  - 21-mysql-service.yaml
  - 30-deployment.yaml
  - 40-service.yaml
  - 53-httproute-internal.yaml

generators:
  - 25-ksops.yaml

images:
  - name: registry.white.fm:5000/monica
    newTag: "5.0.0-beta.5.2"
  - name: mariadb
    newTag: "12"
