apiVersion: viaduct.ai/v1
kind: Ksops
metadata:
  name: external-secrets-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - 00-clustersecretstore.sops.yaml
  - 01-onepassword-token-secret.sops.yaml
