apiVersion: v1
kind: Secret
metadata:
    name: opencti-credentials
    namespace: opencti
type: Opaque
stringData:
    APP__ADMIN__PASSWORD: ENC[AES256_GCM,data:dyyu41JfBwVWE0RpRGxoqYy/i14jZSaWZI0T4oATtNo=,iv:QSOG3ck3bni+GTb30CC3axGr31LdC2FWwXjLqLkXNm8=,tag:8l8Xe52xATLmqnexTGHjbg==,type:str]
    APP__ADMIN__TOKEN: ENC[AES256_GCM,data:E3OLATUj+oVRjZHEI2bAe5BZaLRVhnJ4Tu+TNnvzUWL07n3k,iv:Q7nyYMseLbZorwvujaOtRkIRb5dbAkIZp2MsWar3zYY=,tag:Pkjlp9LgGO4C7beFHl3RAA==,type:str]
    APP__HEALTH_ACCESS_KEY: ENC[AES256_GCM,data:ZyvqKfQ30dX5GO0FNC1mj4N3M7AeVDbx8Jxx/SvLcg8Vk0z7,iv:5uxUj60IsTTgA1n17zT9ttxmLMOXj/pW5SdcIjLA8vo=,tag:OW4aB1eBYWwG0WtO7pfvYQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY01ZSnRZRm1Wa1pNWEdt
            bVVjd2Zpd0l3b29zMVR1eXVud2N4d2x4c1NBCk1xWkNnWElrdVNiY2lwVmszcGxm
            ekZZY1ZIZW9UZ3l5cnl6aER5OFNYLzgKLS0tIFNHMEhraTNiTDRneEdHUmIxNVBB
            WGk3dmNzVkJ2Vy90cFlRbmFtL0NKQ0UKpTqI3nDyJ+bJO3C2g2i4DvX13BrtZAyH
            joSsHsvLj+aecliX0zOO7MWZhLbW6OsflPKI0hwlHaCyz23/s2DJJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T05:52:12Z"
    mac: ENC[AES256_GCM,data:Wh9A8PE1aTGkgveLGDOG/wjVpNqMFhZoZqizNwb+u8Udls+se/4QtFN7+r/PVGCsj3ObFjRckJLjRnzqroq2/IUGT3zB1+XqWaInicgb6I5L1m5ujb/MLY1QXc86gn+ZZxO4GiOedm1d3nmxzs8K9vW3kOy0b9wa6MeoncwyqmY=,iv:UmW/v/7GqXcYvDOmfMNtQ5qJFF+XasPqT+u5lWy612o=,tag:onb3dR0J+nGxjK9fSNGuyQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
