apiVersion: v1
kind: Secret
metadata:
    name: opencti-minio
    namespace: opencti
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:VQQDt3Bjgw==,iv:m/ifgEMs4Bd+0I5RMYrmGXvTS/9/YZSROlUMBS1eNTc=,tag:6lFvlMDxWfsAwLZTcVRKsQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:LJVG16FT4qgcwOAzvi8QNtMhJN7ZuVHMlqyIdvOLmYY=,iv:XaYPYvOquVxQr0haZsljJZb8/PHYn++752BacLxWW+Y=,tag:I2jZPa2hIwBOTsQHPhgwqQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNVpPVlBJMHFrZjNER2VC
            UW1zU2RSVFBqdnVleDZsZXRwc3I0TUtVdlgwCkFPUlgrb21MVTdrYS82OUFMaGpa
            Wit3Q2o3SE9kUXN4R2w1K3A5dU5OY3cKLS0tIENINmNZbXl3bTRPalRybk54aDhn
            dWtYOVNJVEpjMXQ2WlBCdWd2WU5UNk0K1di9Ax4Q+Vxc/ScW3V1AC1tR9W+igizF
            yHzocPIfgTLBUqU6+1YiIZjQB4cLBAcKT1sgvLmoeL9Lud1NeLXCYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T05:52:12Z"
    mac: ENC[AES256_GCM,data:ZzbT3xpicNxWxl46BG7wx4HFaUt/JsSc609KFNM7qFbBf8QhWbYzseecwzFVes58uTX075LCdLr+H1ICwd0bIMoFxqo6AJsaiXiCczMhbtVbf7pqEvOG2qA4M8JF+GNeK0dWgfjuKcdhHpg0Q5qDHpNFNbzTKbs2lyHxDT486MI=,iv:VQA2pFXCFEuNQrrruQt6E9W62me3jb0uP83bjmoqAlk=,tag:Qn7KyopyIo2yYTJLe9GFHg==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
