apiVersion: v1
kind: Secret
metadata:
    name: opencti-rabbitmq
    namespace: opencti
type: Opaque
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:1/Km3i1y80TVQYobmK3JPKOPU031JsZxRK/qxJ/ucfQ=,iv:eXpOzHFX3F2PC/H9FtxPvcsd2TVMMD/wuj5u1AkBgFc=,tag:3JI9Z5oqNi4Dtd2XiK19dQ==,type:str]
    rabbitmq-erlang-cookie: ENC[AES256_GCM,data:kvbfgDiC2B1WeDzeM5lSUCpfIxXrbszI09JB0toEV4rDCCC1,iv:tUwJXlcqEm+1R7BgwwpWiUbUYQJbaySyJALbjratJYA=,tag:H/OsU7HSt+XqDX/VNwIuFw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT0VxRkIrVnlYdzZjZ05Q
            Tkg3TGcyRWd3KzBUK254b2kvOGNhMXlvSVdJCmk2L01VZ2JJSitiL21DNHhocUly
            SVJKb3J6dG1KVjJaSlV0cnpPaEVObUUKLS0tIG0wTzMyWVRwR0E1VzNiOUZvbjh4
            L2VSZ25ncHlSL2VFV244VEhuTzhQdDgKIKuDZnluqhVDv4uWu6zAmgkLaVdysBCs
            5GyVWVWAZn4EdroqStu/jbfjtZ5IsNrEcMNRsmMtfb/H9SuBSdNksA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T05:52:12Z"
    mac: ENC[AES256_GCM,data:7Z2S86S3BNxuLf+tPNd43wRsNEPp07qqH8eh6NesRN0sai9eB6EJEy7agifdXceCQijZ5kqRNqKDASFhqgy300qOckEAEj3VUSFeSSCRnoQZ0K8Za5zOoLqYomKIpGd9mRoLG4ZoJwl0ecJ58D22hsSiMkUj/Jwb/ZMyy4cdOa0=,iv:5TVkdvUmW74UJBcXdNex2UH0Zc9yXuuNW2QShzWu3vI=,tag:ALXdxpTK/Ba3/r1GPwLq5Q==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
