apiVersion: v1
kind: Secret
metadata:
    name: nodebyte-mcp-env
    namespace: nodebyte-mcp
type: Opaque
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:c1Eh5AR038QDfXChTKNztrqSsJdHw4+RoFoolErknfSvAjXjnpqZm9Fxig==,iv:+jbqIQyK/KFJ9SUUgp15Llhi5mn6yVeX+/KQr88vH/8=,tag:Qs3bzPrCgqxSScxJ6AuunA==,type:str]
    NODEBYTE_EMAIL: ENC[AES256_GCM,data:OceqJ2Z0wrLatQc3BUD+301Yhmx9taU=,iv:RZMln36FRuH5OiiUHgf3P8Q+qzAaJtAemQPhyq9eERA=,tag:VPqq4FcXsTNPbufPM40LtA==,type:str]
    NODEBYTE_PASSWORD: ENC[AES256_GCM,data:JZm7ffP2BC07wgZ3MrhduTnR+icu1uA2kq7C6C4nqRg=,iv:glIN0IutbRLO7fEUn1d1/nBm7ooGV4Wu/BIUI/vQMLs=,tag:iLiAmpB6HmTxO72yQ/84NQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbzl2S2w4SVRGVXlUaGsr
            dWVWWjhudnBFOFBvclViQTc4TVpUWlZ1SDFzClpQa2xpOWhoT09MTG5ZbmIvd0N3
            YkQ2bjA5V0VqbFRjaXB3Ri9ZMWxqOWsKLS0tIElic2VDSHNYNXdUaU9kZXRiY3Nn
            SGFtVmV2dFpKT2ZOT0lNRnJBRWxjS0kKqO8dL3zcEZ5GpkElqdgSZrqWjUkLJz/o
            6m0/0foEYj2CyBU8Edfl1m/1SKGdXosFjtOflKDqQVlqqvJcG4bR5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-10T21:07:38Z"
    mac: ENC[AES256_GCM,data:53o1rMalzUg1GPi6xtaTxbqgsqvQ/nwkhF/TfhjqinWO7qe8uxJXGSGpQMsEZ1XkUzMGXXgbqDyCeWrHGSqtxd0Q3x39VF6v78BkWqGMoRX+jb4htbnuRcwwjtmb+wMmw2Y9cgmp7xu22fBVA3MiA09a+c73KsJxCvCvp0UPUl8=,iv:vsTWlKqnTav5Dyj+QhJJ67DlFm83xQkX+YUNEQr8C/M=,tag:fBh7Y9NwI+oa+1t13zSObQ==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
