apiVersion: v1
kind: Endpoints
metadata:
    name: plex
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 32400
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSVcyeFRpb1kxV2E2ZXY3
            a25iVEh2TW5vVFFiY2NhMy85RmFjS3NIWjFJCnNxRlAyZ1Q2YjcrbmF5UTRnektS
            L3ZNWjBQZHEwQmROUTVVY0FNenVtMUUKLS0tIE9XVEhZeUdkUUdoUmRmU1YvMTdo
            Q0hDRExuNzNvajF2NjRQSHZ3UmNnbnMKItumeTB6QQPcpA3XRXmVCqswCqIyrY+j
            jipZSDzkYZZL/4P6dYSn8hkMrP9tGzpk9lZ3en6q4L7uGEx0x9jlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T15:36:37Z"
    mac: ENC[AES256_GCM,data:94pMiCWlvJCDbUSqnA50IG3U22yAmg10NP36aehGAuqPog2LjTEn5gqMdEWugUcRcs8VC10RhILGIycTOoM06ypweJgGS0m580PgLzmD5B9eh1lIWtFMjTtuivOfUtRlzbW4GEcXmbp/Kb2hJNLPXMrL5fSqhEUMo6lO9KJeBQ4=,iv:5VnY4gpjkkb/6QyS6om9gQ61hBTl3RVqLn9QbfBD/zI=,tag:yCLCNHCqZBH+Pfn84hWvVA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
