apiVersion: v1
kind: Endpoints
metadata:
    name: pihole1
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.0.20
      ports:
        - name: https
          port: 443
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISldDaHpURHg0T24zOXdM
            SDBWQ2laVCszL1BJeUxVMEFZUmY0K3RiUUNVCkZpU1cyc29vU0VKcXpnaUx6UW5L
            Y2dRMzBQNUR0VmFJUFNLaVpGNUpOdHcKLS0tIGhqRzJscEhHSnc4dHk1M1EzM2ls
            cmlYLzNyWmlWMThvNS9DSkZ2OU1JZ3MKgYgDVxjTX+3iDMQk0iUTT4khBWNutpYY
            ABiWZG0Ye6Bc2PtRFi723Ab2GGI8jAge1aLRKeLp80nDHdiopX5NqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:23:27Z"
    mac: ENC[AES256_GCM,data:ofCsvvwukr534HOAxSmRp81zfKkqQckjJvQGsMDXxdkcrTijkrdszXfzXt7FFNNUep6v9AFfwFM3sSf8cVc61j4F7oByyXebLcmiT21HaR66A+9R1ceQBz60E588++DTm/eKYZ1ot/VLmmzIcZGTLXTzPoh+egVwL+2mtEJYzOM=,iv:66W9tBWnJ5+2I2vNlAsBZ/dURPgXHT4pVJPRgmnaAOY=,tag:ZWHT3yhjxoFPyn9L2p4KMA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
