apiVersion: v1
kind: Endpoints
metadata:
    name: scrypted
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.7.5
      ports:
        - name: https
          port: 10443
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTDlLS2hlYzJjNzNLT2hl
            OEI1WmNESXRjeGxTczY0aXJMWUJHZjAyWlhBCmJmeUFzUUFOcEYwZVJWTS9NV1NE
            SXdGOVEyWlp5QkVkRzF0dlJnUmFrbnMKLS0tIHBiVmN4Y281ZndFMDlLYXIxL3Bk
            RzJWcEJIdTBEbWRXUWZZYUp4Vi9MU28Kx3z7gudef65Wil8pS2rWHKQg888rDEoU
            iIf4tnGZq4GzJd2iBgvrp4/0HUTGkjPc6z63OGG3q5PHUEQIS+kEVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:23:27Z"
    mac: ENC[AES256_GCM,data:6IqZIwQ9rIBkHGrwowqENeINta5AfuldXoutCZu93HRtWeS6QEahk1hjKD1GjSly2oC4Wxep/CDY3RovkD+LygZPBXVY1UsDG1GAP2Ogrc2VkgwnP76kuuR/cOPZfsr9sensILXk8fjNbLj6Ntmh2hQNkcpuC2Z0MxBh2aNw4dg=,iv:JpXZSCElkTjQ4dkcRuZ1f6g93QBRnd3YtcjGg7X8uIs=,tag:DLq5Eyzr0Wv+yu5lMiRV8g==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
