apiVersion: v1
kind: Endpoints
metadata:
    name: ytdl
    namespace: external-services
subsets:
    - addresses:
        - ip: 10.100.1.20
      ports:
        - name: http
          port: 8998
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOC9KRFp3RXN5aVF4L2s4
            Z0dwRXhoMFhYMHhpdWJ3djFwOU42VENnU2pvCnBEL281bEZEYVNNVFp2cmFzYnRX
            bEUwQm9QUDdSSzdtZzQyZU51MGY5MW8KLS0tIFFFS3h3MFBaWklteEVnQzNZbUI2
            V2w4aitCNWN0ck1rWndiWXU0UlBUOXMKIQfrdPR0G0+yMm9Zn/g3/SwfUA3gw09b
            wzFMJDPdyCUIfk0izdbvmEdYxNA+BQ149VhgbhMn5iGT0daPph7gsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:23:27Z"
    mac: ENC[AES256_GCM,data:yfi9B7MNzJaEeUGgaAesEIY8cJQewPAf5bSosRBLXXH3k2ACNJbH4B3SUUzNJK/RbndRCPhDfpzw2pUB395fgl3aUFzaze3wmmdu9gFnX6gRaFCK8kSNmvM3xQt4QuTxLgPcWfwev0DI2H0W9+58mjwfY7tTGldqcRbdk3k6uJk=,iv:Ea6qk7OMLf48/4R/H66lrF/bCeqb3FH/8EWiAWyAL6A=,tag:y4EaY6yg1yrUYdlhd9jUzw==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
