apiVersion: ENC[AES256_GCM,data:2pc=,iv:iWhhx6/AeEU8MLmatnJYE62qiZFZx4n58SS+v86a+YU=,tag:EVeBOqEflbDib14GrMRFrA==,type:str]
kind: ENC[AES256_GCM,data:ouuEfWCQjw==,iv:SPUhRal7oXRuiXOHX4HPjqAyLmcGsEMeTx+R1XHCk8g=,tag:gEKl2D0COtq0UMsegmWnSg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4m2O,iv:tGxspGgSgAOyl23uNy1wyijtV4jDZGb4RtUFLjshIlM=,tag:XoknjJYD7JsZMB7CyzhE+w==,type:str]
    namespace: ENC[AES256_GCM,data:y20uKBGaMAn/S1wP8QB8asc=,iv:BfhKd8DedRMcaAIc1+ZcnVM4dB7KyYLxllUbWtHgN3o=,tag:3hdxgRPnoJfFVbehmRiK4w==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:c07qwA==,iv:eYJQomIGoZcL/9qXh35A0fiWWSB3nASjkbQbsn1wbis=,tag:IqVS0ciCESTY9m0CADWT+g==,type:str]
          port: ENC[AES256_GCM,data:v/Qxbg==,iv:ZBkIPG8gqQAR7ylhmqp7UXKyiJmKJu4dU2L66+rCf3k=,tag:MmR88+sv1WH2iqfC4DPI1Q==,type:int]
          targetPort: ENC[AES256_GCM,data:vd29eg==,iv:r4IHpu6OAhAG4RSAnc+BUiEMB99YHC8SphtGuKBwOZ0=,tag:bJk3z3dh5+mtodclEMIQPg==,type:int]
    clusterIP: ENC[AES256_GCM,data:sLDANg==,iv:IlJO31ClfxSouAIa+cuyD5Pf5/h/V75RLyl0ctQMSpw=,tag:DquHX1fVN3FlmwUOAtDLlw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbGZhdEhMY1FKWmpnZ2FF
            L0dVMGIzdXI0RlF1Q0JlUzNBTVlyTEN1WDBBCjVoNUJQcFRyN2FPUi9TMkhySTFO
            OXFpSHpEQWkxMmx1QmQ4WHNhNStCdzAKLS0tIEpNM21yYkpUa1ZGQk10aEFobVcy
            Mm9lMnpFbHZJRm9XbzE4L09CWTMzWFEKDg/gn8NTjlPETuyTW2g/mqx5H7SZuDPP
            2T4ldpOrTF4TexfaWJfwXC31ugnb3xk0ClfG17ajJMKI5fr4YS+VSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:4VrIc6dbKJrpTNT77yLGpIXcRyyMWrlV0+viFzsp7wsTRqvojCGrQMNFqTZH0Jt9P4FNVU/SG2a8ggtI8HPcCZ15swl/gDasDqYZN7mBgj+thCJUhLdSL8GN00HQo9JIvhYQ+8VEuEimxsyzU+gHOXUnB7E7DwwCE5faF9vt6fo=,iv:tKg6Jz60JGWpZfIqV/G+EaDWIg4BdY8byNe/4A9L9QY=,tag:SPVoJpn2jGSv4s8DW4VcHQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
