apiVersion: ENC[AES256_GCM,data:ptg=,iv:doZMkpMj8BWn2FasAoygV1b4qbaydj7KtRRBuSEM1Po=,tag:JPZaO2jrOzWMjti204kG2w==,type:str]
kind: ENC[AES256_GCM,data:OTEoxXoWyg==,iv:4PJiN/15mPCZQkrOASvnRlCwhoF1AJMaraInq3mIA2Q=,tag:onT2edcTF6bq/xa1QaA1Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SQOLzrgkz7rY,iv:jwP5EcrLRg2NgLkuEo26FZDO8FrTcMKnroHsItgl+Ws=,tag:AZB0V+6mNTeGATluvUzHHg==,type:str]
    namespace: ENC[AES256_GCM,data:OudSXr4Ot62Dg5pizHCfWwY=,iv:IzPU/gmvBuuHptZEn4aQfM9Zt5CPUxTYKH/BYnAiac8=,tag:9n7AuW096A4O7TkucM/bow==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:UZ996A==,iv:FjB+ClILHEsdlcOFEH/HddtxIk38CTaOrahEFia/yB0=,tag:tvgimtt18nH1iP+5/0eLfA==,type:str]
          port: ENC[AES256_GCM,data:eBrA4Q==,iv:kyNnpvxGfkINxn/w69Z0jxZqKDFnrb/NCkO4oiDZy20=,tag:p84OW1DEmwTYDzEEgBnNSQ==,type:int]
          targetPort: ENC[AES256_GCM,data:eKEpsA==,iv:yc5LcRB0zjSomeyg/4UWta8B5utb8QVzH0zP+beuCcE=,tag:skN/ZDMzF5PGlcKSJHvPtw==,type:int]
    clusterIP: ENC[AES256_GCM,data:gahurg==,iv:4XR+ZNtGRi9nkQa7jT/YI1cxViyJDeNDFP2vS7JJl58=,tag:0DxmtZckgH/jWmGCYli5mg==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSGUydXlVT0RXR2pvdUVE
            dzN0M2lvVkg1V2FkWENEb1FvN2t2WldGZm5zCjl2VkxBNFRYclZuRGpCVXZWS2ZO
            N2orOC9FakNEeGI2b2xCNnhzMnBwVkEKLS0tIHl0NlhwWlhCN25YaTVBSVFCOTcw
            ZHpFbEpTaXArdkc3MEs2RkgxWVBnR00KKxoMW2XIHdDMtIVG2yS0luVlaXhXC5Or
            F1cuHNcCV4TwJR3cwPCNjixw9/FEqPIWJ8IU84Rf1Tm40G8ayqnppg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-03T05:09:15Z"
    mac: ENC[AES256_GCM,data:4QmY2V14a/Q5uZPQjwyvfWhlV/fgBy3J9jnAl6ptMqZjEHa2EMZF+Cl3ceqrT4qqGOcO9FJMiPoAMDPDxZefXbafCRazSA7n+jXaYnBoDuHZ2o5WmwmQt4fYH3bJ92YfKk7DmEoP4wtA7Fy6uiN6EHEZiEjELRnVygA9ArTevqg=,iv:rj8J44mZHZpvzOhSmiZCqhsL5lNoR8wz6l0v6N5bwDE=,tag:aULbvzJo3gwNzDW8AGJG+Q==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
