apiVersion: v1
kind: Service
metadata:
    name: protect
    namespace: external-services
spec:
    ports:
        - name: https
          port: 443
          targetPort: 443
    clusterIP: None
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSm5IK2JldFNUVjlIZEVE
            Wkx5Sm5pQUZrZkJJemdwQTB2WnB1MHVXYVF3CjAxdmhOK1FtUUl3Q1VQeHRwdmw4
            WWt5NTYveTd1bHZaeDhuTzhpT2xzbncKLS0tIDVIMXo1czJMaENuRnVCRlNjUTBr
            QnRWcWQvNVdxdmxTak9vaExpWjh6MHcKXVguID2VnskCDAdWv97Fnq+ivTLkrlNs
            oT8gBk4KAFoshKEBDBi4Pzbsa11xRzbWnXin7n32Cj/YdSQ54bOJjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:27:20Z"
    mac: ENC[AES256_GCM,data:71KpiS+RdPZxnt+eo30WkOXSFxPKrjOlf+r8jFjg5SGBSvICM6hVKjAo76TPOfRGSLKyiAskGrH+fAuWTCOYdC4TsjKN8dkZ4D6bsaPXTslNuvbHWCe9OH5YXbfYyHCkmtbr7KhErY1o3pypCpzeybCXQrkbc3zhGTEmw6XfJW0=,iv:lVXqoTz7zKLOzpyVpOiLqxv6T1f0Y2JerAg9C8K65pc=,tag:yVpFXTGIINpjUKmIOOWfCA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
