apiVersion: ENC[AES256_GCM,data:huA=,iv:q6G3xlEokfBTGt8YESDXXlkg+EENDQ9ZzXBLa8sreWc=,tag:WJjWLFvDa4RombFTjApAfw==,type:str]
kind: ENC[AES256_GCM,data:GkXQ1tGi0Q==,iv:kukWzT1VEd4oOf0jhz5TLtZMWERz+5uGhEc7b5Edghc=,tag:MoajxozlMgs55wno0ruf1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lyI+/w==,iv:dKANab1dbHgtuOhY2JmyXWvnzL9e9GjIzKzJnP7nwXE=,tag:892CgJrK7vSBdTmk0QUodA==,type:str]
    namespace: ENC[AES256_GCM,data:CK64I84lgQ15N6O2vWJXC6E=,iv:ILyA71LxtzS3RFQgIUzZeYFXqBQa7rGVgFTFEvYdQoE=,tag:kSqoLnjHlGN3nJqONgw05Q==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:bhMhPg==,iv:uhEfO5ZrpPWJUaJ97f3nuww1KMsBuNZwY5q5226kbnw=,tag:qKkYC8e2JrykwCKaB+zQaA==,type:str]
          port: ENC[AES256_GCM,data:NzIv+Q==,iv:LRalvczGUwTx7QJHsN4dyKxUvevzJpvJ7AEV1g/ArXg=,tag:ZL0zdu2si/CcY9PEgJ4D9g==,type:int]
          targetPort: ENC[AES256_GCM,data:/kI0zg==,iv:GaVd33s04Sv9roNu2n6+hfTssv4wtiWh9lNblVZaXSs=,tag:mWpR0VRWt0z2Nqd829xW6Q==,type:int]
    clusterIP: ENC[AES256_GCM,data:M0Ls9g==,iv:r4m+Eao1YfpPAUAhhuDCi2P9q1wIQC0TwcmHdnRYfiY=,tag:LtBkTndGHKrRoexdmEH+Vw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkakhSc1NMa2NFN2tFN3FX
            M1V5b1FqNGtmcytEc2pqaWFqL2xZTWJ3MG1rCm1sNWo2MTJQYnhxaTRiZkE0NzlH
            WVlzTEdlSEV5bEYzN1BQSnF6RHlrbm8KLS0tIHdDbzExWllTdTdjbzI5SWZST1JC
            Ykd3UytHRi9Ma2gwL1dKYkxRZzJNZWsK2G5viytWXfl9DA8Sfl0h636q4shHg77H
            /GnI1nrEaRYAnA0rojVpc/xhmvjFD3TqJIQ5KF07Ar9W2NZbETidXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:22Z"
    mac: ENC[AES256_GCM,data:qIgj+Y2IvEtJV+Gh0A1mb2nawLkcsC/Amkm4e5nl/CbxY18z02hsl6i2uZMM1rjbuIkqsFRB9xpIt2em37vZNxGPhqPIdgYvdr+eRw3ZTn3soA23b20iwy0wZYN+kVaVz5v9zM1AeMWkKOFclGzhBQETA6hIYvstX/wKWUviL8c=,iv:CetNVTr9naakDDlr4zvaNDfDHdlYvXsdAIPLtuZ2IyM=,tag:BiIFiVkReYQpkRq5RVD5WA==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
