apiVersion: v1
kind: Service
metadata:
    name: unifi
    namespace: external-services
spec:
    ports:
        - name: https
          port: 443
          targetPort: 443
    clusterIP: None
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdktWNFNBMFBwZys4dEFa
            VXBpUHVWaHBPeFZRcDQrbU1WbUJTT0xqZG5jCjk2OXRSeW1xZ2lLMDdDY3BETmNX
            SjVNSmtQa0FVVWxqWU4wQVBLUzltVXMKLS0tIFdNUEhCK1lmWUtvUVJtdW5yOThr
            SlFEd2t0c29RQkVuQUxBa2JacUo5TE0Kz1adXYizdBamTTxm5tx2ITFCfg8bALSy
            cItfZ3fOeDoWvxdd75P6E7BgxW33JLad6fgEr+hjf4quNGiBQ0cNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:27:20Z"
    mac: ENC[AES256_GCM,data:JKLjn0mW0Pyie3qZ6bnPMZInvsaBye9+19Js2I2zMTQLpVadDycRJqjAX0ZgL7ueUttuHT2Z4mwUJw8SjR3MfGIbbI3pFlz4KyJdntNSqsJJj+C09On583uIAu3XuGZc3sEY/zUkf9agQjMeWrUEvCBDK116pMNXhdPRRcaovZ8=,iv:cISFis8kS7ZBBuUp3XeSXdan6G8y7EMEnGtjAG5XJyU=,tag:dgUpW7fKPe2zYFqqo9BveA==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
