apiVersion: ENC[AES256_GCM,data:w7k=,iv:IE7T+zo8+HRoYlP6AC+1OAMWM8ER9FIpevEW1Vqb0Zo=,tag:aPmqJ2z2Ht3lVOf75gbJnw==,type:str]
kind: ENC[AES256_GCM,data:djODAn/wHQ==,iv:wHgzEQdYaW+2H/YeSUEClxOQiYsnLsjcozSr3oGdxTQ=,tag:GqikWDF5Odq5lK7XhZ9q/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:44ja7uqeXA==,iv:x1sHZiMSFB0k1TB0n+o9MsNo90E41x+MibZqUBvh1/U=,tag:Ok6T2AgcdPiD0pDD5SHbFQ==,type:str]
    namespace: ENC[AES256_GCM,data:XNHX2v2TQmbc1GWDSVI7il4=,iv:RNWljmhWaUJ09Jd90d3VcauBypexB7j03jwibJLFAkU=,tag:3blAYO5oxB5/P47xCuszgA==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:RnqnBgU=,iv:O1VoQhZYwiDr5rwwdzrGXFFW3VhdOjN5N8bQM92LFlc=,tag:lNThU+Lh/rnWaSaz6/CsqQ==,type:str]
          port: ENC[AES256_GCM,data:JzZ9,iv:nr9LvskpsilKhYaHqJko/eLkDK+RRsajRKLz6VmD6W0=,tag:LVpFYULNr+ft7Re8PhTljA==,type:int]
          targetPort: ENC[AES256_GCM,data:Oh0m,iv:ODAwxpk1tt6fdwR7a6L9EqD7341c2Hw8aQUdVfropjQ=,tag:4BwU8+kUvgjADAmwWT1RaA==,type:int]
    clusterIP: ENC[AES256_GCM,data:rCxP9Q==,iv:nDpDwqhg06pY5MaI7Gv2oCMGnt0jnka4evYSsGBa1d8=,tag:JGZ3kW6lA+oJMO6nBaR5Dw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM2RuMzZ6ZU5xdldNY29i
            SS9jTklxU1ZydDRqM0lQSHhrVkdjZFJWMWhnCjVTWDlyMnlNVUZrdll0Nno3a3NL
            ODZ4VmhLbEFJb0ZDdzhYTEtTOGpnemsKLS0tIGIrYzNzWVFsSXNRc3ZmR0l3djNy
            dFQ5dTRYNlVDYTBKM0MvV1k0VTZZR0EK4wscHyTVCNyOB4uG0kj0wUTfS2H58GUZ
            IXxMkS2fTl4/V47n+kgw7BETr/196LcnWBvJ7MZLb01zd5IcWnwC8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:22:03Z"
    mac: ENC[AES256_GCM,data:AZtHpEx7zu9qec34J1mFawvJruudUvEiCNu4wREegvAEIYtBoZML1B5gO7Q7FvNc6EU9cI2j9c4QjGYGiavD1p21wD9IT510eHlEqAinvSkU/+cc9nOMwOPMuEOi9MISJk2/kgqrRcTjB+GbUdJDvguTvafnkxzDZul5gMTU+NY=,iv:bJcja/r8dMfMeppMlmvdeuZe7ER7pAyhukPZXBMOhpc=,tag:xhY+q6auOsbnPtAQTOc5Vw==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
