apiVersion: v1
kind: Service
metadata:
    name: minio-console
    namespace: external-services
spec:
    ports:
        - name: https
          port: 9005
          targetPort: 9005
    clusterIP: None
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RmtZTXF1QVVkWmU4L29l
            UENmR0wyQVVFSjNBTDMrSHF4TmhLZjArbVZVCmk2MVhqTzNYd0RwZ25sdVN4eEpz
            T1o0cFFKeUl5NFMxbE9aYWt2V0tRa1UKLS0tIDUxV1dQbkZ3T0UxSTAzQnJJUlQx
            TW5TSVFBQXA3ZlBEamN4VDFuWmo1NkEKnKR25SgHHOKN5onci1MLsgmh1NTfVb/n
            sEVYlKMxeAyw/lXoB2mppKoePaFLI7KeIiQYACsVqT1m/DeZKRVC/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T05:00:25Z"
    mac: ENC[AES256_GCM,data:Pm0CAgew2rdyFuYrU01dWW7ZQ2JrUW3DWAmZovg43s5tza8v49cwoFhUu4WXdfsciNNqpz5dAW5ykvOvR0+LlyyvhHLOCPNc5LuVE2r1Y8BUnJm6lLRCfw2Oennf3AcBmnA4iBc07g3cl2G5DE45CiSJSTmvb0dImA0UaGP1vOY=,iv:AIRYZOmwnxuxDjvsl2sD8MNPWeL58jCBQlKIMUCdkXQ=,tag:tHy0PSm9W0WS9LK4NodF8A==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
