apiVersion: ENC[AES256_GCM,data:5l0=,iv:PO6UZnoXHAP4qg4MlHNeW3gWhF3iEzwLdDqRNJAdC7A=,tag:w2ljLNvM7MeGdhScOYmsiQ==,type:str]
kind: ENC[AES256_GCM,data:ZxOjDQ7nYQ==,iv:qBprRWpWKfwc78irWAWK/xPwupHEORhal5nn6IEYnMo=,tag:IA1dhUJqN+5boSXKiL58bw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8ht5,iv:qAAC6S8IX9zqstzmXb9oaMBTjTHeGNUEGpOA9hW82mE=,tag:hSOoxHb7wEVoapDgO9+P/Q==,type:str]
    namespace: ENC[AES256_GCM,data:tGfu6mNEraT3xyxu2psJzME=,iv:IN9lys3VaVSoXpmQ02qfsaCiuTn9maZbbmV8FFE5wlQ=,tag:wDUJhpCjEsezRKNWdKXYSA==,type:str]
spec:
    ports:
        - name: ENC[AES256_GCM,data:4SOUfw==,iv:DQJG3Rvkm9hQP2PRhWYa9GWBVpElGOkGkso0WTXeyuM=,tag:N74VUtibFovUW4QobruDMw==,type:str]
          port: ENC[AES256_GCM,data:ukJWWQ==,iv:kuEFDmKv2GerLWTOVLMPWOzoi4Au5fKKM7LHrgNB0p0=,tag:5nsc6EY0wd6yecndXg5SrQ==,type:int]
          targetPort: ENC[AES256_GCM,data:nPsiYQ==,iv:07Vh+RXWwPh24eI9XO7SbXydJKwNjItDOMlMi5Mi9yY=,tag:XVPVQK4jnNIv5S6F3XqNWA==,type:int]
    clusterIP: ENC[AES256_GCM,data:W4gaWg==,iv:doI5zoG+/cyKhY8IZzUZnAJiUNgtK/QA79KDuchxyA4=,tag:95WIVbJwav/qgtjWsQE4Hw==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVmFIaGJCZ1d3b0MrWFA4
            RjkxcFB4c2FaVTU4b2VpdUtwdTdjcGc1QjA0CnZndEVCZ0hIMmhSb3VVVlNmcUZQ
            UGRvS3hYdDRIT2ZSSGJEMjQ3allSL0EKLS0tIDIvQlkveGExMmRDT3JCelRvKytz
            cGh4SGs2dG9rdmE1ZnE0eXNCV3h6MFEKDWdApuvFnun4t/vKKSFgPuX9U6Fm/CA+
            xLtTqWchEL0GpBL4MI8BvHQgdgZNUjs+xe61rAG6EkQHvlroyNMNZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T06:25:21Z"
    mac: ENC[AES256_GCM,data:yvk9j8ILSv7khNgYW2NrBkSMshnNqyHVErEmOOgu37TFhzjZ9DTSIRiPdRDQdOOtGvYqN7TStmBHyuK8w6dmGFcJpiNJrKWAANVGTDXsHbbHHPGManHmUcba5RYM05/EaqK2K9oWvGwJgR+2gxAlH46jBIvV7bZ+aLgTFK1yRgU=,iv:QDt3J+kYD9AeMi76moggJ5S5qM9wdAGgpT0kAppb9IY=,tag:ksQ1gS1m7stkoiZ8/SoMQQ==,type:str]
    encrypted_regex: ^(.*)$
    version: 3.10.2
