apiVersion: v1
kind: Secret
metadata:
    name: congress-mcp-env
    namespace: congress-mcp
type: Opaque
stringData:
    MCP_TOKEN: ENC[AES256_GCM,data:UcCtqsrqDt2Q0EmlN9QyDCAsXEY7SU4yLWQryo15O3I=,iv:FLCfHDp7EsmOXvfx/cYOz9MkTdHOEMz0JuRQIuMfjFE=,tag:fY3DcAD6ewcXql/9O/O1VA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ0dPNkx2Ujl5MlV4Vms2
            NHlCMXNQUVVqNWRsQ0J6c1NBcXRpT1VBOXowCjU2NjhPK2lzZzdFN1U4Umt6UVVv
            RUxpRUN4Q0x2L0FwemEwd0V4U3U1bWMKLS0tIDBlc1RxL2xvVzZnWm1zZll2OFBD
            bjBKbTZQMTRpMVVpV2cxZ3RWQjZrNncKwvg88YvLAyF07qcteEkPShe0F2C530sL
            wAuHaJ0WNYfp4Q6Sp7y42rtJ7lqIdGj2PMk0gzHCrmw7L8OLxfEQcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T16:09:43Z"
    mac: ENC[AES256_GCM,data:4C7ogQ4ZwZtieY3MxnRgES5fQS803zg4kdCSNIrtkz5LDkWbAehBfEVSduSVbj7oIQj6MyLLM4TlKmBpOGsrR7XBAxSmd4cT33AOgZVeL7P4at3D/a3vmRpv9SiG2Ucu5LiARirHaHcSAdTG6jH3+TuciTKvb8ETBMLUU3GVsEY=,iv:9nD5gcbLL7bgxme3F/IOBho9HVDjffjlCY1beN+lHTE=,tag:SlhbgWJO42nRAJ1YDb9F9g==,type:str]
    encrypted_regex: ^(data|stringData|parameters)$
    version: 3.10.2
