apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-shared
  target:
    name: openclaw-api-keys
    creationPolicy: Owner
    template:
      data:
        ANTHROPIC_API_KEY: "{{ .ANTHROPIC_API_KEY }}"
        NPM_CONFIG_CACHE: "/home/openclaw/.openclaw/.npm"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        TELEGRAM_BOT_TOKEN: "{{ .TELEGRAM_BOT_TOKEN }}"
  data:
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: "openclaw-api-keys/ANTHROPIC_API_KEY"
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: "openclaw-api-keys/OPENAI_API_KEY"
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: "openclaw-api-keys/TELEGRAM_BOT_TOKEN"
