apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-secrets
    namespace: openclaw
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:hMGibCO7hRwrj7o3OOZDM0VP/0BTB2+/lHHhtuq3ZGh0NwFg/wVMSQ==,iv:5aAyktDsKPjeasDu41KjpOJKfvQ6EdAuEAGMMjcS0i8=,tag:FJoNG+KG1y2YvX+dflBeSw==,type:str]
    MATRIX_ROOM_ID: ENC[AES256_GCM,data:WiZNMwOk9vAN8nlJ5BHYqqjo6HGV35pOpKUyow==,iv:xoU/BDzLrH/7ZG6XBDMXIWGJc5wUe0eDteWeyRHpMdE=,tag:2rrmJqGRoJyqQa9TRZWnfA==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMTY3d3pjTXlzRllwdERo
            WHdDMUZValVmOVpZRThJczVKYVhibDFDYkU0CmYzYmNEbUEvT1Bacm91WkdMaEVP
            T090Z1oyUERxYXVlQW9RVW41eDF2MFEKLS0tIElLSjlpdlE3dlBDZXlkd1FBeGFF
            dm1FdTNkRU41RjFldGgyUU1WY2ZObDgKK4RNj8QYWSNBXkpMdx6v62CdOQagTH6/
            7cLN/LTE93qZtuXbStwZJLGz2ZWdVJGTbeyXz1CH7mqc3gvna+Trhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T04:18:06Z"
    mac: ENC[AES256_GCM,data:71m54lte9/YwSoTddawMaALPwL63ifXHdHG+74LAhvHseg+/QNTv8YkQTwpswvDzuePbLvjvh3FHZhaipiRavJnGJewypzxZ5+5GcnSLs8Xuv9HcX7DdJvJ90gdgWd/9C8MLVdUxQrzXgVoyF9HWMoC+gZqqge5b4PU6XdgkPXU=,iv:tJqPkzK6x1z4o6ZKcamcgfUkhPvDkkw6C+N/FWVo3yI=,tag:SNeuhCu8uXrBCSG+AOEiIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
