apiVersion: v1
kind: Secret
metadata:
    name: openclaw-matrix-secrets
    namespace: openclaw
stringData:
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:almI7A3Wa5X18heV/n4Qg3q1Rxtto5ppWu6P4uQEZgpPvUaX82cN2Q==,iv:jxYPMGQIugxMwk3f5wUmdr6QaXO0kJek0NkGTuW2Lm8=,tag:v72eE+ozPwVQ6RgLSAdpOw==,type:str]
    MATRIX_ROOM_ID: ENC[AES256_GCM,data:WiZNMwOk9vAN8nlJ5BHYqqjo6HGV35pOpKUyow==,iv:xoU/BDzLrH/7ZG6XBDMXIWGJc5wUe0eDteWeyRHpMdE=,tag:2rrmJqGRoJyqQa9TRZWnfA==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:mjUqbzqFAo4tMck2ZSA9BWk=,iv:NQ016KHGTAcABbj7JNmyS9aH6RM1OwWOhM3pVu+XBe4=,tag:9OYIEAVFFBqOWWgiLTbGmQ==,type:str]
sops:
    age:
        - recipient: age16krjysalsq26mfndnthd9r42thapj43a0zdndgrrz30utzuhwd0q7fxh9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMTY3d3pjTXlzRllwdERo
            WHdDMUZValVmOVpZRThJczVKYVhibDFDYkU0CmYzYmNEbUEvT1Bacm91WkdMaEVP
            T090Z1oyUERxYXVlQW9RVW41eDF2MFEKLS0tIElLSjlpdlE3dlBDZXlkd1FBeGFF
            dm1FdTNkRU41RjFldGgyUU1WY2ZObDgKK4RNj8QYWSNBXkpMdx6v62CdOQagTH6/
            7cLN/LTE93qZtuXbStwZJLGz2ZWdVJGTbeyXz1CH7mqc3gvna+Trhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T01:00:43Z"
    mac: ENC[AES256_GCM,data:x5TUZJ6QtnnqKwnPeVXarONTRaMp9g7IQApDDSLLiFi7xgLKFZ/cRJPhH5V5IZaptquMFW1eiad+A0+ny00a3Y1nN94h7dYWqgrguiGjpt7AnhD/b+FnVkYggX4i4OILskwo0t757tL6YAK9HdhTTZBIMnhTelbz8uBBdjLYiX0=,iv:uxiA7eW+Dq2GINdSuny1KS0RYqrWuaahcLPQpzt1pQk=,tag:pobpahbcqT8boKWmhGI0/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
